Quake II RTX doxygen: C:/entry/dev/Q2RTX/src/common/math.c File Reference
math.c File Reference
#include "shared/shared.h"
#include "common/math.h"
Macros
#define P(i, j, k)
Functions
int DirToByte (const vec3_t dir)
void SetPlaneType (cplane_t *plane)
void SetPlaneSignbits (cplane_t *plane)
int BoxOnPlaneSide (vec3_t emins, vec3_t emaxs, cplane_t *p)
void RotatePointAroundVector (vec3_t dst, const vec3_t dir, const vec3_t point, float degrees)
void SetupRotationMatrix (vec3_t matrix[3], const vec3_t dir, float degrees)
Variables
const vec3_t bytedirs [NUMVERTEXNORMALS]
Macro Definition Documentation
P
#define P (i, j, k)
Value:
    p->normal[0] * bounds[i][0] + \
    p->normal[1] * bounds[j][1] + \
    p->normal[2] * bounds[k][2]
Function Documentation
BoxOnPlaneSide()
int BoxOnPlaneSide (vec3_t emins, vec3_t emaxs, cplane_t * p)
Definition at line 322 of file math.c.
 {
     vec_t   *bounds[2] = { emins, emaxs };
     int     i = p->signbits & 1;
     int     j = (p->signbits >> 1) & 1;
     int     k = (p->signbits >> 2) & 1;
 #define P(i, j, k) \
     p->normal[0] * bounds[i][0] + \
     p->normal[1] * bounds[j][1] + \
     p->normal[2] * bounds[k][2]
     vec_t   dist1 = P(i ^ 1, j ^ 1, k ^ 1);
     vec_t   dist2 = P(i, j, k);
     int     sides = 0;
 #undef P
     if (dist1 >= p->dist)
         sides = BOX_INFRONT;
     if (dist2 < p->dist)
         sides |= BOX_BEHIND;
     return sides;
 }
Referenced by GL_ClipNode(), and GL_CullBox().
DirToByte()
int DirToByte (const vec3_t dir)
Definition at line 245 of file math.c.
 {
     int     i, best;
     float   d, bestd;
     if (!dir) {
         return 0;
     }
     bestd = 0;
     best = 0;
     for (i = 0; i < NUMVERTEXNORMALS; i++) {
         d = DotProduct(dir, bytedirs[i]);
         if (d > bestd) {
             bestd = d;
             best = i;
         }
     }
     return best;
 }
Referenced by MSG_WriteDir().
RotatePointAroundVector()
void RotatePointAroundVector (vec3_t dst, const vec3_t dir, const vec3_t point, float degrees)
Definition at line 348 of file math.c.
 {
     vec3_t  matrix[3];
     SetupRotationMatrix(matrix, dir, degrees);
     dst[0] = DotProduct(matrix[0], point);
     dst[1] = DotProduct(matrix[1], point);
     dst[2] = DotProduct(matrix[2], point);
 }
Referenced by R_DrawBeam().
SetPlaneSignbits()
void SetPlaneSignbits (cplane_t * plane)
Definition at line 298 of file math.c.
 {
     int bits = 0;
     if (plane->normal[0] < 0) {
         bits |= 1;
     }
     if (plane->normal[1] < 0) {
         bits |= 2;
     }
     if (plane->normal[2] < 0) {
         bits |= 4;
     }
     plane->signbits = bits;
 }
Referenced by GL_SetupFrustum(), and LOAD().
SetPlaneType()
void SetPlaneType (cplane_t * plane)
Definition at line 278 of file math.c.
 {
     vec_t *normal = plane->normal;
     if (normal[0] == 1) {
         plane->type = PLANE_X;
         return;
     }
     if (normal[1] == 1) {
         plane->type = PLANE_Y;
         return;
     }
     if (normal[2] == 1) {
         plane->type = PLANE_Z;
         return;
     }
     plane->type = PLANE_NON_AXIAL;
 }
Referenced by LOAD().
SetupRotationMatrix()
void SetupRotationMatrix (vec3_t matrix[3], const vec3_t dir, float degrees)
Definition at line 367 of file math.c.
 {
     vec_t   angle, s, c, one_c, xx, yy, zz, xy, yz, zx, xs, ys, zs;
     angle = DEG2RAD(degrees);
     s = sin(angle);
     c = cos(angle);
     one_c = 1.0F - c;
     xx = dir[0] * dir[0];
     yy = dir[1] * dir[1];
     zz = dir[2] * dir[2];
     xy = dir[0] * dir[1];
     yz = dir[1] * dir[2];
     zx = dir[2] * dir[0];
     xs = dir[0] * s;
     ys = dir[1] * s;
     zs = dir[2] * s;
     matrix[0][0] = (one_c * xx) + c;
     matrix[0][1] = (one_c * xy) - zs;
     matrix[0][2] = (one_c * zx) + ys;
     matrix[1][0] = (one_c * xy) + zs;
     matrix[1][1] = (one_c * yy) + c;
     matrix[1][2] = (one_c * yz) - xs;
     matrix[2][0] = (one_c * zx) - ys;
     matrix[2][1] = (one_c * yz) + xs;
     matrix[2][2] = (one_c * zz) + c;
 }
Referenced by prepare_sky_matrix(), R_AddSkySurface(), and RotatePointAroundVector().
Variable Documentation
bytedirs
const vec3_t bytedirs[NUMVERTEXNORMALS]
Definition at line 80 of file math.c.
Referenced by CL_BfgParticles(), CL_FlyParticles(), DirToByte(), GL_InitTables(), MOD_LoadMD2_RTX(), MSG_ReadDir(), and R_AliasTransformFinalVerts().