Quake II RTX doxygen: C:/entry/dev/Q2RTX/src/client/ui/ui.h File Reference
ui.h File Reference
#include "shared/shared.h"
#include "shared/list.h"
#include "common/cmd.h"
#include "common/common.h"
#include "common/cvar.h"
#include "common/field.h"
#include "common/zone.h"
#include "client/keys.h"
#include "client/sound/sound.h"
#include "client/client.h"
#include "client/ui.h"
#include "refresh/refresh.h"
Classes
struct menuCondition_s
struct menuFrameWork_s
struct menuCommon_s
struct menuField_s
struct menuSlider_s
struct menuListColumn_s
struct menuList_s
struct menuSpinControl_s
struct menuAction_s
struct menuSeparator_s
struct menuStatic_s
struct menuBitmap_s
struct menuKeybind_s
struct playerModelInfo_s
struct uiStatic_s
Macros
#define UI_Malloc(s) Z_TagMalloc(s, TAG_UI)
#define UI_Mallocz(s) Z_TagMallocz(s, TAG_UI)
#define UI_CopyString(s) Z_TagCopyString(s, TAG_UI)
#define MAXMENUITEMS 64
#define QMF_LEFT_JUSTIFY 0x00000001
#define QMF_GRAYED 0x00000002
#define QMF_NUMBERSONLY 0x00000004
#define QMF_HASFOCUS 0x00000008
#define QMF_HIDDEN 0x00000010
#define QMF_DISABLED 0x00000020
#define QMF_CUSTOM_COLOR 0x00000040
#define RCOLUMN_OFFSET (CHAR_WIDTH * 2)
#define LCOLUMN_OFFSET -RCOLUMN_OFFSET
#define GENERIC_SPACING(x) ((x) + (x) / 4)
#define MENU_SPACING GENERIC_SPACING(CHAR_HEIGHT)
#define DOUBLE_CLICK_DELAY 300
#define UI_IsItemSelectable(item)
#define SLIDER_RANGE 10
#define MAX_COLUMNS 8
#define MLIST_SPACING GENERIC_SPACING(CHAR_HEIGHT)
#define MLIST_BORDER_WIDTH 1
#define MLIST_SCROLLBAR_WIDTH GENERIC_SPACING(CHAR_WIDTH)
#define MLIST_PRESTEP 3
#define MLIST_PADDING (MLIST_PRESTEP*2)
#define MLF_HEADER 0x00000001
#define MLF_SCROLLBAR 0x00000002
#define MLF_COLOR 0x00000004
#define MAX_PLAYERMODELS 1024
#define MAX_MENU_DEPTH 8
#define CURSOR_WIDTH 32
#define CURSOR_OFFSET 25
#define NUM_CURSOR_FRAMES 15
Typedefs
typedef void(* confirmAction_t) (qboolean)
typedef struct menuCondition_s menuCondition_t
typedef struct menuFrameWork_s menuFrameWork_t
typedef struct menuCommon_s menuCommon_t
typedef struct menuField_s menuField_t
typedef struct menuSlider_s menuSlider_t
typedef struct menuListColumn_s menuListColumn_t
typedef struct menuList_s menuList_t
typedef struct menuSpinControl_s menuSpinControl_t
typedef struct menuAction_s menuAction_t
typedef struct menuSeparator_s menuSeparator_t
typedef struct menuStatic_s menuStatic_t
typedef struct menuBitmap_s menuBitmap_t
typedef struct menuKeybind_s menuKeybind_t
typedef struct playerModelInfo_s playerModelInfo_t
typedef struct uiStatic_s uiStatic_t
Enumerations
enum menuType_t {
MTYPE_BAD, MTYPE_SLIDER, MTYPE_LIST, MTYPE_ACTION,
MTYPE_SPINCONTROL, MTYPE_SEPARATOR, MTYPE_FIELD, MTYPE_BITFIELD,
MTYPE_PAIRS, MTYPE_STRINGS, MTYPE_VALUES, MTYPE_TOGGLE,
MTYPE_STATIC, MTYPE_KEYBIND, MTYPE_BITMAP, MTYPE_SAVEGAME,
MTYPE_LOADGAME
}
enum menuSound_t {
QMS_NOTHANDLED, QMS_SILENT, QMS_IN, QMS_MOVE,
QMS_OUT, QMS_BEEP
}
Functions
void PlayerModel_Load (void)
void PlayerModel_Free (void)
void UI_PushMenu (menuFrameWork_t *menu)
void UI_ForceMenuOff (void)
void UI_PopMenu (void)
void UI_StartSound (menuSound_t sound)
qboolean UI_DoHitTest (void)
qboolean UI_CursorInRect (vrect_t *rect)
void * UI_FormatColumns (int extrasize,...) q_sentinel
char * UI_GetColumn (char *s, int n)
void UI_DrawString (int x, int y, int flags, const char *string)
void UI_DrawChar (int x, int y, int flags, int ch)
void UI_DrawRect8 (const vrect_t *rect, int border, int c)
void UI_StringDimensions (vrect_t *rc, int flags, const char *string)
void UI_LoadScript (void)
menuFrameWork_t * UI_FindMenu (const char *name)
void Menu_Init (menuFrameWork_t *menu)
void Menu_Size (menuFrameWork_t *menu)
void Menu_Draw (menuFrameWork_t *menu)
void Menu_AddItem (menuFrameWork_t *menu, void *item)
menuSound_t Menu_SelectItem (menuFrameWork_t *menu)
menuSound_t Menu_SlideItem (menuFrameWork_t *menu, int dir)
menuSound_t Menu_KeyEvent (menuCommon_t *item, int key)
menuSound_t Menu_CharEvent (menuCommon_t *item, int key)
menuSound_t Menu_MouseMove (menuCommon_t *item)
menuSound_t Menu_Keydown (menuFrameWork_t *menu, int key)
void Menu_SetFocus (menuCommon_t *item)
menuSound_t Menu_AdjustCursor (menuFrameWork_t *menu, int dir)
menuCommon_t * Menu_ItemAtCursor (menuFrameWork_t *menu)
menuCommon_t * Menu_HitTest (menuFrameWork_t *menu)
void MenuList_Init (menuList_t *l)
void MenuList_SetValue (menuList_t *l, int value)
void MenuList_Sort (menuList_t *l, int offset, int(*cmpfunc)(const void *, const void *))
void SpinControl_Init (menuSpinControl_t *s)
qboolean Menu_Push (menuFrameWork_t *menu)
void Menu_Pop (menuFrameWork_t *menu)
void Menu_Free (menuFrameWork_t *menu)
void M_Menu_PlayerConfig (void)
void M_Menu_Demos (void)
void M_Menu_Servers (void)
Variables
uiStatic_t uis
list_t ui_menus
cvar_t * ui_debug
Macro Definition Documentation
CURSOR_OFFSET
#define CURSOR_OFFSET 25
Definition at line 285 of file ui.h.
CURSOR_WIDTH
#define CURSOR_WIDTH 32
Definition at line 284 of file ui.h.
DOUBLE_CLICK_DELAY
#define DOUBLE_CLICK_DELAY 300
Definition at line 83 of file ui.h.
GENERIC_SPACING
#define GENERIC_SPACING (x) ((x) + (x) / 4)
Definition at line 79 of file ui.h.
LCOLUMN_OFFSET
#define LCOLUMN_OFFSET -RCOLUMN_OFFSET
Definition at line 77 of file ui.h.
MAX_COLUMNS
#define MAX_COLUMNS 8
Definition at line 185 of file ui.h.
MAX_MENU_DEPTH
#define MAX_MENU_DEPTH 8
Definition at line 281 of file ui.h.
MAX_PLAYERMODELS
#define MAX_PLAYERMODELS 1024
Definition at line 270 of file ui.h.
MAXMENUITEMS
#define MAXMENUITEMS 64
Definition at line 37 of file ui.h.
MENU_SPACING
#define MENU_SPACING GENERIC_SPACING(CHAR_HEIGHT)
Definition at line 81 of file ui.h.
MLF_COLOR
#define MLF_COLOR 0x00000004
Definition at line 195 of file ui.h.
MLF_HEADER
#define MLF_HEADER 0x00000001
Definition at line 193 of file ui.h.
MLF_SCROLLBAR
#define MLF_SCROLLBAR 0x00000002
Definition at line 194 of file ui.h.
MLIST_BORDER_WIDTH
#define MLIST_BORDER_WIDTH 1
Definition at line 188 of file ui.h.
MLIST_PADDING
#define MLIST_PADDING (MLIST_PRESTEP*2)
Definition at line 191 of file ui.h.
MLIST_PRESTEP
#define MLIST_PRESTEP 3
Definition at line 190 of file ui.h.
MLIST_SCROLLBAR_WIDTH
#define MLIST_SCROLLBAR_WIDTH GENERIC_SPACING(CHAR_WIDTH)
Definition at line 189 of file ui.h.
MLIST_SPACING
#define MLIST_SPACING GENERIC_SPACING(CHAR_HEIGHT)
Definition at line 187 of file ui.h.
NUM_CURSOR_FRAMES
#define NUM_CURSOR_FRAMES 15
Definition at line 287 of file ui.h.
QMF_CUSTOM_COLOR
#define QMF_CUSTOM_COLOR 0x00000040
Definition at line 65 of file ui.h.
QMF_DISABLED
#define QMF_DISABLED 0x00000020
Definition at line 64 of file ui.h.
QMF_GRAYED
#define QMF_GRAYED 0x00000002
Definition at line 60 of file ui.h.
QMF_HASFOCUS
#define QMF_HASFOCUS 0x00000008
Definition at line 62 of file ui.h.
QMF_HIDDEN
#define QMF_HIDDEN 0x00000010
Definition at line 63 of file ui.h.
QMF_LEFT_JUSTIFY
#define QMF_LEFT_JUSTIFY 0x00000001
Definition at line 59 of file ui.h.
QMF_NUMBERSONLY
#define QMF_NUMBERSONLY 0x00000004
Definition at line 61 of file ui.h.
RCOLUMN_OFFSET
#define RCOLUMN_OFFSET (CHAR_WIDTH * 2)
Definition at line 76 of file ui.h.
SLIDER_RANGE
#define SLIDER_RANGE 10
Definition at line 170 of file ui.h.
UI_CopyString
#define UI_CopyString (s) Z_TagCopyString(s, TAG_UI)
Definition at line 35 of file ui.h.
UI_IsItemSelectable
#define UI_IsItemSelectable (item)
Value:
    ((item)->type != MTYPE_SEPARATOR && \
     (item)->type != MTYPE_STATIC && \
     !((item)->flags & (QMF_GRAYED | QMF_HIDDEN | QMF_DISABLED)))
Definition at line 85 of file ui.h.
UI_Malloc
#define UI_Malloc (s) Z_TagMalloc(s, TAG_UI)
Definition at line 33 of file ui.h.
UI_Mallocz
#define UI_Mallocz (s) Z_TagMallocz(s, TAG_UI)
Definition at line 34 of file ui.h.
Typedef Documentation
confirmAction_t
typedef void(* confirmAction_t) (qboolean)
Definition at line 90 of file ui.h.
menuAction_t
typedef struct menuAction_s menuAction_t
menuBitmap_t
typedef struct menuBitmap_s menuBitmap_t
menuCommon_t
typedef struct menuCommon_s menuCommon_t
menuCondition_t
typedef struct menuCondition_s menuCondition_t
menuField_t
typedef struct menuField_s menuField_t
menuFrameWork_t
typedef struct menuFrameWork_s menuFrameWork_t
menuKeybind_t
typedef struct menuKeybind_s menuKeybind_t
menuList_t
typedef struct menuList_s menuList_t
menuListColumn_t
typedef struct menuListColumn_s menuListColumn_t
menuSeparator_t
typedef struct menuSeparator_s menuSeparator_t
menuSlider_t
typedef struct menuSlider_s menuSlider_t
menuSpinControl_t
typedef struct menuSpinControl_s menuSpinControl_t
menuStatic_t
typedef struct menuStatic_s menuStatic_t
playerModelInfo_t
typedef struct playerModelInfo_s playerModelInfo_t
uiStatic_t
typedef struct uiStatic_s uiStatic_t
Enumeration Type Documentation
menuSound_t
enum menuSound_t
Enumerator
QMS_NOTHANDLED
QMS_SILENT
QMS_IN
QMS_MOVE
QMS_OUT
QMS_BEEP
Definition at line 67 of file ui.h.
              {
     QMS_NOTHANDLED,
     QMS_SILENT,
     QMS_IN,
     QMS_MOVE,
     QMS_OUT,
     QMS_BEEP
 } menuSound_t;
menuType_t
enum menuType_t
Enumerator
MTYPE_BAD
MTYPE_SLIDER
MTYPE_LIST
MTYPE_ACTION
MTYPE_SPINCONTROL
MTYPE_SEPARATOR
MTYPE_FIELD
MTYPE_BITFIELD
MTYPE_PAIRS
MTYPE_STRINGS
MTYPE_VALUES
MTYPE_TOGGLE
MTYPE_STATIC
MTYPE_KEYBIND
MTYPE_BITMAP
MTYPE_SAVEGAME
MTYPE_LOADGAME
Definition at line 39 of file ui.h.
              {
     MTYPE_BAD,
     MTYPE_SLIDER,
     MTYPE_LIST,
     MTYPE_ACTION,
     MTYPE_SPINCONTROL,
     MTYPE_SEPARATOR,
     MTYPE_FIELD,
     MTYPE_BITFIELD,
     MTYPE_PAIRS,
     MTYPE_STRINGS,
     MTYPE_VALUES,
     MTYPE_TOGGLE,
     MTYPE_STATIC,
     MTYPE_KEYBIND,
     MTYPE_BITMAP,
     MTYPE_SAVEGAME,
     MTYPE_LOADGAME
 } menuType_t;
Function Documentation
M_Menu_Demos()
void M_Menu_Demos (void)
Definition at line 636 of file demos.c.
 {
     ui_sortdemos = Cvar_Get("ui_sortdemos", "1", 0);
     ui_sortdemos->changed = ui_sortdemos_changed;
     ui_listalldemos = Cvar_Get("ui_listalldemos", "0", 0);
     m_demos.menu.name = "demos";
     m_demos.menu.title = "Demo Browser";
     strcpy(m_demos.browse, "/demos");
     m_demos.menu.draw       = Draw;
     m_demos.menu.expose     = Expose;
     m_demos.menu.pop        = Pop;
     m_demos.menu.size       = Size;
     m_demos.menu.keydown    = Keydown;
     m_demos.menu.free       = Free;
     m_demos.menu.image      = uis.backgroundHandle;
     m_demos.menu.color.u32  = uis.color.background.u32;
     m_demos.menu.transparent    = uis.transparent;
     m_demos.list.generic.type   = MTYPE_LIST;
     m_demos.list.generic.flags  = QMF_HASFOCUS;
     m_demos.list.generic.activate = Activate;
     m_demos.list.generic.change = Change;
     m_demos.list.numcolumns     = COL_MAX;
     m_demos.list.sortdir        = 1;
     m_demos.list.sortcol        = COL_NAME;
     m_demos.list.extrasize      = DEMO_EXTRASIZE;
     m_demos.list.sort           = Sort;
     m_demos.list.mlFlags        = MLF_HEADER | MLF_SCROLLBAR;
     m_demos.list.columns[0].name    = m_demos.browse;
     m_demos.list.columns[0].uiFlags = UI_LEFT;
     m_demos.list.columns[1].name    = "Date";
     m_demos.list.columns[1].uiFlags = UI_CENTER;
     m_demos.list.columns[2].name    = "Size";
     m_demos.list.columns[2].uiFlags = UI_RIGHT;
     m_demos.list.columns[3].name    = "Map";
     m_demos.list.columns[3].uiFlags = UI_CENTER;
     m_demos.list.columns[4].name    = "POV";
     m_demos.list.columns[4].uiFlags = UI_CENTER;
     ui_sortdemos_changed(ui_sortdemos);
     Menu_AddItem(&m_demos.menu, &m_demos.list);
     List_Append(&ui_menus, &m_demos.menu.entry);
 }
Referenced by UI_Init().
M_Menu_PlayerConfig()
void M_Menu_PlayerConfig (void)
Definition at line 322 of file playerconfig.c.
 {
     static const vec3_t origin = { 40.0f, 0.0f, 0.0f };
     static const vec3_t angles = { 0.0f, 260.0f, 0.0f };
     m_player.menu.name = "players";
     m_player.menu.push = Push;
     m_player.menu.pop = Pop;
     m_player.menu.size = Size;
     m_player.menu.draw = Draw;
     m_player.menu.free = Free;
     m_player.menu.image = uis.backgroundHandle;
     if (vid_rtx->integer)
     {
         // Q2RTX: make the player menu transparent so that we can see
         // the model below: all 2D stuff is rendered after 3D, in stretch_pics.
         m_player.menu.color.u32 = 0;
     }
     else
     {
         m_player.menu.color.u32 = MakeColor(0, 0, 0, 255);
     }
     m_player.menu.transparent = uis.transparent;
     m_player.entities[0].flags = RF_FULLBRIGHT;
     m_player.entities[0].id = 1; // Q2RTX: add entity id to fix motion vectors
     VectorCopy(angles, m_player.entities[0].angles);
     VectorCopy(origin, m_player.entities[0].origin);
     VectorCopy(origin, m_player.entities[0].oldorigin);
     m_player.entities[1].flags = RF_FULLBRIGHT;
     m_player.entities[1].id = 2; // Q2RTX: add entity id to fix motion vectors
     VectorCopy(angles, m_player.entities[1].angles);
     VectorCopy(origin, m_player.entities[1].origin);
     VectorCopy(origin, m_player.entities[1].oldorigin);
     m_player.refdef.num_entities = 0;
     m_player.refdef.entities = m_player.entities;
     m_player.refdef.rdflags = RDF_NOWORLDMODEL;
     if (vid_rtx->integer)
     {
         m_player.refdef.num_dlights = sizeof(dlights) / sizeof(*dlights);
         m_player.refdef.dlights = dlights;
     }
     else
     {
         m_player.refdef.num_dlights = 0;
     }
     m_player.name.generic.type = MTYPE_FIELD;
     m_player.name.generic.flags = QMF_HASFOCUS;
     m_player.name.generic.name = "name";
     m_player.name.width = MAX_CLIENT_NAME - 1;
     m_player.model.generic.type = MTYPE_SPINCONTROL;
     m_player.model.generic.id = ID_MODEL;
     m_player.model.generic.name = "model";
     m_player.model.generic.change = Change;
     m_player.skin.generic.type = MTYPE_SPINCONTROL;
     m_player.skin.generic.id = ID_SKIN;
     m_player.skin.generic.name = "skin";
     m_player.skin.generic.change = Change;
     m_player.hand.generic.type = MTYPE_SPINCONTROL;
     m_player.hand.generic.name = "handedness";
     m_player.hand.itemnames = (char **)handedness;
     m_player.view.generic.type = MTYPE_SPINCONTROL;
     m_player.view.generic.name = "view";
     m_player.view.itemnames = (char **)viewmodes;
     Menu_AddItem(&m_player.menu, &m_player.name);
     Menu_AddItem(&m_player.menu, &m_player.model);
     Menu_AddItem(&m_player.menu, &m_player.skin);
     Menu_AddItem(&m_player.menu, &m_player.hand);
     Menu_AddItem(&m_player.menu, &m_player.view);
     List_Append(&ui_menus, &m_player.menu.entry);
 }
Referenced by UI_Init().
M_Menu_Servers()
void M_Menu_Servers (void)
Definition at line 1073 of file servers.c.
 {
     ui_sortservers = Cvar_Get("ui_sortservers", "0", 0);
     ui_sortservers->changed = ui_sortservers_changed;
     ui_colorservers = Cvar_Get("ui_colorservers", "0", 0);
     ui_colorservers->changed = ui_colorservers_changed;
     ui_pingrate = Cvar_Get("ui_pingrate", "0", 0);
     m_servers.menu.name     = "servers";
     m_servers.menu.title    = "Server Browser";
     m_servers.menu.draw         = Draw;
     m_servers.menu.expose       = Expose;
     m_servers.menu.push         = Push;
     m_servers.menu.pop          = Pop;
     m_servers.menu.size         = Size;
     m_servers.menu.keydown      = Keydown;
     m_servers.menu.free         = Free;
     m_servers.menu.image        = uis.backgroundHandle;
     m_servers.menu.color.u32    = uis.color.background.u32;
     m_servers.menu.transparent  = uis.transparent;
 //
 // server list
 //
     m_servers.list.generic.type         = MTYPE_LIST;
     m_servers.list.generic.flags        = QMF_LEFT_JUSTIFY | QMF_HASFOCUS;
     m_servers.list.generic.activate     = Connect;
     m_servers.list.generic.change       = Change;
     m_servers.list.items                = m_servers.names;
     m_servers.list.numcolumns           = COL_MAX;
     m_servers.list.sortdir              = 1;
     m_servers.list.sortcol              = -1;
     m_servers.list.sort                 = Sort;
     m_servers.list.extrasize            = SLOT_EXTRASIZE;
     m_servers.list.mlFlags              = MLF_HEADER | MLF_SCROLLBAR;
     m_servers.list.columns[0].uiFlags   = UI_LEFT;
     m_servers.list.columns[0].name      = "Hostname";
     m_servers.list.columns[1].uiFlags   = UI_CENTER;
     m_servers.list.columns[1].name      = "Mod";
     m_servers.list.columns[2].uiFlags   = UI_CENTER;
     m_servers.list.columns[2].name      = "Map";
     m_servers.list.columns[3].uiFlags   = UI_CENTER;
     m_servers.list.columns[3].name      = "Players";
     m_servers.list.columns[4].uiFlags   = UI_RIGHT;
     m_servers.list.columns[4].name      = "RTT";
     ui_colorservers_changed(ui_colorservers);
 //
 // server info
 //
     m_servers.info.generic.type         = MTYPE_LIST;
     m_servers.info.generic.flags        = QMF_LEFT_JUSTIFY | QMF_HIDDEN;
     m_servers.info.generic.activate     = Connect;
     m_servers.info.numcolumns           = 2;
     m_servers.info.mlFlags              = MLF_HEADER | MLF_SCROLLBAR;
     m_servers.info.columns[0].uiFlags   = UI_LEFT;
     m_servers.info.columns[0].name      = "Key";
     m_servers.info.columns[1].uiFlags   = UI_LEFT;
     m_servers.info.columns[1].name      = "Value";
 //
 // player list
 //
     m_servers.players.generic.type      = MTYPE_LIST;
     m_servers.players.generic.flags     = QMF_LEFT_JUSTIFY | QMF_HIDDEN;
     m_servers.players.generic.activate  = Connect;
     m_servers.players.numcolumns        = 3;
     m_servers.players.mlFlags           = MLF_HEADER;
     m_servers.players.columns[0].uiFlags    = UI_RIGHT;
     m_servers.players.columns[0].name       = "Frg";
     m_servers.players.columns[1].uiFlags    = UI_RIGHT;
     m_servers.players.columns[1].name       = "RTT";
     m_servers.players.columns[2].uiFlags    = UI_LEFT;
     m_servers.players.columns[2].name       = "Name";
     Menu_AddItem(&m_servers.menu, &m_servers.list);
     Menu_AddItem(&m_servers.menu, &m_servers.info);
     Menu_AddItem(&m_servers.menu, &m_servers.players);
     List_Append(&ui_menus, &m_servers.menu.entry);
 }
Referenced by UI_Init().
Menu_AddItem()
void Menu_AddItem (menuFrameWork_t * menu, void * item)
Definition at line 1785 of file menu.c.
 {
     if (menu->nitems >= MAXMENUITEMS) {
         Com_Error(ERR_FATAL, "Menu_AddItem: too many items");
     }
     menu->items[menu->nitems++] = item;
     ((menuCommon_t *)item)->parent = menu;
     ((menuCommon_t *)item)->condition = menu->current_condition;
 }
Referenced by M_Menu_Demos(), M_Menu_PlayerConfig(), M_Menu_Servers(), Parse_Action(), Parse_Bind(), Parse_Bitmap(), Parse_Blank(), Parse_Field(), Parse_Pairs(), Parse_Range(), Parse_Savegame(), Parse_Spin(), and Parse_Toggle().
Menu_AdjustCursor()
menuSound_t Menu_AdjustCursor (menuFrameWork_t * menu, int dir)
Definition at line 2101 of file menu.c.
 {
     menuCommon_t *item;
     int cursor, pos;
     int i;
     pos = 0;
     for (i = 0; i < m->nitems; i++) {
         item = (menuCommon_t *)m->items[i];
         if (item->flags & QMF_HASFOCUS) {
             pos = i;
             break;
         }
     }
     /*
     ** crawl in the direction indicated until we find a valid spot
     */
     cursor = pos;
     if (dir == 1) {
         do {
             cursor++;
             if (cursor >= m->nitems)
                 cursor = 0;
             item = (menuCommon_t *)m->items[cursor];
             if (UI_IsItemSelectable(item))
                 break;
         } while (cursor != pos);
     } else {
         do {
             cursor--;
             if (cursor < 0)
                 cursor = m->nitems - 1;
             item = (menuCommon_t *)m->items[cursor];
             if (UI_IsItemSelectable(item))
                 break;
         } while (cursor != pos);
     }
     Menu_SetFocus(item);
     return QMS_MOVE;
 }
Referenced by Menu_DefaultKey().
Menu_CharEvent()
menuSound_t Menu_CharEvent (menuCommon_t * item, int key)
Definition at line 2376 of file menu.c.
 {
     switch (item->type) {
     case MTYPE_FIELD:
         return Field_Char((menuField_t *)item, key);
     default:
         return QMS_NOTHANDLED;
     }
 }
Referenced by UI_CharEvent().
Menu_Draw()
void Menu_Draw (menuFrameWork_t * menu)
Definition at line 2196 of file menu.c.
 {
     void *item;
     int i;
 //
 // draw background
 //
     if (menu->image) {
         R_DrawStretchPic(0, menu->y1, uis.width,
                          menu->y2 - menu->y1, menu->image);
     } else {
         R_DrawFill32(0, menu->y1, uis.width,
                      menu->y2 - menu->y1, menu->color.u32);
     }
 //
 // draw title bar
 //
     if (menu->title) {
         UI_DrawString(uis.width / 2, menu->y1,
                       UI_CENTER | UI_ALTCOLOR, menu->title);
     }
 //
 // draw banner, plaque and logo
 //
     if (menu->banner) {
         R_DrawPic(menu->banner_rc.x, menu->banner_rc.y, menu->banner);
     }
     if (menu->plaque) {
         R_DrawPic(menu->plaque_rc.x, menu->plaque_rc.y, menu->plaque);
     }
     if (menu->logo) {
         R_DrawPic(menu->logo_rc.x, menu->logo_rc.y, menu->logo);
     }
     if (menu->footer) {
         R_DrawStretchPic(menu->footer_rc.x, menu->footer_rc.y, menu->footer_rc.width, menu->footer_rc.height, menu->footer);
     }
 //
 // draw contents
 //
     for (i = 0; i < menu->nitems; i++) {
         item = menu->items[i];
         if (((menuCommon_t *)item)->flags & QMF_HIDDEN) {
             continue;
         }
         switch (((menuCommon_t *)item)->type) {
         case MTYPE_FIELD:
             Field_Draw(item);
             break;
         case MTYPE_SLIDER:
             Slider_Draw(item);
             break;
         case MTYPE_LIST:
             MenuList_Draw(item);
             break;
         case MTYPE_SPINCONTROL:
         case MTYPE_BITFIELD:
         case MTYPE_PAIRS:
         case MTYPE_VALUES:
         case MTYPE_STRINGS:
         case MTYPE_TOGGLE:
             SpinControl_Draw(item);
             break;
         case MTYPE_ACTION:
         case MTYPE_SAVEGAME:
         case MTYPE_LOADGAME:
             Action_Draw(item);
             break;
         case MTYPE_SEPARATOR:
             Separator_Draw(item);
             break;
         case MTYPE_STATIC:
             Static_Draw(item);
             break;
         case MTYPE_KEYBIND:
             Keybind_Draw(item);
             break;
         case MTYPE_BITMAP:
             Bitmap_Draw(item);
             break;
         default:
             Com_Error(ERR_FATAL, "Menu_Draw: unknown item type");
             break;
         }
         if (ui_debug->integer) {
             UI_DrawRect8(&((menuCommon_t *)item)->rect, 1, 223);
         }
     }
 //
 // draw status bar
 //
     if (menu->status) {
         Menu_DrawStatus(menu);
     }
 }
Referenced by Draw(), and UI_Draw().
Menu_Free()
void Menu_Free (menuFrameWork_t * menu)
Definition at line 2586 of file menu.c.
 {
     void *item;
     int i;
     for (i = 0; i < menu->nitems; i++) {
         item = menu->items[i];
         switch (((menuCommon_t *)item)->type) {
         case MTYPE_ACTION:
         case MTYPE_SAVEGAME:
         case MTYPE_LOADGAME:
             Action_Free(item);
             break;
         case MTYPE_SLIDER:
             Slider_Free(item);
             break;
         case MTYPE_BITFIELD:
         case MTYPE_TOGGLE:
             BitField_Free(item);
             break;
         case MTYPE_PAIRS:
             Pairs_Free(item);
             break;
         case MTYPE_SPINCONTROL:
         case MTYPE_STRINGS:
             SpinControl_Free(item);
             break;
         case MTYPE_KEYBIND:
             Keybind_Free(item);
             break;
         case MTYPE_FIELD:
             Field_Free(item);
             break;
         case MTYPE_SEPARATOR:
             Z_Free(item);
             break;
         case MTYPE_BITMAP:
             Bitmap_Free(item);
             break;
         default:
             break;
         }
     }
     Z_Free(menu->title);
     Z_Free(menu->name);
     Z_Free(menu);
 }
Referenced by Parse_File().
Menu_HitTest()
menuCommon_t* Menu_HitTest (menuFrameWork_t * menu)
Definition at line 2480 of file menu.c.
 {
     int i;
     menuCommon_t *item;
     if (menu->keywait) {
         return NULL;
     }
     for (i = 0; i < menu->nitems; i++) {
         item = menu->items[i];
         if (item->flags & QMF_HIDDEN) {
             continue;
         }
         if (UI_CursorInRect(&item->rect)) {
             return item;
         }
     }
     return NULL;
 }
Referenced by Menu_DefaultKey(), and UI_DoHitTest().
Menu_Init()
void Menu_Init (menuFrameWork_t * menu)
Definition at line 1817 of file menu.c.
 {
     void *item;
     int i;
     int focus = 0;
     vrect_t *rc;
     menu->y1 = 0;
     menu->y2 = uis.height;
     for (i = 0; i < menu->nitems; i++) {
         item = menu->items[i];
         menuCondition_t *condition = &((menuCommon_t*)item)->condition;
         if (condition->cvar)
         {
             qboolean equals = condition->cvar->integer == condition->value;
             if (equals == condition->equals)
                 ((menuCommon_t *)item)->flags &= ~QMF_HIDDEN;
             else
                 ((menuCommon_t *)item)->flags |= QMF_HIDDEN;
         }
     }
     if (!menu->size) {
         menu->size = Menu_Size;
     }
     menu->size(menu);
     for (i = 0; i < menu->nitems; i++) {
         item = menu->items[i];
         focus |= ((menuCommon_t *)item)->flags & QMF_HASFOCUS;
         switch (((menuCommon_t *)item)->type) {
         case MTYPE_FIELD:
             Field_Init(item);
             break;
         case MTYPE_SLIDER:
             Slider_Init(item);
             break;
         case MTYPE_LIST:
             MenuList_Init(item);
             break;
         case MTYPE_SPINCONTROL:
         case MTYPE_BITFIELD:
         case MTYPE_PAIRS:
         case MTYPE_VALUES:
         case MTYPE_STRINGS:
         case MTYPE_TOGGLE:
             SpinControl_Init(item);
             break;
         case MTYPE_ACTION:
         case MTYPE_SAVEGAME:
         case MTYPE_LOADGAME:
             Action_Init(item);
             break;
         case MTYPE_SEPARATOR:
             Separator_Init(item);
             break;
         case MTYPE_STATIC:
             Static_Init(item);
             break;
         case MTYPE_KEYBIND:
             Keybind_Init(item);
             break;
         case MTYPE_BITMAP:
             Bitmap_Init(item);
             break;
         default:
             Com_Error(ERR_FATAL, "Menu_Init: unknown item type");
             break;
         }
     }
     // set focus to the first non-hidden item by default
     if (!focus && menu->nitems) {
         for (i = 0; i < menu->nitems; i++) {
             item = menu->items[i];
             if (!(((menuCommon_t *)item)->flags & QMF_HIDDEN) && (((menuCommon_t *)item)->type != MTYPE_SEPARATOR)) {
                 ((menuCommon_t *)item)->flags |= QMF_HASFOCUS;
                 if (((menuCommon_t *)item)->status) {
                     menu->status = ((menuCommon_t *)item)->status;
                 }
                 break;
             }
         }
     }
     // calc menu bounding box
     UI_ClearBounds(menu->mins, menu->maxs);
     for (i = 0; i < menu->nitems; i++) {
         item = menu->items[i];
         rc = &((menuCommon_t *)item)->rect;
         UI_AddRectToBounds(rc, menu->mins, menu->maxs);
     }
     // expand
     menu->mins[0] -= MENU_SPACING;
     menu->mins[1] -= MENU_SPACING;
     menu->maxs[0] += MENU_SPACING;
     menu->maxs[1] += MENU_SPACING;
     // clamp
     if (menu->mins[0] < 0) menu->mins[0] = 0;
     if (menu->mins[1] < 0) menu->mins[1] = 0;
     if (menu->maxs[0] > uis.width) menu->maxs[0] = uis.width;
     if (menu->maxs[1] > uis.height) menu->maxs[1] = uis.height;
 }
Referenced by UI_PushMenu(), and UI_Resize().
Menu_ItemAtCursor()
menuCommon_t* Menu_ItemAtCursor (menuFrameWork_t * menu)
Definition at line 2042 of file menu.c.
 {
     menuCommon_t *item;
     int i;
     for (i = 0; i < m->nitems; i++) {
         item = m->items[i];
         if (item->flags & QMF_HASFOCUS) {
             return item;
         }
     }
     return NULL;
 }
Referenced by Menu_Keydown(), Menu_SelectItem(), Menu_SlideItem(), and UI_CharEvent().
Menu_Keydown()
menuSound_t Menu_Keydown (menuFrameWork_t * menu, int key)
Definition at line 2452 of file menu.c.
 {
     menuCommon_t *item;
     menuSound_t sound;
     if (menu->keywait) {
     }
     if (menu->keydown) {
         sound = menu->keydown(menu, key);
         if (sound != QMS_NOTHANDLED) {
             return sound;
         }
     }
     item = Menu_ItemAtCursor(menu);
     if (item) {
         sound = Menu_KeyEvent(item, key);
         if (sound != QMS_NOTHANDLED) {
             return sound;
         }
     }
     sound = Menu_DefaultKey(menu, key);
     return sound;
 }
Referenced by UI_KeyEvent().
Menu_KeyEvent()
menuSound_t Menu_KeyEvent (menuCommon_t * item, int key)
Definition at line 2353 of file menu.c.
 {
     if (item->keydown) {
         menuSound_t sound = item->keydown(item, key);
         if (sound != QMS_NOTHANDLED) {
             return sound;
         }
     }
     switch (item->type) {
     case MTYPE_FIELD:
         return Field_Key((menuField_t *)item, key);
     case MTYPE_LIST:
         return MenuList_Key((menuList_t *)item, key);
     case MTYPE_SLIDER:
         return Slider_Key((menuSlider_t *)item, key);
     case MTYPE_KEYBIND:
         return Keybind_Key((menuKeybind_t *)item, key);
     default:
         return QMS_NOTHANDLED;
     }
 }
Referenced by Menu_Keydown().
Menu_MouseMove()
menuSound_t Menu_MouseMove (menuCommon_t * item)
Definition at line 2386 of file menu.c.
 {
     switch (item->type) {
     case MTYPE_LIST:
         return MenuList_MouseMove((menuList_t *)item);
     case MTYPE_SLIDER:
         return Slider_MouseMove((menuSlider_t *)item);
     default:
         return QMS_NOTHANDLED;
     }
 }
Referenced by UI_DoHitTest().
Menu_Pop()
void Menu_Pop (menuFrameWork_t * menu)
Definition at line 2547 of file menu.c.
 {
     void *item;
     int i;
     for (i = 0; i < menu->nitems; i++) {
         item = menu->items[i];
         switch (((menuCommon_t *)item)->type) {
         case MTYPE_SLIDER:
             Slider_Pop(item);
             break;
         case MTYPE_BITFIELD:
             BitField_Pop(item);
             break;
         case MTYPE_PAIRS:
             Pairs_Pop(item);
             break;
         case MTYPE_STRINGS:
             Strings_Pop(item);
             break;
         case MTYPE_SPINCONTROL:
             SpinControl_Pop(item);
             break;
         case MTYPE_TOGGLE:
             Toggle_Pop(item);
             break;
         case MTYPE_KEYBIND:
             Keybind_Pop(item);
             break;
         case MTYPE_FIELD:
             Field_Pop(item);
             break;
         default:
             break;
         }
     }
 }
Referenced by Parse_File().
Menu_Push()
qboolean Menu_Push (menuFrameWork_t * menu)
Definition at line 2503 of file menu.c.
 {
     void *item;
     int i;
     for (i = 0; i < menu->nitems; i++) {
         item = menu->items[i];
         switch (((menuCommon_t *)item)->type) {
         case MTYPE_SLIDER:
             Slider_Push(item);
             break;
         case MTYPE_BITFIELD:
             BitField_Push(item);
             break;
         case MTYPE_PAIRS:
             Pairs_Push(item);
             break;
         case MTYPE_STRINGS:
             Strings_Push(item);
             break;
         case MTYPE_SPINCONTROL:
             SpinControl_Push(item);
             break;
         case MTYPE_TOGGLE:
             Toggle_Push(item);
             break;
         case MTYPE_KEYBIND:
             Keybind_Push(item);
             break;
         case MTYPE_FIELD:
             Field_Push(item);
             break;
         case MTYPE_SAVEGAME:
         case MTYPE_LOADGAME:
             Savegame_Push(item);
             break;
         default:
             break;
         }
     }
     return qtrue;
 }
Referenced by Parse_File().
Menu_SelectItem()
menuSound_t Menu_SelectItem (menuFrameWork_t * menu)
Definition at line 2298 of file menu.c.
 {
     menuCommon_t *item;
     if (!(item = Menu_ItemAtCursor(s))) {
         return QMS_NOTHANDLED;
     }
     switch (item->type) {
     //case MTYPE_SLIDER:
     //    return Slider_DoSlide((menuSlider_t *)item, 1);
     case MTYPE_SPINCONTROL:
     case MTYPE_BITFIELD:
     case MTYPE_PAIRS:
     case MTYPE_VALUES:
     case MTYPE_STRINGS:
     case MTYPE_TOGGLE:
         return SpinControl_DoEnter((menuSpinControl_t *)item);
     case MTYPE_KEYBIND:
         return Keybind_DoEnter((menuKeybind_t *)item);
     case MTYPE_FIELD:
     case MTYPE_ACTION:
     case MTYPE_LIST:
     case MTYPE_BITMAP:
     case MTYPE_SAVEGAME:
     case MTYPE_LOADGAME:
         return Common_DoEnter(item);
     default:
         return QMS_NOTHANDLED;
     }
 }
Referenced by Menu_DefaultKey().
Menu_SetFocus()
void Menu_SetFocus (menuCommon_t * item)
Definition at line 2057 of file menu.c.
 {
     menuFrameWork_t *menu;
     menuCommon_t *item;
     int i;
     if (focus->flags & QMF_HASFOCUS) {
         return;
     }
     menu = focus->parent;
     for (i = 0; i < menu->nitems; i++) {
         item = (menuCommon_t *)menu->items[i];
         if (item == focus) {
             item->flags |= QMF_HASFOCUS;
             if (item->focus) {
                 item->focus(item, qtrue);
             } else if (item->status) {
                 menu->status = item->status;
             }
         } else if (item->flags & QMF_HASFOCUS) {
             item->flags &= ~QMF_HASFOCUS;
             if (item->focus) {
                 item->focus(item, qfalse);
             } else if (menu->status == item->status
                        && menu->status != focus->status) {
                 menu->status = NULL;
             }
         }
     }
 }
Referenced by Menu_AdjustCursor(), and UI_DoHitTest().
Menu_Size()
void Menu_Size (menuFrameWork_t * menu)
Definition at line 1928 of file menu.c.
 {
     menuCommon_t *item;
     int x, y, w, h;
     int i, widest = -1;
     // count visible items
     for (i = 0, h = 0; i < menu->nitems; i++) {
         item = menu->items[i];
         if (item->flags & QMF_HIDDEN) {
             continue;
         }
         if (item->type == MTYPE_BITMAP) {
             h += GENERIC_SPACING(item->height);
             if (widest < item->width) {
                 widest = item->width;
             }
         } else {
             h += MENU_SPACING;
         }
     }
     // account for banner
     if (menu->banner) {
         h += GENERIC_SPACING(menu->banner_rc.height);
     }
     // set menu top/bottom
     if (menu->compact) {
         menu->y1 = (uis.height - h) / 2 - MENU_SPACING;
         menu->y2 = (uis.height + h) / 2 + MENU_SPACING;
     } else {
         menu->y1 = 0;
         menu->y2 = uis.height;
     }
     // set menu horizontal base
     if (widest == -1) {
         x = uis.width / 2;
     } else {
         // if menu has bitmaps, it is expected to have plaque and logo
         // align them horizontally to avoid going off screen on small resolution
         w = widest + CURSOR_WIDTH;
         if (menu->plaque_rc.width > menu->logo_rc.width) {
             w += menu->plaque_rc.width;
         } else {
             w += menu->logo_rc.width;
         }
         x = (uis.width + w) / 2 - widest;
     }
     // set menu vertical base
     y = (uis.height - h) / 2;
     // banner is horizontally centered and
     // positioned on top of all menu items
     if (menu->banner) {
         menu->banner_rc.x = (uis.width - menu->banner_rc.width) / 2;
         menu->banner_rc.y = y;
         y += GENERIC_SPACING(menu->banner_rc.height);
     }
     // plaque and logo are vertically centered and
     // positioned to the left of bitmaps and cursor
     h = 0;
     if (menu->plaque) {
         h += menu->plaque_rc.height;
     }
     if (menu->logo) {
         h += menu->logo_rc.height + 5;
     }
     if (menu->plaque) {
         menu->plaque_rc.x = x - CURSOR_WIDTH - menu->plaque_rc.width;
         menu->plaque_rc.y = (uis.height - h) / 2;
     }
     if (menu->logo) {
         menu->logo_rc.x = x - CURSOR_WIDTH - menu->logo_rc.width;
         menu->logo_rc.y = (uis.height + h) / 2 - menu->logo_rc.height;
     }
     // align items
     for (i = 0; i < menu->nitems; i++) {
         item = menu->items[i];
         if (item->flags & QMF_HIDDEN) {
             continue;
         }
         item->x = x;
         item->y = y;
         if (item->type == MTYPE_BITMAP) {
             y += GENERIC_SPACING(item->height);
         } else {
             y += MENU_SPACING;
         }
     }
     // footer is horizontally centered and
     // positioned below all menu items
     if (menu->footer) {
         menu->footer_rc.x = (uis.width - menu->footer_rc.width) / 2;
         menu->footer_rc.y = y;
         if (menu->plaque)
             menu->footer_rc.y = max(menu->footer_rc.y, menu->plaque_rc.y + menu->plaque_rc.height);
         if (menu->logo)
             menu->footer_rc.y = max(menu->footer_rc.y, menu->logo_rc.y + menu->logo_rc.height);
         menu->footer_rc.y += menu->footer_rc.height;
     }
 }
Referenced by Menu_Init().
Menu_SlideItem()
menuSound_t Menu_SlideItem (menuFrameWork_t * menu, int dir)
Definition at line 2330 of file menu.c.
 {
     menuCommon_t *item;
     if (!(item = Menu_ItemAtCursor(s))) {
         return QMS_NOTHANDLED;
     }
     switch (item->type) {
     case MTYPE_SLIDER:
         return Slider_DoSlide((menuSlider_t *)item, dir);
     case MTYPE_SPINCONTROL:
     case MTYPE_BITFIELD:
     case MTYPE_PAIRS:
     case MTYPE_VALUES:
     case MTYPE_STRINGS:
     case MTYPE_TOGGLE:
         return SpinControl_DoSlide((menuSpinControl_t *)item, dir);
     default:
         return QMS_NOTHANDLED;
     }
 }
Referenced by Menu_DefaultKey().
MenuList_Init()
void MenuList_Init (menuList_t * l)
Definition at line 820 of file menu.c.
 {
     int        height;
     int        i;
     height = l->generic.height;
     if (l->mlFlags & MLF_HEADER) {
         height -= MLIST_SPACING;
     }
     l->maxItems = height / MLIST_SPACING;
     //clamp(l->curvalue, 0, l->numItems - 1);
     MenuList_ValidatePrestep(l);
     l->generic.rect.x = l->generic.x;
     l->generic.rect.y = l->generic.y;
     l->generic.rect.width = 0;
     for (i = 0; i < l->numcolumns; i++) {
         l->generic.rect.width += l->columns[i].width;
     }
     if (l->mlFlags & MLF_SCROLLBAR) {
         l->generic.rect.width += MLIST_SCROLLBAR_WIDTH;
     }
     l->generic.rect.height = l->generic.height;
     if (l->sortdir && l->sort) {
         l->sort(l);
     }
 }
Referenced by EnterDirectory(), LeaveDirectory(), and Menu_Init().
MenuList_SetValue()
void MenuList_SetValue (menuList_t * l, int value)
Definition at line 860 of file menu.c.
 {
     if (value > l->numItems - 1)
         value = l->numItems - 1;
     if (value < 0)
         value = 0;
     if (value != l->curvalue) {
         l->curvalue = value;
         if (l->generic.change) {
             l->generic.change(&l->generic);
         }
     }
     MenuList_AdjustPrestep(l);
 }
Referenced by Expose(), LeaveDirectory(), and MenuList_Key().
MenuList_Sort()
void MenuList_Sort (menuList_t * l, int offset, int(*)(const void *, const void *) cmpfunc)
Definition at line 1465 of file menu.c.
 {
     void *n;
     int i;
     if (!l->items)
         return;
     if (offset >= l->numItems)
         return;
     if (l->sortcol < 0 || l->sortcol >= l->numcolumns)
         return;
     if (l->curvalue < 0 || l->curvalue >= l->numItems)
         n = NULL;
     else
         n = l->items[l->curvalue];
     qsort(l->items + offset, l->numItems - offset, sizeof(char *), cmpfunc);
     for (i = 0; i < l->numItems; i++) {
         if (l->items[i] == n) {
             l->curvalue = i;
             break;
         }
     }
     if (n)
         MenuList_AdjustPrestep(l);
 }
Referenced by Sort().
PlayerModel_Free()
void PlayerModel_Free (void)
Definition at line 186 of file playermodels.c.
 {
     playerModelInfo_t *pmi;
     int i, j;
     for (i = 0, pmi = uis.pmi; i < uis.numPlayerModels; i++, pmi++) {
         if (pmi->skindisplaynames) {
             for (j = 0; j < pmi->nskins; j++) {
                 Z_Free(pmi->skindisplaynames[j]);
             }
             Z_Free(pmi->skindisplaynames);
         }
         Z_Free(pmi->directory);
         memset(pmi, 0, sizeof(*pmi));
     }
     uis.numPlayerModels = 0;
 }
Referenced by UI_Shutdown().
PlayerModel_Load()
void PlayerModel_Load (void)
Definition at line 67 of file playermodels.c.
 {
     char scratch[MAX_QPATH];
     size_t len;
     int ndirs = 0;
     char *dirnames[MAX_PLAYERMODELS];
     int i, j;
     char **list;
     char *s, *p;
     int numFiles;
     playerModelInfo_t *pmi;
     uis.numPlayerModels = 0;
     // get a list of directories
     if (!(list = (char **)FS_ListFiles(NULL, "players/*/tris.md2", FS_SEARCH_BYFILTER | FS_SEARCH_SAVEPATH, &numFiles))) {
         return;
     }
     for (i = 0; i < numFiles; i++) {
         len = Q_strlcpy(scratch, list[i], sizeof(scratch));
         if (len >= sizeof(scratch))
             continue;
         // make short name for the model
         if (!(s = strchr(scratch, '/')))
             continue;
         s++;
         if (!(p = strchr(s, '/')))
             continue;
         *p = 0;
         for (j = 0; j < ndirs; j++) {
             if (!strcmp(dirnames[j], s)) {
                 break;
             }
         }
         if (j != ndirs) {
             continue;
         }
         dirnames[ndirs++] = UI_CopyString(s);
         if (ndirs == MAX_PLAYERMODELS) {
             break;
         }
     }
     FS_FreeList((void **)list);
     if (!ndirs) {
         return;
     }
     // go through the subdirectories
     for (i = 0; i < ndirs; i++) {
         int k, s;
         char **pcxnames;
         char **skinnames;
         int npcxfiles;
         int nskins = 0;
         // verify the existence of tris.md2
         Q_concat(scratch, sizeof(scratch), "players/", dirnames[i], "/tris.md2", NULL);
         if (!FS_FileExists(scratch)) {
             goto skip;
         }
         // verify the existence of at least one pcx skin
         Q_concat(scratch, sizeof(scratch), "players/", dirnames[i], NULL);
         pcxnames = (char **)FS_ListFiles(scratch, ".pcx", 0, &npcxfiles);
         if (!pcxnames) {
             goto skip;
         }
         // count valid skins, which consist of a skin with a matching "_i" icon
         for (k = 0; k < npcxfiles; k++) {
             if (!strstr(pcxnames[k], "_i.pcx")) {
                 if (IconOfSkinExists(pcxnames[k], pcxnames, npcxfiles)) {
                     nskins++;
                 }
             }
         }
         if (!nskins) {
             FS_FreeList((void **)pcxnames);
             goto skip;
         }
         skinnames = UI_Malloc(sizeof(char *) * (nskins + 1));
         skinnames[nskins] = NULL;
         // copy the valid skins
         for (s = 0, k = 0; k < npcxfiles; k++) {
             if (!strstr(pcxnames[k], "_i.pcx")) {
                 if (IconOfSkinExists(pcxnames[k], pcxnames, npcxfiles)) {
                     COM_StripExtension(pcxnames[k], scratch, sizeof(scratch));
                     skinnames[s++] = UI_CopyString(scratch);
                 }
             }
         }
         FS_FreeList((void **)pcxnames);
         // at this point we have a valid player model
         pmi = &uis.pmi[uis.numPlayerModels++];
         pmi->nskins = nskins;
         pmi->skindisplaynames = skinnames;
         pmi->directory = dirnames[i];
         continue;
 skip:
         Z_Free(dirnames[i]);
     }
     qsort(uis.pmi, uis.numPlayerModels, sizeof(uis.pmi[0]), pmicmpfnc);
 }
Referenced by Push().
SpinControl_Init()
void SpinControl_Init (menuSpinControl_t * s)
Definition at line 543 of file menu.c.
 {
     char **n;
     int    maxLength, length;
     s->generic.uiFlags &= ~(UI_LEFT | UI_RIGHT);
     s->generic.rect.x = s->generic.x + LCOLUMN_OFFSET;
     s->generic.rect.y = s->generic.y;
     UI_StringDimensions(&s->generic.rect,
                         s->generic.uiFlags | UI_RIGHT, s->generic.name);
     maxLength = 0;
     s->numItems = 0;
     n = s->itemnames;
     while (*n) {
         length = strlen(*n);
         if (maxLength < length) {
             maxLength = length;
         }
         s->numItems++;
         n++;
     }
     s->generic.rect.width += (RCOLUMN_OFFSET - LCOLUMN_OFFSET) +
                              maxLength * CHAR_WIDTH;
 }
Referenced by Change(), and Menu_Init().
UI_CursorInRect()
qboolean UI_CursorInRect (vrect_t * rect)
Definition at line 297 of file ui.c.
 {
     if (uis.mouseCoords[0] < rect->x) {
         return qfalse;
     }
     if (uis.mouseCoords[0] >= rect->x + rect->width) {
         return qfalse;
     }
     if (uis.mouseCoords[1] < rect->y) {
         return qfalse;
     }
     if (uis.mouseCoords[1] >= rect->y + rect->height) {
         return qfalse;
     }
     return qtrue;
 }
Referenced by Menu_HitTest(), MenuList_Click(), and Slider_Click().
UI_DoHitTest()
qboolean UI_DoHitTest (void)
Definition at line 368 of file ui.c.
 {
     menuCommon_t *item;
     if (!uis.activeMenu) {
         return qfalse;
     }
     if (uis.mouseTracker) {
         item = uis.mouseTracker;
     } else {
         if (!(item = Menu_HitTest(uis.activeMenu))) {
             return qfalse;
         }
     }
     if (!UI_IsItemSelectable(item)) {
         return qfalse;
     }
     Menu_MouseMove(item);
     if (item->flags & QMF_HASFOCUS) {
         return qfalse;
     }
     Menu_SetFocus(item);
     return qtrue;
 }
Referenced by UI_MouseEvent(), UI_PopMenu(), and UI_PushMenu().
UI_DrawChar()
void UI_DrawChar (int x, int y, int flags, int ch)
Definition at line 325 of file ui.c.
 {
     R_DrawChar(x, y, flags, ch, uis.fontHandle);
 }
Referenced by Action_Draw(), Keybind_Draw(), Slider_Draw(), and SpinControl_Draw().
UI_DrawRect8()
void UI_DrawRect8 (const vrect_t * rect, int border, int c)
Definition at line 342 of file ui.c.
 {
     R_DrawFill8(rc->x, rc->y, border, rc->height, c);   // left
     R_DrawFill8(rc->x + rc->width - border, rc->y, border, rc->height, c);   // right
     R_DrawFill8(rc->x + border, rc->y, rc->width - border * 2, border, c);   // top
     R_DrawFill8(rc->x + border, rc->y + rc->height - border, rc->width - border * 2, border, c);   // bottom
 }
Referenced by Menu_Draw().
UI_DrawString()
void UI_DrawString (int x, int y, int flags, const char * string)
Definition at line 314 of file ui.c.
 {
     if ((flags & UI_CENTER) == UI_CENTER) {
         x -= strlen(string) * CHAR_WIDTH / 2;
     } else if (flags & UI_RIGHT) {
         x -= strlen(string) * CHAR_WIDTH;
     }
     R_DrawString(x, y, flags, MAX_STRING_CHARS, string, uis.fontHandle);
 }
Referenced by Action_Draw(), Draw(), DrawStatus(), Field_Draw(), Keybind_Draw(), Menu_Draw(), MenuList_DrawString(), Separator_Draw(), Slider_Draw(), SpinControl_Draw(), Static_Draw(), and UI_Draw().
UI_FindMenu()
menuFrameWork_t* UI_FindMenu (const char * name)
Definition at line 190 of file ui.c.
 {
     menuFrameWork_t *menu;
     LIST_FOR_EACH(menuFrameWork_t, menu, &ui_menus, entry) {
         if (!strcmp(menu->name, name)) {
             return menu;
         }
     }
     return NULL;
 }
Referenced by Parse_File(), UI_OpenMenu(), and UI_PushMenu_f().
UI_ForceMenuOff()
void UI_ForceMenuOff (void)
Definition at line 119 of file ui.c.
 {
     menuFrameWork_t *menu;
     int i;
     for (i = 0; i < uis.menuDepth; i++) {
         menu = uis.layers[i];
         if (menu->pop) {
             menu->pop(menu);
         }
     }
     Key_SetDest(Key_GetDest() & ~KEY_MENU);
     uis.menuDepth = 0;
     uis.activeMenu = NULL;
     uis.mouseTracker = NULL;
     uis.transparent = qfalse;
 }
Referenced by UI_OpenMenu(), UI_PopMenu(), and UI_Shutdown().
UI_FormatColumns()
void* UI_FormatColumns (int extrasize, ...)
Definition at line 251 of file ui.c.
 {
     va_list argptr;
     char *buffer, *p;
     int i, j;
     size_t total = 0;
     char *strings[MAX_COLUMNS];
     size_t lengths[MAX_COLUMNS];
     va_start(argptr, extrasize);
     for (i = 0; i < MAX_COLUMNS; i++) {
         if ((p = va_arg(argptr, char *)) == NULL) {
             break;
         }
         strings[i] = p;
         total += lengths[i] = strlen(p) + 1;
     }
     va_end(argptr);
     buffer = UI_Malloc(extrasize + total + 1);
     p = buffer + extrasize;
     for (j = 0; j < i; j++) {
         memcpy(p, strings[j], lengths[j]);
         p += lengths[j];
     }
     *p = 0;
     return buffer;
 }
Referenced by AddServer(), BuildDir(), BuildName(), PingSelected(), UI_ErrorEvent(), and UI_StatusEvent().
UI_GetColumn()
char* UI_GetColumn (char * s, int n)
Definition at line 281 of file ui.c.
 {
     int i;
     for (i = 0; i < n && *s; i++) {
         s += strlen(s) + 1;
     }
     return s;
 }
Referenced by MenuList_Key(), namecmp(), pingcmp(), and WriteCache().
UI_LoadScript()
void UI_LoadScript (void)
Definition at line 789 of file script.c.
 {
     Parse_File("q2rtx.menu", 0);
 }
Referenced by UI_Init().
UI_PopMenu()
void UI_PopMenu (void)
Definition at line 143 of file ui.c.
 {
     menuFrameWork_t *menu;
     if (uis.menuDepth < 1)
         Com_Error(ERR_FATAL, "UI_PopMenu: depth < 1");
     menu = uis.layers[--uis.menuDepth];
     if (menu->pop) {
         menu->pop(menu);
     }
     if (!uis.menuDepth) {
         UI_ForceMenuOff();
         // Save the config file if the user closes the menu while in-game
         if (cls.state >= ca_active) {
             CL_WriteConfig();
         }
         return;
     }
     uis.activeMenu = uis.layers[uis.menuDepth - 1];
     uis.mouseTracker = NULL;
     UI_DoHitTest();
 }
Referenced by Menu_DefaultKey(), UI_PopMenu_f(), and UI_PushMenu().
UI_PushMenu()
void UI_PushMenu (menuFrameWork_t * menu)
Definition at line 39 of file ui.c.
 {
     int i, j;
     if (!menu) {
         return;
     }
     // if this menu is already present, drop back to that level
     // to avoid stacking menus by hotkeys
     for (i = 0; i < uis.menuDepth; i++) {
         if (uis.layers[i] == menu) {
             break;
         }
     }
     if (i == uis.menuDepth) {
         if (uis.menuDepth >= MAX_MENU_DEPTH) {
             Com_EPrintf("UI_PushMenu: MAX_MENU_DEPTH exceeded\n");
             return;
         }
         uis.layers[uis.menuDepth++] = menu;
     } else {
         for (j = i; j < uis.menuDepth; j++) {
             UI_PopMenu();
         }
         uis.menuDepth = i + 1;
     }
     if (menu->push && !menu->push(menu)) {
         uis.menuDepth--;
         return;
     }
     Menu_Init(menu);
     Key_SetDest((Key_GetDest() & ~KEY_CONSOLE) | KEY_MENU);
     Con_Close(qtrue);
     if (!uis.activeMenu) {
         // opening menu moves cursor to the nice location
         IN_WarpMouse(menu->mins[0] / uis.scale, menu->mins[1] / uis.scale);
         uis.mouseCoords[0] = menu->mins[0];
         uis.mouseCoords[1] = menu->mins[1];
         uis.entersound = qtrue;
     }
     uis.activeMenu = menu;
     UI_DoHitTest();
     if (menu->expose) {
         menu->expose(menu);
     }
 }
Referenced by UI_OpenMenu(), and UI_PushMenu_f().
UI_StartSound()
void UI_StartSound (menuSound_t sound)
Definition at line 478 of file ui.c.
 {
     switch (sound) {
     case QMS_IN:
         S_StartLocalSound("misc/menu1.wav");
         break;
     case QMS_MOVE:
         S_StartLocalSound("misc/menu2.wav");
         break;
     case QMS_OUT:
         S_StartLocalSound("misc/menu3.wav");
         break;
     case QMS_BEEP:
         S_StartLocalSound("misc/talk1.wav");
         break;
     default:
         break;
     }
 }
Referenced by keybind_cb(), UI_CharEvent(), and UI_KeyEvent().
UI_StringDimensions()
void UI_StringDimensions (vrect_t * rc, int flags, const char * string)
Definition at line 330 of file ui.c.
 {
     rc->height = CHAR_HEIGHT;
     rc->width = CHAR_WIDTH * strlen(string);
     if ((flags & UI_CENTER) == UI_CENTER) {
         rc->x -= rc->width / 2;
     } else if (flags & UI_RIGHT) {
         rc->x -= rc->width;
     }
 }
Referenced by Action_Init(), Field_Init(), Keybind_Init(), Savegame_Push(), SpinControl_Init(), and Static_Init().
Variable Documentation
ui_debug
cvar_t* ui_debug
Definition at line 28 of file ui.c.
Referenced by Menu_Draw(), UI_Draw(), and UI_Init().
ui_menus
list_t ui_menus
Referenced by M_Menu_Demos(), M_Menu_PlayerConfig(), M_Menu_Servers(), Parse_File(), UI_FindMenu(), UI_FreeMenus(), UI_Init(), and UI_Menu_g().
uis
uiStatic_t uis
Definition at line 24 of file ui.c.