Quake II RTX doxygen: C:/entry/dev/Q2RTX/src/baseq2/g_svcmds.c File Reference
g_svcmds.c File Reference
#include "g_local.h"
Classes
struct ipfilter_t
Macros
#define MAX_IPFILTERS 1024
Functions
void Svcmd_Test_f (void)
static qboolean StringToFilter (char *s, ipfilter_t *f)
qboolean SV_FilterPacket (char *from)
void SVCmd_AddIP_f (void)
void SVCmd_RemoveIP_f (void)
void SVCmd_ListIP_f (void)
void SVCmd_WriteIP_f (void)
void ServerCommand (void)
Variables
ipfilter_t ipfilters [MAX_IPFILTERS]
int numipfilters
Macro Definition Documentation
MAX_IPFILTERS
#define MAX_IPFILTERS 1024
Definition at line 63 of file g_svcmds.c.
Function Documentation
ServerCommand()
void ServerCommand (void)
Definition at line 275 of file g_svcmds.c.
 {
     char    *cmd;
     cmd = gi.argv(1);
     if (Q_stricmp(cmd, "test") == 0)
         Svcmd_Test_f();
     else if (Q_stricmp(cmd, "addip") == 0)
         SVCmd_AddIP_f();
     else if (Q_stricmp(cmd, "removeip") == 0)
         SVCmd_RemoveIP_f();
     else if (Q_stricmp(cmd, "listip") == 0)
         SVCmd_ListIP_f();
     else if (Q_stricmp(cmd, "writeip") == 0)
         SVCmd_WriteIP_f();
     else
         gi.cprintf(NULL, PRINT_HIGH, "Unknown server command \"%s\"\n", cmd);
 }
Referenced by GetGameAPI().
StringToFilter()
static qboolean StringToFilter (char * s, ipfilter_t * f) static
Definition at line 73 of file g_svcmds.c.
 {
     char    num[128];
     int     i, j;
     byte    b[4];
     byte    m[4];
     for (i = 0 ; i < 4 ; i++) {
         b[i] = 0;
         m[i] = 0;
     }
     for (i = 0 ; i < 4 ; i++) {
         if (*s < '0' || *s > '9') {
             gi.cprintf(NULL, PRINT_HIGH, "Bad filter address: %s\n", s);
             return qfalse;
         }
         j = 0;
         while (*s >= '0' && *s <= '9') {
             num[j++] = *s++;
         }
         num[j] = 0;
         b[i] = atoi(num);
         if (b[i] != 0)
             m[i] = 255;
         if (!*s)
             break;
         s++;
     }
     f->mask = *(unsigned *)m;
     f->compare = *(unsigned *)b;
     return qtrue;
 }
Referenced by SVCmd_AddIP_f(), and SVCmd_RemoveIP_f().
SV_FilterPacket()
qboolean SV_FilterPacket (char * from)
Definition at line 116 of file g_svcmds.c.
 {
     int     i;
     unsigned    in;
     byte m[4];
     char *p;
     i = 0;
     p = from;
     while (*p && i < 4) {
         m[i] = 0;
         while (*p >= '0' && *p <= '9') {
             m[i] = m[i] * 10 + (*p - '0');
             p++;
         }
         if (!*p || *p == ':')
             break;
         i++, p++;
     }
     in = *(unsigned *)m;
     for (i = 0 ; i < numipfilters ; i++)
         if ((in & ipfilters[i].mask) == ipfilters[i].compare)
             return (int)filterban->value;
     return (int)!filterban->value;
 }
Referenced by ClientConnect().
SVCmd_AddIP_f()
void SVCmd_AddIP_f (void)
Definition at line 151 of file g_svcmds.c.
 {
     int     i;
     if (gi.argc() < 3) {
         gi.cprintf(NULL, PRINT_HIGH, "Usage:  addip <ip-mask>\n");
         return;
     }
     for (i = 0 ; i < numipfilters ; i++)
         if (ipfilters[i].compare == 0xffffffff)
             break;      // free spot
     if (i == numipfilters) {
         if (numipfilters == MAX_IPFILTERS) {
             gi.cprintf(NULL, PRINT_HIGH, "IP filter list is full\n");
             return;
         }
         numipfilters++;
     }
     if (!StringToFilter(gi.argv(2), &ipfilters[i]))
         ipfilters[i].compare = 0xffffffff;
 }
Referenced by ServerCommand().
SVCmd_ListIP_f()
void SVCmd_ListIP_f (void)
Definition at line 210 of file g_svcmds.c.
 {
     int     i;
     byte    b[4];
     gi.cprintf(NULL, PRINT_HIGH, "Filter list:\n");
     for (i = 0 ; i < numipfilters ; i++) {
         *(unsigned *)b = ipfilters[i].compare;
         gi.cprintf(NULL, PRINT_HIGH, "%3i.%3i.%3i.%3i\n", b[0], b[1], b[2], b[3]);
     }
 }
Referenced by ServerCommand().
SVCmd_RemoveIP_f()
void SVCmd_RemoveIP_f (void)
Definition at line 180 of file g_svcmds.c.
 {
     ipfilter_t  f;
     int         i, j;
     if (gi.argc() < 3) {
         gi.cprintf(NULL, PRINT_HIGH, "Usage:  sv removeip <ip-mask>\n");
         return;
     }
     if (!StringToFilter(gi.argv(2), &f))
         return;
     for (i = 0 ; i < numipfilters ; i++)
         if (ipfilters[i].mask == f.mask
             && ipfilters[i].compare == f.compare) {
             for (j = i + 1 ; j < numipfilters ; j++)
                 ipfilters[j - 1] = ipfilters[j];
             numipfilters--;
             gi.cprintf(NULL, PRINT_HIGH, "Removed.\n");
             return;
         }
     gi.cprintf(NULL, PRINT_HIGH, "Didn't find %s.\n", gi.argv(2));
 }
Referenced by ServerCommand().
Svcmd_Test_f()
void Svcmd_Test_f (void)
Definition at line 22 of file g_svcmds.c.
 {
     gi.cprintf(NULL, PRINT_HIGH, "Svcmd_Test_f()\n");
 }
Referenced by ServerCommand().
SVCmd_WriteIP_f()
void SVCmd_WriteIP_f (void)
Definition at line 227 of file g_svcmds.c.
 {
     FILE    *f;
     char    name[MAX_OSPATH];
     size_t  len;
     byte    b[4];
     int     i;
     cvar_t  *game;
     game = gi.cvar("game", "", 0);
     if (!*game->string)
         len = Q_snprintf(name, sizeof(name), "%s/listip.cfg", GAMEVERSION);
     else
         len = Q_snprintf(name, sizeof(name), "%s/listip.cfg", game->string);
     if (len >= sizeof(name)) {
         gi.cprintf(NULL, PRINT_HIGH, "File name too long\n");
         return;
     }
     gi.cprintf(NULL, PRINT_HIGH, "Writing %s.\n", name);
     f = fopen(name, "wb");
     if (!f) {
         gi.cprintf(NULL, PRINT_HIGH, "Couldn't open %s\n", name);
         return;
     }
     fprintf(f, "set filterban %d\n", (int)filterban->value);
     for (i = 0 ; i < numipfilters ; i++) {
         *(unsigned *)b = ipfilters[i].compare;
         fprintf(f, "sv addip %i.%i.%i.%i\n", b[0], b[1], b[2], b[3]);
     }
     fclose(f);
 }
Referenced by ServerCommand().
Variable Documentation
ipfilters
ipfilter_t ipfilters[MAX_IPFILTERS]
Definition at line 65 of file g_svcmds.c.
Referenced by SV_FilterPacket(), SVCmd_AddIP_f(), SVCmd_ListIP_f(), SVCmd_RemoveIP_f(), and SVCmd_WriteIP_f().
numipfilters
int numipfilters
Definition at line 66 of file g_svcmds.c.
Referenced by SV_FilterPacket(), SVCmd_AddIP_f(), SVCmd_ListIP_f(), SVCmd_RemoveIP_f(), and SVCmd_WriteIP_f().