Quake II RTX doxygen: C:/entry/dev/Q2RTX/src/common/sizebuf.c File Reference
sizebuf.c File Reference
#include "shared/shared.h"
#include "common/protocol.h"
#include "common/sizebuf.h"
Functions
void SZ_TagInit (sizebuf_t *buf, void *data, size_t size, uint32_t tag)
void SZ_Init (sizebuf_t *buf, void *data, size_t size)
void SZ_Clear (sizebuf_t *buf)
void * SZ_GetSpace (sizebuf_t *buf, size_t len)
void SZ_WriteByte (sizebuf_t *sb, int c)
void SZ_WriteShort (sizebuf_t *sb, int c)
void SZ_WriteLong (sizebuf_t *sb, int c)
Function Documentation
SZ_Clear()
void SZ_Clear (sizebuf_t * buf)
Definition at line 40 of file sizebuf.c.
 {
     buf->cursize = 0;
     buf->readcount = 0;
     buf->bitpos = 0;
     buf->overflowed = qfalse;
 }
Referenced by AC_Announce(), AC_Flush(), AC_Write(), CL_Disconnect(), CL_EmitDemoFrame(), CL_EmitDemoSnapshot(), CL_GTV_EmitFrame(), CL_GTV_Resume(), CL_GTV_Transmit(), CL_SendBatchedCmd(), CL_SendDefaultCmd(), CL_WriteDemoMessage(), demo_emit_snapshot(), gtv_forward_cmd(), MVD_BroadcastPrintf(), MVD_ChangeLevel(), mvd_disable(), MVD_Frame(), MVD_StreamedRecord_f(), MVD_UpdateConfigstring(), NetchanNew_Process(), NetchanNew_TransmitNextFragment(), parse_hello(), parse_stream_start(), PF_bprintf(), PF_configstring(), PF_cprintf(), PF_Unicast(), rec_start(), redirect(), resume_streams(), send_hello(), send_stream_start(), SV_BroadcastCommand(), SV_BroadcastPrintf(), SV_ClientAddMessage(), SV_FinalMessage(), SV_Multicast(), SV_MvdEndFrame(), SV_MvdMapChanged(), SV_RunGameFrame(), SV_SendClientMessages(), SV_StuffAll_f(), SZ_GetSpace(), write_datagram_new(), write_datagram_old(), write_level_file(), and write_server_file().
SZ_GetSpace()
void* SZ_GetSpace (sizebuf_t * buf, size_t len)
Definition at line 48 of file sizebuf.c.
 {
     void    *data;
     if (buf->cursize > buf->maxsize) {
         Com_Error(ERR_FATAL,
                   "%s: %#x: already overflowed",
                   __func__, buf->tag);
     }
     if (len > buf->maxsize - buf->cursize) {
         if (len > buf->maxsize) {
             Com_Error(ERR_FATAL,
                       "%s: %#x: %"PRIz" is > full buffer size %"PRIz"",
                       __func__, buf->tag, len, buf->maxsize);
         }
         if (!buf->allowoverflow) {
             Com_Error(ERR_FATAL,
                       "%s: %#x: overflow without allowoverflow set",
                       __func__, buf->tag);
         }
         //Com_DPrintf("%s: %#x: overflow\n", __func__, buf->tag);
         SZ_Clear(buf);
         buf->overflowed = qtrue;
     }
     data = buf->data + buf->cursize;
     buf->cursize += len;
     buf->bitpos = buf->cursize << 3;
     return data;
 }
Referenced by CL_SendBatchedCmd(), CL_SendDefaultCmd(), MSG_WriteByte(), MSG_WriteChar(), MSG_WriteLong(), MSG_WriteShort(), SV_WriteFrameToClient_Enhanced(), SZ_WriteByte(), SZ_WriteLong(), and SZ_WriteShort().
SZ_Init()
void SZ_Init (sizebuf_t * buf, void * data, size_t size)
Definition at line 31 of file sizebuf.c.
 {
     memset(buf, 0, sizeof(*buf));
     buf->data = data;
     buf->maxsize = size;
     buf->allowoverflow = qtrue;
     buf->allowunderflow = qtrue;
 }
Referenced by CL_GTV_Resume(), CL_ParseZPacket(), CL_Record_f(), CL_Seek_f(), demo_read_message(), demo_skip_map(), FIFO_ReadMessage(), MVD_Seek_f(), NET_GetUdpPackets(), NetchanNew_Setup(), NetchanOld_Setup(), read_binary_file(), read_first_message(), read_next_message(), and SV_MvdInit().
SZ_TagInit()
void SZ_TagInit (sizebuf_t * buf, void * data, size_t size, uint32_t tag)
Definition at line 23 of file sizebuf.c.
 {
     memset(buf, 0, sizeof(*buf));
     buf->data = data;
     buf->maxsize = size;
     buf->tag = tag;
 }
Referenced by MSG_Init(), NetchanNew_Setup(), NetchanNew_Transmit(), NetchanNew_TransmitNextFragment(), and NetchanOld_Transmit().
SZ_WriteByte()
void SZ_WriteByte (sizebuf_t * sb, int c)
Definition at line 82 of file sizebuf.c.
 {
     byte    *buf;
     buf = SZ_GetSpace(sb, 1);
     buf[0] = c;
 }
Referenced by CL_GTV_WriteMessage(), NetchanNew_Transmit(), NetchanNew_TransmitNextFragment(), NetchanOld_Transmit(), resume_record(), SV_MvdBroadcastPrint(), SV_MvdConfigstring(), SV_MvdMulticast(), SV_MvdStartSound(), SV_MvdUnicast(), and write_pending_download().
SZ_WriteLong()
void SZ_WriteLong (sizebuf_t * sb, int c)
Definition at line 99 of file sizebuf.c.
 {
     byte    *buf;
     buf = SZ_GetSpace(sb, 4);
     buf[0] = c & 0xff;
     buf[1] = (c >> 8) & 0xff;
     buf[2] = (c >> 16) & 0xff;
     buf[3] = c >> 24;
 }
Referenced by NetchanNew_Transmit(), NetchanNew_TransmitNextFragment(), and NetchanOld_Transmit().
SZ_WriteShort()
void SZ_WriteShort (sizebuf_t * sb, int c)
Definition at line 90 of file sizebuf.c.
 {
     byte    *buf;
     buf = SZ_GetSpace(sb, 2);
     buf[0] = c & 0xff;
     buf[1] = c >> 8;
 }
Referenced by NetchanNew_TransmitNextFragment(), NetchanOld_Transmit(), resume_record(), SV_MvdConfigstring(), SV_MvdMulticast(), SV_MvdStartSound(), and write_pending_download().