Quake II RTX doxygen: C:/entry/dev/Q2RTX/src/common/net/inet_pton.h File Reference
inet_pton.h File Reference
Functions
static int inet_pton4 (const char *src, unsigned char *dst)
static int inet_pton6 (const char *src, unsigned char *dst)
static int os_inet_pton (int af, const char *src, void *dst)
Function Documentation
inet_pton4()
static int inet_pton4 (const char * src, unsigned char * dst) static
int inet_pton4(src, dst) like inet_aton() but without all the hexadecimal and shorthand. return: 1 if ‘src’ is a valid dotted quad, else 0. notice: does not touch ‘dst’ unless it's returning 1. author: Paul Vixie, 1996.
Definition at line 65 of file inet_pton.h.
 {
     static const char digits[] = "0123456789";
     int saw_digit, octets, ch;
     unsigned char tmp[NS_INADDRSZ], *tp;
     saw_digit = 0;
     octets = 0;
     *(tp = tmp) = 0;
     while ((ch = *src++) != '\0') {
         const char *pch;
         if ((pch = strchr(digits, ch)) != NULL) {
             unsigned int new = *tp * 10;
             new += (unsigned int)(pch - digits);
             if (new > 255)
                 return (0);
             *tp = new;
             if (!saw_digit) {
                 if (++octets > 4)
                     return (0);
                 saw_digit = 1;
             }
         } else if (ch == '.' && saw_digit) {
             if (octets == 4)
                 return (0);
             /*
              * "clang --analyse" generates warnings using:
              *      *++tp = 0;
              */
             tp++;
             *tp = 0;
             saw_digit = 0;
         } else
             return (0);
     }
     if (octets < 4)
         return (0);
     memmove(dst, tmp, NS_INADDRSZ);
     return (1);
 }
Referenced by inet_pton6(), and os_inet_pton().
inet_pton6()
static int inet_pton6 (const char * src, unsigned char * dst) static
int inet_pton6(src, dst) convert presentation level address to network order binary form. return: 1 if ‘src’ is a valid [RFC1884 2.2] address, else 0. notice: (1) does not touch ‘dst’ unless it's returning 1. (2) :: in a full address is silently ignored. credit: inspired by Mark Andrews. author: Paul Vixie, 1996.
Definition at line 121 of file inet_pton.h.
 {
     static const char xdigits_l[] = "0123456789abcdef",
                       xdigits_u[] = "0123456789ABCDEF";
     unsigned char tmp[NS_IN6ADDRSZ], *tp, *endp, *colonp;
     const char *xdigits, *curtok;
     int ch, seen_xdigits;
     unsigned int val;
     memset((tp = tmp), '\0', NS_IN6ADDRSZ);
     endp = tp + NS_IN6ADDRSZ;
     colonp = NULL;
     /* Leading :: requires some special handling. */
     if (*src == ':')
         if (*++src != ':')
             return (0);
     curtok = src;
     seen_xdigits = 0;
     val = 0;
     while ((ch = *src++) != '\0') {
         const char *pch;
         if ((pch = strchr((xdigits = xdigits_l), ch)) == NULL)
             pch = strchr((xdigits = xdigits_u), ch);
         if (pch != NULL) {
             val <<= 4;
             val |= (pch - xdigits);
             if (++seen_xdigits > 4)
                 return (0);
             continue;
         }
         if (ch == ':') {
             curtok = src;
             if (!seen_xdigits) {
                 if (colonp)
                     return (0);
                 colonp = tp;
                 continue;
             }
             if (tp + NS_INT16SZ > endp)
                 return (0);
             *tp++ = (unsigned char)(val >> 8) & 0xff;
             *tp++ = (unsigned char)val & 0xff;
             seen_xdigits = 0;
             val = 0;
             continue;
         }
         if (ch == '.' && ((tp + NS_INADDRSZ) <= endp) &&
             inet_pton4(curtok, tp) > 0) {
             tp += NS_INADDRSZ;
             seen_xdigits = 0;
             break;  /* '\0' was seen by inet_pton4(). */
         }
         return (0);
     }
     if (seen_xdigits) {
         if (tp + NS_INT16SZ > endp)
             return (0);
         *tp++ = (unsigned char)(val >> 8) & 0xff;
         *tp++ = (unsigned char)val & 0xff;
     }
     if (colonp != NULL) {
         /*
          * Since some memmove()'s erroneously fail to handle
          * overlapping regions, we'll do the shift by hand.
          */
         const int n = (int)(tp - colonp);
         int i;
         for (i = 1; i <= n; i++) {
             endp[-i] = colonp[n - i];
             colonp[n - i] = 0;
         }
         tp = endp;
     }
     if (tp != endp)
         return (0);
     memmove(dst, tmp, NS_IN6ADDRSZ);
     return (1);
 }
Referenced by os_inet_pton().
os_inet_pton()
static int os_inet_pton (int af, const char * src, void * dst) static
int lwres_net_pton(af, src, dst) convert from presentation format (which usually means ASCII printable) to network format (which is usually some kind of binary format). return: 1 if the address was valid for the specified address family 0 if the address wasn't valid (‘dst’ is untouched in this case) -1 if some other error occurred (‘dst’ is untouched in this case, too) author: Paul Vixie, 1996.
Definition at line 41 of file inet_pton.h.
 {
     switch (af) {
     case AF_INET:
         return (inet_pton4(src, dst));
     case AF_INET6:
         return (inet_pton6(src, dst));
     default:
         /* errno = EAFNOSUPPORT */;
         return (-1);
     }
     /* NOTREACHED */
 }
Referenced by NET_StringPairToAdr().