Quake II RTX doxygen: C:/entry/dev/Q2RTX/src/baseq2/g_local.h File Reference
g_local.h File Reference
#include "shared/shared.h"
#include "shared/list.h"
#include "shared/game.h"
Classes
struct gitem_armor_t
struct gitem_s
struct game_locals_t
struct level_locals_t
struct spawn_temp_t
struct moveinfo_t
struct mframe_t
struct mmove_t
struct monsterinfo_t
struct client_persistant_t
struct client_respawn_t
struct gclient_s
struct edict_s
Macros
#define GAME_INCLUDE
#define G_FEATURES (GMF_PROPERINUSE|GMF_WANT_ALL_DISCONNECTS|GMF_ENHANCED_SAVEGAMES)
#define GAMEVERSION "baseq2"
#define svc_muzzleflash 1
#define svc_muzzleflash2 2
#define svc_temp_entity 3
#define svc_layout 4
#define svc_inventory 5
#define svc_stufftext 11
#define DAMAGE_TIME 0.5
#define FALL_TIME 0.3
#define SPAWNFLAG_NOT_EASY 0x00000100
#define SPAWNFLAG_NOT_MEDIUM 0x00000200
#define SPAWNFLAG_NOT_HARD 0x00000400
#define SPAWNFLAG_NOT_DEATHMATCH 0x00000800
#define SPAWNFLAG_NOT_COOP 0x00001000
#define FL_FLY 0x00000001
#define FL_SWIM 0x00000002
#define FL_IMMUNE_LASER 0x00000004
#define FL_INWATER 0x00000008
#define FL_GODMODE 0x00000010
#define FL_NOTARGET 0x00000020
#define FL_IMMUNE_SLIME 0x00000040
#define FL_IMMUNE_LAVA 0x00000080
#define FL_PARTIALGROUND 0x00000100
#define FL_WATERJUMP 0x00000200
#define FL_TEAMSLAVE 0x00000400
#define FL_NO_KNOCKBACK 0x00000800
#define FL_POWER_ARMOR 0x00001000
#define FL_RESPAWN 0x80000000
#define FRAMETIME 0.1
#define TAG_GAME 765
#define TAG_LEVEL 766
#define MELEE_DISTANCE 80
#define BODY_QUEUE_SIZE 8
#define DEAD_NO 0
#define DEAD_DYING 1
#define DEAD_DEAD 2
#define DEAD_RESPAWNABLE 3
#define RANGE_MELEE 0
#define RANGE_NEAR 1
#define RANGE_MID 2
#define RANGE_FAR 3
#define GIB_ORGANIC 0
#define GIB_METALLIC 1
#define AI_STAND_GROUND 0x00000001
#define AI_TEMP_STAND_GROUND 0x00000002
#define AI_SOUND_TARGET 0x00000004
#define AI_LOST_SIGHT 0x00000008
#define AI_PURSUIT_LAST_SEEN 0x00000010
#define AI_PURSUE_NEXT 0x00000020
#define AI_PURSUE_TEMP 0x00000040
#define AI_HOLD_FRAME 0x00000080
#define AI_GOOD_GUY 0x00000100
#define AI_BRUTAL 0x00000200
#define AI_NOSTEP 0x00000400
#define AI_DUCKED 0x00000800
#define AI_COMBAT_POINT 0x00001000
#define AI_MEDIC 0x00002000
#define AI_RESURRECTING 0x00004000
#define AS_STRAIGHT 1
#define AS_SLIDING 2
#define AS_MELEE 3
#define AS_MISSILE 4
#define ARMOR_NONE 0
#define ARMOR_JACKET 1
#define ARMOR_COMBAT 2
#define ARMOR_BODY 3
#define ARMOR_SHARD 4
#define POWER_ARMOR_NONE 0
#define POWER_ARMOR_SCREEN 1
#define POWER_ARMOR_SHIELD 2
#define RIGHT_HANDED 0
#define LEFT_HANDED 1
#define CENTER_HANDED 2
#define SFL_CROSS_TRIGGER_1 0x00000001
#define SFL_CROSS_TRIGGER_2 0x00000002
#define SFL_CROSS_TRIGGER_3 0x00000004
#define SFL_CROSS_TRIGGER_4 0x00000008
#define SFL_CROSS_TRIGGER_5 0x00000010
#define SFL_CROSS_TRIGGER_6 0x00000020
#define SFL_CROSS_TRIGGER_7 0x00000040
#define SFL_CROSS_TRIGGER_8 0x00000080
#define SFL_CROSS_TRIGGER_MASK 0x000000ff
#define PNOISE_SELF 0
#define PNOISE_WEAPON 1
#define PNOISE_IMPACT 2
#define IT_WEAPON 1
#define IT_AMMO 2
#define IT_ARMOR 4
#define IT_STAY_COOP 8
#define IT_KEY 16
#define IT_POWERUP 32
#define WEAP_BLASTER 1
#define WEAP_SHOTGUN 2
#define WEAP_SUPERSHOTGUN 3
#define WEAP_MACHINEGUN 4
#define WEAP_CHAINGUN 5
#define WEAP_GRENADES 6
#define WEAP_GRENADELAUNCHER 7
#define WEAP_ROCKETLAUNCHER 8
#define WEAP_HYPERBLASTER 9
#define WEAP_RAILGUN 10
#define WEAP_BFG 11
#define WEAP_FLAREGUN 12
#define MOD_UNKNOWN 0
#define MOD_BLASTER 1
#define MOD_SHOTGUN 2
#define MOD_SSHOTGUN 3
#define MOD_MACHINEGUN 4
#define MOD_CHAINGUN 5
#define MOD_GRENADE 6
#define MOD_G_SPLASH 7
#define MOD_ROCKET 8
#define MOD_R_SPLASH 9
#define MOD_HYPERBLASTER 10
#define MOD_RAILGUN 11
#define MOD_BFG_LASER 12
#define MOD_BFG_BLAST 13
#define MOD_BFG_EFFECT 14
#define MOD_HANDGRENADE 15
#define MOD_HG_SPLASH 16
#define MOD_WATER 17
#define MOD_SLIME 18
#define MOD_LAVA 19
#define MOD_CRUSH 20
#define MOD_TELEFRAG 21
#define MOD_FALLING 22
#define MOD_SUICIDE 23
#define MOD_HELD_GRENADE 24
#define MOD_EXPLOSIVE 25
#define MOD_BARREL 26
#define MOD_BOMB 27
#define MOD_EXIT 28
#define MOD_SPLASH 29
#define MOD_TARGET_LASER 30
#define MOD_TRIGGER_HURT 31
#define MOD_HIT 32
#define MOD_TARGET_BLASTER 33
#define MOD_FRIENDLY_FIRE 0x8000000
#define FOFS(x) q_offsetof(edict_t, x)
#define STOFS(x) q_offsetof(spawn_temp_t, x)
#define LLOFS(x) q_offsetof(level_locals_t, x)
#define GLOFS(x) q_offsetof(game_locals_t, x)
#define CLOFS(x) q_offsetof(gclient_t, x)
#define random() ((rand () & 0x7fff) / ((float)0x7fff))
#define crandom() (2.0 * (random() - 0.5))
#define world (&g_edicts[0])
#define ITEM_TRIGGER_SPAWN 0x00000001
#define ITEM_NO_TOUCH 0x00000002
#define DROPPED_ITEM 0x00010000
#define DROPPED_PLAYER_ITEM 0x00020000
#define ITEM_TARGETS_USED 0x00040000
#define ITEM_INDEX(x) ((x)-itemlist)
#define DAMAGE_RADIUS 0x00000001
#define DAMAGE_NO_ARMOR 0x00000002
#define DAMAGE_ENERGY 0x00000004
#define DAMAGE_NO_KNOCKBACK 0x00000008
#define DAMAGE_BULLET 0x00000010
#define DAMAGE_NO_PROTECTION 0x00000020
#define DEFAULT_BULLET_HSPREAD 300
#define DEFAULT_BULLET_VSPREAD 500
#define DEFAULT_SHOTGUN_HSPREAD 1000
#define DEFAULT_SHOTGUN_VSPREAD 500
#define DEFAULT_DEATHMATCH_SHOTGUN_COUNT 12
#define DEFAULT_SHOTGUN_COUNT 12
#define DEFAULT_SSHOTGUN_COUNT 20
#define CLOCK_MESSAGE_SIZE 16
#define ANIM_BASIC 0
#define ANIM_WAVE 1
#define ANIM_JUMP 2
#define ANIM_PAIN 3
#define ANIM_ATTACK 4
#define ANIM_DEATH 5
#define ANIM_REVERSE 6
Typedefs
typedef struct gitem_s gitem_t
Enumerations
enum damage_t { DAMAGE_NO, DAMAGE_YES, DAMAGE_AIM }
enum weaponstate_t { WEAPON_READY, WEAPON_ACTIVATING, WEAPON_DROPPING, WEAPON_FIRING }
enum ammo_t {
AMMO_BULLETS, AMMO_SHELLS, AMMO_ROCKETS, AMMO_GRENADES,
AMMO_CELLS, AMMO_SLUGS
}
enum movetype_t {
MOVETYPE_NONE, MOVETYPE_NOCLIP, MOVETYPE_PUSH, MOVETYPE_STOP,
MOVETYPE_WALK, MOVETYPE_STEP, MOVETYPE_FLY, MOVETYPE_TOSS,
MOVETYPE_FLYMISSILE, MOVETYPE_BOUNCE
}
enum fieldtype_t {
F_BAD, F_BYTE, F_SHORT, F_INT,
F_FLOAT, F_LSTRING, F_GSTRING, F_ZSTRING,
F_VECTOR, F_ANGLEHACK, F_EDICT, F_ITEM,
F_CLIENT, F_FUNCTION, F_POINTER, F_IGNORE
}
Functions
void Cmd_Help_f (edict_t *ent)
void Cmd_Score_f (edict_t *ent)
void PrecacheItem (gitem_t *it)
void InitItems (void)
void SetItemNames (void)
gitem_t * FindItem (char *pickup_name)
gitem_t * FindItemByClassname (char *classname)
edict_t * Drop_Item (edict_t *ent, gitem_t *item)
void SetRespawn (edict_t *ent, float delay)
void ChangeWeapon (edict_t *ent)
void SpawnItem (edict_t *ent, gitem_t *item)
void Think_Weapon (edict_t *ent)
int ArmorIndex (edict_t *ent)
int PowerArmorType (edict_t *ent)
gitem_t * GetItemByIndex (int index)
qboolean Add_Ammo (edict_t *ent, gitem_t *item, int count)
void Touch_Item (edict_t *ent, edict_t *other, cplane_t *plane, csurface_t *surf)
qboolean KillBox (edict_t *ent)
void G_ProjectSource (const vec3_t point, const vec3_t distance, const vec3_t forward, const vec3_t right, vec3_t result)
edict_t * G_Find (edict_t *from, int fieldofs, char *match)
edict_t * findradius (edict_t *from, vec3_t org, float rad)
edict_t * G_PickTarget (char *targetname)
void G_UseTargets (edict_t *ent, edict_t *activator)
void G_SetMovedir (vec3_t angles, vec3_t movedir)
void G_InitEdict (edict_t *e)
edict_t * G_Spawn (void)
void G_FreeEdict (edict_t *e)
void G_TouchTriggers (edict_t *ent)
void G_TouchSolids (edict_t *ent)
char * G_CopyString (char *in)
float * tv (float x, float y, float z)
char * vtos (vec3_t v)
float vectoyaw (vec3_t vec)
void vectoangles (vec3_t vec, vec3_t angles)
qboolean OnSameTeam (edict_t *ent1, edict_t *ent2)
qboolean CanDamage (edict_t *targ, edict_t *inflictor)
void T_Damage (edict_t *targ, edict_t *inflictor, edict_t *attacker, vec3_t dir, vec3_t point, vec3_t normal, int damage, int knockback, int dflags, int mod)
void T_RadiusDamage (edict_t *inflictor, edict_t *attacker, float damage, edict_t *ignore, float radius, int mod)
void monster_fire_bullet (edict_t *self, vec3_t start, vec3_t dir, int damage, int kick, int hspread, int vspread, int flashtype)
void monster_fire_shotgun (edict_t *self, vec3_t start, vec3_t aimdir, int damage, int kick, int hspread, int vspread, int count, int flashtype)
void monster_fire_blaster (edict_t *self, vec3_t start, vec3_t dir, int damage, int speed, int flashtype, int effect)
void monster_fire_grenade (edict_t *self, vec3_t start, vec3_t aimdir, int damage, int speed, int flashtype)
void monster_fire_rocket (edict_t *self, vec3_t start, vec3_t dir, int damage, int speed, int flashtype)
void monster_fire_railgun (edict_t *self, vec3_t start, vec3_t aimdir, int damage, int kick, int flashtype)
void monster_fire_bfg (edict_t *self, vec3_t start, vec3_t aimdir, int damage, int speed, int kick, float damage_radius, int flashtype)
void M_droptofloor (edict_t *ent)
void monster_think (edict_t *self)
void walkmonster_start (edict_t *self)
void swimmonster_start (edict_t *self)
void flymonster_start (edict_t *self)
void AttackFinished (edict_t *self, float time)
void monster_death_use (edict_t *self)
void M_CatagorizePosition (edict_t *ent)
qboolean M_CheckAttack (edict_t *self)
void M_FlyCheck (edict_t *self)
void M_CheckGround (edict_t *ent)
void ThrowHead (edict_t *self, char *gibname, int damage, int type)
void ThrowClientHead (edict_t *self, int damage)
void ThrowGib (edict_t *self, char *gibname, int damage, int type)
void BecomeExplosion1 (edict_t *self)
void func_clock_think (edict_t *self)
void func_clock_use (edict_t *self, edict_t *other, edict_t *activator)
void AI_SetSightClient (void)
void ai_stand (edict_t *self, float dist)
void ai_move (edict_t *self, float dist)
void ai_walk (edict_t *self, float dist)
void ai_turn (edict_t *self, float dist)
void ai_run (edict_t *self, float dist)
void ai_charge (edict_t *self, float dist)
int range (edict_t *self, edict_t *other)
void FoundTarget (edict_t *self)
qboolean infront (edict_t *self, edict_t *other)
qboolean visible (edict_t *self, edict_t *other)
qboolean FacingIdeal (edict_t *self)
void ThrowDebris (edict_t *self, char *modelname, float speed, vec3_t origin)
qboolean fire_hit (edict_t *self, vec3_t aim, int damage, int kick)
void fire_bullet (edict_t *self, vec3_t start, vec3_t aimdir, int damage, int kick, int hspread, int vspread, int mod)
void fire_shotgun (edict_t *self, vec3_t start, vec3_t aimdir, int damage, int kick, int hspread, int vspread, int count, int mod)
void fire_blaster (edict_t *self, vec3_t start, vec3_t aimdir, int damage, int speed, int effect, qboolean hyper)
void fire_grenade (edict_t *self, vec3_t start, vec3_t aimdir, int damage, int speed, float timer, float damage_radius)
void fire_grenade2 (edict_t *self, vec3_t start, vec3_t aimdir, int damage, int speed, float timer, float damage_radius, qboolean held)
void fire_rocket (edict_t *self, vec3_t start, vec3_t dir, int damage, int speed, float damage_radius, int radius_damage)
void fire_rail (edict_t *self, vec3_t start, vec3_t aimdir, int damage, int kick)
void fire_bfg (edict_t *self, vec3_t start, vec3_t dir, int damage, int speed, float damage_radius)
void PlayerTrail_Init (void)
void PlayerTrail_Add (vec3_t spot)
void PlayerTrail_New (vec3_t spot)
edict_t * PlayerTrail_PickFirst (edict_t *self)
edict_t * PlayerTrail_PickNext (edict_t *self)
edict_t * PlayerTrail_LastSpot (void)
void respawn (edict_t *ent)
void BeginIntermission (edict_t *targ)
void PutClientInServer (edict_t *ent)
void InitClientPersistant (gclient_t *client)
void InitClientResp (gclient_t *client)
void InitBodyQue (void)
void ClientBeginServerFrame (edict_t *ent)
void player_pain (edict_t *self, edict_t *other, float kick, int damage)
void player_die (edict_t *self, edict_t *inflictor, edict_t *attacker, int damage, vec3_t point)
void ServerCommand (void)
qboolean SV_FilterPacket (char *from)
void ClientEndServerFrame (edict_t *ent)
void MoveClientToIntermission (edict_t *client)
void G_SetStats (edict_t *ent)
void G_SetSpectatorStats (edict_t *ent)
void G_CheckChaseStats (edict_t *ent)
void ValidateSelectedItem (edict_t *ent)
void DeathmatchScoreboardMessage (edict_t *client, edict_t *killer)
void PlayerNoise (edict_t *who, vec3_t where, int type)
qboolean M_CheckBottom (edict_t *ent)
qboolean M_walkmove (edict_t *ent, float yaw, float dist)
void M_MoveToGoal (edict_t *ent, float dist)
void M_ChangeYaw (edict_t *ent)
void G_RunEntity (edict_t *ent)
void SaveClientData (void)
void FetchClientEntData (edict_t *ent)
void UpdateChaseCam (edict_t *ent)
void ChaseNext (edict_t *ent)
void ChasePrev (edict_t *ent)
void GetChaseTarget (edict_t *ent)
Variables
game_locals_t game
level_locals_t level
game_import_t gi
game_export_t globals
spawn_temp_t st
int sm_meat_index
int snd_fry
int meansOfDeath
edict_t * g_edicts
cvar_t * maxentities
cvar_t * deathmatch
cvar_t * coop
cvar_t * dmflags
cvar_t * skill
cvar_t * fraglimit
cvar_t * timelimit
cvar_t * password
cvar_t * spectator_password
cvar_t * needpass
cvar_t * g_select_empty
cvar_t * dedicated
cvar_t * nomonsters
cvar_t * filterban
cvar_t * sv_gravity
cvar_t * sv_maxvelocity
cvar_t * gun_x
cvar_t * gun_y
cvar_t * gun_z
cvar_t * sv_rollspeed
cvar_t * sv_rollangle
cvar_t * run_pitch
cvar_t * run_roll
cvar_t * bob_up
cvar_t * bob_pitch
cvar_t * bob_roll
cvar_t * sv_cheats
cvar_t * maxclients
cvar_t * maxspectators
cvar_t * flood_msgs
cvar_t * flood_persecond
cvar_t * flood_waitdelay
cvar_t * sv_maplist
cvar_t * sv_features
cvar_t * sv_flaregun
gitem_t itemlist []
Macro Definition Documentation
AI_BRUTAL
#define AI_BRUTAL 0x00000200
Definition at line 135 of file g_local.h.
AI_COMBAT_POINT
#define AI_COMBAT_POINT 0x00001000
Definition at line 138 of file g_local.h.
AI_DUCKED
#define AI_DUCKED 0x00000800
Definition at line 137 of file g_local.h.
AI_GOOD_GUY
#define AI_GOOD_GUY 0x00000100
Definition at line 134 of file g_local.h.
AI_HOLD_FRAME
#define AI_HOLD_FRAME 0x00000080
Definition at line 133 of file g_local.h.
AI_LOST_SIGHT
#define AI_LOST_SIGHT 0x00000008
Definition at line 129 of file g_local.h.
AI_MEDIC
#define AI_MEDIC 0x00002000
Definition at line 139 of file g_local.h.
AI_NOSTEP
#define AI_NOSTEP 0x00000400
Definition at line 136 of file g_local.h.
AI_PURSUE_NEXT
#define AI_PURSUE_NEXT 0x00000020
Definition at line 131 of file g_local.h.
AI_PURSUE_TEMP
#define AI_PURSUE_TEMP 0x00000040
Definition at line 132 of file g_local.h.
AI_PURSUIT_LAST_SEEN
#define AI_PURSUIT_LAST_SEEN 0x00000010
Definition at line 130 of file g_local.h.
AI_RESURRECTING
#define AI_RESURRECTING 0x00004000
Definition at line 140 of file g_local.h.
AI_SOUND_TARGET
#define AI_SOUND_TARGET 0x00000004
Definition at line 128 of file g_local.h.
AI_STAND_GROUND
#define AI_STAND_GROUND 0x00000001
Definition at line 126 of file g_local.h.
AI_TEMP_STAND_GROUND
#define AI_TEMP_STAND_GROUND 0x00000002
Definition at line 127 of file g_local.h.
ANIM_ATTACK
#define ANIM_ATTACK 4
Definition at line 815 of file g_local.h.
ANIM_BASIC
#define ANIM_BASIC 0
Definition at line 811 of file g_local.h.
ANIM_DEATH
#define ANIM_DEATH 5
Definition at line 816 of file g_local.h.
ANIM_JUMP
#define ANIM_JUMP 2
Definition at line 813 of file g_local.h.
ANIM_PAIN
#define ANIM_PAIN 3
Definition at line 814 of file g_local.h.
ANIM_REVERSE
#define ANIM_REVERSE 6
Definition at line 817 of file g_local.h.
ANIM_WAVE
#define ANIM_WAVE 1
Definition at line 812 of file g_local.h.
ARMOR_BODY
#define ARMOR_BODY 3
Definition at line 152 of file g_local.h.
ARMOR_COMBAT
#define ARMOR_COMBAT 2
Definition at line 151 of file g_local.h.
ARMOR_JACKET
#define ARMOR_JACKET 1
Definition at line 150 of file g_local.h.
ARMOR_NONE
#define ARMOR_NONE 0
Definition at line 149 of file g_local.h.
ARMOR_SHARD
#define ARMOR_SHARD 4
Definition at line 153 of file g_local.h.
AS_MELEE
#define AS_MELEE 3
Definition at line 145 of file g_local.h.
AS_MISSILE
#define AS_MISSILE 4
Definition at line 146 of file g_local.h.
AS_SLIDING
#define AS_SLIDING 2
Definition at line 144 of file g_local.h.
AS_STRAIGHT
#define AS_STRAIGHT 1
Definition at line 143 of file g_local.h.
BODY_QUEUE_SIZE
#define BODY_QUEUE_SIZE 8
Definition at line 84 of file g_local.h.
CENTER_HANDED
#define CENTER_HANDED 2
Definition at line 163 of file g_local.h.
CLOCK_MESSAGE_SIZE
#define CLOCK_MESSAGE_SIZE 16
Definition at line 692 of file g_local.h.
CLOFS
#define CLOFS (x) q_offsetof(gclient_t, x)
Definition at line 502 of file g_local.h.
crandom
#define crandom () (2.0 * (random() - 0.5))
Definition at line 505 of file g_local.h.
DAMAGE_BULLET
#define DAMAGE_BULLET 0x00000010
Definition at line 651 of file g_local.h.
DAMAGE_ENERGY
#define DAMAGE_ENERGY 0x00000004
Definition at line 649 of file g_local.h.
DAMAGE_NO_ARMOR
#define DAMAGE_NO_ARMOR 0x00000002
Definition at line 648 of file g_local.h.
DAMAGE_NO_KNOCKBACK
#define DAMAGE_NO_KNOCKBACK 0x00000008
Definition at line 650 of file g_local.h.
DAMAGE_NO_PROTECTION
#define DAMAGE_NO_PROTECTION 0x00000020
Definition at line 652 of file g_local.h.
DAMAGE_RADIUS
#define DAMAGE_RADIUS 0x00000001
Definition at line 647 of file g_local.h.
DAMAGE_TIME
#define DAMAGE_TIME 0.5
Definition at line 46 of file g_local.h.
DEAD_DEAD
#define DEAD_DEAD 2
Definition at line 112 of file g_local.h.
DEAD_DYING
#define DEAD_DYING 1
Definition at line 111 of file g_local.h.
DEAD_NO
#define DEAD_NO 0
Definition at line 110 of file g_local.h.
DEAD_RESPAWNABLE
#define DEAD_RESPAWNABLE 3
Definition at line 113 of file g_local.h.
DEFAULT_BULLET_HSPREAD
#define DEFAULT_BULLET_HSPREAD 300
Definition at line 654 of file g_local.h.
DEFAULT_BULLET_VSPREAD
#define DEFAULT_BULLET_VSPREAD 500
Definition at line 655 of file g_local.h.
DEFAULT_DEATHMATCH_SHOTGUN_COUNT
#define DEFAULT_DEATHMATCH_SHOTGUN_COUNT 12
Definition at line 658 of file g_local.h.
DEFAULT_SHOTGUN_COUNT
#define DEFAULT_SHOTGUN_COUNT 12
Definition at line 659 of file g_local.h.
DEFAULT_SHOTGUN_HSPREAD
#define DEFAULT_SHOTGUN_HSPREAD 1000
Definition at line 656 of file g_local.h.
DEFAULT_SHOTGUN_VSPREAD
#define DEFAULT_SHOTGUN_VSPREAD 500
Definition at line 657 of file g_local.h.
DEFAULT_SSHOTGUN_COUNT
#define DEFAULT_SSHOTGUN_COUNT 20
Definition at line 660 of file g_local.h.
DROPPED_ITEM
#define DROPPED_ITEM 0x00010000
Definition at line 557 of file g_local.h.
DROPPED_PLAYER_ITEM
#define DROPPED_PLAYER_ITEM 0x00020000
Definition at line 558 of file g_local.h.
FALL_TIME
#define FALL_TIME 0.3
Definition at line 47 of file g_local.h.
FL_FLY
#define FL_FLY 0x00000001
Definition at line 59 of file g_local.h.
FL_GODMODE
#define FL_GODMODE 0x00000010
Definition at line 63 of file g_local.h.
FL_IMMUNE_LASER
#define FL_IMMUNE_LASER 0x00000004
Definition at line 61 of file g_local.h.
FL_IMMUNE_LAVA
#define FL_IMMUNE_LAVA 0x00000080
Definition at line 66 of file g_local.h.
FL_IMMUNE_SLIME
#define FL_IMMUNE_SLIME 0x00000040
Definition at line 65 of file g_local.h.
FL_INWATER
#define FL_INWATER 0x00000008
Definition at line 62 of file g_local.h.
FL_NO_KNOCKBACK
#define FL_NO_KNOCKBACK 0x00000800
Definition at line 70 of file g_local.h.
FL_NOTARGET
#define FL_NOTARGET 0x00000020
Definition at line 64 of file g_local.h.
FL_PARTIALGROUND
#define FL_PARTIALGROUND 0x00000100
Definition at line 67 of file g_local.h.
FL_POWER_ARMOR
#define FL_POWER_ARMOR 0x00001000
Definition at line 71 of file g_local.h.
FL_RESPAWN
#define FL_RESPAWN 0x80000000
Definition at line 72 of file g_local.h.
FL_SWIM
#define FL_SWIM 0x00000002
Definition at line 60 of file g_local.h.
FL_TEAMSLAVE
#define FL_TEAMSLAVE 0x00000400
Definition at line 69 of file g_local.h.
FL_WATERJUMP
#define FL_WATERJUMP 0x00000200
Definition at line 68 of file g_local.h.
FOFS
#define FOFS (x) q_offsetof(edict_t, x)
Definition at line 498 of file g_local.h.
FRAMETIME
#define FRAMETIME 0.1
Definition at line 75 of file g_local.h.
G_FEATURES
#define G_FEATURES (GMF_PROPERINUSE|GMF_WANT_ALL_DISCONNECTS|GMF_ENHANCED_SAVEGAMES)
Definition at line 30 of file g_local.h.
GAME_INCLUDE
#define GAME_INCLUDE
Definition at line 26 of file g_local.h.
GAMEVERSION
#define GAMEVERSION "baseq2"
Definition at line 33 of file g_local.h.
GIB_METALLIC
#define GIB_METALLIC 1
Definition at line 123 of file g_local.h.
GIB_ORGANIC
#define GIB_ORGANIC 0
Definition at line 122 of file g_local.h.
GLOFS
#define GLOFS (x) q_offsetof(game_locals_t, x)
Definition at line 501 of file g_local.h.
IT_AMMO
#define IT_AMMO 2
Definition at line 212 of file g_local.h.
IT_ARMOR
#define IT_ARMOR 4
Definition at line 213 of file g_local.h.
IT_KEY
#define IT_KEY 16
Definition at line 215 of file g_local.h.
IT_POWERUP
#define IT_POWERUP 32
Definition at line 216 of file g_local.h.
IT_STAY_COOP
#define IT_STAY_COOP 8
Definition at line 214 of file g_local.h.
IT_WEAPON
#define IT_WEAPON 1
Definition at line 211 of file g_local.h.
ITEM_INDEX
#define ITEM_INDEX (x) ((x)-itemlist)
Definition at line 600 of file g_local.h.
ITEM_NO_TOUCH
#define ITEM_NO_TOUCH 0x00000002
Definition at line 554 of file g_local.h.
ITEM_TARGETS_USED
#define ITEM_TARGETS_USED 0x00040000
Definition at line 559 of file g_local.h.
ITEM_TRIGGER_SPAWN
#define ITEM_TRIGGER_SPAWN 0x00000001
Definition at line 553 of file g_local.h.
LEFT_HANDED
#define LEFT_HANDED 1
Definition at line 162 of file g_local.h.
LLOFS
#define LLOFS (x) q_offsetof(level_locals_t, x)
Definition at line 500 of file g_local.h.
MELEE_DISTANCE
#define MELEE_DISTANCE 80
Definition at line 82 of file g_local.h.
MOD_BARREL
#define MOD_BARREL 26
Definition at line 483 of file g_local.h.
MOD_BFG_BLAST
#define MOD_BFG_BLAST 13
Definition at line 470 of file g_local.h.
MOD_BFG_EFFECT
#define MOD_BFG_EFFECT 14
Definition at line 471 of file g_local.h.
MOD_BFG_LASER
#define MOD_BFG_LASER 12
Definition at line 469 of file g_local.h.
MOD_BLASTER
#define MOD_BLASTER 1
Definition at line 458 of file g_local.h.
MOD_BOMB
#define MOD_BOMB 27
Definition at line 484 of file g_local.h.
MOD_CHAINGUN
#define MOD_CHAINGUN 5
Definition at line 462 of file g_local.h.
MOD_CRUSH
#define MOD_CRUSH 20
Definition at line 477 of file g_local.h.
MOD_EXIT
#define MOD_EXIT 28
Definition at line 485 of file g_local.h.
MOD_EXPLOSIVE
#define MOD_EXPLOSIVE 25
Definition at line 482 of file g_local.h.
MOD_FALLING
#define MOD_FALLING 22
Definition at line 479 of file g_local.h.
MOD_FRIENDLY_FIRE
#define MOD_FRIENDLY_FIRE 0x8000000
Definition at line 491 of file g_local.h.
MOD_G_SPLASH
#define MOD_G_SPLASH 7
Definition at line 464 of file g_local.h.
MOD_GRENADE
#define MOD_GRENADE 6
Definition at line 463 of file g_local.h.
MOD_HANDGRENADE
#define MOD_HANDGRENADE 15
Definition at line 472 of file g_local.h.
MOD_HELD_GRENADE
#define MOD_HELD_GRENADE 24
Definition at line 481 of file g_local.h.
MOD_HG_SPLASH
#define MOD_HG_SPLASH 16
Definition at line 473 of file g_local.h.
MOD_HIT
#define MOD_HIT 32
Definition at line 489 of file g_local.h.
MOD_HYPERBLASTER
#define MOD_HYPERBLASTER 10
Definition at line 467 of file g_local.h.
MOD_LAVA
#define MOD_LAVA 19
Definition at line 476 of file g_local.h.
MOD_MACHINEGUN
#define MOD_MACHINEGUN 4
Definition at line 461 of file g_local.h.
MOD_R_SPLASH
#define MOD_R_SPLASH 9
Definition at line 466 of file g_local.h.
MOD_RAILGUN
#define MOD_RAILGUN 11
Definition at line 468 of file g_local.h.
MOD_ROCKET
#define MOD_ROCKET 8
Definition at line 465 of file g_local.h.
MOD_SHOTGUN
#define MOD_SHOTGUN 2
Definition at line 459 of file g_local.h.
MOD_SLIME
#define MOD_SLIME 18
Definition at line 475 of file g_local.h.
MOD_SPLASH
#define MOD_SPLASH 29
Definition at line 486 of file g_local.h.
MOD_SSHOTGUN
#define MOD_SSHOTGUN 3
Definition at line 460 of file g_local.h.
MOD_SUICIDE
#define MOD_SUICIDE 23
Definition at line 480 of file g_local.h.
MOD_TARGET_BLASTER
#define MOD_TARGET_BLASTER 33
Definition at line 490 of file g_local.h.
MOD_TARGET_LASER
#define MOD_TARGET_LASER 30
Definition at line 487 of file g_local.h.
MOD_TELEFRAG
#define MOD_TELEFRAG 21
Definition at line 478 of file g_local.h.
MOD_TRIGGER_HURT
#define MOD_TRIGGER_HURT 31
Definition at line 488 of file g_local.h.
MOD_UNKNOWN
#define MOD_UNKNOWN 0
Definition at line 457 of file g_local.h.
MOD_WATER
#define MOD_WATER 17
Definition at line 474 of file g_local.h.
PNOISE_IMPACT
#define PNOISE_IMPACT 2
Definition at line 181 of file g_local.h.
PNOISE_SELF
#define PNOISE_SELF 0
Definition at line 179 of file g_local.h.
PNOISE_WEAPON
#define PNOISE_WEAPON 1
Definition at line 180 of file g_local.h.
POWER_ARMOR_NONE
#define POWER_ARMOR_NONE 0
Definition at line 156 of file g_local.h.
POWER_ARMOR_SCREEN
#define POWER_ARMOR_SCREEN 1
Definition at line 157 of file g_local.h.
POWER_ARMOR_SHIELD
#define POWER_ARMOR_SHIELD 2
Definition at line 158 of file g_local.h.
random
#define random () ((rand () & 0x7fff) / ((float)0x7fff))
Definition at line 504 of file g_local.h.
RANGE_FAR
#define RANGE_FAR 3
Definition at line 119 of file g_local.h.
RANGE_MELEE
#define RANGE_MELEE 0
Definition at line 116 of file g_local.h.
RANGE_MID
#define RANGE_MID 2
Definition at line 118 of file g_local.h.
RANGE_NEAR
#define RANGE_NEAR 1
Definition at line 117 of file g_local.h.
RIGHT_HANDED
#define RIGHT_HANDED 0
Definition at line 161 of file g_local.h.
SFL_CROSS_TRIGGER_1
#define SFL_CROSS_TRIGGER_1 0x00000001
Definition at line 167 of file g_local.h.
SFL_CROSS_TRIGGER_2
#define SFL_CROSS_TRIGGER_2 0x00000002
Definition at line 168 of file g_local.h.
SFL_CROSS_TRIGGER_3
#define SFL_CROSS_TRIGGER_3 0x00000004
Definition at line 169 of file g_local.h.
SFL_CROSS_TRIGGER_4
#define SFL_CROSS_TRIGGER_4 0x00000008
Definition at line 170 of file g_local.h.
SFL_CROSS_TRIGGER_5
#define SFL_CROSS_TRIGGER_5 0x00000010
Definition at line 171 of file g_local.h.
SFL_CROSS_TRIGGER_6
#define SFL_CROSS_TRIGGER_6 0x00000020
Definition at line 172 of file g_local.h.
SFL_CROSS_TRIGGER_7
#define SFL_CROSS_TRIGGER_7 0x00000040
Definition at line 173 of file g_local.h.
SFL_CROSS_TRIGGER_8
#define SFL_CROSS_TRIGGER_8 0x00000080
Definition at line 174 of file g_local.h.
SFL_CROSS_TRIGGER_MASK
#define SFL_CROSS_TRIGGER_MASK 0x000000ff
Definition at line 175 of file g_local.h.
SPAWNFLAG_NOT_COOP
#define SPAWNFLAG_NOT_COOP 0x00001000
Definition at line 56 of file g_local.h.
SPAWNFLAG_NOT_DEATHMATCH
#define SPAWNFLAG_NOT_DEATHMATCH 0x00000800
Definition at line 55 of file g_local.h.
SPAWNFLAG_NOT_EASY
#define SPAWNFLAG_NOT_EASY 0x00000100
Definition at line 52 of file g_local.h.
SPAWNFLAG_NOT_HARD
#define SPAWNFLAG_NOT_HARD 0x00000400
Definition at line 54 of file g_local.h.
SPAWNFLAG_NOT_MEDIUM
#define SPAWNFLAG_NOT_MEDIUM 0x00000200
Definition at line 53 of file g_local.h.
STOFS
#define STOFS (x) q_offsetof(spawn_temp_t, x)
Definition at line 499 of file g_local.h.
svc_inventory
#define svc_inventory 5
Definition at line 40 of file g_local.h.
svc_layout
#define svc_layout 4
Definition at line 39 of file g_local.h.
svc_muzzleflash
#define svc_muzzleflash 1
Definition at line 36 of file g_local.h.
svc_muzzleflash2
#define svc_muzzleflash2 2
Definition at line 37 of file g_local.h.
svc_stufftext
#define svc_stufftext 11
Definition at line 41 of file g_local.h.
svc_temp_entity
#define svc_temp_entity 3
Definition at line 38 of file g_local.h.
TAG_GAME
#define TAG_GAME 765
Definition at line 78 of file g_local.h.
TAG_LEVEL
#define TAG_LEVEL 766
Definition at line 79 of file g_local.h.
WEAP_BFG
#define WEAP_BFG 11
Definition at line 229 of file g_local.h.
WEAP_BLASTER
#define WEAP_BLASTER 1
Definition at line 219 of file g_local.h.
WEAP_CHAINGUN
#define WEAP_CHAINGUN 5
Definition at line 223 of file g_local.h.
WEAP_FLAREGUN
#define WEAP_FLAREGUN 12
Definition at line 230 of file g_local.h.
WEAP_GRENADELAUNCHER
#define WEAP_GRENADELAUNCHER 7
Definition at line 225 of file g_local.h.
WEAP_GRENADES
#define WEAP_GRENADES 6
Definition at line 224 of file g_local.h.
WEAP_HYPERBLASTER
#define WEAP_HYPERBLASTER 9
Definition at line 227 of file g_local.h.
WEAP_MACHINEGUN
#define WEAP_MACHINEGUN 4
Definition at line 222 of file g_local.h.
WEAP_RAILGUN
#define WEAP_RAILGUN 10
Definition at line 228 of file g_local.h.
WEAP_ROCKETLAUNCHER
#define WEAP_ROCKETLAUNCHER 8
Definition at line 226 of file g_local.h.
WEAP_SHOTGUN
#define WEAP_SHOTGUN 2
Definition at line 220 of file g_local.h.
WEAP_SUPERSHOTGUN
#define WEAP_SUPERSHOTGUN 3
Definition at line 221 of file g_local.h.
world
#define world (&g_edicts[0])
Definition at line 550 of file g_local.h.
Typedef Documentation
gitem_t
typedef struct gitem_s gitem_t
Enumeration Type Documentation
ammo_t
enum ammo_t
Enumerator
AMMO_BULLETS
AMMO_SHELLS
AMMO_ROCKETS
AMMO_GRENADES
AMMO_CELLS
AMMO_SLUGS
Definition at line 99 of file g_local.h.
              {
     AMMO_BULLETS,
     AMMO_SHELLS,
     AMMO_ROCKETS,
     AMMO_GRENADES,
     AMMO_CELLS,
     AMMO_SLUGS
 } ammo_t;
damage_t
enum damage_t
Enumerator
DAMAGE_NO
DAMAGE_YES
DAMAGE_AIM
Definition at line 86 of file g_local.h.
              {
     DAMAGE_NO,
     DAMAGE_YES,         // will take damage if hit
     DAMAGE_AIM          // auto targeting recognizes this
 } damage_t;
fieldtype_t
enum fieldtype_t
Enumerator
F_BAD
F_BYTE
F_SHORT
F_INT
F_FLOAT
F_LSTRING
F_GSTRING
F_ZSTRING
F_VECTOR
F_ANGLEHACK
F_EDICT
F_ITEM
F_CLIENT
F_FUNCTION
F_POINTER
F_IGNORE
Definition at line 565 of file g_local.h.
              {
     F_BAD,
     F_BYTE,
     F_SHORT,
     F_INT,
     F_FLOAT,
     F_LSTRING,          // string on disk, pointer in memory, TAG_LEVEL
     F_GSTRING,          // string on disk, pointer in memory, TAG_GAME
     F_ZSTRING,          // string on disk, string in memory
     F_VECTOR,
     F_ANGLEHACK,
     F_EDICT,            // index on disk, pointer in memory
     F_ITEM,             // index on disk, pointer in memory
     F_CLIENT,           // index on disk, pointer in memory
     F_FUNCTION,
     F_POINTER,
     F_IGNORE
 } fieldtype_t;
movetype_t
enum movetype_t
Enumerator
MOVETYPE_NONE
MOVETYPE_NOCLIP
MOVETYPE_PUSH
MOVETYPE_STOP
MOVETYPE_WALK
MOVETYPE_STEP
MOVETYPE_FLY
MOVETYPE_TOSS
MOVETYPE_FLYMISSILE
MOVETYPE_BOUNCE
Definition at line 185 of file g_local.h.
              {
     MOVETYPE_NONE,          // never moves
     MOVETYPE_NOCLIP,        // origin and angles change with no interaction
     MOVETYPE_PUSH,          // no clip to world, push on box contact
     MOVETYPE_STOP,          // no clip to world, stops on box contact
     MOVETYPE_WALK,          // gravity
     MOVETYPE_STEP,          // gravity, special edge handling
     MOVETYPE_FLY,
     MOVETYPE_TOSS,          // gravity
     MOVETYPE_FLYMISSILE,    // extra size to monsters
     MOVETYPE_BOUNCE
 } movetype_t;
weaponstate_t
enum weaponstate_t
Enumerator
WEAPON_READY
WEAPON_ACTIVATING
WEAPON_DROPPING
WEAPON_FIRING
Definition at line 92 of file g_local.h.
              {
     WEAPON_READY,
     WEAPON_ACTIVATING,
     WEAPON_DROPPING,
     WEAPON_FIRING
 } weaponstate_t;
Function Documentation
Add_Ammo()
qboolean Add_Ammo (edict_t * ent, gitem_t * item, int count)
Definition at line 426 of file g_items.c.
 {
     int         index;
     int         max;
     if (!ent->client)
         return qfalse;
     if (item->tag == AMMO_BULLETS)
         max = ent->client->pers.max_bullets;
     else if (item->tag == AMMO_SHELLS)
         max = ent->client->pers.max_shells;
     else if (item->tag == AMMO_ROCKETS)
         max = ent->client->pers.max_rockets;
     else if (item->tag == AMMO_GRENADES)
         max = ent->client->pers.max_grenades;
     else if (item->tag == AMMO_CELLS)
         max = ent->client->pers.max_cells;
     else if (item->tag == AMMO_SLUGS)
         max = ent->client->pers.max_slugs;
     else
         return qfalse;
     index = ITEM_INDEX(item);
     if (ent->client->pers.inventory[index] == max)
         return qfalse;
     ent->client->pers.inventory[index] += count;
     if (ent->client->pers.inventory[index] > max)
         ent->client->pers.inventory[index] = max;
     return qtrue;
 }
Referenced by Cmd_Give_f(), Pickup_Ammo(), and Pickup_Weapon().
ai_charge()
void ai_charge (edict_t * self, float dist)
Definition at line 175 of file g_ai.c.
 {
     vec3_t  v;
     VectorSubtract(self->enemy->s.origin, self->s.origin, v);
     self->ideal_yaw = vectoyaw(v);
     M_ChangeYaw(self);
     if (dist)
         M_walkmove(self, self->s.angles[YAW], dist);
 }
ai_move()
void ai_move (edict_t * self, float dist)
Definition at line 86 of file g_ai.c.
 {
     M_walkmove(self, self->s.angles[YAW], dist);
 }
ai_run()
void ai_run (edict_t * self, float dist)
Definition at line 821 of file g_ai.c.
 {
     vec3_t      v;
     edict_t     *tempgoal;
     edict_t     *save;
     qboolean    new;
     edict_t     *marker;
     float       d1, d2;
     trace_t     tr;
     vec3_t      v_forward, v_right;
     float       left, center, right;
     vec3_t      left_target, right_target;
     // if we're going to a combat point, just proceed
     if (self->monsterinfo.aiflags & AI_COMBAT_POINT) {
         M_MoveToGoal(self, dist);
         return;
     }
     if (self->monsterinfo.aiflags & AI_SOUND_TARGET) {
         VectorSubtract(self->s.origin, self->enemy->s.origin, v);
         if (VectorLength(v) < 64) {
             self->monsterinfo.aiflags |= (AI_STAND_GROUND | AI_TEMP_STAND_GROUND);
             self->monsterinfo.stand(self);
             return;
         }
         M_MoveToGoal(self, dist);
         if (!FindTarget(self))
             return;
     }
     if (ai_checkattack(self, dist))
         return;
     if (self->monsterinfo.attack_state == AS_SLIDING) {
         ai_run_slide(self, dist);
         return;
     }
     if (enemy_vis) {
 //      if (self.aiflags & AI_LOST_SIGHT)
 //          dprint("regained sight\n");
         M_MoveToGoal(self, dist);
         self->monsterinfo.aiflags &= ~AI_LOST_SIGHT;
         VectorCopy(self->enemy->s.origin, self->monsterinfo.last_sighting);
         self->monsterinfo.trail_time = level.time;
         return;
     }
     // coop will change to another enemy if visible
     if (coop->value) {
         // FIXME: insane guys get mad with this, which causes crashes!
         if (FindTarget(self))
             return;
     }
     if ((self->monsterinfo.search_time) && (level.time > (self->monsterinfo.search_time + 20))) {
         M_MoveToGoal(self, dist);
         self->monsterinfo.search_time = 0;
 //      dprint("search timeout\n");
         return;
     }
     save = self->goalentity;
     tempgoal = G_Spawn();
     self->goalentity = tempgoal;
     new = qfalse;
     if (!(self->monsterinfo.aiflags & AI_LOST_SIGHT)) {
         // just lost sight of the player, decide where to go first
 //      dprint("lost sight of player, last seen at "); dprint(vtos(self.last_sighting)); dprint("\n");
         self->monsterinfo.aiflags |= (AI_LOST_SIGHT | AI_PURSUIT_LAST_SEEN);
         self->monsterinfo.aiflags &= ~(AI_PURSUE_NEXT | AI_PURSUE_TEMP);
         new = qtrue;
     }
     if (self->monsterinfo.aiflags & AI_PURSUE_NEXT) {
         self->monsterinfo.aiflags &= ~AI_PURSUE_NEXT;
 //      dprint("reached current goal: "); dprint(vtos(self.origin)); dprint(" "); dprint(vtos(self.last_sighting)); dprint(" "); dprint(ftos(vlen(self.origin - self.last_sighting))); dprint("\n");
         // give ourself more time since we got this far
         self->monsterinfo.search_time = level.time + 5;
         if (self->monsterinfo.aiflags & AI_PURSUE_TEMP) {
 //          dprint("was temp goal; retrying original\n");
             self->monsterinfo.aiflags &= ~AI_PURSUE_TEMP;
             marker = NULL;
             VectorCopy(self->monsterinfo.saved_goal, self->monsterinfo.last_sighting);
             new = qtrue;
         } else if (self->monsterinfo.aiflags & AI_PURSUIT_LAST_SEEN) {
             self->monsterinfo.aiflags &= ~AI_PURSUIT_LAST_SEEN;
             marker = PlayerTrail_PickFirst(self);
         } else {
             marker = PlayerTrail_PickNext(self);
         }
         if (marker) {
             VectorCopy(marker->s.origin, self->monsterinfo.last_sighting);
             self->monsterinfo.trail_time = marker->timestamp;
             self->s.angles[YAW] = self->ideal_yaw = marker->s.angles[YAW];
 //          dprint("heading is "); dprint(ftos(self.ideal_yaw)); dprint("\n");
 //          debug_drawline(self.origin, self.last_sighting, 52);
             new = qtrue;
         }
     }
     VectorSubtract(self->s.origin, self->monsterinfo.last_sighting, v);
     d1 = VectorLength(v);
     if (d1 <= dist) {
         self->monsterinfo.aiflags |= AI_PURSUE_NEXT;
         dist = d1;
     }
     VectorCopy(self->monsterinfo.last_sighting, self->goalentity->s.origin);
     if (new) {
 //      gi.dprintf("checking for course correction\n");
         tr = gi.trace(self->s.origin, self->mins, self->maxs, self->monsterinfo.last_sighting, self, MASK_PLAYERSOLID);
         if (tr.fraction < 1) {
             VectorSubtract(self->goalentity->s.origin, self->s.origin, v);
             d1 = VectorLength(v);
             center = tr.fraction;
             d2 = d1 * ((center + 1) / 2);
             self->s.angles[YAW] = self->ideal_yaw = vectoyaw(v);
             AngleVectors(self->s.angles, v_forward, v_right, NULL);
             VectorSet(v, d2, -16, 0);
             G_ProjectSource(self->s.origin, v, v_forward, v_right, left_target);
             tr = gi.trace(self->s.origin, self->mins, self->maxs, left_target, self, MASK_PLAYERSOLID);
             left = tr.fraction;
             VectorSet(v, d2, 16, 0);
             G_ProjectSource(self->s.origin, v, v_forward, v_right, right_target);
             tr = gi.trace(self->s.origin, self->mins, self->maxs, right_target, self, MASK_PLAYERSOLID);
             right = tr.fraction;
             center = (d1 * center) / d2;
             if (left >= center && left > right) {
                 if (left < 1) {
                     VectorSet(v, d2 * left * 0.5, -16, 0);
                     G_ProjectSource(self->s.origin, v, v_forward, v_right, left_target);
 //                  gi.dprintf("incomplete path, go part way and adjust again\n");
                 }
                 VectorCopy(self->monsterinfo.last_sighting, self->monsterinfo.saved_goal);
                 self->monsterinfo.aiflags |= AI_PURSUE_TEMP;
                 VectorCopy(left_target, self->goalentity->s.origin);
                 VectorCopy(left_target, self->monsterinfo.last_sighting);
                 VectorSubtract(self->goalentity->s.origin, self->s.origin, v);
                 self->s.angles[YAW] = self->ideal_yaw = vectoyaw(v);
 //              gi.dprintf("adjusted left\n");
 //              debug_drawline(self.origin, self.last_sighting, 152);
             } else if (right >= center && right > left) {
                 if (right < 1) {
                     VectorSet(v, d2 * right * 0.5, 16, 0);
                     G_ProjectSource(self->s.origin, v, v_forward, v_right, right_target);
 //                  gi.dprintf("incomplete path, go part way and adjust again\n");
                 }
                 VectorCopy(self->monsterinfo.last_sighting, self->monsterinfo.saved_goal);
                 self->monsterinfo.aiflags |= AI_PURSUE_TEMP;
                 VectorCopy(right_target, self->goalentity->s.origin);
                 VectorCopy(right_target, self->monsterinfo.last_sighting);
                 VectorSubtract(self->goalentity->s.origin, self->s.origin, v);
                 self->s.angles[YAW] = self->ideal_yaw = vectoyaw(v);
 //              gi.dprintf("adjusted right\n");
 //              debug_drawline(self.origin, self.last_sighting, 152);
             }
         }
 //      else gi.dprintf("course was fine\n");
     }
     M_MoveToGoal(self, dist);
     G_FreeEdict(tempgoal);
     if (self)
         self->goalentity = save;
 }
AI_SetSightClient()
void AI_SetSightClient (void)
Definition at line 47 of file g_ai.c.
 {
     edict_t *ent;
     int     start, check;
     if (level.sight_client == NULL)
         start = 1;
     else
         start = level.sight_client - g_edicts;
     check = start;
     while (1) {
         check++;
         if (check > game.maxclients)
             check = 1;
         ent = &g_edicts[check];
         if (ent->inuse
             && ent->health > 0
             && !(ent->flags & FL_NOTARGET)) {
             level.sight_client = ent;
             return;     // got one
         }
         if (check == start) {
             level.sight_client = NULL;
             return;     // nobody to see
         }
     }
 }
Referenced by G_RunFrame().
ai_stand()
void ai_stand (edict_t * self, float dist)
Definition at line 100 of file g_ai.c.
 {
     vec3_t  v;
     if (dist)
         M_walkmove(self, self->s.angles[YAW], dist);
     if (self->monsterinfo.aiflags & AI_STAND_GROUND) {
         if (self->enemy) {
             VectorSubtract(self->enemy->s.origin, self->s.origin, v);
             self->ideal_yaw = vectoyaw(v);
             if (self->s.angles[YAW] != self->ideal_yaw && self->monsterinfo.aiflags & AI_TEMP_STAND_GROUND) {
                 self->monsterinfo.aiflags &= ~(AI_STAND_GROUND | AI_TEMP_STAND_GROUND);
                 self->monsterinfo.run(self);
             }
             M_ChangeYaw(self);
             ai_checkattack(self, 0);
         } else
             FindTarget(self);
         return;
     }
     if (FindTarget(self))
         return;
     if (level.time > self->monsterinfo.pausetime) {
         self->monsterinfo.walk(self);
         return;
     }
     if (!(self->spawnflags & 1) && (self->monsterinfo.idle) && (level.time > self->monsterinfo.idle_time)) {
         if (self->monsterinfo.idle_time) {
             self->monsterinfo.idle(self);
             self->monsterinfo.idle_time = level.time + 15 + random() * 15;
         } else {
             self->monsterinfo.idle_time = level.time + random() * 15;
         }
     }
 }
ai_turn()
void ai_turn (edict_t * self, float dist)
Definition at line 196 of file g_ai.c.
 {
     if (dist)
         M_walkmove(self, self->s.angles[YAW], dist);
     if (FindTarget(self))
         return;
     M_ChangeYaw(self);
 }
ai_walk()
void ai_walk (edict_t * self, float dist)
Definition at line 148 of file g_ai.c.
 {
     M_MoveToGoal(self, dist);
     // check for noticing a player
     if (FindTarget(self))
         return;
     if ((self->monsterinfo.search) && (level.time > self->monsterinfo.idle_time)) {
         if (self->monsterinfo.idle_time) {
             self->monsterinfo.search(self);
             self->monsterinfo.idle_time = level.time + 15 + random() * 15;
         } else {
             self->monsterinfo.idle_time = level.time + random() * 15;
         }
     }
 }
ArmorIndex()
int ArmorIndex (edict_t * ent)
Definition at line 563 of file g_items.c.
 {
     if (!ent->client)
         return 0;
     if (ent->client->pers.inventory[jacket_armor_index] > 0)
         return jacket_armor_index;
     if (ent->client->pers.inventory[combat_armor_index] > 0)
         return combat_armor_index;
     if (ent->client->pers.inventory[body_armor_index] > 0)
         return body_armor_index;
     return 0;
 }
Referenced by CheckArmor(), G_SetStats(), and Pickup_Armor().
AttackFinished()
void AttackFinished (edict_t * self, float time)
Definition at line 133 of file g_monster.c.
 {
     self->monsterinfo.attack_finished = level.time + time;
 }
Referenced by HuntTarget().
BecomeExplosion1()
void BecomeExplosion1 (edict_t * self)
Definition at line 297 of file g_misc.c.
 {
     gi.WriteByte(svc_temp_entity);
     gi.WriteByte(TE_EXPLOSION1);
     gi.WritePosition(self->s.origin);
     gi.multicast(self->s.origin, MULTICAST_PVS);
     G_FreeEdict(self);
 }
Referenced by barrel_explode(), door_blocked(), door_secret_blocked(), floater_die(), flyer_die(), func_explosive_explode(), hover_deadthink(), plat_blocked(), and train_blocked().
BeginIntermission()
void BeginIntermission (edict_t * targ)
Definition at line 70 of file p_hud.c.
 {
     int     i, n;
     edict_t *ent, *client;
     if (level.intermissiontime)
         return;     // already activated
     game.autosaved = qfalse;
     // respawn any dead clients
     for (i = 0 ; i < maxclients->value ; i++) {
         client = g_edicts + 1 + i;
         if (!client->inuse)
             continue;
         if (client->health <= 0)
             respawn(client);
     }
     level.intermissiontime = level.time;
     level.changemap = targ->map;
     if (strstr(level.changemap, "*")) {
         if (coop->value) {
             for (i = 0 ; i < maxclients->value ; i++) {
                 client = g_edicts + 1 + i;
                 if (!client->inuse)
                     continue;
                 // strip players of all keys between units
                 for (n = 0; n < MAX_ITEMS; n++) {
                     if (itemlist[n].flags & IT_KEY)
                         client->client->pers.inventory[n] = 0;
                 }
             }
         }
     } else {
         if (!deathmatch->value) {
             level.exitintermission = 1;     // go immediately to the next level
             return;
         }
     }
     level.exitintermission = 0;
     // find an intermission spot
     ent = G_Find(NULL, FOFS(classname), "info_player_intermission");
     if (!ent) {
         // the map creator forgot to put in an intermission point...
         ent = G_Find(NULL, FOFS(classname), "info_player_start");
         if (!ent)
             ent = G_Find(NULL, FOFS(classname), "info_player_deathmatch");
     } else {
         // chose one of four spots
         i = rand() & 3;
         while (i--) {
             ent = G_Find(ent, FOFS(classname), "info_player_intermission");
             if (!ent)   // wrap around the list
                 ent = G_Find(ent, FOFS(classname), "info_player_intermission");
         }
     }
     VectorCopy(ent->s.origin, level.intermission_origin);
     VectorCopy(ent->s.angles, level.intermission_angle);
     // move all clients to the intermission point
     for (i = 0 ; i < maxclients->value ; i++) {
         client = g_edicts + 1 + i;
         if (!client->inuse)
             continue;
         MoveClientToIntermission(client);
     }
 }
Referenced by EndDMLevel(), and use_target_changelevel().
CanDamage()
qboolean CanDamage (edict_t * targ, edict_t * inflictor)
Definition at line 30 of file g_combat.c.
 {
     vec3_t  dest;
     trace_t trace;
 // bmodels need special checking because their origin is 0,0,0
     if (targ->movetype == MOVETYPE_PUSH) {
         VectorAdd(targ->absmin, targ->absmax, dest);
         VectorScale(dest, 0.5, dest);
         trace = gi.trace(inflictor->s.origin, vec3_origin, vec3_origin, dest, inflictor, MASK_SOLID);
         if (trace.fraction == 1.0)
             return qtrue;
         if (trace.ent == targ)
             return qtrue;
         return qfalse;
     }
     trace = gi.trace(inflictor->s.origin, vec3_origin, vec3_origin, targ->s.origin, inflictor, MASK_SOLID);
     if (trace.fraction == 1.0)
         return qtrue;
     VectorCopy(targ->s.origin, dest);
     dest[0] += 15.0;
     dest[1] += 15.0;
     trace = gi.trace(inflictor->s.origin, vec3_origin, vec3_origin, dest, inflictor, MASK_SOLID);
     if (trace.fraction == 1.0)
         return qtrue;
     VectorCopy(targ->s.origin, dest);
     dest[0] += 15.0;
     dest[1] -= 15.0;
     trace = gi.trace(inflictor->s.origin, vec3_origin, vec3_origin, dest, inflictor, MASK_SOLID);
     if (trace.fraction == 1.0)
         return qtrue;
     VectorCopy(targ->s.origin, dest);
     dest[0] -= 15.0;
     dest[1] += 15.0;
     trace = gi.trace(inflictor->s.origin, vec3_origin, vec3_origin, dest, inflictor, MASK_SOLID);
     if (trace.fraction == 1.0)
         return qtrue;
     VectorCopy(targ->s.origin, dest);
     dest[0] -= 15.0;
     dest[1] -= 15.0;
     trace = gi.trace(inflictor->s.origin, vec3_origin, vec3_origin, dest, inflictor, MASK_SOLID);
     if (trace.fraction == 1.0)
         return qtrue;
     return qfalse;
 }
Referenced by bfg_explode(), and T_RadiusDamage().
ChangeWeapon()
void ChangeWeapon (edict_t * ent)
Definition at line 162 of file p_weapon.c.
 {
     int i;
     if (ent->client->grenade_time) {
         ent->client->grenade_time = level.time;
         ent->client->weapon_sound = 0;
         weapon_grenade_fire(ent, qfalse);
         ent->client->grenade_time = 0;
     }
     ent->client->pers.lastweapon = ent->client->pers.weapon;
     ent->client->pers.weapon = ent->client->newweapon;
     ent->client->newweapon = NULL;
     ent->client->machinegun_shots = 0;
     // set visible model
     if (ent->s.modelindex == 255) {
         if (ent->client->pers.weapon)
             i = ((ent->client->pers.weapon->weapmodel & 0xff) << 8);
         else
             i = 0;
         ent->s.skinnum = (ent - g_edicts - 1) | i;
     }
     if (ent->client->pers.weapon && ent->client->pers.weapon->ammo)
         ent->client->ammo_index = ITEM_INDEX(FindItem(ent->client->pers.weapon->ammo));
     else
         ent->client->ammo_index = 0;
     if (!ent->client->pers.weapon) {
         // dead
         ent->client->ps.gunindex = 0;
         return;
     }
     ent->client->weaponstate = WEAPON_ACTIVATING;
     ent->client->ps.gunframe = 0;
     ent->client->ps.gunindex = gi.modelindex(ent->client->pers.weapon->view_model);
     ent->client->anim_priority = ANIM_PAIN;
     if (ent->client->ps.pmove.pm_flags & PMF_DUCKED) {
         ent->s.frame = FRAME_crpain1;
         ent->client->anim_end = FRAME_crpain4;
     } else {
         ent->s.frame = FRAME_pain301;
         ent->client->anim_end = FRAME_pain304;
     }
 }
Referenced by PutClientInServer(), Think_Weapon(), Weapon_Generic(), and Weapon_Grenade().
ChaseNext()
void ChaseNext (edict_t * ent)
Definition at line 107 of file g_chase.c.
 {
     int i;
     edict_t *e;
     if (!ent->client->chase_target)
         return;
     i = ent->client->chase_target - g_edicts;
     do {
         i++;
         if (i > maxclients->value)
             i = 1;
         e = g_edicts + i;
         if (!e->inuse)
             continue;
         if (!e->client->resp.spectator)
             break;
     } while (e != ent->client->chase_target);
     ent->client->chase_target = e;
     ent->client->update_chase = qtrue;
 }
Referenced by ClientThink(), SelectNextItem(), and UpdateChaseCam().
ChasePrev()
void ChasePrev (edict_t * ent)
Definition at line 131 of file g_chase.c.
 {
     int i;
     edict_t *e;
     if (!ent->client->chase_target)
         return;
     i = ent->client->chase_target - g_edicts;
     do {
         i--;
         if (i < 1)
             i = maxclients->value;
         e = g_edicts + i;
         if (!e->inuse)
             continue;
         if (!e->client->resp.spectator)
             break;
     } while (e != ent->client->chase_target);
     ent->client->chase_target = e;
     ent->client->update_chase = qtrue;
 }
Referenced by SelectPrevItem().
ClientBeginServerFrame()
void ClientBeginServerFrame (edict_t * ent)
Definition at line 1709 of file p_client.c.
 {
     gclient_t   *client;
     int         buttonMask;
     if (level.intermissiontime)
         return;
     client = ent->client;
     if (deathmatch->value &&
         client->pers.spectator != client->resp.spectator &&
         (level.time - client->respawn_time) >= 5) {
         spectator_respawn(ent);
         return;
     }
     // run weapon animations if it hasn't been done by a ucmd_t
     if (!client->weapon_thunk && !client->resp.spectator)
         Think_Weapon(ent);
     else
         client->weapon_thunk = qfalse;
     if (ent->deadflag) {
         // wait for any button just going down
         if (level.time > client->respawn_time) {
             // in deathmatch, only wait for attack button
             if (deathmatch->value)
                 buttonMask = BUTTON_ATTACK;
             else
                 buttonMask = -1;
             if ((client->latched_buttons & buttonMask) ||
                 (deathmatch->value && ((int)dmflags->value & DF_FORCE_RESPAWN))) {
                 respawn(ent);
                 client->latched_buttons = 0;
             }
         }
         return;
     }
     // add player trail so monsters can follow
     if (!deathmatch->value)
         if (!visible(ent, PlayerTrail_LastSpot()))
             PlayerTrail_Add(ent->s.old_origin);
     client->latched_buttons = 0;
 }
Referenced by G_RunFrame().
ClientEndServerFrame()
void ClientEndServerFrame (edict_t * ent)
Definition at line 889 of file p_view.c.
 {
     float   bobtime;
     int     i;
     current_player = ent;
     current_client = ent->client;
     //
     // If the origin or velocity have changed since ClientThink(),
     // update the pmove values.  This will happen when the client
     // is pushed by a bmodel or kicked by an explosion.
     //
     // If it wasn't updated here, the view position would lag a frame
     // behind the body position when pushed -- "sinking into plats"
     //
     for (i = 0 ; i < 3 ; i++) {
         current_client->ps.pmove.origin[i] = ent->s.origin[i] * 8.0;
         current_client->ps.pmove.velocity[i] = ent->velocity[i] * 8.0;
     }
     //
     // If the end of unit layout is displayed, don't give
     // the player any normal movement attributes
     //
     if (level.intermissiontime) {
         // FIXME: add view drifting here?
         current_client->ps.blend[3] = 0;
         current_client->ps.fov = 90;
         G_SetStats(ent);
         return;
     }
     AngleVectors(ent->client->v_angle, forward, right, up);
     // burn from lava, etc
     P_WorldEffects();
     //
     // set model angles from view angles so other things in
     // the world can tell which direction you are looking
     //
     if (ent->client->v_angle[PITCH] > 180)
         ent->s.angles[PITCH] = (-360 + ent->client->v_angle[PITCH]) / 3;
     else
         ent->s.angles[PITCH] = ent->client->v_angle[PITCH] / 3;
     ent->s.angles[YAW] = ent->client->v_angle[YAW];
     ent->s.angles[ROLL] = 0;
     ent->s.angles[ROLL] = SV_CalcRoll(ent->s.angles, ent->velocity) * 4;
     //
     // calculate speed and cycle to be used for
     // all cyclic walking effects
     //
     xyspeed = sqrt(ent->velocity[0] * ent->velocity[0] + ent->velocity[1] * ent->velocity[1]);
     if (xyspeed < 5) {
         bobmove = 0;
         current_client->bobtime = 0;    // start at beginning of cycle again
     } else if (ent->groundentity) {
         // so bobbing only cycles when on ground
         if (xyspeed > 210)
             bobmove = 0.25;
         else if (xyspeed > 100)
             bobmove = 0.125;
         else
             bobmove = 0.0625;
     }
     bobtime = (current_client->bobtime += bobmove);
     if (current_client->ps.pmove.pm_flags & PMF_DUCKED)
         bobtime *= 4;
     bobcycle = (int)bobtime;
     bobfracsin = fabs(sin(bobtime * M_PI));
     // detect hitting the floor
     P_FallingDamage(ent);
     // apply all the damage taken this frame
     P_DamageFeedback(ent);
     // determine the view offsets
     SV_CalcViewOffset(ent);
     // determine the gun offsets
     SV_CalcGunOffset(ent);
     // determine the full screen color blend
     // must be after viewoffset, so eye contents can be
     // accurately determined
     // FIXME: with client prediction, the contents
     // should be determined by the client
     SV_CalcBlend(ent);
     // chase cam stuff
     if (ent->client->resp.spectator)
         G_SetSpectatorStats(ent);
     else
         G_SetStats(ent);
     G_CheckChaseStats(ent);
     G_SetClientEvent(ent);
     G_SetClientEffects(ent);
     G_SetClientSound(ent);
     G_SetClientFrame(ent);
     VectorCopy(ent->velocity, ent->client->oldvelocity);
     VectorCopy(ent->client->ps.viewangles, ent->client->oldviewangles);
     // clear weapon kicks
     VectorClear(ent->client->kick_origin);
     VectorClear(ent->client->kick_angles);
     // if the scoreboard is up, update it
     if (ent->client->showscores && !(level.framenum & 31)) {
         DeathmatchScoreboardMessage(ent, ent->enemy);
         gi.unicast(ent, qfalse);
     }
 }
Referenced by ClientBegin(), ClientBeginDeathmatch(), and ClientEndServerFrames().
Cmd_Help_f()
void Cmd_Help_f (edict_t * ent)
Definition at line 324 of file p_hud.c.
 {
     // this is for backwards compatability
     if (deathmatch->value) {
         Cmd_Score_f(ent);
         return;
     }
     ent->client->showinventory = qfalse;
     ent->client->showscores = qfalse;
     if (ent->client->showhelp && (ent->client->pers.game_helpchanged == game.helpchanged)) {
         ent->client->showhelp = qfalse;
         return;
     }
     ent->client->showhelp = qtrue;
     ent->client->pers.helpchanged = 0;
     HelpComputer(ent);
 }
Referenced by ClientCommand(), and player_die().
Cmd_Score_f()
void Cmd_Score_f (edict_t * ent)
Definition at line 255 of file p_hud.c.
 {
     ent->client->showinventory = qfalse;
     ent->client->showhelp = qfalse;
     if (!deathmatch->value && !coop->value)
         return;
     if (ent->client->showscores) {
         ent->client->showscores = qfalse;
         return;
     }
     ent->client->showscores = qtrue;
     DeathmatchScoreboard(ent);
 }
Referenced by ClientCommand(), and Cmd_Help_f().
DeathmatchScoreboardMessage()
void DeathmatchScoreboardMessage (edict_t * client, edict_t * killer)
Definition at line 150 of file p_hud.c.
 {
     char    entry[1024];
     char    string[1400];
     int     stringlength;
     int     i, j, k;
     int     sorted[MAX_CLIENTS];
     int     sortedscores[MAX_CLIENTS];
     int     score, total;
     int     x, y;
     gclient_t   *cl;
     edict_t     *cl_ent;
     char    *tag;
     // sort the clients by score
     total = 0;
     for (i = 0 ; i < game.maxclients ; i++) {
         cl_ent = g_edicts + 1 + i;
         if (!cl_ent->inuse || game.clients[i].resp.spectator)
             continue;
         score = game.clients[i].resp.score;
         for (j = 0 ; j < total ; j++) {
             if (score > sortedscores[j])
                 break;
         }
         for (k = total ; k > j ; k--) {
             sorted[k] = sorted[k - 1];
             sortedscores[k] = sortedscores[k - 1];
         }
         sorted[j] = i;
         sortedscores[j] = score;
         total++;
     }
     // print level name and exit rules
     string[0] = 0;
     stringlength = strlen(string);
     // add the clients in sorted order
     if (total > 12)
         total = 12;
     for (i = 0 ; i < total ; i++) {
         cl = &game.clients[sorted[i]];
         cl_ent = g_edicts + 1 + sorted[i];
         x = (i >= 6) ? 160 : 0;
         y = 32 + 32 * (i % 6);
         // add a dogtag
         if (cl_ent == ent)
             tag = "tag1";
         else if (cl_ent == killer)
             tag = "tag2";
         else
             tag = NULL;
         if (tag) {
             Q_snprintf(entry, sizeof(entry),
                        "xv %i yv %i picn %s ", x + 32, y, tag);
             j = strlen(entry);
             if (stringlength + j > 1024)
                 break;
             strcpy(string + stringlength, entry);
             stringlength += j;
         }
         // send the layout
         Q_snprintf(entry, sizeof(entry),
                    "client %i %i %i %i %i %i ",
                    x, y, sorted[i], cl->resp.score, cl->ping, (level.framenum - cl->resp.enterframe) / 600);
         j = strlen(entry);
         if (stringlength + j > 1024)
             break;
         strcpy(string + stringlength, entry);
         stringlength += j;
     }
     gi.WriteByte(svc_layout);
     gi.WriteString(string);
 }
Referenced by ClientEndServerFrame(), DeathmatchScoreboard(), and MoveClientToIntermission().
Drop_Item()
edict_t* Drop_Item (edict_t * ent, gitem_t * item)
Definition at line 798 of file g_items.c.
 {
     edict_t *dropped;
     vec3_t  forward, right;
     vec3_t  offset;
     dropped = G_Spawn();
     dropped->classname = item->classname;
     dropped->item = item;
     dropped->spawnflags = DROPPED_ITEM;
     dropped->s.effects = item->world_model_flags;
     dropped->s.renderfx = RF_GLOW;
     VectorSet(dropped->mins, -15, -15, -15);
     VectorSet(dropped->maxs, 15, 15, 15);
     gi.setmodel(dropped, dropped->item->world_model);
     dropped->solid = SOLID_TRIGGER;
     dropped->movetype = MOVETYPE_TOSS;
     dropped->touch = drop_temp_touch;
     dropped->owner = ent;
     if (ent->client) {
         trace_t trace;
         AngleVectors(ent->client->v_angle, forward, right, NULL);
         VectorSet(offset, 24, 0, -16);
         G_ProjectSource(ent->s.origin, offset, forward, right, dropped->s.origin);
         trace = gi.trace(ent->s.origin, dropped->mins, dropped->maxs,
                          dropped->s.origin, ent, CONTENTS_SOLID);
         VectorCopy(trace.endpos, dropped->s.origin);
     } else {
         AngleVectors(ent->s.angles, forward, right, NULL);
         VectorCopy(ent->s.origin, dropped->s.origin);
     }
     VectorScale(forward, 100, dropped->velocity);
     dropped->velocity[2] = 300;
     dropped->think = drop_make_touchable;
     dropped->nextthink = level.time + 1;
     gi.linkentity(dropped);
     return dropped;
 }
Referenced by Drop_Ammo(), Drop_General(), Drop_Weapon(), monster_death_use(), and TossClientWeapon().
FacingIdeal()
qboolean FacingIdeal (edict_t * self)
Definition at line 540 of file g_ai.c.
 {
     float   delta;
     delta = anglemod(self->s.angles[YAW] - self->ideal_yaw);
     if (delta > 45 && delta < 315)
         return qfalse;
     return qtrue;
 }
Referenced by ai_run_melee(), and ai_run_missile().
FetchClientEntData()
void FetchClientEntData (edict_t * ent)
Definition at line 652 of file p_client.c.
 {
     ent->health = ent->client->pers.health;
     ent->max_health = ent->client->pers.max_health;
     ent->flags |= ent->client->pers.savedFlags;
     if (coop->value)
         ent->client->resp.score = ent->client->pers.score;
 }
Referenced by PutClientInServer().
FindItem()
gitem_t* FindItem (char * pickup_name)
Definition at line 98 of file g_items.c.
 {
     int     i;
     gitem_t *it;
     it = itemlist;
     for (i = 0 ; i < game.num_items ; i++, it++) {
         if (!it->pickup_name)
             continue;
         if (!Q_stricmp(it->pickup_name, pickup_name))
             return it;
     }
     return NULL;
 }
Referenced by ChangeWeapon(), CheckPowerArmor(), Cmd_Drop_f(), Cmd_Give_f(), Cmd_Use_f(), G_SetStats(), InitClientPersistant(), NoAmmoWeaponChange(), Pickup_Ammo(), Pickup_Bandolier(), Pickup_Pack(), Pickup_Weapon(), PrecacheItem(), SetItemNames(), SP_item_health(), SP_item_health_large(), SP_item_health_mega(), SP_item_health_small(), SP_worldspawn(), Use_PowerArmor(), and Use_Weapon().
FindItemByClassname()
gitem_t* FindItemByClassname (char * classname)
Definition at line 76 of file g_items.c.
 {
     int     i;
     gitem_t *it;
     it = itemlist;
     for (i = 0 ; i < game.num_items ; i++, it++) {
         if (!it->classname)
             continue;
         if (!Q_stricmp(it->classname, classname))
             return it;
     }
     return NULL;
 }
Referenced by monster_start(), SP_trigger_key(), SP_turret_driver(), and TossClientWeapon().
findradius()
edict_t* findradius (edict_t * from, vec3_t org, float rad)
Definition at line 75 of file g_utils.c.
 {
     vec3_t  eorg;
     int     j;
     if (!from)
         from = g_edicts;
     else
         from++;
     for (; from < &g_edicts[globals.num_edicts]; from++) {
         if (!from->inuse)
             continue;
         if (from->solid == SOLID_NOT)
             continue;
         for (j = 0 ; j < 3 ; j++)
             eorg[j] = org[j] - (from->s.origin[j] + (from->mins[j] + from->maxs[j]) * 0.5);
         if (VectorLength(eorg) > rad)
             continue;
         return from;
     }
     return NULL;
 }
Referenced by bfg_explode(), bfg_think(), medic_FindDeadMonster(), and T_RadiusDamage().
fire_bfg()
void fire_bfg (edict_t * self, vec3_t start, vec3_t dir, int damage, int speed, float damage_radius)
Definition at line 830 of file g_weapon.c.
 {
     edict_t *bfg;
     bfg = G_Spawn();
     VectorCopy(start, bfg->s.origin);
     VectorCopy(dir, bfg->movedir);
     vectoangles(dir, bfg->s.angles);
     VectorScale(dir, speed, bfg->velocity);
     bfg->movetype = MOVETYPE_FLYMISSILE;
     bfg->clipmask = MASK_SHOT;
     bfg->solid = SOLID_BBOX;
     bfg->s.effects |= EF_BFG | EF_ANIM_ALLFAST;
     VectorClear(bfg->mins);
     VectorClear(bfg->maxs);
     bfg->s.modelindex = gi.modelindex("sprites/s_bfg1.sp2");
     bfg->owner = self;
     bfg->touch = bfg_touch;
     bfg->nextthink = level.time + 8000 / speed;
     bfg->think = G_FreeEdict;
     bfg->radius_dmg = damage;
     bfg->dmg_radius = damage_radius;
     bfg->classname = "bfg blast";
     bfg->s.sound = gi.soundindex("weapons/bfg__l1a.wav");
     bfg->think = bfg_think;
     bfg->nextthink = level.time + FRAMETIME;
     bfg->teammaster = bfg;
     bfg->teamchain = NULL;
     if (self->client)
         check_dodge(self, bfg->s.origin, dir, speed);
     gi.linkentity(bfg);
 }
Referenced by monster_fire_bfg(), and weapon_bfg_fire().
fire_blaster()
void fire_blaster (edict_t * self, vec3_t start, vec3_t aimdir, int damage, int speed, int effect, qboolean hyper)
Definition at line 319 of file g_weapon.c.
 {
     edict_t *bolt;
     trace_t tr;
     VectorNormalize(dir);
     bolt = G_Spawn();
     bolt->svflags = SVF_DEADMONSTER;
     // yes, I know it looks weird that projectiles are deadmonsters
     // what this means is that when prediction is used against the object
     // (blaster/hyperblaster shots), the player won't be solid clipped against
     // the object.  Right now trying to run into a firing hyperblaster
     // is very jerky since you are predicted 'against' the shots.
     VectorCopy(start, bolt->s.origin);
     VectorCopy(start, bolt->s.old_origin);
     vectoangles(dir, bolt->s.angles);
     VectorScale(dir, speed, bolt->velocity);
     bolt->movetype = MOVETYPE_FLYMISSILE;
     bolt->clipmask = MASK_SHOT;
     bolt->solid = SOLID_BBOX;
     bolt->s.effects |= effect;
     VectorClear(bolt->mins);
     VectorClear(bolt->maxs);
     bolt->s.modelindex = gi.modelindex("models/objects/laser/tris.md2");
     bolt->s.sound = gi.soundindex("misc/lasfly.wav");
     bolt->owner = self;
     bolt->touch = blaster_touch;
     bolt->nextthink = level.time + 2;
     bolt->think = G_FreeEdict;
     bolt->dmg = damage;
     bolt->classname = "bolt";
     if (hyper)
         bolt->spawnflags = 1;
     gi.linkentity(bolt);
     if (self->client)
         check_dodge(self, bolt->s.origin, dir, speed);
     tr = gi.trace(self->s.origin, NULL, NULL, bolt->s.origin, bolt, MASK_SHOT);
     if (tr.fraction < 1.0) {
         VectorMA(bolt->s.origin, -10, dir, bolt->s.origin);
         bolt->touch(bolt, tr.ent, NULL, NULL);
     }
 }
Referenced by Blaster_Fire(), monster_fire_blaster(), and use_target_blaster().
fire_bullet()
void fire_bullet (edict_t * self, vec3_t start, vec3_t aimdir, int damage, int kick, int hspread, int vspread, int mod)
Definition at line 255 of file g_weapon.c.
 {
     fire_lead(self, start, aimdir, damage, kick, TE_GUNSHOT, hspread, vspread, mod);
 }
Referenced by Chaingun_Fire(), Machinegun_Fire(), and monster_fire_bullet().
fire_grenade()
void fire_grenade (edict_t * self, vec3_t start, vec3_t aimdir, int damage, int speed, float timer, float damage_radius)
Definition at line 450 of file g_weapon.c.
 {
     edict_t *grenade;
     vec3_t  dir;
     vec3_t  forward, right, up;
     vectoangles(aimdir, dir);
     AngleVectors(dir, forward, right, up);
     grenade = G_Spawn();
     VectorCopy(start, grenade->s.origin);
     VectorScale(aimdir, speed, grenade->velocity);
     VectorMA(grenade->velocity, 200 + crandom() * 10.0, up, grenade->velocity);
     VectorMA(grenade->velocity, crandom() * 10.0, right, grenade->velocity);
     VectorSet(grenade->avelocity, 300, 300, 300);
     grenade->movetype = MOVETYPE_BOUNCE;
     grenade->clipmask = MASK_SHOT;
     grenade->solid = SOLID_BBOX;
     grenade->s.effects |= EF_GRENADE;
     VectorClear(grenade->mins);
     VectorClear(grenade->maxs);
     grenade->s.modelindex = gi.modelindex("models/objects/grenade/tris.md2");
     grenade->owner = self;
     grenade->touch = Grenade_Touch;
     grenade->nextthink = level.time + timer;
     grenade->think = Grenade_Explode;
     grenade->dmg = damage;
     grenade->dmg_radius = damage_radius;
     grenade->classname = "grenade";
     gi.linkentity(grenade);
 }
Referenced by monster_fire_grenade(), and weapon_grenadelauncher_fire().
fire_grenade2()
void fire_grenade2 (edict_t * self, vec3_t start, vec3_t aimdir, int damage, int speed, float timer, float damage_radius, qboolean held)
Definition at line 483 of file g_weapon.c.
 {
     edict_t *grenade;
     vec3_t  dir;
     vec3_t  forward, right, up;
     vectoangles(aimdir, dir);
     AngleVectors(dir, forward, right, up);
     grenade = G_Spawn();
     VectorCopy(start, grenade->s.origin);
     VectorScale(aimdir, speed, grenade->velocity);
     VectorMA(grenade->velocity, 200 + crandom() * 10.0, up, grenade->velocity);
     VectorMA(grenade->velocity, crandom() * 10.0, right, grenade->velocity);
     VectorSet(grenade->avelocity, 300, 300, 300);
     grenade->movetype = MOVETYPE_BOUNCE;
     grenade->clipmask = MASK_SHOT;
     grenade->solid = SOLID_BBOX;
     grenade->s.effects |= EF_GRENADE;
     VectorClear(grenade->mins);
     VectorClear(grenade->maxs);
     grenade->s.modelindex = gi.modelindex("models/objects/grenade2/tris.md2");
     grenade->owner = self;
     grenade->touch = Grenade_Touch;
     grenade->nextthink = level.time + timer;
     grenade->think = Grenade_Explode;
     grenade->dmg = damage;
     grenade->dmg_radius = damage_radius;
     grenade->classname = "hgrenade";
     if (held)
         grenade->spawnflags = 3;
     else
         grenade->spawnflags = 1;
     grenade->s.sound = gi.soundindex("weapons/hgrenc1b.wav");
     if (timer <= 0.0)
         Grenade_Explode(grenade);
     else {
         gi.sound(self, CHAN_WEAPON, gi.soundindex("weapons/hgrent1a.wav"), 1, ATTN_NORM, 0);
         gi.linkentity(grenade);
     }
 }
Referenced by weapon_grenade_fire().
fire_hit()
qboolean fire_hit (edict_t * self, vec3_t aim, int damage, int kick)
Definition at line 59 of file g_weapon.c.
 {
     trace_t     tr;
     vec3_t      forward, right, up;
     vec3_t      v;
     vec3_t      point;
     float       range;
     vec3_t      dir;
     //see if enemy is in range
     VectorSubtract(self->enemy->s.origin, self->s.origin, dir);
     range = VectorLength(dir);
     if (range > aim[0])
         return qfalse;
     if (aim[1] > self->mins[0] && aim[1] < self->maxs[0]) {
         // the hit is straight on so back the range up to the edge of their bbox
         range -= self->enemy->maxs[0];
     } else {
         // this is a side hit so adjust the "right" value out to the edge of their bbox
         if (aim[1] < 0)
             aim[1] = self->enemy->mins[0];
         else
             aim[1] = self->enemy->maxs[0];
     }
     VectorMA(self->s.origin, range, dir, point);
     tr = gi.trace(self->s.origin, NULL, NULL, point, self, MASK_SHOT);
     if (tr.fraction < 1) {
         if (!tr.ent->takedamage)
             return qfalse;
         // if it will hit any client/monster then hit the one we wanted to hit
         if ((tr.ent->svflags & SVF_MONSTER) || (tr.ent->client))
             tr.ent = self->enemy;
     }
     AngleVectors(self->s.angles, forward, right, up);
     VectorMA(self->s.origin, range, forward, point);
     VectorMA(point, aim[1], right, point);
     VectorMA(point, aim[2], up, point);
     VectorSubtract(point, self->enemy->s.origin, dir);
     // do the damage
     T_Damage(tr.ent, self, self, dir, point, vec3_origin, damage, kick / 2, DAMAGE_NO_KNOCKBACK, MOD_HIT);
     if (!(tr.ent->svflags & SVF_MONSTER) && (!tr.ent->client))
         return qfalse;
     // do our special form of knockback here
     VectorMA(self->enemy->absmin, 0.5, self->enemy->size, v);
     VectorSubtract(v, point, v);
     VectorNormalize(v);
     VectorMA(self->enemy->velocity, kick, v, self->enemy->velocity);
     if (self->enemy->velocity[2] > 0)
         self->enemy->groundentity = NULL;
     return qtrue;
 }
Referenced by berserk_attack_club(), berserk_attack_spike(), brain_hit_left(), brain_hit_right(), brain_tentacle_attack(), ChickSlash(), flipper_bite(), floater_wham(), flyer_slash_left(), flyer_slash_right(), GaldiatorMelee(), infantry_smack(), mutant_hit_left(), and mutant_hit_right().
fire_rail()
void fire_rail (edict_t * self, vec3_t start, vec3_t aimdir, int damage, int kick)
Definition at line 615 of file g_weapon.c.
 {
     vec3_t      from;
     vec3_t      end;
     trace_t     tr;
     edict_t     *ignore;
     int         mask;
     qboolean    water;
     VectorMA(start, 8192, aimdir, end);
     VectorCopy(start, from);
     ignore = self;
     water = qfalse;
     mask = MASK_SHOT | CONTENTS_SLIME | CONTENTS_LAVA;
     while (ignore) {
         tr = gi.trace(from, NULL, NULL, end, ignore, mask);
         if (tr.contents & (CONTENTS_SLIME | CONTENTS_LAVA)) {
             mask &= ~(CONTENTS_SLIME | CONTENTS_LAVA);
             water = qtrue;
         } else {
             //ZOID--added so rail goes through SOLID_BBOX entities (gibs, etc)
             if ((tr.ent->svflags & SVF_MONSTER) || (tr.ent->client) ||
                 (tr.ent->solid == SOLID_BBOX))
                 ignore = tr.ent;
             else
                 ignore = NULL;
             if ((tr.ent != self) && (tr.ent->takedamage))
                 T_Damage(tr.ent, self, self, aimdir, tr.endpos, tr.plane.normal, damage, kick, 0, MOD_RAILGUN);
         }
         VectorCopy(tr.endpos, from);
     }
     // send gun puff / flash
     gi.WriteByte(svc_temp_entity);
     gi.WriteByte(TE_RAILTRAIL);
     gi.WritePosition(start);
     gi.WritePosition(tr.endpos);
     gi.multicast(self->s.origin, MULTICAST_PHS);
 //  gi.multicast (start, MULTICAST_PHS);
     if (water) {
         gi.WriteByte(svc_temp_entity);
         gi.WriteByte(TE_RAILTRAIL);
         gi.WritePosition(start);
         gi.WritePosition(tr.endpos);
         gi.multicast(tr.endpos, MULTICAST_PHS);
     }
     if (self->client)
         PlayerNoise(self, tr.endpos, PNOISE_IMPACT);
 }
Referenced by monster_fire_railgun(), and weapon_railgun_fire().
fire_rocket()
void fire_rocket (edict_t * self, vec3_t start, vec3_t dir, int damage, int speed, float damage_radius, int radius_damage)
Definition at line 577 of file g_weapon.c.
 {
     edict_t *rocket;
     rocket = G_Spawn();
     VectorCopy(start, rocket->s.origin);
     VectorCopy(dir, rocket->movedir);
     vectoangles(dir, rocket->s.angles);
     VectorScale(dir, speed, rocket->velocity);
     rocket->movetype = MOVETYPE_FLYMISSILE;
     rocket->clipmask = MASK_SHOT;
     rocket->solid = SOLID_BBOX;
     rocket->s.effects |= EF_ROCKET;
     VectorClear(rocket->mins);
     VectorClear(rocket->maxs);
     rocket->s.modelindex = gi.modelindex("models/objects/rocket/tris.md2");
     rocket->owner = self;
     rocket->touch = rocket_touch;
     rocket->nextthink = level.time + 8000 / speed;
     rocket->think = G_FreeEdict;
     rocket->dmg = damage;
     rocket->radius_dmg = radius_damage;
     rocket->dmg_radius = damage_radius;
     rocket->s.sound = gi.soundindex("weapons/rockfly.wav");
     rocket->classname = "rocket";
     if (self->client)
         check_dodge(self, rocket->s.origin, dir, speed);
     gi.linkentity(rocket);
 }
Referenced by monster_fire_rocket(), turret_breach_fire(), and Weapon_RocketLauncher_Fire().
fire_shotgun()
void fire_shotgun (edict_t * self, vec3_t start, vec3_t aimdir, int damage, int kick, int hspread, int vspread, int count, int mod)
Definition at line 268 of file g_weapon.c.
 {
     int     i;
     for (i = 0; i < count; i++)
         fire_lead(self, start, aimdir, damage, kick, TE_SHOTGUN, hspread, vspread, mod);
 }
Referenced by monster_fire_shotgun(), weapon_shotgun_fire(), and weapon_supershotgun_fire().
flymonster_start()
void flymonster_start (edict_t * self)
Definition at line 653 of file g_monster.c.
 {
     self->flags |= FL_FLY;
     self->think = flymonster_start_go;
     monster_start(self);
 }
Referenced by SP_misc_insane(), SP_monster_boss2(), SP_monster_floater(), SP_monster_flyer(), and SP_monster_hover().
FoundTarget()
void FoundTarget (edict_t * self)
Definition at line 328 of file g_ai.c.
 {
     // let other monsters see this monster for a while
     if (self->enemy->client) {
         level.sight_entity = self;
         level.sight_entity_framenum = level.framenum;
         level.sight_entity->light_level = 128;
     }
     self->show_hostile = level.time + 1;        // wake up other monsters
     VectorCopy(self->enemy->s.origin, self->monsterinfo.last_sighting);
     self->monsterinfo.trail_time = level.time;
     if (!self->combattarget) {
         HuntTarget(self);
         return;
     }
     self->goalentity = self->movetarget = G_PickTarget(self->combattarget);
     if (!self->movetarget) {
         self->goalentity = self->movetarget = self->enemy;
         HuntTarget(self);
         gi.dprintf("%s at %s, combattarget %s not found\n", self->classname, vtos(self->s.origin), self->combattarget);
         return;
     }
     // clear out our combattarget, these are a one shot deal
     self->combattarget = NULL;
     self->monsterinfo.aiflags |= AI_COMBAT_POINT;
     // clear the targetname, that point is ours!
     self->movetarget->targetname = NULL;
     self->monsterinfo.pausetime = 0;
     // run for it
     self->monsterinfo.run(self);
 }
Referenced by FindTarget(), M_ReactToDamage(), medic_cable_attack(), medic_idle(), medic_run(), medic_search(), monster_triggered_spawn(), and monster_use().
func_clock_think()
void func_clock_think (edict_t * self)
Definition at line 1600 of file g_misc.c.
 {
     if (!self->enemy) {
         self->enemy = G_Find(NULL, FOFS(targetname), self->target);
         if (!self->enemy)
             return;
     }
     if (self->spawnflags & 1) {
         func_clock_format_countdown(self);
         self->health++;
     } else if (self->spawnflags & 2) {
         func_clock_format_countdown(self);
         self->health--;
     } else {
         struct tm   *ltime;
         time_t      gmtime;
         gmtime = time(NULL);
         ltime = localtime(&gmtime);
         if (ltime)
             Q_snprintf(self->message, CLOCK_MESSAGE_SIZE, "%2i:%2i:%2i", ltime->tm_hour, ltime->tm_min, ltime->tm_sec);
         else
             strcpy(self->message, "00:00:00");
         if (self->message[3] == ' ')
             self->message[3] = '0';
         if (self->message[6] == ' ')
             self->message[6] = '0';
     }
     self->enemy->message = self->message;
     self->enemy->use(self->enemy, self, self);
     if (((self->spawnflags & 1) && (self->health > self->wait)) ||
         ((self->spawnflags & 2) && (self->health < self->wait))) {
         if (self->pathtarget) {
             char *savetarget;
             char *savemessage;
             savetarget = self->target;
             savemessage = self->message;
             self->target = self->pathtarget;
             self->message = NULL;
             G_UseTargets(self, self->activator);
             self->target = savetarget;
             self->message = savemessage;
         }
         if (!(self->spawnflags & 8))
             return;
         func_clock_reset(self);
         if (self->spawnflags & 4)
             return;
     }
     self->nextthink = level.time + 1;
 }
Referenced by ReadLevel(), and SP_func_clock().
func_clock_use()
void func_clock_use (edict_t * self, edict_t * other, edict_t * activator)
Definition at line 1660 of file g_misc.c.
 {
     if (!(self->spawnflags & 8))
         self->use = NULL;
     if (self->activator)
         return;
     self->activator = activator;
     self->think(self);
 }
Referenced by ReadLevel(), and SP_func_clock().
G_CheckChaseStats()
void G_CheckChaseStats (edict_t * ent)
Definition at line 485 of file p_hud.c.
 {
     int i;
     gclient_t *cl;
     for (i = 1; i <= maxclients->value; i++) {
         cl = g_edicts[i].client;
         if (!g_edicts[i].inuse || cl->chase_target != ent)
             continue;
         memcpy(cl->ps.stats, ent->client->ps.stats, sizeof(cl->ps.stats));
         G_SetSpectatorStats(g_edicts + i);
     }
 }
Referenced by ClientEndServerFrame().
G_CopyString()
char* G_CopyString (char * in)
Definition at line 362 of file g_utils.c.
 {
     char    *out;
     out = gi.TagMalloc(strlen(in) + 1, TAG_LEVEL);
     strcpy(out, in);
     return out;
 }
G_Find()
edict_t* G_Find (edict_t * from, int fieldofs, char * match)
Definition at line 43 of file g_utils.c.
 {
     char    *s;
     if (!from)
         from = g_edicts;
     else
         from++;
     for (; from < &g_edicts[globals.num_edicts] ; from++) {
         if (!from->inuse)
             continue;
         s = *(char **)((byte *)from + fieldofs);
         if (!s)
             continue;
         if (!Q_stricmp(s, match))
             return from;
     }
     return NULL;
 }
Referenced by BeginIntermission(), door_use_areaportals(), EndDMLevel(), func_clock_think(), G_PickTarget(), G_UseTargets(), misc_viper_bomb_use(), monster_start_go(), SelectCoopSpawnPoint(), SelectFarthestDeathmatchSpawnPoint(), SelectRandomDeathmatchSpawnPoint(), SelectSpawnPoint(), SP_FixCoopSpots(), target_laser_start(), target_lightramp_use(), and teleporter_touch().
G_FreeEdict()
void G_FreeEdict (edict_t * e)
Definition at line 421 of file g_utils.c.
 {
     gi.unlinkentity(ed);        // unlink from world
     if ((ed - g_edicts) <= (maxclients->value + BODY_QUEUE_SIZE)) {
 //      gi.dprintf("tried to free special edict\n");
         return;
     }
     memset(ed, 0, sizeof(*ed));
     ed->classname = "freed";
     ed->freetime = level.time;
     ed->inuse = qfalse;
 }
Referenced by ai_run(), BecomeExplosion1(), BecomeExplosion2(), bfg_explode(), bfg_touch(), blaster_touch(), Cmd_Give_f(), debris_die(), Drop_Ammo(), drop_make_touchable(), droptofloor(), fire_bfg(), fire_blaster(), fire_rocket(), flare_think(), func_explosive_explode(), G_UseTargets(), gib_die(), gib_think(), Grenade_Explode(), Grenade_Touch(), MegaHealth_think(), misc_blackhole_use(), monster_start(), multi_trigger(), rocket_touch(), SP_func_clock(), SP_func_explosive(), SP_info_null(), SP_info_player_coop(), SP_info_player_deathmatch(), SP_item_health(), SP_item_health_large(), SP_item_health_mega(), SP_item_health_small(), SP_light(), SP_misc_actor(), SP_misc_deadsoldier(), SP_misc_explobox(), SP_misc_gib_arm(), SP_misc_gib_head(), SP_misc_gib_leg(), SP_misc_insane(), SP_misc_strogg_ship(), SP_misc_teleporter(), SP_misc_viper(), SP_monster_berserk(), SP_monster_boss2(), SP_monster_boss3_stand(), SP_monster_brain(), SP_monster_chick(), SP_monster_flipper(), SP_monster_floater(), SP_monster_flyer(), SP_monster_gladiator(), SP_monster_gunner(), SP_monster_hover(), SP_monster_infantry(), SP_monster_jorg(), SP_monster_makron(), SP_monster_medic(), SP_monster_mutant(), SP_monster_parasite(), SP_monster_soldier(), SP_monster_soldier_light(), SP_monster_soldier_ss(), SP_monster_supertank(), SP_monster_tank(), SP_path_corner(), SP_point_combat(), SP_target_changelevel(), SP_target_goal(), SP_target_help(), SP_target_lightramp(), SP_target_secret(), SP_trigger_gravity(), SP_turret_driver(), SpawnEntities(), SpawnItem(), target_crosslevel_target_think(), target_lightramp_use(), Think_Delay(), ThrowDebris(), ThrowGib(), ThrowHead(), TossClientWeapon(), Touch_Item(), trigger_crosslevel_trigger_use(), trigger_push_touch(), turret_breach_finish_init(), Use_Boss3(), use_target_goal(), and use_target_secret().
G_InitEdict()
void G_InitEdict (edict_t * e)
Definition at line 372 of file g_utils.c.
 {
     e->inuse = qtrue;
     e->classname = "noclass";
     e->gravity = 1.0;
     e->s.number = e - g_edicts;
 }
Referenced by ClientBegin(), ClientBeginDeathmatch(), and G_Spawn().
G_PickTarget()
edict_t* G_PickTarget (char * targetname)
Definition at line 114 of file g_utils.c.
 {
     edict_t *ent = NULL;
     int     num_choices = 0;
     edict_t *choice[MAXCHOICES];
     if (!targetname) {
         gi.dprintf("G_PickTarget called with NULL targetname\n");
         return NULL;
     }
     while (1) {
         ent = G_Find(ent, FOFS(targetname), targetname);
         if (!ent)
             break;
         choice[num_choices++] = ent;
         if (num_choices == MAXCHOICES)
             break;
     }
     if (!num_choices) {
         gi.dprintf("G_PickTarget: target %s not found\n", targetname);
         return NULL;
     }
     return choice[rand() % num_choices];
 }
Referenced by actor_use(), FoundTarget(), func_train_find(), monster_start_go(), path_corner_touch(), point_combat_touch(), target_actor_touch(), train_next(), trigger_elevator_init(), trigger_elevator_use(), turret_breach_finish_init(), and turret_driver_link().
G_ProjectSource()
void G_ProjectSource (const vec3_t point, const vec3_t distance, const vec3_t forward, const vec3_t right, vec3_t result)
Definition at line 23 of file g_utils.c.
 {
     result[0] = point[0] + forward[0] * distance[0] + right[0] * distance[1];
     result[1] = point[1] + forward[1] * distance[0] + right[1] * distance[1];
     result[2] = point[2] + forward[2] * distance[0] + right[2] * distance[1] + distance[2];
 }
Referenced by actorMachineGun(), ai_run(), boss2_firebullet_left(), boss2_firebullet_right(), Boss2Rocket(), ChickRocket(), Drop_Item(), floater_fire_blaster(), floater_zap(), flyer_fire(), GladiatorGun(), GunnerFire(), GunnerGrenade(), hover_fire_blaster(), InfantryMachineGun(), jorg_firebullet_left(), jorg_firebullet_right(), jorgBFG(), makronBFG(), MakronHyperblaster(), MakronRailgun(), medic_cable_attack(), medic_fire_blaster(), P_ProjectSource(), parasite_drain_attack(), soldier_fire(), supertankMachineGun(), supertankRocket(), TankBlaster(), TankMachineGun(), and TankRocket().
G_RunEntity()
void G_RunEntity (edict_t * ent)
Definition at line 905 of file g_phys.c.
 {
     if (ent->prethink)
         ent->prethink(ent);
     switch ((int)ent->movetype) {
     case MOVETYPE_PUSH:
     case MOVETYPE_STOP:
         SV_Physics_Pusher(ent);
         break;
     case MOVETYPE_NONE:
         SV_Physics_None(ent);
         break;
     case MOVETYPE_NOCLIP:
         SV_Physics_Noclip(ent);
         break;
     case MOVETYPE_STEP:
         SV_Physics_Step(ent);
         break;
     case MOVETYPE_TOSS:
     case MOVETYPE_BOUNCE:
     case MOVETYPE_FLY:
     case MOVETYPE_FLYMISSILE:
         SV_Physics_Toss(ent);
         break;
     default:
         gi.error("SV_Physics: bad movetype %i", (int)ent->movetype);
     }
 }
Referenced by G_RunFrame().
G_SetMovedir()
void G_SetMovedir (vec3_t angles, vec3_t movedir)
Definition at line 296 of file g_utils.c.
 {
     if (VectorCompare(angles, VEC_UP)) {
         VectorCopy(MOVEDIR_UP, movedir);
     } else if (VectorCompare(angles, VEC_DOWN)) {
         VectorCopy(MOVEDIR_DOWN, movedir);
     } else {
         AngleVectors(angles, movedir, NULL, NULL);
     }
     VectorClear(angles);
 }
Referenced by InitTrigger(), SP_func_button(), SP_func_door(), SP_func_water(), SP_target_actor(), SP_target_blaster(), SP_target_spawner(), SP_target_splash(), SP_trigger_multiple(), and target_laser_start().
G_SetSpectatorStats()
void G_SetSpectatorStats (edict_t * ent)
Definition at line 504 of file p_hud.c.
 {
     gclient_t *cl = ent->client;
     if (!cl->chase_target)
         G_SetStats(ent);
     cl->ps.stats[STAT_SPECTATOR] = 1;
     // layouts are independant in spectator
     cl->ps.stats[STAT_LAYOUTS] = 0;
     if (cl->pers.health <= 0 || level.intermissiontime || cl->showscores)
         cl->ps.stats[STAT_LAYOUTS] |= 1;
     if (cl->showinventory && cl->pers.health > 0)
         cl->ps.stats[STAT_LAYOUTS] |= 2;
     if (cl->chase_target && cl->chase_target->inuse)
         cl->ps.stats[STAT_CHASE] = CS_PLAYERSKINS +
                                    (cl->chase_target - g_edicts) - 1;
     else
         cl->ps.stats[STAT_CHASE] = 0;
 }
Referenced by ClientEndServerFrame(), and G_CheckChaseStats().
G_SetStats()
void G_SetStats (edict_t * ent)
Definition at line 353 of file p_hud.c.
 {
     gitem_t     *item;
     int         index, cells;
     int         power_armor_type;
     //
     // health
     //
     ent->client->ps.stats[STAT_HEALTH_ICON] = level.pic_health;
     ent->client->ps.stats[STAT_HEALTH] = ent->health;
     //
     // ammo
     //
     if (!ent->client->ammo_index /* || !ent->client->pers.inventory[ent->client->ammo_index] */) {
         ent->client->ps.stats[STAT_AMMO_ICON] = 0;
         ent->client->ps.stats[STAT_AMMO] = 0;
     } else {
         item = &itemlist[ent->client->ammo_index];
         ent->client->ps.stats[STAT_AMMO_ICON] = gi.imageindex(item->icon);
         ent->client->ps.stats[STAT_AMMO] = ent->client->pers.inventory[ent->client->ammo_index];
     }
     //
     // armor
     //
     power_armor_type = PowerArmorType(ent);
     if (power_armor_type) {
         cells = ent->client->pers.inventory[ITEM_INDEX(FindItem("cells"))];
         if (cells == 0) {
             // ran out of cells for power armor
             ent->flags &= ~FL_POWER_ARMOR;
             gi.sound(ent, CHAN_ITEM, gi.soundindex("misc/power2.wav"), 1, ATTN_NORM, 0);
             power_armor_type = 0;;
         }
     }
     index = ArmorIndex(ent);
     if (power_armor_type && (!index || (level.framenum & 8))) {
         // flash between power armor and other armor icon
         ent->client->ps.stats[STAT_ARMOR_ICON] = gi.imageindex("i_powershield");
         ent->client->ps.stats[STAT_ARMOR] = cells;
     } else if (index) {
         item = GetItemByIndex(index);
         ent->client->ps.stats[STAT_ARMOR_ICON] = gi.imageindex(item->icon);
         ent->client->ps.stats[STAT_ARMOR] = ent->client->pers.inventory[index];
     } else {
         ent->client->ps.stats[STAT_ARMOR_ICON] = 0;
         ent->client->ps.stats[STAT_ARMOR] = 0;
     }
     //
     // pickup message
     //
     if (level.time > ent->client->pickup_msg_time) {
         ent->client->ps.stats[STAT_PICKUP_ICON] = 0;
         ent->client->ps.stats[STAT_PICKUP_STRING] = 0;
     }
     //
     // timers
     //
     if (ent->client->quad_framenum > level.framenum) {
         ent->client->ps.stats[STAT_TIMER_ICON] = gi.imageindex("p_quad");
         ent->client->ps.stats[STAT_TIMER] = (ent->client->quad_framenum - level.framenum) / 10;
     } else if (ent->client->invincible_framenum > level.framenum) {
         ent->client->ps.stats[STAT_TIMER_ICON] = gi.imageindex("p_invulnerability");
         ent->client->ps.stats[STAT_TIMER] = (ent->client->invincible_framenum - level.framenum) / 10;
     } else if (ent->client->enviro_framenum > level.framenum) {
         ent->client->ps.stats[STAT_TIMER_ICON] = gi.imageindex("p_envirosuit");
         ent->client->ps.stats[STAT_TIMER] = (ent->client->enviro_framenum - level.framenum) / 10;
     } else if (ent->client->breather_framenum > level.framenum) {
         ent->client->ps.stats[STAT_TIMER_ICON] = gi.imageindex("p_rebreather");
         ent->client->ps.stats[STAT_TIMER] = (ent->client->breather_framenum - level.framenum) / 10;
     } else {
         ent->client->ps.stats[STAT_TIMER_ICON] = 0;
         ent->client->ps.stats[STAT_TIMER] = 0;
     }
     //
     // selected item
     //
     if (ent->client->pers.selected_item == -1)
         ent->client->ps.stats[STAT_SELECTED_ICON] = 0;
     else
         ent->client->ps.stats[STAT_SELECTED_ICON] = gi.imageindex(itemlist[ent->client->pers.selected_item].icon);
     ent->client->ps.stats[STAT_SELECTED_ITEM] = ent->client->pers.selected_item;
     //
     // layouts
     //
     ent->client->ps.stats[STAT_LAYOUTS] = 0;
     if (deathmatch->value) {
         if (ent->client->pers.health <= 0 || level.intermissiontime
             || ent->client->showscores)
             ent->client->ps.stats[STAT_LAYOUTS] |= 1;
         if (ent->client->showinventory && ent->client->pers.health > 0)
             ent->client->ps.stats[STAT_LAYOUTS] |= 2;
     } else {
         if (ent->client->showscores || ent->client->showhelp)
             ent->client->ps.stats[STAT_LAYOUTS] |= 1;
         if (ent->client->showinventory && ent->client->pers.health > 0)
             ent->client->ps.stats[STAT_LAYOUTS] |= 2;
     }
     //
     // frags
     //
     ent->client->ps.stats[STAT_FRAGS] = ent->client->resp.score;
     //
     // help icon / current weapon if not shown
     //
     if (ent->client->pers.helpchanged && (level.framenum & 8))
         ent->client->ps.stats[STAT_HELPICON] = gi.imageindex("i_help");
     else if ((ent->client->pers.hand == CENTER_HANDED || ent->client->ps.fov > 91)
              && ent->client->pers.weapon)
         ent->client->ps.stats[STAT_HELPICON] = gi.imageindex(ent->client->pers.weapon->icon);
     else
         ent->client->ps.stats[STAT_HELPICON] = 0;
     ent->client->ps.stats[STAT_SPECTATOR] = 0;
 }
Referenced by ClientEndServerFrame(), and G_SetSpectatorStats().
G_Spawn()
edict_t* G_Spawn (void)
Definition at line 391 of file g_utils.c.
 {
     int         i;
     edict_t     *e;
     e = &g_edicts[game.maxclients + 1];
     for (i = game.maxclients + 1 ; i < globals.num_edicts ; i++, e++) {
         // the first couple seconds of server time can involve a lot of
         // freeing and allocating, so relax the replacement policy
         if (!e->inuse && (e->freetime < 2 || level.time - e->freetime > 0.5)) {
             G_InitEdict(e);
             return e;
         }
     }
     if (i == game.maxentities)
         gi.error("ED_Alloc: no free edicts");
     globals.num_edicts++;
     G_InitEdict(e);
     return e;
 }
Referenced by ai_run(), Cmd_Give_f(), CreateTargetChangeLevel(), Drop_Item(), fire_bfg(), fire_blaster(), fire_flaregun(), fire_grenade(), fire_grenade2(), fire_rocket(), G_UseTargets(), InitBodyQue(), jorg_dead(), makron_die(), MakronToss(), plat_spawn_inside_trigger(), PlayerNoise(), PlayerTrail_Init(), SP_CreateCoopSpots(), SP_misc_teleporter(), SpawnEntities(), Think_SpawnDoorTrigger(), ThrowDebris(), ThrowGib(), and use_target_spawner().
G_TouchSolids()
void G_TouchSolids (edict_t * ent)
Definition at line 475 of file g_utils.c.
 {
     int         i, num;
     edict_t     *touch[MAX_EDICTS], *hit;
     num = gi.BoxEdicts(ent->absmin, ent->absmax, touch
                        , MAX_EDICTS, AREA_SOLID);
     // be careful, it is possible to have an entity in this
     // list removed before we get to it (killtriggered)
     for (i = 0 ; i < num ; i++) {
         hit = touch[i];
         if (!hit->inuse)
             continue;
         if (ent->touch)
             ent->touch(hit, ent, NULL, NULL);
         if (!ent->inuse)
             break;
     }
 }
G_TouchTriggers()
void G_TouchTriggers (edict_t * ent)
Definition at line 443 of file g_utils.c.
 {
     int         i, num;
     edict_t     *touch[MAX_EDICTS], *hit;
     // dead things don't activate triggers!
     if ((ent->client || (ent->svflags & SVF_MONSTER)) && (ent->health <= 0))
         return;
     num = gi.BoxEdicts(ent->absmin, ent->absmax, touch
                        , MAX_EDICTS, AREA_TRIGGERS);
     // be careful, it is possible to have an entity in this
     // list removed before we get to it (killtriggered)
     for (i = 0 ; i < num ; i++) {
         hit = touch[i];
         if (!hit->inuse)
             continue;
         if (!hit->touch)
             continue;
         hit->touch(hit, ent, NULL, NULL);
     }
 }
Referenced by ClientThink(), SV_movestep(), SV_Physics_Step(), SV_Push(), SV_PushEntity(), and SV_StepDirection().
G_UseTargets()
void G_UseTargets (edict_t * ent, edict_t * activator)
Definition at line 166 of file g_utils.c.
 {
     edict_t     *t;
 //
 // check for a delay
 //
     if (ent->delay) {
         // create a temp object to fire at a later time
         t = G_Spawn();
         t->classname = "DelayedUse";
         t->nextthink = level.time + ent->delay;
         t->think = Think_Delay;
         t->activator = activator;
         if (!activator)
             gi.dprintf("Think_Delay with no activator\n");
         t->message = ent->message;
         t->target = ent->target;
         t->killtarget = ent->killtarget;
         return;
     }
 //
 // print the message
 //
     if ((ent->message) && !(activator->svflags & SVF_MONSTER)) {
         gi.centerprintf(activator, "%s", ent->message);
         if (ent->noise_index)
             gi.sound(activator, CHAN_AUTO, ent->noise_index, 1, ATTN_NORM, 0);
         else
             gi.sound(activator, CHAN_AUTO, gi.soundindex("misc/talk1.wav"), 1, ATTN_NORM, 0);
     }
 //
 // kill killtargets
 //
     if (ent->killtarget) {
         t = NULL;
         while ((t = G_Find(t, FOFS(targetname), ent->killtarget))) {
             G_FreeEdict(t);
             if (!ent->inuse) {
                 gi.dprintf("entity was removed while using killtargets\n");
                 return;
             }
         }
     }
 //
 // fire targets
 //
     if (ent->target) {
         t = NULL;
         while ((t = G_Find(t, FOFS(targetname), ent->target))) {
             // doors fire area portals in a specific way
             if (!Q_stricmp(t->classname, "func_areaportal") &&
                 (!Q_stricmp(ent->classname, "func_door") || !Q_stricmp(ent->classname, "func_door_rotating")))
                 continue;
             if (t == ent) {
                 gi.dprintf("WARNING: Entity used itself.\n");
             } else {
                 if (t->use)
                     t->use(t, ent, activator);
             }
             if (!ent->inuse) {
                 gi.dprintf("entity was removed while using targets\n");
                 return;
             }
         }
     }
 }
Referenced by button_wait(), door_go_up(), func_clock_think(), func_explosive_explode(), func_timer_think(), misc_viper_bomb_touch(), monster_death_use(), multi_trigger(), path_corner_touch(), point_combat_touch(), SP_trigger_always(), target_actor_touch(), target_crosslevel_target_think(), target_explosion_explode(), Think_Delay(), Touch_Item(), train_wait(), trigger_key_use(), trigger_relay_use(), use_target_goal(), and use_target_secret().
GetChaseTarget()
void GetChaseTarget (edict_t * ent)
Definition at line 155 of file g_chase.c.
 {
     int i;
     edict_t *other;
     for (i = 1; i <= maxclients->value; i++) {
         other = g_edicts + i;
         if (other->inuse && !other->client->resp.spectator) {
             ent->client->chase_target = other;
             ent->client->update_chase = qtrue;
             UpdateChaseCam(ent);
             return;
         }
     }
     gi.centerprintf(ent, "No other players to chase.");
 }
Referenced by ClientThink().
GetItemByIndex()
gitem_t* GetItemByIndex (int index)
Definition at line 61 of file g_items.c.
 {
     if (index == 0 || index >= game.num_items)
         return NULL;
     return &itemlist[index];
 }
Referenced by CheckArmor(), and G_SetStats().
infront()
qboolean infront (edict_t * self, edict_t * other)
Definition at line 293 of file g_ai.c.
 {
     vec3_t  vec;
     float   dot;
     vec3_t  forward;
     AngleVectors(self->s.angles, forward, NULL, NULL);
     VectorSubtract(other->s.origin, self->s.origin, vec);
     VectorNormalize(vec);
     dot = DotProduct(vec, forward);
     if (dot > 0.3)
         return qtrue;
     return qfalse;
 }
InitBodyQue()
void InitBodyQue (void)
Definition at line 887 of file p_client.c.
 {
     int     i;
     edict_t *ent;
     level.body_que = 0;
     for (i = 0; i < BODY_QUEUE_SIZE ; i++) {
         ent = G_Spawn();
         ent->classname = "bodyque";
     }
 }
Referenced by SP_worldspawn().
InitClientPersistant()
void InitClientPersistant (gclient_t * client)
Definition at line 575 of file p_client.c.
 {
     gitem_t     *item;
     memset(&client->pers, 0, sizeof(client->pers));
     item = FindItem("Blaster");
     client->pers.selected_item = ITEM_INDEX(item);
     client->pers.inventory[client->pers.selected_item] = 1;
     client->pers.weapon = item;
     if (sv_flaregun->integer > 0)
     {
         // Q2RTX: Spawn with a flare gun and some grenades to use with it.
         // Flare gun is new and not found anywhere in the game as a pickup item.
         gitem_t* item_flareg = FindItem("Flare Gun");
         if (item_flareg)
         {
             client->pers.inventory[ITEM_INDEX(item_flareg)] = 1;
             if (sv_flaregun->integer == 2)
             {
                 gitem_t* item_grenades = FindItem("Grenades");
                 client->pers.inventory[ITEM_INDEX(item_grenades)] = 5;
             }
         }
     }
     client->pers.health         = 100;
     client->pers.max_health     = 100;
     client->pers.max_bullets    = 200;
     client->pers.max_shells     = 100;
     client->pers.max_rockets    = 50;
     client->pers.max_grenades   = 50;
     client->pers.max_cells      = 200;
     client->pers.max_slugs      = 50;
     client->pers.connected = qtrue;
 }
Referenced by ClientConnect(), and PutClientInServer().
InitClientResp()
void InitClientResp (gclient_t * client)
Definition at line 618 of file p_client.c.
 {
     memset(&client->resp, 0, sizeof(client->resp));
     client->resp.enterframe = level.framenum;
     client->resp.coop_respawn = client->pers;
 }
Referenced by ClientBegin(), ClientBeginDeathmatch(), and ClientConnect().
InitItems()
void InitItems (void)
Definition at line 2132 of file g_items.c.
 {
     game.num_items = sizeof(itemlist) / sizeof(itemlist[0]) - 1;
 }
Referenced by InitGame().
KillBox()
qboolean KillBox (edict_t * ent)
Definition at line 515 of file g_utils.c.
 {
     trace_t     tr;
     while (1) {
         tr = gi.trace(ent->s.origin, ent->mins, ent->maxs, ent->s.origin, NULL, MASK_PLAYERSOLID);
         if (!tr.ent)
             break;
         // nail it
         T_Damage(tr.ent, ent, ent, vec3_origin, ent->s.origin, vec3_origin, 100000, 0, DAMAGE_NO_PROTECTION, MOD_TELEFRAG);
         // if we didn't kill it, fail
         if (tr.ent->solid)
             return qfalse;
     }
     return qtrue;        // all clear
 }
Referenced by func_explosive_spawn(), func_object_use(), func_wall_use(), monster_triggered_spawn(), PutClientInServer(), teleporter_touch(), use_killbox(), and use_target_spawner().
M_CatagorizePosition()
void M_CatagorizePosition (edict_t * ent)
Definition at line 178 of file g_monster.c.
 {
     vec3_t      point;
     int         cont;
 //
 // get waterlevel
 //
     point[0] = ent->s.origin[0];
     point[1] = ent->s.origin[1];
     point[2] = ent->s.origin[2] + ent->mins[2] + 1;
     cont = gi.pointcontents(point);
     if (!(cont & MASK_WATER)) {
         ent->waterlevel = 0;
         ent->watertype = 0;
         return;
     }
     ent->watertype = cont;
     ent->waterlevel = 1;
     point[2] += 26;
     cont = gi.pointcontents(point);
     if (!(cont & MASK_WATER))
         return;
     ent->waterlevel = 2;
     point[2] += 22;
     cont = gi.pointcontents(point);
     if (cont & MASK_WATER)
         ent->waterlevel = 3;
 }
Referenced by M_droptofloor(), and monster_think().
M_ChangeYaw()
void M_ChangeYaw (edict_t * ent)
Definition at line 279 of file m_move.c.
 {
     float   ideal;
     float   current;
     float   move;
     float   speed;
     current = anglemod(ent->s.angles[YAW]);
     ideal = ent->ideal_yaw;
     if (current == ideal)
         return;
     move = ideal - current;
     speed = ent->yaw_speed;
     if (ideal > current) {
         if (move >= 180)
             move = move - 360;
     } else {
         if (move <= -180)
             move = move + 360;
     }
     if (move > 0) {
         if (move > speed)
             move = speed;
     } else {
         if (move < -speed)
             move = -speed;
     }
     ent->s.angles[YAW] = anglemod(current + move);
 }
Referenced by ai_charge(), ai_run_melee(), ai_run_missile(), ai_run_slide(), ai_stand(), ai_turn(), FindTarget(), and SV_StepDirection().
M_CheckAttack()
qboolean M_CheckAttack (edict_t * self)
Definition at line 553 of file g_ai.c.
 {
     vec3_t  spot1, spot2;
     float   chance;
     trace_t tr;
     if (self->enemy->health > 0) {
         // see if any entities are in the way of the shot
         VectorCopy(self->s.origin, spot1);
         spot1[2] += self->viewheight;
         VectorCopy(self->enemy->s.origin, spot2);
         spot2[2] += self->enemy->viewheight;
         tr = gi.trace(spot1, NULL, NULL, spot2, self, CONTENTS_SOLID | CONTENTS_MONSTER | CONTENTS_SLIME | CONTENTS_LAVA | CONTENTS_WINDOW);
         // do we have a clear shot?
         if (tr.ent != self->enemy)
             return qfalse;
     }
     // melee attack
     if (enemy_range == RANGE_MELEE) {
         // don't always melee in easy mode
         if (skill->value == 0 && (rand() & 3))
             return qfalse;
         if (self->monsterinfo.melee)
             self->monsterinfo.attack_state = AS_MELEE;
         else
             self->monsterinfo.attack_state = AS_MISSILE;
         return qtrue;
     }
 // missile attack
     if (!self->monsterinfo.attack)
         return qfalse;
     if (level.time < self->monsterinfo.attack_finished)
         return qfalse;
     if (enemy_range == RANGE_FAR)
         return qfalse;
     if (self->monsterinfo.aiflags & AI_STAND_GROUND) {
         chance = 0.4;
     } else if (enemy_range == RANGE_MELEE) {
         chance = 0.2;
     } else if (enemy_range == RANGE_NEAR) {
         chance = 0.1;
     } else if (enemy_range == RANGE_MID) {
         chance = 0.02;
     } else {
         return qfalse;
     }
     if (skill->value == 0)
         chance *= 0.5;
     else if (skill->value >= 2)
         chance *= 2;
     if (random() < chance) {
         self->monsterinfo.attack_state = AS_MISSILE;
         self->monsterinfo.attack_finished = level.time + 2 * random();
         return qtrue;
     }
     if (self->flags & FL_FLY) {
         if (random() < 0.3)
             self->monsterinfo.attack_state = AS_SLIDING;
         else
             self->monsterinfo.attack_state = AS_STRAIGHT;
     }
     return qfalse;
 }
Referenced by medic_checkattack(), and monster_start().
M_CheckBottom()
qboolean M_CheckBottom (edict_t * ent)
Definition at line 35 of file m_move.c.
 {
     vec3_t  mins, maxs, start, stop;
     trace_t trace;
     int     x, y;
     float   mid, bottom;
     VectorAdd(ent->s.origin, ent->mins, mins);
     VectorAdd(ent->s.origin, ent->maxs, maxs);
 // if all of the points under the corners are solid world, don't bother
 // with the tougher checks
 // the corners must be within 16 of the midpoint
     start[2] = mins[2] - 1;
     for (x = 0 ; x <= 1 ; x++)
         for (y = 0 ; y <= 1 ; y++) {
             start[0] = x ? maxs[0] : mins[0];
             start[1] = y ? maxs[1] : mins[1];
             if (gi.pointcontents(start) != CONTENTS_SOLID)
                 goto realcheck;
         }
     c_yes++;
     return qtrue;        // we got out easy
 realcheck:
     c_no++;
 //
 // check it for real...
 //
     start[2] = mins[2];
 // the midpoint must be within 16 of the bottom
     start[0] = stop[0] = (mins[0] + maxs[0]) * 0.5;
     start[1] = stop[1] = (mins[1] + maxs[1]) * 0.5;
     stop[2] = start[2] - 2 * STEPSIZE;
     trace = gi.trace(start, vec3_origin, vec3_origin, stop, ent, MASK_MONSTERSOLID);
     if (trace.fraction == 1.0)
         return qfalse;
     mid = bottom = trace.endpos[2];
 // the corners must be within 16 of the midpoint
     for (x = 0 ; x <= 1 ; x++)
         for (y = 0 ; y <= 1 ; y++) {
             start[0] = stop[0] = x ? maxs[0] : mins[0];
             start[1] = stop[1] = y ? maxs[1] : mins[1];
             trace = gi.trace(start, vec3_origin, vec3_origin, stop, ent, MASK_MONSTERSOLID);
             if (trace.fraction != 1.0 && trace.endpos[2] > bottom)
                 bottom = trace.endpos[2];
             if (trace.fraction == 1.0 || mid - trace.endpos[2] > STEPSIZE)
                 return qfalse;
         }
     c_yes++;
     return qtrue;
 }
Referenced by mutant_jump_touch(), SV_movestep(), SV_NewChaseDir(), and SV_Physics_Step().
M_CheckGround()
void M_CheckGround (edict_t * ent)
Definition at line 139 of file g_monster.c.
 {
     vec3_t      point;
     trace_t     trace;
     if (ent->flags & (FL_SWIM | FL_FLY))
         return;
     if (ent->velocity[2] > 100) {
         ent->groundentity = NULL;
         return;
     }
 // if the hull point one-quarter unit down is solid the entity is on ground
     point[0] = ent->s.origin[0];
     point[1] = ent->s.origin[1];
     point[2] = ent->s.origin[2] - 0.25;
     trace = gi.trace(ent->s.origin, ent->mins, ent->maxs, point, ent, MASK_MONSTERSOLID);
     // check steepness
     if (trace.plane.normal[2] < 0.7 && !trace.startsolid) {
         ent->groundentity = NULL;
         return;
     }
 //  ent->groundentity = trace.ent;
 //  ent->groundentity_linkcount = trace.ent->linkcount;
 //  if (!trace.startsolid && !trace.allsolid)
 //      VectorCopy (trace.endpos, ent->s.origin);
     if (!trace.startsolid && !trace.allsolid) {
         VectorCopy(trace.endpos, ent->s.origin);
         ent->groundentity = trace.ent;
         ent->groundentity_linkcount = trace.ent->linkcount;
         ent->velocity[2] = 0;
     }
 }
Referenced by G_RunFrame(), M_droptofloor(), monster_think(), and SV_Physics_Step().
M_droptofloor()
void M_droptofloor (edict_t * ent)
Definition at line 286 of file g_monster.c.
 {
     vec3_t      end;
     trace_t     trace;
     ent->s.origin[2] += 1;
     VectorCopy(ent->s.origin, end);
     end[2] -= 256;
     trace = gi.trace(ent->s.origin, ent->mins, ent->maxs, end, ent, MASK_MONSTERSOLID);
     if (trace.fraction == 1 || trace.allsolid)
         return;
     VectorCopy(trace.endpos, ent->s.origin);
     gi.linkentity(ent);
     M_CheckGround(ent);
     M_CatagorizePosition(ent);
 }
Referenced by SP_misc_explobox(), and walkmonster_start_go().
M_FlyCheck()
void M_FlyCheck (edict_t * self)
Definition at line 121 of file g_monster.c.
 {
     if (self->waterlevel)
         return;
     if (random() > 0.5)
         return;
     self->think = M_FliesOn;
     self->nextthink = level.time + 5 + 10 * random();
 }
Referenced by infantry_dead(), and mutant_dead().
M_MoveToGoal()
void M_MoveToGoal (edict_t * ent, float dist)
Definition at line 477 of file m_move.c.
 {
     edict_t     *goal;
     goal = ent->goalentity;
     if (!ent->groundentity && !(ent->flags & (FL_FLY | FL_SWIM)))
         return;
 // if the next step hits the enemy, return immediately
     if (ent->enemy &&  SV_CloseEnough(ent, ent->enemy, dist))
         return;
 // bump around...
     if ((rand() & 3) == 1 || !SV_StepDirection(ent, ent->ideal_yaw, dist)) {
         if (ent->inuse)
             SV_NewChaseDir(ent, goal, dist);
     }
 }
Referenced by ai_run(), and ai_walk().
M_walkmove()
qboolean M_walkmove (edict_t * ent, float yaw, float dist)
Definition at line 503 of file m_move.c.
 {
     vec3_t  move;
     if (!ent->groundentity && !(ent->flags & (FL_FLY | FL_SWIM)))
         return qfalse;
     yaw = yaw * M_PI * 2 / 360;
     move[0] = cos(yaw) * dist;
     move[1] = sin(yaw) * dist;
     move[2] = 0;
     return SV_movestep(ent, move, qtrue);
 }
Referenced by ai_charge(), ai_move(), ai_run_slide(), ai_stand(), ai_turn(), barrel_touch(), flymonster_start_go(), and walkmonster_start_go().
monster_death_use()
void monster_death_use (edict_t * self)
Definition at line 470 of file g_monster.c.
 {
     self->flags &= ~(FL_FLY | FL_SWIM);
     self->monsterinfo.aiflags &= AI_GOOD_GUY;
     if (self->item) {
         Drop_Item(self, self->item);
         self->item = NULL;
     }
     if (self->deathtarget)
         self->target = self->deathtarget;
     if (!self->target)
         return;
     G_UseTargets(self, self->enemy);
 }
Referenced by Killed().
monster_fire_bfg()
void monster_fire_bfg (edict_t * self, vec3_t start, vec3_t aimdir, int damage, int speed, int kick, float damage_radius, int flashtype)
Definition at line 89 of file g_monster.c.
 {
     fire_bfg(self, start, aimdir, damage, speed, damage_radius);
     gi.WriteByte(svc_muzzleflash2);
     gi.WriteShort(self - g_edicts);
     gi.WriteByte(flashtype);
     gi.multicast(start, MULTICAST_PVS);
 }
Referenced by jorgBFG(), and makronBFG().
monster_fire_blaster()
void monster_fire_blaster (edict_t * self, vec3_t start, vec3_t dir, int damage, int speed, int flashtype, int effect)
Definition at line 49 of file g_monster.c.
 {
     fire_blaster(self, start, dir, damage, speed, effect, qfalse);
     gi.WriteByte(svc_muzzleflash2);
     gi.WriteShort(self - g_edicts);
     gi.WriteByte(flashtype);
     gi.multicast(start, MULTICAST_PVS);
 }
Referenced by floater_fire_blaster(), flyer_fire(), hover_fire_blaster(), MakronHyperblaster(), medic_fire_blaster(), soldier_fire(), and TankBlaster().
monster_fire_bullet()
void monster_fire_bullet (edict_t * self, vec3_t start, vec3_t dir, int damage, int kick, int hspread, int vspread, int flashtype)
Definition at line 29 of file g_monster.c.
 {
     fire_bullet(self, start, dir, damage, kick, hspread, vspread, MOD_UNKNOWN);
     gi.WriteByte(svc_muzzleflash2);
     gi.WriteShort(self - g_edicts);
     gi.WriteByte(flashtype);
     gi.multicast(start, MULTICAST_PVS);
 }
Referenced by actorMachineGun(), boss2_firebullet_left(), boss2_firebullet_right(), GunnerFire(), InfantryMachineGun(), jorg_firebullet_left(), jorg_firebullet_right(), soldier_fire(), supertankMachineGun(), and TankMachineGun().
monster_fire_grenade()
void monster_fire_grenade (edict_t * self, vec3_t start, vec3_t aimdir, int damage, int speed, int flashtype)
Definition at line 59 of file g_monster.c.
 {
     fire_grenade(self, start, aimdir, damage, speed, 2.5, damage + 40);
     gi.WriteByte(svc_muzzleflash2);
     gi.WriteShort(self - g_edicts);
     gi.WriteByte(flashtype);
     gi.multicast(start, MULTICAST_PVS);
 }
Referenced by GunnerGrenade().
monster_fire_railgun()
void monster_fire_railgun (edict_t * self, vec3_t start, vec3_t aimdir, int damage, int kick, int flashtype)
Definition at line 79 of file g_monster.c.
 {
     fire_rail(self, start, aimdir, damage, kick);
     gi.WriteByte(svc_muzzleflash2);
     gi.WriteShort(self - g_edicts);
     gi.WriteByte(flashtype);
     gi.multicast(start, MULTICAST_PVS);
 }
Referenced by GladiatorGun(), and MakronRailgun().
monster_fire_rocket()
void monster_fire_rocket (edict_t * self, vec3_t start, vec3_t dir, int damage, int speed, int flashtype)
Definition at line 69 of file g_monster.c.
 {
     fire_rocket(self, start, dir, damage, speed, damage + 20, damage);
     gi.WriteByte(svc_muzzleflash2);
     gi.WriteShort(self - g_edicts);
     gi.WriteByte(flashtype);
     gi.multicast(start, MULTICAST_PVS);
 }
Referenced by Boss2Rocket(), ChickRocket(), supertankRocket(), and TankRocket().
monster_fire_shotgun()
void monster_fire_shotgun (edict_t * self, vec3_t start, vec3_t aimdir, int damage, int kick, int hspread, int vspread, int count, int flashtype)
Definition at line 39 of file g_monster.c.
 {
     fire_shotgun(self, start, aimdir, damage, kick, hspread, vspread, count, MOD_UNKNOWN);
     gi.WriteByte(svc_muzzleflash2);
     gi.WriteShort(self - g_edicts);
     gi.WriteByte(flashtype);
     gi.multicast(start, MULTICAST_PVS);
 }
Referenced by soldier_fire().
monster_think()
void monster_think (edict_t * self)
Definition at line 382 of file g_monster.c.
 {
     M_MoveFrame(self);
     if (self->linkcount != self->monsterinfo.linkcount) {
         self->monsterinfo.linkcount = self->linkcount;
         M_CheckGround(self);
     }
     M_CatagorizePosition(self);
     M_WorldEffects(self);
     M_SetEffects(self);
 }
Referenced by monster_start_go().
MoveClientToIntermission()
void MoveClientToIntermission (edict_t * client)
Definition at line 30 of file p_hud.c.
 {
     if (deathmatch->value || coop->value)
         ent->client->showscores = qtrue;
     VectorCopy(level.intermission_origin, ent->s.origin);
     ent->client->ps.pmove.origin[0] = level.intermission_origin[0] * 8;
     ent->client->ps.pmove.origin[1] = level.intermission_origin[1] * 8;
     ent->client->ps.pmove.origin[2] = level.intermission_origin[2] * 8;
     VectorCopy(level.intermission_angle, ent->client->ps.viewangles);
     ent->client->ps.pmove.pm_type = PM_FREEZE;
     ent->client->ps.gunindex = 0;
     ent->client->ps.blend[3] = 0;
     ent->client->ps.rdflags &= ~RDF_UNDERWATER;
     // clean up powerup info
     ent->client->quad_framenum = 0;
     ent->client->invincible_framenum = 0;
     ent->client->breather_framenum = 0;
     ent->client->enviro_framenum = 0;
     ent->client->grenade_blew_up = qfalse;
     ent->client->grenade_time = 0;
     ent->viewheight = 0;
     ent->s.modelindex = 0;
     ent->s.modelindex2 = 0;
     ent->s.modelindex3 = 0;
     ent->s.modelindex = 0;
     ent->s.effects = 0;
     ent->s.sound = 0;
     ent->solid = SOLID_NOT;
     // add the layout
     if (deathmatch->value || coop->value) {
         DeathmatchScoreboardMessage(ent, NULL);
         gi.unicast(ent, qtrue);
     }
 }
Referenced by BeginIntermission(), ClientBegin(), and ClientBeginDeathmatch().
OnSameTeam()
qboolean OnSameTeam (edict_t * ent1, edict_t * ent2)
Definition at line 46 of file g_cmds.c.
 {
     char    ent1Team [512];
     char    ent2Team [512];
     if (!((int)(dmflags->value) & (DF_MODELTEAMS | DF_SKINTEAMS)))
         return qfalse;
     strcpy(ent1Team, ClientTeam(ent1));
     strcpy(ent2Team, ClientTeam(ent2));
     if (strcmp(ent1Team, ent2Team) == 0)
         return qtrue;
     return qfalse;
 }
Referenced by Cmd_Say_f(), and T_Damage().
player_die()
void player_die (edict_t * self, edict_t * inflictor, edict_t * attacker, int damage, vec3_t point)
Definition at line 476 of file p_client.c.
 {
     int     n;
     VectorClear(self->avelocity);
     self->takedamage = DAMAGE_YES;
     self->movetype = MOVETYPE_TOSS;
     self->s.modelindex2 = 0;    // remove linked weapon model
     self->s.angles[0] = 0;
     self->s.angles[2] = 0;
     self->s.sound = 0;
     self->client->weapon_sound = 0;
     self->maxs[2] = -8;
 //  self->solid = SOLID_NOT;
     self->svflags |= SVF_DEADMONSTER;
     if (!self->deadflag) {
         self->client->respawn_time = level.time + 1.0;
         LookAtKiller(self, inflictor, attacker);
         self->client->ps.pmove.pm_type = PM_DEAD;
         ClientObituary(self, inflictor, attacker);
         TossClientWeapon(self);
         if (deathmatch->value)
             Cmd_Help_f(self);       // show scores
         // clear inventory
         // this is kind of ugly, but it's how we want to handle keys in coop
         for (n = 0; n < game.num_items; n++) {
             if (coop->value && itemlist[n].flags & IT_KEY)
                 self->client->resp.coop_respawn.inventory[n] = self->client->pers.inventory[n];
             self->client->pers.inventory[n] = 0;
         }
     }
     // remove powerups
     self->client->quad_framenum = 0;
     self->client->invincible_framenum = 0;
     self->client->breather_framenum = 0;
     self->client->enviro_framenum = 0;
     self->flags &= ~FL_POWER_ARMOR;
     if (self->health < -40) {
         // gib
         gi.sound(self, CHAN_BODY, gi.soundindex("misc/udeath.wav"), 1, ATTN_NORM, 0);
         for (n = 0; n < 4; n++)
             ThrowGib(self, "models/objects/gibs/sm_meat/tris.md2", damage, GIB_ORGANIC);
         ThrowClientHead(self, damage);
         self->takedamage = DAMAGE_NO;
     } else {
         // normal death
         if (!self->deadflag) {
             static int i;
             i = (i + 1) % 3;
             // start a death animation
             self->client->anim_priority = ANIM_DEATH;
             if (self->client->ps.pmove.pm_flags & PMF_DUCKED) {
                 self->s.frame = FRAME_crdeath1 - 1;
                 self->client->anim_end = FRAME_crdeath5;
             } else switch (i) {
                 case 0:
                     self->s.frame = FRAME_death101 - 1;
                     self->client->anim_end = FRAME_death106;
                     break;
                 case 1:
                     self->s.frame = FRAME_death201 - 1;
                     self->client->anim_end = FRAME_death206;
                     break;
                 case 2:
                     self->s.frame = FRAME_death301 - 1;
                     self->client->anim_end = FRAME_death308;
                     break;
                 }
             gi.sound(self, CHAN_VOICE, gi.soundindex(va("*death%i.wav", (rand() % 4) + 1)), 1, ATTN_NORM, 0);
         }
     }
     self->deadflag = DEAD_DEAD;
     gi.linkentity(self);
 }
Referenced by Cmd_Kill_f(), and PutClientInServer().
player_pain()
void player_pain (edict_t * self, edict_t * other, float kick, int damage)
Definition at line 170 of file p_client.c.
 {
     // player pain is handled at the end of the frame in P_DamageFeedback
 }
Referenced by PutClientInServer().
PlayerNoise()
void PlayerNoise (edict_t * who, vec3_t where, int type)
Definition at line 56 of file p_weapon.c.
 {
     edict_t     *noise;
     if (type == PNOISE_WEAPON) {
         if (who->client->silencer_shots) {
             who->client->silencer_shots--;
             return;
         }
     }
     if (deathmatch->value)
         return;
     if (who->flags & FL_NOTARGET)
         return;
     if (!who->mynoise) {
         noise = G_Spawn();
         noise->classname = "player_noise";
         VectorSet(noise->mins, -8, -8, -8);
         VectorSet(noise->maxs, 8, 8, 8);
         noise->owner = who;
         noise->svflags = SVF_NOCLIENT;
         who->mynoise = noise;
         noise = G_Spawn();
         noise->classname = "player_noise";
         VectorSet(noise->mins, -8, -8, -8);
         VectorSet(noise->maxs, 8, 8, 8);
         noise->owner = who;
         noise->svflags = SVF_NOCLIENT;
         who->mynoise2 = noise;
     }
     if (type == PNOISE_SELF || type == PNOISE_WEAPON) {
         noise = who->mynoise;
         level.sound_entity = noise;
         level.sound_entity_framenum = level.framenum;
     } else { // type == PNOISE_IMPACT
         noise = who->mynoise2;
         level.sound2_entity = noise;
         level.sound2_entity_framenum = level.framenum;
     }
     VectorCopy(where, noise->s.origin);
     VectorSubtract(where, noise->maxs, noise->absmin);
     VectorAdd(where, noise->maxs, noise->absmax);
     noise->teleport_time = level.time;
     gi.linkentity(noise);
 }
Referenced by bfg_touch(), Blaster_Fire(), blaster_touch(), Chaingun_Fire(), ClientThink(), fire_lead(), fire_rail(), Grenade_Explode(), Machinegun_Fire(), P_WorldEffects(), rocket_touch(), weapon_bfg_fire(), weapon_flaregun_fire(), weapon_grenadelauncher_fire(), weapon_railgun_fire(), Weapon_RocketLauncher_Fire(), weapon_shotgun_fire(), and weapon_supershotgun_fire().
PlayerTrail_Add()
void PlayerTrail_Add (vec3_t spot)
Definition at line 64 of file p_trail.c.
 {
     vec3_t  temp;
     if (!trail_active)
         return;
     VectorCopy(spot, trail[trail_head]->s.origin);
     trail[trail_head]->timestamp = level.time;
     VectorSubtract(spot, trail[PREV(trail_head)]->s.origin, temp);
     trail[trail_head]->s.angles[1] = vectoyaw(temp);
     trail_head = NEXT(trail_head);
 }
Referenced by ClientBeginServerFrame(), and PlayerTrail_New().
PlayerTrail_Init()
void PlayerTrail_Init (void)
Definition at line 47 of file p_trail.c.
 {
     int     n;
     if (deathmatch->value /* FIXME || coop */)
         return;
     for (n = 0; n < TRAIL_LENGTH; n++) {
         trail[n] = G_Spawn();
         trail[n]->classname = "player_trail";
     }
     trail_head = 0;
     trail_active = qtrue;
 }
Referenced by PlayerTrail_New(), and SpawnEntities().
PlayerTrail_LastSpot()
edict_t* PlayerTrail_LastSpot (void)
Definition at line 136 of file p_trail.c.
 {
     return trail[PREV(trail_head)];
 }
Referenced by ClientBeginServerFrame().
PlayerTrail_New()
void PlayerTrail_New (vec3_t spot)
Definition at line 82 of file p_trail.c.
 {
     if (!trail_active)
         return;
     PlayerTrail_Init();
     PlayerTrail_Add(spot);
 }
PlayerTrail_PickFirst()
edict_t* PlayerTrail_PickFirst (edict_t * self)
Definition at line 92 of file p_trail.c.
 {
     int     marker;
     int     n;
     if (!trail_active)
         return NULL;
     for (marker = trail_head, n = TRAIL_LENGTH; n; n--) {
         if (trail[marker]->timestamp <= self->monsterinfo.trail_time)
             marker = NEXT(marker);
         else
             break;
     }
     if (visible(self, trail[marker])) {
         return trail[marker];
     }
     if (visible(self, trail[PREV(marker)])) {
         return trail[PREV(marker)];
     }
     return trail[marker];
 }
Referenced by ai_run().
PlayerTrail_PickNext()
edict_t* PlayerTrail_PickNext (edict_t * self)
Definition at line 118 of file p_trail.c.
 {
     int     marker;
     int     n;
     if (!trail_active)
         return NULL;
     for (marker = trail_head, n = TRAIL_LENGTH; n; n--) {
         if (trail[marker]->timestamp <= self->monsterinfo.trail_time)
             marker = NEXT(marker);
         else
             break;
     }
     return trail[marker];
 }
Referenced by ai_run().
PowerArmorType()
int PowerArmorType (edict_t * ent)
Definition at line 655 of file g_items.c.
 {
     if (!ent->client)
         return POWER_ARMOR_NONE;
     if (!(ent->flags & FL_POWER_ARMOR))
         return POWER_ARMOR_NONE;
     if (ent->client->pers.inventory[power_shield_index] > 0)
         return POWER_ARMOR_SHIELD;
     if (ent->client->pers.inventory[power_screen_index] > 0)
         return POWER_ARMOR_SCREEN;
     return POWER_ARMOR_NONE;
 }
Referenced by CheckPowerArmor(), G_SetClientEffects(), and G_SetStats().
PrecacheItem()
void PrecacheItem (gitem_t * it)
Definition at line 937 of file g_items.c.
 {
     char    *s, *start;
     char    data[MAX_QPATH];
     int     len;
     gitem_t *ammo;
     if (!it)
         return;
     if (it->pickup_sound)
         gi.soundindex(it->pickup_sound);
     if (it->world_model)
         gi.modelindex(it->world_model);
     if (it->view_model)
         gi.modelindex(it->view_model);
     if (it->icon)
         gi.imageindex(it->icon);
     // parse everything for its ammo
     if (it->ammo && it->ammo[0]) {
         ammo = FindItem(it->ammo);
         if (ammo != it)
             PrecacheItem(ammo);
     }
     // parse the space seperated precache string for other items
     s = it->precaches;
     if (!s || !s[0])
         return;
     while (*s) {
         start = s;
         while (*s && *s != ' ')
             s++;
         len = s - start;
         if (len >= MAX_QPATH || len < 5)
             gi.error("PrecacheItem: %s has bad precache string", it->classname);
         memcpy(data, start, len);
         data[len] = 0;
         if (*s)
             s++;
         // determine type based on extension
         if (!strcmp(data + len - 3, "md2"))
             gi.modelindex(data);
         else if (!strcmp(data + len - 3, "sp2"))
             gi.modelindex(data);
         else if (!strcmp(data + len - 3, "wav"))
             gi.soundindex(data);
         if (!strcmp(data + len - 3, "pcx"))
             gi.imageindex(data);
     }
 }
Referenced by PrecacheItem(), SP_worldspawn(), and SpawnItem().
PutClientInServer()
void PutClientInServer (edict_t * ent)
Definition at line 1073 of file p_client.c.
 {
     vec3_t  mins = { -16, -16, -24};
     vec3_t  maxs = {16, 16, 32};
     int     index;
     vec3_t  spawn_origin, spawn_angles;
     gclient_t   *client;
     int     i;
     client_persistant_t saved;
     client_respawn_t    resp;
     // find a spawn point
     // do it before setting health back up, so farthest
     // ranging doesn't count this client
     SelectSpawnPoint(ent, spawn_origin, spawn_angles);
     index = ent - g_edicts - 1;
     client = ent->client;
     // deathmatch wipes most client data every spawn
     if (deathmatch->value) {
         char        userinfo[MAX_INFO_STRING];
         resp = client->resp;
         memcpy(userinfo, client->pers.userinfo, sizeof(userinfo));
         InitClientPersistant(client);
         ClientUserinfoChanged(ent, userinfo);
     } else {
 //      int         n;
         char        userinfo[MAX_INFO_STRING];
         resp = client->resp;
         memcpy(userinfo, client->pers.userinfo, sizeof(userinfo));
         // this is kind of ugly, but it's how we want to handle keys in coop
 //      for (n = 0; n < game.num_items; n++)
 //      {
 //          if (itemlist[n].flags & IT_KEY)
 //              resp.coop_respawn.inventory[n] = client->pers.inventory[n];
 //      }
         resp.coop_respawn.game_helpchanged = client->pers.game_helpchanged;
         resp.coop_respawn.helpchanged = client->pers.helpchanged;
         client->pers = resp.coop_respawn;
         ClientUserinfoChanged(ent, userinfo);
         if (resp.score > client->pers.score)
             client->pers.score = resp.score;
     }
     // clear everything but the persistant data
     saved = client->pers;
     memset(client, 0, sizeof(*client));
     client->pers = saved;
     if (client->pers.health <= 0)
         InitClientPersistant(client);
     client->resp = resp;
     // copy some data from the client to the entity
     FetchClientEntData(ent);
     // clear entity values
     ent->groundentity = NULL;
     ent->client = &game.clients[index];
     ent->takedamage = DAMAGE_AIM;
     ent->movetype = MOVETYPE_WALK;
     ent->viewheight = 22;
     ent->inuse = qtrue;
     ent->classname = "player";
     ent->mass = 200;
     ent->solid = SOLID_BBOX;
     ent->deadflag = DEAD_NO;
     ent->air_finished = level.time + 12;
     ent->clipmask = MASK_PLAYERSOLID;
     ent->model = "players/male/tris.md2";
     ent->pain = player_pain;
     ent->die = player_die;
     ent->waterlevel = 0;
     ent->watertype = 0;
     ent->flags &= ~FL_NO_KNOCKBACK;
     ent->svflags &= ~SVF_DEADMONSTER;
     VectorCopy(mins, ent->mins);
     VectorCopy(maxs, ent->maxs);
     VectorClear(ent->velocity);
     // clear playerstate values
     memset(&ent->client->ps, 0, sizeof(client->ps));
     client->ps.pmove.origin[0] = spawn_origin[0] * 8;
     client->ps.pmove.origin[1] = spawn_origin[1] * 8;
     client->ps.pmove.origin[2] = spawn_origin[2] * 8;
     if (deathmatch->value && ((int)dmflags->value & DF_FIXED_FOV)) {
         client->ps.fov = 90;
     } else {
         client->ps.fov = atoi(Info_ValueForKey(client->pers.userinfo, "fov"));
         if (client->ps.fov < 1)
             client->ps.fov = 90;
         else if (client->ps.fov > 160)
             client->ps.fov = 160;
     }
     client->ps.gunindex = gi.modelindex(client->pers.weapon->view_model);
     // clear entity state values
     ent->s.effects = 0;
     ent->s.modelindex = 255;        // will use the skin specified model
     ent->s.modelindex2 = 255;       // custom gun model
     // sknum is player num and weapon number
     // weapon number will be added in changeweapon
     ent->s.skinnum = ent - g_edicts - 1;
     ent->s.frame = 0;
     VectorCopy(spawn_origin, ent->s.origin);
     ent->s.origin[2] += 1;  // make sure off ground
     VectorCopy(ent->s.origin, ent->s.old_origin);
     // set the delta angle
     for (i = 0 ; i < 3 ; i++) {
         client->ps.pmove.delta_angles[i] = ANGLE2SHORT(spawn_angles[i] - client->resp.cmd_angles[i]);
     }
     ent->s.angles[PITCH] = 0;
     ent->s.angles[YAW] = spawn_angles[YAW];
     ent->s.angles[ROLL] = 0;
     VectorCopy(ent->s.angles, client->ps.viewangles);
     VectorCopy(ent->s.angles, client->v_angle);
     // spawn a spectator
     if (client->pers.spectator) {
         client->chase_target = NULL;
         client->resp.spectator = qtrue;
         ent->movetype = MOVETYPE_NOCLIP;
         ent->solid = SOLID_NOT;
         ent->svflags |= SVF_NOCLIENT;
         ent->client->ps.gunindex = 0;
         gi.linkentity(ent);
         return;
     } else
         client->resp.spectator = qfalse;
     if (!KillBox(ent)) {
         // could't spawn in?
     }
     gi.linkentity(ent);
     // force the current weapon up
     client->newweapon = client->pers.weapon;
     ChangeWeapon(ent);
 }
Referenced by ClientBegin(), ClientBeginDeathmatch(), respawn(), and spectator_respawn().
range()
int range (edict_t * self, edict_t * other)
Definition at line 245 of file g_ai.c.
 {
     vec3_t  v;
     float   len;
     VectorSubtract(self->s.origin, other->s.origin, v);
     len = VectorLength(v);
     if (len < MELEE_DISTANCE)
         return RANGE_MELEE;
     if (len < 500)
         return RANGE_NEAR;
     if (len < 1000)
         return RANGE_MID;
     return RANGE_FAR;
 }
Referenced by ai_checkattack(), boss2_attack(), Boss2_CheckAttack(), chick_rerocket(), chick_reslash(), CL_SetupThirdPersionView(), create_invalid_texture(), FindTarget(), fire_hit(), flyer_check_melee(), gladiator_attack(), gunner_attack(), infantry_attack(), Jorg_CheckAttack(), Makron_CheckAttack(), mutant_check_melee(), mutant_check_refire(), SelectRandomDeathmatchSpawnPoint(), soldier_attack1_refire1(), soldier_attack1_refire2(), soldier_attack2_refire1(), soldier_attack2_refire2(), soldier_attack6_refire(), soldier_sight(), supertank_attack(), and tank_attack().
respawn()
void respawn (edict_t * ent)
Definition at line 957 of file p_client.c.
 {
     if (deathmatch->value || coop->value) {
         // spectator's don't leave bodies
         if (self->movetype != MOVETYPE_NOCLIP)
             CopyToBodyQue(self);
         self->svflags &= ~SVF_NOCLIENT;
         PutClientInServer(self);
         // add a teleportation effect
         self->s.event = EV_PLAYER_TELEPORT;
         // hold in place briefly
         self->client->ps.pmove.pm_flags = PMF_TIME_TELEPORT;
         self->client->ps.pmove.pm_time = 14;
         self->client->respawn_time = level.time;
         return;
     }
     // restart the entire server
     gi.AddCommandString("pushmenu loadgame\n");
 }
Referenced by BeginIntermission(), and ClientBeginServerFrame().
SaveClientData()
void SaveClientData (void)
Definition at line 635 of file p_client.c.
 {
     int     i;
     edict_t *ent;
     for (i = 0 ; i < game.maxclients ; i++) {
         ent = &g_edicts[1 + i];
         if (!ent->inuse)
             continue;
         game.clients[i].pers.health = ent->health;
         game.clients[i].pers.max_health = ent->max_health;
         game.clients[i].pers.savedFlags = (ent->flags & (FL_GODMODE | FL_NOTARGET | FL_POWER_ARMOR));
         if (coop->value)
             game.clients[i].pers.score = ent->client->resp.score;
     }
 }
Referenced by SpawnEntities(), and WriteGame().
ServerCommand()
void ServerCommand (void)
Definition at line 275 of file g_svcmds.c.
 {
     char    *cmd;
     cmd = gi.argv(1);
     if (Q_stricmp(cmd, "test") == 0)
         Svcmd_Test_f();
     else if (Q_stricmp(cmd, "addip") == 0)
         SVCmd_AddIP_f();
     else if (Q_stricmp(cmd, "removeip") == 0)
         SVCmd_RemoveIP_f();
     else if (Q_stricmp(cmd, "listip") == 0)
         SVCmd_ListIP_f();
     else if (Q_stricmp(cmd, "writeip") == 0)
         SVCmd_WriteIP_f();
     else
         gi.cprintf(NULL, PRINT_HIGH, "Unknown server command \"%s\"\n", cmd);
 }
Referenced by GetGameAPI().
SetItemNames()
void SetItemNames (void)
Definition at line 2146 of file g_items.c.
 {
     int     i;
     gitem_t *it;
     for (i = 0 ; i < game.num_items ; i++) {
         it = &itemlist[i];
         gi.configstring(CS_ITEMS + i, it->pickup_name);
     }
     jacket_armor_index = ITEM_INDEX(FindItem("Jacket Armor"));
     combat_armor_index = ITEM_INDEX(FindItem("Combat Armor"));
     body_armor_index   = ITEM_INDEX(FindItem("Body Armor"));
     power_screen_index = ITEM_INDEX(FindItem("Power Screen"));
     power_shield_index = ITEM_INDEX(FindItem("Power Shield"));
 }
Referenced by SP_worldspawn().
SetRespawn()
void SetRespawn (edict_t * ent, float delay)
Definition at line 142 of file g_items.c.
 {
     ent->flags |= FL_RESPAWN;
     ent->svflags |= SVF_NOCLIENT;
     ent->solid = SOLID_NOT;
     ent->nextthink = level.time + delay;
     ent->think = DoRespawn;
     gi.linkentity(ent);
 }
Referenced by MegaHealth_think(), Pickup_Adrenaline(), Pickup_Ammo(), Pickup_AncientHead(), Pickup_Armor(), Pickup_Bandolier(), Pickup_Health(), Pickup_Pack(), Pickup_PowerArmor(), Pickup_Powerup(), and Pickup_Weapon().
SpawnItem()
void SpawnItem (edict_t * ent, gitem_t * item)
Definition at line 1003 of file g_items.c.
 {
     PrecacheItem(item);
     if (ent->spawnflags) {
         if (strcmp(ent->classname, "key_power_cube") != 0) {
             ent->spawnflags = 0;
             gi.dprintf("%s at %s has invalid spawnflags set\n", ent->classname, vtos(ent->s.origin));
         }
     }
     // some items will be prevented in deathmatch
     if (deathmatch->value) {
         if ((int)dmflags->value & DF_NO_ARMOR) {
             if (item->pickup == Pickup_Armor || item->pickup == Pickup_PowerArmor) {
                 G_FreeEdict(ent);
                 return;
             }
         }
         if ((int)dmflags->value & DF_NO_ITEMS) {
             if (item->pickup == Pickup_Powerup) {
                 G_FreeEdict(ent);
                 return;
             }
         }
         if ((int)dmflags->value & DF_NO_HEALTH) {
             if (item->pickup == Pickup_Health || item->pickup == Pickup_Adrenaline || item->pickup == Pickup_AncientHead) {
                 G_FreeEdict(ent);
                 return;
             }
         }
         if ((int)dmflags->value & DF_INFINITE_AMMO) {
             if ((item->flags == IT_AMMO) || (strcmp(ent->classname, "weapon_bfg") == 0)) {
                 G_FreeEdict(ent);
                 return;
             }
         }
     }
     if (coop->value && (strcmp(ent->classname, "key_power_cube") == 0)) {
         ent->spawnflags |= (1 << (8 + level.power_cubes));
         level.power_cubes++;
     }
     // don't let them drop items that stay in a coop game
     if ((coop->value) && (item->flags & IT_STAY_COOP)) {
         item->drop = NULL;
     }
     ent->item = item;
     ent->nextthink = level.time + 2 * FRAMETIME;    // items start after other solids
     ent->think = droptofloor;
     ent->s.effects = item->world_model_flags;
     ent->s.renderfx = RF_GLOW;
     if (ent->model)
         gi.modelindex(ent->model);
 }
Referenced by Cmd_Give_f(), ED_CallSpawn(), SP_item_health(), SP_item_health_large(), SP_item_health_mega(), and SP_item_health_small().
SV_FilterPacket()
qboolean SV_FilterPacket (char * from)
Definition at line 116 of file g_svcmds.c.
 {
     int     i;
     unsigned    in;
     byte m[4];
     char *p;
     i = 0;
     p = from;
     while (*p && i < 4) {
         m[i] = 0;
         while (*p >= '0' && *p <= '9') {
             m[i] = m[i] * 10 + (*p - '0');
             p++;
         }
         if (!*p || *p == ':')
             break;
         i++, p++;
     }
     in = *(unsigned *)m;
     for (i = 0 ; i < numipfilters ; i++)
         if ((in & ipfilters[i].mask) == ipfilters[i].compare)
             return (int)filterban->value;
     return (int)!filterban->value;
 }
Referenced by ClientConnect().
swimmonster_start()
void swimmonster_start (edict_t * self)
Definition at line 673 of file g_monster.c.
 {
     self->flags |= FL_SWIM;
     self->think = swimmonster_start_go;
     monster_start(self);
 }
Referenced by SP_monster_flipper().
T_Damage()
void T_Damage (edict_t * targ, edict_t * inflictor, edict_t * attacker, vec3_t dir, vec3_t point, vec3_t normal, int damage, int knockback, int dflags, int mod)
Definition at line 358 of file g_combat.c.
 {
     gclient_t   *client;
     int         take;
     int         save;
     int         asave;
     int         psave;
     int         te_sparks;
     if (!targ->takedamage)
         return;
     // friendly fire avoidance
     // if enabled you can't hurt teammates (but you can hurt yourself)
     // knockback still occurs
     if ((targ != attacker) && ((deathmatch->value && ((int)(dmflags->value) & (DF_MODELTEAMS | DF_SKINTEAMS))) || coop->value)) {
         if (OnSameTeam(targ, attacker)) {
             if ((int)(dmflags->value) & DF_NO_FRIENDLY_FIRE)
                 damage = 0;
             else
                 mod |= MOD_FRIENDLY_FIRE;
         }
     }
     meansOfDeath = mod;
     // easy mode takes half damage
     if (skill->value == 0 && deathmatch->value == 0 && targ->client) {
         damage *= 0.5;
         if (!damage)
             damage = 1;
     }
     client = targ->client;
     if (dflags & DAMAGE_BULLET)
         te_sparks = TE_BULLET_SPARKS;
     else
         te_sparks = TE_SPARKS;
     VectorNormalize(dir);
 // bonus damage for suprising a monster
     if (!(dflags & DAMAGE_RADIUS) && (targ->svflags & SVF_MONSTER) && (attacker->client) && (!targ->enemy) && (targ->health > 0))
         damage *= 2;
     if (targ->flags & FL_NO_KNOCKBACK)
         knockback = 0;
 // figure momentum add
     if (!(dflags & DAMAGE_NO_KNOCKBACK)) {
         if ((knockback) && (targ->movetype != MOVETYPE_NONE) && (targ->movetype != MOVETYPE_BOUNCE) && (targ->movetype != MOVETYPE_PUSH) && (targ->movetype != MOVETYPE_STOP)) {
             vec3_t  kvel;
             float   mass;
             if (targ->mass < 50)
                 mass = 50;
             else
                 mass = targ->mass;
             if (targ->client  && attacker == targ)
                 VectorScale(dir, 1600.0 * (float)knockback / mass, kvel);   // the rocket jump hack...
             else
                 VectorScale(dir, 500.0 * (float)knockback / mass, kvel);
             VectorAdd(targ->velocity, kvel, targ->velocity);
         }
     }
     take = damage;
     save = 0;
     // check for godmode
     if ((targ->flags & FL_GODMODE) && !(dflags & DAMAGE_NO_PROTECTION)) {
         take = 0;
         save = damage;
         SpawnDamage(te_sparks, point, normal, save);
     }
     // check for invincibility
     if ((client && client->invincible_framenum > level.framenum) && !(dflags & DAMAGE_NO_PROTECTION)) {
         if (targ->pain_debounce_time < level.time) {
             gi.sound(targ, CHAN_ITEM, gi.soundindex("items/protect4.wav"), 1, ATTN_NORM, 0);
             targ->pain_debounce_time = level.time + 2;
         }
         take = 0;
         save = damage;
     }
     psave = CheckPowerArmor(targ, point, normal, take, dflags);
     take -= psave;
     asave = CheckArmor(targ, point, normal, take, te_sparks, dflags);
     take -= asave;
     //treat cheat/powerup savings the same as armor
     asave += save;
     // team damage avoidance
     if (!(dflags & DAMAGE_NO_PROTECTION) && CheckTeamDamage(targ, attacker))
         return;
 // do the damage
     if (take) {
         if ((targ->svflags & SVF_MONSTER) || (client))
         {
             // SpawnDamage(TE_BLOOD, point, normal, take);
             SpawnDamage(TE_BLOOD, point, dir, take);
         }
         else
             SpawnDamage(te_sparks, point, normal, take);
         targ->health = targ->health - take;
         if (targ->health <= 0) {
             if ((targ->svflags & SVF_MONSTER) || (client))
                 targ->flags |= FL_NO_KNOCKBACK;
             Killed(targ, inflictor, attacker, take, point);
             return;
         }
     }
     if (targ->svflags & SVF_MONSTER) {
         M_ReactToDamage(targ, attacker);
         if (!(targ->monsterinfo.aiflags & AI_DUCKED) && (take)) {
             targ->pain(targ, attacker, knockback, take);
             // nightmare mode monsters don't go into pain frames often
             if (skill->value == 3)
                 targ->pain_debounce_time = level.time + 5;
         }
     } else if (client) {
         if (!(targ->flags & FL_GODMODE) && (take))
             targ->pain(targ, attacker, knockback, take);
     } else if (take) {
         if (targ->pain)
             targ->pain(targ, attacker, knockback, take);
     }
     // add to the damage inflicted on a player this frame
     // the total will be turned into screen blends and view angle kicks
     // at the end of the frame
     if (client) {
         client->damage_parmor += psave;
         client->damage_armor += asave;
         client->damage_blood += take;
         client->damage_knockback += knockback;
         VectorCopy(point, client->damage_from);
     }
 }
Referenced by bfg_explode(), bfg_think(), bfg_touch(), blaster_touch(), door_blocked(), door_secret_blocked(), fire_hit(), fire_lead(), fire_rail(), floater_zap(), func_object_touch(), Grenade_Explode(), hurt_touch(), KillBox(), M_WorldEffects(), mutant_jump_touch(), P_FallingDamage(), P_WorldEffects(), parasite_drain_attack(), plat_blocked(), rocket_touch(), rotating_blocked(), rotating_touch(), T_RadiusDamage(), target_laser_think(), train_blocked(), turret_blocked(), and use_target_changelevel().
T_RadiusDamage()
void T_RadiusDamage (edict_t * inflictor, edict_t * attacker, float damage, edict_t * ignore, float radius, int mod)
Definition at line 514 of file g_combat.c.
 {
     float   points;
     edict_t *ent = NULL;
     vec3_t  v;
     vec3_t  dir;
     while ((ent = findradius(ent, inflictor->s.origin, radius)) != NULL) {
         if (ent == ignore)
             continue;
         if (!ent->takedamage)
             continue;
         VectorAdd(ent->mins, ent->maxs, v);
         VectorMA(ent->s.origin, 0.5, v, v);
         VectorSubtract(inflictor->s.origin, v, v);
         points = damage - 0.5 * VectorLength(v);
         if (ent == attacker)
             points = points * 0.5;
         if (points > 0) {
             if (CanDamage(ent, inflictor)) {
                 VectorSubtract(ent->s.origin, inflictor->s.origin, dir);
                 T_Damage(ent, inflictor, attacker, dir, inflictor->s.origin, vec3_origin, (int)points, (int)points, DAMAGE_RADIUS, mod);
             }
         }
     }
 }
Referenced by barrel_explode(), bfg_touch(), func_explosive_explode(), Grenade_Explode(), misc_viper_bomb_touch(), rocket_touch(), target_explosion_explode(), and use_target_splash().
Think_Weapon()
void Think_Weapon (edict_t * ent)
Definition at line 260 of file p_weapon.c.
 {
     // if just died, put the weapon away
     if (ent->health < 1) {
         ent->client->newweapon = NULL;
         ChangeWeapon(ent);
     }
     // call active weapon think routine
     if (ent->client->pers.weapon && ent->client->pers.weapon->weaponthink) {
         is_quad = (ent->client->quad_framenum > level.framenum);
         if (ent->client->silencer_shots)
             is_silenced = MZ_SILENCED;
         else
             is_silenced = 0;
         ent->client->pers.weapon->weaponthink(ent);
     }
 }
Referenced by ClientBeginServerFrame(), and ClientThink().
ThrowClientHead()
void ThrowClientHead (edict_t * self, int damage)
Definition at line 218 of file g_misc.c.
 {
     vec3_t  vd;
     char    *gibname;
     if (rand() & 1) {
         gibname = "models/objects/gibs/head2/tris.md2";
         self->s.skinnum = 1;        // second skin is player
     } else {
         gibname = "models/objects/gibs/skull/tris.md2";
         self->s.skinnum = 0;
     }
     self->s.origin[2] += 32;
     self->s.frame = 0;
     gi.setmodel(self, gibname);
     VectorSet(self->mins, -16, -16, 0);
     VectorSet(self->maxs, 16, 16, 16);
     self->takedamage = DAMAGE_NO;
     self->solid = SOLID_NOT;
     self->s.effects = EF_GIB;
     self->s.sound = 0;
     self->flags |= FL_NO_KNOCKBACK;
     self->movetype = MOVETYPE_BOUNCE;
     VelocityForDamage(damage, vd);
     VectorAdd(self->velocity, vd, self->velocity);
     if (self->client) { // bodies in the queue don't have a client anymore
         self->client->anim_priority = ANIM_DEATH;
         self->client->anim_end = self->s.frame;
     } else {
         self->think = NULL;
         self->nextthink = 0;
     }
     gi.linkentity(self);
 }
Referenced by body_die(), and player_die().
ThrowDebris()
void ThrowDebris (edict_t * self, char * modelname, float speed, vec3_t origin)
Definition at line 269 of file g_misc.c.
 {
     edict_t *chunk;
     vec3_t  v;
     chunk = G_Spawn();
     VectorCopy(origin, chunk->s.origin);
     gi.setmodel(chunk, modelname);
     v[0] = 100 * crandom();
     v[1] = 100 * crandom();
     v[2] = 100 + 100 * crandom();
     VectorMA(self->velocity, speed, v, chunk->velocity);
     chunk->movetype = MOVETYPE_BOUNCE;
     chunk->solid = SOLID_NOT;
     chunk->avelocity[0] = random() * 600;
     chunk->avelocity[1] = random() * 600;
     chunk->avelocity[2] = random() * 600;
     chunk->think = G_FreeEdict;
     chunk->nextthink = level.time + 5 + random() * 5;
     chunk->s.frame = 0;
     chunk->flags = 0;
     chunk->classname = "debris";
     chunk->takedamage = DAMAGE_YES;
     chunk->die = debris_die;
     gi.linkentity(chunk);
 }
Referenced by barrel_explode(), func_explosive_explode(), and rocket_touch().
ThrowGib()
void ThrowGib (edict_t * self, char * gibname, int damage, int type)
Definition at line 130 of file g_misc.c.
 {
     edict_t *gib;
     vec3_t  vd;
     vec3_t  origin;
     vec3_t  size;
     float   vscale;
     gib = G_Spawn();
     VectorScale(self->size, 0.5, size);
     VectorAdd(self->absmin, size, origin);
     gib->s.origin[0] = origin[0] + crandom() * size[0];
     gib->s.origin[1] = origin[1] + crandom() * size[1];
     gib->s.origin[2] = origin[2] + crandom() * size[2];
     gi.setmodel(gib, gibname);
     gib->solid = SOLID_NOT;
     gib->s.effects |= EF_GIB;
     gib->flags |= FL_NO_KNOCKBACK;
     gib->takedamage = DAMAGE_YES;
     gib->die = gib_die;
     if (type == GIB_ORGANIC) {
         gib->movetype = MOVETYPE_TOSS;
         gib->touch = gib_touch;
         vscale = 0.5;
     } else {
         gib->movetype = MOVETYPE_BOUNCE;
         vscale = 1.0;
     }
     VelocityForDamage(damage, vd);
     VectorMA(self->velocity, vscale, vd, gib->velocity);
     ClipGibVelocity(gib);
     gib->avelocity[0] = random() * 600;
     gib->avelocity[1] = random() * 600;
     gib->avelocity[2] = random() * 600;
     gib->think = G_FreeEdict;
     gib->nextthink = level.time + 10 + random() * 10;
     gi.linkentity(gib);
 }
Referenced by actor_die(), berserk_die(), body_die(), boss2_die(), BossExplode(), brain_die(), chick_die(), flipper_die(), gladiator_die(), gunner_die(), hover_die(), infantry_die(), insane_die(), makron_die(), medic_die(), misc_deadsoldier_die(), mutant_die(), parasite_die(), player_die(), soldier_die(), and tank_die().
ThrowHead()
void ThrowHead (edict_t * self, char * gibname, int damage, int type)
Definition at line 175 of file g_misc.c.
 {
     vec3_t  vd;
     float   vscale;
     self->s.skinnum = 0;
     self->s.frame = 0;
     VectorClear(self->mins);
     VectorClear(self->maxs);
     self->s.modelindex2 = 0;
     gi.setmodel(self, gibname);
     self->solid = SOLID_NOT;
     self->s.effects |= EF_GIB;
     self->s.effects &= ~EF_FLIES;
     self->s.sound = 0;
     self->flags |= FL_NO_KNOCKBACK;
     self->svflags &= ~SVF_MONSTER;
     self->takedamage = DAMAGE_YES;
     self->die = gib_die;
     if (type == GIB_ORGANIC) {
         self->movetype = MOVETYPE_TOSS;
         self->touch = gib_touch;
         vscale = 0.5;
     } else {
         self->movetype = MOVETYPE_BOUNCE;
         vscale = 1.0;
     }
     VelocityForDamage(damage, vd);
     VectorMA(self->velocity, vscale, vd, self->velocity);
     ClipGibVelocity(self);
     self->avelocity[YAW] = crandom() * 600;
     self->think = G_FreeEdict;
     self->nextthink = level.time + 10 + random() * 10;
     gi.linkentity(self);
 }
Referenced by actor_die(), berserk_die(), boss2_die(), BossExplode(), brain_die(), chick_die(), flipper_die(), gladiator_die(), gunner_die(), hover_die(), infantry_die(), insane_die(), makron_die(), medic_die(), misc_deadsoldier_die(), mutant_die(), parasite_die(), soldier_die(), and tank_die().
Touch_Item()
void Touch_Item (edict_t * ent, edict_t * other, cplane_t * plane, csurface_t * surf)
Definition at line 723 of file g_items.c.
 {
     qboolean    taken;
     if (!other->client)
         return;
     if (other->health < 1)
         return;     // dead people can't pickup
     if (!ent->item->pickup)
         return;     // not a grabbable item?
     taken = ent->item->pickup(ent, other);
     if (taken) {
         // flash the screen
         other->client->bonus_alpha = 0.25;
         // show icon and name on status bar
         other->client->ps.stats[STAT_PICKUP_ICON] = gi.imageindex(ent->item->icon);
         other->client->ps.stats[STAT_PICKUP_STRING] = CS_ITEMS + ITEM_INDEX(ent->item);
         other->client->pickup_msg_time = level.time + 3.0;
         // change selected item
         if (ent->item->use)
             other->client->pers.selected_item = other->client->ps.stats[STAT_SELECTED_ITEM] = ITEM_INDEX(ent->item);
         if (ent->item->pickup == Pickup_Health) {
             if (ent->count == 2)
                 gi.sound(other, CHAN_ITEM, gi.soundindex("items/s_health.wav"), 1, ATTN_NORM, 0);
             else if (ent->count == 10)
                 gi.sound(other, CHAN_ITEM, gi.soundindex("items/n_health.wav"), 1, ATTN_NORM, 0);
             else if (ent->count == 25)
                 gi.sound(other, CHAN_ITEM, gi.soundindex("items/l_health.wav"), 1, ATTN_NORM, 0);
             else // (ent->count == 100)
                 gi.sound(other, CHAN_ITEM, gi.soundindex("items/m_health.wav"), 1, ATTN_NORM, 0);
         } else if (ent->item->pickup_sound) {
             gi.sound(other, CHAN_ITEM, gi.soundindex(ent->item->pickup_sound), 1, ATTN_NORM, 0);
         }
     }
     if (!(ent->spawnflags & ITEM_TARGETS_USED)) {
         G_UseTargets(ent, other);
         ent->spawnflags |= ITEM_TARGETS_USED;
     }
     if (!taken)
         return;
     if (!((coop->value) && (ent->item->flags & IT_STAY_COOP)) || (ent->spawnflags & (DROPPED_ITEM | DROPPED_PLAYER_ITEM))) {
         if (ent->flags & FL_RESPAWN)
             ent->flags &= ~FL_RESPAWN;
         else
             G_FreeEdict(ent);
     }
 }
tv()
float* tv (float x, float y, float z)
Definition at line 248 of file g_utils.c.
 {
     static  int     index;
     static  vec3_t  vecs[8];
     float   *v;
     // use an array so that multiple tempvectors won't collide
     // for a while
     v = vecs[index];
     index = (index + 1) & 7;
     v[0] = x;
     v[1] = y;
     v[2] = z;
     return v;
 }
Referenced by droptofloor(), NET_Sleep(), and os_select().
UpdateChaseCam()
void UpdateChaseCam (edict_t * ent)
Definition at line 20 of file g_chase.c.
 {
     vec3_t o, ownerv, goal;
     edict_t *targ;
     vec3_t forward, right;
     trace_t trace;
     int i;
     vec3_t angles;
     // is our chase target gone?
     if (!ent->client->chase_target->inuse
         || ent->client->chase_target->client->resp.spectator) {
         edict_t *old = ent->client->chase_target;
         ChaseNext(ent);
         if (ent->client->chase_target == old) {
             ent->client->chase_target = NULL;
             ent->client->ps.pmove.pm_flags &= ~PMF_NO_PREDICTION;
             return;
         }
     }
     targ = ent->client->chase_target;
     VectorCopy(targ->s.origin, ownerv);
     ownerv[2] += targ->viewheight;
     VectorCopy(targ->client->v_angle, angles);
     if (angles[PITCH] > 56)
         angles[PITCH] = 56;
     AngleVectors(angles, forward, right, NULL);
     VectorNormalize(forward);
     VectorMA(ownerv, -30, forward, o);
     if (o[2] < targ->s.origin[2] + 20)
         o[2] = targ->s.origin[2] + 20;
     // jump animation lifts
     if (!targ->groundentity)
         o[2] += 16;
     trace = gi.trace(ownerv, vec3_origin, vec3_origin, o, targ, MASK_SOLID);
     VectorCopy(trace.endpos, goal);
     VectorMA(goal, 2, forward, goal);
     // pad for floors and ceilings
     VectorCopy(goal, o);
     o[2] += 6;
     trace = gi.trace(goal, vec3_origin, vec3_origin, o, targ, MASK_SOLID);
     if (trace.fraction < 1) {
         VectorCopy(trace.endpos, goal);
         goal[2] -= 6;
     }
     VectorCopy(goal, o);
     o[2] -= 6;
     trace = gi.trace(goal, vec3_origin, vec3_origin, o, targ, MASK_SOLID);
     if (trace.fraction < 1) {
         VectorCopy(trace.endpos, goal);
         goal[2] += 6;
     }
     if (targ->deadflag)
         ent->client->ps.pmove.pm_type = PM_DEAD;
     else
         ent->client->ps.pmove.pm_type = PM_FREEZE;
     VectorCopy(goal, ent->s.origin);
     for (i = 0 ; i < 3 ; i++)
         ent->client->ps.pmove.delta_angles[i] = ANGLE2SHORT(targ->client->v_angle[i] - ent->client->resp.cmd_angles[i]);
     if (targ->deadflag) {
         ent->client->ps.viewangles[ROLL] = 40;
         ent->client->ps.viewangles[PITCH] = -15;
         ent->client->ps.viewangles[YAW] = targ->client->killer_yaw;
     } else {
         VectorCopy(targ->client->v_angle, ent->client->ps.viewangles);
         VectorCopy(targ->client->v_angle, ent->client->v_angle);
     }
     ent->viewheight = 0;
     ent->client->ps.pmove.pm_flags |= PMF_NO_PREDICTION;
     gi.linkentity(ent);
 }
Referenced by ClientThink(), and GetChaseTarget().
ValidateSelectedItem()
void ValidateSelectedItem (edict_t * ent)
Definition at line 125 of file g_cmds.c.
 {
     gclient_t   *cl;
     cl = ent->client;
     if (cl->pers.inventory[cl->pers.selected_item])
         return;     // valid
     SelectNextItem(ent, -1);
 }
Referenced by Cmd_InvDrop_f(), Cmd_InvUse_f(), Drop_Ammo(), Drop_General(), Use_Breather(), Use_Envirosuit(), Use_Invulnerability(), Use_Quad(), and Use_Silencer().
vectoangles()
void vectoangles (vec3_t vec, vec3_t angles)
Definition at line 330 of file g_utils.c.
 {
     float   forward;
     float   yaw, pitch;
     if (value1[1] == 0 && value1[0] == 0) {
         yaw = 0;
         if (value1[2] > 0)
             pitch = 90;
         else
             pitch = 270;
     } else {
         if (value1[0])
             yaw = (int)(atan2(value1[1], value1[0]) * 180 / M_PI);
         else if (value1[1] > 0)
             yaw = 90;
         else
             yaw = -90;
         if (yaw < 0)
             yaw += 360;
         forward = sqrt(value1[0] * value1[0] + value1[1] * value1[1]);
         pitch = (int)(atan2(value1[2], forward) * 180 / M_PI);
         if (pitch < 0)
             pitch += 360;
     }
     angles[PITCH] = -pitch;
     angles[YAW] = yaw;
     angles[ROLL] = 0;
 }
Referenced by fire_bfg(), fire_blaster(), fire_flaregun(), fire_grenade(), fire_grenade2(), fire_lead(), fire_rocket(), flare_sparks(), gib_touch(), MakronHyperblaster(), medic_cable_attack(), misc_viper_bomb_prethink(), parasite_drain_attack_ok(), soldier_fire(), TankMachineGun(), turret_driver_link(), and turret_driver_think().
vectoyaw()
float vectoyaw (vec3_t vec)
Definition at line 310 of file g_utils.c.
 {
     float   yaw;
     if (/*vec[YAW] == 0 &&*/ vec[PITCH] == 0) {
         yaw = 0;
         if (vec[YAW] > 0)
             yaw = 90;
         else if (vec[YAW] < 0)
             yaw = -90;
     } else {
         yaw = (int)(atan2(vec[YAW], vec[PITCH]) * 180 / M_PI);
         if (yaw < 0)
             yaw += 360;
     }
     return yaw;
 }
Referenced by actor_pain(), actor_use(), ai_charge(), ai_checkattack(), ai_run(), ai_stand(), barrel_touch(), Boss2_CheckAttack(), FindTarget(), HuntTarget(), Jorg_CheckAttack(), Makron_CheckAttack(), MakronSpawn(), monster_start_go(), path_corner_touch(), PlayerTrail_Add(), and target_actor_touch().
visible()
qboolean visible (edict_t * self, edict_t * other)
Definition at line 268 of file g_ai.c.
 {
     vec3_t  spot1;
     vec3_t  spot2;
     trace_t trace;
     VectorCopy(self->s.origin, spot1);
     spot1[2] += self->viewheight;
     VectorCopy(other->s.origin, spot2);
     spot2[2] += other->viewheight;
     trace = gi.trace(spot1, vec3_origin, vec3_origin, spot2, self, MASK_OPAQUE);
     if (trace.fraction == 1.0)
         return qtrue;
     return qfalse;
 }
vtos()
char* vtos (vec3_t v)
Definition at line 275 of file g_utils.c.
 {
     static  int     index;
     static  char    str[8][32];
     char    *s;
     // use an array so that multiple vtos won't collide
     s = str[index];
     index = (index + 1) & 7;
     Q_snprintf(s, 32, "(%i %i %i)", (int)v[0], (int)v[1], (int)v[2]);
     return s;
 }
Referenced by actor_use(), droptofloor(), flymonster_start_go(), FoundTarget(), monster_start(), monster_start_go(), point_combat_touch(), SP_func_clock(), SP_func_door_rotating(), SP_func_timer(), SP_func_train(), SP_misc_actor(), SP_misc_strogg_ship(), SP_misc_viper(), SP_path_corner(), SP_target_actor(), SP_target_changelevel(), SP_target_earthquake(), SP_target_help(), SP_target_lightramp(), SP_target_speaker(), SP_trigger_gravity(), SP_trigger_key(), SP_trigger_once(), SP_turret_driver(), SpawnItem(), target_laser_start(), target_lightramp_use(), train_next(), turret_breach_finish_init(), and walkmonster_start_go().
walkmonster_start()
void walkmonster_start (edict_t * self)
Definition at line 630 of file g_monster.c.
 {
     self->think = walkmonster_start_go;
     monster_start(self);
 }
Referenced by SP_misc_actor(), SP_misc_insane(), SP_monster_berserk(), SP_monster_brain(), SP_monster_chick(), SP_monster_gladiator(), SP_monster_gunner(), SP_monster_infantry(), SP_monster_jorg(), SP_monster_makron(), SP_monster_medic(), SP_monster_mutant(), SP_monster_parasite(), SP_monster_soldier_x(), SP_monster_supertank(), and SP_monster_tank().
Variable Documentation
bob_pitch
cvar_t* bob_pitch
Definition at line 63 of file g_main.c.
Referenced by InitGame(), and SV_CalcViewOffset().
bob_roll
cvar_t* bob_roll
Definition at line 64 of file g_main.c.
Referenced by InitGame(), and SV_CalcViewOffset().
bob_up
cvar_t* bob_up
Definition at line 62 of file g_main.c.
Referenced by InitGame(), and SV_CalcViewOffset().
coop
cvar_t* coop
Definition at line 34 of file g_main.c.
Referenced by ai_run(), BeginIntermission(), ClientObituary(), Cmd_Score_f(), FetchClientEntData(), InitGame(), Killed(), MoveClientToIntermission(), Pickup_Key(), Pickup_Powerup(), Pickup_Weapon(), player_die(), respawn(), rocket_touch(), SaveClientData(), SelectSpawnPoint(), SP_info_player_coop(), SP_info_player_start(), SpawnItem(), T_Damage(), Touch_Item(), trigger_key_use(), and use_target_changelevel().
deathmatch
cvar_t* deathmatch
Definition at line 33 of file g_main.c.
Referenced by BeginIntermission(), bfg_think(), Chaingun_Fire(), CheckDMRules(), ClientBegin(), ClientBeginServerFrame(), ClientConnect(), ClientObituary(), ClientUserinfoChanged(), Cmd_Give_f(), Cmd_God_f(), Cmd_Help_f(), Cmd_Noclip_f(), Cmd_Notarget_f(), Cmd_Score_f(), drop_make_touchable(), G_SetStats(), InitGame(), Machinegun_Fire(), MegaHealth_think(), monster_start(), MoveClientToIntermission(), P_FallingDamage(), Pickup_Adrenaline(), Pickup_Ammo(), Pickup_AncientHead(), Pickup_Armor(), Pickup_Bandolier(), Pickup_Health(), Pickup_Pack(), Pickup_PowerArmor(), Pickup_Powerup(), Pickup_Weapon(), player_die(), PlayerNoise(), PlayerTrail_Init(), PutClientInServer(), respawn(), rocket_touch(), SelectSpawnPoint(), SP_func_door(), SP_func_explosive(), SP_info_player_deathmatch(), SP_item_health(), SP_item_health_large(), SP_item_health_mega(), SP_item_health_small(), SP_light(), SP_misc_actor(), SP_misc_deadsoldier(), SP_misc_explobox(), SP_misc_insane(), SP_monster_berserk(), SP_monster_boss2(), SP_monster_boss3_stand(), SP_monster_brain(), SP_monster_chick(), SP_monster_flipper(), SP_monster_floater(), SP_monster_flyer(), SP_monster_gladiator(), SP_monster_gunner(), SP_monster_hover(), SP_monster_infantry(), SP_monster_jorg(), SP_monster_makron(), SP_monster_medic(), SP_monster_mutant(), SP_monster_parasite(), SP_monster_soldier(), SP_monster_soldier_light(), SP_monster_soldier_ss(), SP_monster_supertank(), SP_monster_tank(), SP_point_combat(), SP_target_goal(), SP_target_help(), SP_target_lightramp(), SP_target_secret(), SP_turret_driver(), SP_worldspawn(), SpawnEntities(), SpawnItem(), T_Damage(), TossClientWeapon(), use_target_changelevel(), weapon_bfg_fire(), Weapon_Blaster_Fire(), Weapon_HyperBlaster_Fire(), weapon_railgun_fire(), and weapon_shotgun_fire().
dedicated
cvar_t* dedicated
Definition at line 46 of file g_main.c.
Referenced by AC_Connect(), BSP_Load(), check_paused(), CL_Init(), Cmd_Say_f(), InitGame(), MVD_SetChannel(), NET_OpenServer(), Qcommon_Frame(), Qcommon_Init(), SV_Loadgame_f(), SV_Map(), SV_NoSaveGames(), SV_Savegame_f(), SV_SetMaster_f(), SV_SpawnServer(), SVC_RemoteCommand(), Sys_Init(), and Sys_Quit().
dmflags
cvar_t* dmflags
Definition at line 35 of file g_main.c.
Referenced by Chaingun_Fire(), ClientBeginServerFrame(), ClientTeam(), ClientUserinfoChanged(), Cmd_Say_f(), Drop_Weapon(), EndDMLevel(), InitGame(), Machinegun_Fire(), OnSameTeam(), P_FallingDamage(), Pickup_Ammo(), Pickup_Powerup(), Pickup_Weapon(), PutClientInServer(), SelectDeathmatchSpawnPoint(), SP_item_health(), SP_item_health_large(), SP_item_health_mega(), SP_item_health_small(), SpawnItem(), T_Damage(), TossClientWeapon(), use_target_changelevel(), weapon_bfg_fire(), weapon_grenade_fire(), weapon_grenadelauncher_fire(), Weapon_HyperBlaster_Fire(), weapon_railgun_fire(), Weapon_RocketLauncher_Fire(), weapon_shotgun_fire(), and weapon_supershotgun_fire().
filterban
cvar_t* filterban
Definition at line 49 of file g_main.c.
Referenced by InitGame(), SV_FilterPacket(), and SVCmd_WriteIP_f().
flood_msgs
cvar_t* flood_msgs
Definition at line 68 of file g_main.c.
Referenced by Cmd_Say_f(), and InitGame().
flood_persecond
cvar_t* flood_persecond
Definition at line 69 of file g_main.c.
Referenced by Cmd_Say_f(), and InitGame().
flood_waitdelay
cvar_t* flood_waitdelay
Definition at line 70 of file g_main.c.
Referenced by Cmd_Say_f(), and InitGame().
fraglimit
cvar_t* fraglimit
Definition at line 37 of file g_main.c.
Referenced by CheckDMRules(), and InitGame().
g_edicts
edict_t* g_edicts
Definition at line 31 of file g_main.c.
Referenced by actor_pain(), AI_SetSightClient(), BeginIntermission(), Blaster_Fire(), Chaingun_Fire(), ChangeWeapon(), ChaseNext(), ChasePrev(), CheckDMRules(), ClientBegin(), ClientBeginDeathmatch(), ClientConnect(), ClientDisconnect(), ClientEndServerFrames(), ClientThink(), ClientUserinfoChanged(), Cmd_PlayerList_f(), Cmd_Say_f(), CopyToBodyQue(), DeathmatchScoreboardMessage(), ExitLevel(), findradius(), flare_sparks(), G_CheckChaseStats(), G_Find(), G_FindTeams(), G_FreeEdict(), G_InitEdict(), G_RunFrame(), G_SetSpectatorStats(), G_Spawn(), GetChaseTarget(), InitGame(), Machinegun_Fire(), medic_cable_attack(), monster_fire_bfg(), monster_fire_blaster(), monster_fire_bullet(), monster_fire_grenade(), monster_fire_railgun(), monster_fire_rocket(), monster_fire_shotgun(), parasite_drain_attack(), PlayersRangeFromSpot(), PutClientInServer(), read_field(), ReadGame(), ReadLevel(), SaveClientData(), SpawnEntities(), spectator_respawn(), SV_Physics_Toss(), SV_Push(), SV_TestEntityPosition(), target_actor_touch(), target_earthquake_think(), trigger_key_use(), use_target_changelevel(), weapon_bfg_fire(), weapon_flaregun_fire(), weapon_grenadelauncher_fire(), weapon_railgun_fire(), Weapon_RocketLauncher_Fire(), weapon_shotgun_fire(), weapon_supershotgun_fire(), write_field(), and WriteLevel().
g_select_empty
cvar_t* g_select_empty
Definition at line 45 of file g_main.c.
Referenced by InitGame(), and Use_Weapon().
game
game_locals_t game
Definition at line 21 of file g_main.c.
Referenced by AI_SetSightClient(), BeginIntermission(), CheckDMRules(), ClientBegin(), ClientConnect(), Cmd_Give_f(), Cmd_Help_f(), Cmd_Players_f(), Cmd_Say_f(), CopyToBodyQue(), DeathmatchScoreboardMessage(), ED_CallSpawn(), FindItem(), FindItemByClassname(), G_SetClientSound(), G_Spawn(), GetItemByIndex(), HelpComputer(), InitGame(), InitItems(), player_die(), PlayerSort(), PutClientInServer(), read_field(), ReadGame(), ReadLevel(), SaveClientData(), SelectCoopSpawnPoint(), SelectSpawnPoint(), SetItemNames(), SpawnEntities(), SV_LoadGameLibrary(), SVCmd_WriteIP_f(), target_actor_touch(), target_crosslevel_target_think(), trigger_crosslevel_trigger_use(), trigger_key_use(), use_target_changelevel(), Use_Target_Help(), write_field(), and WriteGame().
gi
game_import_t gi
Definition at line 23 of file g_main.c.
Referenced by actor_dead(), actor_pain(), actor_use(), ai_run(), BecomeExplosion1(), BecomeExplosion2(), berserk_dead(), berserk_die(), berserk_fidget(), berserk_pain(), berserk_search(), berserk_sight(), berserk_swing(), bfg_explode(), bfg_think(), bfg_touch(), Blaster_Fire(), blaster_touch(), body_die(), Boss2_CheckAttack(), boss2_dead(), boss2_die(), boss2_pain(), boss2_search(), BossExplode(), brain_chest_open(), brain_dead(), brain_die(), brain_duck_down(), brain_duck_up(), brain_hit_left(), brain_hit_right(), brain_idle(), brain_pain(), brain_search(), brain_sight(), brain_swing_left(), brain_swing_right(), brain_tentacle_attack(), button_fire(), CanDamage(), Chaingun_Fire(), ChangeWeapon(), check_dodge(), CheckDMRules(), CheckNeedPass(), chick_dead(), chick_die(), chick_duck_down(), chick_duck_up(), chick_pain(), Chick_PreAttack1(), chick_sight(), ChickMoan(), ChickReload(), ChickSlash(), ClientBegin(), ClientBeginDeathmatch(), ClientCommand(), ClientConnect(), ClientDisconnect(), ClientEndServerFrame(), ClientObituary(), ClientThink(), ClientUserinfoChanged(), Cmd_Drop_f(), Cmd_Give_f(), Cmd_God_f(), Cmd_InvDrop_f(), Cmd_Inven_f(), Cmd_InvUse_f(), Cmd_Noclip_f(), Cmd_Notarget_f(), Cmd_PlayerList_f(), Cmd_Players_f(), Cmd_Say_f(), Cmd_Use_f(), Cmd_Wave_f(), Com_Error(), Com_LPrintf(), commander_body_think(), commander_body_use(), CopyToBodyQue(), DeathmatchScoreboard(), DeathmatchScoreboardMessage(), door_go_down(), door_go_up(), door_hit_bottom(), door_hit_top(), door_touch(), door_use_areaportals(), DoRespawn(), Drop_Ammo(), Drop_Item(), Drop_Weapon(), droptofloor(), ED_CallSpawn(), ED_NewString(), ED_ParseEdict(), ED_ParseField(), ExitLevel(), FindTarget(), fire_bfg(), fire_blaster(), fire_flaregun(), fire_grenade(), fire_grenade2(), fire_hit(), fire_lead(), fire_rail(), fire_rocket(), flare_sparks(), flipper_dead(), flipper_die(), flipper_pain(), flipper_preattack(), flipper_sight(), floater_dead(), floater_die(), floater_idle(), floater_pain(), floater_sight(), floater_wham(), floater_zap(), flyer_die(), flyer_idle(), flyer_pain(), flyer_pop_blades(), flyer_sight(), flyer_slash_left(), flyer_slash_right(), flymonster_start_go(), FoundTarget(), func_explosive_spawn(), func_train_find(), func_wall_use(), G_CopyString(), G_FindTeams(), G_FreeEdict(), G_PickTarget(), G_RunEntity(), G_SetClientSound(), G_SetStats(), G_Spawn(), G_TouchSolids(), G_TouchTriggers(), G_UseTargets(), GaldiatorMelee(), GetChaseTarget(), GetGameAPI(), gib_touch(), gladiator_attack(), gladiator_cleaver_swing(), gladiator_dead(), gladiator_die(), gladiator_idle(), gladiator_pain(), gladiator_search(), gladiator_sight(), Grenade_Explode(), Grenade_Touch(), gunner_dead(), gunner_die(), gunner_duck_down(), gunner_duck_up(), gunner_idlesound(), gunner_opengun(), gunner_pain(), gunner_search(), gunner_sight(), HelpComputer(), hover_dead(), hover_die(), hover_pain(), hover_search(), hover_sight(), hurt_touch(), hurt_use(), infantry_cock_gun(), infantry_dead(), infantry_die(), infantry_duck_down(), infantry_duck_up(), infantry_fidget(), infantry_pain(), infantry_sight(), infantry_smack(), infantry_swing(), InitGame(), InitTrigger(), insane_dead(), insane_die(), insane_fist(), insane_moan(), insane_pain(), insane_scream(), insane_shake(), jorg_attack(), Jorg_CheckAttack(), jorg_dead(), jorg_death_hit(), jorg_die(), jorg_idle(), jorg_pain(), jorg_search(), jorg_step_left(), jorg_step_right(), jorgBFG(), KillBox(), light_use(), M_CatagorizePosition(), M_CheckAttack(), M_CheckBottom(), M_CheckGround(), M_droptofloor(), M_FliesOn(), M_WorldEffects(), Machinegun_Fire(), makron_brainsplorch(), Makron_CheckAttack(), makron_dead(), makron_die(), makron_hit(), makron_pain(), makron_popup(), makron_prerailgun(), makron_step_left(), makron_step_right(), makron_taunt(), makron_torso(), makronBFG(), MakronPrecache(), medic_cable_attack(), medic_dead(), medic_die(), medic_duck_down(), medic_duck_up(), medic_hook_launch(), medic_hook_retract(), medic_idle(), medic_pain(), medic_search(), medic_sight(), misc_deadsoldier_die(), monster_fire_bfg(), monster_fire_blaster(), monster_fire_bullet(), monster_fire_grenade(), monster_fire_railgun(), monster_fire_rocket(), monster_fire_shotgun(), monster_start(), monster_start_go(), monster_triggered_spawn(), MoveClientToIntermission(), mutant_check_landing(), mutant_dead(), mutant_die(), mutant_hit_left(), mutant_hit_right(), mutant_idle(), mutant_jump_takeoff(), mutant_pain(), mutant_search(), mutant_sight(), mutant_step(), mutant_swing(), P_DamageFeedback(), P_WorldEffects(), parasite_dead(), parasite_die(), parasite_drain_attack(), parasite_launch(), parasite_pain(), parasite_reel_in(), parasite_scratch(), parasite_search(), parasite_sight(), parasite_tap(), plat_go_down(), plat_go_up(), plat_hit_bottom(), plat_hit_top(), plat_spawn_inside_trigger(), player_die(), PlayerNoise(), PM_trace(), point_combat_touch(), PrecacheItem(), PutClientInServer(), read_data(), read_field(), read_index(), read_pointer(), read_string(), read_zstring(), ReadGame(), ReadLevel(), respawn(), rocket_touch(), SelectSpawnPoint(), ServerCommand(), SetItemNames(), SetRespawn(), ShutdownGame(), soldier_cock(), soldier_dead(), soldier_die(), soldier_duck_down(), soldier_duck_up(), soldier_idle(), soldier_pain(), soldier_sight(), SP_func_button(), SP_func_clock(), SP_func_conveyor(), SP_func_door(), SP_func_door_rotating(), SP_func_door_secret(), SP_func_explosive(), SP_func_killbox(), SP_func_object(), SP_func_plat(), SP_func_rotating(), SP_func_timer(), SP_func_train(), SP_func_wall(), SP_func_water(), SP_item_health(), SP_item_health_large(), SP_item_health_mega(), SP_item_health_small(), SP_light(), SP_light_mine1(), SP_light_mine2(), SP_misc_actor(), SP_misc_banner(), SP_misc_bigviper(), SP_misc_blackhole(), SP_misc_deadsoldier(), SP_misc_easterchick(), SP_misc_easterchick2(), SP_misc_eastertank(), SP_misc_explobox(), SP_misc_gib_arm(), SP_misc_gib_head(), SP_misc_gib_leg(), SP_misc_insane(), SP_misc_satellite_dish(), SP_misc_strogg_ship(), SP_misc_teleporter(), SP_misc_teleporter_dest(), SP_misc_viper(), SP_misc_viper_bomb(), SP_monster_berserk(), SP_monster_boss2(), SP_monster_boss3_stand(), SP_monster_brain(), SP_monster_chick(), SP_monster_commander_body(), SP_monster_flipper(), SP_monster_floater(), SP_monster_flyer(), SP_monster_gladiator(), SP_monster_gunner(), SP_monster_hover(), SP_monster_infantry(), SP_monster_jorg(), SP_monster_makron(), SP_monster_medic(), SP_monster_mutant(), SP_monster_parasite(), SP_monster_soldier(), SP_monster_soldier_light(), SP_monster_soldier_ss(), SP_monster_soldier_x(), SP_monster_supertank(), SP_monster_tank(), SP_path_corner(), SP_point_combat(), SP_target_actor(), SP_target_blaster(), SP_target_changelevel(), SP_target_character(), SP_target_earthquake(), SP_target_goal(), SP_target_help(), SP_target_lightramp(), SP_target_secret(), SP_target_speaker(), SP_trigger_gravity(), SP_trigger_hurt(), SP_trigger_key(), SP_trigger_multiple(), SP_trigger_once(), SP_trigger_push(), SP_turret_base(), SP_turret_breach(), SP_turret_driver(), SP_viewthing(), SP_worldspawn(), SpawnDamage(), SpawnEntities(), SpawnItem(), spectator_respawn(), StringToFilter(), supertank_dead(), supertank_die(), supertank_pain(), supertank_search(), SV_CalcBlend(), SV_FlyMove(), SV_movestep(), SV_Physics_Noclip(), SV_Physics_Pusher(), SV_Physics_Step(), SV_Physics_Toss(), SV_Push(), SV_PushEntity(), SV_RunThink(), SV_StepDirection(), SV_TestEntityPosition(), SVCmd_AddIP_f(), SVCmd_ListIP_f(), SVCmd_RemoveIP_f(), Svcmd_Test_f(), SVCmd_WriteIP_f(), T_Damage(), tank_dead(), tank_die(), tank_footstep(), tank_idle(), tank_pain(), tank_sight(), tank_thud(), tank_windup(), TankStrike(), target_actor_touch(), target_earthquake_think(), target_explosion_explode(), target_laser_start(), target_laser_think(), target_lightramp_think(), target_lightramp_use(), teleporter_touch(), Think_SpawnDoorTrigger(), ThrowClientHead(), ThrowDebris(), ThrowGib(), ThrowHead(), Touch_Item(), train_next(), train_wait(), TreadSound(), trigger_counter_use(), trigger_elevator_init(), trigger_elevator_use(), trigger_enable(), trigger_key_use(), trigger_push_touch(), turret_breach_finish_init(), turret_breach_fire(), UpdateChaseCam(), Use_Areaportal(), Use_Boss3(), Use_Invulnerability(), Use_Item(), Use_PowerArmor(), Use_Quad(), use_target_blaster(), use_target_changelevel(), use_target_goal(), use_target_secret(), use_target_spawner(), Use_Target_Speaker(), use_target_splash(), Use_Target_Tent(), Use_Weapon(), visible(), walkmonster_start_go(), weapon_bfg_fire(), weapon_flaregun_fire(), Weapon_Generic(), Weapon_Grenade(), weapon_grenadelauncher_fire(), Weapon_HyperBlaster_Fire(), weapon_railgun_fire(), Weapon_RocketLauncher_Fire(), weapon_shotgun_fire(), weapon_supershotgun_fire(), write_data(), write_field(), write_index(), write_pointer(), WriteGame(), and WriteLevel().
globals
game_export_t globals
Definition at line 24 of file g_main.c.
Referenced by findradius(), G_Find(), G_FindTeams(), G_RunFrame(), G_Spawn(), GetGameAPI(), InitGame(), ReadGame(), ReadLevel(), SpawnEntities(), SV_Push(), target_earthquake_think(), and WriteLevel().
gun_x
cvar_t* gun_x
Definition at line 56 of file g_main.c.
Referenced by InitGame(), and SV_CalcGunOffset().
gun_y
cvar_t * gun_y
Definition at line 526 of file g_local.h.
Referenced by SV_CalcGunOffset().
gun_z
cvar_t * gun_z
Definition at line 526 of file g_local.h.
Referenced by SV_CalcGunOffset().
itemlist
gitem_t itemlist[]
Definition at line 1063 of file g_items.c.
Referenced by BeginIntermission(), Cmd_Give_f(), Cmd_InvDrop_f(), Cmd_InvUse_f(), Cmd_WeapLast_f(), Cmd_WeapNext_f(), Cmd_WeapPrev_f(), ED_CallSpawn(), FindItem(), FindItemByClassname(), G_SetStats(), GetItemByIndex(), InitItems(), player_die(), read_field(), SelectNextItem(), SelectPrevItem(), SetItemNames(), and write_field().
level
level_locals_t level
Definition at line 22 of file g_main.c.
Referenced by actor_attack(), actor_fire(), actor_pain(), actor_run(), actor_stand(), ai_checkattack(), ai_run(), AI_SetSightClient(), ai_stand(), ai_walk(), AngleMove_Begin(), AngleMove_Calc(), AngleMove_Final(), AttackFinished(), barrel_delay(), BeginIntermission(), berserk_pain(), bfg_explode(), bfg_think(), bfg_touch(), Boss2_CheckAttack(), boss2_pain(), BossExplode(), brain_dodge(), brain_duck_hold(), brain_pain(), buddy_allocator_allocate(), buddy_allocator_free(), button_wait(), Chaingun_Fire(), ChangeWeapon(), CheckDMRules(), CheckPowerArmor(), chick_duck_down(), chick_duck_hold(), chick_pain(), CL_ParsePrint(), ClientBegin(), ClientBeginDeathmatch(), ClientBeginServerFrame(), ClientCommand(), ClientEndServerFrame(), ClientThink(), Cmd_Kill_f(), Cmd_PlayerList_f(), Cmd_Say_f(), commander_body_think(), commander_body_use(), CopyToBodyQue(), CreateTargetChangeLevel(), DeathmatchScoreboardMessage(), door_go_up(), door_hit_top(), door_secret_blocked(), door_secret_move1(), door_secret_move3(), door_secret_move5(), door_touch(), Drop_Item(), drop_make_touchable(), droptofloor(), EndDMLevel(), ExitLevel(), FindTarget(), finish_download(), fire_bfg(), fire_blaster(), fire_flaregun(), fire_grenade(), fire_grenade2(), fire_rocket(), flare_sparks(), flare_think(), flipper_pain(), floater_pain(), flyer_pain(), FoundTarget(), func_clock_think(), func_timer_think(), func_timer_use(), func_train_find(), G_FreeEdict(), G_RunFrame(), G_SetClientEffects(), G_SetClientSound(), G_SetSpectatorStats(), G_SetStats(), G_Spawn(), G_UseTargets(), get_level_offset(), gib_think(), gib_touch(), gladiator_pain(), gunner_duck_down(), gunner_duck_hold(), gunner_pain(), HelpComputer(), hover_dead(), hover_deadthink(), hover_pain(), hurt_touch(), infantry_cock_gun(), infantry_duck_down(), infantry_duck_hold(), infantry_fire(), infantry_pain(), InitBodyQue(), InitClientResp(), insane_pain(), Jorg_CheckAttack(), jorg_pain(), Killed(), M_CheckAttack(), M_FliesOn(), M_FlyCheck(), M_MoveFrame(), M_SetEffects(), M_WorldEffects(), Machinegun_Fire(), Makron_CheckAttack(), makron_pain(), makron_torso(), makron_torso_think(), MakronSpawn(), MakronToss(), medic_cable_attack(), medic_duck_down(), medic_duck_hold(), medic_pain(), MegaHealth_think(), merge_blocks(), misc_banner_think(), misc_blackhole_think(), misc_easterchick2_think(), misc_easterchick_think(), misc_eastertank_think(), misc_satellite_dish_think(), misc_satellite_dish_use(), misc_viper_bomb_prethink(), misc_viper_bomb_use(), monster_start(), monster_start_go(), monster_triggered_spawn(), monster_triggered_spawn_use(), Move_Begin(), Move_Calc(), Move_Final(), MoveClientToIntermission(), multi_trigger(), mutant_check_landing(), mutant_jump_takeoff(), mutant_pain(), MVD_BroadcastPrintf(), MVD_ParsePrint(), MVD_UnicastPrint(), os_getsockopt(), os_setsockopt(), P_DamageFeedback(), P_FallingDamage(), P_WorldEffects(), parasite_pain(), path_corner_touch(), PF_bprintf(), PF_cprintf(), Pickup_Health(), Pickup_Powerup(), plat_hit_top(), player_die(), PlayerNoise(), PlayerTrail_Add(), point_combat_touch(), PutClientInServer(), ReadLevel(), remove_block_from_free_list(), respawn(), S_Activate(), SetRespawn(), soldier_attack3_refire(), soldier_dodge(), soldier_duck_down(), soldier_duck_hold(), soldier_fire(), soldier_pain(), SP_CreateCoopSpots(), SP_func_clock(), SP_func_door(), SP_func_door_rotating(), SP_func_object(), SP_func_timer(), SP_func_train(), SP_info_player_coop(), SP_info_player_start(), SP_misc_banner(), SP_misc_blackhole(), SP_misc_easterchick(), SP_misc_easterchick2(), SP_misc_eastertank(), SP_misc_explobox(), SP_misc_gib_arm(), SP_misc_gib_head(), SP_misc_gib_leg(), SP_misc_strogg_ship(), SP_misc_viper(), SP_monster_boss3_stand(), SP_monster_commander_body(), SP_monster_flyer(), SP_target_changelevel(), SP_target_crosslevel_target(), SP_target_goal(), SP_target_laser(), SP_target_secret(), SP_trigger_elevator(), SP_turret_breach(), SP_turret_driver(), SP_viewthing(), SP_worldspawn(), SpawnEntities(), SpawnItem(), spectator_respawn(), supertank_pain(), SV_BroadcastPrintf(), SV_CalcBlend(), SV_CalcViewOffset(), SV_ClientPrintf(), SV_MvdBroadcastPrint(), SV_RunThink(), T_Damage(), tank_attack(), tank_pain(), target_actor_touch(), target_earthquake_think(), target_earthquake_use(), target_laser_think(), target_lightramp_think(), target_lightramp_use(), TH_viewthing(), Think_AccelMove(), Think_Boss3Stand(), Think_Weapon(), ThrowDebris(), ThrowGib(), ThrowHead(), TossClientWeapon(), Touch_DoorTrigger(), Touch_Item(), Touch_Plat_Center(), train_blocked(), train_wait(), trigger_key_use(), trigger_push_touch(), turret_breach_think(), turret_driver_link(), turret_driver_think(), Use_Breather(), Use_Envirosuit(), Use_Invulnerability(), Use_Quad(), use_target_changelevel(), use_target_explosion(), use_target_goal(), use_target_secret(), walkmonster_start_go(), weapon_bfg_fire(), Weapon_Generic(), Weapon_Grenade(), weapon_grenade_fire(), Weapon_HyperBlaster_Fire(), write_free_block_to_list(), and WriteLevel().
maxclients
cvar_t* maxclients
Definition at line 42 of file g_main.c.
Referenced by CheckDMRules(), ClientEndServerFrames(), ExitLevel(), and InitGame().
maxentities
cvar_t* maxentities
Definition at line 44 of file g_main.c.
Referenced by InitGame().
maxspectators
cvar_t* maxspectators
Definition at line 43 of file g_main.c.
Referenced by ClientConnect(), InitGame(), and spectator_respawn().
meansOfDeath
int meansOfDeath
Definition at line 29 of file g_main.c.
Referenced by ClientObituary(), Cmd_Kill_f(), and T_Damage().
needpass
cvar_t* needpass
Definition at line 41 of file g_main.c.
Referenced by InitGame().
nomonsters
cvar_t* nomonsters
Definition at line 47 of file g_main.c.
Referenced by InitGame(), and SpawnEntities().
password
cvar_t* password
Definition at line 39 of file g_main.c.
Referenced by auth_client(), CheckNeedPass(), ClientConnect(), InitGame(), MVD_Connect_f(), parse_hello(), and spectator_respawn().
run_pitch
cvar_t* run_pitch
Definition at line 60 of file g_main.c.
Referenced by InitGame(), and SV_CalcViewOffset().
run_roll
cvar_t* run_roll
Definition at line 61 of file g_main.c.
Referenced by InitGame(), and SV_CalcViewOffset().
skill
cvar_t* skill
Definition at line 36 of file g_main.c.
Referenced by berserk_pain(), brain_pain(), brain_tentacle_attack(), check_dodge(), chick_pain(), flipper_pain(), floater_pain(), flyer_pain(), gladiator_pain(), gunner_duck_down(), gunner_pain(), HelpComputer(), hover_pain(), infantry_pain(), InitGame(), insane_pain(), jorg_pain(), M_CheckAttack(), makron_pain(), medic_pain(), mutant_check_refire(), mutant_pain(), parasite_pain(), Pickup_Powerup(), soldier_attack1_refire1(), soldier_attack1_refire2(), soldier_attack2_refire1(), soldier_attack2_refire2(), soldier_attack6_refire(), soldier_dodge(), soldier_pain(), soldier_sight(), SpawnEntities(), supertank_pain(), T_Damage(), tank_pain(), tank_reattack_blaster(), tank_refire_rocket(), turret_breach_fire(), and turret_driver_think().
sm_meat_index
int sm_meat_index
Definition at line 27 of file g_main.c.
Referenced by gib_touch(), and SP_worldspawn().
snd_fry
int snd_fry
Definition at line 28 of file g_main.c.
Referenced by G_SetClientSound(), and SP_worldspawn().
spectator_password
cvar_t* spectator_password
Definition at line 40 of file g_main.c.
Referenced by CheckNeedPass(), ClientConnect(), InitGame(), and spectator_respawn().
st
spawn_temp_t st
Definition at line 25 of file g_main.c.
Referenced by Cmd_PlayerList_f(), ED_ParseEdict(), get_fp_info(), get_path_info(), monster_start(), plat_spawn_inside_trigger(), SP_func_button(), SP_func_door(), SP_func_door_rotating(), SP_func_plat(), SP_func_timer(), SP_func_train(), SP_func_water(), SP_target_actor(), SP_target_goal(), SP_target_secret(), SP_target_speaker(), SP_trigger_gravity(), SP_trigger_key(), SP_trigger_monsterjump(), SP_turret_breach(), SP_turret_driver(), and SP_worldspawn().
sv_cheats
cvar_t* sv_cheats
Definition at line 66 of file g_main.c.
Referenced by Cmd_Give_f(), Cmd_God_f(), Cmd_Noclip_f(), Cmd_Notarget_f(), and InitGame().
sv_features
cvar_t* sv_features
Definition at line 74 of file g_main.c.
Referenced by InitGame().
sv_flaregun
cvar_t* sv_flaregun
Definition at line 76 of file g_main.c.
Referenced by InitClientPersistant(), and InitGame().
sv_gravity
cvar_t* sv_gravity
Definition at line 52 of file g_main.c.
Referenced by ClientThink(), InitGame(), SV_AddGravity(), and SV_Physics_Step().
sv_maplist
cvar_t* sv_maplist
Definition at line 72 of file g_main.c.
Referenced by EndDMLevel(), and InitGame().
sv_maxvelocity
cvar_t* sv_maxvelocity
Definition at line 51 of file g_main.c.
Referenced by InitGame(), and SV_CheckVelocity().
sv_rollangle
cvar_t* sv_rollangle
Definition at line 55 of file g_main.c.
Referenced by InitGame(), and SV_CalcRoll().
sv_rollspeed
cvar_t* sv_rollspeed
Definition at line 54 of file g_main.c.
Referenced by InitGame(), and SV_CalcRoll().
timelimit
cvar_t* timelimit
Definition at line 38 of file g_main.c.
Referenced by CheckDMRules(), and InitGame().