Quake II RTX doxygen: C:/entry/dev/Q2RTX/src/client/ascii.c File Reference
ascii.c File Reference
#include "client.h"
Macros
#define CL_RTX_SHADERBALLS 1
#define TH_WIDTH 80
#define TH_HEIGHT 40
Functions
static void TH_DrawString (char *dst, int x, int y, char *src, size_t len)
static void TH_DrawCenterString (char *dst, int x, int y, char *src, size_t len)
static void TH_DrawNumber (char *dst, int x, int y, int width, int value)
static void TH_DrawLayoutString (char *dst, const char *s)
static void SCR_ScoreShot_f (void)
static void SCR_ScoreDump_f (void)
void CL_InitAscii (void)
Macro Definition Documentation
CL_RTX_SHADERBALLS
#define CL_RTX_SHADERBALLS 1
Definition at line 1036 of file client.h.
TH_HEIGHT
#define TH_HEIGHT 40
Definition at line 30 of file ascii.c.
TH_WIDTH
#define TH_WIDTH 80
Definition at line 29 of file ascii.c.
Function Documentation
CL_InitAscii()
void CL_InitAscii (void)
Definition at line 370 of file ascii.c.
 {
     Cmd_AddCommand("aashot", SCR_ScoreShot_f);
     Cmd_AddCommand("aadump", SCR_ScoreDump_f);
 }
Referenced by CL_InitLocal().
SCR_ScoreDump_f()
static void SCR_ScoreDump_f (void) static
Definition at line 348 of file ascii.c.
 {
     char buffer[(TH_WIDTH + 1) * TH_HEIGHT];
     int i;
     if (cls.state != ca_active) {
         Com_Printf("Must be in a level.\n");
         return;
     }
     memset(buffer, ' ', sizeof(buffer));
     for (i = 0; i < TH_HEIGHT - 1; i++) {
         buffer[i * (TH_WIDTH + 1) + TH_WIDTH] = '\n';
     }
     buffer[i * (TH_WIDTH + 1) + TH_WIDTH] = 0;
     TH_DrawLayoutString(buffer, cl.configstrings[CS_STATUSBAR]);
     TH_DrawLayoutString(buffer, cl.layout);
     Com_Printf("%s\n", buffer);
 }
Referenced by CL_InitAscii().
SCR_ScoreShot_f()
static void SCR_ScoreShot_f (void) static
Definition at line 293 of file ascii.c.
 {
     char buffer[(TH_WIDTH + 1) * TH_HEIGHT];
     char path[MAX_OSPATH];
     qhandle_t f;
     int i;
     qerror_t ret;
     if (cls.state != ca_active) {
         Com_Printf("Must be in a level.\n");
         return;
     }
     if (Cmd_Argc() > 1) {
         f = FS_EasyOpenFile(path, sizeof(path), FS_MODE_WRITE | FS_FLAG_TEXT,
                             "scoreshots/", Cmd_Argv(1), ".txt");
         if (!f) {
             return;
         }
     } else {
         // find a file name to save it to
         for (i = 0; i < 1000; i++) {
             Q_snprintf(path, sizeof(path), "scoreshots/quake%03d.txt", i);
             ret = FS_FOpenFile(path, &f, FS_MODE_WRITE | FS_FLAG_TEXT | FS_FLAG_EXCL);
             if (f) {
                 break;
             }
             if (ret != Q_ERR_EXIST) {
                 Com_EPrintf("Couldn't exclusively open %s for writing: %s\n",
                             path, Q_ErrorString(ret));
                 return;
             }
         }
         if (i == 1000) {
             Com_EPrintf("All scoreshot slots are full.\n");
             return;
         }
     }
     memset(buffer, ' ', sizeof(buffer));
     for (i = 0; i < TH_HEIGHT; i++) {
         buffer[i * (TH_WIDTH + 1) + TH_WIDTH] = '\n';
     }
     TH_DrawLayoutString(buffer, cl.configstrings[CS_STATUSBAR]);
     TH_DrawLayoutString(buffer, cl.layout);
     FS_Write(buffer, sizeof(buffer), f);
     FS_FCloseFile(f);
     Com_Printf("Wrote %s.\n", path);
 }
Referenced by CL_InitAscii().
TH_DrawCenterString()
static void TH_DrawCenterString (char * dst, int x, int y, char * src, size_t len) static
Definition at line 61 of file ascii.c.
 {
     x -= len / 2;
     if (x < 0) {
         src -= x;
         x = 0;
     }
     TH_DrawString(dst, x, y, src, len);
 }
Referenced by TH_DrawLayoutString().
TH_DrawLayoutString()
static void TH_DrawLayoutString (char * dst, const char * s) static
Definition at line 92 of file ascii.c.
 {
     char    buffer[MAX_QPATH];
     int     x, y;
     int     value;
     char    *token;
     size_t  len;
     int     width, index;
     clientinfo_t    *ci;
     if (!s[0])
         return;
     x = 0;
     y = 0;
     while (s) {
         token = COM_Parse(&s);
         if (token[2] == 0) {
             if (token[0] == 'x') {
                 if (token[1] == 'l') {
                     token = COM_Parse(&s);
                     x = atoi(token) / 8;
                     continue;
                 }
                 if (token[1] == 'r') {
                     token = COM_Parse(&s);
                     x = TH_WIDTH + atoi(token) / 8;
                     continue;
                 }
                 if (token[1] == 'v') {
                     token = COM_Parse(&s);
                     x = TH_WIDTH / 2 - 20 + atoi(token) / 8;
                     continue;
                 }
             }
             if (token[0] == 'y') {
                 if (token[1] == 't') {
                     token = COM_Parse(&s);
                     y = atoi(token) / 8;
                     continue;
                 }
                 if (token[1] == 'b') {
                     token = COM_Parse(&s);
                     y = TH_HEIGHT + atoi(token) / 8;
                     continue;
                 }
                 if (token[1] == 'v') {
                     token = COM_Parse(&s);
                     y = TH_HEIGHT / 2 - 15 + atoi(token) / 8;
                     continue;
                 }
             }
         }
         if (!strcmp(token, "pic")) {
             // draw a pic from a stat number
             COM_Parse(&s);
             continue;
         }
         if (!strcmp(token, "client")) {
             // draw a deathmatch client block
             int     score, ping, time;
             token = COM_Parse(&s);
             x = TH_WIDTH / 2 - 20 + atoi(token) / 8;
             token = COM_Parse(&s);
             y = TH_HEIGHT / 2 - 15 + atoi(token) / 8;
             token = COM_Parse(&s);
             value = atoi(token);
             if (value < 0 || value >= MAX_CLIENTS) {
                 Com_Error(ERR_DROP, "%s: invalid client index", __func__);
             }
             ci = &cl.clientinfo[value];
             token = COM_Parse(&s);
             score = atoi(token);
             token = COM_Parse(&s);
             ping = atoi(token);
             token = COM_Parse(&s);
             time = atoi(token);
             len = strlen(ci->name);
             TH_DrawString(dst, x + 4, y, ci->name, len);
             len = Q_scnprintf(buffer, sizeof(buffer), "Score: %i", score);
             TH_DrawString(dst, x + 4, y + 1, buffer, len);
             len = Q_scnprintf(buffer, sizeof(buffer), "Ping:  %i", ping);
             TH_DrawString(dst, x + 4, y + 2, buffer, len);
             len = Q_scnprintf(buffer, sizeof(buffer), "Time:  %i", time);
             TH_DrawString(dst, x + 4, y + 3, buffer, len);
             continue;
         }
         if (!strcmp(token, "ctf")) {
             // draw a ctf client block
             int     score, ping;
             token = COM_Parse(&s);
             x = TH_WIDTH / 2 - 20 + atoi(token) / 8;
             token = COM_Parse(&s);
             y = TH_HEIGHT / 2 - 15 + atoi(token) / 8;
             token = COM_Parse(&s);
             value = atoi(token);
             if (value < 0 || value >= MAX_CLIENTS) {
                 Com_Error(ERR_DROP, "%s: invalid client index", __func__);
             }
             ci = &cl.clientinfo[value];
             token = COM_Parse(&s);
             score = atoi(token);
             token = COM_Parse(&s);
             ping = atoi(token);
             if (ping > 999)
                 ping = 999;
             len = Q_scnprintf(buffer, sizeof(buffer), "%3d %3d %-12.12s",
                               score, ping, ci->name);
             TH_DrawString(dst, x, y, buffer, len);
             continue;
         }
         if (!strcmp(token, "picn")) {
             // draw a pic from a name
             COM_Parse(&s);
             continue;
         }
         if (!strcmp(token, "num")) {
             // draw a number
             token = COM_Parse(&s);
             width = atoi(token);
             token = COM_Parse(&s);
             value = atoi(token);
             if (value < 0 || value >= MAX_STATS) {
                 Com_Error(ERR_DROP, "%s: invalid stat index", __func__);
             }
             value = cl.frame.ps.stats[value];
             TH_DrawNumber(dst, x, y, width, value);
             continue;
         }
         if (!strcmp(token, "stat_string")) {
             token = COM_Parse(&s);
             index = atoi(token);
             if (index < 0 || index >= MAX_STATS) {
                 Com_Error(ERR_DROP, "%s: invalid string index", __func__);
             }
             index = cl.frame.ps.stats[index];
             if (index < 0 || index >= MAX_CONFIGSTRINGS) {
                 Com_Error(ERR_DROP, "%s: invalid string index", __func__);
             }
             len = strlen(cl.configstrings[index]);
             TH_DrawString(dst, x, y, cl.configstrings[index], len);
             continue;
         }
         if (!strncmp(token, "cstring", 7)) {
             token = COM_Parse(&s);
             len = strlen(token);
             TH_DrawCenterString(dst, x + 40 / 2, y, token, len);
             continue;
         }
         if (!strncmp(token, "string", 6)) {
             token = COM_Parse(&s);
             len = strlen(token);
             TH_DrawString(dst, x, y, token, len);
             continue;
         }
         if (!strcmp(token, "if")) {
             token = COM_Parse(&s);
             value = atoi(token);
             if (value < 0 || value >= MAX_STATS) {
                 Com_Error(ERR_DROP, "%s: invalid stat index", __func__);
             }
             value = cl.frame.ps.stats[value];
             if (!value) {   // skip to endif
                 while (strcmp(token, "endif")) {
                     token = COM_Parse(&s);
                     if (!s) {
                         break;
                     }
                 }
             }
             continue;
         }
     }
 }
Referenced by SCR_ScoreDump_f(), and SCR_ScoreShot_f().
TH_DrawNumber()
static void TH_DrawNumber (char * dst, int x, int y, int width, int value) static
Definition at line 72 of file ascii.c.
 {
     char num[16];
     int l;
     if (width < 1)
         return;
     // draw number string
     if (width > 5)
         width = 5;
     l = Q_scnprintf(num, sizeof(num), "%d", value);
     if (l > width)
         l = width;
     x += width - l;
     TH_DrawString(dst, x, y, num, l);
 }
Referenced by TH_DrawLayoutString().
TH_DrawString()
static void TH_DrawString (char * dst, int x, int y, char * src, size_t len) static
Definition at line 32 of file ascii.c.
 {
     int c;
     if (x + len > TH_WIDTH) {
         len = TH_WIDTH - x;
     }
     dst += y * (TH_WIDTH + 1) + x;
     while (len--) {
         c = *src++;
         c &= 127;
         switch (c) {
         case 13: c = '>'; break;
         case 16: c = '['; break;
         case 17: c = ']'; break;
         case 29: c = '<'; break;
         case 30: c = '='; break;
         case 31: c = '>'; break;
         default:
             if (c < 32) {
                 c = 32;
             }
             break;
         }
         *dst++ = c;
     }
 }
Referenced by TH_DrawCenterString(), TH_DrawLayoutString(), and TH_DrawNumber().