Quake II RTX doxygen: C:/entry/dev/Q2RTX/src/client/ui/ui.c File Reference
ui.c File Reference
#include "ui.h"
#include "client/input.h"
#include "../client.h"
#include "common/prompt.h"
Functions
LIST_DECL (ui_menus)
void UI_PushMenu (menuFrameWork_t *menu)
static void UI_Resize (void)
void UI_ForceMenuOff (void)
void UI_PopMenu (void)
qboolean UI_IsTransparent (void)
menuFrameWork_t * UI_FindMenu (const char *name)
void UI_OpenMenu (uiMenu_t type)
void * UI_FormatColumns (int extrasize,...)
char * UI_GetColumn (char *s, int n)
qboolean UI_CursorInRect (vrect_t *rect)
void UI_DrawString (int x, int y, int flags, const char *string)
void UI_DrawChar (int x, int y, int flags, int ch)
void UI_StringDimensions (vrect_t *rc, int flags, const char *string)
void UI_DrawRect8 (const vrect_t *rc, int border, int c)
qboolean UI_DoHitTest (void)
void UI_MouseEvent (int x, int y)
void UI_Draw (int realtime)
void UI_StartSound (menuSound_t sound)
void UI_KeyEvent (int key, qboolean down)
void UI_CharEvent (int key)
static void UI_Menu_g (genctx_t *ctx)
static void UI_PushMenu_c (genctx_t *ctx, int argnum)
static void UI_PushMenu_f (void)
static void UI_PopMenu_f (void)
static void ui_scale_changed (cvar_t *self)
void UI_ModeChanged (void)
static void UI_FreeMenus (void)
void UI_Init (void)
void UI_Shutdown (void)
Variables
uiStatic_t uis
cvar_t * ui_debug
static cvar_t * ui_open
static cvar_t * ui_scale
static const cmdreg_t c_ui []
Function Documentation
LIST_DECL()
LIST_DECL (ui_menus)
UI_CharEvent()
void UI_CharEvent (int key)
Definition at line 528 of file ui.c.
 {
     menuCommon_t *item;
     menuSound_t sound;
     if (!uis.activeMenu) {
         return;
     }
     if ((item = Menu_ItemAtCursor(uis.activeMenu)) == NULL ||
         (sound = Menu_CharEvent(item, key)) == QMS_NOTHANDLED) {
         return;
     }
     UI_StartSound(sound);
 }
Referenced by Key_Event().
UI_CursorInRect()
qboolean UI_CursorInRect (vrect_t * rect)
Definition at line 297 of file ui.c.
 {
     if (uis.mouseCoords[0] < rect->x) {
         return qfalse;
     }
     if (uis.mouseCoords[0] >= rect->x + rect->width) {
         return qfalse;
     }
     if (uis.mouseCoords[1] < rect->y) {
         return qfalse;
     }
     if (uis.mouseCoords[1] >= rect->y + rect->height) {
         return qfalse;
     }
     return qtrue;
 }
Referenced by Menu_HitTest(), MenuList_Click(), and Slider_Click().
UI_DoHitTest()
qboolean UI_DoHitTest (void)
Definition at line 368 of file ui.c.
 {
     menuCommon_t *item;
     if (!uis.activeMenu) {
         return qfalse;
     }
     if (uis.mouseTracker) {
         item = uis.mouseTracker;
     } else {
         if (!(item = Menu_HitTest(uis.activeMenu))) {
             return qfalse;
         }
     }
     if (!UI_IsItemSelectable(item)) {
         return qfalse;
     }
     Menu_MouseMove(item);
     if (item->flags & QMF_HASFOCUS) {
         return qfalse;
     }
     Menu_SetFocus(item);
     return qtrue;
 }
Referenced by UI_MouseEvent(), UI_PopMenu(), and UI_PushMenu().
UI_Draw()
void UI_Draw (int realtime)
Definition at line 420 of file ui.c.
 {
     int i;
     uis.realtime = realtime;
     if (!(Key_GetDest() & KEY_MENU)) {
         return;
     }
     if (!uis.activeMenu) {
         return;
     }
     R_ClearColor();
     R_SetScale(uis.scale);
     if (1) {
         // draw top menu
         if (uis.activeMenu->draw) {
             uis.activeMenu->draw(uis.activeMenu);
         } else {
             Menu_Draw(uis.activeMenu);
         }
     } else {
         // draw all layers
         for (i = 0; i < uis.menuDepth; i++) {
             if (uis.layers[i]->draw) {
                 uis.layers[i]->draw(uis.layers[i]);
             } else {
                 Menu_Draw(uis.layers[i]);
             }
         }
     }
     // draw custom cursor in fullscreen mode
     if (r_config.flags & QVF_FULLSCREEN) {
         R_DrawPic(uis.mouseCoords[0] - uis.cursorWidth / 2,
                   uis.mouseCoords[1] - uis.cursorHeight / 2, uis.cursorHandle);
     }
     if (ui_debug->integer) {
         UI_DrawString(uis.width - 4, 4, UI_RIGHT,
                       va("%3i %3i", uis.mouseCoords[0], uis.mouseCoords[1]));
     }
     // delay playing the enter sound until after the
     // menu has been drawn, to avoid delay while
     // caching images
     if (uis.entersound) {
         uis.entersound = qfalse;
         S_StartLocalSound("misc/menu1.wav");
     }
     R_ClearColor();
     R_SetScale(1.0f);
 }
Referenced by SCR_UpdateScreen().
UI_DrawChar()
void UI_DrawChar (int x, int y, int flags, int ch)
Definition at line 325 of file ui.c.
 {
     R_DrawChar(x, y, flags, ch, uis.fontHandle);
 }
Referenced by Action_Draw(), Keybind_Draw(), Slider_Draw(), and SpinControl_Draw().
UI_DrawRect8()
void UI_DrawRect8 (const vrect_t * rc, int border, int c)
Definition at line 342 of file ui.c.
 {
     R_DrawFill8(rc->x, rc->y, border, rc->height, c);   // left
     R_DrawFill8(rc->x + rc->width - border, rc->y, border, rc->height, c);   // right
     R_DrawFill8(rc->x + border, rc->y, rc->width - border * 2, border, c);   // top
     R_DrawFill8(rc->x + border, rc->y + rc->height - border, rc->width - border * 2, border, c);   // bottom
 }
Referenced by Menu_Draw().
UI_DrawString()
void UI_DrawString (int x, int y, int flags, const char * string)
Definition at line 314 of file ui.c.
 {
     if ((flags & UI_CENTER) == UI_CENTER) {
         x -= strlen(string) * CHAR_WIDTH / 2;
     } else if (flags & UI_RIGHT) {
         x -= strlen(string) * CHAR_WIDTH;
     }
     R_DrawString(x, y, flags, MAX_STRING_CHARS, string, uis.fontHandle);
 }
Referenced by Action_Draw(), Draw(), DrawStatus(), Field_Draw(), Keybind_Draw(), Menu_Draw(), MenuList_DrawString(), Separator_Draw(), Slider_Draw(), SpinControl_Draw(), Static_Draw(), and UI_Draw().
UI_FindMenu()
menuFrameWork_t* UI_FindMenu (const char * name)
Definition at line 190 of file ui.c.
 {
     menuFrameWork_t *menu;
     LIST_FOR_EACH(menuFrameWork_t, menu, &ui_menus, entry) {
         if (!strcmp(menu->name, name)) {
             return menu;
         }
     }
     return NULL;
 }
Referenced by Parse_File(), UI_OpenMenu(), and UI_PushMenu_f().
UI_ForceMenuOff()
void UI_ForceMenuOff (void)
Definition at line 119 of file ui.c.
 {
     menuFrameWork_t *menu;
     int i;
     for (i = 0; i < uis.menuDepth; i++) {
         menu = uis.layers[i];
         if (menu->pop) {
             menu->pop(menu);
         }
     }
     Key_SetDest(Key_GetDest() & ~KEY_MENU);
     uis.menuDepth = 0;
     uis.activeMenu = NULL;
     uis.mouseTracker = NULL;
     uis.transparent = qfalse;
 }
Referenced by UI_OpenMenu(), UI_PopMenu(), and UI_Shutdown().
UI_FormatColumns()
void* UI_FormatColumns (int extrasize, ...)
Definition at line 251 of file ui.c.
 {
     va_list argptr;
     char *buffer, *p;
     int i, j;
     size_t total = 0;
     char *strings[MAX_COLUMNS];
     size_t lengths[MAX_COLUMNS];
     va_start(argptr, extrasize);
     for (i = 0; i < MAX_COLUMNS; i++) {
         if ((p = va_arg(argptr, char *)) == NULL) {
             break;
         }
         strings[i] = p;
         total += lengths[i] = strlen(p) + 1;
     }
     va_end(argptr);
     buffer = UI_Malloc(extrasize + total + 1);
     p = buffer + extrasize;
     for (j = 0; j < i; j++) {
         memcpy(p, strings[j], lengths[j]);
         p += lengths[j];
     }
     *p = 0;
     return buffer;
 }
Referenced by AddServer(), BuildDir(), BuildName(), PingSelected(), UI_ErrorEvent(), and UI_StatusEvent().
UI_FreeMenus()
static void UI_FreeMenus (void) static
Definition at line 609 of file ui.c.
 {
     menuFrameWork_t *menu, *next;
     LIST_FOR_EACH_SAFE(menuFrameWork_t, menu, next, &ui_menus, entry) {
         if (menu->free) {
             menu->free(menu);
         }
     }
     List_Init(&ui_menus);
 }
Referenced by UI_Shutdown().
UI_GetColumn()
char* UI_GetColumn (char * s, int n)
Definition at line 281 of file ui.c.
 {
     int i;
     for (i = 0; i < n && *s; i++) {
         s += strlen(s) + 1;
     }
     return s;
 }
Referenced by MenuList_Key(), namecmp(), pingcmp(), and WriteCache().
UI_Init()
void UI_Init (void)
Definition at line 627 of file ui.c.
 {
     char buffer[MAX_QPATH];
     int i;
     Cmd_Register(c_ui);
     ui_debug = Cvar_Get("ui_debug", "0", 0);
     ui_open = Cvar_Get("ui_open", "1", 0);
     UI_ModeChanged();
     uis.fontHandle = R_RegisterFont("conchars");
     uis.cursorHandle = R_RegisterPic("ch1");
     R_GetPicSize(&uis.cursorWidth, &uis.cursorHeight, uis.cursorHandle);
     for (i = 0; i < NUM_CURSOR_FRAMES; i++) {
         Q_snprintf(buffer, sizeof(buffer), "m_cursor%d", i);
         uis.bitmapCursors[i] = R_RegisterPic(buffer);
     }
     uis.color.background.u32    = MakeColor(0,   0,   0, 255);
     uis.color.normal.u32        = MakeColor(15, 128, 235, 100);
     uis.color.active.u32        = MakeColor(15, 128, 235, 100);
     uis.color.selection.u32     = MakeColor(15, 128, 235, 100);
     uis.color.disabled.u32      = MakeColor(127, 127, 127, 255);
     strcpy(uis.weaponModel, "w_railgun.md2");
     // load custom menus
     UI_LoadScript();
     // load built-in menus
     M_Menu_PlayerConfig();
     M_Menu_Servers();
     M_Menu_Demos();
     Com_DPrintf("Registered %d menus.\n", List_Count(&ui_menus));
     uis.initialized = qtrue;
 }
Referenced by CL_InitRefresh(), CL_RestartFilesystem(), and CL_RestartRefresh().
UI_IsTransparent()
qboolean UI_IsTransparent (void)
Definition at line 177 of file ui.c.
 {
     if (!(Key_GetDest() & KEY_MENU)) {
         return qtrue;
     }
     if (!uis.activeMenu) {
         return qtrue;
     }
     return uis.activeMenu->transparent;
 }
Referenced by SCR_DrawActive().
UI_KeyEvent()
void UI_KeyEvent (int key, qboolean down)
Definition at line 503 of file ui.c.
 {
     menuSound_t sound;
     if (!uis.activeMenu) {
         return;
     }
     if (!down) {
         if (key == K_MOUSE1) {
             uis.mouseTracker = NULL;
         }
         return;
     }
     sound = Menu_Keydown(uis.activeMenu, key);
     UI_StartSound(sound);
 }
Referenced by Key_Event().
UI_Menu_g()
static void UI_Menu_g (genctx_t * ctx) static
Definition at line 545 of file ui.c.
 {
     menuFrameWork_t *menu;
     LIST_FOR_EACH(menuFrameWork_t, menu, &ui_menus, entry) {
         if (!Prompt_AddMatch(ctx, menu->name)) {
             break;
         }
     }
 }
Referenced by UI_PushMenu_c().
UI_ModeChanged()
void UI_ModeChanged (void)
Definition at line 602 of file ui.c.
 {
     ui_scale = Cvar_Get("ui_scale", "2", 0);
     ui_scale->changed = ui_scale_changed;
     UI_Resize();
 }
Referenced by SCR_ModeChanged(), and UI_Init().
UI_MouseEvent()
void UI_MouseEvent (int x, int y)
Definition at line 404 of file ui.c.
 {
     clamp(x, 0, r_config.width - 1);
     clamp(y, 0, r_config.height - 1);
     uis.mouseCoords[0] = Q_rint(x * uis.scale);
     uis.mouseCoords[1] = Q_rint(y * uis.scale);
     UI_DoHitTest();
 }
Referenced by Win_MainWndProc().
UI_OpenMenu()
void UI_OpenMenu (uiMenu_t type)
Definition at line 208 of file ui.c.
 {
     menuFrameWork_t *menu = NULL;
     if (!uis.initialized) {
         return;
     }
     // close any existing menus
     UI_ForceMenuOff();
     switch (type) {
     case UIMENU_DEFAULT:
         if (ui_open->integer) {
             menu = UI_FindMenu("main");
         }
         break;
     case UIMENU_MAIN:
         menu = UI_FindMenu("main");
         break;
     case UIMENU_GAME:
         menu = UI_FindMenu("game");
         if (!menu) {
             menu = UI_FindMenu("main");
         }
         break;
     case UIMENU_NONE:
         break;
     default:
         Com_Error(ERR_FATAL, "UI_OpenMenu: bad menu");
         break;
     }
     UI_PushMenu(menu);
 }
Referenced by CL_CheckForResend(), CL_Disconnect(), CL_Init(), CL_RestartFilesystem(), CL_RestartRefresh(), and Key_Event().
UI_PopMenu()
void UI_PopMenu (void)
Definition at line 143 of file ui.c.
 {
     menuFrameWork_t *menu;
     if (uis.menuDepth < 1)
         Com_Error(ERR_FATAL, "UI_PopMenu: depth < 1");
     menu = uis.layers[--uis.menuDepth];
     if (menu->pop) {
         menu->pop(menu);
     }
     if (!uis.menuDepth) {
         UI_ForceMenuOff();
         // Save the config file if the user closes the menu while in-game
         if (cls.state >= ca_active) {
             CL_WriteConfig();
         }
         return;
     }
     uis.activeMenu = uis.layers[uis.menuDepth - 1];
     uis.mouseTracker = NULL;
     UI_DoHitTest();
 }
Referenced by Menu_DefaultKey(), UI_PopMenu_f(), and UI_PushMenu().
UI_PopMenu_f()
static void UI_PopMenu_f (void) static
Definition at line 581 of file ui.c.
 {
     if (uis.activeMenu) {
         UI_PopMenu();
     }
 }
UI_PushMenu()
void UI_PushMenu (menuFrameWork_t * menu)
Definition at line 39 of file ui.c.
 {
     int i, j;
     if (!menu) {
         return;
     }
     // if this menu is already present, drop back to that level
     // to avoid stacking menus by hotkeys
     for (i = 0; i < uis.menuDepth; i++) {
         if (uis.layers[i] == menu) {
             break;
         }
     }
     if (i == uis.menuDepth) {
         if (uis.menuDepth >= MAX_MENU_DEPTH) {
             Com_EPrintf("UI_PushMenu: MAX_MENU_DEPTH exceeded\n");
             return;
         }
         uis.layers[uis.menuDepth++] = menu;
     } else {
         for (j = i; j < uis.menuDepth; j++) {
             UI_PopMenu();
         }
         uis.menuDepth = i + 1;
     }
     if (menu->push && !menu->push(menu)) {
         uis.menuDepth--;
         return;
     }
     Menu_Init(menu);
     Key_SetDest((Key_GetDest() & ~KEY_CONSOLE) | KEY_MENU);
     Con_Close(qtrue);
     if (!uis.activeMenu) {
         // opening menu moves cursor to the nice location
         IN_WarpMouse(menu->mins[0] / uis.scale, menu->mins[1] / uis.scale);
         uis.mouseCoords[0] = menu->mins[0];
         uis.mouseCoords[1] = menu->mins[1];
         uis.entersound = qtrue;
     }
     uis.activeMenu = menu;
     UI_DoHitTest();
     if (menu->expose) {
         menu->expose(menu);
     }
 }
Referenced by UI_OpenMenu(), and UI_PushMenu_f().
UI_PushMenu_c()
static void UI_PushMenu_c (genctx_t * ctx, int argnum) static
Definition at line 556 of file ui.c.
 {
     if (argnum == 1) {
         UI_Menu_g(ctx);
     }
 }
UI_PushMenu_f()
static void UI_PushMenu_f (void) static
Definition at line 563 of file ui.c.
 {
     menuFrameWork_t *menu;
     char *s;
     if (Cmd_Argc() < 2) {
         Com_Printf("Usage: %s <menu>\n", Cmd_Argv(0));
         return;
     }
     s = Cmd_Argv(1);
     menu = UI_FindMenu(s);
     if (menu) {
         UI_PushMenu(menu);
     } else {
         Com_Printf("No such menu: %s\n", s);
     }
 }
UI_Resize()
static void UI_Resize (void) static
Definition at line 98 of file ui.c.
 {
     int i;
     uis.scale = R_ClampScale(ui_scale);
     uis.width = r_config.width * uis.scale;
     uis.height = r_config.height * uis.scale;
     for (i = 0; i < uis.menuDepth; i++) {
         Menu_Init(uis.layers[i]);
     }
     //CL_WarpMouse(0, 0);
 }
Referenced by UI_ModeChanged(), and ui_scale_changed().
ui_scale_changed()
static void ui_scale_changed (cvar_t * self) static
Definition at line 597 of file ui.c.
 {
     UI_Resize();
 }
Referenced by UI_ModeChanged().
UI_Shutdown()
void UI_Shutdown (void)
Definition at line 674 of file ui.c.
 {
     if (!uis.initialized) {
         return;
     }
     UI_ForceMenuOff();
     ui_scale->changed = NULL;
     PlayerModel_Free();
     UI_FreeMenus();
     Cmd_Deregister(c_ui);
     memset(&uis, 0, sizeof(uis));
     Z_LeakTest(TAG_UI);
 }
Referenced by CL_RestartFilesystem(), CL_RestartRefresh(), and CL_ShutdownRefresh().
UI_StartSound()
void UI_StartSound (menuSound_t sound)
Definition at line 478 of file ui.c.
 {
     switch (sound) {
     case QMS_IN:
         S_StartLocalSound("misc/menu1.wav");
         break;
     case QMS_MOVE:
         S_StartLocalSound("misc/menu2.wav");
         break;
     case QMS_OUT:
         S_StartLocalSound("misc/menu3.wav");
         break;
     case QMS_BEEP:
         S_StartLocalSound("misc/talk1.wav");
         break;
     default:
         break;
     }
 }
Referenced by keybind_cb(), UI_CharEvent(), and UI_KeyEvent().
UI_StringDimensions()
void UI_StringDimensions (vrect_t * rc, int flags, const char * string)
Definition at line 330 of file ui.c.
 {
     rc->height = CHAR_HEIGHT;
     rc->width = CHAR_WIDTH * strlen(string);
     if ((flags & UI_CENTER) == UI_CENTER) {
         rc->x -= rc->width / 2;
     } else if (flags & UI_RIGHT) {
         rc->x -= rc->width;
     }
 }
Referenced by Action_Init(), Field_Init(), Keybind_Init(), Savegame_Push(), SpinControl_Init(), and Static_Init().
Variable Documentation
c_ui
const cmdreg_t c_ui[] static
Initial value:
= {
    { "forcemenuoff", UI_ForceMenuOff },
    { "pushmenu", UI_PushMenu_f, UI_PushMenu_c },
    { "popmenu", UI_PopMenu_f },
    { NULL, NULL }
}
Definition at line 589 of file ui.c.
Referenced by UI_Init(), and UI_Shutdown().
ui_debug
cvar_t* ui_debug
Definition at line 28 of file ui.c.
Referenced by Menu_Draw(), UI_Draw(), and UI_Init().
ui_open
cvar_t* ui_open static
Definition at line 29 of file ui.c.
Referenced by UI_Init(), and UI_OpenMenu().
ui_scale
cvar_t* ui_scale static
Definition at line 30 of file ui.c.
Referenced by UI_ModeChanged(), UI_Resize(), and UI_Shutdown().
uis
uiStatic_t uis
Definition at line 24 of file ui.c.
Referenced by Action_Draw(), Bitmap_Draw(), Change(), ColorForStatus(), Draw(), DrawStatus(), Field_Draw(), Keybind_Draw(), M_Menu_Demos(), M_Menu_PlayerConfig(), M_Menu_Servers(), Menu_Draw(), Menu_DrawStatus(), Menu_Init(), Menu_Size(), MenuList_Click(), MenuList_Draw(), MenuList_Key(), MenuList_MouseMove(), Parse_Color(), Parse_File(), PlayerModel_Free(), PlayerModel_Load(), Pop(), Push(), R_RenderFrame_RTX(), ReloadMedia(), RunFrame(), Size(), SizeCompact(), SizeFull(), Slider_Click(), Slider_Draw(), Slider_MouseMove(), SpinControl_Draw(), UI_CharEvent(), UI_CursorInRect(), UI_DoHitTest(), UI_Draw(), UI_DrawChar(), UI_DrawString(), UI_ForceMenuOff(), UI_Init(), UI_IsTransparent(), UI_KeyEvent(), UI_MouseEvent(), UI_OpenMenu(), UI_PopMenu(), UI_PopMenu_f(), UI_PushMenu(), UI_Resize(), UI_Shutdown(), and UpdateSelection().