Quake II RTX doxygen: C:/entry/dev/Q2RTX/src/client/view.c File Reference
view.c File Reference
#include "client.h"
Functions
static void V_ClearScene (void)
void V_AddEntity (entity_t *ent)
void V_AddParticle (particle_t *p)
void CL_UpdateBlendSetting (void)
static void V_Gun_Next_f (void)
static void V_Gun_Prev_f (void)
static void V_Gun_Model_f (void)
static int entitycmpfnc (const void *_a, const void *_b)
static void V_SetLightLevel (void)
float V_CalcFov (float fov_x, float width, float height)
void V_RenderView (void)
static void V_Viewpos_f (void)
static void cl_add_blend_changed (cvar_t *self)
void V_Init (void)
void V_Shutdown (void)
Variables
int gun_frame
qhandle_t gun_model
static cvar_t * cl_add_particles
static cvar_t * cl_add_entities
static cvar_t * cl_add_blend
static cvar_t * cl_adjustfov
int r_numentities
entity_t r_entities [MAX_ENTITIES]
int r_numparticles
particle_t r_particles [MAX_PARTICLES]
static const cmdreg_t v_cmds []
Function Documentation
cl_add_blend_changed()
static void cl_add_blend_changed (cvar_t * self) static
Definition at line 523 of file view.c.
 {
     CL_UpdateBlendSetting();
 }
Referenced by V_Init().
CL_UpdateBlendSetting()
void CL_UpdateBlendSetting (void)
Definition at line 292 of file view.c.
 {
     if (cls.state < ca_connected) {
         return;
     }
     if (cls.serverProtocol < PROTOCOL_VERSION_R1Q2) {
         return;
     }
     MSG_WriteByte(clc_setting);
     MSG_WriteShort(CLS_NOBLEND);
     MSG_WriteShort(!cl_add_blend->integer);
     MSG_FlushTo(&cls.netchan->message);
 }
Referenced by cl_add_blend_changed(), and CL_Begin().
entitycmpfnc()
static int entitycmpfnc (const void * _a, const void * _b) static
Definition at line 338 of file view.c.
 {
     const entity_t *a = (const entity_t *)_a;
     const entity_t *b = (const entity_t *)_b;
     // all other models are sorted by model then skin
     if (a->model == b->model)
         return a->skin - b->skin;
     else
         return a->model - b->model;
 }
Referenced by V_RenderView().
V_AddEntity()
void V_AddEntity (entity_t * ent)
Definition at line 91 of file view.c.
 {
     if (r_numentities >= MAX_ENTITIES)
         return;
     r_entities[r_numentities++] = *ent;
 }
Referenced by CL_AddBeams(), CL_AddExplosions(), CL_AddLasers(), CL_AddPacketEntities(), CL_AddPlayerBeams(), CL_AddViewWeapon(), and LOC_AddLocationsToScene().
V_AddParticle()
void V_AddParticle (particle_t * p)
Definition at line 106 of file view.c.
 {
     if (r_numparticles >= MAX_PARTICLES)
         return;
     r_particles[r_numparticles++] = *p;
 }
V_CalcFov()
float V_CalcFov (float fov_x, float width, float height)
Definition at line 379 of file view.c.
 {
     float    a;
     float    x;
     if (fov_x < 1 || fov_x > 179)
         Com_Error(ERR_DROP, "%s: bad fov: %f", __func__, fov_x);
     x = width / tan(fov_x / 360 * M_PI);
     a = atan(height / x);
     a = a * 360 / M_PI;
     return a;
 }
Referenced by CL_CalcViewValues(), m_autosens_changed(), Size(), and V_RenderView().
V_ClearScene()
static void V_ClearScene (void) static
Definition at line 75 of file view.c.
 {
 #if USE_DLIGHTS
     r_numdlights = 0;
 #endif
     r_numentities = 0;
     r_numparticles = 0;
 }
Referenced by V_RenderView().
V_Gun_Model_f()
static void V_Gun_Model_f (void) static
Definition at line 324 of file view.c.
 {
     char    name[MAX_QPATH];
     if (Cmd_Argc() != 2) {
         gun_model = 0;
         return;
     }
     Q_concat(name, sizeof(name), "models/", Cmd_Argv(1), "/tris.md2", NULL);
     gun_model = R_RegisterModel(name);
 }
V_Gun_Next_f()
static void V_Gun_Next_f (void) static
Definition at line 310 of file view.c.
 {
     gun_frame++;
     Com_Printf("frame %i\n", gun_frame);
 }
V_Gun_Prev_f()
static void V_Gun_Prev_f (void) static
Definition at line 316 of file view.c.
 {
     gun_frame--;
     if (gun_frame < 0)
         gun_frame = 0;
     Com_Printf("frame %i\n", gun_frame);
 }
V_Init()
void V_Init (void)
Definition at line 533 of file view.c.
 {
     Cmd_Register(v_cmds);
 #ifdef _DEBUG
     cl_testblend = Cvar_Get("cl_testblend", "0", 0);
     cl_testparticles = Cvar_Get("cl_testparticles", "0", 0);
     cl_testentities = Cvar_Get("cl_testentities", "0", 0);
 #if USE_DLIGHTS
     cl_testlights = Cvar_Get("cl_testlights", "0", CVAR_CHEAT);
 #endif
     cl_stats = Cvar_Get("cl_stats", "0", 0);
 #endif
 #if USE_DLIGHTS
     cl_add_lights = Cvar_Get("cl_lights", "1", 0);
     cl_show_lights = Cvar_Get("cl_show_lights", "0", 0);
 #endif
     cl_add_particles = Cvar_Get("cl_particles", "1", 0);
     cl_add_entities = Cvar_Get("cl_entities", "1", 0);
     cl_add_blend = Cvar_Get("cl_blend", "1", 0);
     cl_add_blend->changed = cl_add_blend_changed;
     cl_adjustfov = Cvar_Get("cl_adjustfov", "1", 0);
 }
Referenced by CL_InitRefresh().
V_RenderView()
void V_RenderView (void)
Definition at line 402 of file view.c.
 {
     // an invalid frame will just use the exact previous refdef
     // we can't use the old frame if the video mode has changed, though...
     if (cl.frame.valid) {
         V_ClearScene();
         // build a refresh entity list and calc cl.sim*
         // this also calls CL_CalcViewValues which loads
         // v_forward, etc.
         CL_AddEntities();
 #ifdef _DEBUG
         if (cl_testparticles->integer)
             V_TestParticles();
         if (cl_testentities->integer)
             V_TestEntities();
 #if USE_DLIGHTS
         if (cl_testlights->integer)
             V_TestLights();
 #endif
         if (cl_testblend->integer) {
             cl.refdef.blend[0] = 1;
             cl.refdef.blend[1] = 0.5;
             cl.refdef.blend[2] = 0.25;
             cl.refdef.blend[3] = 0.5;
         }
 #endif
         // never let it sit exactly on a node line, because a water plane can
         // dissapear when viewed with the eye exactly on it.
         // the server protocol only specifies to 1/8 pixel, so add 1/16 in each axis
         cl.refdef.vieworg[0] += 1.0 / 16;
         cl.refdef.vieworg[1] += 1.0 / 16;
         cl.refdef.vieworg[2] += 1.0 / 16;
         cl.refdef.x = scr_vrect.x;
         cl.refdef.y = scr_vrect.y;
         cl.refdef.width = scr_vrect.width;
         cl.refdef.height = scr_vrect.height;
         // adjust for non-4/3 screens
         if (cl_adjustfov->integer) {
             cl.refdef.fov_y = cl.fov_y;
             cl.refdef.fov_x = V_CalcFov(cl.refdef.fov_y, cl.refdef.height, cl.refdef.width);
         } else {
             cl.refdef.fov_x = cl.fov_x;
             cl.refdef.fov_y = V_CalcFov(cl.refdef.fov_x, cl.refdef.width, cl.refdef.height);
         }
         cl.refdef.time = cl.time * 0.001;
         if (cl.frame.areabytes) {
             cl.refdef.areabits = cl.frame.areabits;
         } else {
             cl.refdef.areabits = NULL;
         }
         if (!cl_add_entities->integer)
             r_numentities = 0;
         if (!cl_add_particles->integer)
             r_numparticles = 0;
 #if USE_DLIGHTS
         if (!cl_add_lights->integer)
             r_numdlights = 0;
 #endif
         if (!cl_add_blend->integer)
             Vector4Clear(cl.refdef.blend);
         cl.refdef.num_entities = r_numentities;
         cl.refdef.entities = r_entities;
         cl.refdef.num_particles = r_numparticles;
         cl.refdef.particles = r_particles;
 #if USE_DLIGHTS
         cl.refdef.num_dlights = r_numdlights;
         cl.refdef.dlights = r_dlights;
 #endif
 #if USE_LIGHTSTYLES
         cl.refdef.lightstyles = r_lightstyles;
 #endif
         cl.refdef.rdflags = cl.frame.ps.rdflags;
         // sort entities for better cache locality
         qsort(cl.refdef.entities, cl.refdef.num_entities, sizeof(cl.refdef.entities[0]), entitycmpfnc);
     }
     R_RenderFrame(&cl.refdef);
 #ifdef _DEBUG
     if (cl_stats->integer)
 #if USE_DLIGHTS
         Com_Printf("ent:%i  lt:%i  part:%i\n", r_numentities, r_numdlights, r_numparticles);
 #else
         Com_Printf("ent:%i  part:%i\n", r_numentities, r_numparticles);
 #endif
 #endif
     V_SetLightLevel();
 }
Referenced by SCR_DrawActive().
V_SetLightLevel()
static void V_SetLightLevel (void) static
Definition at line 350 of file view.c.
 {
     vec3_t shadelight;
     // save off light value for server to look at (BIG HACK!)
     R_LightPoint(cl.refdef.vieworg, shadelight);
     // pick the greatest component, which should be the same
     // as the mono value returned by software
     if (shadelight[0] > shadelight[1]) {
         if (shadelight[0] > shadelight[2]) {
             cl.lightlevel = 150.0f * shadelight[0];
         } else {
             cl.lightlevel = 150.0f * shadelight[2];
         }
     } else {
         if (shadelight[1] > shadelight[2]) {
             cl.lightlevel = 150.0f * shadelight[1];
         } else {
             cl.lightlevel = 150.0f * shadelight[2];
         }
     }
 }
Referenced by V_RenderView().
V_Shutdown()
void V_Shutdown (void)
Definition at line 560 of file view.c.
 {
     Cmd_Deregister(v_cmds);
 }
Referenced by CL_ShutdownRefresh().
V_Viewpos_f()
static void V_Viewpos_f (void) static
Definition at line 508 of file view.c.
 {
     Com_Printf("(%i %i %i) : %i\n", (int)cl.refdef.vieworg[0],
                (int)cl.refdef.vieworg[1], (int)cl.refdef.vieworg[2],
                (int)cl.refdef.viewangles[YAW]);
 }
Variable Documentation
cl_add_blend
cvar_t* cl_add_blend static
Definition at line 38 of file view.c.
Referenced by CL_UpdateBlendSetting(), V_Init(), and V_RenderView().
cl_add_entities
cvar_t* cl_add_entities static
Definition at line 37 of file view.c.
Referenced by V_Init(), and V_RenderView().
cl_add_particles
cvar_t* cl_add_particles static
Definition at line 32 of file view.c.
Referenced by V_Init(), and V_RenderView().
cl_adjustfov
cvar_t* cl_adjustfov static
Definition at line 51 of file view.c.
Referenced by V_Init(), and V_RenderView().
gun_frame
int gun_frame
Definition at line 27 of file view.c.
Referenced by CL_AddViewWeapon(), V_Gun_Next_f(), and V_Gun_Prev_f().
gun_model
qhandle_t gun_model
Definition at line 28 of file view.c.
Referenced by CL_AddViewWeapon(), and V_Gun_Model_f().
r_entities
entity_t r_entities[MAX_ENTITIES]
Definition at line 59 of file view.c.
Referenced by V_AddEntity(), and V_RenderView().
r_numentities
int r_numentities
Definition at line 58 of file view.c.
Referenced by V_AddEntity(), V_ClearScene(), and V_RenderView().
r_numparticles
int r_numparticles
Definition at line 61 of file view.c.
Referenced by CL_AddParticles(), V_AddParticle(), V_ClearScene(), and V_RenderView().
r_particles
particle_t r_particles[MAX_PARTICLES]
Definition at line 62 of file view.c.
Referenced by CL_AddParticles(), V_AddParticle(), and V_RenderView().
v_cmds
const cmdreg_t v_cmds[] static
Initial value:
= {
    { "gun_next", V_Gun_Next_f },
    { "gun_prev", V_Gun_Prev_f },
    { "gun_model", V_Gun_Model_f },
    { "viewpos", V_Viewpos_f },
    { NULL }
}
Definition at line 515 of file view.c.
Referenced by V_Init(), and V_Shutdown().