Quake II RTX doxygen: C:/entry/dev/Q2RTX/src/windows/hunk.c File Reference
hunk.c File Reference
#include "shared/shared.h"
#include "system/hunk.h"
#include <windows.h>
Functions
void Hunk_Begin (memhunk_t *hunk, size_t maxsize)
void * Hunk_Alloc (memhunk_t *hunk, size_t size)
void Hunk_End (memhunk_t *hunk)
void Hunk_Free (memhunk_t *hunk)
Function Documentation
Hunk_Alloc()
void* Hunk_Alloc (memhunk_t * hunk, size_t size)
Definition at line 38 of file hunk.c.
 {
     void *buf;
     if (size > SIZE_MAX - 63)
         Com_Error(ERR_FATAL, "%s: size > SIZE_MAX", __func__);
     // round to cacheline
     size = (size + 63) & ~63;
     if (hunk->cursize > hunk->maxsize)
         Com_Error(ERR_FATAL, "%s: cursize > maxsize", __func__);
     if (size > hunk->maxsize - hunk->cursize)
         Com_Error(ERR_FATAL, "%s: couldn't allocate %"PRIz" bytes", __func__, size);
     hunk->cursize += size;
     // commit pages as needed
     buf = VirtualAlloc(hunk->base, hunk->cursize, MEM_COMMIT, PAGE_READWRITE);
     if (!buf)
         Com_Error(ERR_FATAL,
                   "VirtualAlloc commit %"PRIz" bytes failed with error %lu",
                   hunk->cursize, GetLastError());
     return (byte *)hunk->base + hunk->cursize - size;
 }
Referenced by GL_LoadWorld().
Hunk_Begin()
void Hunk_Begin (memhunk_t * hunk, size_t maxsize)
Definition at line 23 of file hunk.c.
 {
     if (maxsize > SIZE_MAX - 4095)
         Com_Error(ERR_FATAL, "%s: size > SIZE_MAX", __func__);
     // reserve a huge chunk of memory, but don't commit any yet
     hunk->cursize = 0;
     hunk->maxsize = (maxsize + 4095) & ~4095;
     hunk->base = VirtualAlloc(NULL, hunk->maxsize, MEM_RESERVE, PAGE_NOACCESS);
     if (!hunk->base)
         Com_Error(ERR_FATAL,
                   "VirtualAlloc reserve %"PRIz" bytes failed with error %lu",
                   hunk->maxsize, GetLastError());
 }
Referenced by BSP_Load(), GL_LoadWorld(), MOD_LoadMD2(), MOD_LoadMD2_GL(), MOD_LoadMD2_RTX(), and MOD_LoadSP2().
Hunk_End()
void Hunk_End (memhunk_t * hunk)
Definition at line 66 of file hunk.c.
 {
     if (hunk->cursize > hunk->maxsize)
         Com_Error(ERR_FATAL, "%s: cursize > maxsize", __func__);
     // for statistics
     hunk->mapped = (hunk->cursize + 4095) & ~4095;
 }
Referenced by BSP_Load(), GL_LoadWorld(), MOD_LoadMD2(), MOD_LoadMD2_GL(), MOD_LoadMD2_RTX(), and MOD_LoadSP2().
Hunk_Free()
void Hunk_Free (memhunk_t * hunk)
Definition at line 75 of file hunk.c.
 {
     if (hunk->base && !VirtualFree(hunk->base, 0, MEM_RELEASE))
         Com_Error(ERR_FATAL, "VirtualFree failed with error %lu", GetLastError());
     memset(hunk, 0, sizeof(*hunk));
 }
Referenced by BSP_Free(), BSP_Load(), GL_FreeWorld(), MOD_FreeAll(), MOD_FreeUnused(), MOD_LoadMD2(), MOD_LoadMD2_GL(), and MOD_LoadMD2_RTX().