Quake II RTX doxygen: C:/entry/dev/Q2RTX/src/common/utils.c File Reference
utils.c File Reference
#include "shared/shared.h"
#include "common/utils.h"
Functions
static qboolean match_raw (int c1, int c2, qboolean ignorecase)
static qboolean match_char (int c1, int c2, qboolean ignorecase)
static qboolean match_part (const char *filter, const char *string, size_t len, qboolean ignorecase)
static const char * match_filter (const char *filter, const char *string, size_t len, qboolean ignorecase)
qboolean Com_WildCmpEx (const char *filter, const char *string, int term, qboolean ignorecase)
color_index_t Com_ParseColor (const char *s, color_index_t last)
void Com_PlayerToEntityState (const player_state_t *ps, entity_state_t *es)
unsigned Com_HashString (const char *s, unsigned size)
unsigned Com_HashStringLen (const char *s, size_t len, unsigned size)
void Com_PageInMemory (void *buffer, size_t size)
size_t Com_FormatTime (char *buffer, size_t size, time_t t)
size_t Com_FormatTimeLong (char *buffer, size_t size, time_t t)
size_t Com_TimeDiff (char *buffer, size_t size, time_t *p, time_t now)
size_t Com_TimeDiffLong (char *buffer, size_t size, time_t *p, time_t now)
size_t Com_FormatSize (char *dest, size_t destsize, off_t bytes)
size_t Com_FormatSizeLong (char *dest, size_t destsize, off_t bytes)
Variables
const char *const colorNames [10]
int paged_total
Function Documentation
Com_FormatSize()
size_t Com_FormatSize (char * dest, size_t destsize, off_t bytes)
Definition at line 465 of file utils.c.
 {
     if (bytes >= 10000000) {
         return Q_scnprintf(dest, destsize, "%dM", (int)(bytes / 1000000));
     }
     if (bytes >= 1000000) {
         return Q_scnprintf(dest, destsize, "%.1fM", (float)bytes / 1000000);
     }
     if (bytes >= 1000) {
         return Q_scnprintf(dest, destsize, "%dK", (int)(bytes / 1000));
     }
     if (bytes >= 0) {
         return Q_scnprintf(dest, destsize, "%d", (int)bytes);
     }
     return Q_scnprintf(dest, destsize, "???");
 }
Referenced by BuildName(), and list_recordings().
Com_FormatSizeLong()
size_t Com_FormatSizeLong (char * dest, size_t destsize, off_t bytes)
Definition at line 482 of file utils.c.
 {
     if (bytes >= 10000000) {
         return Q_scnprintf(dest, destsize, "%d MB", (int)(bytes / 1000000));
     }
     if (bytes >= 1000000) {
         return Q_scnprintf(dest, destsize, "%.1f MB", (float)bytes / 1000000);
     }
     if (bytes >= 1000) {
         return Q_scnprintf(dest, destsize, "%d kB", (int)(bytes / 1000));
     }
     if (bytes >= 0) {
         return Q_scnprintf(dest, destsize, "%d byte%s",
                            (int)bytes, bytes == 1 ? "" : "s");
     }
     return Q_scnprintf(dest, destsize, "unknown size");
 }
Referenced by BuildList(), finish_download(), and format_demo_size().
Com_FormatTime()
size_t Com_FormatTime (char * buffer, size_t size, time_t t)
Definition at line 391 of file utils.c.
 {
     int     sec, min, hour, day;
     min = t / 60; sec = t % 60;
     hour = min / 60; min %= 60;
     day = hour / 24; hour %= 24;
     if (day) {
         return Q_scnprintf(buffer, size, "%d+%d:%02d.%02d", day, hour, min, sec);
     }
     if (hour) {
         return Q_scnprintf(buffer, size, "%d:%02d.%02d", hour, min, sec);
     }
     return Q_scnprintf(buffer, size, "%02d.%02d", min, sec);
 }
Referenced by Com_TimeDiff(), and NET_Stats_f().
Com_FormatTimeLong()
size_t Com_FormatTimeLong (char * buffer, size_t size, time_t t)
Definition at line 408 of file utils.c.
 {
     int     sec, min, hour, day;
     size_t  len;
     if (!t) {
         return Q_scnprintf(buffer, size, "0 secs");
     }
     min = t / 60; sec = t % 60;
     hour = min / 60; min %= 60;
     day = hour / 24; hour %= 24;
     len = 0;
     if (day) {
         len += Q_scnprintf(buffer + len, size - len,
                            "%d day%s%s", day, day == 1 ? "" : "s", (hour || min || sec) ? ", " : "");
     }
     if (hour) {
         len += Q_scnprintf(buffer + len, size - len,
                            "%d hour%s%s", hour, hour == 1 ? "" : "s", (min || sec) ? ", " : "");
     }
     if (min) {
         len += Q_scnprintf(buffer + len, size - len,
                            "%d min%s%s", min, min == 1 ? "" : "s", sec ? ", " : "");
     }
     if (sec) {
         len += Q_scnprintf(buffer + len, size - len,
                            "%d sec%s", sec, sec == 1 ? "" : "s");
     }
     return len;
 }
Referenced by AC_Retry(), Com_TimeDiffLong(), and gtv_drop().
Com_HashString()
unsigned Com_HashString (const char * s, unsigned size)
Definition at line 339 of file utils.c.
 {
     unsigned hash, c;
     hash = 0;
     while (*s) {
         c = *s++;
         hash = 127 * hash + c;
     }
     hash = (hash >> 20) ^(hash >> 10) ^ hash;
     return hash & (size - 1);
 }
Referenced by Cmd_AddMacro(), Cmd_AliasFind(), Cmd_AliasSet(), Cmd_Complete_f(), Cmd_Find(), Cmd_FindMacro(), Cmd_RegCommand(), Cvar_FindVar(), and Cvar_Get().
Com_HashStringLen()
unsigned Com_HashStringLen (const char * s, size_t len, unsigned size)
Definition at line 361 of file utils.c.
 {
     unsigned hash, c;
     hash = 0;
     while (*s && len--) {
         c = Q_tolower(*s++);
         hash = 127 * hash + c;
     }
     hash = (hash >> 20) ^(hash >> 10) ^ hash;
     return hash & (size - 1);
 }
Com_PageInMemory()
void Com_PageInMemory (void * buffer, size_t size)
Definition at line 383 of file utils.c.
 {
     int        i;
     for (i = size - 1; i > 0; i -= 4096)
         paged_total += ((byte *)buffer)[i];
 }
Referenced by BSP_Load(), IMG_FreeUnused(), MOD_FreeUnused(), and S_EndRegistration().
Com_ParseColor()
color_index_t Com_ParseColor (const char * s, color_index_t last)
Definition at line 204 of file utils.c.
 {
     color_index_t i;
     if (COM_IsUint(s)) {
         i = strtoul(s, NULL, 10);
         return i > last ? COLOR_NONE : i;
     }
     for (i = 0; i <= last; i++) {
         if (!strcmp(colorNames[i], s)) {
             return i;
         }
     }
     return COLOR_NONE;
 }
Referenced by Cmd_EchoEx_f(), and SCR_ParseColor().
Com_PlayerToEntityState()
void Com_PlayerToEntityState (const player_state_t * ps, entity_state_t * es)
Definition at line 269 of file utils.c.
 {
     vec_t pitch;
     VectorScale(ps->pmove.origin, 0.125f, es->origin);
     pitch = ps->viewangles[PITCH];
     if (pitch > 180) {
         pitch -= 360;
     }
     es->angles[PITCH] = pitch / 3;
     es->angles[YAW] = ps->viewangles[YAW];
     es->angles[ROLL] = 0;
 }
Referenced by CL_DeltaFrame(), entity_update(), and MVD_PlayerToEntityStates().
Com_TimeDiff()
size_t Com_TimeDiff (char * buffer, size_t size, time_t * p, time_t now)
Definition at line 443 of file utils.c.
 {
     time_t diff;
     if (*p > now) {
         *p = now;
     }
     diff = now - *p;
     return Com_FormatTime(buffer, size, diff);
 }
Referenced by Com_Uptime_m(), dump_time(), and SV_PrintMiscInfo().
Com_TimeDiffLong()
size_t Com_TimeDiffLong (char * buffer, size_t size, time_t * p, time_t now)
Definition at line 454 of file utils.c.
 {
     time_t diff;
     if (*p > now) {
         *p = now;
     }
     diff = now - *p;
     return Com_FormatTimeLong(buffer, size, diff);
 }
Referenced by Com_UptimeLong_m().
Com_WildCmpEx()
qboolean Com_WildCmpEx (const char * filter, const char * string, int term, qboolean ignorecase)
Definition at line 122 of file utils.c.
 {
     const char *sub;
     size_t len;
     qboolean match;
     while (*filter && *filter != term) {
         if (*filter == '*') {
             // skip consecutive wildcards
             do {
                 filter++;
             } while (*filter == '*');
             // scan out filter part to match
             for (sub = filter, len = 0; *filter && *filter != term && *filter != '*'; filter++, len++) {
                 // skip over escape character
                 if (*filter == '\\') {
                     filter++;
                     if (!*filter) {
                         break;
                     }
                 }
             }
             // wildcard at the end matches everything
             if (!len) {
                 return qtrue;
             }
             string = match_filter(sub, string, len, ignorecase);
             if (!string) {
                 return qfalse;
             }
         } else {
             // skip over escape character
             if (*filter == '\\') {
                 filter++;
                 if (!*filter) {
                     break;
                 }
                 match = match_raw(*filter, *string, ignorecase);
             } else {
                 match = match_char(*filter, *string, ignorecase);
             }
             // match single character
             if (!match) {
                 return qfalse;
             }
             filter++;
             string++;
         }
     }
     // match NUL at the end
     return !*string;
 }
Referenced by FS_WildCmp(), and MVD_AutoFollow_f().
match_char()
static qboolean match_char (int c1, int c2, qboolean ignorecase) static
Definition at line 52 of file utils.c.
 {
     if (c1 == '?') {
         return !!c2; // match any char except NUL
     }
     return match_raw(c1, c2, ignorecase);
 }
Referenced by Com_WildCmpEx(), and match_part().
match_filter()
static const char* match_filter (const char * filter, const char * string, size_t len, qboolean ignorecase) static
Definition at line 87 of file utils.c.
 {
     const char *ret = NULL;
     size_t remaining = strlen(string);
     while (remaining >= len) {
         if (match_part(filter, string, len, ignorecase)) {
             string += len;
             remaining -= len;
             ret = string;
             continue;
         }
         string++;
         remaining--;
     }
     return ret;
 }
Referenced by Com_WildCmpEx().
match_part()
static qboolean match_part (const char * filter, const char * string, size_t len, qboolean ignorecase) static
Definition at line 61 of file utils.c.
 {
     qboolean match;
     do {
         // skip over escape character
         if (*filter == '\\') {
             filter++;
             match = match_raw(*filter, *string, ignorecase);
         } else {
             match = match_char(*filter, *string, ignorecase);
         }
         if (!match) {
             return qfalse;
         }
         filter++;
         string++;
     } while (--len);
     return qtrue;
 }
Referenced by match_filter().
match_raw()
static qboolean match_raw (int c1, int c2, qboolean ignorecase) static
Definition at line 30 of file utils.c.
 {
     if (c1 != c2) {
         if (!ignorecase) {
             return qfalse;
         }
 #ifdef _WIN32
         // ugly hack for file listing
         c1 = c1 == '\\' ? '/' : Q_tolower(c1);
         c2 = c2 == '\\' ? '/' : Q_tolower(c2);
 #else
         c1 = Q_tolower(c1);
         c2 = Q_tolower(c2);
 #endif
         if (c1 != c2) {
             return qfalse;
         }
     }
     return qtrue;
 }
Referenced by Com_WildCmpEx(), match_char(), and match_part().
Variable Documentation
colorNames
const char* const colorNames[10]
Initial value:
= {
    "black", "red", "green", "yellow",
    "blue", "cyan", "magenta", "white",
    "alt", "none"
}
Definition at line 190 of file utils.c.
Referenced by Com_ParseColor(), and SCR_Color_g().
paged_total
int paged_total
Definition at line 381 of file utils.c.
Referenced by Com_PageInMemory().