Quake II RTX doxygen: C:/entry/dev/Q2RTX/src/common/field.c File Reference
field.c File Reference
#include "shared/shared.h"
#include "common/common.h"
#include "common/field.h"
#include "client/client.h"
#include "client/keys.h"
#include "client/video.h"
#include "refresh/refresh.h"
Functions
void IF_Init (inputField_t *field, size_t visibleChars, size_t maxChars)
void IF_Clear (inputField_t *field)
void IF_Replace (inputField_t *field, const char *text)
Function Documentation
IF_Clear()
void IF_Clear (inputField_t * field)
Definition at line 56 of file field.c.
 {
     memset(field->text, 0, sizeof(field->text));
     field->cursorPos = 0;
 }
Referenced by Con_ClearTyping(), Key_Message(), Prompt_Action(), and Prompt_Clear().
IF_Init()
void IF_Init (inputField_t * field, size_t visibleChars, size_t maxChars)
Definition at line 36 of file field.c.
 {
     memset(field, 0, sizeof(*field));
     if (maxChars >= sizeof(field->text)) {
         maxChars = sizeof(field->text) - 1;
     }
     if (visibleChars > maxChars) {
         visibleChars = maxChars;
     }
     field->maxChars = maxChars;
     field->visibleChars = visibleChars;
 }
Referenced by Con_Init(), Field_Push(), and Push().
IF_Replace()
void IF_Replace (inputField_t * field, const char * text)
Definition at line 67 of file field.c.
 {
     if (field->maxChars && text) {
         size_t len = Q_strlcpy(field->text, text, field->maxChars + 1);
         field->cursorPos = len >= field->maxChars ? field->maxChars - 1 : len;
     } else {
         field->text[0] = 0;
         field->cursorPos = 0;
     }
 }
Referenced by Field_Push(), Prompt_CompleteHistory(), Prompt_HistoryDown(), Prompt_HistoryUp(), Push(), and start_message_mode().