Quake II RTX doxygen: C:/entry/dev/Q2RTX/src/client/sound/mem.c File Reference
mem.c File Reference
#include "sound.h"
Macros
#define TAG_RIFF MakeRawLong('R', 'I', 'F', 'F')
#define TAG_WAVE MakeRawLong('W', 'A', 'V', 'E')
#define TAG_fmt MakeRawLong('f', 'm', 't', ' ')
#define TAG_cue MakeRawLong('c', 'u', 'e', ' ')
#define TAG_LIST MakeRawLong('L', 'I', 'S', 'T')
#define TAG_MARK MakeRawLong('M', 'A', 'R', 'K')
#define TAG_data MakeRawLong('d', 'a', 't', 'a')
Functions
static int GetLittleShort (void)
static int GetLittleLong (void)
static void FindNextChunk (uint32_t search)
static void FindChunk (uint32_t search)
static qboolean GetWavinfo (void)
sfxcache_t * S_LoadSound (sfx_t *s)
Variables
wavinfo_t s_info
static byte * data_p
static byte * iff_end
static byte * iff_data
static uint32_t iff_chunk_len
Macro Definition Documentation
TAG_cue
#define TAG_cue MakeRawLong('c', 'u', 'e', ' ')
Definition at line 163 of file mem.c.
TAG_data
#define TAG_data MakeRawLong('d', 'a', 't', 'a')
Definition at line 166 of file mem.c.
TAG_fmt
#define TAG_fmt MakeRawLong('f', 'm', 't', ' ')
Definition at line 162 of file mem.c.
TAG_LIST
#define TAG_LIST MakeRawLong('L', 'I', 'S', 'T')
Definition at line 164 of file mem.c.
TAG_MARK
#define TAG_MARK MakeRawLong('M', 'A', 'R', 'K')
Definition at line 165 of file mem.c.
TAG_RIFF
#define TAG_RIFF MakeRawLong('R', 'I', 'F', 'F')
Definition at line 160 of file mem.c.
TAG_WAVE
#define TAG_WAVE MakeRawLong('W', 'A', 'V', 'E')
Definition at line 161 of file mem.c.
Function Documentation
FindChunk()
static void FindChunk (uint32_t search) static
Definition at line 154 of file mem.c.
 {
     data_p = iff_data;
     FindNextChunk(search);
 }
Referenced by GetWavinfo().
FindNextChunk()
static void FindNextChunk (uint32_t search) static
Definition at line 131 of file mem.c.
 {
     uint32_t chunk, len;
     size_t remaining;
     while (data_p + 8 < iff_end) {
         chunk = RawLongMem(data_p); data_p += 4;
         len = LittleLongMem(data_p); data_p += 4;
         remaining = (size_t)(iff_end - data_p);
         if (len > remaining) {
             len = remaining;
         }
         if (chunk == search) {
             iff_chunk_len = len;
             return;
         }
         data_p += (len + 1) & ~1;
     }
     // didn't find the chunk
     data_p = NULL;
 }
Referenced by FindChunk(), and GetWavinfo().
GetLittleLong()
static int GetLittleLong (void) static
Definition at line 118 of file mem.c.
 {
     int val;
     if (data_p + 4 > iff_end) {
         return -1;
     }
     val = LittleLongMem(data_p);
     data_p += 4;
     return val;
 }
Referenced by GetWavinfo().
GetLittleShort()
static int GetLittleShort (void) static
Definition at line 105 of file mem.c.
 {
     int val;
     if (data_p + 2 > iff_end) {
         return -1;
     }
     val = LittleShortMem(data_p);
     data_p += 2;
     return val;
 }
Referenced by GetWavinfo().
GetWavinfo()
static qboolean GetWavinfo (void) static
Definition at line 168 of file mem.c.
 {
     int format;
     int samples, width;
     uint32_t chunk;
 // find "RIFF" chunk
     FindChunk(TAG_RIFF);
     if (!data_p) {
         Com_DPrintf("%s has missing/invalid RIFF chunk\n", s_info.name);
         return qfalse;
     }
     chunk = GetLittleLong();
     if (chunk != TAG_WAVE) {
         Com_DPrintf("%s has missing/invalid WAVE chunk\n", s_info.name);
         return qfalse;
     }
     iff_data = data_p;
 // get "fmt " chunk
     FindChunk(TAG_fmt);
     if (!data_p) {
         Com_DPrintf("%s has missing/invalid fmt chunk\n", s_info.name);
         return qfalse;
     }
     format = GetLittleShort();
     if (format != 1) {
         Com_DPrintf("%s has non-Microsoft PCM format\n", s_info.name);
         return qfalse;
     }
     format = GetLittleShort();
     if (format != 1) {
         Com_DPrintf("%s has bad number of channels\n", s_info.name);
         return qfalse;
     }
     s_info.rate = GetLittleLong();
     if (s_info.rate < 8000 || s_info.rate > 48000) {
         Com_DPrintf("%s has bad rate\n", s_info.name);
         return qfalse;
     }
     data_p += 4 + 2;
     width = GetLittleShort();
     switch (width) {
     case 8:
         s_info.width = 1;
         break;
     case 16:
         s_info.width = 2;
         break;
     default:
         Com_DPrintf("%s has bad width\n", s_info.name);
         return qfalse;
     }
 // get cue chunk
     FindChunk(TAG_cue);
     if (data_p) {
         data_p += 24;
         s_info.loopstart = GetLittleLong();
         if (s_info.loopstart < 0 || s_info.loopstart > INT_MAX) {
             Com_DPrintf("%s has bad loop start\n", s_info.name);
             return qfalse;
         }
         FindNextChunk(TAG_LIST);
         if (data_p) {
             data_p += 20;
             chunk = GetLittleLong();
             if (chunk == TAG_MARK) {
                 // this is not a proper parse, but it works with cooledit...
                 data_p += 16;
                 samples = GetLittleLong();    // samples in loop
                 if (samples < 0 || samples > INT_MAX - s_info.loopstart) {
                     Com_DPrintf("%s has bad loop length\n", s_info.name);
                     return qfalse;
                 }
                 s_info.samples = s_info.loopstart + samples;
             }
         }
     } else {
         s_info.loopstart = -1;
     }
 // find data chunk
     FindChunk(TAG_data);
     if (!data_p) {
         Com_DPrintf("%s has missing/invalid data chunk\n", s_info.name);
         return qfalse;
     }
     samples = iff_chunk_len / s_info.width;
     if (!samples) {
         Com_DPrintf("%s has zero length\n", s_info.name);
         return qfalse;
     }
     if (s_info.samples) {
         if (samples < s_info.samples) {
             Com_DPrintf("%s has bad loop length\n", s_info.name);
             return qfalse;
         }
     } else {
         s_info.samples = samples;
     }
     s_info.data = data_p;
     return qtrue;
 }
Referenced by S_LoadSound().
S_LoadSound()
sfxcache_t* S_LoadSound (sfx_t * s)
Definition at line 288 of file mem.c.
 {
     byte        *data;
     sfxcache_t  *sc;
     ssize_t     len;
     char        *name;
     if (s->name[0] == '*')
         return NULL;
 // see if still in memory
     sc = s->cache;
     if (sc)
         return sc;
 // don't retry after error
     if (s->error)
         return NULL;
 // load it in
     if (s->truename)
         name = s->truename;
     else
         name = s->name;
     len = FS_LoadFile(name, (void **)&data);
     if (!data) {
         s->error = len;
         return NULL;
     }
     memset(&s_info, 0, sizeof(s_info));
     s_info.name = name;
     iff_data = data;
     iff_end = data + len;
     if (!GetWavinfo()) {
         s->error = Q_ERR_INVALID_FORMAT;
         goto fail;
     }
 #if USE_OPENAL
     if (s_started == SS_OAL)
         sc = AL_UploadSfx(s);
 #endif
 #if USE_SNDDMA
     if (s_started == SS_DMA)
         sc = ResampleSfx(s);
 #endif
 fail:
     FS_FreeFile(data);
     return sc;
 }
Referenced by S_EndRegistration(), S_IssuePlaysound(), S_PaintChannels(), S_RegisterSexedSound(), S_RegisterSound(), and S_StartSound().
Variable Documentation
data_p
byte* data_p static
Definition at line 100 of file mem.c.
Referenced by AC_SimpleParse(), COM_Parse(), FindChunk(), FindNextChunk(), GetLittleLong(), GetLittleShort(), and GetWavinfo().
iff_chunk_len
uint32_t iff_chunk_len static
Definition at line 103 of file mem.c.
Referenced by FindNextChunk(), and GetWavinfo().
iff_data
byte* iff_data static
Definition at line 102 of file mem.c.
Referenced by FindChunk(), GetWavinfo(), and S_LoadSound().
iff_end
byte* iff_end static
Definition at line 101 of file mem.c.
Referenced by FindNextChunk(), GetLittleLong(), GetLittleShort(), and S_LoadSound().
s_info
wavinfo_t s_info
Definition at line 22 of file mem.c.
Referenced by AL_UploadSfx(), GetWavinfo(), and S_LoadSound().