Quake II RTX doxygen: C:/entry/dev/Q2RTX/src/refresh/sw/image.c File Reference
image.c File Reference
#include "sw.h"
Macros
#define NTX 256
Functions
void IMG_Unload (image_t *image)
static void R_LightScaleTexture (byte *in, int inwidth, int inheight)
void IMG_Load (image_t *image, byte *pic)
void R_BuildGammaTable (void)
static void R_CreateNotexture (void)
void R_InitImages (void)
void R_ShutdownImages (void)
Variables
static byte gammatable [256]
Macro Definition Documentation
NTX
#define NTX 256
Definition at line 126 of file image.c.
Function Documentation
IMG_Load()
void IMG_Load (image_t * image, byte * pic)
Definition at line 54 of file image.c.
 {
     int     i, c, b;
     int     width, height;
     width = image->upload_width;
     height = image->upload_height;
     if (image->flags & IF_TURBULENT) {
         image->width = TURB_SIZE;
         image->height = TURB_SIZE;
     }
     b = image->width * image->height;
     c = width * height;
     if (image->type == IT_WALL) {
         image->pixels[0] = R_Malloc(MIPSIZE(b) * TEX_BYTES);
         image->pixels[1] = image->pixels[0] + b * TEX_BYTES;
         image->pixels[2] = image->pixels[1] + b * TEX_BYTES / 4;
         image->pixels[3] = image->pixels[2] + b * TEX_BYTES / 16;
         if (!(r_config.flags & QVF_GAMMARAMP))
             R_LightScaleTexture(pic, width, height);
         if (width == image->width && height == image->height) {
             memcpy(image->pixels[0], pic, width * height * TEX_BYTES);
         } else {
             IMG_ResampleTexture(pic, width, height, image->pixels[0], image->width, image->height);
             image->upload_width = image->width;
             image->upload_height = image->height;
         }
         IMG_MipMap(image->pixels[1], image->pixels[0], image->width >> 0, image->height >> 0);
         IMG_MipMap(image->pixels[2], image->pixels[1], image->width >> 1, image->height >> 1);
         IMG_MipMap(image->pixels[3], image->pixels[2], image->width >> 2, image->height >> 2);
         Z_Free(pic);
     } else {
         image->pixels[0] = pic;
         if (!(image->flags & IF_OPAQUE)) {
             for (i = 0; i < c; i++) {
                 b = pic[i * TEX_BYTES + 3];
                 if (b != 255) {
                     image->flags |= IF_TRANSPARENT;
                 }
             }
         }
     }
     if (image->type == IT_SKIN && !(r_config.flags & QVF_GAMMARAMP))
         R_LightScaleTexture(image->pixels[0], width, height);
 }
IMG_Unload()
void IMG_Unload (image_t * image)
Definition at line 28 of file image.c.
 {
     Z_Free(image->pixels[0]);
     image->pixels[0] = NULL;
 }
R_BuildGammaTable()
void R_BuildGammaTable (void)
Definition at line 109 of file image.c.
 {
     int     i, inf;
     float   g = vid_gamma->value;
     if (g == 1.0) {
         for (i = 0; i < 256; i++)
             gammatable[i] = i;
         return;
     }
     for (i = 0; i < 256; i++) {
         inf = 255 * pow((i + 0.5) / 255.5, g) + 0.5;
         gammatable[i] = clamp(inf, 0, 255);
     }
 }
Referenced by R_InitImages().
R_CreateNotexture()
static void R_CreateNotexture (void) static
Definition at line 128 of file image.c.
 {
     static byte buffer[MIPSIZE(NTX * NTX) * TEX_BYTES];
     int         x, y, m;
     uint32_t    *p;
     image_t     *ntx;
 // create a simple checkerboard texture for the default
     ntx = R_NOTEXTURE;
     ntx->type = IT_WALL;
     ntx->flags = 0;
     ntx->width = ntx->height = NTX;
     ntx->upload_width = ntx->upload_height = NTX;
     ntx->pixels[0] = buffer;
     ntx->pixels[1] = ntx->pixels[0] + NTX * NTX * TEX_BYTES;
     ntx->pixels[2] = ntx->pixels[1] + NTX * NTX * TEX_BYTES / 4;
     ntx->pixels[3] = ntx->pixels[2] + NTX * NTX * TEX_BYTES / 16;
     for (m = 0; m < 4; m++) {
         p = (uint32_t *)ntx->pixels[m];
         for (y = 0; y < (NTX >> m); y++) {
             for (x = 0; x < (NTX >> m); x++) {
                 if ((x ^ y) & (1 << (3 - m)))
                     *p++ = U32_BLACK;
                 else
                     *p++ = U32_WHITE;
             }
         }
     }
 }
Referenced by R_InitImages().
R_InitImages()
void R_InitImages (void)
Definition at line 164 of file image.c.
 {
     registration_sequence = 1;
     IMG_GetPalette();
     R_CreateNotexture();
     R_BuildGammaTable();
 }
Referenced by R_Init().
R_LightScaleTexture()
static void R_LightScaleTexture (byte * in, int inwidth, int inheight) static
Definition at line 34 of file image.c.
 {
     int     i, c;
     byte    *p;
     p = in;
     c = inwidth * inheight;
     for (i = 0; i < c; i++, p += TEX_BYTES) {
         p[0] = gammatable[p[0]];
         p[1] = gammatable[p[1]];
         p[2] = gammatable[p[2]];
     }
 }
Referenced by IMG_Load().
R_ShutdownImages()
void R_ShutdownImages (void)
Definition at line 180 of file image.c.
 {
     IMG_FreeAll();
 }
Referenced by R_Shutdown().
Variable Documentation
gammatable
byte gammatable[256] static
Definition at line 21 of file image.c.
Referenced by R_BuildGammaTable(), and R_LightScaleTexture().