Quake II RTX doxygen: C:/entry/dev/Q2RTX/src/refresh/vkpt/device_memory_allocator.h File Reference
device_memory_allocator.h File Reference
#include <stdint.h>
Classes
struct DeviceMemory
Typedefs
typedef struct DeviceMemory DeviceMemory
typedef struct DeviceMemoryAllocator DeviceMemoryAllocator
Enumerations
enum DMAResult { DMA_SUCCESS = 0, DMA_NOT_ENOUGH_MEMORY }
Functions
DeviceMemoryAllocator * create_device_memory_allocator (VkDevice device)
DMAResult allocate_device_memory (DeviceMemoryAllocator *allocator, DeviceMemory *device_memory)
void free_device_memory (DeviceMemoryAllocator *allocator, const DeviceMemory *device_memory)
void destroy_device_memory_allocator (DeviceMemoryAllocator *allocator)
Typedef Documentation
DeviceMemory
typedef struct DeviceMemory DeviceMemory
DeviceMemoryAllocator
typedef struct DeviceMemoryAllocator DeviceMemoryAllocator
Definition at line 37 of file device_memory_allocator.h.
Enumeration Type Documentation
DMAResult
enum DMAResult
Enumerator
DMA_SUCCESS
DMA_NOT_ENOUGH_MEMORY
Definition at line 22 of file device_memory_allocator.h.
 {
     DMA_SUCCESS = 0,
     DMA_NOT_ENOUGH_MEMORY
 } DMAResult;
Function Documentation
allocate_device_memory()
DMAResult allocate_device_memory (DeviceMemoryAllocator * allocator, DeviceMemory * device_memory)
Definition at line 60 of file device_memory_allocator.c.
 {
     const uint32_t memory_type = device_memory->memory_type;
     if (allocator->sub_allocators[memory_type] == NULL)
     {
         if (!create_sub_allocator(allocator, memory_type))
             return DMA_NOT_ENOUGH_MEMORY;
     }
     assert(device_memory->size <= ALLOCATOR_CAPACITY);
     BAResult result = BA_NOT_ENOUGH_MEMORY;
     SubAllocator* sub_allocator = allocator->sub_allocators[memory_type];
     while (result != BA_SUCCESS)
     {
         device_memory->memory = sub_allocator->memory;
         result = buddy_allocator_allocate(sub_allocator->buddy_allocator, device_memory->size,
             device_memory->alignment, &device_memory->memory_offset);
         assert(result <= BA_NOT_ENOUGH_MEMORY);
         if (result == BA_NOT_ENOUGH_MEMORY)
         {
             if (sub_allocator->next != NULL)
             {
                 sub_allocator = sub_allocator->next;
             }
             else
             {
                 if (!create_sub_allocator(allocator, memory_type))
                     return DMA_NOT_ENOUGH_MEMORY;
                 sub_allocator = allocator->sub_allocators[memory_type];
             }
         }
     }
     return DMA_SUCCESS;
 }
Referenced by create_invalid_texture(), and vkpt_textures_end_registration().
create_device_memory_allocator()
DeviceMemoryAllocator* create_device_memory_allocator (VkDevice device)
Definition at line 48 of file device_memory_allocator.c.
 {
     char* memory = malloc(sizeof(DeviceMemoryAllocator));
     DeviceMemoryAllocator* allocator = (DeviceMemoryAllocator*)memory;
     memset(allocator, 0, sizeof(DeviceMemoryAllocator));
     allocator->memory = memory;
     allocator->device = device;
     return allocator;
 }
Referenced by vkpt_textures_initialize().
destroy_device_memory_allocator()
void destroy_device_memory_allocator (DeviceMemoryAllocator * allocator)
Definition at line 110 of file device_memory_allocator.c.
 {
     for (uint32_t i = 0; i < VK_MAX_MEMORY_TYPES; i++)
     {
         SubAllocator* sub_allocator = allocator->sub_allocators[i];
         while (sub_allocator != NULL)
         {
             vkFreeMemory(allocator->device, sub_allocator->memory, NULL);
             sub_allocator = sub_allocator->next;
         }
     }
     free(allocator->memory);
 }
Referenced by vkpt_textures_destroy().
free_device_memory()
void free_device_memory (DeviceMemoryAllocator * allocator, const DeviceMemory * device_memory)
Definition at line 100 of file device_memory_allocator.c.
 {
     SubAllocator* sub_allocator = allocator->sub_allocators[device_memory->memory_type];
     while (sub_allocator->memory != device_memory->memory)
         sub_allocator = sub_allocator->next;
     buddy_allocator_free(sub_allocator->buddy_allocator, device_memory->memory_offset, device_memory->size);
 }
Referenced by destroy_invalid_texture(), destroy_tex_images(), IMG_ReloadAll(), and textures_destroy_unused_set().