Quake II RTX doxygen: C:/entry/dev/Q2RTX/src/common/zone.c File Reference
zone.c File Reference
#include "shared/shared.h"
#include "common/common.h"
#include "common/zone.h"
Classes
struct zhead_s
struct zstatic_t
struct zstats_t
Macros
#define Z_MAGIC 0x1d0d
#define Z_TAIL 0x5b7b
#define Z_TAIL_F(z) *(uint16_t *)((byte *)(z) + (z)->size - sizeof(uint16_t))
#define Z_FOR_EACH(z) for ((z) = z_chain.next; (z) != &z_chain; (z) = (z)->next)
#define Z_FOR_EACH_SAFE(z, n) for ((z) = z_chain.next; (z) != &z_chain; (z) = (n))
#define Z_EXTRA (sizeof(zhead_t) + sizeof(uint16_t))
#define Z_STATIC(x) { { Z_MAGIC, TAG_STATIC, q_offsetof(zstatic_t, tail) + sizeof(uint16_t) }, x, Z_TAIL }
Typedefs
typedef struct zhead_s zhead_t
Functions
static void Z_Validate (zhead_t *z, const char *func)
void Z_Check (void)
void Z_LeakTest (memtag_t tag)
void Z_Free (void *ptr)
void * Z_Realloc (void *ptr, size_t size)
void Z_Stats_f (void)
void Z_FreeTags (memtag_t tag)
void * Z_TagMalloc (size_t size, memtag_t tag)
void * Z_TagMallocz (size_t size, memtag_t tag)
void Z_TagReserve (size_t size, memtag_t tag)
void * Z_ReservedAlloc (size_t size)
void * Z_ReservedAllocz (size_t size)
char * Z_ReservedCopyString (const char *in)
void Z_Init (void)
char * Z_TagCopyString (const char *in, memtag_t tag)
char * Z_CvarCopyString (const char *in)
Variables
static zhead_t z_chain
static const zstatic_t z_static []
static zstats_t z_stats [TAG_MAX]
static const char z_tagnames [TAG_MAX][8]
static byte * z_reserved_data
static size_t z_reserved_inuse
static size_t z_reserved_total
Macro Definition Documentation
Z_EXTRA
#define Z_EXTRA (sizeof(zhead_t) + sizeof(uint16_t))
Definition at line 47 of file zone.c.
Z_FOR_EACH
#define Z_FOR_EACH (z) for ((z) = z_chain.next; (z) != &z_chain; (z) = (z)->next)
Definition at line 29 of file zone.c.
Z_FOR_EACH_SAFE
#define Z_FOR_EACH_SAFE (z, n) for ((z) = z_chain.next; (z) != &z_chain; (z) = (n))
Definition at line 32 of file zone.c.
Z_MAGIC
#define Z_MAGIC 0x1d0d
Definition at line 23 of file zone.c.
Z_STATIC
#define Z_STATIC (x) { { Z_MAGIC, TAG_STATIC, q_offsetof(zstatic_t, tail) + sizeof(uint16_t) }, x, Z_TAIL }
Z_TAIL
#define Z_TAIL 0x5b7b
Definition at line 24 of file zone.c.
Z_TAIL_F
#define Z_TAIL_F (z) *(uint16_t *)((byte *)(z) + (z)->size - sizeof(uint16_t))
Definition at line 26 of file zone.c.
Typedef Documentation
zhead_t
typedef struct zhead_s zhead_t
Function Documentation
Z_Check()
void Z_Check (void)
Definition at line 111 of file zone.c.
 {
     zhead_t *z;
     Z_FOR_EACH(z) {
         Z_Validate(z, __func__);
     }
 }
Z_CvarCopyString()
char* Z_CvarCopyString (const char * in)
Definition at line 419 of file zone.c.
 {
     size_t len;
     zstatic_t *z;
     zstats_t *s;
     int i;
     if (!in) {
         return NULL;
     }
     if (!in[0]) {
         i = 10;
     } else if (!in[1] && Q_isdigit(in[0])) {
         i = in[0] - '0';
     } else {
         len = strlen(in) + 1;
         return memcpy(Z_TagMalloc(len, TAG_CVAR), in, len);
     }
     // return static storage
     z = (zstatic_t *)&z_static[i];
     s = &z_stats[TAG_STATIC];
     s->count++;
     s->bytes += z->z.size;
     return z->data;
 }
Referenced by change_string_value(), Cvar_Get(), Cvar_SetByVar(), and get_engine_cvar().
Z_Free()
void Z_Free (void * ptr)
Definition at line 147 of file zone.c.
 {
     zhead_t *z;
     zstats_t *s;
     if (!ptr) {
         return;
     }
     z = (zhead_t *)ptr - 1;
     Z_Validate(z, __func__);
     s = &z_stats[z->tag < TAG_MAX ? z->tag : TAG_FREE];
     s->count--;
     s->bytes -= z->size;
     if (z->tag != TAG_STATIC) {
         z->prev->next = z->next;
         z->next->prev = z->prev;
         z->magic = 0xdead;
         z->tag = TAG_FREE;
         free(z);
     }
 }
Referenced by AC_FreeChecks(), Action_Free(), BitField_Free(), Bitmap_Free(), BSP_Free(), BSP_Load(), bsp_mesh_destroy(), BSP_SavePatchedPVS(), change_string_value(), CL_CleanupDemos(), CL_CleanupDownloads(), CL_InitRefresh(), CL_LoadDownloadIgnores(), ClearServers(), CM_FreeMap(), Cmd_AliasSet(), Cmd_RemoveCommand(), Cmd_UnAlias_f(), Cmd_UnTrigger_f(), collect_cluster_lights(), Com_Crash_f(), Com_MapList_m(), computeTangents(), Con_Paste(), Con_RemoteMode_f(), create_shader_module_from_file(), Cvar_GetLatchedVars(), Cvar_SetByVar(), demo_destroy(), demo_free_playlist(), dummy_create(), Field_Free(), finish_download(), free_all_links(), free_msg_packet(), free_search_path(), FreeList(), FreeSlot(), FS_File_g(), FS_FreeList(), FS_Link_f(), FS_ListFiles(), FS_LoadFileEx(), FS_UnLink_f(), get_engine_cvar(), gtv_destroy(), HTTP_CleanupDownloads(), IMG_Load(), IMG_Load_GL(), IMG_ReloadAll(), IMG_Unload(), IMG_Unload_RTX(), Key_SetBinding(), Keybind_Free(), load_blue_noise(), load_cameras(), load_sky_and_lava_clusters(), LOC_Delete_f(), LOC_FreeLocations(), LOC_Update_f(), Menu_Free(), MVD_ClearState(), MVD_Free(), MVD_FreePlayer(), MVD_ParseServerData(), MVD_Shutdown(), MVD_StopRecord(), Netchan_Close(), pack_put(), Pairs_Free(), Parse_File(), parse_file_list(), ParseMasterArgs(), PlayerModel_Free(), PlayerModel_Load(), Pop(), Prompt_Action(), Prompt_Clear(), Prompt_ClearState(), Prompt_CompleteCommand(), Prompt_HistoryUp(), Prompt_LoadHistory(), q_printf(), R_FreeCaches(), R_ModeChanged(), R_NewMap(), R_SetSky_RTX(), R_Shutdown(), remove_all_ignores(), remove_client(), remove_ignore(), reset_unicast_strings(), S_FreeSound(), Savegame_Push(), SCR_ReadNextFrame(), SCR_StopCinematic(), SCR_UnDraw_f(), set_back_cvar(), Slider_Free(), SpinControl_Free(), SV_BeginDownload_f(), SV_CleanClient(), SV_CloseDownload(), SV_DelFilterCmd_f(), SV_DelMatch_f(), SV_DelStuffCmd_f(), SV_InitGameProgs(), SV_MvdShutdown(), SV_SetMaster_f(), SV_Shutdown(), SV_ShutdownClientSend(), VID_GetDefaultModeList(), vkpt_begin_command_buffer(), vkpt_free_command_buffers(), Z_FreeTags(), and Z_Realloc().
Z_FreeTags()
void Z_FreeTags (memtag_t tag)
Definition at line 257 of file zone.c.
 {
     zhead_t *z, *n;
     Z_FOR_EACH_SAFE(z, n) {
         Z_Validate(z, __func__);
         n = z->next;
         if (z->tag == tag) {
             Z_Free(z + 1);
         }
     }
 }
Referenced by PF_FreeTags().
Z_Init()
void Z_Init (void)
Definition at line 392 of file zone.c.
 {
     z_chain.next = z_chain.prev = &z_chain;
 }
Referenced by Qcommon_Init().
Z_LeakTest()
void Z_LeakTest (memtag_t tag)
Definition at line 120 of file zone.c.
 {
     zhead_t *z;
     size_t numLeaks = 0, numBytes = 0;
     Z_FOR_EACH(z) {
         Z_Validate(z, __func__);
         if (z->tag == tag) {
             numLeaks++;
             numBytes += z->size;
         }
     }
     if (numLeaks) {
         Com_WPrintf("************* Z_LeakTest *************\n"
                     "%s leaked %"PRIz" bytes of memory (%"PRIz" object%s)\n"
                     "**************************************\n",
                     z_tagnames[tag < TAG_MAX ? tag : TAG_FREE],
                     numBytes, numLeaks, numLeaks == 1 ? "" : "s");
     }
 }
Referenced by CL_ShutdownRefresh(), FS_Shutdown(), MVD_Shutdown(), S_Shutdown(), SV_Shutdown(), and UI_Shutdown().
Z_Realloc()
void* Z_Realloc (void * ptr, size_t size)
Definition at line 178 of file zone.c.
 {
     zhead_t *z;
     zstats_t *s;
     if (!ptr) {
         return Z_Malloc(size);
     }
     if (!size) {
         Z_Free(ptr);
         return NULL;
     }
     z = (zhead_t *)ptr - 1;
     Z_Validate(z, __func__);
     if (z->tag == TAG_STATIC) {
         Com_Error(ERR_FATAL, "%s: couldn't realloc static memory", __func__);
     }
     s = &z_stats[z->tag < TAG_MAX ? z->tag : TAG_FREE];
     s->bytes -= z->size;
     if (size > SIZE_MAX - Z_EXTRA - 3) {
         Com_Error(ERR_FATAL, "%s: bad size", __func__);
     }
     size = (size + Z_EXTRA + 3) & ~3;
     z = realloc(z, size);
     if (!z) {
         Com_Error(ERR_FATAL, "%s: couldn't realloc %"PRIz" bytes", __func__, size);
     }
     z->size = size;
     z->prev->next = z;
     z->next->prev = z;
     s->bytes += size;
     Z_TAIL_F(z) = Z_TAIL;
     return z + 1;
 }
Referenced by append_light_poly(), recv_func(), and VID_GetDefaultModeList().
Z_ReservedAlloc()
void* Z_ReservedAlloc (size_t size)
Definition at line 349 of file zone.c.
 {
     void *ptr;
     if (!size) {
         return NULL;
     }
     if (size > z_reserved_total - z_reserved_inuse) {
         Com_Error(ERR_FATAL, "%s: couldn't allocate %"PRIz" bytes", __func__, size);
     }
     ptr = z_reserved_data + z_reserved_inuse;
     z_reserved_inuse += size;
     return ptr;
 }
Referenced by AC_ParseCvar(), NetchanOld_Setup(), SV_MvdInit(), Z_ReservedAllocz(), and Z_ReservedCopyString().
Z_ReservedAllocz()
void* Z_ReservedAllocz (size_t size)
Definition at line 367 of file zone.c.
 {
     if (!size) {
         return NULL;
     }
     return memset(Z_ReservedAlloc(size), 0, size);
 }
Referenced by MVD_GameInit().
Z_ReservedCopyString()
char* Z_ReservedCopyString (const char * in)
Definition at line 375 of file zone.c.
 {
     size_t len;
     if (!in) {
         return NULL;
     }
     len = strlen(in) + 1;
     return memcpy(Z_ReservedAlloc(len), in, len);
 }
Z_Stats_f()
void Z_Stats_f (void)
Definition at line 229 of file zone.c.
 {
     size_t bytes = 0, count = 0;
     zstats_t *s;
     int i;
     Com_Printf("    bytes blocks name\n"
                "--------- ------ -------\n");
     for (i = 0, s = z_stats; i < TAG_MAX; i++, s++) {
         if (!s->count) {
             continue;
         }
         Com_Printf("%9"PRIz" %6"PRIz" %s\n", s->bytes, s->count, z_tagnames[i]);
         bytes += s->bytes;
         count += s->count;
     }
     Com_Printf("--------- ------ -------\n"
                "%9"PRIz" %6"PRIz" total\n",
                bytes, count);
 }
Referenced by Qcommon_Init().
Z_TagCopyString()
char* Z_TagCopyString (const char * in, memtag_t tag)
Definition at line 402 of file zone.c.
 {
     size_t len;
     if (!in) {
         return NULL;
     }
     len = strlen(in) + 1;
     return memcpy(Z_TagMalloc(len, tag), in, len);
 }
Z_TagMalloc()
void* Z_TagMalloc (size_t size, memtag_t tag)
Definition at line 275 of file zone.c.
 {
     zhead_t *z;
     zstats_t *s;
     if (!size) {
         return NULL;
     }
     if (tag == TAG_FREE) {
         Com_Error(ERR_FATAL, "%s: bad tag", __func__);
     }
     if (size > SIZE_MAX - Z_EXTRA - 3) {
         Com_Error(ERR_FATAL, "%s: bad size", __func__);
     }
     size = (size + Z_EXTRA + 3) & ~3;
     z = malloc(size);
     if (!z) {
         Com_Error(ERR_FATAL, "%s: couldn't allocate %"PRIz" bytes", __func__, size);
     }
     z->magic = Z_MAGIC;
     z->tag = tag;
     z->size = size;
 #ifdef _DEBUG
 #if (defined __GNUC__)
     z->addr = __builtin_return_address(0);
 #elif (defined _MSC_VER)
     z->addr = _ReturnAddress();
 #else
     z->addr = NULL;
 #endif
     z->time = time(NULL);
 #endif
     z->next = z_chain.next;
     z->prev = &z_chain;
     z_chain.next->prev = z;
     z_chain.next = z;
     if (z_perturb && z_perturb->integer) {
         memset(z + 1, z_perturb->integer, size - Z_EXTRA);
     }
     Z_TAIL_F(z) = Z_TAIL;
     s = &z_stats[tag < TAG_MAX ? tag : TAG_FREE];
     s->count++;
     s->bytes += size;
     return z + 1;
 }
Referenced by FS_LoadFileEx(), PF_TagMalloc(), Z_CvarCopyString(), Z_TagCopyString(), Z_TagMallocz(), and Z_TagReserve().
Z_TagMallocz()
void* Z_TagMallocz (size_t size, memtag_t tag)
Definition at line 330 of file zone.c.
 {
     if (!size) {
         return NULL;
     }
     return memset(Z_TagMalloc(size, tag), 0, size);
 }
Referenced by CM_LoadMap(), and NetchanNew_Setup().
Z_TagReserve()
void Z_TagReserve (size_t size, memtag_t tag)
Definition at line 342 of file zone.c.
 {
     z_reserved_data = Z_TagMalloc(size, tag);
     z_reserved_total = size;
     z_reserved_inuse = 0;
 }
Referenced by AC_ParseCvar(), MVD_GameInit(), NetchanOld_Setup(), and SV_MvdInit().
Z_Validate()
static void Z_Validate (zhead_t * z, const char * func) inline static
Definition at line 98 of file zone.c.
 {
     if (z->magic != Z_MAGIC) {
         Com_Error(ERR_FATAL, "%s: bad magic", func);
     }
     if (Z_TAIL_F(z) != Z_TAIL) {
         Com_Error(ERR_FATAL, "%s: bad tail", func);
     }
     if (z->tag == TAG_FREE) {
         Com_Error(ERR_FATAL, "%s: bad tag", func);
     }
 }
Referenced by Z_Check(), Z_Free(), Z_FreeTags(), Z_LeakTest(), and Z_Realloc().
Variable Documentation
z_chain
zhead_t z_chain static
Definition at line 49 of file zone.c.
Referenced by Z_Init(), and Z_TagMalloc().
z_reserved_data
byte* z_reserved_data static
Definition at line 338 of file zone.c.
Referenced by Z_ReservedAlloc(), and Z_TagReserve().
z_reserved_inuse
size_t z_reserved_inuse static
Definition at line 339 of file zone.c.
Referenced by Z_ReservedAlloc(), and Z_TagReserve().
z_reserved_total
size_t z_reserved_total static
Definition at line 340 of file zone.c.
Referenced by Z_ReservedAlloc(), and Z_TagReserve().
z_static
const zstatic_t z_static[] static
Initial value:
= {
#define Z_STATIC(x)
    Z_STATIC("0"),
    Z_STATIC("1"),
    Z_STATIC("2"),
    Z_STATIC("3"),
    Z_STATIC("4"),
    Z_STATIC("5"),
    Z_STATIC("6"),
    Z_STATIC("7"),
    Z_STATIC("8"),
    Z_STATIC("9"),
}
Definition at line 57 of file zone.c.
Referenced by Z_CvarCopyString().
z_stats
zstats_t z_stats[TAG_MAX] static
Definition at line 81 of file zone.c.
Referenced by Z_CvarCopyString(), Z_Free(), Z_Realloc(), Z_Stats_f(), and Z_TagMalloc().
z_tagnames
const char z_tagnames[TAG_MAX][8] static
Initial value:
= {
    "game",
    "static",
    "generic",
    "cmd",
    "cvar",
    "fs",
    "refresh",
    "ui",
    "server",
    "mvd",
    "sound",
    "cmodel"
}
Definition at line 83 of file zone.c.
Referenced by Z_LeakTest(), and Z_Stats_f().