Quake II RTX doxygen: C:/entry/dev/Q2RTX/src/common/error.c File Reference
error.c File Reference
#include "shared/shared.h"
#include "common/error.h"
Functions
const char * Q_ErrorString (qerror_t error)
Variables
static const char *const error_table []
static const int num_errors = q_countof(error_table)
Function Documentation
Q_ErrorString()
const char* Q_ErrorString (qerror_t error)
Definition at line 51 of file error.c.
 {
     int e;
     if (error >= 0) {
         return "Success";
     }
     if (error > -ERRNO_MAX) {
 #if EINVAL > 0
         e = -error;
 #else
         e = error;
 #endif
         return strerror(e);
     }
     e = _Q_ERR(error);
     return error_table[e >= num_errors ? 0 : e];
 }
Referenced by AC_ParseFile(), BSP_Test_f(), CL_Download_f(), CL_HandleDownload(), CL_LoadDownloadIgnores(), CL_PlayDemo_f(), CL_RegisterBspModels(), CL_Seek_f(), CL_WriteConfig(), CL_WriteDemoMessage(), Cmd_Exec_f(), Com_AddConfigFile(), Con_RegisterMedia(), create_screenshot(), demo_finish(), demo_play_next(), easy_open_read(), easy_open_write(), finish_demo(), FS_EasyWriteFile(), FS_WhereIs_f(), GL_LoadWorld(), IMG_Find(), IMG_GetPalette(), LOC_LoadLocations(), logfile_write(), make_screenshot(), MVD_GameInit(), MVD_ParseServerData(), MVD_Seek_f(), MVD_StreamedRecord_f(), MVD_WriteDemoMessage(), open_file_read(), open_file_write(), open_from_disk(), open_from_pak(), override_entity_string(), Parse_File(), R_BeginRegistration(), R_BeginRegistration_RTX(), R_RegisterImage(), R_RegisterModel(), rec_frame(), rec_write(), S_SoundList_f(), SCR_ScoreShot_f(), start_download(), start_udp_download(), SV_ParseMapCmd(), and write_udp_download().
Variable Documentation
error_table
const char* const error_table[] static
Initial value:
= {
    "Unspecified error",
    "Unknown file format",
    "Invalid file format",
    "Bad lump extent",
    "Odd lump size",
    "Too many elements",
    "Too few elements",
    "Index out of range",
    "Invalid quake path",
    "File name too short",
    "Unexpected end of file",
    "File too small",
    "Not a regular file",
    "Bad run length packet",
    "String truncation avoided",
    "Runaway loop avoided",
    "Infinite loop avoided",
    "Library error",
    "Out of slots",
}
Definition at line 22 of file error.c.
Referenced by Q_ErrorString().
num_errors
const int num_errors = q_countof(error_table) static
Definition at line 49 of file error.c.
Referenced by Q_ErrorString().