Quake II RTX doxygen: C:/entry/dev/Q2RTX/src/client/sound/main.c File Reference
main.c File Reference
#include "sound.h"
#include "client/sound/vorbis.h"
Macros
#define MAX_SFX (MAX_SOUNDS*2)
#define MAX_PLAYSOUNDS 128
Functions
static void S_SoundInfo_f (void)
static void S_SoundList_f (void)
static void s_auto_focus_changed (cvar_t *self)
void S_Init (void)
static void S_FreeSound (sfx_t *sfx)
void S_FreeAllSounds (void)
void S_Shutdown (void)
void S_Activate (void)
sfx_t * S_SfxForHandle (qhandle_t hSfx)
static sfx_t * S_AllocSfx (void)
static sfx_t * S_FindName (const char *name, size_t namelen)
void S_BeginRegistration (void)
qhandle_t S_RegisterSound (const char *name)
static sfx_t * S_RegisterSexedSound (int entnum, const char *base)
static void S_RegisterSexedSounds (void)
void S_EndRegistration (void)
channel_t * S_PickChannel (int entnum, int entchannel)
static playsound_t * S_AllocPlaysound (void)
static void S_FreePlaysound (playsound_t *ps)
void S_IssuePlaysound (playsound_t *ps)
void S_StartSound (const vec3_t origin, int entnum, int entchannel, qhandle_t hSfx, float vol, float attenuation, float timeofs)
void S_ParseStartSound (void)
void S_StartLocalSound (const char *sound)
void S_StartLocalSound_ (const char *sound)
void S_StopAllSounds (void)
void S_BuildSoundList (int *sounds)
void S_Update (void)
float S_GetLinearVolume (float perceptual)
Variables
int s_registration_sequence
channel_t channels [MAX_CHANNELS]
int s_numchannels
sndstarted_t s_started
qboolean s_active
vec3_t listener_origin
vec3_t listener_forward
vec3_t listener_right
vec3_t listener_up
int listener_entnum
qboolean s_registering
int paintedtime
static sfx_t known_sfx [MAX_SFX]
static int num_sfx
playsound_t s_playsounds [MAX_PLAYSOUNDS]
playsound_t s_freeplays
playsound_t s_pendingplays
cvar_t * s_volume
cvar_t * s_ambient
static cvar_t * s_enable
static cvar_t * s_auto_focus
static cvar_t * s_swapstereo
static const cmdreg_t c_sound []
Macro Definition Documentation
MAX_PLAYSOUNDS
#define MAX_PLAYSOUNDS 128
Definition at line 53 of file main.c.
MAX_SFX
#define MAX_SFX (MAX_SOUNDS*2)
Definition at line 49 of file main.c.
Function Documentation
S_Activate()
void S_Activate (void)
Definition at line 272 of file main.c.
 {
     qboolean active;
     active_t level;
     if (!s_started)
         return;
     level = Cvar_ClampInteger(s_auto_focus, ACT_MINIMIZED, ACT_ACTIVATED);
     active = cls.active >= level;
     if (active == s_active)
         return;
     s_active = active;
     Com_DDDPrintf("%s: %d\n", __func__, s_active);
 #if USE_OPENAL
     if (s_started == SS_OAL)
         S_StopAllSounds();
 #endif
 #if USE_SNDDMA
     if (s_started == SS_DMA)
         DMA_Activate();
 #endif
 }
Referenced by CL_Activate(), and s_auto_focus_changed().
S_AllocPlaysound()
static playsound_t* S_AllocPlaysound (void) static
Definition at line 716 of file main.c.
 {
     playsound_t *ps;
     ps = s_freeplays.next;
     if (ps == &s_freeplays)
         return NULL;        // no free playsounds
     // unlink from freelist
     ps->prev->next = ps->next;
     ps->next->prev = ps->prev;
     return ps;
 }
Referenced by S_StartSound().
S_AllocSfx()
static sfx_t* S_AllocSfx (void) static
Definition at line 325 of file main.c.
 {
     sfx_t   *sfx;
     int     i;
     // find a free sfx
     for (i = 0, sfx = known_sfx; i < num_sfx; i++, sfx++) {
         if (!sfx->name[0])
             break;
     }
     if (i == num_sfx) {
         if (num_sfx == MAX_SFX)
             return NULL;
         num_sfx++;
     }
     return sfx;
 }
Referenced by S_FindName().
s_auto_focus_changed()
static void s_auto_focus_changed (cvar_t * self) static
Definition at line 138 of file main.c.
 {
     S_Activate();
 }
Referenced by S_Init().
S_BeginRegistration()
void S_BeginRegistration (void)
Definition at line 379 of file main.c.
 {
     s_registration_sequence++;
     s_registering = qtrue;
 }
Referenced by CL_RegisterSounds().
S_BuildSoundList()
void S_BuildSoundList (int * sounds)
Definition at line 969 of file main.c.
 {
     int         i;
     int         num;
     entity_state_t  *ent;
     for (i = 0; i < cl.frame.numEntities; i++) {
         num = (cl.frame.firstEntity + i) & PARSE_ENTITIES_MASK;
         ent = &cl.entityStates[num];
         if (s_ambient->integer == 2 && !ent->modelindex) {
             sounds[i] = 0;
         } else if (s_ambient->integer == 3 && ent->number != listener_entnum) {
             sounds[i] = 0;
         } else {
             sounds[i] = ent->sound;
         }
     }
 }
Referenced by AL_AddLoopSounds().
S_EndRegistration()
void S_EndRegistration (void)
Definition at line 522 of file main.c.
 {
     int     i;
     sfx_t   *sfx;
 #if USE_SNDDMA
     sfxcache_t *sc;
     int     size;
 #endif
     S_RegisterSexedSounds();
     // clear playsound list, so we don't free sfx still present there
     S_StopAllSounds();
     // free any sounds not from this registration sequence
     for (i = 0, sfx = known_sfx; i < num_sfx; i++, sfx++) {
         if (!sfx->name[0])
             continue;
         if (sfx->registration_sequence != s_registration_sequence) {
             // don't need this sound
             S_FreeSound(sfx);
             continue;
         }
 #if USE_OPENAL
         if (s_started == SS_OAL)
             continue;
 #endif
 #if USE_SNDDMA
         // make sure it is paged in
         sc = sfx->cache;
         if (sc) {
             size = sc->length * sc->width;
             Com_PageInMemory(sc, size);
         }
 #endif
     }
     // load everything in
     for (i = 0, sfx = known_sfx; i < num_sfx; i++, sfx++) {
         if (!sfx->name[0])
             continue;
         S_LoadSound(sfx);
     }
     s_registering = qfalse;
 }
Referenced by CL_RegisterSounds().
S_FindName()
static sfx_t* S_FindName (const char * name, size_t namelen) static
Definition at line 351 of file main.c.
 {
     int     i;
     sfx_t   *sfx;
     // see if already loaded
     for (i = 0, sfx = known_sfx; i < num_sfx; i++, sfx++) {
         if (!FS_pathcmp(sfx->name, name)) {
             sfx->registration_sequence = s_registration_sequence;
             return sfx;
         }
     }
     // allocate new one
     sfx = S_AllocSfx();
     if (sfx) {
         memcpy(sfx->name, name, namelen + 1);
         sfx->registration_sequence = s_registration_sequence;
     }
     return sfx;
 }
Referenced by S_RegisterSexedSound(), and S_RegisterSound().
S_FreeAllSounds()
void S_FreeAllSounds (void)
Definition at line 226 of file main.c.
 {
     int     i;
     sfx_t   *sfx;
     // free all sounds
     for (i = 0, sfx = known_sfx; i < num_sfx; i++, sfx++) {
         if (!sfx->name[0])
             continue;
         S_FreeSound(sfx);
     }
     num_sfx = 0;
 }
Referenced by CL_RestartFilesystem(), and S_Shutdown().
S_FreePlaysound()
static void S_FreePlaysound (playsound_t * ps) static
Definition at line 737 of file main.c.
 {
     // unlink from channel
     ps->prev->next = ps->next;
     ps->next->prev = ps->prev;
     // add to free list
     ps->next = s_freeplays.next;
     s_freeplays.next->prev = ps;
     ps->prev = &s_freeplays;
     s_freeplays.next = ps;
 }
Referenced by S_IssuePlaysound().
S_FreeSound()
static void S_FreeSound (sfx_t * sfx) static
Definition at line 213 of file main.c.
 {
 #if USE_OPENAL
     if (s_started == SS_OAL)
         AL_DeleteSfx(sfx);
 #endif
     if (sfx->cache)
         Z_Free(sfx->cache);
     if (sfx->truename)
         Z_Free(sfx->truename);
     memset(sfx, 0, sizeof(*sfx));
 }
Referenced by S_EndRegistration(), and S_FreeAllSounds().
S_GetLinearVolume()
float S_GetLinearVolume (float perceptual)
Definition at line 1171 of file main.c.
 {
     float volume = perceptual;
     // clamp anything below 1% to zero
     if (volume < 0.01f)
         return 0.f;
     // 50 dB exponential curve
     // more info: https://www.dr-lex.be/info-stuff/volumecontrols.html
     volume = 0.003161f * expf(perceptual * 5.757f);
     // upper limit
     volume = min(1.f, volume);
     return volume;
 }
Referenced by AL_Update(), OGG_Read(), and S_InitScaletable().
S_Init()
void S_Init (void)
Definition at line 148 of file main.c.
 {
     s_enable = Cvar_Get("s_enable", "2", CVAR_SOUND);
     if (s_enable->integer <= SS_NOT) {
         Com_Printf("Sound initialization disabled.\n");
         return;
     }
     Com_Printf("------- S_Init -------\n");
     s_volume = Cvar_Get("s_volume", "0.7", CVAR_ARCHIVE);
     s_ambient = Cvar_Get("s_ambient", "1", 0);
 #ifdef _DEBUG
     s_show = Cvar_Get("s_show", "0", 0);
 #endif
     s_auto_focus = Cvar_Get("s_auto_focus", "0", 0);
     s_swapstereo = Cvar_Get("s_swapstereo", "0", 0);
     // start one of available sound engines
     s_started = SS_NOT;
 #if USE_OPENAL
     if (s_started == SS_NOT && s_enable->integer >= SS_OAL && AL_Init())
         s_started = SS_OAL;
 #endif
 #if USE_SNDDMA
     if (s_started == SS_NOT && s_enable->integer >= SS_DMA && DMA_Init())
         s_started = SS_DMA;
 #endif
     if (s_started == SS_NOT) {
         Com_EPrintf("Sound failed to initialize.\n");
         goto fail;
     }
     Cmd_Register(c_sound);
     // init playsound list
     // clear DMA buffer
     S_StopAllSounds();
     s_auto_focus->changed = s_auto_focus_changed;
     s_auto_focus_changed(s_auto_focus);
     num_sfx = 0;
     paintedtime = 0;
     s_registration_sequence = 1;
     OGG_Init();
     OGG_InitTrackList();
     OGG_RecoverState();
 fail:
     Cvar_SetInteger(s_enable, s_started, FROM_CODE);
     Com_Printf("----------------------\n");
 }
Referenced by CL_Init(), and CL_RestartSound_f().
S_IssuePlaysound()
void S_IssuePlaysound (playsound_t * ps)
Definition at line 759 of file main.c.
 {
     channel_t   *ch;
     sfxcache_t  *sc;
 #ifdef _DEBUG
     if (s_show->integer)
         Com_Printf("Issue %i\n", ps->begin);
 #endif
     // pick a channel to play on
     ch = S_PickChannel(ps->entnum, ps->entchannel);
     if (!ch) {
         S_FreePlaysound(ps);
         return;
     }
     sc = S_LoadSound(ps->sfx);
     if (!sc) {
         Com_Printf("S_IssuePlaysound: couldn't load %s\n", ps->sfx->name);
         S_FreePlaysound(ps);
         return;
     }
     // spatialize
     if (ps->attenuation == ATTN_STATIC)
         ch->dist_mult = ps->attenuation * 0.001;
     else
         ch->dist_mult = ps->attenuation * 0.0005;
     ch->master_vol = ps->volume;
     ch->entnum = ps->entnum;
     ch->entchannel = ps->entchannel;
     ch->sfx = ps->sfx;
     VectorCopy(ps->origin, ch->origin);
     ch->fixed_origin = ps->fixed_origin;
 #if USE_OPENAL
     if (s_started == SS_OAL)
         AL_PlayChannel(ch);
 #endif
 #if USE_SNDDMA
     if (s_started == SS_DMA)
         S_Spatialize(ch);
 #endif
     ch->pos = 0;
     ch->end = paintedtime + sc->length;
     // free the playsound
     S_FreePlaysound(ps);
 }
Referenced by AL_IssuePlaysounds(), and S_PaintChannels().
S_ParseStartSound()
void S_ParseStartSound (void)
Definition at line 889 of file main.c.
 {
     qhandle_t handle = cl.sound_precache[snd.index];
     if (!handle)
         return;
 #ifdef _DEBUG
     if (developer->integer && !(snd.flags & SND_POS))
         CL_CheckEntityPresent(snd.entity, "sound");
 #endif
     S_StartSound((snd.flags & SND_POS) ? snd.pos : NULL,
                  snd.entity, snd.channel, handle,
                  snd.volume, snd.attenuation, snd.timeofs);
 }
Referenced by CL_ParseServerMessage().
S_PickChannel()
channel_t* S_PickChannel (int entnum, int entchannel)
Definition at line 579 of file main.c.
 {
     int         ch_idx;
     int         first_to_die;
     int         life_left;
     channel_t   *ch;
     if (entchannel < 0)
         Com_Error(ERR_DROP, "S_PickChannel: entchannel < 0");
 // Check for replacement sound, or find the best one to replace
     first_to_die = -1;
     life_left = 0x7fffffff;
     for (ch_idx = 0; ch_idx < s_numchannels; ch_idx++) {
         ch = &channels[ch_idx];
         // channel 0 never overrides unless out of channels
         if (ch->entnum == entnum && ch->entchannel == entchannel && entchannel != 0) {
             if (entchannel == 256 && ch->sfx) {
                 return NULL; // channel 256 never overrides
             }
             // always override sound from same entity
             first_to_die = ch_idx;
             break;
         }
         // don't let monster sounds override player sounds
         if (ch->entnum == listener_entnum && entnum != listener_entnum && ch->sfx)
             continue;
         if (ch->end - paintedtime < life_left) {
             life_left = ch->end - paintedtime;
             first_to_die = ch_idx;
         }
     }
     if (first_to_die == -1)
         return NULL;
     ch = &channels[first_to_die];
 #if USE_OPENAL
     if (s_started == SS_OAL && ch->sfx)
         AL_StopChannel(ch);
 #endif
     memset(ch, 0, sizeof(*ch));
     return ch;
 }
Referenced by AL_AddLoopSounds(), and S_IssuePlaysound().
S_RegisterSexedSound()
static sfx_t* S_RegisterSexedSound (int entnum, const char * base) static
Definition at line 444 of file main.c.
 {
     sfx_t           *sfx;
     char            *model;
     char            buffer[MAX_QPATH];
     size_t          len;
     // determine what model the client is using
     if (entnum > 0 && entnum <= MAX_CLIENTS)
         model = cl.clientinfo[entnum - 1].model_name;
     else
         model = cl.baseclientinfo.model_name;
     // if we can't figure it out, they're male
     if (!*model)
         model = "male";
     // see if we already know of the model specific sound
     len = Q_concat(buffer, MAX_QPATH,
                    "players/", model, "/", base + 1, NULL);
     if (len >= MAX_QPATH) {
         len = Q_concat(buffer, MAX_QPATH,
                        "players/", "male", "/", base + 1, NULL);
         if (len >= MAX_QPATH)
             return NULL;
     }
     len = FS_NormalizePath(buffer, buffer);
     sfx = S_FindName(buffer, len);
     // see if it exists
     if (sfx && !sfx->truename && !s_registering && !S_LoadSound(sfx)) {
         // no, revert to the male sound in the pak0.pak
         len = Q_concat(buffer, MAX_QPATH,
                        "sound/player/male/", base + 1, NULL);
         if (len < MAX_QPATH) {
             FS_NormalizePath(buffer, buffer);
             sfx->error = Q_ERR_SUCCESS;
             sfx->truename = S_CopyString(buffer);
         }
     }
     return sfx;
 }
Referenced by S_RegisterSexedSounds(), and S_StartSound().
S_RegisterSexedSounds()
static void S_RegisterSexedSounds (void) static
Definition at line 489 of file main.c.
 {
     int     sounds[MAX_SFX];
     int     i, j, total;
     sfx_t   *sfx;
     // find sexed sounds
     total = 0;
     for (i = 0, sfx = known_sfx; i < num_sfx; i++, sfx++) {
         if (sfx->name[0] != '*')
             continue;
         if (sfx->registration_sequence != s_registration_sequence)
             continue;
         sounds[total++] = i;
     }
     // register sounds for baseclientinfo and other valid clientinfos
     for (i = 0; i <= MAX_CLIENTS; i++) {
         if (i > 0 && !cl.clientinfo[i - 1].model_name[0])
             continue;
         for (j = 0; j < total; j++) {
             sfx = &known_sfx[sounds[j]];
             S_RegisterSexedSound(i, sfx->name);
         }
     }
 }
Referenced by S_EndRegistration().
S_RegisterSound()
qhandle_t S_RegisterSound (const char * name)
Definition at line 391 of file main.c.
 {
     char    buffer[MAX_QPATH];
     sfx_t   *sfx;
     size_t  len;
     if (!s_started)
         return 0;
     // empty names are legal, silently ignore them
     if (!*name)
         return 0;
     if (*name == '*') {
         len = Q_strlcpy(buffer, name, MAX_QPATH);
     } else if (*name == '#') {
         len = FS_NormalizePathBuffer(buffer, name + 1, MAX_QPATH);
     } else {
         len = Q_concat(buffer, MAX_QPATH, "sound/", name, NULL);
         if (len < MAX_QPATH)
             len = FS_NormalizePath(buffer, buffer);
     }
     // this MAY happen after prepending "sound/"
     if (len >= MAX_QPATH) {
         Com_DPrintf("%s: oversize name\n", __func__);
         return 0;
     }
     // normalized to empty name?
     if (len == 0) {
         Com_DPrintf("%s: empty name\n", __func__);
         return 0;
     }
     sfx = S_FindName(buffer, len);
     if (!sfx) {
         Com_DPrintf("%s: out of slots\n", __func__);
         return 0;
     }
     if (!s_registering) {
         S_LoadSound(sfx);
     }
     return (sfx - known_sfx) + 1;
 }
Referenced by CL_MuzzleFlash(), CL_MuzzleFlash2(), CL_ParseTEnt(), CL_RegisterSounds(), CL_RegisterTEntSounds(), CL_UpdateConfigstring(), entity_event(), S_StartLocalSound(), and S_StartLocalSound_().
S_SfxForHandle()
sfx_t* S_SfxForHandle (qhandle_t hSfx)
Definition at line 312 of file main.c.
 {
     if (!hSfx) {
         return NULL;
     }
     if (hSfx < 1 || hSfx > num_sfx) {
         Com_Error(ERR_DROP, "S_SfxForHandle: %d out of range", hSfx);
     }
     return &known_sfx[hSfx - 1];
 }
Referenced by AL_AddLoopSounds(), and S_StartSound().
S_Shutdown()
void S_Shutdown (void)
Definition at line 241 of file main.c.
 {
     if (!s_started)
         return;
     S_StopAllSounds();
     S_FreeAllSounds();
     OGG_SaveState();
     OGG_Shutdown();
 #if USE_OPENAL
     if (s_started == SS_OAL)
         AL_Shutdown();
 #endif
 #if USE_SNDDMA
     if (s_started == SS_DMA)
         DMA_Shutdown();
 #endif
     s_started = SS_NOT;
     s_active = qfalse;
     s_auto_focus->changed = NULL;
     Cmd_Deregister(c_sound);
     Z_LeakTest(TAG_SOUND);
 }
Referenced by CL_RestartSound_f(), and CL_Shutdown().
S_SoundInfo_f()
static void S_SoundInfo_f (void) static
Definition at line 72 of file main.c.
 {
     if (!s_started) {
         Com_Printf("Sound system not started.\n");
         return;
     }
 #if USE_OPENAL
     if (s_started == SS_OAL)
         AL_SoundInfo();
 #endif
 #if USE_SNDDMA
     if (s_started == SS_DMA)
         DMA_SoundInfo();
 #endif
 }
S_SoundList_f()
static void S_SoundList_f (void) static
Definition at line 90 of file main.c.
 {
     int     i;
     sfx_t   *sfx;
     sfxcache_t  *sc;
     int     size, total;
     total = 0;
     for (sfx = known_sfx, i = 0; i < num_sfx; i++, sfx++) {
         if (!sfx->name[0])
             continue;
         sc = sfx->cache;
         if (sc) {
 #if USE_OPENAL
             if (s_started == SS_OAL)
                 size = sc->size;
             else
 #endif
                 size = sc->length * sc->width;
             total += size;
             if (sc->loopstart >= 0)
                 Com_Printf("L");
             else
                 Com_Printf(" ");
             Com_Printf("(%2db) %6i : %s\n", sc->width * 8,  size, sfx->name) ;
         } else {
             if (sfx->name[0] == '*')
                 Com_Printf("  placeholder : %s\n", sfx->name);
             else
                 Com_Printf("  not loaded  : %s (%s)\n",
                            sfx->name, Q_ErrorString(sfx->error));
         }
     }
     Com_Printf("Total resident: %i\n", total);
 }
S_StartLocalSound()
void S_StartLocalSound (const char * sound)
Definition at line 911 of file main.c.
 {
     if (s_started) {
         qhandle_t sfx = S_RegisterSound(sound);
         S_StartSound(NULL, listener_entnum, 0, sfx, 1, ATTN_NONE, 0);
     }
 }
Referenced by CL_PlaySound_f(), UI_Draw(), and UI_StartSound().
S_StartLocalSound_()
void S_StartLocalSound_ (const char * sound)
Definition at line 919 of file main.c.
 {
     if (s_started) {
         qhandle_t sfx = S_RegisterSound(sound);
         S_StartSound(NULL, listener_entnum, 256, sfx, 1, ATTN_NONE, 0);
     }
 }
Referenced by CL_ParsePrint().
S_StartSound()
void S_StartSound (const vec3_t origin, int entnum, int entchannel, qhandle_t hSfx, float vol, float attenuation, float timeofs)
Definition at line 824 of file main.c.
 {
     sfxcache_t  *sc;
     playsound_t *ps, *sort;
     sfx_t       *sfx;
     if (!s_started)
         return;
     if (!s_active)
         return;
     if (!(sfx = S_SfxForHandle(hSfx))) {
         return;
     }
     if (sfx->name[0] == '*') {
         sfx = S_RegisterSexedSound(entnum, sfx->name);
         if (!sfx)
             return;
     }
     // make sure the sound is loaded
     sc = S_LoadSound(sfx);
     if (!sc)
         return;     // couldn't load the sound's data
     // make the playsound_t
     ps = S_AllocPlaysound();
     if (!ps)
         return;
     if (origin) {
         VectorCopy(origin, ps->origin);
         ps->fixed_origin = qtrue;
     } else {
         ps->fixed_origin = qfalse;
     }
     ps->entnum = entnum;
     ps->entchannel = entchannel;
     ps->attenuation = attenuation;
     ps->volume = vol;
     ps->sfx = sfx;
 #if USE_OPENAL
     if (s_started == SS_OAL)
         ps->begin = paintedtime + timeofs * 1000;
 #endif
 #if USE_SNDDMA
     if (s_started == SS_DMA)
         ps->begin = DMA_DriftBeginofs(timeofs);
 #endif
     // sort into the pending sound list
     for (sort = s_pendingplays.next; sort != &s_pendingplays && sort->begin < ps->begin; sort = sort->next)
         ;
     ps->next = sort;
     ps->prev = sort->prev;
     ps->next->prev = ps;
     ps->prev->next = ps;
 }
Referenced by CL_MuzzleFlash(), CL_MuzzleFlash2(), CL_ParseTEnt(), entity_event(), S_ParseStartSound(), S_StartLocalSound(), and S_StartLocalSound_().
S_StopAllSounds()
void S_StopAllSounds (void)
Definition at line 932 of file main.c.
 {
     int     i;
     if (!s_started)
         return;
     // clear all the playsounds
     memset(s_playsounds, 0, sizeof(s_playsounds));
     s_freeplays.next = s_freeplays.prev = &s_freeplays;
     s_pendingplays.next = s_pendingplays.prev = &s_pendingplays;
     for (i = 0; i < MAX_PLAYSOUNDS; i++) {
         s_playsounds[i].prev = &s_freeplays;
         s_playsounds[i].next = s_freeplays.next;
         s_playsounds[i].prev->next = &s_playsounds[i];
         s_playsounds[i].next->prev = &s_playsounds[i];
     }
 #if USE_OPENAL
     if (s_started == SS_OAL)
         AL_StopAllChannels();
 #endif
 #if USE_SNDDMA
     if (s_started == SS_DMA)
         DMA_ClearBuffer();
 #endif
     // clear all the channels
     memset(channels, 0, sizeof(channels));
 }
Referenced by BuildList(), CL_Changing_f(), CL_ClearState(), CL_ConnectionlessPacket(), CL_Precache_f(), CL_RestartFilesystem(), CL_RestartRefresh(), CL_Seek_f(), DMA_Activate(), DMA_GetTime(), PingServers(), S_Activate(), S_EndRegistration(), S_Init(), and S_Shutdown().
S_Update()
void S_Update (void)
Definition at line 1080 of file main.c.
 {
 #if USE_SNDDMA
     int         i;
     channel_t   *ch;
 #endif
     if (cvar_modified & CVAR_SOUND) {
         Cbuf_AddText(&cmd_buffer, "snd_restart\n");
         cvar_modified &= ~CVAR_SOUND;
         return;
     }
     if (!s_started)
         return;
     // if the laoding plaque is up, clear everything
     // out to make sure we aren't looping a dirty
     // dma buffer while loading
     if (cls.state == ca_loading) {
         // S_ClearBuffer should be already done in S_StopAllSounds
         return;
     }
     // set listener entity number
     // other parameters should be already set up by CL_CalcViewValues
     if (cl.clientNum == -1 || cl.frame.clientNum == CLIENTNUM_NONE) {
         listener_entnum = -1;
     } else {
         listener_entnum = cl.frame.clientNum + 1;
     }
 #if USE_OPENAL
     if (s_started == SS_OAL) {
         OGG_Stream();
         AL_Update();
         return;
     }
 #endif
 #if USE_SNDDMA
     // rebuild scale tables if volume is modified
     if (s_volume->modified)
         S_InitScaletable();
     // update spatialization for dynamic sounds
     ch = channels;
     for (i = 0; i < s_numchannels; i++, ch++) {
         if (!ch->sfx)
             continue;
         if (ch->autosound) {
             // autosounds are regenerated fresh each frame
             memset(ch, 0, sizeof(*ch));
             continue;
         }
         S_Spatialize(ch);         // respatialize channel
         if (!ch->leftvol && !ch->rightvol) {
             memset(ch, 0, sizeof(*ch));
             continue;
         }
     }
     // add loopsounds
     S_AddLoopSounds();
     OGG_Stream();
 #ifdef _DEBUG
     //
     // debugging output
     //
     if (s_show->integer) {
         int total = 0;
         ch = channels;
         for (i = 0; i < s_numchannels; i++, ch++)
             if (ch->sfx && (ch->leftvol || ch->rightvol)) {
                 Com_Printf("%3i %3i %s\n", ch->leftvol, ch->rightvol, ch->sfx->name);
                 total++;
             }
         if (s_show->integer > 1 || total) {
             Com_Printf("----(%i)---- painted: %i\n", total, paintedtime);
         }
     }
 #endif
 // mix some sound
     DMA_Update();
 #endif
 }
Referenced by CL_Frame().
Variable Documentation
c_sound
const cmdreg_t c_sound[] static
Initial value:
= {
    { "stopsound", S_StopAllSounds },
    { "soundlist", S_SoundList_f },
    { "soundinfo", S_SoundInfo_f },
    { NULL }
}
Definition at line 126 of file main.c.
Referenced by S_Init(), and S_Shutdown().
channels
channel_t channels[MAX_CHANNELS]
Definition at line 29 of file main.c.
Referenced by AL_FindLoopingSound(), AL_PlayChannel(), AL_RawSamples(), AL_StopAllChannels(), AL_Update(), IMG_LOAD(), S_PaintChannels(), S_PickChannel(), S_RawSamples(), S_StopAllSounds(), and S_Update().
known_sfx
sfx_t known_sfx[MAX_SFX] static
Definition at line 50 of file main.c.
Referenced by S_AllocSfx(), S_EndRegistration(), S_FindName(), S_FreeAllSounds(), S_RegisterSexedSounds(), S_RegisterSound(), S_SfxForHandle(), and S_SoundList_f().
listener_entnum
int listener_entnum
Definition at line 39 of file main.c.
Referenced by AL_Spatialize(), CL_GetEntitySoundOrigin(), S_BuildSoundList(), S_PickChannel(), S_StartLocalSound(), S_StartLocalSound_(), and S_Update().
listener_forward
vec3_t listener_forward
Definition at line 36 of file main.c.
Referenced by AL_Update(), and CL_CalcViewValues().
listener_origin
vec3_t listener_origin
Definition at line 35 of file main.c.
Referenced by AL_AddLoopSounds(), AL_Spatialize(), AL_Update(), CL_CalcViewValues(), and CL_GetEntitySoundOrigin().
listener_right
vec3_t listener_right
Definition at line 37 of file main.c.
Referenced by CL_CalcViewValues().
listener_up
vec3_t listener_up
Definition at line 38 of file main.c.
Referenced by AL_Update(), and CL_CalcViewValues().
num_sfx
int num_sfx static
Definition at line 51 of file main.c.
Referenced by S_AllocSfx(), S_EndRegistration(), S_FindName(), S_FreeAllSounds(), S_Init(), S_RegisterSexedSounds(), S_SfxForHandle(), and S_SoundList_f().
paintedtime
int paintedtime
Definition at line 43 of file main.c.
Referenced by AL_AddLoopSounds(), AL_IssuePlaysounds(), AL_Update(), DMA_DriftBeginofs(), DMA_GetTime(), DMA_Update(), OGG_Stream(), S_Init(), S_IssuePlaysound(), S_PaintChannels(), S_PickChannel(), S_RawSamples(), S_StartSound(), S_Update(), TransferPaintBuffer(), TransferStereo(), TransferStereo16(), and WAVE_Submit().
s_active
qboolean s_active
Definition at line 33 of file main.c.
Referenced by AL_Update(), DMA_Activate(), S_Activate(), S_Shutdown(), and S_StartSound().
s_ambient
cvar_t* s_ambient
Definition at line 59 of file main.c.
Referenced by AL_AddLoopSounds(), S_BuildSoundList(), and S_Init().
s_auto_focus
cvar_t* s_auto_focus static
Definition at line 65 of file main.c.
Referenced by S_Activate(), S_Init(), and S_Shutdown().
s_enable
cvar_t* s_enable static
Definition at line 64 of file main.c.
Referenced by S_Init().
s_freeplays
playsound_t s_freeplays
Definition at line 55 of file main.c.
Referenced by S_AllocPlaysound(), S_FreePlaysound(), and S_StopAllSounds().
s_numchannels
int s_numchannels
Definition at line 30 of file main.c.
Referenced by AL_FindLoopingSound(), AL_Init(), AL_Shutdown(), AL_SoundInfo(), AL_StopAllChannels(), AL_Update(), DMA_Init(), DMA_Shutdown(), S_PaintChannels(), S_PickChannel(), and S_Update().
s_pendingplays
playsound_t s_pendingplays
Definition at line 56 of file main.c.
Referenced by AL_IssuePlaysounds(), S_PaintChannels(), S_StartSound(), and S_StopAllSounds().
s_playsounds
playsound_t s_playsounds[MAX_PLAYSOUNDS]
Definition at line 54 of file main.c.
Referenced by S_StopAllSounds().
s_registering
qboolean s_registering
Definition at line 41 of file main.c.
Referenced by S_BeginRegistration(), S_EndRegistration(), S_RegisterSexedSound(), and S_RegisterSound().
s_registration_sequence
int s_registration_sequence
Definition at line 27 of file main.c.
Referenced by S_BeginRegistration(), S_EndRegistration(), S_FindName(), S_Init(), and S_RegisterSexedSounds().
s_started
sndstarted_t s_started
Definition at line 32 of file main.c.
Referenced by OGG_PlayTrack(), OGG_Stop(), OGG_Stream(), OGG_TogglePlayback(), S_Activate(), S_EndRegistration(), S_FreeSound(), S_Init(), S_IssuePlaysound(), S_LoadSound(), S_PickChannel(), S_RawSamples(), S_RegisterSound(), S_Shutdown(), S_SoundInfo_f(), S_SoundList_f(), S_StartLocalSound(), S_StartLocalSound_(), S_StartSound(), S_StopAllSounds(), S_UnqueueRawSamples(), S_Update(), and SCR_PlayCinematic().
s_swapstereo
cvar_t* s_swapstereo static
Definition at line 66 of file main.c.
Referenced by S_Init().
s_volume
cvar_t* s_volume
Definition at line 58 of file main.c.
Referenced by AL_Update(), S_Init(), S_InitScaletable(), S_RawSamples(), and S_Update().