Quake II RTX doxygen: C:/entry/dev/Q2RTX/src/refresh/gl/draw.c File Reference
draw.c File Reference
#include "gl.h"
Macros
#define GL_StretchPic(x, y, w, h, s1, t1, s2, t2, color, image) _GL_StretchPic(x,y,w,h,s1,t1,s2,t2,color,(image)->texnum,(image)->flags)
#define DIV64 (1.0f / 64.0f)
Functions
static void _GL_StretchPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, uint32_t color, int texnum, int flags)
void GL_Blend (void)
void R_ClearColor_GL (void)
void R_SetAlpha_GL (float alpha)
void R_SetAlphaScale_GL (float alpha)
void R_SetColor_GL (uint32_t color)
void R_SetClipRect_GL (const clipRect_t *clip)
void R_SetScale_GL (float scale)
void R_DrawStretchPic_GL (int x, int y, int w, int h, qhandle_t pic)
void R_DrawPic_GL (int x, int y, qhandle_t pic)
void R_TileClear_GL (int x, int y, int w, int h, qhandle_t pic)
void R_DrawFill8_GL (int x, int y, int w, int h, int c)
void R_DrawFill32_GL (int x, int y, int w, int h, uint32_t color)
static void draw_char (int x, int y, int flags, int c, image_t *image)
void R_DrawChar_GL (int x, int y, int flags, int c, qhandle_t font)
int R_DrawString_GL (int x, int y, int flags, size_t maxlen, const char *s, qhandle_t font)
Variables
drawStatic_t draw
Macro Definition Documentation
DIV64
#define DIV64 (1.0f / 64.0f)
Definition at line 187 of file draw.c.
GL_StretchPic
#define GL_StretchPic (x, y, w, h, s1, t1, s2, t2, color, image) _GL_StretchPic(x,y,w,h,s1,t1,s2,t2,color,(image)->texnum,(image)->flags)
Definition at line 76 of file draw.c.
Function Documentation
_GL_StretchPic()
static void _GL_StretchPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, uint32_t color, int texnum, int flags) inline static
Definition at line 23 of file draw.c.
 {
     vec_t *dst_vert;
     uint32_t *dst_color;
     QGL_INDEX_TYPE *dst_indices;
     if (tess.numverts + 4 > TESS_MAX_VERTICES ||
         tess.numindices + 6 > TESS_MAX_INDICES ||
         (tess.numverts && tess.texnum[0] != texnum)) {
         GL_Flush2D();
     }
     tess.texnum[0] = texnum;
     dst_vert = tess.vertices + tess.numverts * 4;
     Vector4Set(dst_vert,      x,     y,     s1, t1);
     Vector4Set(dst_vert +  4, x + w, y,     s2, t1);
     Vector4Set(dst_vert +  8, x + w, y + h, s2, t2);
     Vector4Set(dst_vert + 12, x,     y + h, s1, t2);
     dst_color = (uint32_t *)tess.colors + tess.numverts;
     dst_color[0] = color;
     dst_color[1] = color;
     dst_color[2] = color;
     dst_color[3] = color;
     dst_indices = tess.indices + tess.numindices;
     dst_indices[0] = tess.numverts + 0;
     dst_indices[1] = tess.numverts + 2;
     dst_indices[2] = tess.numverts + 3;
     dst_indices[3] = tess.numverts + 0;
     dst_indices[4] = tess.numverts + 1;
     dst_indices[5] = tess.numverts + 2;
     if (flags & IF_TRANSPARENT) {
         if ((flags & IF_PALETTED) && draw.scale == 1) {
             tess.flags |= 1;
         } else {
             tess.flags |= 2;
         }
     }
     if ((color & U32_ALPHA) != U32_ALPHA) {
         tess.flags |= 2;
     }
     tess.numverts += 4;
     tess.numindices += 6;
 }
Referenced by GL_Blend(), R_DrawFill32_GL(), and R_DrawFill8_GL().
draw_char()
static void draw_char (int x, int y, int flags, int c, image_t * image) inline static
Definition at line 209 of file draw.c.
 {
     float s, t;
     if ((c & 127) == 32) {
         return;
     }
     if (flags & UI_ALTCOLOR) {
         c |= 0x80;
     }
     if (flags & UI_XORCOLOR) {
         c ^= 0x80;
     }
     s = (c & 15) * 0.0625f;
     t = (c >> 4) * 0.0625f;
     if (gl_fontshadow->integer > 0 && c != 0x83) {
         uint32_t black = MakeColor(0, 0, 0, draw.colors[0].u8[3]);
         GL_StretchPic(x + 1, y + 1, CHAR_WIDTH, CHAR_HEIGHT, s, t,
                       s + 0.0625f, t + 0.0625f, black, image);
         if (gl_fontshadow->integer > 1)
             GL_StretchPic(x + 2, y + 2, CHAR_WIDTH, CHAR_HEIGHT, s, t,
                           s + 0.0625f, t + 0.0625f, black, image);
     }
     GL_StretchPic(x, y, CHAR_WIDTH, CHAR_HEIGHT, s, t,
                   s + 0.0625f, t + 0.0625f, draw.colors[c >> 7].u32, image);
 }
Referenced by R_DrawChar_GL(), and R_DrawString_GL().
GL_Blend()
void GL_Blend (void)
Definition at line 79 of file draw.c.
 {
     color_t color;
     color.u8[0] = glr.fd.blend[0] * 255;
     color.u8[1] = glr.fd.blend[1] * 255;
     color.u8[2] = glr.fd.blend[2] * 255;
     color.u8[3] = glr.fd.blend[3] * 255;
     _GL_StretchPic(glr.fd.x, glr.fd.y, glr.fd.width, glr.fd.height, 0, 0, 1, 1,
                    color.u32, TEXNUM_WHITE, 0);
 }
Referenced by R_RenderFrame_GL().
R_ClearColor_GL()
void R_ClearColor_GL (void)
Definition at line 92 of file draw.c.
 {
     draw.colors[0].u32 = U32_WHITE;
     draw.colors[1].u32 = U32_WHITE;
 }
Referenced by R_RegisterFunctionsGL().
R_DrawChar_GL()
void R_DrawChar_GL (int x, int y, int flags, int c, qhandle_t font)
Definition at line 242 of file draw.c.
 {
     draw_char(x, y, flags, c & 255, IMG_ForHandle(font));
 }
Referenced by R_RegisterFunctionsGL().
R_DrawFill32_GL()
void R_DrawFill32_GL (int x, int y, int w, int h, uint32_t color)
Definition at line 202 of file draw.c.
 {
     if (!w || !h)
         return;
     _GL_StretchPic(x, y, w, h, 0, 0, 1, 1, color, TEXNUM_WHITE, 0);
 }
Referenced by R_RegisterFunctionsGL().
R_DrawFill8_GL()
void R_DrawFill8_GL (int x, int y, int w, int h, int c)
Definition at line 195 of file draw.c.
 {
     if (!w || !h)
         return;
     _GL_StretchPic(x, y, w, h, 0, 0, 1, 1, d_8to24table[c & 0xff], TEXNUM_WHITE, 0);
 }
Referenced by R_RegisterFunctionsGL().
R_DrawPic_GL()
void R_DrawPic_GL (int x, int y, qhandle_t pic)
Definition at line 179 of file draw.c.
 {
     image_t *image = IMG_ForHandle(pic);
     GL_StretchPic(x, y, image->width, image->height,
                   image->sl, image->tl, image->sh, image->th, draw.colors[0].u32, image);
 }
Referenced by R_RegisterFunctionsGL().
R_DrawStretchPic_GL()
void R_DrawStretchPic_GL (int x, int y, int w, int h, qhandle_t pic)
Definition at line 171 of file draw.c.
 {
     image_t *image = IMG_ForHandle(pic);
     GL_StretchPic(x, y, w, h, image->sl, image->tl, image->sh, image->th,
                   draw.colors[0].u32, image);
 }
Referenced by R_RegisterFunctionsGL().
R_DrawString_GL()
int R_DrawString_GL (int x, int y, int flags, size_t maxlen, const char * s, qhandle_t font)
Definition at line 247 of file draw.c.
 {
     image_t *image = IMG_ForHandle(font);
     while (maxlen-- && *s) {
         byte c = *s++;
         draw_char(x, y, flags, c, image);
         x += CHAR_WIDTH;
     }
     return x;
 }
Referenced by R_RegisterFunctionsGL().
R_SetAlpha_GL()
void R_SetAlpha_GL (float alpha)
Definition at line 98 of file draw.c.
 {
     draw.colors[0].u8[3] =
         draw.colors[1].u8[3] = alpha * 255;
 }
Referenced by R_RegisterFunctionsGL().
R_SetAlphaScale_GL()
void R_SetAlphaScale_GL (float alpha)
Definition at line 104 of file draw.c.
 {
     // nop - only used by the RTX renderer
 }
Referenced by R_RegisterFunctionsGL().
R_SetClipRect_GL()
void R_SetClipRect_GL (const clipRect_t * clip)
Definition at line 115 of file draw.c.
 {
     clipRect_t rc;
     float scale;
     GL_Flush2D();
     if (!clip) {
 clear:
         if (draw.scissor) {
             qglDisable(GL_SCISSOR_TEST);
             draw.scissor = qfalse;
         }
         return;
     }
     scale = 1 / draw.scale;
     rc.left = clip->left * scale;
     rc.top = clip->top * scale;
     rc.right = clip->right * scale;
     rc.bottom = clip->bottom * scale;
     if (rc.left < 0)
         rc.left = 0;
     if (rc.top < 0)
         rc.top = 0;
     if (rc.right > r_config.width)
         rc.right = r_config.width;
     if (rc.bottom > r_config.height)
         rc.bottom = r_config.height;
     if (rc.right < rc.left)
         goto clear;
     if (rc.bottom < rc.top)
         goto clear;
     qglEnable(GL_SCISSOR_TEST);
     qglScissor(rc.left, r_config.height - rc.bottom,
                rc.right - rc.left, rc.bottom - rc.top);
     draw.scissor = qtrue;
 }
Referenced by R_RegisterFunctionsGL().
R_SetColor_GL()
void R_SetColor_GL (uint32_t color)
Definition at line 109 of file draw.c.
 {
     draw.colors[0].u32 = color;
     draw.colors[1].u8[3] = draw.colors[0].u8[3];
 }
Referenced by R_RegisterFunctionsGL().
R_SetScale_GL()
void R_SetScale_GL (float scale)
Definition at line 157 of file draw.c.
 {
     if (draw.scale == scale) {
         return;
     }
     GL_Flush2D();
     GL_Ortho(0, Q_rint(r_config.width * scale),
              Q_rint(r_config.height * scale), 0, -1, 1);
     draw.scale = scale;
 }
Referenced by R_RegisterFunctionsGL().
R_TileClear_GL()
void R_TileClear_GL (int x, int y, int w, int h, qhandle_t pic)
Definition at line 189 of file draw.c.
 {
     GL_StretchPic(x, y, w, h, x * DIV64, y * DIV64,
                   (x + w) * DIV64, (y + h) * DIV64, U32_WHITE, IMG_ForHandle(pic));
 }
Referenced by R_RegisterFunctionsGL().
Variable Documentation
draw
drawStatic_t draw
Definition at line 21 of file draw.c.
Referenced by _GL_StretchPic(), draw_char(), enqueue_stretch_pic(), GL_Setup2D(), R_ClearColor(), R_ClearColor_GL(), R_ClearColor_RTX(), R_DrawFixedData(), R_DrawPic(), R_DrawPic_GL(), R_DrawStretchData(), R_DrawStretchPic(), R_DrawStretchPic_GL(), R_DrawStretchPic_RTX(), R_InitDraw(), R_SetAlpha(), R_SetAlpha_GL(), R_SetAlpha_RTX(), R_SetAlphaScale_RTX(), R_SetClipRect(), R_SetClipRect_GL(), R_SetColor(), R_SetColor_GL(), R_SetColor_RTX(), R_SetScale_GL(), R_SetScale_RTX(), and SCR_DrawLayout().