Quake II RTX doxygen: C:/entry/dev/Q2RTX/src/baseq2/m_boss2.c File Reference
m_boss2.c File Reference
#include "g_local.h"
#include "m_boss2.h"
Functions
void BossExplode (edict_t *self)
qboolean infront (edict_t *self, edict_t *other)
void boss2_search (edict_t *self)
void boss2_run (edict_t *self)
void boss2_stand (edict_t *self)
void boss2_dead (edict_t *self)
void boss2_attack (edict_t *self)
void boss2_attack_mg (edict_t *self)
void boss2_reattack_mg (edict_t *self)
void boss2_die (edict_t *self, edict_t *inflictor, edict_t *attacker, int damage, vec3_t point)
void Boss2Rocket (edict_t *self)
void boss2_firebullet_right (edict_t *self)
void boss2_firebullet_left (edict_t *self)
void Boss2MachineGun (edict_t *self)
void boss2_walk (edict_t *self)
void boss2_pain (edict_t *self, edict_t *other, float kick, int damage)
qboolean Boss2_CheckAttack (edict_t *self)
void SP_monster_boss2 (edict_t *self)
Variables
static int sound_pain1
static int sound_pain2
static int sound_pain3
static int sound_death
static int sound_search1
mframe_t boss2_frames_stand []
mmove_t boss2_move_stand = {FRAME_stand30, FRAME_stand50, boss2_frames_stand, NULL}
mframe_t boss2_frames_fidget []
mmove_t boss2_move_fidget = {FRAME_stand1, FRAME_stand30, boss2_frames_fidget, NULL}
mframe_t boss2_frames_walk []
mmove_t boss2_move_walk = {FRAME_walk1, FRAME_walk20, boss2_frames_walk, NULL}
mframe_t boss2_frames_run []
mmove_t boss2_move_run = {FRAME_walk1, FRAME_walk20, boss2_frames_run, NULL}
mframe_t boss2_frames_attack_pre_mg []
mmove_t boss2_move_attack_pre_mg = {FRAME_attack1, FRAME_attack9, boss2_frames_attack_pre_mg, NULL}
mframe_t boss2_frames_attack_mg []
mmove_t boss2_move_attack_mg = {FRAME_attack10, FRAME_attack15, boss2_frames_attack_mg, NULL}
mframe_t boss2_frames_attack_post_mg []
mmove_t boss2_move_attack_post_mg = {FRAME_attack16, FRAME_attack19, boss2_frames_attack_post_mg, boss2_run}
mframe_t boss2_frames_attack_rocket []
mmove_t boss2_move_attack_rocket = {FRAME_attack20, FRAME_attack40, boss2_frames_attack_rocket, boss2_run}
mframe_t boss2_frames_pain_heavy []
mmove_t boss2_move_pain_heavy = {FRAME_pain2, FRAME_pain19, boss2_frames_pain_heavy, boss2_run}
mframe_t boss2_frames_pain_light []
mmove_t boss2_move_pain_light = {FRAME_pain20, FRAME_pain23, boss2_frames_pain_light, boss2_run}
mframe_t boss2_frames_death []
mmove_t boss2_move_death = {FRAME_death2, FRAME_death50, boss2_frames_death, boss2_dead}
Function Documentation
boss2_attack()
void boss2_attack (edict_t * self)
Definition at line 419 of file m_boss2.c.
 {
     vec3_t  vec;
     float   range;
     VectorSubtract(self->enemy->s.origin, self->s.origin, vec);
     range = VectorLength(vec);
     if (range <= 125) {
         self->monsterinfo.currentmove = &boss2_move_attack_pre_mg;
     } else {
         if (random() <= 0.6)
             self->monsterinfo.currentmove = &boss2_move_attack_pre_mg;
         else
             self->monsterinfo.currentmove = &boss2_move_attack_rocket;
     }
 }
Referenced by SP_monster_boss2().
boss2_attack_mg()
void boss2_attack_mg (edict_t * self)
Definition at line 437 of file m_boss2.c.
 {
     self->monsterinfo.currentmove = &boss2_move_attack_mg;
 }
Boss2_CheckAttack()
qboolean Boss2_CheckAttack (edict_t * self)
Definition at line 518 of file m_boss2.c.
 {
     vec3_t  spot1, spot2;
     vec3_t  temp;
     float   chance;
     trace_t tr;
     int         enemy_range;
     float       enemy_yaw;
     if (self->enemy->health > 0) {
         // see if any entities are in the way of the shot
         VectorCopy(self->s.origin, spot1);
         spot1[2] += self->viewheight;
         VectorCopy(self->enemy->s.origin, spot2);
         spot2[2] += self->enemy->viewheight;
         tr = gi.trace(spot1, NULL, NULL, spot2, self, CONTENTS_SOLID | CONTENTS_MONSTER | CONTENTS_SLIME | CONTENTS_LAVA);
         // do we have a clear shot?
         if (tr.ent != self->enemy)
             return qfalse;
     }
     enemy_range = range(self, self->enemy);
     VectorSubtract(self->enemy->s.origin, self->s.origin, temp);
     enemy_yaw = vectoyaw(temp);
     self->ideal_yaw = enemy_yaw;
     // melee attack
     if (enemy_range == RANGE_MELEE) {
         if (self->monsterinfo.melee)
             self->monsterinfo.attack_state = AS_MELEE;
         else
             self->monsterinfo.attack_state = AS_MISSILE;
         return qtrue;
     }
 // missile attack
     if (!self->monsterinfo.attack)
         return qfalse;
     if (level.time < self->monsterinfo.attack_finished)
         return qfalse;
     if (enemy_range == RANGE_FAR)
         return qfalse;
     if (self->monsterinfo.aiflags & AI_STAND_GROUND) {
         chance = 0.4;
     } else if (enemy_range == RANGE_MELEE) {
         chance = 0.8;
     } else if (enemy_range == RANGE_NEAR) {
         chance = 0.8;
     } else if (enemy_range == RANGE_MID) {
         chance = 0.8;
     } else {
         return qfalse;
     }
     if (random() < chance) {
         self->monsterinfo.attack_state = AS_MISSILE;
         self->monsterinfo.attack_finished = level.time + 2 * random();
         return qtrue;
     }
     if (self->flags & FL_FLY) {
         if (random() < 0.3)
             self->monsterinfo.attack_state = AS_SLIDING;
         else
             self->monsterinfo.attack_state = AS_STRAIGHT;
     }
     return qfalse;
 }
Referenced by SP_monster_boss2().
boss2_dead()
void boss2_dead (edict_t * self)
Definition at line 476 of file m_boss2.c.
 {
     VectorSet(self->mins, -56, -56, 0);
     VectorSet(self->maxs, 56, 56, 80);
     self->movetype = MOVETYPE_TOSS;
     self->svflags |= SVF_DEADMONSTER;
     self->nextthink = 0;
     gi.linkentity(self);
 }
boss2_die()
void boss2_die (edict_t * self, edict_t * inflictor, edict_t * attacker, int damage, vec3_t point)
Definition at line 486 of file m_boss2.c.
 {
     gi.sound(self, CHAN_VOICE, sound_death, 1, ATTN_NONE, 0);
     self->deadflag = DEAD_DEAD;
     self->takedamage = DAMAGE_NO;
     self->count = 0;
     self->monsterinfo.currentmove = &boss2_move_death;
 #if 0
     int     n;
     self->s.sound = 0;
     // check for gib
     if (self->health <= self->gib_health) {
         gi.sound(self, CHAN_VOICE, gi.soundindex("misc/udeath.wav"), 1, ATTN_NORM, 0);
         for (n = 0; n < 2; n++)
             ThrowGib(self, "models/objects/gibs/bone/tris.md2", damage, GIB_ORGANIC);
         for (n = 0; n < 4; n++)
             ThrowGib(self, "models/objects/gibs/sm_meat/tris.md2", damage, GIB_ORGANIC);
         ThrowHead(self, "models/objects/gibs/head2/tris.md2", damage, GIB_ORGANIC);
         self->deadflag = DEAD_DEAD;
         return;
     }
     if (self->deadflag == DEAD_DEAD)
         return;
     self->deadflag = DEAD_DEAD;
     self->takedamage = DAMAGE_YES;
     self->monsterinfo.currentmove = &boss2_move_death;
 #endif
 }
Referenced by SP_monster_boss2().
boss2_firebullet_left()
void boss2_firebullet_left (edict_t * self)
Definition at line 111 of file m_boss2.c.
 {
     vec3_t  forward, right, target;
     vec3_t  start;
     AngleVectors(self->s.angles, forward, right, NULL);
     G_ProjectSource(self->s.origin, monster_flash_offset[MZ2_BOSS2_MACHINEGUN_L1], forward, right, start);
     VectorMA(self->enemy->s.origin, -0.2, self->enemy->velocity, target);
     target[2] += self->enemy->viewheight;
     VectorSubtract(target, start, forward);
     VectorNormalize(forward);
     monster_fire_bullet(self, start, forward, 6, 4, DEFAULT_BULLET_HSPREAD, DEFAULT_BULLET_VSPREAD, MZ2_BOSS2_MACHINEGUN_L1);
 }
Referenced by Boss2MachineGun().
boss2_firebullet_right()
void boss2_firebullet_right (edict_t * self)
Definition at line 95 of file m_boss2.c.
 {
     vec3_t  forward, right, target;
     vec3_t  start;
     AngleVectors(self->s.angles, forward, right, NULL);
     G_ProjectSource(self->s.origin, monster_flash_offset[MZ2_BOSS2_MACHINEGUN_R1], forward, right, start);
     VectorMA(self->enemy->s.origin, -0.2, self->enemy->velocity, target);
     target[2] += self->enemy->viewheight;
     VectorSubtract(target, start, forward);
     VectorNormalize(forward);
     monster_fire_bullet(self, start, forward, 6, 4, DEFAULT_BULLET_HSPREAD, DEFAULT_BULLET_VSPREAD, MZ2_BOSS2_MACHINEGUN_R1);
 }
Referenced by Boss2MachineGun().
boss2_pain()
void boss2_pain (edict_t * self, edict_t * other, float kick, int damage)
Definition at line 454 of file m_boss2.c.
 {
     if (self->health < (self->max_health / 2))
         self->s.skinnum = 1;
     if (level.time < self->pain_debounce_time)
         return;
     self->pain_debounce_time = level.time + 3;
 // American wanted these at no attenuation
     if (damage < 10) {
         gi.sound(self, CHAN_VOICE, sound_pain3, 1, ATTN_NONE, 0);
         self->monsterinfo.currentmove = &boss2_move_pain_light;
     } else if (damage < 30) {
         gi.sound(self, CHAN_VOICE, sound_pain1, 1, ATTN_NONE, 0);
         self->monsterinfo.currentmove = &boss2_move_pain_light;
     } else {
         gi.sound(self, CHAN_VOICE, sound_pain2, 1, ATTN_NONE, 0);
         self->monsterinfo.currentmove = &boss2_move_pain_heavy;
     }
 }
Referenced by SP_monster_boss2().
boss2_reattack_mg()
void boss2_reattack_mg (edict_t * self)
Definition at line 442 of file m_boss2.c.
 {
     if (infront(self, self->enemy))
         if (random() <= 0.7)
             self->monsterinfo.currentmove = &boss2_move_attack_mg;
         else
             self->monsterinfo.currentmove = &boss2_move_attack_post_mg;
     else
         self->monsterinfo.currentmove = &boss2_move_attack_post_mg;
 }
boss2_run()
void boss2_run (edict_t * self)
Definition at line 406 of file m_boss2.c.
 {
     if (self->monsterinfo.aiflags & AI_STAND_GROUND)
         self->monsterinfo.currentmove = &boss2_move_stand;
     else
         self->monsterinfo.currentmove = &boss2_move_run;
 }
Referenced by SP_monster_boss2().
boss2_search()
void boss2_search (edict_t * self)
Definition at line 39 of file m_boss2.c.
 {
     if (random() < 0.5)
         gi.sound(self, CHAN_VOICE, sound_search1, 1, ATTN_NONE, 0);
 }
Referenced by SP_monster_boss2().
boss2_stand()
void boss2_stand (edict_t * self)
Definition at line 401 of file m_boss2.c.
 {
     self->monsterinfo.currentmove = &boss2_move_stand;
 }
Referenced by SP_monster_boss2().
boss2_walk()
void boss2_walk (edict_t * self)
Definition at line 414 of file m_boss2.c.
 {
     self->monsterinfo.currentmove = &boss2_move_walk;
 }
Referenced by SP_monster_boss2().
Boss2MachineGun()
void Boss2MachineGun (edict_t * self)
Definition at line 128 of file m_boss2.c.
 {
     /*  vec3_t  forward, right;
         vec3_t  start;
         vec3_t  dir;
         vec3_t  vec;
         int     flash_number;
         AngleVectors (self->s.angles, forward, right, NULL);
         flash_number = MZ2_BOSS2_MACHINEGUN_1 + (self->s.frame - FRAME_attack10);
         G_ProjectSource (self->s.origin, monster_flash_offset[flash_number], forward, right, start);
         VectorCopy (self->enemy->s.origin, vec);
         vec[2] += self->enemy->viewheight;
         VectorSubtract (vec, start, dir);
         VectorNormalize (dir);
         monster_fire_bullet (self, start, dir, 3, 4, DEFAULT_BULLET_HSPREAD, DEFAULT_BULLET_VSPREAD, flash_number);
     */
     boss2_firebullet_left(self);
     boss2_firebullet_right(self);
 }
Boss2Rocket()
void Boss2Rocket (edict_t * self)
Definition at line 53 of file m_boss2.c.
 {
     vec3_t  forward, right;
     vec3_t  start;
     vec3_t  dir;
     vec3_t  vec;
     AngleVectors(self->s.angles, forward, right, NULL);
 //1
     G_ProjectSource(self->s.origin, monster_flash_offset[MZ2_BOSS2_ROCKET_1], forward, right, start);
     VectorCopy(self->enemy->s.origin, vec);
     vec[2] += self->enemy->viewheight;
     VectorSubtract(vec, start, dir);
     VectorNormalize(dir);
     monster_fire_rocket(self, start, dir, 50, 500, MZ2_BOSS2_ROCKET_1);
 //2
     G_ProjectSource(self->s.origin, monster_flash_offset[MZ2_BOSS2_ROCKET_2], forward, right, start);
     VectorCopy(self->enemy->s.origin, vec);
     vec[2] += self->enemy->viewheight;
     VectorSubtract(vec, start, dir);
     VectorNormalize(dir);
     monster_fire_rocket(self, start, dir, 50, 500, MZ2_BOSS2_ROCKET_2);
 //3
     G_ProjectSource(self->s.origin, monster_flash_offset[MZ2_BOSS2_ROCKET_3], forward, right, start);
     VectorCopy(self->enemy->s.origin, vec);
     vec[2] += self->enemy->viewheight;
     VectorSubtract(vec, start, dir);
     VectorNormalize(dir);
     monster_fire_rocket(self, start, dir, 50, 500, MZ2_BOSS2_ROCKET_3);
 //4
     G_ProjectSource(self->s.origin, monster_flash_offset[MZ2_BOSS2_ROCKET_4], forward, right, start);
     VectorCopy(self->enemy->s.origin, vec);
     vec[2] += self->enemy->viewheight;
     VectorSubtract(vec, start, dir);
     VectorNormalize(dir);
     monster_fire_rocket(self, start, dir, 50, 500, MZ2_BOSS2_ROCKET_4);
 }
BossExplode()
void BossExplode (edict_t * self)
Definition at line 569 of file m_supertank.c.
 {
     vec3_t  org;
     int     n;
     self->think = BossExplode;
     VectorCopy(self->s.origin, org);
     org[2] += 24 + (rand() & 15);
     switch (self->count++) {
     case 0:
         org[0] -= 24;
         org[1] -= 24;
         break;
     case 1:
         org[0] += 24;
         org[1] += 24;
         break;
     case 2:
         org[0] += 24;
         org[1] -= 24;
         break;
     case 3:
         org[0] -= 24;
         org[1] += 24;
         break;
     case 4:
         org[0] -= 48;
         org[1] -= 48;
         break;
     case 5:
         org[0] += 48;
         org[1] += 48;
         break;
     case 6:
         org[0] -= 48;
         org[1] += 48;
         break;
     case 7:
         org[0] += 48;
         org[1] -= 48;
         break;
     case 8:
         self->s.sound = 0;
         for (n = 0; n < 4; n++)
             ThrowGib(self, "models/objects/gibs/sm_meat/tris.md2", 500, GIB_ORGANIC);
         for (n = 0; n < 8; n++)
             ThrowGib(self, "models/objects/gibs/sm_metal/tris.md2", 500, GIB_METALLIC);
         ThrowGib(self, "models/objects/gibs/chest/tris.md2", 500, GIB_ORGANIC);
         ThrowHead(self, "models/objects/gibs/gear/tris.md2", 500, GIB_METALLIC);
         self->deadflag = DEAD_DEAD;
         return;
     }
     gi.WriteByte(svc_temp_entity);
     gi.WriteByte(TE_EXPLOSION1);
     gi.WritePosition(org);
     gi.multicast(self->s.origin, MULTICAST_PVS);
     self->nextthink = level.time + 0.1;
 }
infront()
qboolean infront (edict_t * self, edict_t * other)
Definition at line 293 of file g_ai.c.
 {
     vec3_t  vec;
     float   dot;
     vec3_t  forward;
     AngleVectors(self->s.angles, forward, NULL, NULL);
     VectorSubtract(other->s.origin, self->s.origin, vec);
     VectorNormalize(vec);
     dot = DotProduct(vec, forward);
     if (dot > 0.3)
         return qtrue;
     return qfalse;
 }
Referenced by boss2_reattack_mg(), check_dodge(), FindTarget(), and GL_CullLocalBox().
SP_monster_boss2()
void SP_monster_boss2 (edict_t * self)
Definition at line 599 of file m_boss2.c.
 {
     if (deathmatch->value) {
         G_FreeEdict(self);
         return;
     }
     sound_pain1 = gi.soundindex("bosshovr/bhvpain1.wav");
     sound_pain2 = gi.soundindex("bosshovr/bhvpain2.wav");
     sound_pain3 = gi.soundindex("bosshovr/bhvpain3.wav");
     sound_death = gi.soundindex("bosshovr/bhvdeth1.wav");
     sound_search1 = gi.soundindex("bosshovr/bhvunqv1.wav");
     self->s.sound = gi.soundindex("bosshovr/bhvengn1.wav");
     self->movetype = MOVETYPE_STEP;
     self->solid = SOLID_BBOX;
     self->s.modelindex = gi.modelindex("models/monsters/boss2/tris.md2");
     VectorSet(self->mins, -56, -56, 0);
     VectorSet(self->maxs, 56, 56, 80);
     self->health = 2000;
     self->gib_health = -200;
     self->mass = 1000;
     self->flags |= FL_IMMUNE_LASER;
     self->pain = boss2_pain;
     self->die = boss2_die;
     self->monsterinfo.stand = boss2_stand;
     self->monsterinfo.walk = boss2_walk;
     self->monsterinfo.run = boss2_run;
     self->monsterinfo.attack = boss2_attack;
     self->monsterinfo.search = boss2_search;
     self->monsterinfo.checkattack = Boss2_CheckAttack;
     gi.linkentity(self);
     self->monsterinfo.currentmove = &boss2_move_stand;
     self->monsterinfo.scale = MODEL_SCALE;
     flymonster_start(self);
 }
Variable Documentation
boss2_frames_attack_mg
mframe_t boss2_frames_attack_mg[]
Initial value:
= {
    { ai_charge,  1,  Boss2MachineGun },
    { ai_charge,  1,  Boss2MachineGun },
    { ai_charge,  1,  Boss2MachineGun },
    { ai_charge,  1,  Boss2MachineGun },
    { ai_charge,  1,  Boss2MachineGun },
    { ai_charge,  1,  boss2_reattack_mg }
}
Definition at line 275 of file m_boss2.c.
boss2_frames_attack_post_mg
mframe_t boss2_frames_attack_post_mg[]
Initial value:
= {
    { ai_charge,  1,  NULL },
    { ai_charge,  1,  NULL },
    { ai_charge,  1,  NULL },
    { ai_charge,  1,  NULL }
}
Definition at line 285 of file m_boss2.c.
boss2_frames_attack_pre_mg
mframe_t boss2_frames_attack_pre_mg[]
Initial value:
= {
    { ai_charge,  1,  NULL },
    { ai_charge,  1,  NULL },
    { ai_charge,  1,  NULL },
    { ai_charge,  1,  NULL },
    { ai_charge,  1,  NULL },
    { ai_charge,  1,  NULL },
    { ai_charge,  1,  NULL },
    { ai_charge,  1,  NULL },
    { ai_charge,  1,  boss2_attack_mg }
}
Definition at line 260 of file m_boss2.c.
boss2_frames_attack_rocket
mframe_t boss2_frames_attack_rocket[]
Initial value:
= {
    { ai_charge,  1,  NULL },
    { ai_charge,  1,  NULL },
    { ai_charge,  1,  NULL },
    { ai_charge,  1,  NULL },
    { ai_charge,  1,  NULL },
    { ai_charge,  1,  NULL },
    { ai_charge,  1,  NULL },
    { ai_charge,  1,  NULL },
    { ai_charge,  1,  NULL },
    { ai_charge,  1,  NULL },
    { ai_charge,  1,  NULL },
    { ai_charge,  1,  NULL },
    { ai_move,    -20,    Boss2Rocket },
    { ai_charge,  1,  NULL },
    { ai_charge,  1,  NULL },
    { ai_charge,  1,  NULL },
    { ai_charge,  1,  NULL },
    { ai_charge,  1,  NULL },
    { ai_charge,  1,  NULL },
    { ai_charge,  1,  NULL },
    { ai_charge,  1,  NULL }
}
Definition at line 293 of file m_boss2.c.
boss2_frames_death
mframe_t boss2_frames_death[]
Definition at line 348 of file m_boss2.c.
boss2_frames_fidget
mframe_t boss2_frames_fidget[]
Definition at line 177 of file m_boss2.c.
boss2_frames_pain_heavy
mframe_t boss2_frames_pain_heavy[]
Initial value:
= {
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL }
}
Definition at line 318 of file m_boss2.c.
boss2_frames_pain_light
mframe_t boss2_frames_pain_light[]
Initial value:
= {
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL }
}
Definition at line 340 of file m_boss2.c.
boss2_frames_run
mframe_t boss2_frames_run[]
Initial value:
= {
    { ai_run, 8,  NULL },
    { ai_run, 8,  NULL },
    { ai_run, 8,  NULL },
    { ai_run, 8,  NULL },
    { ai_run, 8,  NULL },
    { ai_run, 8,  NULL },
    { ai_run, 8,  NULL },
    { ai_run, 8,  NULL },
    { ai_run, 8,  NULL },
    { ai_run, 8,  NULL },
    { ai_run, 8,  NULL },
    { ai_run, 8,  NULL },
    { ai_run, 8,  NULL },
    { ai_run, 8,  NULL },
    { ai_run, 8,  NULL },
    { ai_run, 8,  NULL },
    { ai_run, 8,  NULL },
    { ai_run, 8,  NULL },
    { ai_run, 8,  NULL },
    { ai_run, 8,  NULL }
}
Definition at line 236 of file m_boss2.c.
boss2_frames_stand
mframe_t boss2_frames_stand[]
Initial value:
= {
    { ai_stand, 0, NULL },
    { ai_stand, 0, NULL },
    { ai_stand, 0, NULL },
    { ai_stand, 0, NULL },
    { ai_stand, 0, NULL },
    { ai_stand, 0, NULL },
    { ai_stand, 0, NULL },
    { ai_stand, 0, NULL },
    { ai_stand, 0, NULL },
    { ai_stand, 0, NULL },
    { ai_stand, 0, NULL },
    { ai_stand, 0, NULL },
    { ai_stand, 0, NULL },
    { ai_stand, 0, NULL },
    { ai_stand, 0, NULL },
    { ai_stand, 0, NULL },
    { ai_stand, 0, NULL },
    { ai_stand, 0, NULL },
    { ai_stand, 0, NULL },
    { ai_stand, 0, NULL },
    { ai_stand, 0, NULL }
}
Definition at line 152 of file m_boss2.c.
boss2_frames_walk
mframe_t boss2_frames_walk[]
Initial value:
= {
    { ai_walk,    8,  NULL },
    { ai_walk,    8,  NULL },
    { ai_walk,    8,  NULL },
    { ai_walk,    8,  NULL },
    { ai_walk,    8,  NULL },
    { ai_walk,    8,  NULL },
    { ai_walk,    8,  NULL },
    { ai_walk,    8,  NULL },
    { ai_walk,    8,  NULL },
    { ai_walk,    8,  NULL },
    { ai_walk,    8,  NULL },
    { ai_walk,    8,  NULL },
    { ai_walk,    8,  NULL },
    { ai_walk,    8,  NULL },
    { ai_walk,    8,  NULL },
    { ai_walk,    8,  NULL },
    { ai_walk,    8,  NULL },
    { ai_walk,    8,  NULL },
    { ai_walk,    8,  NULL },
    { ai_walk,    8,  NULL }
}
Definition at line 211 of file m_boss2.c.
boss2_move_attack_mg
mmove_t boss2_move_attack_mg = {FRAME_attack10, FRAME_attack15, boss2_frames_attack_mg, NULL}
Definition at line 283 of file m_boss2.c.
Referenced by boss2_attack_mg(), and boss2_reattack_mg().
boss2_move_attack_post_mg
mmove_t boss2_move_attack_post_mg = {FRAME_attack16, FRAME_attack19, boss2_frames_attack_post_mg, boss2_run}
Definition at line 291 of file m_boss2.c.
Referenced by boss2_reattack_mg().
boss2_move_attack_pre_mg
mmove_t boss2_move_attack_pre_mg = {FRAME_attack1, FRAME_attack9, boss2_frames_attack_pre_mg, NULL}
Definition at line 271 of file m_boss2.c.
Referenced by boss2_attack().
boss2_move_attack_rocket
mmove_t boss2_move_attack_rocket = {FRAME_attack20, FRAME_attack40, boss2_frames_attack_rocket, boss2_run}
Definition at line 316 of file m_boss2.c.
Referenced by boss2_attack().
boss2_move_death
mmove_t boss2_move_death = {FRAME_death2, FRAME_death50, boss2_frames_death, boss2_dead}
Definition at line 399 of file m_boss2.c.
Referenced by boss2_die().
boss2_move_fidget
mmove_t boss2_move_fidget = {FRAME_stand1, FRAME_stand30, boss2_frames_fidget, NULL}
Definition at line 209 of file m_boss2.c.
boss2_move_pain_heavy
mmove_t boss2_move_pain_heavy = {FRAME_pain2, FRAME_pain19, boss2_frames_pain_heavy, boss2_run}
Definition at line 338 of file m_boss2.c.
Referenced by boss2_pain().
boss2_move_pain_light
mmove_t boss2_move_pain_light = {FRAME_pain20, FRAME_pain23, boss2_frames_pain_light, boss2_run}
Definition at line 346 of file m_boss2.c.
Referenced by boss2_pain().
boss2_move_run
mmove_t boss2_move_run = {FRAME_walk1, FRAME_walk20, boss2_frames_run, NULL}
Definition at line 258 of file m_boss2.c.
Referenced by boss2_run().
boss2_move_stand
mmove_t boss2_move_stand = {FRAME_stand30, FRAME_stand50, boss2_frames_stand, NULL}
Definition at line 175 of file m_boss2.c.
Referenced by boss2_run(), boss2_stand(), and SP_monster_boss2().
boss2_move_walk
mmove_t boss2_move_walk = {FRAME_walk1, FRAME_walk20, boss2_frames_walk, NULL}
Definition at line 233 of file m_boss2.c.
Referenced by boss2_walk().
sound_death
int sound_death static
Definition at line 36 of file m_boss2.c.
Referenced by boss2_die(), and SP_monster_boss2().
sound_pain1
int sound_pain1 static
Definition at line 33 of file m_boss2.c.
Referenced by boss2_pain(), and SP_monster_boss2().
sound_pain2
int sound_pain2 static
Definition at line 34 of file m_boss2.c.
Referenced by boss2_pain(), and SP_monster_boss2().
sound_pain3
int sound_pain3 static
Definition at line 35 of file m_boss2.c.
Referenced by boss2_pain(), and SP_monster_boss2().
sound_search1
int sound_search1 static
Definition at line 37 of file m_boss2.c.
Referenced by boss2_search(), and SP_monster_boss2().