Quake II RTX doxygen: C:/entry/dev/Q2RTX/src/common/mdfour.c File Reference
mdfour.c File Reference
#include "shared/shared.h"
#include "common/mdfour.h"
Macros
#define F(X, Y, Z) (((X)&(Y)) | ((~(X))&(Z)))
#define G(X, Y, Z) (((X)&(Y)) | ((X)&(Z)) | ((Y)&(Z)))
#define H(X, Y, Z) ((X)^(Y)^(Z))
#define lshift(x, s) (((x)<<(s)) | ((x)>>(32-(s))))
#define ROUND1(a, b, c, d, k, s) a = lshift(a + F(b,c,d) + X[k], s)
#define ROUND2(a, b, c, d, k, s) a = lshift(a + G(b,c,d) + X[k] + 0x5A827999,s)
#define ROUND3(a, b, c, d, k, s) a = lshift(a + H(b,c,d) + X[k] + 0x6ED9EBA1,s)
Functions
static void mdfour64 (uint32_t *M)
static void copy64 (uint32_t *M, uint8_t *in)
static void copy4 (uint8_t *out, uint32_t x)
void mdfour_begin (struct mdfour *md)
static void mdfour_tail (uint8_t *in, size_t n)
void mdfour_update (struct mdfour *md, uint8_t *in, size_t n)
void mdfour_result (struct mdfour *md, uint8_t *out)
uint32_t Com_BlockChecksum (void *buffer, size_t len)
Variables
static struct mdfour * m
Macro Definition Documentation
F
#define F (X, Y, Z) (((X)&(Y)) | ((~(X))&(Z)))
Definition at line 34 of file mdfour.c.
G
#define G (X, Y, Z) (((X)&(Y)) | ((X)&(Z)) | ((Y)&(Z)))
Definition at line 35 of file mdfour.c.
H
#define H (X, Y, Z) ((X)^(Y)^(Z))
Definition at line 36 of file mdfour.c.
lshift
#define lshift (x, s) (((x)<<(s)) | ((x)>>(32-(s))))
Definition at line 40 of file mdfour.c.
ROUND1
#define ROUND1 (a, b, c, d, k, s) a = lshift(a + F(b,c,d) + X[k], s)
Definition at line 43 of file mdfour.c.
ROUND2
#define ROUND2 (a, b, c, d, k, s) a = lshift(a + G(b,c,d) + X[k] + 0x5A827999,s)
Definition at line 44 of file mdfour.c.
ROUND3
#define ROUND3 (a, b, c, d, k, s) a = lshift(a + H(b,c,d) + X[k] + 0x6ED9EBA1,s)
Definition at line 45 of file mdfour.c.
Function Documentation
Com_BlockChecksum()
uint32_t Com_BlockChecksum (void * buffer, size_t len)
Definition at line 187 of file mdfour.c.
 {
     uint32_t digest[4];
     uint32_t val;
     struct mdfour md;
     mdfour_begin(&md);
     mdfour_update(&md, (uint8_t *)buffer, len);
     mdfour_result(&md, (uint8_t *)digest);
     val = digest[0] ^ digest[1] ^ digest[2] ^ digest[3];
     return val;
 }
Referenced by BSP_Load().
copy4()
static void copy4 (uint8_t * out, uint32_t x) static
Definition at line 110 of file mdfour.c.
 {
     out[0] = x & 0xFF;
     out[1] = (x >> 8) & 0xFF;
     out[2] = (x >> 16) & 0xFF;
     out[3] = (x >> 24) & 0xFF;
 }
Referenced by mdfour_result(), and mdfour_tail().
copy64()
static void copy64 (uint32_t * M, uint8_t * in) static
Definition at line 101 of file mdfour.c.
 {
     int i;
     for (i = 0; i < 16; i++)
         M[i] = (in[i * 4 + 3] << 24) | (in[i * 4 + 2] << 16) |
                (in[i * 4 + 1] << 8) | (in[i * 4 + 0] << 0);
 }
Referenced by mdfour_tail(), and mdfour_update().
mdfour64()
static void mdfour64 (uint32_t * M) static
Definition at line 48 of file mdfour.c.
 {
     int j;
     uint32_t AA, BB, CC, DD;
     uint32_t X[16];
     uint32_t A, B, C, D;
     for (j = 0; j < 16; j++)
         X[j] = M[j];
     A = m->A; B = m->B; C = m->C; D = m->D;
     AA = A; BB = B; CC = C; DD = D;
     ROUND1(A, B, C, D,  0,  3);  ROUND1(D, A, B, C,  1,  7);
     ROUND1(C, D, A, B,  2, 11);  ROUND1(B, C, D, A,  3, 19);
     ROUND1(A, B, C, D,  4,  3);  ROUND1(D, A, B, C,  5,  7);
     ROUND1(C, D, A, B,  6, 11);  ROUND1(B, C, D, A,  7, 19);
     ROUND1(A, B, C, D,  8,  3);  ROUND1(D, A, B, C,  9,  7);
     ROUND1(C, D, A, B, 10, 11);  ROUND1(B, C, D, A, 11, 19);
     ROUND1(A, B, C, D, 12,  3);  ROUND1(D, A, B, C, 13,  7);
     ROUND1(C, D, A, B, 14, 11);  ROUND1(B, C, D, A, 15, 19);
     ROUND2(A, B, C, D,  0,  3);  ROUND2(D, A, B, C,  4,  5);
     ROUND2(C, D, A, B,  8,  9);  ROUND2(B, C, D, A, 12, 13);
     ROUND2(A, B, C, D,  1,  3);  ROUND2(D, A, B, C,  5,  5);
     ROUND2(C, D, A, B,  9,  9);  ROUND2(B, C, D, A, 13, 13);
     ROUND2(A, B, C, D,  2,  3);  ROUND2(D, A, B, C,  6,  5);
     ROUND2(C, D, A, B, 10,  9);  ROUND2(B, C, D, A, 14, 13);
     ROUND2(A, B, C, D,  3,  3);  ROUND2(D, A, B, C,  7,  5);
     ROUND2(C, D, A, B, 11,  9);  ROUND2(B, C, D, A, 15, 13);
     ROUND3(A, B, C, D,  0,  3);  ROUND3(D, A, B, C,  8,  9);
     ROUND3(C, D, A, B,  4, 11);  ROUND3(B, C, D, A, 12, 15);
     ROUND3(A, B, C, D,  2,  3);  ROUND3(D, A, B, C, 10,  9);
     ROUND3(C, D, A, B,  6, 11);  ROUND3(B, C, D, A, 14, 15);
     ROUND3(A, B, C, D,  1,  3);  ROUND3(D, A, B, C,  9,  9);
     ROUND3(C, D, A, B,  5, 11);  ROUND3(B, C, D, A, 13, 15);
     ROUND3(A, B, C, D,  3,  3);  ROUND3(D, A, B, C, 11,  9);
     ROUND3(C, D, A, B,  7, 11);  ROUND3(B, C, D, A, 15, 15);
     A += AA; B += BB; C += CC; D += DD;
 #ifdef LARGE_INT32
     A &= 0xFFFFFFFF; B &= 0xFFFFFFFF;
     C &= 0xFFFFFFFF; D &= 0xFFFFFFFF;
 #endif
     for (j = 0; j < 16; j++)
         X[j] = 0;
     m->A = A; m->B = B; m->C = C; m->D = D;
 }
Referenced by mdfour_tail(), and mdfour_update().
mdfour_begin()
void mdfour_begin (struct mdfour * md)
Definition at line 118 of file mdfour.c.
 {
     md->A = 0x67452301;
     md->B = 0xefcdab89;
     md->C = 0x98badcfe;
     md->D = 0x10325476;
     md->totalN = 0;
 }
Referenced by CalcHash(), and Com_BlockChecksum().
mdfour_result()
void mdfour_result (struct mdfour * md, uint8_t * out)
Definition at line 175 of file mdfour.c.
 {
     m = md;
     copy4(out, m->A);
     copy4(out + 4, m->B);
     copy4(out + 8, m->C);
     copy4(out + 12, m->D);
 }
Referenced by CalcHash(), and Com_BlockChecksum().
mdfour_tail()
static void mdfour_tail (uint8_t * in, size_t n) static
Definition at line 128 of file mdfour.c.
 {
     uint8_t buf[128];
     uint32_t M[16];
     uint32_t b;
     m->totalN += n;
     b = m->totalN * 8;
     memset(buf, 0, 128);
     if (n) memcpy(buf, in, n);
     buf[n] = 0x80;
     if (n <= 55) {
         copy4(buf + 56, b);
         copy64(M, buf);
         mdfour64(M);
     } else {
         copy4(buf + 120, b);
         copy64(M, buf);
         mdfour64(M);
         copy64(M, buf + 64);
         mdfour64(M);
     }
 }
Referenced by mdfour_update().
mdfour_update()
void mdfour_update (struct mdfour * md, uint8_t * in, size_t n)
Definition at line 155 of file mdfour.c.
 {
     uint32_t M[16];
     m = md;
     if (n == 0) mdfour_tail(in, n);
     while (n >= 64) {
         copy64(M, in);
         mdfour64(M);
         in += 64;
         n -= 64;
         m->totalN += 64;
     }
     mdfour_tail(in, n);
 }
Referenced by CalcHash(), and Com_BlockChecksum().
Variable Documentation
m
struct mdfour* m static
Definition at line 32 of file mdfour.c.
Referenced by Cmd_Macro_g(), inverse(), mdfour64(), mdfour_result(), mdfour_tail(), mdfour_update(), Menu_AdjustCursor(), Menu_DefaultKey(), Menu_ItemAtCursor(), Prompt_CompleteHistory(), R_BeginRegistration_RTX(), R_CreateNotexture(), resolve_masters(), sample_polygonal_lights(), setup_color(), StringToFilter(), SV_FilterPacket(), SV_ListMasters_f(), SV_MasterHeartbeat(), SV_MasterShutdown(), SV_SetMaster_f(), SVC_Ack(), and vkpt_vertex_buffer_upload_models_to_staging().