Quake II RTX doxygen: C:/entry/dev/Q2RTX/src/common/net/unix.h File Reference
unix.h File Reference
Functions
static const char * os_error_string (int err)
static qboolean process_error_queue (qsocket_t sock, const netadr_t *to)
static ssize_t os_udp_recv (qsocket_t sock, void *data, size_t len, netadr_t *from)
static ssize_t os_udp_send (qsocket_t sock, const void *data, size_t len, const netadr_t *to)
static neterr_t os_get_error (void)
static ssize_t os_recv (qsocket_t sock, void *data, size_t len, int flags)
static ssize_t os_send (qsocket_t sock, const void *data, size_t len, int flags)
static neterr_t os_listen (qsocket_t sock, int backlog)
static neterr_t os_accept (qsocket_t sock, qsocket_t *newsock, netadr_t *from)
static neterr_t os_connect (qsocket_t sock, const netadr_t *to)
static neterr_t os_make_nonblock (qsocket_t sock, int val)
static neterr_t os_setsockopt (qsocket_t sock, int level, int name, int val)
static neterr_t os_getsockopt (qsocket_t sock, int level, int name, int *val)
static neterr_t os_bind (qsocket_t sock, const struct sockaddr *addr, size_t addrlen)
static neterr_t os_getsockname (qsocket_t sock, netadr_t *name)
static void os_closesocket (qsocket_t sock)
static qsocket_t os_socket (int domain, int type, int protocol)
static ioentry_t * _os_get_io (qsocket_t fd, const char *func)
static ioentry_t * os_add_io (qsocket_t fd)
static ioentry_t * os_get_io (qsocket_t fd)
static qsocket_t os_get_fd (ioentry_t *e)
static int os_select (int nfds, fd_set *rfds, fd_set *wfds, fd_set *efds, struct timeval *tv)
static void os_net_init (void)
static void os_net_shutdown (void)
Function Documentation
_os_get_io()
static ioentry_t* _os_get_io (qsocket_t fd, const char * func) static
Definition at line 319 of file unix.h.
 {
     if (fd < 0 || fd >= FD_SETSIZE)
         Com_Error(ERR_FATAL, "%s: fd out of range: %d", func, fd);
     return &io_entries[fd];
 }
Referenced by os_add_io(), and os_get_io().
os_accept()
static neterr_t os_accept (qsocket_t sock, qsocket_t * newsock, netadr_t * from) static
Definition at line 205 of file unix.h.
 {
     struct sockaddr_storage addr;
     socklen_t addrlen;
     int s;
     memset(&addr, 0, sizeof(addr));
     addrlen = sizeof(addr);
     s = accept(sock, (struct sockaddr *)&addr, &addrlen);
     NET_SockadrToNetadr(&addr, from);
     if (s == -1) {
         *newsock = -1;
         return os_get_error();
     }
     *newsock = s;
     return NET_OK;
 }
Referenced by NET_AcceptSocket().
os_add_io()
static ioentry_t* os_add_io (qsocket_t fd) static
Definition at line 327 of file unix.h.
 {
     if (fd >= io_numfds) {
         io_numfds = fd + 1;
     }
     return _os_get_io(fd, __func__);
 }
Referenced by NET_AddFd().
os_bind()
static neterr_t os_bind (qsocket_t sock, const struct sockaddr * addr, size_t addrlen) static
Definition at line 276 of file unix.h.
 {
     if (bind(sock, addr, addrlen) == -1) {
         net_error = errno;
         return NET_ERROR;
     }
     return NET_OK;
 }
Referenced by TCP_OpenSocket(), and UDP_OpenSocket().
os_closesocket()
static void os_closesocket (qsocket_t sock) static
Definition at line 302 of file unix.h.
 {
     close(sock);
 }
Referenced by NET_AcceptSocket(), NET_CloseStream(), NET_Config(), NET_Connect(), NET_EnableIP6(), NET_Listen4(), NET_Listen6(), TCP_OpenSocket(), and UDP_OpenSocket().
os_connect()
static neterr_t os_connect (qsocket_t sock, const netadr_t * to) static
Definition at line 226 of file unix.h.
 {
     struct sockaddr_storage addr;
     socklen_t addrlen;
     addrlen = NET_NetadrToSockadr(to, &addr);
     if (connect(sock, (struct sockaddr *)&addr, addrlen) == -1) {
         net_error = errno;
         if (net_error == EINPROGRESS)
             return NET_OK;
         return NET_ERROR;
     }
     return NET_OK;
 }
Referenced by NET_Connect().
os_error_string()
static const char* os_error_string (int err) static
Definition at line 23 of file unix.h.
 {
     return strerror(err);
 }
Referenced by NET_ErrorString().
os_get_error()
static neterr_t os_get_error (void) static
Definition at line 166 of file unix.h.
 {
     net_error = errno;
     if (net_error == EWOULDBLOCK)
         return NET_AGAIN;
     return NET_ERROR;
 }
Referenced by os_accept(), os_recv(), and os_send().
os_get_fd()
static qsocket_t os_get_fd (ioentry_t * e) static
Definition at line 341 of file unix.h.
 {
     return e - io_entries;
 }
Referenced by NET_Sleep().
os_get_io()
static ioentry_t* os_get_io (qsocket_t fd) static
Definition at line 336 of file unix.h.
 {
     return _os_get_io(fd, __func__);
 }
Referenced by NET_AcceptSocket(), NET_GetUdpPackets(), NET_RemoveFd(), NET_RunConnect(), NET_RunStream(), and NET_UpdateStream().
os_getsockname()
static neterr_t os_getsockname (qsocket_t sock, netadr_t * name) static
Definition at line 286 of file unix.h.
 {
     struct sockaddr_storage addr;
     socklen_t addrlen;
     memset(&addr, 0, sizeof(addr));
     addrlen = sizeof(addr);
     if (getsockname(sock, (struct sockaddr *)&addr, &addrlen) == -1) {
         net_error = errno;
         return NET_ERROR;
     }
     NET_SockadrToNetadr(&addr, name);
     return NET_OK;
 }
Referenced by dump_socket(), and NET_GetAddress().
os_getsockopt()
static neterr_t os_getsockopt (qsocket_t sock, int level, int name, int * val) static
Definition at line 264 of file unix.h.
 {
     socklen_t _optlen = sizeof(*val);
     if (getsockopt(sock, level, name, val, &_optlen) == -1) {
         net_error = errno;
         return NET_ERROR;
     }
     return NET_OK;
 }
Referenced by NET_RunConnect().
os_listen()
static neterr_t os_listen (qsocket_t sock, int backlog) static
Definition at line 195 of file unix.h.
 {
     if (listen(sock, backlog) == -1) {
         net_error = errno;
         return NET_ERROR;
     }
     return NET_OK;
 }
Referenced by NET_Listen4(), and NET_Listen6().
os_make_nonblock()
static neterr_t os_make_nonblock (qsocket_t sock, int val) static
Definition at line 244 of file unix.h.
 {
     if (ioctl(sock, FIONBIO, &val) == -1) {
         net_error = errno;
         return NET_ERROR;
     }
     return NET_OK;
 }
Referenced by NET_AcceptSocket(), TCP_OpenSocket(), and UDP_OpenSocket().
os_net_init()
static void os_net_init (void) static
Definition at line 360 of file unix.h.
 {
 }
Referenced by NET_Init().
os_net_shutdown()
static void os_net_shutdown (void) static
Definition at line 364 of file unix.h.
 {
 }
Referenced by NET_Shutdown().
os_recv()
static ssize_t os_recv (qsocket_t sock, void * data, size_t len, int flags) static
Definition at line 175 of file unix.h.
 {
     ssize_t ret = recv(sock, data, len, flags);
     if (ret == -1)
         return os_get_error();
     return ret;
 }
Referenced by NET_RunStream().
os_select()
static int os_select (int nfds, fd_set * rfds, fd_set * wfds, fd_set * efds, struct timeval * tv) static
Definition at line 346 of file unix.h.
 {
     int ret = select(nfds, rfds, wfds, efds, tv);
     if (ret == -1) {
         net_error = errno;
         if (net_error == EINTR)
             return 0;
     }
     return ret;
 }
Referenced by NET_Sleep().
os_send()
static ssize_t os_send (qsocket_t sock, const void * data, size_t len, int flags) static
Definition at line 185 of file unix.h.
 {
     ssize_t ret = send(sock, data, len, flags);
     if (ret == -1)
         return os_get_error();
     return ret;
 }
Referenced by NET_RunStream().
os_setsockopt()
static neterr_t os_setsockopt (qsocket_t sock, int level, int name, int val) static
Definition at line 254 of file unix.h.
 {
     if (setsockopt(sock, level, name, &val, sizeof(val)) == -1) {
         net_error = errno;
         return NET_ERROR;
     }
     return NET_OK;
 }
Referenced by TCP_OpenSocket(), and UDP_OpenSocket().
os_socket()
static qsocket_t os_socket (int domain, int type, int protocol) static
Definition at line 307 of file unix.h.
 {
     int s = socket(domain, type, protocol);
     if (s == -1) {
         net_error = errno;
         return -1;
     }
     return s;
 }
Referenced by NET_EnableIP6(), TCP_OpenSocket(), and UDP_OpenSocket().
os_udp_recv()
static ssize_t os_udp_recv (qsocket_t sock, void * data, size_t len, netadr_t * from) static
Definition at line 105 of file unix.h.
 {
     struct sockaddr_storage addr;
     socklen_t addrlen;
     ssize_t ret;
     int tries;
     for (tries = 0; tries < MAX_ERROR_RETRIES; tries++) {
         memset(&addr, 0, sizeof(addr));
         addrlen = sizeof(addr);
         ret = recvfrom(sock, data, len, 0,
                        (struct sockaddr *)&addr, &addrlen);
         NET_SockadrToNetadr(&addr, from);
         if (ret >= 0)
             return ret;
         net_error = errno;
         // wouldblock is silent
         if (net_error == EWOULDBLOCK)
             return NET_AGAIN;
         if (!process_error_queue(sock, NULL))
             break;
     }
     return NET_ERROR;
 }
Referenced by NET_GetUdpPackets().
os_udp_send()
static ssize_t os_udp_send (qsocket_t sock, const void * data, size_t len, const netadr_t * to) static
Definition at line 137 of file unix.h.
 {
     struct sockaddr_storage addr;
     socklen_t addrlen;
     ssize_t ret;
     int tries;
     addrlen = NET_NetadrToSockadr(to, &addr);
     for (tries = 0; tries < MAX_ERROR_RETRIES; tries++) {
         ret = sendto(sock, data, len, 0,
                      (struct sockaddr *)&addr, addrlen);
         if (ret >= 0)
             return ret;
         net_error = errno;
         // wouldblock is silent
         if (net_error == EWOULDBLOCK)
             return NET_AGAIN;
         if (!process_error_queue(sock, to))
             break;
     }
     return NET_ERROR;
 }
Referenced by NET_SendPacket().
process_error_queue()
static qboolean process_error_queue (qsocket_t sock, const netadr_t * to) static
Definition at line 29 of file unix.h.
 {
 #ifdef IP_RECVERR
     byte buffer[1024];
     struct sockaddr_storage from_addr;
     struct msghdr msg;
     struct cmsghdr *cmsg;
     struct sock_extended_err *ee;
     netadr_t from;
     int tries;
     qboolean found = qfalse;
     for (tries = 0; tries < MAX_ERROR_RETRIES; tries++) {
         memset(&from_addr, 0, sizeof(from_addr));
         memset(&msg, 0, sizeof(msg));
         msg.msg_name = &from_addr;
         msg.msg_namelen = sizeof(from_addr);
         msg.msg_control = buffer;
         msg.msg_controllen = sizeof(buffer);
         if (recvmsg(sock, &msg, MSG_ERRQUEUE) == -1) {
             if (errno != EWOULDBLOCK)
                 Com_DPrintf("%s: %s\n", __func__, strerror(errno));
             break;
         }
         if (!(msg.msg_flags & MSG_ERRQUEUE)) {
             Com_DPrintf("%s: no extended error received\n", __func__);
             break;
         }
         // find an ICMP error message
         for (cmsg = CMSG_FIRSTHDR(&msg);
              cmsg != NULL;
              cmsg = CMSG_NXTHDR(&msg, cmsg)) {
             if (cmsg->cmsg_level != IPPROTO_IP &&
                 cmsg->cmsg_level != IPPROTO_IPV6) {
                 continue;
             }
             if (cmsg->cmsg_type != IP_RECVERR &&
                 cmsg->cmsg_type != IPV6_RECVERR) {
                 continue;
             }
             ee = (struct sock_extended_err *)CMSG_DATA(cmsg);
             if (ee->ee_origin == SO_EE_ORIGIN_ICMP ||
                 ee->ee_origin == SO_EE_ORIGIN_ICMP6) {
                 break;
             }
         }
         if (!cmsg) {
             Com_DPrintf("%s: no ICMP error found\n", __func__);
             break;
         }
         NET_SockadrToNetadr(&from_addr, &from);
         // check for offender address being current packet destination
         if (to != NULL && NET_IsEqualBaseAdr(&from, to) &&
             (from.port == 0 || from.port == to->port)) {
             Com_DPrintf("%s: found offending address: %s\n", __func__,
                         NET_AdrToString(&from));
             found = qtrue;
         }
         // handle ICMP error
         NET_ErrorEvent(sock, &from, ee->ee_errno, ee->ee_info);
     }
     return !!tries && !found;
 #else
     return qfalse;
 #endif
 }
Referenced by os_udp_recv(), and os_udp_send().