Quake II RTX doxygen: C:/entry/dev/Q2RTX/src/windows/system.c File Reference
system.c File Reference
#include "client.h"
#include "common/cvar.h"
#include "common/field.h"
#include "common/prompt.h"
#include <mmsystem.h>
Enumerations
enum should_exit_t { SE_NOT, SE_YES, SE_FULL }
Functions
void Sys_Error (const char *error,...)
void Sys_Quit (void)
void Sys_DebugBreak (void)
unsigned Sys_Milliseconds (void)
void Sys_AddDefaultConfig (void)
void Sys_Sleep (int msec)
qboolean Sys_IsDir (const char *path)
qboolean Sys_IsFile (const char *path)
void Sys_Init (void)
void Sys_FreeLibrary (void *handle)
void * Sys_LoadLibrary (const char *path, const char *sym, void **handle)
void * Sys_GetProcAddress (void *handle, const char *sym)
static time_t file_time_to_unix (FILETIME *f)
static void * copy_info (const char *name, const LPWIN32_FIND_DATAA data)
void Sys_ListFiles_r (const char *path, const char *filter, unsigned flags, size_t baselen, int *count_p, void **files, int depth)
static BOOL fix_current_directory (void)
static int Sys_Main (int argc, char **argv)
int main (int argc, char **argv)
Variables
HINSTANCE hGlobalInstance
static char currentDirectory [MAX_OSPATH]
static volatile should_exit_t shouldExit
static volatile qboolean errorEntered
cvar_t * sys_basedir
cvar_t * sys_libdir
cvar_t * sys_homedir
cvar_t * sys_forcegamelib
Enumeration Type Documentation
should_exit_t
enum should_exit_t
Enumerator
SE_NOT
SE_YES
SE_FULL
Definition at line 41 of file system.c.
              {
     SE_NOT,
     SE_YES,
     SE_FULL
 } should_exit_t;
Function Documentation
copy_info()
static void* copy_info (const char * name, const LPWIN32_FIND_DATAA data) static
Definition at line 850 of file system.c.
 {
     time_t ctime = file_time_to_unix(&data->ftCreationTime);
     time_t mtime = file_time_to_unix(&data->ftLastWriteTime);
     return FS_CopyInfo(name, data->nFileSizeLow, ctime, mtime);
 }
Referenced by Sys_ListFiles_r().
file_time_to_unix()
static time_t file_time_to_unix (FILETIME * f) inline static
Definition at line 844 of file system.c.
 {
     ULARGE_INTEGER u = *(ULARGE_INTEGER *)f;
     return (time_t)((u.QuadPart - 116444736000000000ULL) / 10000000);
 }
Referenced by copy_info().
fix_current_directory()
static BOOL fix_current_directory (void) static
Definition at line 1006 of file system.c.
 {
     char *p;
     if (!GetModuleFileNameA(NULL, currentDirectory, sizeof(currentDirectory) - 1)) {
         return FALSE;
     }
     if ((p = strrchr(currentDirectory, '\\')) != NULL) {
         *p = 0;
     }
 #ifndef UNDER_CE
     if (!SetCurrentDirectoryA(currentDirectory)) {
         return FALSE;
     }
 #endif
     return TRUE;
 }
Referenced by Sys_Main().
main()
int main (int argc, char ** argv)
Definition at line 1174 of file system.c.
 {
 #if USE_WINSVC
     int i;
 #endif
     hGlobalInstance = GetModuleHandle(NULL);
 #if USE_WINSVC
     for (i = 1; i < argc; i++) {
         if (!strcmp(argv[i], "-service")) {
             argv[i] = NULL;
             sys_argc = argc;
             sys_argv = argv;
             if (StartServiceCtrlDispatcher(serviceTable)) {
                 return 0;
             }
             if (GetLastError() == ERROR_FAILED_SERVICE_CONTROLLER_CONNECT) {
                 break; // fall back to normal server startup
             }
             return 1;
         }
     }
 #endif
     return Sys_Main(argc, argv);
 }
Sys_AddDefaultConfig()
void Sys_AddDefaultConfig (void)
Definition at line 649 of file system.c.
 {
 }
Referenced by Qcommon_Init().
Sys_DebugBreak()
void Sys_DebugBreak (void)
Definition at line 639 of file system.c.
 {
     DebugBreak();
 }
Referenced by Com_Error().
Sys_Error()
void Sys_Error (const char * error, ...)
Definition at line 574 of file system.c.
 {
     va_list     argptr;
     char        text[MAXERRORMSG];
     va_start(argptr, error);
     Q_vsnprintf(text, sizeof(text), error, argptr);
     va_end(argptr);
     errorEntered = qtrue;
 #if USE_CLIENT
     VID_Shutdown();
 #endif
 #if USE_SYSCON
     Sys_SetConsoleColor(COLOR_RED);
     Sys_Printf("********************\n"
                "FATAL: %s\n"
                "********************\n", text);
     Sys_SetConsoleColor(COLOR_NONE);
 #endif
 #if USE_WINSVC
     if (!statusHandle)
 #endif
     {
 #if USE_SYSCON
         if (gotConsole) {
             Sleep(INFINITE);
         }
 #endif
         MessageBoxA(NULL, text, PRODUCT " Fatal Error", MB_ICONERROR | MB_OK);
     }
     exit(1);
 }
Referenced by Com_Error(), Qcommon_Init(), and Sys_Init().
Sys_FreeLibrary()
void Sys_FreeLibrary (void * handle)
Definition at line 787 of file system.c.
 {
     if (handle && !FreeLibrary(handle)) {
         Com_Error(ERR_FATAL, "FreeLibrary failed on %p", handle);
     }
 }
Referenced by QAL_Shutdown(), and SV_ShutdownGameProgs().
Sys_GetProcAddress()
void* Sys_GetProcAddress (void * handle, const char * sym)
Definition at line 824 of file system.c.
 {
     void    *entry;
     entry = GetProcAddress(handle, sym);
     if (!entry)
         Com_SetLastError(va("GetProcAddress(%s) failed with error %lu",
                             sym, GetLastError()));
     return entry;
 }
Sys_Init()
void Sys_Init (void)
Definition at line 695 of file system.c.
 {
     OSVERSIONINFO vinfo;
 #ifndef _WIN64
     HMODULE module;
     BOOL (WINAPI * pSetProcessDEPPolicy)(DWORD);
 #endif
     cvar_t *var = NULL;
     timeBeginPeriod(1);
     // check windows version
     vinfo.dwOSVersionInfoSize = sizeof(vinfo);
 #pragma warning(push)
 #pragma warning(disable: 4996) // warning C4996: 'GetVersionExA': was declared deprecated
     if (!GetVersionEx(&vinfo)) {
         Sys_Error("Couldn't get OS info");
     }
 #pragma warning(pop)
     if (vinfo.dwPlatformId != VER_PLATFORM_WIN32_NT) {
         Sys_Error(PRODUCT " requires Windows NT");
     }
     if (vinfo.dwMajorVersion < 5) {
         Sys_Error(PRODUCT " requires Windows 2000 or greater");
     }
     // basedir <path>
     // allows the game to run from outside the data tree
     sys_basedir = Cvar_Get("basedir", currentDirectory, CVAR_NOSET);
     sys_libdir = Cvar_Get("libdir", currentDirectory, CVAR_NOSET);
     // homedir <path>
     // specifies per-user writable directory for demos, screenshots, etc
     sys_homedir = Cvar_Get("homedir", "", CVAR_NOSET);
     sys_forcegamelib = Cvar_Get("sys_forcegamelib", "", CVAR_NOSET);
 #if USE_WINSVC
     Cmd_AddCommand("installservice", Sys_InstallService_f);
     Cmd_AddCommand("deleteservice", Sys_DeleteService_f);
 #endif
 #if USE_SYSCON
     houtput = GetStdHandle(STD_OUTPUT_HANDLE);
 #if USE_CLIENT
     sys_viewlog = Cvar_Get("sys_viewlog", "0", CVAR_NOSET);
     if (dedicated->integer || sys_viewlog->integer)
 #endif
         Sys_ConsoleInit();
 #endif // USE_SYSCON
 #if USE_DBGHELP
     var = Cvar_Get("sys_disablecrashdump", "0", CVAR_NOSET);
     // install our exception filter
     if (!var->integer) {
         mainProcessThread = GetCurrentThread();
         prevExceptionFilter = SetUnhandledExceptionFilter(
                                   Sys_ExceptionFilter);
     }
 #endif
 #ifndef _WIN64
     module = GetModuleHandle("kernel32.dll");
     if (module) {
         pSetProcessDEPPolicy = (PVOID)GetProcAddress(module,
                                                      "SetProcessDEPPolicy");
         if (pSetProcessDEPPolicy) {
             var = Cvar_Get("sys_disabledep", "0", CVAR_NOSET);
             // opt-in or opt-out for DEP
             if (!var->integer) {
                 pSetProcessDEPPolicy(
                     PROCESS_DEP_ENABLE |
                     PROCESS_DEP_DISABLE_ATL_THUNK_EMULATION);
             } else if (var->integer == 2) {
                 pSetProcessDEPPolicy(0);
             }
         }
     }
 #endif
 }
Referenced by Qcommon_Init().
Sys_IsDir()
qboolean Sys_IsDir (const char * path)
Definition at line 659 of file system.c.
 {
     WCHAR wpath[MAX_OSPATH] = { 0 };
     MultiByteToWideChar(CP_UTF8, 0, path, -1, wpath, MAX_OSPATH);
     DWORD fileAttributes = GetFileAttributesW(wpath);
     if (fileAttributes == INVALID_FILE_ATTRIBUTES)
     {
         return qfalse;
     }
     return (fileAttributes & FILE_ATTRIBUTE_DIRECTORY) != 0;
 }
Referenced by OGG_InitTrackList().
Sys_IsFile()
qboolean Sys_IsFile (const char * path)
Definition at line 674 of file system.c.
 {
     WCHAR wpath[MAX_OSPATH] = { 0 };
     MultiByteToWideChar(CP_UTF8, 0, path, -1, wpath, MAX_OSPATH);
     DWORD fileAttributes = GetFileAttributesW(wpath);
     if (fileAttributes == INVALID_FILE_ATTRIBUTES)
     {
         return qfalse;
     }
     // I guess the assumption that if it's not a file or device
     // then it's a directory is good enough for us?
     return (fileAttributes & (FILE_ATTRIBUTE_DIRECTORY | FILE_ATTRIBUTE_DEVICE)) == 0;
 }
Referenced by OGG_InitTrackList().
Sys_ListFiles_r()
void Sys_ListFiles_r (const char * path, const char * filter, unsigned flags, size_t baselen, int * count_p, void ** files, int depth)
Definition at line 868 of file system.c.
 {
     WIN32_FIND_DATAA    data;
     HANDLE      handle;
     char        fullpath[MAX_OSPATH], *name;
     size_t      pathlen, len;
     unsigned    mask;
     void        *info;
     // optimize single extension search
     if (!(flags & FS_SEARCH_BYFILTER) &&
         filter && !strchr(filter, ';')) {
         if (*filter == '.') {
             filter++;
         }
         len = Q_concat(fullpath, sizeof(fullpath),
                        path, "\\*.", filter, NULL);
         filter = NULL; // do not check it later
     } else {
         len = Q_concat(fullpath, sizeof(fullpath),
                        path, "\\*", NULL);
     }
     if (len >= sizeof(fullpath)) {
         return;
     }
     // format path to windows style
     // done on the first run only
     if (!depth) {
         FS_ReplaceSeparators(fullpath, '\\');
     }
     handle = FindFirstFileA(fullpath, &data);
     if (handle == INVALID_HANDLE_VALUE) {
         return;
     }
     // make it point right after the slash
     pathlen = strlen(path) + 1;
     do {
         if (!strcmp(data.cFileName, ".") ||
             !strcmp(data.cFileName, "..")) {
             continue; // ignore special entries
         }
         // construct full path
         len = strlen(data.cFileName);
         if (pathlen + len >= sizeof(fullpath)) {
             continue;
         }
         memcpy(fullpath + pathlen, data.cFileName, len + 1);
         if (data.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) {
             mask = FS_SEARCH_DIRSONLY;
         } else {
             mask = 0;
         }
         // pattern search implies recursive search
         if ((flags & FS_SEARCH_BYFILTER) && mask &&
             depth < MAX_LISTED_DEPTH) {
             Sys_ListFiles_r(fullpath, filter, flags, baselen,
                             count_p, files, depth + 1);
             // re-check count
             if (*count_p >= MAX_LISTED_FILES) {
                 break;
             }
         }
         // check type
         if ((flags & FS_SEARCH_DIRSONLY) != mask) {
             continue;
         }
         // check filter
         if (filter) {
             if (flags & FS_SEARCH_BYFILTER) {
                 if (!FS_WildCmp(filter, fullpath + baselen)) {
                     continue;
                 }
             } else {
                 if (!FS_ExtCmp(filter, data.cFileName)) {
                     continue;
                 }
             }
         }
         // strip path
         if (flags & FS_SEARCH_SAVEPATH) {
             name = fullpath + baselen;
         } else {
             name = data.cFileName;
         }
         // reformat it back to quake filesystem style
         FS_ReplaceSeparators(name, '/');
         // strip extension
         if (flags & FS_SEARCH_STRIPEXT) {
             *COM_FileExtension(name) = 0;
             if (!*name) {
                 continue;
             }
         }
         // copy info off
         if (flags & FS_SEARCH_EXTRAINFO) {
             info = copy_info(name, &data);
         } else {
             info = FS_CopyString(name);
         }
         files[(*count_p)++] = info;
     } while (*count_p < MAX_LISTED_FILES &&
              FindNextFileA(handle, &data) != FALSE);
     FindClose(handle);
 }
Referenced by FS_ListFiles(), and q_printf().
Sys_LoadLibrary()
void* Sys_LoadLibrary (const char * path, const char * sym, void ** handle)
Definition at line 794 of file system.c.
 {
     HMODULE module;
     void    *entry;
     *handle = NULL;
     module = LoadLibraryA(path);
     if (!module) {
         Com_SetLastError(va("%s: LoadLibrary failed with error %lu",
                             path, GetLastError()));
         return NULL;
     }
     if (sym) {
         entry = GetProcAddress(module, sym);
         if (!entry) {
             Com_SetLastError(va("%s: GetProcAddress(%s) failed with error %lu",
                                 path, sym, GetLastError()));
             FreeLibrary(module);
             return NULL;
         }
     } else {
         entry = NULL;
     }
     *handle = module;
     return entry;
 }
Referenced by _SV_LoadGameLibrary(), and QAL_Init().
Sys_Main()
static int Sys_Main (int argc, char ** argv) static
Definition at line 1034 of file system.c.
 {
     // fix current directory to point to the basedir
     if (!fix_current_directory()) {
         return 1;
     }
 #if (_MSC_VER >= 1400)
     // work around strftime given invalid format string
     // killing the whole fucking process :((
     _set_invalid_parameter_handler(msvcrt_sucks);
 #endif
     Qcommon_Init(argc, argv);
     // main program loop
     while (1) {
         Qcommon_Frame();
         if (shouldExit) {
 #if USE_WINSVC
             if (shouldExit == SE_FULL)
 #endif
                 Com_Quit(NULL, ERR_DISCONNECT);
             break;
         }
     }
     // may get here when our service stops
     return 0;
 }
Referenced by main().
Sys_Milliseconds()
unsigned Sys_Milliseconds (void)
Definition at line 644 of file system.c.
 {
     return timeGetTime();
 }
Referenced by BSP_Test_f(), CL_CleanupDemos(), CL_FirstDemoFrame(), CL_Frame(), Com_Freeze_f(), MVD_Spawn(), Netchan_Init(), PingServers(), process_gamepad_input(), Qcommon_Frame(), Qcommon_Init(), R_PrintTimes(), R_RenderFrame(), R_RenderFrame_RTX(), SCR_BeginLoadingPlaque(), SCR_DrawSelectedItemName(), SCR_TimeRefresh_f(), SCR_UpdateScreen(), SV_RunGameFrame(), SV_SpawnServer(), and vkpt_bloom_update().
Sys_Quit()
void Sys_Quit (void)
Definition at line 619 of file system.c.
 {
     timeEndPeriod(1);
 #if USE_CLIENT
 #if USE_SYSCON
     if (dedicated && dedicated->integer) {
         FreeConsole();
     }
 #endif
 #elif USE_WINSVC
     if (statusHandle && !shouldExit) {
         shouldExit = SE_YES;
         Com_AbortFrame();
     }
 #endif
     exit(0);
 }
Referenced by Com_Quit().
Sys_Sleep()
void Sys_Sleep (int msec)
Definition at line 653 of file system.c.
 {
     Sleep(msec);
 }
Referenced by NET_Sleep().
Variable Documentation
currentDirectory
char currentDirectory[MAX_OSPATH] static
Definition at line 35 of file system.c.
Referenced by fix_current_directory(), and Sys_Init().
errorEntered
volatile qboolean errorEntered static
Definition at line 48 of file system.c.
Referenced by Sys_Error().
hGlobalInstance
HINSTANCE hGlobalInstance
Definition at line 28 of file system.c.
Referenced by DI_InitMouse(), GetFakeWindowExtensions(), main(), Sys_ExceptionFilter(), win_disablewinkey_changed(), Win_Init(), and Win_Shutdown().
shouldExit
volatile should_exit_t shouldExit static
Definition at line 47 of file system.c.
Referenced by Sys_Main(), and Sys_Quit().
sys_basedir
cvar_t* sys_basedir
Definition at line 50 of file system.c.
Referenced by FS_Restart(), open_file_write(), setup_base_paths(), setup_game_paths(), and Sys_Init().
sys_forcegamelib
cvar_t* sys_forcegamelib
Definition at line 53 of file system.c.
Referenced by SV_InitGameProgs(), and Sys_Init().
sys_homedir
cvar_t* sys_homedir
Definition at line 52 of file system.c.
Referenced by open_file_write(), setup_game_paths(), and Sys_Init().
sys_libdir
cvar_t* sys_libdir
Definition at line 51 of file system.c.
Referenced by SV_LoadGameLibrary(), and Sys_Init().