Quake II RTX doxygen: C:/entry/dev/Q2RTX/src/common/cvar.c File Reference
cvar.c File Reference
#include "shared/shared.h"
#include "common/cmd.h"
#include "common/common.h"
#include "common/cvar.h"
#include "common/files.h"
#include "common/prompt.h"
#include "common/utils.h"
#include "common/zone.h"
#include "client/client.h"
Macros
#define Cvar_Malloc(size) Z_TagMalloc(size, TAG_CVAR)
#define CVARHASH_SIZE 256
Functions
cvar_t * Cvar_FindVar (const char *var_name)
xgenerator_t Cvar_FindGenerator (const char *var_name)
qboolean Cvar_Exists (const char *var_name, qboolean weak)
float Cvar_VariableValue (const char *var_name)
int Cvar_VariableInteger (const char *var_name)
char * Cvar_VariableString (const char *var_name)
void Cvar_Variable_g (genctx_t *ctx)
void Cvar_Default_g (genctx_t *ctx)
static void parse_string_value (cvar_t *var)
static void change_string_value (cvar_t *var, const char *value, from_t from)
static qboolean validate_info_cvar (const char *s)
static void get_engine_cvar (cvar_t *var, const char *var_value, int flags)
cvar_t * Cvar_Get (const char *var_name, const char *var_value, int flags)
cvar_t * Cvar_WeakGet (const char *var_name)
static void set_back_cvar (cvar_t *var)
void Cvar_SetByVar (cvar_t *var, const char *value, from_t from)
cvar_t * Cvar_SetEx (const char *var_name, const char *value, from_t from)
cvar_t * Cvar_FullSet (const char *var_name, const char *value, int flags, from_t from)
cvar_t * Cvar_Set (const char *var_name, const char *value)
cvar_t * Cvar_UserSet (const char *var_name, const char *value)
void Cvar_SetValue (cvar_t *var, float value, from_t from)
void Cvar_SetInteger (cvar_t *var, int value, from_t from)
int Cvar_ClampInteger (cvar_t *var, int min, int max)
float Cvar_ClampValue (cvar_t *var, float min, float max)
void Cvar_FixCheats (void)
void Cvar_GetLatchedVars (void)
int Cvar_CountLatchedVars (void)
void Cvar_Command (cvar_t *v)
static void Cvar_Set_c (genctx_t *ctx, int argnum)
void Cvar_Set_f (void)
static void Cvar_SetFlag_f (void)
static void Cvar_List_c (genctx_t *ctx, int argnum)
static void Cvar_List_f (void)
static void Cvar_Toggle_f (void)
static void Cvar_Toggle_c (genctx_t *ctx, int argnum)
static void Cvar_Inc_f (void)
static void Cvar_Reset_f (void)
static void Cvar_Reset_c (genctx_t *ctx, int argnum)
static void Cvar_ResetAll_f (void)
size_t Cvar_BitInfo (char *info, int bit)
void Cvar_Init (void)
Variables
cvar_t * cvar_vars
int cvar_modified
static cvar_t * cvarHash [CVARHASH_SIZE]
static const cmd_option_t o_cvarlist []
static const cmdreg_t c_cvar []
Macro Definition Documentation
Cvar_Malloc
#define Cvar_Malloc (size) Z_TagMalloc(size, TAG_CVAR)
Definition at line 34 of file cvar.c.
CVARHASH_SIZE
#define CVARHASH_SIZE 256
Definition at line 36 of file cvar.c.
Function Documentation
change_string_value()
static void change_string_value (cvar_t * var, const char * value, from_t from) static
Definition at line 173 of file cvar.c.
 {
     // free the old value string
     Z_Free(var->string);
     var->string = Z_CvarCopyString(value);
     parse_string_value(var);
     if (var->flags & CVAR_USERINFO) {
         CL_UpdateUserinfo(var, from);
     }
     var->modified = qtrue;
     if (from != FROM_CODE) {
         cvar_modified |= var->flags & CVAR_MODIFYMASK;
         var->flags |= CVAR_MODIFIED;
         if (from == FROM_MENU && !(var->flags & CVAR_NOARCHIVEMASK)) {
             var->flags |= CVAR_ARCHIVE;
         }
         if (var->changed) {
             var->changed(var);
         }
     }
 }
Referenced by Cvar_SetByVar(), and get_engine_cvar().
Cvar_BitInfo()
size_t Cvar_BitInfo (char * info, int bit)
Definition at line 1109 of file cvar.c.
 {
     char    newi[MAX_INFO_STRING], *v;
     cvar_t  *var;
     size_t  len, total = 0;
     int     c;
     for (var = cvar_vars; var; var = var->next) {
         if (!(var->flags & bit)) {
             continue;
         }
         if (var->flags & CVAR_PRIVATE) {
             continue;
         }
         if (!var->string[0]) {
             continue;
         }
         len = Q_concat(newi, sizeof(newi),
                        "\\", var->name, "\\", var->string, NULL);
         if (len >= sizeof(newi)) {
             continue;
         }
         if (total + len >= MAX_INFO_STRING) {
             break;
         }
         // only copy ascii values
         v = newi;
         while (*v) {
             c = *v++;
             c &= 127;        // strip high bits
             if (Q_isprint(c))
                 info[total++] = c;
         }
     }
     info[total] = 0;
     return total;
 }
Referenced by CL_CheckForResend(), CL_SendUserinfo(), CL_Userinfo_f(), SV_Serverinfo_f(), SV_ShowServerInfo_f(), and SV_StatusString().
Cvar_ClampInteger()
int Cvar_ClampInteger (cvar_t * var, int min, int max)
Definition at line 549 of file cvar.c.
 {
     char    val[32];
     if (var->integer < min) {
         Q_snprintf(val, sizeof(val), "%i", min);
         Cvar_SetByVar(var, val, FROM_CODE);
         return min;
     }
     if (var->integer > max) {
         Q_snprintf(val, sizeof(val), "%i", max);
         Cvar_SetByVar(var, val, FROM_CODE);
         return max;
     }
     return var->integer;
 }
Referenced by CalcPingRate(), CL_Record_f(), CL_SendBatchedCmd(), CL_UpdateFrameTimes(), drs_maxscale_changed(), drs_minscale_changed(), drs_target_changed(), GL_UpscaleLevel(), LoadGL(), MVD_Say_f(), net_maxmsglen_changed(), parse_hello(), parse_stream_data(), Qcommon_Frame(), R_InitCaches(), R_NewMap(), R_SetupFrame(), S_Activate(), SCR_LagDraw(), SV_BeginDownload_f(), SV_InitGame(), SV_MvdInit(), ui_sortdemos_changed(), ui_sortservers_changed(), and viewsize_changed().
Cvar_ClampValue()
float Cvar_ClampValue (cvar_t * var, float min, float max)
Definition at line 571 of file cvar.c.
 {
     char    val[32];
     if (var->value < min) {
         if (min == (int)min) {
             Q_snprintf(val, sizeof(val), "%i", (int)min);
         } else {
             Q_snprintf(val, sizeof(val), "%f", min);
         }
         Cvar_SetByVar(var, val, FROM_CODE);
         return min;
     }
     if (var->value > max) {
         if (max == (int)max) {
             Q_snprintf(val, sizeof(val), "%i", (int)max);
         } else {
             Q_snprintf(val, sizeof(val), "%f", max);
         }
         Cvar_SetByVar(var, val, FROM_CODE);
         return max;
     }
     return var->value;
 }
Referenced by CL_AddViewWeapon(), CL_MouseMove(), Con_DrawSolidConsole(), Con_RunConsole(), GL_BuildIntensityTable(), GL_InitImages(), gl_lightmap_changed(), HQ2x_Init(), R_ClampScale(), scr_crosshair_changed(), SCR_Draw2D(), SCR_DrawCenterString(), setup_celshading(), and vkpt_freecam_mousemove().
Cvar_Command()
void Cvar_Command (cvar_t * v)
Definition at line 672 of file cvar.c.
 {
 // perform a variable print or set
     if (Cmd_Argc() < 2) {
         Com_Printf("\"%s\" is \"%s\"", v->name, v->string);
         if (strcmp(v->string, v->default_string)) {
             Com_Printf("  default: \"%s\"", v->default_string);
         }
         if (v->latched_string && strcmp(v->latched_string, v->string)) {
             Com_Printf("  latched: \"%s\"", v->latched_string);
         }
         Com_Printf("\n");
     } else {
         Cvar_SetByVar(v, Cmd_ArgsFrom(1), Cmd_From());
     }
 }
Referenced by Cmd_ExecuteCommand(), and dummy_exec_string().
Cvar_CountLatchedVars()
int Cvar_CountLatchedVars (void)
Definition at line 649 of file cvar.c.
 {
     cvar_t  *var;
     int     total = 0;
     for (var = cvar_vars; var; var = var->next) {
         if (!(var->flags & CVAR_LATCH))
             continue;
         if (!var->latched_string)
             continue;
         total++;
     }
     return total;
 }
Referenced by should_really_restart().
Cvar_Default_g()
void Cvar_Default_g (genctx_t * ctx)
Definition at line 144 of file cvar.c.
 {
     cvar_t *c = ctx->data;
     if (c) {
         if (strcmp(c->string, c->default_string)) {
             Prompt_AddMatch(ctx, c->string);
         }
         Prompt_AddMatch(ctx, c->default_string);
     }
 }
Referenced by Cvar_Get().
Cvar_Exists()
qboolean Cvar_Exists (const char * var_name, qboolean weak)
Definition at line 73 of file cvar.c.
 {
     cvar_t *var = Cvar_FindVar(var_name);
     if (!var)
         return qfalse;
     if (!weak && (var->flags & (CVAR_CUSTOM | CVAR_WEAK)))
         return qfalse;
     return qtrue;
 }
Referenced by Cmd_AddMacro(), Cmd_Alias_f(), Cmd_Complete_f(), and Cmd_RegCommand().
Cvar_FindGenerator()
xgenerator_t Cvar_FindGenerator (const char * var_name)
Definition at line 61 of file cvar.c.
 {
     cvar_t *var = Cvar_FindVar(var_name);
     return var ? var->generator : NULL;
 }
Referenced by Cvar_Toggle_c().
Cvar_FindVar()
cvar_t* Cvar_FindVar (const char * var_name)
Definition at line 45 of file cvar.c.
 {
     cvar_t *var;
     unsigned hash;
     hash = Com_HashString(var_name, CVARHASH_SIZE);
     for (var = cvarHash[hash]; var; var = var->hashNext) {
         if (!strcmp(var_name, var->name)) {
             return var;
         }
     }
     return NULL;
 }
Referenced by CL_PingServers_f(), Cmd_ExecuteCommand(), Cmd_MacroExpandString(), Com_Address_g(), Com_Generic_c(), Cvar_Exists(), Cvar_FindGenerator(), Cvar_FullSet(), Cvar_Get(), Cvar_Inc_f(), Cvar_Reset_f(), Cvar_Set_c(), Cvar_SetEx(), Cvar_Toggle_f(), Cvar_VariableInteger(), Cvar_VariableString(), Cvar_VariableValue(), dummy_exec_string(), and ParseAddressBook().
Cvar_FixCheats()
void Cvar_FixCheats (void)
Definition at line 601 of file cvar.c.
 {
     cvar_t *var;
     if (CL_CheatsOK()) {
         return;
     }
     // fix any cheating cvars
     for (var = cvar_vars; var; var = var->next) {
         if (var->flags & CVAR_CHEAT) {
             Cvar_SetByVar(var, var->default_string, FROM_CODE);
             if (var->changed)
                 var->changed(var);
         }
     }
 }
Referenced by CL_Begin().
Cvar_FullSet()
cvar_t* Cvar_FullSet (const char * var_name, const char * value, int flags, from_t from)
Definition at line 437 of file cvar.c.
 {
     cvar_t *var;
     var = Cvar_FindVar(var_name);
     if (!var) {
         // create it
         return Cvar_Get(var_name, value, flags | CVAR_CUSTOM);
     }
     Cvar_SetByVar(var, value, from);
     // force retransmit of userinfo variables
     // needed for compatibility with q2admin
     if ((var->flags | flags) & CVAR_USERINFO) {
         CL_UpdateUserinfo(var, from);
     }
     var->flags &= ~CVAR_INFOMASK;
     var->flags |= flags;
     return var;
 }
Referenced by AC_Disconnect(), AC_ParseReady(), Cvar_Set_f(), Cvar_SetFlag_f(), setup_game_paths(), and SV_InitGame().
Cvar_Get()
cvar_t* Cvar_Get (const char * var_name, const char * var_value, int flags)
Definition at line 257 of file cvar.c.
 {
     cvar_t *var, *c, **p;
     unsigned hash;
     size_t length;
     if (!var_name) {
         Com_Error(ERR_FATAL, "Cvar_Get: NULL var_name");
     }
     if (!var_value) {
         return Cvar_FindVar(var_name);
     }
     if (flags & CVAR_INFOMASK) {
         if (!validate_info_cvar(var_name)) {
             return NULL;
         }
         if (!validate_info_cvar(var_value)) {
             return NULL;
         }
     }
     var = Cvar_FindVar(var_name);
     if (var) {
         if (!(flags & (CVAR_WEAK | CVAR_CUSTOM))) {
             get_engine_cvar(var, var_value, flags);
         }
         return var;
     }
     // create new variable
     length = strlen(var_name) + 1;
     var = Cvar_Malloc(sizeof(*var) + length);
     var->name = (char *)(var + 1);
     memcpy(var->name, var_name, length);
     var->string = Z_CvarCopyString(var_value);
     var->latched_string = NULL;
     var->default_string = Z_CvarCopyString(var_value);
     parse_string_value(var);
     var->flags = flags;
     var->changed = NULL;
     var->generator = Cvar_Default_g;
     var->modified = qtrue;
     // sort the variable in
     for (c = cvar_vars, p = &cvar_vars; c; p = &c->next, c = c->next) {
         if (strcmp(var->name, c->name) < 0) {
             break;
         }
     }
     var->next = c;
     *p = var;
     // link the variable in
     hash = Com_HashString(var_name, CVARHASH_SIZE);
     var->hashNext = cvarHash[hash];
     cvarHash[hash] = var;
     return var;
 }
Referenced by AC_Register(), BSP_Init(), CL_InitDemos(), CL_InitLocal(), CL_InitRefresh(), CL_InitTEnts(), CL_PrepRefresh(), CL_RegisterInput(), CM_Init(), Con_Init(), Cvar_FullSet(), Cvar_SetEx(), Cvar_WeakGet(), DMA_Init(), drs_init(), FS_Init(), FX_Init(), GL_InitImages(), GL_Register(), GL_SetupConfig(), HQ2x_Init(), HTTP_Init(), IMG_Init(), IN_Init(), InitialiseSkyCVars(), initialize_transparency(), LOC_Init(), M_Menu_Demos(), M_Menu_Servers(), MVD_GameInit(), MVD_Register(), NET_Init(), Netchan_Init(), OGG_Init(), OGG_InitTrackList(), PF_cvar(), Prompt_Init(), QAL_Init(), Qcommon_Init(), R_Init_RTX(), R_ModeChanged(), R_Register(), S_Init(), SCR_Init(), SV_BuildClientFrame(), SV_Init(), SV_MvdRegister(), SV_RegisterSavegames(), Sys_Init(), UI_Init(), UI_ModeChanged(), V_Init(), VID_Init(), vkpt_bloom_initialize(), vkpt_initialize_god_rays(), vkpt_pt_init(), vkpt_tone_mapping_record_cmd_buffer(), and Win_Init().
Cvar_GetLatchedVars()
void Cvar_GetLatchedVars (void)
Definition at line 626 of file cvar.c.
 {
     cvar_t    *var;
     for (var = cvar_vars; var; var = var->next) {
         if (var->flags & CVAR_GAME)
             var->flags &= ~CVAR_SERVERINFO;
         if (!(var->flags & CVAR_LATCH))
             continue;
         if (!var->latched_string)
             continue;
         Z_Free(var->string);
         var->string = var->latched_string;
         var->latched_string = NULL;
         parse_string_value(var);
         var->modified = qtrue;
         cvar_modified |= var->flags & CVAR_MODIFYMASK;
         if (var->changed) {
             var->changed(var);
         }
     }
 }
Referenced by SV_InitGame().
Cvar_Inc_f()
static void Cvar_Inc_f (void) static
Definition at line 1024 of file cvar.c.
 {
     cvar_t *var;
     float value;
     char val[32];
     if (Cmd_Argc() < 2) {
         Com_Printf("Usage: %s <variable> [value]\n", Cmd_Argv(0));
         return;
     }
     var = Cvar_FindVar(Cmd_Argv(1));
     if (!var) {
         Com_Printf("%s is not a variable\n", Cmd_Argv(1));
         return;
     }
     if (!COM_IsFloat(var->string)) {
         Com_Printf("\"%s\" is \"%s\", can't %s\n",
                    var->name, var->string, Cmd_Argv(0));
         return;
     }
     value = 1;
     if (Cmd_Argc() > 2) {
         value = atof(Cmd_Argv(2));
     }
     if (!strcmp(Cmd_Argv(0), "dec")) {
         value = -value;
     }
     value += var->value;
     if (value == (int)value)
         Q_snprintf(val, sizeof(val), "%i", (int)value);
     else
         Q_snprintf(val, sizeof(val), "%f", value);
     Cvar_SetByVar(var, val, Cmd_From());
 }
Cvar_Init()
void Cvar_Init (void)
Definition at line 1169 of file cvar.c.
 {
     Cmd_Register(c_cvar);
 }
Referenced by Qcommon_Init().
Cvar_List_c()
static void Cvar_List_c (genctx_t * ctx, int argnum) static
Definition at line 840 of file cvar.c.
 {
     Cmd_Option_c(o_cvarlist, NULL, ctx, argnum);
 }
Cvar_List_f()
static void Cvar_List_f (void) static
Definition at line 845 of file cvar.c.
 {
     cvar_t    *var;
     int        i, total;
     qboolean verbose = qfalse, modified = qfalse, latched = qfalse;
     int mask = 0;
     char *wildcard = NULL;
     char buffer[5];
     int c;
     while ((c = Cmd_ParseOptions(o_cvarlist)) != -1) {
         switch (c) {
         case 'a':
             mask |= CVAR_ARCHIVE;
             break;
         case 'c':
             mask |= CVAR_CHEAT;
             break;
         case 'h':
             Cmd_PrintUsage(o_cvarlist, NULL);
             Com_Printf("List registered console variables.\n");
             Cmd_PrintHelp(o_cvarlist);
             Com_Printf(
                 "Flags legend:\n"
                 "C: cheat protected\n"
                 "A: archived in config file\n"
                 "U: included in userinfo\n"
                 "S: included in serverinfo\n"
                 "N: set from command line only\n"
                 "R: read-only variable\n"
                 "L: latched\n"
                 "?: created by user\n");
             return;
         case 'l':
             latched = qtrue;
             break;
         case 'm':
             modified = qtrue;
             break;
         case 'n':
             mask |= CVAR_NOSET;
             break;
         case 'r':
             mask |= CVAR_ROM;
             break;
         case 's':
             mask |= CVAR_SERVERINFO;
             break;
         case 't':
             mask |= CVAR_CUSTOM;
             break;
         case 'u':
             mask |= CVAR_USERINFO;
             break;
         case 'v':
             verbose = qtrue;
             break;
         case 'w':
             wildcard = cmd_optarg;
             break;
         default:
             return;
         }
     }
     buffer[sizeof(buffer) - 1] = 0;
     i = 0;
     for (var = cvar_vars, total = 0; var; var = var->next, total++) {
         if (latched && !var->latched_string) {
             continue;
         }
         if (mask && !(var->flags & mask)) {
             continue;
         }
         if (wildcard && !Com_WildCmp(wildcard, var->name)) {
             continue;
         }
         if (modified && (!strcmp(var->latched_string ? var->latched_string :
                                  var->string, var->default_string) || (var->flags & CVAR_ROM))) {
             continue;
         }
         if (verbose) {
             memset(buffer, '-', sizeof(buffer) - 1);
             if (var->flags & CVAR_CHEAT)
                 buffer[0] = 'C';
             else if (var->flags & CVAR_ARCHIVE)
                 buffer[0] = 'A';
             if (var->flags & CVAR_USERINFO)
                 buffer[1] = 'U';
             if (var->flags & CVAR_SERVERINFO)
                 buffer[2] = 'S';
             if (var->flags & CVAR_ROM)
                 buffer[3] = 'R';
             else if (var->flags & CVAR_NOSET)
                 buffer[3] = 'N';
             else if (var->flags & CVAR_LATCH)
                 buffer[3] = 'L';
             else if (var->flags & CVAR_CUSTOM)
                 buffer[3] = '?';
             Com_Printf("%s ", buffer);
         }
         Com_Printf("%s \"%s\"\n", var->name, var->string);
         i++;
     }
     Com_Printf("%i of %i cvars\n", i, total);
 }
Cvar_Reset_c()
static void Cvar_Reset_c (genctx_t * ctx, int argnum) static
Definition at line 1087 of file cvar.c.
 {
     if (argnum == 1) {
         Cvar_Variable_g(ctx);
     }
 }
Cvar_Reset_f()
static void Cvar_Reset_f (void) static
Definition at line 1069 of file cvar.c.
 {
     cvar_t *var;
     if (Cmd_Argc() < 2) {
         Com_Printf("Usage: %s <variable>\n", Cmd_Argv(0));
         return;
     }
     var = Cvar_FindVar(Cmd_Argv(1));
     if (!var) {
         Com_Printf("%s is not a variable\n", Cmd_Argv(1));
         return;
     }
     Cvar_SetByVar(var, var->default_string, Cmd_From());
 }
Cvar_ResetAll_f()
static void Cvar_ResetAll_f (void) static
Definition at line 1094 of file cvar.c.
 {
     cvar_t *var;
     for (var = cvar_vars; var; var = var->next) {
         if (var->flags & CVAR_ROM)
             continue;
         if ((var->flags & CVAR_NOSET) && com_initialized)
             continue;
         if (var == fs_game)
             continue;
         Cvar_SetByVar(var, var->default_string, Cmd_From());
     }
 }
Cvar_Set()
cvar_t* Cvar_Set (const char * var_name, const char * value)
Definition at line 466 of file cvar.c.
 {
     return Cvar_SetEx(var_name, value, FROM_CODE);
 }
Referenced by check_paused(), CL_CheckForPause(), CL_Connect_f(), CL_FixUpGender(), CL_Init(), CL_InitLocal(), CL_InitRefresh(), CL_Pause_f(), CL_RunRefresh(), CL_Shutdown(), DMA_Init(), finish_demo(), fs_game_changed(), GL_InitPrograms(), GL_PostInit(), IN_Init(), LoadGL(), logfile_open(), logfile_write(), MVD_GameInit(), MVD_GameShutdown(), MVD_Spawn(), R_BeginRegistration_RTX(), ready_to_send(), SCR_PlayCinematic(), SCR_StopCinematic(), SetRconAddress(), SV_InitGame(), SV_InitGameProgs(), SV_MvdInit(), SV_MvdMapChanged(), SV_NextServer_f(), SV_ParseMapCmd(), SV_SetMaster_f(), SV_Shutdown(), SV_ShutdownGameProgs(), SV_SpawnServer(), upload_world_surfaces(), VID_Init(), VID_ToggleFullscreen(), win_disablewinkey_changed(), Win_Init(), and Win_InitMouse().
Cvar_Set_c()
static void Cvar_Set_c (genctx_t * ctx, int argnum) static
Definition at line 689 of file cvar.c.
 {
     char *s;
     cvar_t *var;
     xgenerator_t g;
     if (argnum == 1) {
         Cvar_Variable_g(ctx);
     } else if (argnum == 2) {
         s = Cmd_Argv(ctx->argnum - 1);
         if ((var = Cvar_FindVar(s)) != NULL) {
             g = var->generator;
             if (g) {
                 ctx->data = var;
                 g(ctx);
             }
         }
     }
 }
Cvar_Set_f()
void Cvar_Set_f (void)
Definition at line 717 of file cvar.c.
 {
     int     c, flags;
     char    *f;
     c = Cmd_Argc();
     if (c < 3) {
         Com_Printf("Usage: set <variable> <value> [u / s]\n");
         return;
     }
     if (c == 3) {
         Cvar_SetEx(Cmd_Argv(1), Cmd_Argv(2), Cmd_From());
         return;
     }
     if (c == 4) {
         f = Cmd_Argv(3);
         if (!strcmp(f, "u")) {
             flags = CVAR_USERINFO;
         } else if (!strcmp(f, "s")) {
             flags = CVAR_SERVERINFO;
         } else {
             goto set;
         }
         Cvar_FullSet(Cmd_Argv(1), Cmd_Argv(2), flags, Cmd_From());
         return;
     }
 set:
     Cvar_SetEx(Cmd_Argv(1), Cmd_ArgsFrom(2), Cmd_From());
 }
Cvar_SetByVar()
void Cvar_SetByVar (cvar_t * var, const char * value, from_t from)
Definition at line 345 of file cvar.c.
 {
     if (!value) {
         value = "";
     }
     if (!strcmp(value, var->string)) {
         set_back_cvar(var);
         return; // not changed
     }
     if (var->flags & CVAR_INFOMASK) {
         if (!validate_info_cvar(value)) {
             return;
         }
     }
     // some cvars may not be changed by user at all
     if (from != FROM_CODE) {
         if (var->flags & CVAR_ROM) {
             Com_Printf("%s is read-only.\n", var->name);
             return;
         }
         if (var->flags & CVAR_CHEAT) {
             if (!CL_CheatsOK()) {
                 Com_Printf("%s is cheat protected.\n", var->name);
                 return;
             }
         }
     }
     // some cvars may require special processing if set by user from console
     if (from <= FROM_CONSOLE && com_initialized) {
         if (var->flags & CVAR_NOSET) {
             Com_Printf("%s may be set from command line only.\n", var->name);
             return;
         }
         if (var->flags & CVAR_LATCH) {
             // free latched value
             if (var->latched_string) {
                 if (!strcmp(var->latched_string, value)) {
                     return; // latched string not changed
                 }
                 Z_Free(var->latched_string);
                 var->latched_string = NULL;
             }
             if (sv_running->integer) {
                 Com_Printf("%s will be changed for next game.\n", var->name);
                 var->latched_string = Z_CvarCopyString(value);
                 return;
             }
             // server is down, it's ok to update this cvar now
         }
     }
     // free latched string, if any
     if (var->latched_string) {
         Z_Free(var->latched_string);
         var->latched_string = NULL;
     }
     change_string_value(var, value, from);
 }
Referenced by AC_Connect(), AC_Disable(), Cvar_ClampInteger(), Cvar_ClampValue(), Cvar_Command(), Cvar_FixCheats(), Cvar_FullSet(), Cvar_Inc_f(), Cvar_Reset_f(), Cvar_ResetAll_f(), Cvar_SetEx(), Cvar_SetInteger(), Cvar_SetValue(), Cvar_Toggle_f(), Field_Pop(), Pairs_Pop(), R_InterceptKey_RTX(), Strings_Pop(), VID_SetGeometry(), vkpt_freecam_reset(), vkpt_freecam_update(), and vkpt_next_sun_preset().
Cvar_SetEx()
cvar_t* Cvar_SetEx (const char * var_name, const char * value, from_t from)
Definition at line 417 of file cvar.c.
 {
     cvar_t    *var;
     var = Cvar_FindVar(var_name);
     if (!var) {
         // create it
         return Cvar_Get(var_name, value, CVAR_CUSTOM);
     }
     Cvar_SetByVar(var, value, from);
     return var;
 }
Referenced by Com_AddEarlyCommands(), Cvar_Set(), Cvar_Set_f(), Cvar_SetFlag_f(), Cvar_UserSet(), and Pop().
Cvar_SetFlag_f()
static void Cvar_SetFlag_f (void) static
Definition at line 757 of file cvar.c.
 {
     char    *s = Cmd_Argv(0);
     int     flags;
     if (Cmd_Argc() < 3) {
         Com_Printf("Usage: %s <variable> <value>\n", s);
         return;
     }
     if (!strcmp(s, "seta")) {
         cvar_t *var = Cvar_SetEx(Cmd_Argv(1), Cmd_ArgsFrom(2), Cmd_From());
         if (var && !(var->flags & CVAR_NOARCHIVEMASK))
             var->flags |= CVAR_ARCHIVE;
         return;
     }
     if (!strcmp(s, "setu")) {
         flags = CVAR_USERINFO;
     } else if (!strcmp(s, "sets")) {
         flags = CVAR_SERVERINFO;
     } else {
         return;
     }
     Cvar_FullSet(Cmd_Argv(1), Cmd_ArgsFrom(2), flags, Cmd_From());
 }
Cvar_SetInteger()
void Cvar_SetInteger (cvar_t * var, int value, from_t from)
Definition at line 509 of file cvar.c.
 {
     char    val[32];
     if (var->integer == value) {
         set_back_cvar(var);
         return; // not changed
     }
     Q_snprintf(val, sizeof(val), "%i", value);
     Cvar_SetByVar(var, val, from);
 }
Referenced by BitField_Pop(), MVD_Spawn(), R_EndFrame_RTX(), S_Init(), SCR_SizeDown_f(), SCR_SizeUp_f(), set_frame_time(), SpinControl_Pop(), SV_InitGame(), SV_SpawnServer(), and Toggle_Pop().
Cvar_SetValue()
void Cvar_SetValue (cvar_t * var, float value, from_t from)
Definition at line 487 of file cvar.c.
 {
     char    val[32];
     if (var->value == value) {
         set_back_cvar(var);
         return; // not changed
     }
     if (value == (int)value)
         Q_snprintf(val, sizeof(val), "%i", (int)value);
     else
         Q_snprintf(val, sizeof(val), "%f", value);
     Cvar_SetByVar(var, val, from);
 }
Referenced by OGG_RecoverState(), R_ClampScale(), Slider_Pop(), and UpdatePhysicalSkyCVars().
Cvar_Toggle_c()
static void Cvar_Toggle_c (genctx_t * ctx, int argnum) static
Definition at line 1004 of file cvar.c.
 {
     char *s;
     xgenerator_t g;
     if (argnum == 1) {
         Cvar_Variable_g(ctx);
     } else {
         s = Cmd_Argv(ctx->argnum - argnum + 1);
         if ((g = Cvar_FindGenerator(s)) != NULL) {
             g(ctx);
         }
     }
 }
Cvar_Toggle_f()
static void Cvar_Toggle_f (void) static
Definition at line 965 of file cvar.c.
 {
     cvar_t *var;
     int i, argc = Cmd_Argc();
     if (argc < 2) {
         Com_Printf("Usage: %s <variable> [values]\n", Cmd_Argv(0));
         return;
     }
     var = Cvar_FindVar(Cmd_Argv(1));
     if (!var) {
         Com_Printf("%s is not a variable\n", Cmd_Argv(1));
         return;
     }
     if (argc < 3) {
         if (!strcmp(var->string, "0")) {
             Cvar_SetByVar(var, "1", Cmd_From());
         } else if (!strcmp(var->string, "1")) {
             Cvar_SetByVar(var, "0", Cmd_From());
         } else {
             Com_Printf("\"%s\" is \"%s\", can't toggle\n",
                        var->name, var->string);
         }
         return;
     }
     for (i = 0; i < argc - 2; i++) {
         if (!Q_stricmp(var->string, Cmd_Argv(2 + i))) {
             i = (i + 1) % (argc - 2);
             Cvar_SetByVar(var, Cmd_Argv(2 + i), Cmd_From());
             return;
         }
     }
     Com_Printf("\"%s\" is \"%s\", can't cycle\n", var->name, var->string);
 }
Cvar_UserSet()
cvar_t* Cvar_UserSet (const char * var_name, const char * value)
Definition at line 476 of file cvar.c.
 {
     return Cvar_SetEx(var_name, value, FROM_CONSOLE);
 }
Referenced by CL_ParseServerData(), MVD_ParseServerData(), read_server_file(), and SV_InitGameProgs().
Cvar_Variable_g()
void Cvar_Variable_g (genctx_t * ctx)
Definition at line 133 of file cvar.c.
 {
     cvar_t *c;
     for (c = cvar_vars; c; c = c->next) {
         if (!Prompt_AddMatch(ctx, c->name)) {
             break;
         }
     }
 }
Referenced by Com_Generic_c(), Cvar_Reset_c(), Cvar_Set_c(), Cvar_Toggle_c(), Prompt_CompleteCommand(), and SCR_Draw_c().
Cvar_VariableInteger()
int Cvar_VariableInteger (const char * var_name)
Definition at line 105 of file cvar.c.
 {
     cvar_t *var;
     var = Cvar_FindVar(var_name);
     if (!var)
         return 0;
     return var->integer;
 }
Referenced by CL_CheatsOK(), Push(), SV_InitGame(), SV_NextServer_f(), SV_NoSaveGames(), SV_Savegame_f(), and SV_SpawnServer().
Cvar_VariableString()
char* Cvar_VariableString (const char * var_name)
Definition at line 122 of file cvar.c.
 {
     cvar_t *var;
     var = Cvar_FindVar(var_name);
     if (!var)
         return "";
     return var->string;
 }
Referenced by finish_demo(), Push(), and SV_NextServer_f().
Cvar_VariableValue()
float Cvar_VariableValue (const char * var_name)
Definition at line 89 of file cvar.c.
 {
     cvar_t    *var;
     var = Cvar_FindVar(var_name);
     if (!var)
         return 0;
     return var->value;
 }
Referenced by SCR_PlayCinematic().
Cvar_WeakGet()
cvar_t* Cvar_WeakGet (const char * var_name)
Definition at line 324 of file cvar.c.
 {
     return Cvar_Get(var_name, "", CVAR_WEAK);
 }
Referenced by Parse_Field(), Parse_If(), Parse_Pairs(), Parse_Range(), Parse_Spin(), Parse_Toggle(), SCR_Draw_f(), SCR_UnDraw_f(), and SV_SpawnServer().
get_engine_cvar()
static void get_engine_cvar (cvar_t * var, const char * var_value, int flags) static
Definition at line 219 of file cvar.c.
 {
     if (var->flags & (CVAR_CUSTOM | CVAR_WEAK)) {
         // update default string if cvar was set from command line
         Z_Free(var->default_string);
         var->default_string = Z_CvarCopyString(var_value);
         // see if it was changed from it's default value
         if (strcmp(var_value, var->string)) {
             if ((flags & CVAR_ROM) ||
                 ((flags & CVAR_NOSET) && com_initialized) ||
                 ((flags & CVAR_CHEAT) && !CL_CheatsOK()) ||
                 ((flags & CVAR_INFOMASK) && !validate_info_cvar(var->string)) ||
                 (var->flags & CVAR_WEAK)) {
                 // restricted cvars are reset back to default value
                 change_string_value(var, var_value, FROM_CODE);
             } else {
                 // normal cvars are just flagged as modified by user
                 flags |= CVAR_MODIFIED;
             }
         }
     } else {
         flags &= ~CVAR_GAME;
     }
     // some flags are not saved
     var->flags &= ~(CVAR_GAME | CVAR_CUSTOM | CVAR_WEAK);
     var->flags |= flags;
 }
Referenced by Cvar_Get().
parse_string_value()
static void parse_string_value (cvar_t * var) static
Definition at line 157 of file cvar.c.
 {
     char *s = var->string;
     if (s[0] == '0' && s[1] == 'x') {
         long v = strtol(s, NULL, 16);
         var->integer = clamp(v, INT_MIN, INT_MAX);
         var->value = (float)var->integer;
     } else {
         var->integer = atoi(var->string);
         var->value = atof(var->string);
     }
 }
Referenced by change_string_value(), Cvar_Get(), and Cvar_GetLatchedVars().
set_back_cvar()
static void set_back_cvar (cvar_t * var) static
Definition at line 329 of file cvar.c.
 {
     if (var->flags & CVAR_LATCH) {
         // set back to current value
         if (var->latched_string) {
             Z_Free(var->latched_string);
             var->latched_string = NULL;
         }
     }
 }
Referenced by Cvar_SetByVar(), Cvar_SetInteger(), and Cvar_SetValue().
validate_info_cvar()
static qboolean validate_info_cvar (const char * s) static
Definition at line 198 of file cvar.c.
 {
     size_t len = Info_SubValidate(s);
     if (len == SIZE_MAX) {
         Com_Printf("Info cvars should not contain '\\', ';' or '\"' characters.\n");
         return qfalse;
     }
     if (len >= MAX_QPATH) {
         Com_Printf("Info cvars should be less than 64 characters long.\n");
         return qfalse;
     }
     return qtrue;
 }
Referenced by Cvar_Get(), Cvar_SetByVar(), and get_engine_cvar().
Variable Documentation
c_cvar
const cmdreg_t c_cvar[] static
Initial value:
= {
    { "set", Cvar_Set_f, Cvar_Set_c },
    { "setu", Cvar_SetFlag_f, Cvar_Set_c },
    { "sets", Cvar_SetFlag_f, Cvar_Set_c },
    { "seta", Cvar_SetFlag_f, Cvar_Set_c },
    { "cvarlist", Cvar_List_f, Cvar_List_c },
    { "toggle", Cvar_Toggle_f, Cvar_Toggle_c },
    { "inc", Cvar_Inc_f, Cvar_Reset_c },
    { "dec", Cvar_Inc_f, Cvar_Reset_c },
    { "reset", Cvar_Reset_f, Cvar_Reset_c },
    { "resetall", Cvar_ResetAll_f },
    { NULL }
}
Definition at line 1149 of file cvar.c.
Referenced by Cvar_Init().
cvar_modified
int cvar_modified
Definition at line 32 of file cvar.c.
Referenced by change_string_value(), CL_InitRefresh(), CL_RestartFilesystem(), CL_RestartRefresh(), CL_RunRefresh(), Cvar_GetLatchedVars(), and S_Update().
cvar_vars
cvar_t* cvar_vars
Definition at line 30 of file cvar.c.
Referenced by Cvar_BitInfo(), Cvar_CountLatchedVars(), Cvar_FixCheats(), Cvar_Get(), Cvar_GetLatchedVars(), Cvar_List_f(), Cvar_ResetAll_f(), Cvar_Variable_g(), and write_server_file().
cvarHash
cvar_t* cvarHash[CVARHASH_SIZE] static
Definition at line 38 of file cvar.c.
Referenced by Cvar_FindVar(), and Cvar_Get().
o_cvarlist
const cmd_option_t o_cvarlist[] static
Initial value:
= {
    { "a", "archive", "list archived cvars" },
    { "c", "cheat", "list cheat protected cvars" },
    { "h", "help", "display this help message" },
    { "l", "latched", "list latched cvars" },
    { "m", "modified", "list modified cvars" },
    { "n", "noset", "list command line cvars" },
    { "r", "rom", "list read-only cvars" },
    { "s", "serverinfo", "list serverinfo cvars" },
    { "t", "custom", "list user-created cvars" },
    { "u", "userinfo", "list userinfo cvars" },
    { "v", "verbose", "display flags of each cvar" },
    { "w:string", "wildcard", "list cvars matching wildcard" },
    { NULL }
}
Definition at line 824 of file cvar.c.
Referenced by Cvar_List_c(), and Cvar_List_f().