Quake II RTX doxygen: C:/entry/dev/Q2RTX/src/refresh/vkpt/vkpt.h File Reference
vkpt.h File Reference
#include <vulkan/vulkan.h>
#include <SDL.h>
#include <SDL_vulkan.h>
#include "vk_util.h"
#include "shared/shared.h"
#include "common/bsp.h"
#include "common/cmd.h"
#include "common/common.h"
#include "common/cvar.h"
#include "common/files.h"
#include "common/math.h"
#include "client/video.h"
#include "client/client.h"
#include "refresh/refresh.h"
#include "refresh/images.h"
#include "refresh/models.h"
#include "system/hunk.h"
#include "shader/global_ubo.h"
#include "shader/global_textures.h"
#include "shader/vertex_buffer.h"
Classes
struct cmd_buf_group_s
struct semaphore_group_s
struct QVK_s
struct light_poly_s
struct bsp_model_s
struct aabb_s
struct bsp_mesh_s
struct vkpt_refdef_s
struct sun_light_s
struct EntityUploadInfo
struct maliasframe_s
struct maliasmesh_s
struct drawStatic_t
Macros
#define HAVE_M_PI
#define LENGTH(a) ((sizeof (a)) / (sizeof(*(a))))
#define MIN(a, b) ((a) < (b) ? (a) : (b))
#define MAX(a, b) ((a) > (b) ? (a) : (b))
#define LOG_FUNC_(f) do {} while(0)
#define LOG_FUNC() LOG_FUNC_(__func__)
#define _VK(...) do { __VA_ARGS__; } while(0)
#define LIST_SHADER_MODULES
#define VKPT_SHADER_DIR "shader_vkpt"
#define SHADER_PATH_TEMPLATE VKPT_SHADER_DIR "/%s.spv"
#define SHADER_STAGE(_module, _stage)
#define SHADER_STAGE_SPEC(_module, _stage, _spec)
#define SHADER_MODULE_DO(a) a,
#define MAX_FRAMES_IN_FLIGHT 2
#define MAX_SWAPCHAIN_IMAGES 4
#define _VK_INST_EXTENSION_LIST
#define _VK_INST_EXTENSION_DO(a) extern PFN_##a q##a;
#define _VK_EXTENSION_LIST
#define _VK_EXTENSION_DO(a) extern PFN_##a q##a;
#define MAX_SKY_CLUSTERS 1024
#define PROFILER_LIST
#define PROFILER_DO(a, ...) a,
#define NUM_PROFILER_QUERIES_PER_FRAME (NUM_PROFILER_ENTRIES * 2)
#define ALL_GPUS (-1)
#define TESS_MAX_VERTICES 16384
#define TESS_MAX_INDICES (3 * TESS_MAX_VERTICES)
#define QGL_INDEX_TYPE GLuint
#define BEGIN_PERF_MARKER(command_buffer, name) begin_perf_marker(command_buffer, name, #name)
#define END_PERF_MARKER(command_buffer, name) end_perf_marker(command_buffer, name)
Typedefs
typedef struct cmd_buf_group_s cmd_buf_group_t
typedef struct semaphore_group_s semaphore_group_t
typedef struct QVK_s QVK_t
typedef struct light_poly_s light_poly_t
typedef struct bsp_model_s bsp_model_t
typedef struct aabb_s aabb_t
typedef struct bsp_mesh_s bsp_mesh_t
typedef struct vkpt_refdef_s vkpt_refdef_t
typedef struct sun_light_s sun_light_t
typedef struct EntityUploadInfo EntityUploadInfo
typedef struct maliasframe_s maliasframe_t
typedef struct maliasmesh_s maliasmesh_t
Enumerations
enum QVK_SHADER_MODULES { NUM_QVK_SHADER_MODULES }
enum { NUM_PROFILER_ENTRIES }
enum VKPTProfilerAction { PROFILER_START, PROFILER_STOP }
Functions
void bsp_mesh_create_from_bsp (bsp_mesh_t *wm, bsp_t *bsp, const char *map_name)
void bsp_mesh_destroy (bsp_mesh_t *wm)
void bsp_mesh_register_textures (bsp_t *bsp)
void mult_matrix_matrix (float *p, const float *a, const float *b)
void mult_matrix_vector (float *p, const float *a, const float *b)
void create_entity_matrix (float matrix[16], entity_t *e, qboolean enable_left_hand)
void create_projection_matrix (float matrix[16], float znear, float zfar, float fov_x, float fov_y)
void create_view_matrix (float matrix[16], refdef_t *fd)
void inverse (const float *m, float *inv)
void create_orthographic_matrix (float matrix[16], float xmin, float xmax, float ymin, float ymax, float znear, float zfar)
VkDescriptorSet qvk_get_current_desc_set_textures ()
VkResult vkpt_profiler_initialize ()
VkResult vkpt_profiler_destroy ()
VkResult vkpt_profiler_query (VkCommandBuffer cmd_buf, int idx, VKPTProfilerAction action)
VkResult vkpt_profiler_next_frame (VkCommandBuffer cmd_buf)
void draw_profiler (int enable_asvgf)
double vkpt_get_profiler_result (int idx)
VkResult vkpt_readback (struct ReadbackBuffer *dst)
VkResult vkpt_textures_initialize ()
VkResult vkpt_textures_destroy ()
VkResult vkpt_textures_end_registration ()
VkResult vkpt_textures_upload_envmap (int w, int h, byte *data)
void vkpt_textures_destroy_unused ()
void vkpt_textures_update_descriptor_set ()
void vkpt_normalize_normal_map (image_t *image)
void vkpt_extract_emissive_texture_info (image_t *image)
void vkpt_textures_prefetch ()
void vkpt_init_light_textures ()
VkCommandBuffer vkpt_begin_command_buffer (cmd_buf_group_t *group)
void vkpt_free_command_buffers (cmd_buf_group_t *group)
void vkpt_reset_command_buffers (cmd_buf_group_t *group)
void vkpt_wait_idle (VkQueue queue, cmd_buf_group_t *group)
void vkpt_submit_command_buffer (VkCommandBuffer cmd_buf, VkQueue queue, uint32_t execute_device_mask, int wait_semaphore_count, VkSemaphore *wait_semaphores, VkPipelineStageFlags *wait_stages, uint32_t *wait_device_indices, int signal_semaphore_count, VkSemaphore *signal_semaphores, uint32_t *signal_device_indices, VkFence fence)
void vkpt_submit_command_buffer_simple (VkCommandBuffer cmd_buf, VkQueue queue, qboolean all_gpus)
void set_current_gpu (VkCommandBuffer cmd_buf, int gpu_index)
VkResult allocate_gpu_memory (VkMemoryRequirements mem_req, VkDeviceMemory *pMemory)
void vkpt_image_copy (VkCommandBuffer cmd_buf, int src_image_index, int dst_image_index, VkOffset2D src_offset, VkOffset2D dst_offset, VkExtent2D size)
VkResult vkpt_draw_initialize ()
VkResult vkpt_draw_destroy ()
VkResult vkpt_draw_destroy_pipelines ()
VkResult vkpt_draw_create_pipelines ()
VkResult vkpt_draw_submit_stretch_pics (VkCommandBuffer cmd_buf)
VkResult vkpt_final_blit_simple (VkCommandBuffer cmd_buf)
VkResult vkpt_final_blit_filtered (VkCommandBuffer cmd_buf)
VkResult vkpt_draw_clear_stretch_pics ()
VkResult vkpt_uniform_buffer_create ()
VkResult vkpt_uniform_buffer_destroy ()
VkResult vkpt_uniform_buffer_update (VkCommandBuffer command_buffer)
VkResult vkpt_vertex_buffer_create ()
VkResult vkpt_vertex_buffer_destroy ()
VkResult vkpt_vertex_buffer_upload_bsp_mesh_to_staging (bsp_mesh_t *bsp_mesh)
VkResult vkpt_vertex_buffer_create_pipelines ()
VkResult vkpt_vertex_buffer_destroy_pipelines ()
VkResult vkpt_vertex_buffer_create_instance (VkCommandBuffer cmd_buf, uint32_t num_instances, qboolean update_world_animations)
VkResult vkpt_vertex_buffer_upload_models_to_staging ()
VkResult vkpt_vertex_buffer_upload_staging ()
void vkpt_light_buffer_reset_counts ()
VkResult vkpt_light_buffer_upload_to_staging (qboolean render_world, bsp_mesh_t *bsp_mesh, bsp_t *bsp, int num_model_lights, light_poly_t *transformed_model_lights, const float *sky_radiance)
VkResult vkpt_light_buffer_upload_staging (VkCommandBuffer cmd_buf)
VkResult vkpt_light_stats_create (bsp_mesh_t *bsp_mesh)
VkResult vkpt_light_stats_destroy ()
VkResult vkpt_load_shader_modules ()
VkResult vkpt_destroy_shader_modules ()
VkResult vkpt_create_images ()
VkResult vkpt_destroy_images ()
VkResult vkpt_pt_init ()
VkResult vkpt_pt_destroy ()
VkResult vkpt_pt_create_pipelines ()
VkResult vkpt_pt_destroy_pipelines ()
VkResult vkpt_pt_create_toplevel (VkCommandBuffer cmd_buf, int idx, qboolean include_world, qboolean weapon_left_handed)
VkResult vkpt_pt_create_static (VkBuffer vertex_buffer, size_t buffer_offset, int num_vertices, int num_vertices_transparent, int num_vertices_sky, int num_vertices_custom_sky)
VkResult vkpt_pt_destroy_static ()
VkResult vkpt_pt_trace_primary_rays (VkCommandBuffer cmd_buf)
VkResult vkpt_pt_trace_reflections (VkCommandBuffer cmd_buf, int bounce)
VkResult vkpt_pt_trace_lighting (VkCommandBuffer cmd_buf, float num_bounce_rays)
VkResult vkpt_pt_update_descripter_set_bindings (int idx)
VkResult vkpt_pt_create_all_dynamic (VkCommandBuffer cmd_buf, int idx, VkBuffer vertex_buffer, const EntityUploadInfo *upload_info)
VkResult vkpt_asvgf_initialize ()
VkResult vkpt_asvgf_destroy ()
VkResult vkpt_asvgf_create_pipelines ()
VkResult vkpt_asvgf_destroy_pipelines ()
VkResult vkpt_asvgf_filter (VkCommandBuffer cmd_buf, qboolean enable_lf)
VkResult vkpt_compositing (VkCommandBuffer cmd_buf)
VkResult vkpt_interleave (VkCommandBuffer cmd_buf)
VkResult vkpt_taa (VkCommandBuffer cmd_buf)
VkResult vkpt_asvgf_create_gradient_samples (VkCommandBuffer cmd_buf, uint32_t frame_num, int do_gradient_samples)
VkResult vkpt_bloom_initialize ()
VkResult vkpt_bloom_destroy ()
VkResult vkpt_bloom_create_pipelines ()
VkResult vkpt_bloom_destroy_pipelines ()
void vkpt_bloom_reset ()
void vkpt_bloom_update (QVKUniformBuffer_t *ubo, float frame_time, qboolean under_water, qboolean menu_mode)
VkResult vkpt_bloom_record_cmd_buffer (VkCommandBuffer cmd_buf)
VkResult vkpt_tone_mapping_initialize ()
VkResult vkpt_tone_mapping_destroy ()
VkResult vkpt_tone_mapping_create_pipelines ()
VkResult vkpt_tone_mapping_reset (VkCommandBuffer cmd_buf)
VkResult vkpt_tone_mapping_destroy_pipelines ()
VkResult vkpt_tone_mapping_record_cmd_buffer (VkCommandBuffer cmd_buf, float frame_time)
void vkpt_tone_mapping_request_reset ()
VkResult vkpt_shadow_map_initialize ()
VkResult vkpt_shadow_map_destroy ()
VkResult vkpt_shadow_map_create_pipelines ()
VkResult vkpt_shadow_map_destroy_pipelines ()
VkResult vkpt_shadow_map_render (VkCommandBuffer cmd_buf, float *view_projection_matrix, int num_static_verts, int num_dynamic_verts, int transparent_offset, int num_transparent_verts)
VkImageView vkpt_shadow_map_get_view ()
void vkpt_shadow_map_setup (const sun_light_t *light, const float *bbox_min, const float *bbox_max, float *VP, float *depth_scale, qboolean random_sampling)
qerror_t load_img (const char *name, image_t *image)
qboolean initialize_transparency ()
void destroy_transparency ()
void update_transparency (VkCommandBuffer command_buffer, const float *view_matrix, const particle_t *particles, int particle_num, const entity_t *entities, int entity_num)
void build_transparency_blas (VkCommandBuffer cmd_buf)
VkAccelerationStructureNV get_transparency_particle_blas ()
VkAccelerationStructureNV get_transparency_beam_blas ()
VkAccelerationStructureNV get_transparency_sprite_blas ()
VkBufferView get_transparency_particle_color_buffer_view ()
VkBufferView get_transparency_beam_color_buffer_view ()
VkBufferView get_transparency_sprite_info_buffer_view ()
void get_transparency_counts (int *particle_num, int *beam_num, int *sprite_num)
void vkpt_build_beam_lights (light_poly_t *light_list, int *num_lights, int max_lights, bsp_t *bsp, entity_t *entities, int num_entites, float adapted_luminance)
qboolean vkpt_build_cylinder_light (light_poly_t *light_list, int *num_lights, int max_lights, bsp_t *bsp, vec3_t begin, vec3_t end, vec3_t color, float radius)
qboolean get_triangle_off_center (const float *positions, float *center, float *anti_center)
VkResult vkpt_initialize_god_rays ()
VkResult vkpt_destroy_god_rays ()
VkResult vkpt_god_rays_create_pipelines ()
VkResult vkpt_god_rays_destroy_pipelines ()
VkResult vkpt_god_rays_update_images ()
VkResult vkpt_god_rays_noop ()
qboolean vkpt_god_rays_enabled (const sun_light_t *sun_light)
void vkpt_record_god_rays_trace_command_buffer (VkCommandBuffer command_buffer, int pass)
void vkpt_record_god_rays_filter_command_buffer (VkCommandBuffer command_buffer)
void vkpt_god_rays_prepare_ubo (QVKUniformBuffer_t *ubo, const aabb_t *world_aabb, const float *proj, const float *view, const float *shadowmap_viewproj, float shadowmap_depth_scale)
void vkpt_freecam_reset ()
void vkpt_freecam_update (float frame_time)
void vkpt_reset_accumulation ()
static void begin_perf_marker (VkCommandBuffer command_buffer, int index, const char *name)
static void end_perf_marker (VkCommandBuffer command_buffer, int index)
void R_SetClipRect_RTX (const clipRect_t *clip)
void R_ClearColor_RTX (void)
void R_SetAlpha_RTX (float alpha)
void R_SetAlphaScale_RTX (float alpha)
void R_SetColor_RTX (uint32_t color)
void R_LightPoint_RTX (vec3_t origin, vec3_t light)
void R_SetScale_RTX (float scale)
void R_DrawStretchPic_RTX (int x, int y, int w, int h, qhandle_t pic)
void R_DrawPic_RTX (int x, int y, qhandle_t pic)
void R_TileClear_RTX (int x, int y, int w, int h, qhandle_t pic)
void R_DrawFill8_RTX (int x, int y, int w, int h, int c)
void R_DrawFill32_RTX (int x, int y, int w, int h, uint32_t color)
void R_DrawChar_RTX (int x, int y, int flags, int c, qhandle_t font)
int R_DrawString_RTX (int x, int y, int flags, size_t maxlen, const char *s, qhandle_t font)
qboolean R_InterceptKey_RTX (unsigned key, qboolean down)
void IMG_Load_RTX (image_t *image, byte *pic)
void IMG_Unload_RTX (image_t *image)
byte * IMG_ReadPixels_RTX (int *width, int *height, int *rowbytes)
qerror_t MOD_LoadMD2_RTX (model_t *model, const void *rawdata, size_t length)
qerror_t MOD_LoadMD3_RTX (model_t *model, const void *rawdata, size_t length)
void MOD_Reference_RTX (model_t *model)
Variables
QVK_t qvk
vkpt_refdef_t vkpt_refdef
drawStatic_t draw
Macro Definition Documentation
_VK
#define _VK (...) do { __VA_ARGS__; } while(0)
Definition at line 65 of file vkpt.h.
_VK_EXTENSION_DO
#define _VK_EXTENSION_DO (a) extern PFN_##a q##a;
Definition at line 309 of file vkpt.h.
_VK_EXTENSION_LIST
#define _VK_EXTENSION_LIST
Value:
    _VK_EXTENSION_DO(vkCreateAccelerationStructureNV) \
    _VK_EXTENSION_DO(vkCreateAccelerationStructureNV) \
    _VK_EXTENSION_DO(vkDestroyAccelerationStructureNV) \
    _VK_EXTENSION_DO(vkGetAccelerationStructureMemoryRequirementsNV) \
    _VK_EXTENSION_DO(vkBindAccelerationStructureMemoryNV) \
    _VK_EXTENSION_DO(vkCmdBuildAccelerationStructureNV) \
    _VK_EXTENSION_DO(vkCmdCopyAccelerationStructureNV) \
    _VK_EXTENSION_DO(vkCmdTraceRaysNV) \
    _VK_EXTENSION_DO(vkCreateRayTracingPipelinesNV) \
    _VK_EXTENSION_DO(vkGetRayTracingShaderGroupHandlesNV) \
    _VK_EXTENSION_DO(vkGetAccelerationStructureHandleNV) \
    _VK_EXTENSION_DO(vkCmdWriteAccelerationStructuresPropertiesNV) \
    _VK_EXTENSION_DO(vkCompileDeferredNV) \
    _VK_EXTENSION_DO(vkDebugMarkerSetObjectNameEXT) \
    _VK_EXTENSION_DO(vkGetDeviceGroupPeerMemoryFeaturesKHR) \
    _VK_EXTENSION_DO(vkCmdSetDeviceMaskKHR) \
    _VK_EXTENSION_DO(vkCmdDispatchBaseKHR) \
    _VK_EXTENSION_DO(vkGetDeviceGroupPresentCapabilitiesKHR) \
    _VK_EXTENSION_DO(vkGetDeviceGroupSurfacePresentModesKHR) \
    _VK_EXTENSION_DO(vkGetPhysicalDevicePresentRectanglesKHR) \
    _VK_EXTENSION_DO(vkAcquireNextImage2KHR) \
    _VK_EXTENSION_DO(vkBindImageMemory2KHR)
Definition at line 284 of file vkpt.h.
_VK_INST_EXTENSION_DO
#define _VK_INST_EXTENSION_DO (a) extern PFN_##a q##a;
Definition at line 280 of file vkpt.h.
_VK_INST_EXTENSION_LIST
#define _VK_INST_EXTENSION_LIST
Value:
    _VK_INST_EXTENSION_DO(vkCmdBeginDebugUtilsLabelEXT) \
    _VK_INST_EXTENSION_DO(vkCmdEndDebugUtilsLabelEXT) \
    _VK_INST_EXTENSION_DO(vkEnumeratePhysicalDeviceGroupsKHR)
Definition at line 275 of file vkpt.h.
ALL_GPUS
#define ALL_GPUS (-1)
Definition at line 535 of file vkpt.h.
BEGIN_PERF_MARKER
#define BEGIN_PERF_MARKER (command_buffer, name) begin_perf_marker(command_buffer, name, #name)
Definition at line 742 of file vkpt.h.
END_PERF_MARKER
#define END_PERF_MARKER (command_buffer, name) end_perf_marker(command_buffer, name)
Definition at line 743 of file vkpt.h.
HAVE_M_PI
#define HAVE_M_PI
Definition at line 24 of file vkpt.h.
LENGTH
#define LENGTH (a) ((sizeof (a)) / (sizeof(*(a))))
Definition at line 48 of file vkpt.h.
LIST_SHADER_MODULES
#define LIST_SHADER_MODULES
Definition at line 70 of file vkpt.h.
LOG_FUNC
#define LOG_FUNC () LOG_FUNC_(__func__)
Definition at line 54 of file vkpt.h.
LOG_FUNC_
#define LOG_FUNC_ (f) do {} while(0)
Definition at line 52 of file vkpt.h.
MAX
#define MAX (a, b) ((a) > (b) ? (a) : (b))
Definition at line 50 of file vkpt.h.
MAX_FRAMES_IN_FLIGHT
#define MAX_FRAMES_IN_FLIGHT 2
Definition at line 140 of file vkpt.h.
MAX_SKY_CLUSTERS
#define MAX_SKY_CLUSTERS 1024
Definition at line 313 of file vkpt.h.
MAX_SWAPCHAIN_IMAGES
#define MAX_SWAPCHAIN_IMAGES 4
Definition at line 141 of file vkpt.h.
MIN
#define MIN (a, b) ((a) < (b) ? (a) : (b))
Definition at line 49 of file vkpt.h.
NUM_PROFILER_QUERIES_PER_FRAME
#define NUM_PROFILER_QUERIES_PER_FRAME (NUM_PROFILER_ENTRIES * 2)
Definition at line 466 of file vkpt.h.
PROFILER_DO
#define PROFILER_DO (a, ...) a,
Definition at line 460 of file vkpt.h.
PROFILER_LIST
#define PROFILER_LIST
Value:
    PROFILER_DO(PROFILER_FRAME_TIME,                 0) \
    PROFILER_DO(PROFILER_INSTANCE_GEOMETRY,          1) \
    PROFILER_DO(PROFILER_BVH_UPDATE,                 1) \
    PROFILER_DO(PROFILER_ASVGF_GRADIENT_SAMPLES,     1) \
    PROFILER_DO(PROFILER_ASVGF_DO_GRADIENT_SAMPLES,  2) \
    PROFILER_DO(PROFILER_PRIMARY_RAYS,               1) \
    PROFILER_DO(PROFILER_REFLECT_REFRACT_1,          1) \
    PROFILER_DO(PROFILER_REFLECT_REFRACT_2,          1) \
    PROFILER_DO(PROFILER_DIRECT_LIGHTING,            1) \
    PROFILER_DO(PROFILER_INDIRECT_LIGHTING,          1) \
    PROFILER_DO(PROFILER_ASVGF_FULL,                 1) \
    PROFILER_DO(PROFILER_ASVGF_RECONSTRUCT_GRADIENT, 2) \
    PROFILER_DO(PROFILER_ASVGF_TEMPORAL,             2) \
    PROFILER_DO(PROFILER_ASVGF_ATROUS,               2) \
    PROFILER_DO(PROFILER_MGPU_TRANSFERS,             1) \
    PROFILER_DO(PROFILER_INTERLEAVE,                 1) \
    PROFILER_DO(PROFILER_ASVGF_TAA,                  2) \
    PROFILER_DO(PROFILER_BLOOM,                      1) \
    PROFILER_DO(PROFILER_TONE_MAPPING,               1) \
    PROFILER_DO(PROFILER_UPDATE_ENVIRONMENT,         1) \
    PROFILER_DO(PROFILER_GOD_RAYS,                   1) \
    PROFILER_DO(PROFILER_GOD_RAYS_REFLECT_REFRACT,   1) \
    PROFILER_DO(PROFILER_GOD_RAYS_FILTER,            1) \
    PROFILER_DO(PROFILER_SHADOW_MAP,                 1) \
    PROFILER_DO(PROFILER_COMPOSITING,                1) \
Definition at line 432 of file vkpt.h.
QGL_INDEX_TYPE
#define QGL_INDEX_TYPE GLuint
Definition at line 711 of file vkpt.h.
SHADER_MODULE_DO
#define SHADER_MODULE_DO (a) a,
Definition at line 134 of file vkpt.h.
SHADER_PATH_TEMPLATE
#define SHADER_PATH_TEMPLATE VKPT_SHADER_DIR "/%s.spv"
Definition at line 114 of file vkpt.h.
SHADER_STAGE
#define SHADER_STAGE (_module, _stage)
Value:
    { \
        .sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO, \
        .stage = _stage, \
        .module = qvk.shader_modules[_module], \
        .pName = "main" \
    }
Definition at line 116 of file vkpt.h.
SHADER_STAGE_SPEC
#define SHADER_STAGE_SPEC (_module, _stage, _spec)
Value:
    { \
        .sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO, \
        .stage = _stage, \
        .module = qvk.shader_modules[_module], \
        .pName = "main", \
        .pSpecializationInfo = _spec, \
    }
Definition at line 124 of file vkpt.h.
TESS_MAX_INDICES
#define TESS_MAX_INDICES (3 * TESS_MAX_VERTICES)
Definition at line 709 of file vkpt.h.
TESS_MAX_VERTICES
#define TESS_MAX_VERTICES 16384
Definition at line 708 of file vkpt.h.
VKPT_SHADER_DIR
#define VKPT_SHADER_DIR "shader_vkpt"
Definition at line 111 of file vkpt.h.
Typedef Documentation
aabb_t
typedef struct aabb_s aabb_t
bsp_mesh_t
typedef struct bsp_mesh_s bsp_mesh_t
bsp_model_t
typedef struct bsp_model_s bsp_model_t
cmd_buf_group_t
typedef struct cmd_buf_group_s cmd_buf_group_t
EntityUploadInfo
typedef struct EntityUploadInfo EntityUploadInfo
light_poly_t
typedef struct light_poly_s light_poly_t
maliasframe_t
typedef struct maliasframe_s maliasframe_t
maliasmesh_t
typedef struct maliasmesh_s maliasmesh_t
QVK_t
typedef struct QVK_s QVK_t
semaphore_group_t
typedef struct semaphore_group_s semaphore_group_t
sun_light_t
typedef struct sun_light_s sun_light_t
vkpt_refdef_t
typedef struct vkpt_refdef_s vkpt_refdef_t
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
NUM_PROFILER_ENTRIES
Definition at line 459 of file vkpt.h.
      {
 #define PROFILER_DO(a, ...) a,
     PROFILER_LIST
 #undef PROFILER_DO
     NUM_PROFILER_ENTRIES,
 };
QVK_SHADER_MODULES
enum QVK_SHADER_MODULES
Enumerator
NUM_QVK_SHADER_MODULES
Definition at line 133 of file vkpt.h.
{
 #define SHADER_MODULE_DO(a) a,
     LIST_SHADER_MODULES
 #undef SHADER_MODULE_DO
     NUM_QVK_SHADER_MODULES
 };
VKPTProfilerAction
enum VKPTProfilerAction
Enumerator
PROFILER_START
PROFILER_STOP
Definition at line 468 of file vkpt.h.
              {
     PROFILER_START,
     PROFILER_STOP,
 } VKPTProfilerAction;
Function Documentation
allocate_gpu_memory()
VkResult allocate_gpu_memory (VkMemoryRequirements mem_req, VkDeviceMemory * pMemory)
Definition at line 402 of file vk_util.c.
 {
     VkMemoryAllocateInfo mem_alloc_info = {
         .sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,
         .allocationSize = mem_req.size,
         .memoryTypeIndex = get_memory_type(mem_req.memoryTypeBits, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT)
     };
 #ifdef VKPT_DEVICE_GROUPS
     VkMemoryAllocateFlagsInfoKHR mem_alloc_flags = {
         .sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_FLAGS_INFO_KHR,
         .flags = VK_MEMORY_ALLOCATE_DEVICE_MASK_BIT_KHR,
         .deviceMask = (1 << qvk.device_count) - 1
     };
     if (qvk.device_count > 1) {
         mem_alloc_info.pNext = &mem_alloc_flags;
     }
 #endif
     return vkAllocateMemory(qvk.device, &mem_alloc_info, NULL, pMemory);
 }
Referenced by allocate_and_bind_memory_to_blas(), initializeEnvTexture(), load_blue_noise(), vkpt_create_images(), vkpt_pt_create_accel_bottom(), vkpt_pt_create_toplevel(), vkpt_shadow_map_initialize(), and vkpt_textures_upload_envmap().
begin_perf_marker()
static void begin_perf_marker (VkCommandBuffer command_buffer, int index, const char * name) inline static
Definition at line 721 of file vkpt.h.
 {
     _VK(vkpt_profiler_query(command_buffer, index, PROFILER_START));
     const VkDebugUtilsLabelEXT label = {
         .sType = VK_STRUCTURE_TYPE_DEBUG_UTILS_LABEL_EXT,
         .pLabelName = name
     };
     if (qvkCmdBeginDebugUtilsLabelEXT != NULL)
         qvkCmdBeginDebugUtilsLabelEXT(command_buffer, &label);
 }
bsp_mesh_create_from_bsp()
void bsp_mesh_create_from_bsp (bsp_mesh_t * wm, bsp_t * bsp, const char * map_name)
Definition at line 1623 of file bsp_mesh.c.
 {
     const char* full_game_map_name = map_name;
     if (strcmp(map_name, "demo1") == 0)
         full_game_map_name = "base1";
     else if (strcmp(map_name, "demo2") == 0)
         full_game_map_name = "base2";
     else if (strcmp(map_name, "demo3") == 0)
         full_game_map_name = "base3";
     load_sky_and_lava_clusters(wm, full_game_map_name);
     load_cameras(wm, full_game_map_name);
     wm->models = Z_Malloc(bsp->nummodels * sizeof(bsp_model_t));
     memset(wm->models, 0, bsp->nummodels * sizeof(bsp_model_t));
     wm->num_models = bsp->nummodels;
     wm->num_clusters = bsp->vis->numclusters;
     if (wm->num_clusters + 1 >= MAX_LIGHT_LISTS)
     {
         Com_Error(ERR_FATAL, "The BSP model has too many clusters (%d)", wm->num_clusters);
     }
     wm->num_vertices = 0;
     wm->num_indices = 0;
     wm->positions = Z_Malloc(MAX_VERT_BSP * 3 * sizeof(*wm->positions));
     wm->tex_coords = Z_Malloc(MAX_VERT_BSP * 2 * sizeof(*wm->tex_coords));
     wm->materials = Z_Malloc(MAX_VERT_BSP / 3 * sizeof(*wm->materials));
     wm->clusters = Z_Malloc(MAX_VERT_BSP / 3 * sizeof(*wm->clusters));
     // clear these here because `bsp_mesh_load_custom_sky` creates lights before `collect_ligth_polys`
     wm->num_light_polys = 0;
     wm->allocated_light_polys = 0;
     wm->light_polys = NULL;
     int idx_ctr = 0;
 #if DUMP_WORLD_MESH_TO_OBJ
     {
         char filename[MAX_QPATH];
         Q_snprintf(filename, sizeof(filename), "C:\\temp\\%s.obj", map_name);
         obj_dump_file = fopen(filename, "w");
         obj_vertex_num = 1;
     }
 #endif
     collect_surfaces(&idx_ctr, wm, bsp, -1, filter_static_opaque);
     wm->world_idx_count = idx_ctr;
     wm->world_transparent_offset = idx_ctr;
     collect_surfaces(&idx_ctr, wm, bsp, -1, filter_static_transparent);
     wm->world_transparent_count = idx_ctr - wm->world_transparent_offset;
     wm->world_sky_offset = idx_ctr;
     collect_surfaces(&idx_ctr, wm, bsp, -1, filter_static_sky);
     wm->world_sky_count = idx_ctr - wm->world_sky_offset;
     wm->world_custom_sky_offset = idx_ctr;
     bsp_mesh_load_custom_sky(&idx_ctr, wm, bsp, full_game_map_name);
     wm->world_custom_sky_count = idx_ctr - wm->world_custom_sky_offset;
     for (int k = 0; k < bsp->nummodels; k++) {
         bsp_model_t* model = wm->models + k;
         model->idx_offset = idx_ctr;
         collect_surfaces(&idx_ctr, wm, bsp, k, filter_all);
         model->idx_count = idx_ctr - model->idx_offset;
     }
 #if DUMP_WORLD_MESH_TO_OBJ
     fclose(obj_dump_file);
     obj_dump_file = NULL;
 #endif
     if (!bsp->pvs_patched)
     {
         build_pvs2(bsp);
         if (!BSP_SavePatchedPVS(bsp))
         {
             Com_EPrintf("Couldn't save patched PVS for %s.\n", bsp->name);
         }
     }
     wm->num_indices = idx_ctr;
     wm->num_vertices = idx_ctr;
     wm->indices = Z_Malloc(idx_ctr * sizeof(int));
     for (int i = 0; i < wm->num_vertices; i++)
         wm->indices[i] = i;
     compute_world_tangents(wm);
     if (wm->num_vertices >= MAX_VERT_BSP) {
         Com_Error(ERR_FATAL, "The BSP model has too many vertices (%d)", wm->num_vertices);
     }
     for(int i = 0; i < wm->num_models; i++)
     {
         bsp_model_t* model = wm->models + i;
         compute_aabb(wm->positions + model->idx_offset * 3, model->idx_count, model->aabb_min, model->aabb_max);
         VectorAdd(model->aabb_min, model->aabb_max, model->center);
         VectorScale(model->center, 0.5f, model->center);
     }
     compute_aabb(wm->positions, wm->world_idx_count, wm->world_aabb.mins, wm->world_aabb.maxs);
     vec3_t margin = { 1.f, 1.f, 1.f };
     VectorSubtract(wm->world_aabb.mins, margin, wm->world_aabb.mins);
     VectorAdd(wm->world_aabb.maxs, margin, wm->world_aabb.maxs);
     compute_cluster_aabbs(wm);
     collect_ligth_polys(wm, bsp, -1, &wm->num_light_polys, &wm->allocated_light_polys, &wm->light_polys);
     collect_sky_and_lava_ligth_polys(wm, bsp);
     for (int k = 0; k < bsp->nummodels; k++)
     {
         bsp_model_t* model = wm->models + k;
         model->num_light_polys = 0;
         model->allocated_light_polys = 0;
         model->light_polys = NULL;
         collect_ligth_polys(wm, bsp, k, &model->num_light_polys, &model->allocated_light_polys, &model->light_polys);
         model->transparent = is_model_transparent(wm, model);
     }
     collect_cluster_lights(wm, bsp);
     compute_sky_visibility(wm, bsp);
 }
Referenced by R_BeginRegistration_RTX().
bsp_mesh_destroy()
void bsp_mesh_destroy (bsp_mesh_t * wm)
Definition at line 1760 of file bsp_mesh.c.
 {
     Z_Free(wm->models);
     Z_Free(wm->positions);
     Z_Free(wm->tex_coords);
     Z_Free(wm->tangents);
     Z_Free(wm->indices);
     Z_Free(wm->clusters);
     Z_Free(wm->materials);
     Z_Free(wm->texel_density);
     Z_Free(wm->light_polys);
     Z_Free(wm->cluster_lights);
     Z_Free(wm->cluster_light_offsets);
     Z_Free(wm->cluster_aabbs);
     memset(wm, 0, sizeof(*wm));
 }
Referenced by R_BeginRegistration_RTX().
bsp_mesh_register_textures()
void bsp_mesh_register_textures (bsp_t * bsp)
Definition at line 1781 of file bsp_mesh.c.
 {
     for (int i = 0; i < bsp->numtexinfo; i++) {
         mtexinfo_t *info = bsp->texinfo + i;
         imageflags_t flags;
         if (info->c.flags & SURF_WARP)
             flags = IF_TURBULENT;
         else
             flags = IF_NONE;
         char buffer[MAX_QPATH];
         Q_concat(buffer, sizeof(buffer), "textures/", info->name, ".wal", NULL);
         FS_NormalizePath(buffer, buffer);
         pbr_material_t * mat = MAT_FindPBRMaterial(buffer);
         if (!mat)
             Com_EPrintf("error finding material '%s'\n", buffer);
         image_t* image_diffuse = IMG_Find(buffer, IT_WALL, flags | IF_SRGB);
         image_t* image_normals = NULL;
         image_t* image_emissive = NULL;
         if (image_diffuse != R_NOTEXTURE)
         {
             // attempt loading the second texture
             Q_concat(buffer, sizeof(buffer), "textures/", info->name, "_n.tga", NULL);
             FS_NormalizePath(buffer, buffer);
             image_normals = IMG_Find(buffer, IT_WALL, flags);
             if (image_normals == R_NOTEXTURE) image_normals = NULL;
             if (image_normals && !image_normals->processing_complete)
             {
                 vkpt_normalize_normal_map(image_normals);
             }
             // attempt loading the emissive texture
             Q_concat(buffer, sizeof(buffer), "textures/", info->name, "_light.tga", NULL);
             FS_NormalizePath(buffer, buffer);
             image_emissive = IMG_Find(buffer, IT_WALL, flags | IF_SRGB);
             if (image_emissive == R_NOTEXTURE) image_emissive = NULL;
             if (image_emissive && !image_emissive->processing_complete && (mat->emissive_scale > 0.f) && ((mat->flags & MATERIAL_FLAG_LIGHT) != 0 || MAT_IsKind(mat->flags, MATERIAL_KIND_LAVA)))
             {
                 vkpt_extract_emissive_texture_info(image_emissive);
             }
         }
         // finish registration
         MAT_RegisterPBRMaterial(mat, image_diffuse, image_normals, image_emissive);
         info->material = mat;
     }
     // link the animation sequences
     for (int i = 0; i < bsp->numtexinfo; i++)
     {
         mtexinfo_t *texinfo = bsp->texinfo + i;
         pbr_material_t* material = texinfo->material;
         if (texinfo->numframes > 1)
         {
             assert(texinfo->next);
             assert(texinfo->next->material);
             material->num_frames = texinfo->numframes;
             material->next_frame = texinfo->next->material->flags & MATERIAL_INDEX_MASK;
         }
     }
 }
Referenced by R_BeginRegistration_RTX().
build_transparency_blas()
void build_transparency_blas (VkCommandBuffer cmd_buf)
Definition at line 217 of file transparency.c.
 {
     update_particle_blas(cmd_buf);
     update_beam_blas(cmd_buf);
     update_sprite_blas(cmd_buf);
     // No barrier here because a single barrier is used later in the pipeline, after building all the BLAS-es
 }
Referenced by R_RenderFrame_RTX().
create_entity_matrix()
void create_entity_matrix (float matrix[16], entity_t * e, qboolean enable_left_hand)
Definition at line 23 of file matrix.c.
 {
     vec3_t axis[3];
     vec3_t origin;
     origin[0] = (1.f-e->backlerp) * e->origin[0] + e->backlerp * e->oldorigin[0];
     origin[1] = (1.f-e->backlerp) * e->origin[1] + e->backlerp * e->oldorigin[1];
     origin[2] = (1.f-e->backlerp) * e->origin[2] + e->backlerp * e->oldorigin[2];
     AnglesToAxis(e->angles, axis);
     float scale = (e->scale > 0.f) ? e->scale : 1.f;
     vec3_t scales = { scale, scale, scale };
     if ((e->flags & RF_LEFTHAND) && enable_left_hand)
     {
         scales[1] *= -1.f;
     }
     matrix[0]  = axis[0][0] * scales[0];
     matrix[4]  = axis[1][0] * scales[1];
     matrix[8]  = axis[2][0] * scales[2];
     matrix[12] = origin[0];
     matrix[1]  = axis[0][1] * scales[0];
     matrix[5]  = axis[1][1] * scales[1];
     matrix[9]  = axis[2][1] * scales[2];
     matrix[13] = origin[1];
     matrix[2]  = axis[0][2] * scales[0];
     matrix[6]  = axis[1][2] * scales[1];
     matrix[10] = axis[2][2] * scales[2];
     matrix[14] = origin[2];
     matrix[3]  = 0.0f;
     matrix[7]  = 0.0f;
     matrix[11] = 0.0f;
     matrix[15] = 1.0f;
 }
Referenced by process_bsp_entity(), and process_regular_entity().
create_orthographic_matrix()
void create_orthographic_matrix (float matrix[16], float xmin, float xmax, float ymin, float ymax, float znear, float zfar)
Definition at line 100 of file matrix.c.
 {
     float width, height, depth;
     width = xmax - xmin;
     height = ymax - ymin;
     depth = zfar - znear;
     matrix[0] = 2 / width;
     matrix[4] = 0;
     matrix[8] = 0;
     matrix[12] = -(xmax + xmin) / width;
     matrix[1] = 0;
     matrix[5] = 2 / height;
     matrix[9] = 0;
     matrix[13] = -(ymax + ymin) / height;
     matrix[2] = 0;
     matrix[6] = 0;
     matrix[10] = 1 / depth;
     matrix[14] = -znear / depth;
     matrix[3] = 0;
     matrix[7] = 0;
     matrix[11] = 0;
     matrix[15] = 1;
 }
Referenced by vkpt_shadow_map_setup().
create_projection_matrix()
void create_projection_matrix (float matrix[16], float znear, float zfar, float fov_x, float fov_y)
Definition at line 63 of file matrix.c.
 {
     float xmin, xmax, ymin, ymax;
     float width, height, depth;
     ymax = znear * tan(fov_y * M_PI / 360.0);
     ymin = -ymax;
     xmax = znear * tan(fov_x * M_PI / 360.0);
     xmin = -xmax;
     width = xmax - xmin;
     height = ymax - ymin;
     depth = zfar - znear;
     matrix[0] = 2 * znear / width;
     matrix[4] = 0;
     matrix[8] = (xmax + xmin) / width;
     matrix[12] = 0;
     matrix[1] = 0;
     matrix[5] = -2 * znear / height;
     matrix[9] = (ymax + ymin) / height;
     matrix[13] = 0;
     matrix[2] = 0;
     matrix[6] = 0;
     matrix[10] = (zfar + znear) / depth;
     matrix[14] = 2 * zfar * znear / depth;
     matrix[3] = 0;
     matrix[7] = 0;
     matrix[11] = 1;
     matrix[15] = 0;
 }
Referenced by prepare_ubo().
create_view_matrix()
void create_view_matrix (float matrix[16], refdef_t * fd)
Definition at line 131 of file matrix.c.
 {
     vec3_t viewaxis[3];
     AnglesToAxis(fd->viewangles, viewaxis);
     matrix[0]  = -viewaxis[1][0];
     matrix[4]  = -viewaxis[1][1];
     matrix[8]  = -viewaxis[1][2];
     matrix[12] = DotProduct(viewaxis[1], fd->vieworg);
     matrix[1]  = viewaxis[2][0];
     matrix[5]  = viewaxis[2][1];
     matrix[9]  = viewaxis[2][2];
     matrix[13] = -DotProduct(viewaxis[2], fd->vieworg);
     matrix[2]  = viewaxis[0][0];
     matrix[6]  = viewaxis[0][1];
     matrix[10] = viewaxis[0][2];
     matrix[14] = -DotProduct(viewaxis[0], fd->vieworg);
     matrix[3]  = 0;
     matrix[7]  = 0;
     matrix[11] = 0;
     matrix[15] = 1;
 }
Referenced by prepare_ubo().
destroy_transparency()
void destroy_transparency ()
Definition at line 151 of file transparency.c.
 {
     vkDestroyBufferView(qvk.device, transparency.particle_color_buffer_view, NULL);
     vkDestroyBufferView(qvk.device, transparency.beam_color_buffer_view, NULL);
     vkDestroyBufferView(qvk.device, transparency.sprite_info_buffer_view, NULL);
     vkDestroyBuffer(qvk.device, transparency.host_buffer, NULL);
     vkDestroyBuffer(qvk.device, transparency.scratch_buffer, NULL);
     vkDestroyBuffer(qvk.device, transparency.vertex_buffer, NULL);
     vkDestroyBuffer(qvk.device, transparency.index_buffer, NULL);
     vkDestroyBuffer(qvk.device, transparency.particle_color_buffer, NULL);
     vkDestroyBuffer(qvk.device, transparency.beam_color_buffer, NULL);
     vkDestroyBuffer(qvk.device, transparency.sprite_info_buffer, NULL);
     qvkDestroyAccelerationStructureNV(qvk.device, transparency.particle_blas, NULL);
     qvkDestroyAccelerationStructureNV(qvk.device, transparency.beam_blas, NULL);
     qvkDestroyAccelerationStructureNV(qvk.device, transparency.sprite_blas, NULL);
     vkFreeMemory(qvk.device, transparency.host_buffer_memory, NULL);
     vkFreeMemory(qvk.device, transparency.device_buffer_memory, NULL);
     vkFreeMemory(qvk.device, transparency.device_blas_memory, NULL);
 }
Referenced by vkpt_destroy_all().
draw_profiler()
void draw_profiler (int enable_asvgf)
Definition at line 134 of file profiler.c.
 {
     int x = 500;
     int y = 100;
     qhandle_t font;
     font = R_RegisterFont("conchars");
     if(!font)
         return;
 #define PROFILER_DO(name, indent) \
     draw_query(x, y, font, #name + 9, name); y += 10;
     PROFILER_DO(PROFILER_FRAME_TIME, 0);
     PROFILER_DO(PROFILER_INSTANCE_GEOMETRY, 1);
     PROFILER_DO(PROFILER_BVH_UPDATE, 1);
     PROFILER_DO(PROFILER_UPDATE_ENVIRONMENT, 1);
     PROFILER_DO(PROFILER_SHADOW_MAP, 1);
     PROFILER_DO(PROFILER_ASVGF_GRADIENT_SAMPLES, 1);
     PROFILER_DO(PROFILER_ASVGF_DO_GRADIENT_SAMPLES, 2);
     PROFILER_DO(PROFILER_PRIMARY_RAYS, 1);
     if (cvar_pt_reflect_refract->integer > 0) { PROFILER_DO(PROFILER_REFLECT_REFRACT_1, 1); }
     if (cvar_pt_reflect_refract->integer > 1) { PROFILER_DO(PROFILER_REFLECT_REFRACT_2, 1); }
     PROFILER_DO(PROFILER_DIRECT_LIGHTING, 1);
     PROFILER_DO(PROFILER_INDIRECT_LIGHTING, 1);
     PROFILER_DO(PROFILER_GOD_RAYS, 1);
     PROFILER_DO(PROFILER_GOD_RAYS_REFLECT_REFRACT, 1);
     PROFILER_DO(PROFILER_GOD_RAYS_FILTER, 1);
     if (enable_asvgf)
     {
         PROFILER_DO(PROFILER_ASVGF_FULL, 1);
         PROFILER_DO(PROFILER_ASVGF_RECONSTRUCT_GRADIENT, 2);
         PROFILER_DO(PROFILER_ASVGF_TEMPORAL, 2);
         PROFILER_DO(PROFILER_ASVGF_ATROUS, 2);
         PROFILER_DO(PROFILER_ASVGF_TAA, 2);
     }
     else
     {
         PROFILER_DO(PROFILER_COMPOSITING, 1);
     }
     if (qvk.device_count > 1) {
         PROFILER_DO(PROFILER_MGPU_TRANSFERS, 1);
     }
     PROFILER_DO(PROFILER_INTERLEAVE, 1);
     PROFILER_DO(PROFILER_BLOOM, 1);
     PROFILER_DO(PROFILER_TONE_MAPPING, 2);
 #undef PROFILER_DO
 }
Referenced by R_EndFrame_RTX().
end_perf_marker()
static void end_perf_marker (VkCommandBuffer command_buffer, int index) inline static
Definition at line 734 of file vkpt.h.
 {
     if (qvkCmdEndDebugUtilsLabelEXT != NULL)
         qvkCmdEndDebugUtilsLabelEXT(command_buffer);
     _VK(vkpt_profiler_query(command_buffer, index, PROFILER_STOP));
 }
get_transparency_beam_blas()
VkAccelerationStructureNV get_transparency_beam_blas ()
Definition at line 231 of file transparency.c.
 {
     return transparency.beam_blas;
 }
Referenced by vkpt_pt_create_toplevel().
get_transparency_beam_color_buffer_view()
VkBufferView get_transparency_beam_color_buffer_view ()
Definition at line 246 of file transparency.c.
 {
     return transparency.beam_color_buffer_view;
 }
Referenced by vkpt_pt_update_descripter_set_bindings().
get_transparency_counts()
void get_transparency_counts (int * particle_num, int * beam_num, int * sprite_num)
Definition at line 256 of file transparency.c.
 {
     *particle_num = transparency.particle_num;
     *beam_num = transparency.beam_num;
     *sprite_num = transparency.sprite_num;
 }
Referenced by vkpt_pt_create_toplevel().
get_transparency_particle_blas()
VkAccelerationStructureNV get_transparency_particle_blas ()
Definition at line 226 of file transparency.c.
 {
     return transparency.particle_blas;
 }
Referenced by vkpt_pt_create_toplevel().
get_transparency_particle_color_buffer_view()
VkBufferView get_transparency_particle_color_buffer_view ()
Definition at line 241 of file transparency.c.
 {
     return transparency.particle_color_buffer_view;
 }
Referenced by vkpt_pt_update_descripter_set_bindings().
get_transparency_sprite_blas()
VkAccelerationStructureNV get_transparency_sprite_blas ()
Definition at line 236 of file transparency.c.
 {
     return transparency.sprite_blas;
 }
Referenced by vkpt_pt_create_toplevel().
get_transparency_sprite_info_buffer_view()
VkBufferView get_transparency_sprite_info_buffer_view ()
Definition at line 251 of file transparency.c.
 {
     return transparency.sprite_info_buffer_view;
 }
Referenced by vkpt_pt_update_descripter_set_bindings().
get_triangle_off_center()
qboolean get_triangle_off_center (const float * positions, float * center, float * anti_center)
Definition at line 282 of file bsp_mesh.c.
 {
     const float* v0 = positions + 0;
     const float* v1 = positions + 3;
     const float* v2 = positions + 6;
     // Compute the triangle center
     VectorCopy(v0, center);
     VectorAdd(center, v1, center);
     VectorAdd(center, v2, center);
     VectorScale(center, 1.f / 3.f, center);
     // Compute the normal
     vec3_t e1, e2, normal;
     VectorSubtract(v1, v0, e1);
     VectorSubtract(v2, v0, e2);
     CrossProduct(e1, e2, normal);
     float length = VectorNormalize(normal);
     // Offset the center by one normal to make sure that the point is
     // inside a BSP leaf and not on a boundary plane.
     VectorAdd(center, normal, center);
     if (anti_center)
     {
         VectorMA(center, -2.f, normal, anti_center);
     }
     return (length > 0.f);
 }
Referenced by bsp_mesh_load_custom_sky(), collect_ligth_polys(), collect_sky_and_lava_ligth_polys(), collect_surfaces(), and vkpt_build_cylinder_light().
IMG_Load_RTX()
void IMG_Load_RTX (image_t * image, byte * pic)
Definition at line 632 of file textures.c.
 {
     image->pix_data = pic;
     image_loading_dirty_flag = 1;
 }
Referenced by R_RegisterFunctionsRTX().
IMG_ReadPixels_RTX()
byte* IMG_ReadPixels_RTX (int * width, int * height, int * rowbytes)
Definition at line 3028 of file main.c.
 {
     if (qvk.surf_format.format != VK_FORMAT_B8G8R8A8_SRGB &&
         qvk.surf_format.format != VK_FORMAT_R8G8B8A8_SRGB)
     {
         Com_EPrintf("IMG_ReadPixels: unsupported swap chain format (%d)!\n", qvk.surf_format.format);
         return NULL;
     }
     VkCommandBuffer cmd_buf = vkpt_begin_command_buffer(&qvk.cmd_buffers_graphics);
     VkImage swap_chain_image = qvk.swap_chain_images[qvk.current_swap_chain_image_index];
     VkImageSubresourceRange subresource_range = {
         .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
         .baseMipLevel = 0,
         .levelCount = 1,
         .baseArrayLayer = 0,
         .layerCount = 1
     };
     IMAGE_BARRIER(cmd_buf,
         .image = swap_chain_image,
         .subresourceRange = subresource_range,
         .srcAccessMask = 0,
         .dstAccessMask = VK_ACCESS_TRANSFER_READ_BIT,
         .oldLayout = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR,
         .newLayout = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL
     );
     IMAGE_BARRIER(cmd_buf,
         .image = qvk.screenshot_image,
         .subresourceRange = subresource_range,
         .srcAccessMask = VK_ACCESS_HOST_READ_BIT,
         .dstAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT,
         .oldLayout = VK_IMAGE_LAYOUT_GENERAL,
         .newLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL
     );
     VkImageCopy img_copy_region = {
         .srcSubresource = { VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1 },
         .dstSubresource = { VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1 },
         .extent = { qvk.extent_unscaled.width, qvk.extent_unscaled.height, 1 }
     };
     vkCmdCopyImage(cmd_buf,
         swap_chain_image, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
         qvk.screenshot_image, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
         1, &img_copy_region);
     IMAGE_BARRIER(cmd_buf,
         .image = swap_chain_image,
         .subresourceRange = subresource_range,
         .srcAccessMask = VK_ACCESS_TRANSFER_READ_BIT,
         .dstAccessMask = 0,
         .oldLayout = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
         .newLayout = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR
     );
     IMAGE_BARRIER(cmd_buf,
         .image = qvk.screenshot_image,
         .subresourceRange = subresource_range,
         .srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT,
         .dstAccessMask = VK_ACCESS_HOST_READ_BIT,
         .oldLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
         .newLayout = VK_IMAGE_LAYOUT_GENERAL
     );
     vkpt_submit_command_buffer_simple(cmd_buf, qvk.queue_graphics, qfalse);
     vkpt_wait_idle(qvk.queue_graphics, &qvk.cmd_buffers_graphics);
     VkImageSubresource subresource = {
         .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
         .arrayLayer = 0,
         .mipLevel = 0
     };
     VkSubresourceLayout subresource_layout;
     vkGetImageSubresourceLayout(qvk.device, qvk.screenshot_image, &subresource, &subresource_layout);
     void *device_data;
     _VK(vkMapMemory(qvk.device, qvk.screenshot_image_memory, 0, qvk.screenshot_image_memory_size, 0, &device_data));
     int pitch = qvk.extent_unscaled.width * 3;
     byte *pixels = FS_AllocTempMem(pitch * qvk.extent_unscaled.height);
     for (int row = 0; row < qvk.extent_unscaled.height; row++)
     {
         byte* src_row = (byte*)device_data + subresource_layout.rowPitch * row;
         byte* dst_row = pixels + pitch * (qvk.extent_unscaled.height - row - 1);
         if (qvk.surf_format.format == VK_FORMAT_B8G8R8A8_SRGB)
         {
             for (int col = 0; col < qvk.extent_unscaled.width; col++)
             {
                 dst_row[0] = src_row[2];
                 dst_row[1] = src_row[1];
                 dst_row[2] = src_row[0];
                 src_row += 4;
                 dst_row += 3;
             }
         }
         else // must be VK_FORMAT_R8G8B8A8_SRGB then
         {
             for (int col = 0; col < qvk.extent_unscaled.width; col++)
             {
                 dst_row[0] = src_row[0];
                 dst_row[1] = src_row[1];
                 dst_row[2] = src_row[2];
                 src_row += 4;
                 dst_row += 3;
             }
         }
     }
     vkUnmapMemory(qvk.device, qvk.screenshot_image_memory);
     *width = qvk.extent_unscaled.width;
     *height = qvk.extent_unscaled.height;
     *rowbytes = pitch;
     return pixels;
 }
Referenced by R_RegisterFunctionsRTX().
IMG_Unload_RTX()
void IMG_Unload_RTX (image_t * image)
Definition at line 639 of file textures.c.
 {
     if(image->pix_data)
         Z_Free(image->pix_data);
     image->pix_data = NULL;
     const uint32_t index = image - r_images;
     if (tex_images[index])
     {
     const uint32_t frame_index = (qvk.frame_counter + MAX_FRAMES_IN_FLIGHT) % DESTROY_LATENCY;
     UnusedResources* unused_resources = texture_system.unused_resources + frame_index;
     const uint32_t unused_index = unused_resources->image_num++;
     unused_resources->images[unused_index] = tex_images[index];
     unused_resources->image_memory[unused_index] = tex_image_memory[index];
     unused_resources->image_views[unused_index] = tex_image_views[index];
     tex_images[index] = VK_NULL_HANDLE;
     tex_image_views[index] = VK_NULL_HANDLE;
     memset(descriptor_set_dirty_flags, 0xff, sizeof(descriptor_set_dirty_flags));
     }
 }
Referenced by R_RegisterFunctionsRTX().
initialize_transparency()
qboolean initialize_transparency ()
Definition at line 114 of file transparency.c.
 {
     cvar_pt_particle_size = Cvar_Get("pt_particle_size", "0.35", 0);
     cvar_pt_beam_width = Cvar_Get("pt_beam_width", "1.0", 0);
     cvar_pt_beam_lights = Cvar_Get("pt_beam_lights", "1.0", 0);
     memset(&transparency, 0, sizeof(transparency));
     const size_t particle_vertex_position_max_size = TR_VERTEX_MAX_NUM * TR_POSITION_SIZE;
     const size_t particle_color_size = TR_PARTICLE_MAX_NUM * TR_COLOR_SIZE;
     const size_t particle_data_size = particle_vertex_position_max_size + particle_color_size;
     const size_t beam_vertex_position_max_size = TR_BEAM_MAX_NUM * TR_POSITION_SIZE;
     const size_t beam_color_size = TR_BEAM_MAX_NUM * TR_COLOR_SIZE;
     const size_t beam_data_size = beam_vertex_position_max_size + beam_color_size;
     const size_t sprite_vertex_position_max_size = TR_SPRITE_MAX_NUM * TR_POSITION_SIZE;
     const size_t sprite_info_size = TR_SPRITE_MAX_NUM * TR_SPRITE_INFO_SIZE;
     const size_t sprite_data_size = sprite_vertex_position_max_size + sprite_info_size;
     transparency.host_buffered_frame_num = MAX_FRAMES_IN_FLIGHT;
     transparency.host_frame_size = particle_data_size + beam_data_size + sprite_data_size;
     transparency.host_buffer_size = transparency.host_buffered_frame_num * transparency.host_frame_size;
     create_blas(transparency);
     create_buffers(transparency);
     if (allocate_and_bind_memory_to_buffers(transparency) != VK_TRUE)
         return qfalse;
     create_buffer_views(transparency);
     allocate_and_bind_memory_to_blas(transparency);
     fill_index_buffer(transparency);
     return qtrue;
 }
Referenced by vkpt_initialize_all().
inverse()
void inverse (const float * m, float * inv)
Definition at line 158 of file matrix.c.
 {
     inv[0] = m[5]  * m[10] * m[15] -
              m[5]  * m[11] * m[14] -
              m[9]  * m[6]  * m[15] +
              m[9]  * m[7]  * m[14] +
              m[13] * m[6]  * m[11] -
              m[13] * m[7]  * m[10];
     inv[1] = -m[1]  * m[10] * m[15] +
               m[1]  * m[11] * m[14] +
               m[9]  * m[2] * m[15] -
               m[9]  * m[3] * m[14] -
               m[13] * m[2] * m[11] +
               m[13] * m[3] * m[10];
     inv[2] = m[1]  * m[6] * m[15] -
              m[1]  * m[7] * m[14] -
              m[5]  * m[2] * m[15] +
              m[5]  * m[3] * m[14] +
              m[13] * m[2] * m[7] -
              m[13] * m[3] * m[6];
     inv[3] = -m[1] * m[6] * m[11] +
               m[1] * m[7] * m[10] +
               m[5] * m[2] * m[11] -
               m[5] * m[3] * m[10] -
               m[9] * m[2] * m[7] +
               m[9] * m[3] * m[6];
     inv[4] = -m[4]  * m[10] * m[15] +
               m[4]  * m[11] * m[14] +
               m[8]  * m[6]  * m[15] -
               m[8]  * m[7]  * m[14] -
               m[12] * m[6]  * m[11] +
               m[12] * m[7]  * m[10];
     inv[5] = m[0]  * m[10] * m[15] -
              m[0]  * m[11] * m[14] -
              m[8]  * m[2] * m[15] +
              m[8]  * m[3] * m[14] +
              m[12] * m[2] * m[11] -
              m[12] * m[3] * m[10];
     inv[6] = -m[0]  * m[6] * m[15] +
               m[0]  * m[7] * m[14] +
               m[4]  * m[2] * m[15] -
               m[4]  * m[3] * m[14] -
               m[12] * m[2] * m[7] +
               m[12] * m[3] * m[6];
     inv[7] = m[0] * m[6] * m[11] -
              m[0] * m[7] * m[10] -
              m[4] * m[2] * m[11] +
              m[4] * m[3] * m[10] +
              m[8] * m[2] * m[7] -
              m[8] * m[3] * m[6];
     inv[8] = m[4]  * m[9] * m[15] -
              m[4]  * m[11] * m[13] -
              m[8]  * m[5] * m[15] +
              m[8]  * m[7] * m[13] +
              m[12] * m[5] * m[11] -
              m[12] * m[7] * m[9];
     inv[9] = -m[0]  * m[9] * m[15] +
               m[0]  * m[11] * m[13] +
               m[8]  * m[1] * m[15] -
               m[8]  * m[3] * m[13] -
               m[12] * m[1] * m[11] +
               m[12] * m[3] * m[9];
     inv[10] = m[0]  * m[5] * m[15] -
               m[0]  * m[7] * m[13] -
               m[4]  * m[1] * m[15] +
               m[4]  * m[3] * m[13] +
               m[12] * m[1] * m[7] -
               m[12] * m[3] * m[5];
     inv[11] = -m[0] * m[5] * m[11] +
                m[0] * m[7] * m[9] +
                m[4] * m[1] * m[11] -
                m[4] * m[3] * m[9] -
                m[8] * m[1] * m[7] +
                m[8] * m[3] * m[5];
     inv[12] = -m[4]  * m[9] * m[14] +
                m[4]  * m[10] * m[13] +
                m[8]  * m[5] * m[14] -
                m[8]  * m[6] * m[13] -
                m[12] * m[5] * m[10] +
                m[12] * m[6] * m[9];
     inv[13] = m[0]  * m[9] * m[14] -
               m[0]  * m[10] * m[13] -
               m[8]  * m[1] * m[14] +
               m[8]  * m[2] * m[13] +
               m[12] * m[1] * m[10] -
               m[12] * m[2] * m[9];
     inv[14] = -m[0]  * m[5] * m[14] +
                m[0]  * m[6] * m[13] +
                m[4]  * m[1] * m[14] -
                m[4]  * m[2] * m[13] -
                m[12] * m[1] * m[6] +
                m[12] * m[2] * m[5];
     inv[15] = m[0] * m[5] * m[10] -
               m[0] * m[6] * m[9] -
               m[4] * m[1] * m[10] +
               m[4] * m[2] * m[9] +
               m[8] * m[1] * m[6] -
               m[8] * m[2] * m[5];
     float det = m[0] * inv[0] + m[1] * inv[4] + m[2] * inv[8] + m[3] * inv[12];
     det = 1.0f / det;
     for(int i = 0; i < 16; i++)
         inv[i] = inv[i] * det;
 }
Referenced by prepare_ubo().
load_img()
qerror_t load_img (const char * name, image_t * image)
Definition at line 927 of file images.c.
 {
     byte            *pic;
     imageformat_t   fmt;
     qerror_t        ret;
     size_t len = strlen(name);
     // must have an extension and at least 1 char of base name
     if (len <= 4) {
         return Q_ERR_NAMETOOSHORT;
     }
     if (name[len - 4] != '.') {
         return Q_ERR_INVALID_PATH;
     }
     memcpy(image->name, name, len + 1);
     image->baselen = len - 4;
     image->type = 0;
     image->flags = 0;
     image->registration_sequence = 1;
     // find out original extension
     for (fmt = 0; fmt < IM_MAX; fmt++) {
         if (!Q_stricmp(image->name + image->baselen + 1, img_loaders[fmt].ext)) {
             break;
         }
     }
     // load the pic from disk
     pic = NULL;
     // first try with original extension
     ret = _try_image_format(fmt, image, &pic);
     if (ret == Q_ERR_NOENT) {
         // retry with remaining extensions
         ret = try_other_formats(fmt, image, &pic);
     }
     // if we are replacing 8-bit texture with a higher resolution 32-bit
     // texture, we need to recover original image dimensions
     if (fmt <= IM_WAL && ret > IM_WAL) {
         get_image_dimensions(fmt, image);
     }
     // if we are replacing 8-bit texture with a higher resolution 32-bit
     // texture, we need to recover original image dimensions
     if (fmt <= IM_WAL && ret > IM_WAL) {
         get_image_dimensions(fmt, image);
     }
     if (ret < 0) {
         memset(image, 0, sizeof(*image));
         return ret;
     }
 #if USE_REF == REF_VKPT
     image->pix_data = pic;
 #endif
     return Q_ERR_SUCCESS;
 }
Referenced by IMG_ReloadAll().
MOD_LoadMD2_RTX()
qerror_t MOD_LoadMD2_RTX (model_t * model, const void * rawdata, size_t length)
Definition at line 186 of file models.c.
 {
     dmd2header_t    header;
     dmd2frame_t     *src_frame;
     dmd2trivertx_t  *src_vert;
     dmd2triangle_t  *src_tri;
     dmd2stvert_t    *src_tc;
     char            *src_skin;
     maliasframe_t   *dst_frame;
     maliasmesh_t    *dst_mesh;
     int             val;
     uint16_t        remap[TESS_MAX_INDICES];
     uint16_t        vertIndices[TESS_MAX_INDICES];
     uint16_t        tcIndices[TESS_MAX_INDICES];
     uint16_t        finalIndices[TESS_MAX_INDICES];
     int             numverts, numindices;
     char            skinname[MAX_QPATH];
     vec_t           scale_s, scale_t;
     vec3_t          mins, maxs;
     qerror_t        ret;
     if (length < sizeof(header)) {
         return Q_ERR_FILE_TOO_SMALL;
     }
     // byte swap the header
     header = *(dmd2header_t *)rawdata;
     for (int i = 0; i < sizeof(header) / 4; i++) {
         ((uint32_t *)&header)[i] = LittleLong(((uint32_t *)&header)[i]);
     }
     // validate the header
     ret = MOD_ValidateMD2(&header, length);
     if (ret) {
         if (ret == Q_ERR_TOO_FEW) {
             // empty models draw nothing
             model->type = MOD_EMPTY;
             return Q_ERR_SUCCESS;
         }
         return ret;
     }
     // load all triangle indices
     numindices = 0;
     src_tri = (dmd2triangle_t *)((byte *)rawdata + header.ofs_tris);
     for (int i = 0; i < header.num_tris; i++) {
         int good = 1;
         for (int j = 0; j < 3; j++) {
             uint16_t idx_xyz = LittleShort(src_tri->index_xyz[j]);
             uint16_t idx_st = LittleShort(src_tri->index_st[j]);
             // some broken models have 0xFFFF indices
             if (idx_xyz >= header.num_xyz || idx_st >= header.num_st) {
                 good = 0;
                 break;
             }
             vertIndices[numindices + j] = idx_xyz;
             tcIndices[numindices + j] = idx_st;
         }
         if (good) {
             // only count good triangles
             numindices += 3;
         }
         src_tri++;
     }
     if (numindices < 3) {
         return Q_ERR_TOO_FEW;
     }
     qboolean all_normals_same = qtrue;
     int same_normal = -1;
     src_frame = (dmd2frame_t *)((byte *)rawdata + header.ofs_frames);
     for (int i = 0; i < numindices; i++)
     {
         int v = vertIndices[i];
         int normal = src_frame->verts[v].lightnormalindex;
         // detect if the model has broken normals - they are all the same in that case
         // it happens with players/w_<weapon>.md2 models for example
         if (same_normal < 0)
             same_normal = normal;
         else if (normal != same_normal)
             all_normals_same = qfalse;
     }
     for (int i = 0; i < numindices; i++) {
         remap[i] = 0xFFFF;
     }
     // remap all triangle indices
     numverts = 0;
     src_tc = (dmd2stvert_t *)((byte *)rawdata + header.ofs_st);
     for (int i = 0; i < numindices; i++) {
         if (remap[i] != 0xFFFF) {
             continue; // already remapped
         }
         // only dedup vertices if we're not regenerating normals
         if (!all_normals_same)
         {
             for (int j = i + 1; j < numindices; j++) {
                 if (vertIndices[i] == vertIndices[j] &&
                     (src_tc[tcIndices[i]].s == src_tc[tcIndices[j]].s &&
                         src_tc[tcIndices[i]].t == src_tc[tcIndices[j]].t)) {
                     // duplicate vertex
                     remap[j] = i;
                     finalIndices[j] = numverts;
                 }
             }
         }
         // new vertex
         remap[i] = i;
         finalIndices[i] = numverts++;
     }
     Hunk_Begin(&model->hunk, 50u<<20);
     model->type = MOD_ALIAS;
     model->nummeshes = 1;
     model->numframes = header.num_frames;
     model->meshes = MOD_Malloc(sizeof(maliasmesh_t));
     model->frames = MOD_Malloc(header.num_frames * sizeof(maliasframe_t));
     dst_mesh = model->meshes;
     dst_mesh->numtris    = numindices / 3;
     dst_mesh->numindices = numindices;
     dst_mesh->numverts   = numverts;
     dst_mesh->numskins   = header.num_skins;
     dst_mesh->positions  = MOD_Malloc(numverts   * header.num_frames * sizeof(vec3_t));
     dst_mesh->normals    = MOD_Malloc(numverts   * header.num_frames * sizeof(vec3_t));
     dst_mesh->tex_coords = MOD_Malloc(numverts   * header.num_frames * sizeof(vec2_t));
     dst_mesh->tangents   = MOD_Malloc(numverts   * header.num_frames * sizeof(vec4_t));
     dst_mesh->indices    = MOD_Malloc(numindices * sizeof(int));
     if (dst_mesh->numtris != header.num_tris) {
         Com_DPrintf("%s has %d bad triangles\n", model->name, header.num_tris - dst_mesh->numtris);
     }
     // store final triangle indices
     for (int i = 0; i < numindices; i++) {
         dst_mesh->indices[i] = finalIndices[i];
     }
     // load all skins
     src_skin = (char *)rawdata + header.ofs_skins;
     for (int i = 0; i < header.num_skins; i++) {
         if (!Q_memccpy(skinname, src_skin, 0, sizeof(skinname))) {
             ret = Q_ERR_STRING_TRUNCATED;
             goto fail;
         }
         FS_NormalizePath(skinname, skinname);
         pbr_material_t * mat = MAT_FindPBRMaterial(skinname);
         if (!mat)
             Com_EPrintf("error finding material '%s'\n", skinname);
         image_t* image_diffuse = IMG_Find(skinname, IT_SKIN, IF_SRGB);
         image_t* image_normals = NULL;
         image_t* image_emissive = NULL;
         if (image_diffuse != R_NOTEXTURE)
         {
             // attempt loading the normals texture
             if (!Q_strlcpy(skinname, src_skin, strlen(src_skin) - 3))
                 return Q_ERR_STRING_TRUNCATED;
             Q_concat(skinname, sizeof(skinname), skinname, "_n.tga", NULL);
             FS_NormalizePath(skinname, skinname);
             image_normals = IMG_Find(skinname, IT_SKIN, IF_NONE);
             if (image_normals == R_NOTEXTURE) image_normals = NULL;
             // attempt loading the emissive texture
             if (!Q_strlcpy(skinname, src_skin, strlen(src_skin) - 3))
                 return Q_ERR_STRING_TRUNCATED;
             Q_concat(skinname, sizeof(skinname), skinname, "_light.tga", NULL);
             FS_NormalizePath(skinname, skinname);
             image_emissive = IMG_Find(skinname, IT_SKIN, IF_SRGB);
             if (image_emissive == R_NOTEXTURE) image_emissive = NULL;
         }
         MAT_RegisterPBRMaterial(mat, image_diffuse, image_normals, image_emissive);
         dst_mesh->materials[i] = mat;
         src_skin += MD2_MAX_SKINNAME;
     }
     // load all tcoords
     src_tc = (dmd2stvert_t *)((byte *)rawdata + header.ofs_st);
     scale_s = 1.0f / header.skinwidth;
     scale_t = 1.0f / header.skinheight;
     // load all frames
     src_frame = (dmd2frame_t *)((byte *)rawdata + header.ofs_frames);
     dst_frame = model->frames;
     for (int j = 0; j < header.num_frames; j++) {
         LittleVector(src_frame->scale, dst_frame->scale);
         LittleVector(src_frame->translate, dst_frame->translate);
         // load frame vertices
         ClearBounds(mins, maxs);
         for (int i = 0; i < numindices; i++) {
             if (remap[i] != i) {
                 continue;
             }
             src_vert = &src_frame->verts[vertIndices[i]];
             vec3_t *dst_pos = &dst_mesh->positions [j * numverts + finalIndices[i]];
             vec3_t *dst_nrm = &dst_mesh->normals   [j * numverts + finalIndices[i]];
             vec2_t *dst_tc  = &dst_mesh->tex_coords[j * numverts + finalIndices[i]];
             (*dst_tc)[0] = scale_s * src_tc[tcIndices[i]].s;
             (*dst_tc)[1] = scale_t * src_tc[tcIndices[i]].t;
             (*dst_pos)[0] = src_vert->v[0] * dst_frame->scale[0] + dst_frame->translate[0];
             (*dst_pos)[1] = src_vert->v[1] * dst_frame->scale[1] + dst_frame->translate[1];
             (*dst_pos)[2] = src_vert->v[2] * dst_frame->scale[2] + dst_frame->translate[2];
             (*dst_nrm)[0] = 0.0f;
             (*dst_nrm)[1] = 0.0f;
             (*dst_nrm)[2] = 0.0f;
             val = src_vert->lightnormalindex;
             if (val < NUMVERTEXNORMALS) {
                 (*dst_nrm)[0] = bytedirs[val][0];
                 (*dst_nrm)[1] = bytedirs[val][1];
                 (*dst_nrm)[2] = bytedirs[val][2];
             }
             for (int k = 0; k < 3; k++) {
                 val = (*dst_pos)[k];
                 if (val < mins[k])
                     mins[k] = val;
                 if (val > maxs[k])
                     maxs[k] = val;
             }
         }
         // if all normals are the same, rebuild them as flat triangle normals
         if (all_normals_same)
         {
             for (int tri = 0; tri < numindices / 3; tri++)
             {
                 int i0 = j * numverts + finalIndices[tri * 3 + 0];
                 int i1 = j * numverts + finalIndices[tri * 3 + 1];
                 int i2 = j * numverts + finalIndices[tri * 3 + 2];
                 vec3_t *p0 = &dst_mesh->positions[i0];
                 vec3_t *p1 = &dst_mesh->positions[i1];
                 vec3_t *p2 = &dst_mesh->positions[i2];
                 vec3_t e1, e2, n;
                 VectorSubtract(*p1, *p0, e1);
                 VectorSubtract(*p2, *p0, e2);
                 CrossProduct(e2, e1, n);
                 VectorNormalize(n);
                 VectorCopy(n, dst_mesh->normals[i0]);
                 VectorCopy(n, dst_mesh->normals[i1]);
                 VectorCopy(n, dst_mesh->normals[i2]);
             }
         }
         VectorVectorScale(mins, dst_frame->scale, mins);
         VectorVectorScale(maxs, dst_frame->scale, maxs);
         dst_frame->radius = RadiusFromBounds(mins, maxs);
         VectorAdd(mins, dst_frame->translate, dst_frame->bounds[0]);
         VectorAdd(maxs, dst_frame->translate, dst_frame->bounds[1]);
         src_frame = (dmd2frame_t *)((byte *)src_frame + header.framesize);
         dst_frame++;
     }
     // fix winding order
     for (int i = 0; i < dst_mesh->numindices; i += 3) {
         int tmp = dst_mesh->indices[i + 1];
         dst_mesh->indices[i + 1] = dst_mesh->indices[i + 2];
         dst_mesh->indices[i + 2] = tmp;
     }
     computeTangents(model);
     Hunk_End(&model->hunk);
     return Q_ERR_SUCCESS;
 fail:
     Hunk_Free(&model->hunk);
     return ret;
 }
Referenced by R_RegisterFunctionsRTX().
MOD_LoadMD3_RTX()
qerror_t MOD_LoadMD3_RTX (model_t * model, const void * rawdata, size_t length)
Referenced by R_RegisterFunctionsRTX().
MOD_Reference_RTX()
void MOD_Reference_RTX (model_t * model)
Definition at line 731 of file models.c.
 {
     int mesh_idx, skin_idx, frame_idx;
     // register any images used by the models
     switch (model->type) {
     case MOD_ALIAS:
         for (mesh_idx = 0; mesh_idx < model->nummeshes; mesh_idx++) {
             maliasmesh_t *mesh = &model->meshes[mesh_idx];
             for (skin_idx = 0; skin_idx < mesh->numskins; skin_idx++) {
                 MAT_UpdateRegistration(mesh->materials[skin_idx]);
             }
         }
         break;
     case MOD_SPRITE:
         for (frame_idx = 0; frame_idx < model->numframes; frame_idx++) {
             model->spriteframes[frame_idx].image->registration_sequence = registration_sequence;
         }
         break;
     case MOD_EMPTY:
         break;
     default:
         Com_Error(ERR_FATAL, "%s: bad model type", __func__);
     }
     model->registration_sequence = registration_sequence;
 }
Referenced by R_RegisterFunctionsRTX().
mult_matrix_matrix()
void mult_matrix_matrix (float * p, const float * a, const float * b)
Definition at line 281 of file matrix.c.
 {
     for(int i = 0; i < 4; i++) {
         for(int j = 0; j < 4; j++) {
             p[i * 4 + j] =
                 a[0 * 4 + j] * b[i * 4 + 0] +
                 a[1 * 4 + j] * b[i * 4 + 1] +
                 a[2 * 4 + j] * b[i * 4 + 2] +
                 a[3 * 4 + j] * b[i * 4 + 3];
         }
     }
 }
Referenced by prepare_ubo(), UpdateTerrainShadowMapView(), and vkpt_shadow_map_setup().
mult_matrix_vector()
void mult_matrix_vector (float * p, const float * a, const float * b)
Definition at line 295 of file matrix.c.
 {
     int j;
     for (j = 0; j < 4; j++) {
         p[j] =
             a[0 * 4 + j] * b[0] +
             a[1 * 4 + j] * b[1] +
             a[2 * 4 + j] * b[2] +
             a[3 * 4 + j] * b[3];
     }
 }
Referenced by process_regular_entity(), transform_point(), and vkpt_shadow_map_setup().
qvk_get_current_desc_set_textures()
VkDescriptorSet qvk_get_current_desc_set_textures ()
Definition at line 1847 of file main.c.
 {
     return (qvk.frame_counter & 1) ? qvk.desc_set_textures_odd : qvk.desc_set_textures_even;
 }
Referenced by setup_rt_pipeline(), vkpt_asvgf_create_gradient_samples(), vkpt_asvgf_filter(), vkpt_bloom_record_cmd_buffer(), vkpt_compositing(), vkpt_draw_submit_stretch_pics(), vkpt_final_blit_filtered(), vkpt_interleave(), vkpt_physical_sky_record_cmd_buffer(), vkpt_record_god_rays_filter_command_buffer(), vkpt_record_god_rays_trace_command_buffer(), vkpt_taa(), vkpt_textures_update_descriptor_set(), and vkpt_tone_mapping_record_cmd_buffer().
R_ClearColor_RTX()
void R_ClearColor_RTX (void)
Definition at line 643 of file draw.c.
 {
     draw.colors[0].u32 = U32_WHITE;
     draw.colors[1].u32 = U32_WHITE;
 }
Referenced by R_RegisterFunctionsRTX().
R_DrawChar_RTX()
void R_DrawChar_RTX (int x, int y, int flags, int c, qhandle_t font)
Definition at line 750 of file draw.c.
 {
     draw_char(x, y, flags, c & 255, font);
 }
Referenced by R_RegisterFunctionsRTX().
R_DrawFill32_RTX()
void R_DrawFill32_RTX (int x, int y, int w, int h, uint32_t color)
Definition at line 717 of file draw.c.
 {
     if(!w || !h)
         return;
     enqueue_stretch_pic(x, y, w, h, 0.0f, 0.0f, 1.0f, 1.0f,
         color, TEXNUM_WHITE);
 }
Referenced by R_RegisterFunctionsRTX().
R_DrawFill8_RTX()
void R_DrawFill8_RTX (int x, int y, int w, int h, int c)
Definition at line 708 of file draw.c.
 {
     if(!w || !h)
         return;
     enqueue_stretch_pic(x, y, w, h, 0.0f, 0.0f, 1.0f, 1.0f,
         d_8to24table[c & 0xff], TEXNUM_WHITE);
 }
Referenced by R_RegisterFunctionsRTX().
R_DrawPic_RTX()
void R_DrawPic_RTX (int x, int y, qhandle_t pic)
Definition at line 691 of file draw.c.
 {
     image_t *image = IMG_ForHandle(pic);
     R_DrawStretchPic(x, y, image->width, image->height, pic);
 }
Referenced by R_RegisterFunctionsRTX().
R_DrawStretchPic_RTX()
void R_DrawStretchPic_RTX (int x, int y, int w, int h, qhandle_t pic)
Definition at line 682 of file draw.c.
 {
     enqueue_stretch_pic(
         x,    y,    w,    h,
         0.0f, 0.0f, 1.0f, 1.0f,
         draw.colors[0].u32, pic);
 }
Referenced by R_RegisterFunctionsRTX().
R_DrawString_RTX()
int R_DrawString_RTX (int x, int y, int flags, size_t maxlen, const char * s, qhandle_t font)
Definition at line 756 of file draw.c.
 {
     while(maxlen-- && *s) {
         byte c = *s++;
         draw_char(x, y, flags, c, font);
         x += CHAR_WIDTH;
     }
     return x;
 }
Referenced by R_RegisterFunctionsRTX().
R_InterceptKey_RTX()
qboolean R_InterceptKey_RTX (unsigned key, qboolean down)
Definition at line 185 of file freecam.c.
 {
     if (cl_paused->integer != 2 || !sv_paused->integer)
         return qfalse;
     const char* kb = Key_GetBindingForKey(key);
     if (kb && strstr(kb, "pause"))
         return qfalse;
     if (cvar_pt_dof->integer != 0 && down && (key == K_MWHEELUP || key == K_MWHEELDOWN))
     {
         cvar_t* var;
         float minvalue;
         float maxvalue;
         if (Key_IsDown(K_SHIFT))
         {
             var = cvar_pt_aperture;
             minvalue = 0.01f;
             maxvalue = 10.f;
         }
         else
         {
             var = cvar_pt_focus;
             minvalue = 1.f;
             maxvalue = 10000.f;
         }
         float factor = Key_IsDown(K_CTRL) ? 1.01f : 1.1f;
         if (key == K_MWHEELDOWN)
             factor = 1.f / factor;
         float value = var->value;
         value *= factor;
         value = max(minvalue, min(maxvalue, value));
         Cvar_SetByVar(var, va("%f", value), FROM_CONSOLE);
         return qtrue;
     }
     switch (key)
     {
     case 'w': freecam_keystate[0] = down; return qtrue;
     case 's': freecam_keystate[1] = down; return qtrue;
     case 'd': freecam_keystate[2] = down; return qtrue;
     case 'a': freecam_keystate[3] = down; return qtrue;
     case 'e': freecam_keystate[4] = down; return qtrue;
     case 'q': freecam_keystate[5] = down; return qtrue;
     // make sure that other keys that control the freecam mode don't
     // interfere with the game, for example MOUSE1 usually maps to fire
     case K_CTRL:
     case K_SHIFT:
     case K_MWHEELDOWN:
     case K_MWHEELUP:
     case K_MOUSE1:
     case K_MOUSE2:
         return qtrue;
     }
     return qfalse;
 }
Referenced by R_RegisterFunctionsRTX().
R_LightPoint_RTX()
void R_LightPoint_RTX (vec3_t origin, vec3_t light)
Definition at line 670 of file draw.c.
 {
     VectorSet(light, 1, 1, 1);
 }
Referenced by R_RegisterFunctionsRTX().
R_SetAlpha_RTX()
void R_SetAlpha_RTX (float alpha)
Definition at line 650 of file draw.c.
 {
     alpha = powf(fabsf(alpha), 0.4545f); // un-sRGB the alpha
     draw.colors[0].u8[3] = draw.colors[1].u8[3] = alpha * 255;
 }
Referenced by R_RegisterFunctionsRTX().
R_SetAlphaScale_RTX()
void R_SetAlphaScale_RTX (float alpha)
Definition at line 657 of file draw.c.
 {
     draw.alpha_scale = alpha;
 }
Referenced by R_RegisterFunctionsRTX().
R_SetClipRect_RTX()
void R_SetClipRect_RTX (const clipRect_t * clip)
Definition at line 629 of file draw.c.
 {
     if (clip)
     {
         clip_enable = qtrue;
         clip_rect = *clip;
     }
     else
     {
         clip_enable = qfalse;
     }
 }
Referenced by R_RegisterFunctionsRTX().
R_SetColor_RTX()
void R_SetColor_RTX (uint32_t color)
Definition at line 663 of file draw.c.
 {
     draw.colors[0].u32   = color;
     draw.colors[1].u8[3] = draw.colors[0].u8[3];
 }
Referenced by R_RegisterFunctionsRTX().
R_SetScale_RTX()
void R_SetScale_RTX (float scale)
Definition at line 676 of file draw.c.
 {
     draw.scale = scale;
 }
Referenced by R_RegisterFunctionsRTX().
R_TileClear_RTX()
void R_TileClear_RTX (int x, int y, int w, int h, qhandle_t pic)
Definition at line 700 of file draw.c.
 {
     enqueue_stretch_pic(x, y, w, h,
         x * DIV64, y * DIV64, (x + w) * DIV64, (y + h) * DIV64,
         U32_WHITE, pic);
 }
Referenced by R_RegisterFunctionsRTX().
set_current_gpu()
void set_current_gpu (VkCommandBuffer cmd_buf, int gpu_index)
Definition at line 426 of file vk_util.c.
 {
 #ifdef VKPT_DEVICE_GROUPS
     if (qvk.device_count > 1)
     {
         if(gpu_index == ALL_GPUS)
             qvkCmdSetDeviceMaskKHR(cmd_buf, (1 << qvk.device_count) - 1);
         else
             qvkCmdSetDeviceMaskKHR(cmd_buf, 1 << gpu_index);
     }
 #endif
 }
Referenced by vkpt_asvgf_create_gradient_samples(), vkpt_create_images(), vkpt_interleave(), vkpt_profiler_query(), vkpt_pt_trace_lighting(), vkpt_pt_trace_primary_rays(), and vkpt_pt_trace_reflections().
update_transparency()
void update_transparency (VkCommandBuffer command_buffer, const float * view_matrix, const particle_t * particles, int particle_num, const entity_t * entities, int entity_num)
Definition at line 171 of file transparency.c.
 {
     transparency.host_frame_index = (transparency.host_frame_index + 1) % transparency.host_buffered_frame_num;
     particle_num = min(particle_num, TR_PARTICLE_MAX_NUM);
     uint32_t beam_num = 0;
     uint32_t sprite_num = 0;
     for (int i = 0; i < entity_num; i++)
     {
         if (entities[i].flags & RF_BEAM)
             ++beam_num;
         else if ((entities[i].model & 0x80000000) == 0)
         {
             const model_t* model = MOD_ForHandle(entities[i].model);
             if (model && model->type == MOD_SPRITE)
                 ++sprite_num;
         }
     }
     beam_num = min(beam_num, TR_BEAM_MAX_NUM);
     sprite_num = min(sprite_num, TR_SPRITE_MAX_NUM);
     transparency.beam_num = beam_num;
     transparency.particle_num = particle_num;
     transparency.sprite_num = sprite_num;
     const size_t particle_vertices_size = particle_num * 4 * TR_POSITION_SIZE;
     const size_t beam_vertices_size = beam_num * 4 * TR_POSITION_SIZE;
     const size_t sprite_vertices_size = sprite_num * 4 * TR_POSITION_SIZE;
     const size_t host_buffer_offset = transparency.host_frame_index * transparency.host_frame_size;
     transparency.vertex_position_host_offset = host_buffer_offset;
     transparency.particle_color_host_offset = host_buffer_offset + particle_vertices_size + beam_vertices_size + sprite_vertices_size;
     transparency.beam_color_host_offset = transparency.particle_color_host_offset + particle_num * TR_COLOR_SIZE;
     transparency.sprite_info_host_offset = transparency.beam_color_host_offset + beam_num * TR_COLOR_SIZE;
     if (particle_num > 0 || beam_num > 0 || sprite_num > 0)
     {
         write_particle_geometry(view_matrix, particles, particle_num);
         write_beam_geometry(view_matrix, entities, entity_num);
         write_sprite_geometry(view_matrix, entities, entity_num);
         upload_geometry(command_buffer);
     }
 }
Referenced by R_RenderFrame_RTX().
vkpt_asvgf_create_gradient_samples()
VkResult vkpt_asvgf_create_gradient_samples (VkCommandBuffer cmd_buf, uint32_t frame_num, int do_gradient_samples)
Definition at line 251 of file asvgf.c.
 {
     VkDescriptorSet desc_sets[] = {
         qvk.desc_set_ubo,
         qvk_get_current_desc_set_textures(),
         qvk.desc_set_vertex_buffer
     };
     VkClearColorValue clear_grd_smpl_pos = {
         .uint32 = { 0, 0, 0, 0 }
     };
     VkImageSubresourceRange subresource_range = {
         .aspectMask     = VK_IMAGE_ASPECT_COLOR_BIT,
         .baseMipLevel   = 0,
         .levelCount     = 1,
         .baseArrayLayer = 0,
         .layerCount     = 1
     };
     int current_sample_pos_image = VKPT_IMG_ASVGF_GRAD_SMPL_POS_A + (qvk.frame_counter & 1);
     BARRIER_TO_CLEAR(cmd_buf, qvk.images[current_sample_pos_image]);
     vkCmdClearColorImage(cmd_buf, qvk.images[current_sample_pos_image],
         VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, &clear_grd_smpl_pos, 1, &subresource_range);
     BARRIER_FROM_CLEAR(cmd_buf, qvk.images[current_sample_pos_image]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_ASVGF_RNG_SEED_A + (qvk.frame_counter & 1)]);
     for(uint32_t gpu = 0; gpu < qvk.device_count; gpu++)
     {
         set_current_gpu(cmd_buf, gpu);
         uint32_t push_constants[1] = {
             gpu
         };
         vkCmdPushConstants(cmd_buf, pipeline_layout_atrous,
             VK_SHADER_STAGE_COMPUTE_BIT, 0, sizeof(push_constants), push_constants);
         vkCmdBindPipeline(cmd_buf, VK_PIPELINE_BIND_POINT_COMPUTE, pipeline_asvgf[SEED_RNG]);
         vkCmdBindDescriptorSets(cmd_buf, VK_PIPELINE_BIND_POINT_COMPUTE,
             pipeline_layout_general, 0, LENGTH(desc_sets), desc_sets, 0, 0);
         vkCmdDispatch(cmd_buf,
             (qvk.gpu_slice_width + 15) / 16,
             (qvk.extent_render.height + 15) / 16,
             1);
     }
     set_current_gpu(cmd_buf, ALL_GPUS);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_ASVGF_RNG_SEED_A + (qvk.frame_counter & 1)]);
     if (do_gradient_samples)
     {
         BEGIN_PERF_MARKER(cmd_buf, PROFILER_ASVGF_DO_GRADIENT_SAMPLES);
         vkCmdBindPipeline(cmd_buf, VK_PIPELINE_BIND_POINT_COMPUTE, pipeline_asvgf[FWD_PROJECT]);
         vkCmdBindDescriptorSets(cmd_buf, VK_PIPELINE_BIND_POINT_COMPUTE,
             pipeline_layout_general, 0, LENGTH(desc_sets), desc_sets, 0, 0);
         vkCmdDispatch(cmd_buf,
             (qvk.gpu_slice_width_prev / GRAD_DWN + 15) / 16,
             (qvk.extent_render_prev.height / GRAD_DWN + 15) / 16,
             1);
         BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_ASVGF_RNG_SEED_A + (qvk.frame_counter & 1)]);
         BARRIER_COMPUTE(cmd_buf, qvk.images[current_sample_pos_image]);
         END_PERF_MARKER(cmd_buf, PROFILER_ASVGF_DO_GRADIENT_SAMPLES);
     }
     return VK_SUCCESS;
 }
Referenced by R_RenderFrame_RTX().
vkpt_asvgf_create_pipelines()
VkResult vkpt_asvgf_create_pipelines ()
Definition at line 91 of file asvgf.c.
 {
     VkSpecializationMapEntry specEntries[] = {
         { .constantID = 0, .offset = 0, .size = sizeof(uint32_t) }
     };
     uint32_t spec_data[] = {
         0,
         1,
         2,
         3
     };
     VkSpecializationInfo specInfo[] = {
         { .mapEntryCount = 1, .pMapEntries = specEntries, .dataSize = sizeof(uint32_t), .pData = &spec_data[0] },
         { .mapEntryCount = 1, .pMapEntries = specEntries, .dataSize = sizeof(uint32_t), .pData = &spec_data[1] },
         { .mapEntryCount = 1, .pMapEntries = specEntries, .dataSize = sizeof(uint32_t), .pData = &spec_data[2] },
         { .mapEntryCount = 1, .pMapEntries = specEntries, .dataSize = sizeof(uint32_t), .pData = &spec_data[3] },
     };
     VkComputePipelineCreateInfo pipeline_info[ASVGF_NUM_PIPELINES] = {
         [SEED_RNG] = {
             .sType  = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
             .stage  = SHADER_STAGE(QVK_MOD_ASVGF_SEED_RNG_COMP, VK_SHADER_STAGE_COMPUTE_BIT),
             .layout = pipeline_layout_atrous,
         },
         [FWD_PROJECT] = {
             .sType  = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
             .stage  = SHADER_STAGE(QVK_MOD_ASVGF_FWD_PROJECT_COMP, VK_SHADER_STAGE_COMPUTE_BIT),
             .layout = pipeline_layout_general,
         },
         [GRADIENT_IMAGE] = {
             .sType  = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
             .stage  = SHADER_STAGE(QVK_MOD_ASVGF_GRADIENT_IMG_COMP, VK_SHADER_STAGE_COMPUTE_BIT),
             .layout = pipeline_layout_general,
         },
         [GRADIENT_ATROUS] = {
             .sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
             .stage = SHADER_STAGE(QVK_MOD_ASVGF_GRADIENT_ATROUS_COMP, VK_SHADER_STAGE_COMPUTE_BIT),
             .layout = pipeline_layout_atrous,
         },
         [TEMPORAL] = {
             .sType  = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
             .stage  = SHADER_STAGE(QVK_MOD_ASVGF_TEMPORAL_COMP, VK_SHADER_STAGE_COMPUTE_BIT),
             .layout = pipeline_layout_general,
         },
         [ATROUS_LF] = {
             .sType  = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
             .stage  = SHADER_STAGE(QVK_MOD_ASVGF_LF_COMP, VK_SHADER_STAGE_COMPUTE_BIT),
             .layout = pipeline_layout_atrous,
         },
         [ATROUS_ITER_0] = {
             .sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
             .stage = SHADER_STAGE_SPEC(QVK_MOD_ASVGF_ATROUS_COMP, VK_SHADER_STAGE_COMPUTE_BIT, &specInfo[0]),
             .layout = pipeline_layout_atrous,
         },
         [ATROUS_ITER_1] = {
             .sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
             .stage = SHADER_STAGE_SPEC(QVK_MOD_ASVGF_ATROUS_COMP, VK_SHADER_STAGE_COMPUTE_BIT, &specInfo[1]),
             .layout = pipeline_layout_atrous,
         },
         [ATROUS_ITER_2] = {
             .sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
             .stage = SHADER_STAGE_SPEC(QVK_MOD_ASVGF_ATROUS_COMP, VK_SHADER_STAGE_COMPUTE_BIT, &specInfo[2]),
             .layout = pipeline_layout_atrous,
         },
         [ATROUS_ITER_3] = {
             .sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
             .stage = SHADER_STAGE_SPEC(QVK_MOD_ASVGF_ATROUS_COMP, VK_SHADER_STAGE_COMPUTE_BIT, &specInfo[3]),
             .layout = pipeline_layout_atrous,
         },
         [CHECKERBOARD_INTERLEAVE] = {
             .sType  = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
             .stage  = SHADER_STAGE(QVK_MOD_CHECKERBOARD_INTERLEAVE_COMP, VK_SHADER_STAGE_COMPUTE_BIT),
             .layout = pipeline_layout_general,
         },
         [TAA] = {
             .sType  = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
             .stage  = SHADER_STAGE(QVK_MOD_ASVGF_TAA_COMP, VK_SHADER_STAGE_COMPUTE_BIT),
             .layout = pipeline_layout_general,
         },
         [COMPOSITING] = {
             .sType  = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
             .stage  = SHADER_STAGE(QVK_MOD_COMPOSITING_COMP, VK_SHADER_STAGE_COMPUTE_BIT),
             .layout = pipeline_layout_general,
         },
     };
     _VK(vkCreateComputePipelines(qvk.device, 0, LENGTH(pipeline_info), pipeline_info, 0, pipeline_asvgf));
     return VK_SUCCESS;
 }
vkpt_asvgf_destroy()
VkResult vkpt_asvgf_destroy ()
Definition at line 81 of file asvgf.c.
 {
     vkDestroyPipelineLayout(qvk.device, pipeline_layout_atrous,     NULL);
     vkDestroyPipelineLayout(qvk.device, pipeline_layout_general,   NULL);
     vkDestroyPipelineLayout(qvk.device, pipeline_layout_taa,   NULL);
     return VK_SUCCESS;
 }
vkpt_asvgf_destroy_pipelines()
VkResult vkpt_asvgf_destroy_pipelines ()
Definition at line 185 of file asvgf.c.
 {
     for(int i = 0; i < ASVGF_NUM_PIPELINES; i++)
         vkDestroyPipeline(qvk.device, pipeline_asvgf[i], NULL);
     return VK_SUCCESS;
 }
vkpt_asvgf_filter()
VkResult vkpt_asvgf_filter (VkCommandBuffer cmd_buf, qboolean enable_lf)
Definition at line 325 of file asvgf.c.
 {
     VkDescriptorSet desc_sets[] = {
         qvk.desc_set_ubo,
         qvk_get_current_desc_set_textures(),
         qvk.desc_set_vertex_buffer
     };
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_COLOR_LF_SH]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_COLOR_LF_COCG]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_COLOR_HF]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_COLOR_SPEC]);
     BEGIN_PERF_MARKER(cmd_buf, PROFILER_ASVGF_RECONSTRUCT_GRADIENT);
     /* create gradient image */
     vkCmdBindPipeline(cmd_buf, VK_PIPELINE_BIND_POINT_COMPUTE, pipeline_asvgf[GRADIENT_IMAGE]);
     vkCmdBindDescriptorSets(cmd_buf, VK_PIPELINE_BIND_POINT_COMPUTE,
         pipeline_layout_atrous, 0, LENGTH(desc_sets), desc_sets, 0, 0);
     vkCmdDispatch(cmd_buf,
             (qvk.gpu_slice_width / GRAD_DWN + 15) / 16,
             (qvk.extent_render.height / GRAD_DWN + 15) / 16,
             1);
     // XXX BARRIERS!!!
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_ASVGF_GRAD_LF_PING]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_ASVGF_GRAD_HF_SPEC_PING]);
     //vkCmdBindPipeline(cmd_buf, VK_PIPELINE_BIND_POINT_COMPUTE, pipeline_asvgf[GRADIENT_ATROUS]);
     vkCmdBindDescriptorSets(cmd_buf, VK_PIPELINE_BIND_POINT_COMPUTE,
         pipeline_layout_atrous, 0, LENGTH(desc_sets), desc_sets, 0, 0);
     /* reconstruct gradient image */
     const int num_atrous_iterations_gradient = 7;
     for(int i = 0; i < num_atrous_iterations_gradient; i++) {
         uint32_t push_constants[1] = {
             i
         };
         vkCmdPushConstants(cmd_buf, pipeline_layout_atrous,
             VK_SHADER_STAGE_COMPUTE_BIT, 0, sizeof(push_constants), push_constants);
         vkCmdBindPipeline(cmd_buf, VK_PIPELINE_BIND_POINT_COMPUTE, pipeline_asvgf[GRADIENT_ATROUS]);
         vkCmdDispatch(cmd_buf,
                 (qvk.gpu_slice_width / GRAD_DWN + 15) / 16,
                 (qvk.extent_render.height / GRAD_DWN + 15) / 16,
                 1);
         BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_ASVGF_GRAD_LF_PING + !(i & 1)]);
         BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_ASVGF_GRAD_HF_SPEC_PING + !(i & 1)]);
     }
     END_PERF_MARKER(cmd_buf, PROFILER_ASVGF_RECONSTRUCT_GRADIENT);
     BEGIN_PERF_MARKER(cmd_buf, PROFILER_ASVGF_TEMPORAL);
     /* temporal accumulation / filtering */
     vkCmdBindPipeline(cmd_buf, VK_PIPELINE_BIND_POINT_COMPUTE, pipeline_asvgf[TEMPORAL]);
     vkCmdBindDescriptorSets(cmd_buf, VK_PIPELINE_BIND_POINT_COMPUTE,
         pipeline_layout_atrous, 0, LENGTH(desc_sets), desc_sets, 0, 0);
     vkCmdDispatch(cmd_buf,
             (qvk.gpu_slice_width + 14) / 15,
             (qvk.extent_render.height + 14) / 15,
             1);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_ASVGF_ATROUS_PING_LF_SH]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_ASVGF_ATROUS_PING_LF_COCG]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_ASVGF_ATROUS_PING_HF]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_ASVGF_ATROUS_PING_MOMENTS]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_ASVGF_FILTERED_SPEC_A + (qvk.frame_counter & 1)]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_ASVGF_HIST_MOMENTS_HF_A]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_ASVGF_HIST_MOMENTS_HF_B]);
     END_PERF_MARKER(cmd_buf, PROFILER_ASVGF_TEMPORAL);
     BEGIN_PERF_MARKER(cmd_buf, PROFILER_ASVGF_ATROUS);
     //vkCmdBindPipeline(cmd_buf, VK_PIPELINE_BIND_POINT_COMPUTE, pipeline_asvgf[ATROUS]);
     vkCmdBindDescriptorSets(cmd_buf, VK_PIPELINE_BIND_POINT_COMPUTE,
         pipeline_layout_atrous, 0, LENGTH(desc_sets), desc_sets, 0, 0);
     /* spatial reconstruction filtering */
     const int num_atrous_iterations = 4;
     for(int i = 0; i < num_atrous_iterations; i++)
     {
         if (enable_lf)
         {
             uint32_t push_constants[1] = {
                 i
             };
             vkCmdPushConstants(cmd_buf, pipeline_layout_atrous,
                 VK_SHADER_STAGE_COMPUTE_BIT, 0, sizeof(push_constants), push_constants);
             vkCmdBindPipeline(cmd_buf, VK_PIPELINE_BIND_POINT_COMPUTE, pipeline_asvgf[ATROUS_LF]);
             vkCmdDispatch(cmd_buf,
                 (qvk.gpu_slice_width / GRAD_DWN + 15) / 16,
                 (qvk.extent_render.height / GRAD_DWN + 15) / 16,
                 1);
             if (i == num_atrous_iterations - 1)
             {
                 BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_ASVGF_ATROUS_PING_LF_SH]);
                 BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_ASVGF_ATROUS_PING_LF_COCG]);
             }
         }
         int specialization = ATROUS_ITER_0 + i;
         vkCmdBindPipeline(cmd_buf, VK_PIPELINE_BIND_POINT_COMPUTE, pipeline_asvgf[specialization]);
         vkCmdDispatch(cmd_buf,
                 (qvk.gpu_slice_width + 15) / 16,
                 (qvk.extent_render.height + 15) / 16,
                 1);
         BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_ASVGF_ATROUS_PING_LF_SH]);
         BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_ASVGF_ATROUS_PING_LF_COCG]);
         BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_ASVGF_ATROUS_PING_HF]);
         BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_ASVGF_ATROUS_PING_MOMENTS]);
         BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_ASVGF_ATROUS_PONG_LF_SH]);
         BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_ASVGF_ATROUS_PONG_LF_COCG]);
         BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_ASVGF_ATROUS_PONG_HF]);
         BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_ASVGF_ATROUS_PONG_MOMENTS]);
         BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_ASVGF_HIST_COLOR_HF]);
         BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_ASVGF_ATROUS_PING_LF_SH + !(i & 1)]);
         BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_ASVGF_ATROUS_PING_LF_COCG + !(i & 1)]);
         BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_ASVGF_COLOR]);
     }
     END_PERF_MARKER(cmd_buf, PROFILER_ASVGF_ATROUS);
     return VK_SUCCESS;
 }
Referenced by R_RenderFrame_RTX().
vkpt_asvgf_initialize()
VkResult vkpt_asvgf_initialize ()
Definition at line 45 of file asvgf.c.
 {
     VkDescriptorSetLayout desc_set_layouts[] = {
         qvk.desc_set_layout_ubo, qvk.desc_set_layout_textures,
         qvk.desc_set_layout_vertex_buffer
     };
     VkPushConstantRange push_constant_range_atrous = {
         .stageFlags = VK_SHADER_STAGE_COMPUTE_BIT,
         .offset     = 0,
         .size       = sizeof(uint32_t)
     };
     CREATE_PIPELINE_LAYOUT(qvk.device, &pipeline_layout_atrous,
         .setLayoutCount         = LENGTH(desc_set_layouts),
         .pSetLayouts            = desc_set_layouts,
         .pushConstantRangeCount = 1,
         .pPushConstantRanges    = &push_constant_range_atrous
     );
     ATTACH_LABEL_VARIABLE(pipeline_layout_atrous, PIPELINE_LAYOUT);
     CREATE_PIPELINE_LAYOUT(qvk.device, &pipeline_layout_general,
         .setLayoutCount         = LENGTH(desc_set_layouts),
         .pSetLayouts            = desc_set_layouts,
     );
     ATTACH_LABEL_VARIABLE(pipeline_layout_general, PIPELINE_LAYOUT);
     CREATE_PIPELINE_LAYOUT(qvk.device, &pipeline_layout_taa,
         .setLayoutCount         = LENGTH(desc_set_layouts),
         .pSetLayouts            = desc_set_layouts,
     );
     ATTACH_LABEL_VARIABLE(pipeline_layout_taa, PIPELINE_LAYOUT);
     return VK_SUCCESS;
 }
vkpt_begin_command_buffer()
VkCommandBuffer vkpt_begin_command_buffer (cmd_buf_group_t * group)
Definition at line 3301 of file main.c.
 {
     if (group->used_this_frame == group->count_per_frame)
     {
         uint32_t new_count = max(4, group->count_per_frame * 2);
         VkCommandBuffer* new_buffers = Z_Mallocz(new_count * MAX_FRAMES_IN_FLIGHT * sizeof(VkCommandBuffer));
         for (int frame = 0; frame < MAX_FRAMES_IN_FLIGHT; frame++)
         {
             if (group->count_per_frame > 0)
             {
                 memcpy(new_buffers + new_count * frame, group->buffers + group->count_per_frame * frame, group->count_per_frame * sizeof(VkCommandBuffer));
             }
             VkCommandBufferAllocateInfo cmd_buf_alloc_info = {
                 .sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO,
                 .commandPool = group->command_pool,
                 .level = VK_COMMAND_BUFFER_LEVEL_PRIMARY,
                 .commandBufferCount = new_count - group->count_per_frame
             };
             _VK(vkAllocateCommandBuffers(qvk.device, &cmd_buf_alloc_info, new_buffers + new_count * frame + group->count_per_frame));
         }
 #ifdef _DEBUG
         void** new_addrs = Z_Mallocz(new_count * MAX_FRAMES_IN_FLIGHT * sizeof(void*));
         if (group->count_per_frame > 0)
         {
             for (int frame = 0; frame < MAX_FRAMES_IN_FLIGHT; frame++)
             {
                 memcpy(new_addrs + new_count * frame, group->buffer_begin_addrs + group->count_per_frame * frame, group->count_per_frame * sizeof(void*));
             }
         }
         Z_Free(group->buffer_begin_addrs);
         group->buffer_begin_addrs = new_addrs;
 #endif
         Z_Free(group->buffers);
         group->buffers = new_buffers;
         group->count_per_frame = new_count;
     }
     VkCommandBuffer cmd_buf = group->buffers[group->count_per_frame * qvk.current_frame_index + group->used_this_frame];
     VkCommandBufferBeginInfo begin_info = {
         .sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO,
         .flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT,
         .pInheritanceInfo = NULL,
     };
     _VK(vkResetCommandBuffer(cmd_buf, 0));
     _VK(vkBeginCommandBuffer(cmd_buf, &begin_info));
 #ifdef _DEBUG
     void** begin_addr = group->buffer_begin_addrs + group->count_per_frame * qvk.current_frame_index + group->used_this_frame;
 #if (defined __GNUC__)
     *begin_addr = __builtin_return_address(0);
 #elif (defined _MSC_VER)
     *begin_addr = _ReturnAddress();
 #else
     *begin_addr = NULL;
 #endif
 #endif
     group->used_this_frame += 1;
     return cmd_buf;
 }
Referenced by change_image_layouts(), create_invalid_texture(), create_swapchain(), fill_index_buffer(), FillVertexAndIndexBuffers(), IMG_ReadPixels_RTX(), load_blue_noise(), R_BeginFrame_RTX(), R_EndFrame_RTX(), R_RenderFrame_RTX(), UploadImage(), vkpt_create_images(), vkpt_pt_create_static(), vkpt_shadow_map_initialize(), vkpt_textures_end_registration(), vkpt_textures_upload_envmap(), and vkpt_vertex_buffer_upload_staging().
vkpt_bloom_create_pipelines()
VkResult vkpt_bloom_create_pipelines ()
Definition at line 176 of file bloom.c.
 {
     VkComputePipelineCreateInfo pipeline_info[BLOOM_NUM_PIPELINES] = {
         [BLUR] = {
             .sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
             .stage = SHADER_STAGE(QVK_MOD_BLOOM_BLUR_COMP, VK_SHADER_STAGE_COMPUTE_BIT),
             .layout = pipeline_layout_blur,
         },
         [COMPOSITE] = {
             .sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
             .stage = SHADER_STAGE(QVK_MOD_BLOOM_COMPOSITE_COMP, VK_SHADER_STAGE_COMPUTE_BIT),
             .layout = pipeline_layout_composite,
         }
     };
     _VK(vkCreateComputePipelines(qvk.device, 0, LENGTH(pipeline_info), pipeline_info, 0, pipelines));
     return VK_SUCCESS;
 }
vkpt_bloom_destroy()
VkResult vkpt_bloom_destroy ()
Definition at line 165 of file bloom.c.
 {
     vkDestroyPipelineLayout(qvk.device, pipeline_layout_blur, NULL);
     pipeline_layout_blur = NULL;
     vkDestroyPipelineLayout(qvk.device, pipeline_layout_composite, NULL);
     pipeline_layout_composite = NULL;
     return VK_SUCCESS;
 }
vkpt_bloom_destroy_pipelines()
VkResult vkpt_bloom_destroy_pipelines ()
Definition at line 196 of file bloom.c.
 {
     for(int i = 0; i < BLOOM_NUM_PIPELINES; i++)
         vkDestroyPipeline(qvk.device, pipelines[i], NULL);
     return VK_SUCCESS;
 }
vkpt_bloom_initialize()
VkResult vkpt_bloom_initialize ()
Definition at line 127 of file bloom.c.
 {
     cvar_bloom_enable = Cvar_Get("bloom_enable", "1", 0);
     cvar_bloom_debug = Cvar_Get("bloom_debug", "0", 0);
     cvar_bloom_sigma = Cvar_Get("bloom_sigma", "0.037", 0); // relative to screen height
     cvar_bloom_intensity = Cvar_Get("bloom_intensity", "0.002", 0);
     cvar_bloom_sigma_water = Cvar_Get("bloom_sigma_water", "0.037", 0);
     cvar_bloom_intensity_water = Cvar_Get("bloom_intensity_water", "0.2", 0);
     VkDescriptorSetLayout desc_set_layouts[] = {
         qvk.desc_set_layout_ubo, qvk.desc_set_layout_textures,
         qvk.desc_set_layout_vertex_buffer
     };
     VkPushConstantRange push_constant_range = {
         .stageFlags = VK_SHADER_STAGE_COMPUTE_BIT,
         .offset     = 0,
         .size       = sizeof(push_constants_hblur)
     };
     CREATE_PIPELINE_LAYOUT(qvk.device, &pipeline_layout_blur,
         .setLayoutCount         = LENGTH(desc_set_layouts),
         .pSetLayouts            = desc_set_layouts,
         .pushConstantRangeCount = 1,
         .pPushConstantRanges    = &push_constant_range
     );
     ATTACH_LABEL_VARIABLE(pipeline_layout_blur, PIPELINE_LAYOUT);
     CREATE_PIPELINE_LAYOUT(qvk.device, &pipeline_layout_composite,
         .setLayoutCount         = LENGTH(desc_set_layouts),
         .pSetLayouts            = desc_set_layouts,
     );
     ATTACH_LABEL_VARIABLE(pipeline_layout_composite, PIPELINE_LAYOUT);
     return VK_SUCCESS;
 }
vkpt_bloom_record_cmd_buffer()
VkResult vkpt_bloom_record_cmd_buffer (VkCommandBuffer cmd_buf)
Definition at line 301 of file bloom.c.
 {
     compute_push_constants();
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_TAA_OUTPUT]);
     // downscale TAA_OUTPUT -> BLOOM_DOWNSCALE_MIP_1 -> BLOOM_VBLUR
     {
         VkImageSubresourceLayers subresource = {
             .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
             .mipLevel = 0,
             .baseArrayLayer = 0,
             .layerCount = 1
         };
         VkOffset3D offset_UL = {
             .x = 0,
             .y = 0,
             .z = 0
         };
         VkOffset3D offset_LR_mip_0 = {
             .x = qvk.extent_screen_images.width,
             .y = qvk.extent_screen_images.height,
             .z = 1
         };
         VkOffset3D offset_LR_mip_1 = {
             .x = qvk.extent_screen_images.width / 2,
             .y = qvk.extent_screen_images.height / 2,
             .z = 1
         };
         VkOffset3D offset_LR_mip_2 = {
             .x = qvk.extent_screen_images.width / 4,
             .y =  qvk.extent_screen_images.height / 4,
             .z = 1
         };
         VkImageBlit blit_mip_0_to_1 = {
             .srcSubresource = subresource,
             .srcOffsets[0] = offset_UL,
             .srcOffsets[1] = offset_LR_mip_0,
             .dstSubresource = subresource,
             .dstOffsets[0] = offset_UL,
             .dstOffsets[1] = offset_LR_mip_1,
         };
         VkImageBlit blit_mip_1_to_2 = {
             .srcSubresource = subresource,
             .srcOffsets[0] = offset_UL,
             .srcOffsets[1] = offset_LR_mip_1,
             .dstSubresource = subresource,
             .dstOffsets[0] = offset_UL,
             .dstOffsets[1] = offset_LR_mip_2,
         };
         BARRIER_TO_COPY_SRC(cmd_buf, qvk.images[VKPT_IMG_TAA_OUTPUT]);
         BARRIER_TO_COPY_DEST(cmd_buf, qvk.images[VKPT_IMG_BLOOM_DOWNSCALE_MIP_1]);
         vkCmdBlitImage(cmd_buf,
             qvk.images[VKPT_IMG_TAA_OUTPUT], VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
             qvk.images[VKPT_IMG_BLOOM_DOWNSCALE_MIP_1], VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
             1, &blit_mip_0_to_1, VK_FILTER_LINEAR);
         BARRIER_FROM_COPY_SRC(cmd_buf, qvk.images[VKPT_IMG_TAA_OUTPUT]);
         BARRIER_FROM_COPY_DEST(cmd_buf, qvk.images[VKPT_IMG_BLOOM_DOWNSCALE_MIP_1]);
         BARRIER_TO_COPY_SRC(cmd_buf, qvk.images[VKPT_IMG_BLOOM_DOWNSCALE_MIP_1]);
         BARRIER_TO_COPY_DEST(cmd_buf, qvk.images[VKPT_IMG_BLOOM_VBLUR]);
         vkCmdBlitImage(cmd_buf,
             qvk.images[VKPT_IMG_BLOOM_DOWNSCALE_MIP_1], VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
             qvk.images[VKPT_IMG_BLOOM_VBLUR], VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
             1, &blit_mip_1_to_2, VK_FILTER_LINEAR);
         BARRIER_FROM_COPY_SRC(cmd_buf, qvk.images[VKPT_IMG_BLOOM_DOWNSCALE_MIP_1]);
         BARRIER_FROM_COPY_DEST(cmd_buf, qvk.images[VKPT_IMG_BLOOM_VBLUR]);
     }
     VkDescriptorSet desc_sets[] = {
         qvk.desc_set_ubo,
         qvk_get_current_desc_set_textures(),
         qvk.desc_set_vertex_buffer
     };
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_BLOOM_VBLUR]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_BLOOM_HBLUR]);
     // apply horizontal blur from BLOOM_VBLUR -> BLOOM_HBLUR
     vkCmdBindPipeline(cmd_buf, VK_PIPELINE_BIND_POINT_COMPUTE, pipelines[BLUR]);
     vkCmdBindDescriptorSets(cmd_buf, VK_PIPELINE_BIND_POINT_COMPUTE,
         pipeline_layout_blur, 0, LENGTH(desc_sets), desc_sets, 0, 0);
     vkCmdPushConstants(cmd_buf, pipeline_layout_blur, VK_SHADER_STAGE_COMPUTE_BIT,
         0, sizeof(push_constants_hblur), &push_constants_hblur);
     vkCmdDispatch(cmd_buf,
         (qvk.extent_render.width / 4 + 15) / 16,
         (qvk.extent_render.height / 4 + 15) / 16,
         1);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_BLOOM_HBLUR]);
     // vertical blur from BLOOM_HBLUR -> BLOOM_VBLUR
     vkCmdPushConstants(cmd_buf, pipeline_layout_blur, VK_SHADER_STAGE_COMPUTE_BIT,
         0, sizeof(push_constants_vblur), &push_constants_vblur);
     vkCmdDispatch(cmd_buf,
         (qvk.extent_render.width / 4 + 15) / 16,
         (qvk.extent_render.height / 4 + 15) / 16,
         1);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_BLOOM_VBLUR]);
     if (cvar_bloom_debug->integer)
     {
         VkImageSubresourceLayers subresource = {
             .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
             .mipLevel = 0,
             .baseArrayLayer = 0,
             .layerCount = 1
         };
         VkOffset3D offset_UL = {
             .x = 0,
             .y = 0,
             .z = 0
         };
         VkOffset3D offset_LR_input = {
             .x = IMG_WIDTH,
             .y = IMG_HEIGHT,
             .z = 1
         };
         VkImageBlit blit_region = {
             .srcSubresource = subresource,
             .srcOffsets[0] = offset_UL,
             .dstSubresource = subresource,
             .dstOffsets[0] = offset_UL,
             .dstOffsets[1] = offset_LR_input,
         };
         BARRIER_TO_COPY_DEST(cmd_buf, qvk.images[VKPT_IMG_TAA_OUTPUT]);
         int vis_img;
         switch(cvar_bloom_debug->integer)
         {
             case 1:
                 vis_img = VKPT_IMG_BLOOM_DOWNSCALE_MIP_1;
                 blit_region.srcOffsets[1].x = IMG_WIDTH / 2;
                 blit_region.srcOffsets[1].y = IMG_HEIGHT / 2;
                 break;
             case 2:
                 vis_img = VKPT_IMG_BLOOM_HBLUR;
                 blit_region.srcOffsets[1].x = IMG_WIDTH / 4;
                 blit_region.srcOffsets[1].y = IMG_HEIGHT / 4;
                 break;
             default:
                 vis_img = VKPT_IMG_BLOOM_VBLUR;
                 blit_region.srcOffsets[1].x = IMG_WIDTH / 4;
                 blit_region.srcOffsets[1].y = IMG_HEIGHT / 4;
                 break;
         }
         vkCmdBlitImage(cmd_buf,
             qvk.images[vis_img], VK_IMAGE_LAYOUT_GENERAL,
             qvk.images[VKPT_IMG_TAA_OUTPUT], VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
             1, &blit_region, VK_FILTER_LINEAR);
         BARRIER_FROM_COPY_DEST(cmd_buf, qvk.images[VKPT_IMG_TAA_OUTPUT]);
     } else {
         // composite bloom into TAA_OUTPUT
         vkCmdBindPipeline(cmd_buf, VK_PIPELINE_BIND_POINT_COMPUTE, pipelines[COMPOSITE]);
         vkCmdBindDescriptorSets(cmd_buf, VK_PIPELINE_BIND_POINT_COMPUTE,
             pipeline_layout_composite, 0, LENGTH(desc_sets), desc_sets, 0, 0);
         vkCmdDispatch(cmd_buf,
             (qvk.extent_render.width + 15) / 16,
             (qvk.extent_render.height + 15) / 16,
             1);
     }
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_BLOOM_VBLUR]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_TAA_OUTPUT]);
     return VK_SUCCESS;
 }
Referenced by R_RenderFrame_RTX().
vkpt_bloom_reset()
void vkpt_bloom_reset ()
Definition at line 76 of file bloom.c.
 {
     bloom_intensity = cvar_bloom_intensity->value;
     bloom_sigma = cvar_bloom_sigma->value;
     under_water_animation = 0.f;
 }
Referenced by R_BeginRegistration_RTX().
vkpt_bloom_update()
void vkpt_bloom_update (QVKUniformBuffer_t * ubo, float frame_time, qboolean under_water, qboolean menu_mode)
Definition at line 88 of file bloom.c.
 {
     if (under_water)
     {
         under_water_animation = min(1.f, under_water_animation + frame_time * 3.f);
         bloom_intensity = cvar_bloom_intensity_water->value;
         bloom_sigma = cvar_bloom_sigma->value;
     }
     else
     {
         under_water_animation = max(0.f, under_water_animation - frame_time * 3.f);
         bloom_intensity = mix(cvar_bloom_intensity->value, cvar_bloom_intensity_water->value, under_water_animation);
         bloom_sigma = mix(cvar_bloom_sigma->value, cvar_bloom_sigma_water->value, under_water_animation);
     }
     static int menu_start_ms = -1;
     if (menu_mode)
     {
         if (menu_start_ms < 0)
             menu_start_ms = Sys_Milliseconds();
         int current_ms = Sys_Milliseconds();
         float phase = max(0.f, min(1.f, (float)(current_ms - menu_start_ms) / 150.f));
         phase = powf(phase, 0.25f);
         bloom_sigma = phase * 0.03f;
         ubo->bloom_intensity = 1.f;
     }
     else
     {
         menu_start_ms = -1;
         ubo->bloom_intensity = bloom_intensity;
     }
 }
Referenced by R_RenderFrame_RTX().
vkpt_build_beam_lights()
void vkpt_build_beam_lights (light_poly_t * light_list, int * num_lights, int max_lights, bsp_t * bsp, entity_t * entities, int num_entites, float adapted_luminance)
Definition at line 492 of file transparency.c.
 {
     const float beam_width = cvar_pt_beam_width->value;
     const float hdr_factor = cvar_pt_beam_lights->value * adapted_luminance * 20.f;
     if (hdr_factor <= 0.f)
         return;
     int num_beams = 0;
     static entity_t* beams[MAX_BEAMS];
     for (int i = 0; i < num_entites; i++)
     {
         if(num_beams == MAX_BEAMS)
             break;
         if ((entities[i].flags & RF_BEAM) != 0)
             beams[num_beams++] = entities + i;
     }
     if (num_beams == 0)
         return;
     qsort(beams, num_beams, sizeof(entity_t*), compare_beams);
     for (int i = 0; i < num_beams; i++)
     {
         if (*num_lights >= max_lights)
             return;
         const entity_t* beam = beams[i];
         vec3_t begin;
         vec3_t end;
         VectorCopy(beam->oldorigin, begin);
         VectorCopy(beam->origin, end);
         vec3_t to_end;
         VectorSubtract(end, begin, to_end);
         vec3_t norm_dir;
         VectorCopy(to_end, norm_dir);
         VectorNormalize(norm_dir);
         VectorMA(begin, -5.f, norm_dir, begin);
         VectorMA(end, 5.f, norm_dir, end);
         vec3_t color;
         cast_u32_to_f32_color(beam->skinnum, &beam->rgba, color, hdr_factor);
         vkpt_build_cylinder_light(light_list, num_lights, max_lights, bsp, begin, end, color, beam_width);
     }
 }
Referenced by R_RenderFrame_RTX().
vkpt_build_cylinder_light()
qboolean vkpt_build_cylinder_light (light_poly_t * light_list, int * num_lights, int max_lights, bsp_t * bsp, vec3_t begin, vec3_t end, vec3_t color, float radius)
Definition at line 408 of file transparency.c.
 {
     vec3_t dir, norm_dir;
     VectorSubtract(end, begin, dir);
     VectorCopy(dir, norm_dir);
     VectorNormalize(norm_dir);
     vec3_t up = { 0.f, 0.f, 1.f };
     vec3_t left = { 1.f, 0.f, 0.f };
     if (fabsf(norm_dir[2]) < 0.9f)
     {
         CrossProduct(up, norm_dir, left);
         VectorNormalize(left);
         CrossProduct(norm_dir, left, up);
         VectorNormalize(up);
     }
     else
     {
         CrossProduct(norm_dir, left, up);
         VectorNormalize(up);
         CrossProduct(up, norm_dir, left);
         VectorNormalize(left);
     }
     vec3_t vertices[6] = {
         { 0.f, 1.f, 0.f },
         { 0.866f, -0.5f, 0.f },
         { -0.866f, -0.5f, 0.f },
         { 0.f, -1.f, 1.f },
         { -0.866f, 0.5f, 1.f },
         { 0.866f, 0.5f, 1.f },
     };
     const int indices[18] = {
         0, 4, 2,
         2, 4, 3,
         2, 3, 1,
         1, 3, 5,
         1, 5, 0,
         0, 5, 4
     };
     for (int vert = 0; vert < 6; vert++)
     {
         vec3_t transformed;
         VectorCopy(begin, transformed);
         VectorMA(transformed, vertices[vert][0] * radius, up, transformed);
         VectorMA(transformed, vertices[vert][1] * radius, left, transformed);
         VectorMA(transformed, vertices[vert][2], dir, transformed);
         VectorCopy(transformed, vertices[vert]);
     }
     for (int tri = 0; tri < 6; tri++)
     {
         if (*num_lights >= max_lights)
             return qfalse;
         int i0 = indices[tri * 3 + 0];
         int i1 = indices[tri * 3 + 1];
         int i2 = indices[tri * 3 + 2];
         light_poly_t* light = light_list + *num_lights;
         VectorCopy(vertices[i0], light->positions + 0);
         VectorCopy(vertices[i1], light->positions + 3);
         VectorCopy(vertices[i2], light->positions + 6);
         get_triangle_off_center(light->positions, light->off_center, NULL);
         light->cluster = BSP_PointLeaf(bsp->nodes, light->off_center)->cluster;
         light->material = NULL;
         light->style = 0;
         VectorCopy(color, light->color);
         if (light->cluster >= 0)
         {
             (*num_lights)++;
         }
     }
     return qtrue;
 }
Referenced by process_regular_entity(), and vkpt_build_beam_lights().
vkpt_compositing()
VkResult vkpt_compositing (VkCommandBuffer cmd_buf)
Definition at line 460 of file asvgf.c.
 {
     VkDescriptorSet desc_sets[] = {
         qvk.desc_set_ubo,
         qvk_get_current_desc_set_textures(),
         qvk.desc_set_vertex_buffer
     };
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_COLOR_LF_SH]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_COLOR_LF_COCG]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_COLOR_HF]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_COLOR_SPEC]);
     BEGIN_PERF_MARKER(cmd_buf, PROFILER_COMPOSITING);
     /* create gradient image */
     vkCmdBindPipeline(cmd_buf, VK_PIPELINE_BIND_POINT_COMPUTE, pipeline_asvgf[COMPOSITING]);
     vkCmdBindDescriptorSets(cmd_buf, VK_PIPELINE_BIND_POINT_COMPUTE,
         pipeline_layout_general, 0, LENGTH(desc_sets), desc_sets, 0, 0);
     vkCmdDispatch(cmd_buf,
         (qvk.gpu_slice_width + 15) / 16,
         (qvk.extent_render.height + 15) / 16,
         1);
     END_PERF_MARKER(cmd_buf, PROFILER_COMPOSITING);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_ASVGF_COLOR]);
     return VK_SUCCESS;
 }
Referenced by R_RenderFrame_RTX().
vkpt_create_images()
VkResult vkpt_create_images ()
Definition at line 1442 of file textures.c.
 {
     VkImageCreateInfo images_create_info[NUM_VKPT_IMAGES] = {
 #define IMG_DO(_name, _binding, _vkformat, _glslformat, _w, _h) \
     [VKPT_IMG_##_name] = { \
         .sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO, \
         .imageType = VK_IMAGE_TYPE_2D, \
         .format = VK_FORMAT_##_vkformat, \
         .extent = { \
             .width  = _w, \
             .height = _h, \
             .depth  = 1 \
         }, \
         .mipLevels             = 1, \
         .arrayLayers           = 1, \
         .samples               = VK_SAMPLE_COUNT_1_BIT, \
         .tiling                = VK_IMAGE_TILING_OPTIMAL, \
         .usage                 = VK_IMAGE_USAGE_STORAGE_BIT \
                                | VK_IMAGE_USAGE_TRANSFER_SRC_BIT \
                                | VK_IMAGE_USAGE_TRANSFER_DST_BIT \
                                | VK_IMAGE_USAGE_SAMPLED_BIT \
                                | VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT, \
         .sharingMode           = VK_SHARING_MODE_EXCLUSIVE, \
         .queueFamilyIndexCount = qvk.queue_idx_graphics, \
         .initialLayout         = VK_IMAGE_LAYOUT_UNDEFINED, \
     },
 LIST_IMAGES
 LIST_IMAGES_A_B
 #undef IMG_DO
     };
 #ifdef VKPT_DEVICE_GROUPS
 #define IMG_DO(_name, _binding, _vkformat, _glslformat, _w, _h) \
     images_create_info[VKPT_IMG_##_name].flags |= \
         VK_IMAGE_CREATE_SPLIT_INSTANCE_BIND_REGIONS_BIT;
 LIST_IMAGES
 LIST_IMAGES_A_B
 #undef IMG_DO
 #endif
     size_t total_size = 0;
     for(int i = 0; i < NUM_VKPT_IMAGES; i++)
     {
         _VK(vkCreateImage(qvk.device, images_create_info + i, NULL, qvk.images + i));
         ATTACH_LABEL_VARIABLE(qvk.images[i], IMAGE);
         VkMemoryRequirements mem_req;
         vkGetImageMemoryRequirements(qvk.device, qvk.images[i], &mem_req);
         total_size += align(mem_req.size, mem_req.alignment);
         _VK(allocate_gpu_memory(mem_req, &mem_images[i]));
         ATTACH_LABEL_VARIABLE(mem_images[i], DEVICE_MEMORY);
         _VK(vkBindImageMemory(qvk.device, qvk.images[i], mem_images[i], 0));
 #ifdef VKPT_DEVICE_GROUPS
         if (qvk.device_count > 1) {
             // create per-device local image bindings so we can copy back and forth
             // create copies of the same image object that will receive full per-GPU mappings
             for(int d = 0; d < qvk.device_count; d++)
             {
                 _VK(vkCreateImage(qvk.device, images_create_info + i, NULL, &qvk.images_local[d][i]));
                 ATTACH_LABEL_VARIABLE(qvk.images_local[d][i], IMAGE);
                 uint32_t device_indices[VKPT_MAX_GPUS];
                 for (int j = 0; j < VKPT_MAX_GPUS; j++)
                 {
                     // all GPUs attach to memory on one device for this image object
                     device_indices[j] = (uint32_t)d;
                 }
                 // shut up lunarg
                 {
                     VkMemoryRequirements mem_req;
                     vkGetImageMemoryRequirements(qvk.device, qvk.images_local[d][i], &mem_req);
                 }
                 VkBindImageMemoryDeviceGroupInfoKHR device_group_info = {
                     .sType = VK_STRUCTURE_TYPE_BIND_IMAGE_MEMORY_DEVICE_GROUP_INFO_KHR,
                     .pNext = NULL,
                     .deviceIndexCount = qvk.device_count,
                     .pDeviceIndices = device_indices,
                     .splitInstanceBindRegionCount = 0,
                     .pSplitInstanceBindRegions = NULL,
                 };
                 VkBindImageMemoryInfoKHR bind_info = {
                     .sType = VK_STRUCTURE_TYPE_BIND_IMAGE_MEMORY_INFO_KHR,
                     .pNext = &device_group_info,
                     .image = qvk.images_local[d][i],
                     .memory = mem_images[i],
                     .memoryOffset = 0,
                 };
                 _VK(qvkBindImageMemory2KHR(qvk.device, 1, &bind_info));
             }
         }
 #endif
     }
     Com_Printf("Screen-space image memory: %.2f MB\n", (float)total_size / 1048576.f);
     /* attach labels to images */
 #define IMG_DO(_name, _binding, ...) \
     ATTACH_LABEL_VARIABLE_NAME(qvk.images[VKPT_IMG_##_name], IMAGE, #_name);
     LIST_IMAGES
     LIST_IMAGES_A_B
 #undef IMG_DO
     /* attach labels to images */
 #define IMG_DO(_name, _binding, ...) \
     ATTACH_LABEL_VARIABLE_NAME(qvk.images[VKPT_IMG_##_name], IMAGE, #_name);
     LIST_IMAGES
     LIST_IMAGES_A_B
 #undef IMG_DO
 #define IMG_DO(_name, _binding, _vkformat, _glslformat, _w, _h) \
     [VKPT_IMG_##_name] = { \
         .sType      = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO, \
         .viewType   = VK_IMAGE_VIEW_TYPE_2D, \
         .format     = VK_FORMAT_##_vkformat, \
         .image      = qvk.images[VKPT_IMG_##_name], \
         .subresourceRange = { \
             .aspectMask     = VK_IMAGE_ASPECT_COLOR_BIT, \
             .baseMipLevel   = 0, \
             .levelCount     = 1, \
             .baseArrayLayer = 0, \
             .layerCount     = 1 \
         }, \
         .components     = { \
             VK_COMPONENT_SWIZZLE_R, \
             VK_COMPONENT_SWIZZLE_G, \
             VK_COMPONENT_SWIZZLE_B, \
             VK_COMPONENT_SWIZZLE_A \
         }, \
     },
     VkImageViewCreateInfo images_view_create_info[NUM_VKPT_IMAGES] = {
         LIST_IMAGES
         LIST_IMAGES_A_B
     };
 #undef IMG_DO
     for(int i = 0; i < NUM_VKPT_IMAGES; i++) {
         _VK(vkCreateImageView(qvk.device, images_view_create_info + i, NULL, qvk.images_views + i));
 #ifdef VKPT_DEVICE_GROUPS
         if (qvk.device_count > 1) {
             for(int d = 0; d < qvk.device_count; d++) {
                 VkImageViewCreateInfo info = images_view_create_info[i];
                 info.image = qvk.images_local[d][i];
                 _VK(vkCreateImageView(qvk.device, &info, NULL, &qvk.images_views_local[d][i]));
             }
         }
 #endif
     }
     /* attach labels to image views */
 #define IMG_DO(_name, ...) \
     ATTACH_LABEL_VARIABLE_NAME(qvk.images_views[VKPT_IMG_##_name], IMAGE_VIEW, #_name);
     LIST_IMAGES
     LIST_IMAGES_A_B
 #undef IMG_DO
 #define IMG_DO(_name, ...) \
     [VKPT_IMG_##_name] = { \
         .sampler     = VK_NULL_HANDLE, \
         .imageView   = qvk.images_views[VKPT_IMG_##_name], \
         .imageLayout = VK_IMAGE_LAYOUT_GENERAL \
     },
     VkDescriptorImageInfo desc_output_img_info[] = {
         LIST_IMAGES
         LIST_IMAGES_A_B
     };
 #undef IMG_DO
     VkDescriptorImageInfo img_info[] = {
 #define IMG_DO(_name, ...) \
         [VKPT_IMG_##_name] = { \
             .imageLayout = VK_IMAGE_LAYOUT_GENERAL, \
             .imageView   = qvk.images_views[VKPT_IMG_##_name], \
             .sampler     = qvk.tex_sampler, \
         },
         LIST_IMAGES
         LIST_IMAGES_A_B
     };
 #undef IMG_DO
     for(int i = VKPT_IMG_BLOOM_HBLUR; i <= VKPT_IMG_BLOOM_VBLUR; i++) {
         img_info[i].sampler = qvk.tex_sampler_linear_clamp;
     }
     VkWriteDescriptorSet output_img_write[NUM_IMAGES * 2];
     for (int even_odd = 0; even_odd < 2; even_odd++)
     {
         /* create information to update descriptor sets */
 #define IMG_DO(_name, _binding, ...) { \
             VkWriteDescriptorSet elem_image = { \
                 .sType           = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET, \
                 .dstSet          = even_odd ? qvk.desc_set_textures_odd : qvk.desc_set_textures_even, \
                 .dstBinding      = BINDING_OFFSET_IMAGES + _binding, \
                 .dstArrayElement = 0, \
                 .descriptorCount = 1, \
                 .descriptorType  = VK_DESCRIPTOR_TYPE_STORAGE_IMAGE, \
                 .pImageInfo      = desc_output_img_info + VKPT_IMG_##_name, \
             }; \
             VkWriteDescriptorSet elem_texture = { \
                 .sType           = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET, \
                 .dstSet          = even_odd ? qvk.desc_set_textures_odd : qvk.desc_set_textures_even, \
                 .dstBinding      = BINDING_OFFSET_TEXTURES + _binding, \
                 .dstArrayElement = 0, \
                 .descriptorCount = 1, \
                 .descriptorType  = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, \
                 .pImageInfo      = img_info + VKPT_IMG_##_name, \
             }; \
             output_img_write[VKPT_IMG_##_name] = elem_image; \
             output_img_write[VKPT_IMG_##_name + NUM_VKPT_IMAGES] = elem_texture; \
         }
         LIST_IMAGES;
         if (even_odd)
         {
             LIST_IMAGES_B_A;
         }
         else
         {
             LIST_IMAGES_A_B;
         }
 #undef IMG_DO
         vkUpdateDescriptorSets(qvk.device, LENGTH(output_img_write), output_img_write, 0, NULL);
     }
     create_readback_image(&qvk.screenshot_image, &qvk.screenshot_image_memory, &qvk.screenshot_image_memory_size, qvk.surf_format.format, qvk.extent_unscaled.width, qvk.extent_unscaled.height);
 #ifdef VKPT_IMAGE_DUMPS
     create_readback_image(&qvk.dump_image, &qvk.dump_image_memory, &qvk.dump_image_memory_size, VK_FORMAT_R16G16B16A16_SFLOAT, qvk.extent_screen_images.width, qvk.extent_screen_images.height);
 #endif
     VkCommandBuffer cmd_buf = vkpt_begin_command_buffer(&qvk.cmd_buffers_graphics);
     VkImageSubresourceRange subresource_range = {
         .aspectMask     = VK_IMAGE_ASPECT_COLOR_BIT,
         .baseMipLevel   = 0,
         .levelCount     = 1,
         .baseArrayLayer = 0,
         .layerCount     = 1
     };
     for (int i = 0; i < NUM_VKPT_IMAGES; i++) {
         IMAGE_BARRIER(cmd_buf,
             .image = qvk.images[i],
             .subresourceRange = subresource_range,
             .srcAccessMask = 0,
             .dstAccessMask = VK_ACCESS_SHADER_WRITE_BIT,
             .oldLayout = VK_IMAGE_LAYOUT_UNDEFINED,
             .newLayout = VK_IMAGE_LAYOUT_GENERAL,
         );
 #ifdef VKPT_DEVICE_GROUPS
         if (qvk.device_count > 1) {
             for(int d = 0; d < qvk.device_count; d++)
             {
                 set_current_gpu(cmd_buf, d);
                 IMAGE_BARRIER(cmd_buf,
                     .image = qvk.images_local[d][i],
                     .subresourceRange = subresource_range,
                     .srcAccessMask = 0,
                     .dstAccessMask = VK_ACCESS_SHADER_WRITE_BIT,
                     .oldLayout = VK_IMAGE_LAYOUT_UNDEFINED,
                     .newLayout = VK_IMAGE_LAYOUT_GENERAL
                 );
             }
             set_current_gpu(cmd_buf, ALL_GPUS);
         }
 #endif
     }
     IMAGE_BARRIER(cmd_buf,
         .image = qvk.screenshot_image,
         .subresourceRange = subresource_range,
         .srcAccessMask = 0,
         .dstAccessMask = VK_ACCESS_HOST_READ_BIT,
         .oldLayout = VK_IMAGE_LAYOUT_UNDEFINED,
         .newLayout = VK_IMAGE_LAYOUT_GENERAL,
         );
 #ifdef VKPT_IMAGE_DUMPS
     IMAGE_BARRIER(cmd_buf,
         .image = qvk.dump_image,
         .subresourceRange = subresource_range,
         .srcAccessMask = 0,
         .dstAccessMask = VK_ACCESS_HOST_READ_BIT,
         .oldLayout = VK_IMAGE_LAYOUT_UNDEFINED,
         .newLayout = VK_IMAGE_LAYOUT_GENERAL,
     );
 #endif
     vkpt_submit_command_buffer_simple(cmd_buf, qvk.queue_graphics, qtrue);
     vkQueueWaitIdle(qvk.queue_graphics);
     return VK_SUCCESS;
 }
vkpt_destroy_god_rays()
VkResult vkpt_destroy_god_rays ()
Definition at line 65 of file god_rays.c.
 {
     vkDestroySampler(qvk.device, god_rays.shadow_sampler, NULL);
     vkDestroyDescriptorPool(qvk.device, god_rays.descriptor_pool, NULL);
     return VK_SUCCESS;
 }
vkpt_destroy_images()
VkResult vkpt_destroy_images ()
Definition at line 1757 of file textures.c.
 {
     for(int i = 0; i < NUM_VKPT_IMAGES; i++) {
         vkDestroyImageView(qvk.device, qvk.images_views[i], NULL);
         vkDestroyImage    (qvk.device, qvk.images[i],       NULL);
         qvk.images_views[i] = VK_NULL_HANDLE;
         qvk.images[i]       = VK_NULL_HANDLE;
 #ifdef VKPT_DEVICE_GROUPS
         if (qvk.device_count > 1) {
             for (int d = 0; d < qvk.device_count; d++)
             {
                 vkDestroyImageView(qvk.device, qvk.images_views_local[d][i], NULL);
                 vkDestroyImage(qvk.device, qvk.images_local[d][i], NULL);
                 qvk.images_views_local[d][i] = VK_NULL_HANDLE;
                 qvk.images_local[d][i] = VK_NULL_HANDLE;
             }
         }
 #endif
         if (mem_images[i])
         {
             vkFreeMemory(qvk.device, mem_images[i], NULL);
             mem_images[i] = VK_NULL_HANDLE;
         }
     }
     destroy_readback_image(&qvk.screenshot_image, &qvk.screenshot_image_memory, &qvk.screenshot_image_memory_size);
 #ifdef VKPT_IMAGE_DUMPS
     destroy_readback_image(&qvk.dump_image, &qvk.dump_image_memory, &qvk.dump_image_memory_size);
 #endif
     return VK_SUCCESS;
 }
vkpt_destroy_shader_modules()
VkResult vkpt_destroy_shader_modules ()
Definition at line 1180 of file main.c.
 {
 #define SHADER_MODULE_DO(a) \
     vkDestroyShaderModule(qvk.device, qvk.shader_modules[a], NULL); \
     qvk.shader_modules[a] = VK_NULL_HANDLE;
     LIST_SHADER_MODULES
 #undef SHADER_MODULE_DO
     return VK_SUCCESS;
 }
Referenced by R_Shutdown_RTX(), and vkpt_reload_shader().
vkpt_draw_clear_stretch_pics()
VkResult vkpt_draw_clear_stretch_pics ()
Definition at line 492 of file draw.c.
 {
     num_stretch_pics = 0;
     return VK_SUCCESS;
 }
Referenced by R_BeginFrame_RTX().
vkpt_draw_create_pipelines()
VkResult vkpt_draw_create_pipelines ()
Definition at line 323 of file draw.c.
 {
     LOG_FUNC();
     assert(desc_set_layout_sbo);
     VkDescriptorSetLayout desc_set_layouts[] = {
         desc_set_layout_sbo, qvk.desc_set_layout_textures
     };
     CREATE_PIPELINE_LAYOUT(qvk.device, &pipeline_layout_stretch_pic,
         .setLayoutCount = LENGTH(desc_set_layouts),
         .pSetLayouts    = desc_set_layouts
     );
     desc_set_layouts[0] = qvk.desc_set_layout_ubo;
     CREATE_PIPELINE_LAYOUT(qvk.device, &pipeline_layout_final_blit,
         .setLayoutCount = LENGTH(desc_set_layouts),
         .pSetLayouts = desc_set_layouts
     );
     VkPipelineShaderStageCreateInfo shader_info[] = {
         SHADER_STAGE(QVK_MOD_STRETCH_PIC_VERT, VK_SHADER_STAGE_VERTEX_BIT),
         SHADER_STAGE(QVK_MOD_STRETCH_PIC_FRAG, VK_SHADER_STAGE_FRAGMENT_BIT)
     };
     VkPipelineVertexInputStateCreateInfo vertex_input_info = {
         .sType                           = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO,
         .vertexBindingDescriptionCount   = 0,
         .pVertexBindingDescriptions      = NULL,
         .vertexAttributeDescriptionCount = 0,
         .pVertexAttributeDescriptions    = NULL,
     };
     VkPipelineInputAssemblyStateCreateInfo input_assembly_info = {
         .sType                  = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO,
         .topology               = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP,
         .primitiveRestartEnable = VK_FALSE,
     };
     VkViewport viewport = {
         .x        = 0.0f,
         .y        = 0.0f,
         .width    = (float) vkpt_draw_get_extent().width,
         .height   = (float) vkpt_draw_get_extent().height,
         .minDepth = 0.0f,
         .maxDepth = 1.0f,
     };
     VkRect2D scissor = {
         .offset = { 0, 0 },
         .extent = vkpt_draw_get_extent(),
     };
     VkPipelineViewportStateCreateInfo viewport_state = {
         .sType         = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO,
         .viewportCount = 1,
         .pViewports    = &viewport,
         .scissorCount  = 1,
         .pScissors     = &scissor,
     };
     VkPipelineRasterizationStateCreateInfo rasterizer_state = {
         .sType                   = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO,
         .depthClampEnable        = VK_FALSE,
         .rasterizerDiscardEnable = VK_FALSE, /* skip rasterizer */
         .polygonMode             = VK_POLYGON_MODE_FILL,
         .lineWidth               = 1.0f,
         .cullMode                = VK_CULL_MODE_BACK_BIT,
         .frontFace               = VK_FRONT_FACE_CLOCKWISE,
         .depthBiasEnable         = VK_FALSE,
         .depthBiasConstantFactor = 0.0f,
         .depthBiasClamp          = 0.0f,
         .depthBiasSlopeFactor    = 0.0f,
     };
     VkPipelineMultisampleStateCreateInfo multisample_state = {
         .sType                 = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO,
         .sampleShadingEnable   = VK_FALSE,
         .rasterizationSamples  = VK_SAMPLE_COUNT_1_BIT,
         .minSampleShading      = 1.0f,
         .pSampleMask           = NULL,
         .alphaToCoverageEnable = VK_FALSE,
         .alphaToOneEnable      = VK_FALSE,
     };
     VkPipelineColorBlendAttachmentState color_blend_attachment = {
         .colorWriteMask      = VK_COLOR_COMPONENT_R_BIT
                              | VK_COLOR_COMPONENT_G_BIT
                              | VK_COLOR_COMPONENT_B_BIT
                              | VK_COLOR_COMPONENT_A_BIT,
         .blendEnable         = VK_TRUE,
         .srcColorBlendFactor = VK_BLEND_FACTOR_SRC_ALPHA,
         .dstColorBlendFactor = VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA,
         .colorBlendOp        = VK_BLEND_OP_ADD,
         .srcAlphaBlendFactor = VK_BLEND_FACTOR_ONE,
         .dstAlphaBlendFactor = VK_BLEND_FACTOR_ZERO,
         .alphaBlendOp        = VK_BLEND_OP_ADD,
     };
     VkPipelineColorBlendStateCreateInfo color_blend_state = {
         .sType           = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO,
         .logicOpEnable   = VK_FALSE,
         .logicOp         = VK_LOGIC_OP_COPY,
         .attachmentCount = 1,
         .pAttachments    = &color_blend_attachment,
         .blendConstants  = { 0.0f, 0.0f, 0.0f, 0.0f },
     };
     VkGraphicsPipelineCreateInfo pipeline_info = {
         .sType      = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO,
         .stageCount = LENGTH(shader_info),
         .pStages    = shader_info,
         .pVertexInputState   = &vertex_input_info,
         .pInputAssemblyState = &input_assembly_info,
         .pViewportState      = &viewport_state,
         .pRasterizationState = &rasterizer_state,
         .pMultisampleState   = &multisample_state,
         .pDepthStencilState  = NULL,
         .pColorBlendState    = &color_blend_state,
         .pDynamicState       = NULL,
         .layout              = pipeline_layout_stretch_pic,
         .renderPass          = render_pass_stretch_pic,
         .subpass             = 0,
         .basePipelineHandle  = VK_NULL_HANDLE,
         .basePipelineIndex   = -1,
     };
     _VK(vkCreateGraphicsPipelines(qvk.device, VK_NULL_HANDLE, 1, &pipeline_info, NULL, &pipeline_stretch_pic));
     ATTACH_LABEL_VARIABLE(pipeline_stretch_pic, PIPELINE);
     VkPipelineShaderStageCreateInfo shader_info_final_blit[] = {
         SHADER_STAGE(QVK_MOD_FINAL_BLIT_VERT, VK_SHADER_STAGE_VERTEX_BIT),
         SHADER_STAGE(QVK_MOD_FINAL_BLIT_LANCZOS_FRAG, VK_SHADER_STAGE_FRAGMENT_BIT)
     };
     pipeline_info.pStages = shader_info_final_blit;
     pipeline_info.layout = pipeline_layout_final_blit;
     _VK(vkCreateGraphicsPipelines(qvk.device, VK_NULL_HANDLE, 1, &pipeline_info, NULL, &pipeline_final_blit));
     ATTACH_LABEL_VARIABLE(pipeline_final_blit, PIPELINE);
     for(int i = 0; i < qvk.num_swap_chain_images; i++) {
         VkImageView attachments[] = {
             qvk.swap_chain_image_views[i]
         };
         VkFramebufferCreateInfo fb_create_info = {
             .sType           = VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO,
             .renderPass      = render_pass_stretch_pic,
             .attachmentCount = 1,
             .pAttachments    = attachments,
             .width           = vkpt_draw_get_extent().width,
             .height          = vkpt_draw_get_extent().height,
             .layers          = 1,
         };
         _VK(vkCreateFramebuffer(qvk.device, &fb_create_info, NULL, framebuffer_stretch_pic + i));
         ATTACH_LABEL_VARIABLE(framebuffer_stretch_pic[i], FRAMEBUFFER);
     }
     return VK_SUCCESS;
 }
vkpt_draw_destroy()
VkResult vkpt_draw_destroy ()
Definition at line 295 of file draw.c.
 {
     LOG_FUNC();
     for(int i = 0; i < MAX_FRAMES_IN_FLIGHT; i++) {
         buffer_destroy(buf_stretch_pic_queue + i);
     }
     vkDestroyRenderPass(qvk.device, render_pass_stretch_pic, NULL);
     vkDestroyDescriptorPool(qvk.device, desc_pool_sbo, NULL);
     vkDestroyDescriptorSetLayout(qvk.device, desc_set_layout_sbo, NULL);
     return VK_SUCCESS;
 }
vkpt_draw_destroy_pipelines()
VkResult vkpt_draw_destroy_pipelines ()
Definition at line 309 of file draw.c.
 {
     LOG_FUNC();
     vkDestroyPipeline(qvk.device, pipeline_stretch_pic, NULL);
     vkDestroyPipeline(qvk.device, pipeline_final_blit, NULL);
     vkDestroyPipelineLayout(qvk.device, pipeline_layout_stretch_pic, NULL);
     vkDestroyPipelineLayout(qvk.device, pipeline_layout_final_blit, NULL);
     for(int i = 0; i < qvk.num_swap_chain_images; i++) {
         vkDestroyFramebuffer(qvk.device, framebuffer_stretch_pic[i], NULL);
     }
     return VK_SUCCESS;
 }
vkpt_draw_initialize()
VkResult vkpt_draw_initialize ()
Definition at line 217 of file draw.c.
 {
     num_stretch_pics = 0;
     LOG_FUNC();
     create_render_pass();
     for(int i = 0; i < MAX_FRAMES_IN_FLIGHT; i++) {
         _VK(buffer_create(buf_stretch_pic_queue + i, sizeof(StretchPic_t) * MAX_STRETCH_PICS,
             VK_BUFFER_USAGE_STORAGE_BUFFER_BIT,
             VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT));
     }
     VkDescriptorSetLayoutBinding layout_bindings[] = {
         {
             .descriptorType  = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
             .descriptorCount = 1,
             .binding         = 0,
             .stageFlags      = VK_SHADER_STAGE_VERTEX_BIT,
         },
     };
     VkDescriptorSetLayoutCreateInfo layout_info = {
         .sType        = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO,
         .bindingCount = LENGTH(layout_bindings),
         .pBindings    = layout_bindings,
     };
     _VK(vkCreateDescriptorSetLayout(qvk.device, &layout_info, NULL, &desc_set_layout_sbo));
     ATTACH_LABEL_VARIABLE(desc_set_layout_sbo, DESCRIPTOR_SET_LAYOUT);
     VkDescriptorPoolSize pool_size = {
         .type            = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
         .descriptorCount = MAX_FRAMES_IN_FLIGHT,
     };
     VkDescriptorPoolCreateInfo pool_info = {
         .sType         = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO,
         .poolSizeCount = 1,
         .pPoolSizes    = &pool_size,
         .maxSets       = MAX_FRAMES_IN_FLIGHT,
     };
     _VK(vkCreateDescriptorPool(qvk.device, &pool_info, NULL, &desc_pool_sbo));
     ATTACH_LABEL_VARIABLE(desc_pool_sbo, DESCRIPTOR_POOL);
     VkDescriptorSetAllocateInfo descriptor_set_alloc_info = {
         .sType              = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO,
         .descriptorPool     = desc_pool_sbo,
         .descriptorSetCount = 1,
         .pSetLayouts        = &desc_set_layout_sbo,
     };
     for(int i = 0; i < MAX_FRAMES_IN_FLIGHT; i++) {
         _VK(vkAllocateDescriptorSets(qvk.device, &descriptor_set_alloc_info, desc_set_sbo + i));
         BufferResource_t *sbo = buf_stretch_pic_queue + i;
         VkDescriptorBufferInfo buf_info = {
             .buffer = sbo->buffer,
             .offset = 0,
             .range  = sizeof(stretch_pic_queue),
         };
         VkWriteDescriptorSet output_buf_write = {
             .sType           = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,
             .dstSet          = desc_set_sbo[i],
             .dstBinding      = 0,
             .dstArrayElement = 0,
             .descriptorType  = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
             .descriptorCount = 1,
             .pBufferInfo     = &buf_info,
         };
         vkUpdateDescriptorSets(qvk.device, 1, &output_buf_write, 0, NULL);
     }
     return VK_SUCCESS;
 }
vkpt_draw_submit_stretch_pics()
VkResult vkpt_draw_submit_stretch_pics (VkCommandBuffer cmd_buf)
Definition at line 499 of file draw.c.
 {
     if (num_stretch_pics == 0)
         return VK_SUCCESS;
     BufferResource_t *buf_spq = buf_stretch_pic_queue + qvk.current_frame_index;
     StretchPic_t *spq_dev = (StretchPic_t *) buffer_map(buf_spq);
     memcpy(spq_dev, stretch_pic_queue, sizeof(StretchPic_t) * num_stretch_pics);
     buffer_unmap(buf_spq);
     spq_dev = NULL;
     VkRenderPassBeginInfo render_pass_info = {
         .sType             = VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO,
         .renderPass        = render_pass_stretch_pic,
         .framebuffer       = framebuffer_stretch_pic[qvk.current_swap_chain_image_index],
         .renderArea.offset = { 0, 0 },
         .renderArea.extent = vkpt_draw_get_extent()
     };
     VkDescriptorSet desc_sets[] = {
         desc_set_sbo[qvk.current_frame_index],
         qvk_get_current_desc_set_textures()
     };
     vkCmdBeginRenderPass(cmd_buf, &render_pass_info, VK_SUBPASS_CONTENTS_INLINE);
     vkCmdBindDescriptorSets(cmd_buf, VK_PIPELINE_BIND_POINT_GRAPHICS,
             pipeline_layout_stretch_pic, 0, LENGTH(desc_sets), desc_sets, 0, 0);
     vkCmdBindPipeline(cmd_buf, VK_PIPELINE_BIND_POINT_GRAPHICS, pipeline_stretch_pic);
     vkCmdDraw(cmd_buf, 4, num_stretch_pics, 0, 0);
     vkCmdEndRenderPass(cmd_buf);
     num_stretch_pics = 0;
     return VK_SUCCESS;
 }
Referenced by R_EndFrame_RTX().
vkpt_extract_emissive_texture_info()
void vkpt_extract_emissive_texture_info (image_t * image)
Definition at line 532 of file textures.c.
 {
     int w = image->upload_width;
     int h = image->upload_height;
     byte* current_pixel = image->pix_data;
     vec3_t emissive_color;
     VectorClear(emissive_color);
     int min_x = w;
     int max_x = -1;
     int min_y = h;
     int max_y = -1;
     for (int y = 0; y < h; y++) {
         for (int x = 0; x < w; x++) {
             if(current_pixel[0] + current_pixel[1] + current_pixel[2] > 0)
             {
                 vec3_t color;
                 color[0] = decode_srgb(current_pixel[0]);
                 color[1] = decode_srgb(current_pixel[1]);
                 color[2] = decode_srgb(current_pixel[2]);
                 color[0] = max(0.f, color[0] + EMISSIVE_TRANSFORM_BIAS);
                 color[1] = max(0.f, color[1] + EMISSIVE_TRANSFORM_BIAS);
                 color[2] = max(0.f, color[2] + EMISSIVE_TRANSFORM_BIAS);
                 VectorAdd(emissive_color, color, emissive_color);
                 min_x = min(min_x, x);
                 min_y = min(min_y, y);
                 max_x = max(max_x, x);
                 max_y = max(max_y, y);
             }
             current_pixel += 4;
         }
     }
     if (min_x <= max_x && min_y <= max_y)
     {
         float normalization = 1.f / (float)((max_x - min_x + 1) * (max_y - min_y + 1));
         VectorScale(emissive_color, normalization, image->light_color);
     }
     else
     {
         VectorSet(image->light_color, 0.f, 0.f, 0.f);
     }
     image->min_light_texcoord[0] = (float)min_x / (float)w;
     image->min_light_texcoord[1] = (float)min_y / (float)h;
     image->max_light_texcoord[0] = (float)(max_x + 1) / (float)w;
     image->max_light_texcoord[1] = (float)(max_y + 1) / (float)h;
     image->entire_texture_emissive = (min_x == 0) && (min_y == 0) && (max_x == w - 1) && (max_y == h - 1);
     image->processing_complete = qtrue;
 }
Referenced by bsp_mesh_register_textures().
vkpt_final_blit_filtered()
VkResult vkpt_final_blit_filtered (VkCommandBuffer cmd_buf)
Definition at line 604 of file draw.c.
 {
     VkRenderPassBeginInfo render_pass_info = {
         .sType = VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO,
         .renderPass = render_pass_stretch_pic,
         .framebuffer = framebuffer_stretch_pic[qvk.current_swap_chain_image_index],
         .renderArea.offset = { 0, 0 },
         .renderArea.extent = vkpt_draw_get_extent()
     };
     VkDescriptorSet desc_sets[] = {
         qvk.desc_set_ubo,
         qvk_get_current_desc_set_textures()
     };
     vkCmdBeginRenderPass(cmd_buf, &render_pass_info, VK_SUBPASS_CONTENTS_INLINE);
     vkCmdBindDescriptorSets(cmd_buf, VK_PIPELINE_BIND_POINT_GRAPHICS,
         pipeline_layout_final_blit, 0, LENGTH(desc_sets), desc_sets, 0, 0);
     vkCmdBindPipeline(cmd_buf, VK_PIPELINE_BIND_POINT_GRAPHICS, pipeline_final_blit);
     vkCmdDraw(cmd_buf, 4, 1, 0, 0);
     vkCmdEndRenderPass(cmd_buf);
     return VK_SUCCESS;
 }
Referenced by R_EndFrame_RTX().
vkpt_final_blit_simple()
VkResult vkpt_final_blit_simple (VkCommandBuffer cmd_buf)
Definition at line 535 of file draw.c.
 {
     VkImageSubresourceRange subresource_range = {
         .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
         .baseMipLevel = 0,
         .levelCount = 1,
         .baseArrayLayer = 0,
         .layerCount = 1
     };
     IMAGE_BARRIER(cmd_buf,
         .image = qvk.swap_chain_images[qvk.current_swap_chain_image_index],
         .subresourceRange = subresource_range,
         .srcAccessMask = 0,
         .dstAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT,
         .oldLayout = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR,
         .newLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL
     );
     int output_img = VKPT_IMG_TAA_OUTPUT;
     IMAGE_BARRIER(cmd_buf,
         .image = qvk.images[output_img],
         .subresourceRange = subresource_range,
         .srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT,
         .dstAccessMask = VK_ACCESS_TRANSFER_READ_BIT,
         .oldLayout = VK_IMAGE_LAYOUT_GENERAL,
         .newLayout = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL
     );
     VkOffset3D blit_size = {
         .x = qvk.extent_render.width,.y = qvk.extent_render.height,.z = 1
     };
     VkOffset3D blit_size_unscaled = {
         .x = qvk.extent_unscaled.width,.y = qvk.extent_unscaled.height,.z = 1
     };
     VkImageBlit img_blit = {
         .srcSubresource = { VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1 },
         .dstSubresource = { VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1 },
         .srcOffsets = { [1] = blit_size },
         .dstOffsets = { [1] = blit_size_unscaled },
     };
     vkCmdBlitImage(cmd_buf,
         qvk.images[output_img], VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
         qvk.swap_chain_images[qvk.current_swap_chain_image_index], VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
         1, &img_blit, VK_FILTER_NEAREST);
     IMAGE_BARRIER(cmd_buf,
         .image = qvk.swap_chain_images[qvk.current_swap_chain_image_index],
         .subresourceRange = subresource_range,
         .srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT,
         .dstAccessMask = 0,
         .oldLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
         .newLayout = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR
     );
     IMAGE_BARRIER(cmd_buf,
         .image = qvk.images[output_img],
         .subresourceRange = subresource_range,
         .srcAccessMask = VK_ACCESS_TRANSFER_READ_BIT,
         .dstAccessMask = VK_ACCESS_SHADER_WRITE_BIT,
         .oldLayout = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
         .newLayout = VK_IMAGE_LAYOUT_GENERAL
     );
     return VK_SUCCESS;
 }
Referenced by R_EndFrame_RTX().
vkpt_free_command_buffers()
void vkpt_free_command_buffers (cmd_buf_group_t * group)
Definition at line 3373 of file main.c.
 {
     if (group->count_per_frame == 0)
         return;
     vkFreeCommandBuffers(qvk.device, group->command_pool, group->count_per_frame * MAX_FRAMES_IN_FLIGHT, group->buffers);
     Z_Free(group->buffers);
     group->buffers = NULL;
 #ifdef _DEBUG
     Z_Free(group->buffer_begin_addrs);
     group->buffer_begin_addrs = NULL;
 #endif
     group->count_per_frame = 0;
     group->used_this_frame = 0;
 }
Referenced by destroy_vulkan().
vkpt_freecam_reset()
void vkpt_freecam_reset ()
Definition at line 55 of file freecam.c.
 {
     if (!freecam_active)
         return;
     Cvar_SetByVar(cl_player_model, va("%d", freecam_player_model), FROM_CODE);
     freecam_active = qfalse;
 }
Referenced by R_Shutdown_RTX(), and vkpt_freecam_update().
vkpt_freecam_update()
void vkpt_freecam_update (float frame_time)
Definition at line 120 of file freecam.c.
 {
     if (cl_paused->integer != 2 || !sv_paused->integer || !cvar_pt_freecam->integer)
     {
         vkpt_freecam_reset();
         return;
     }
     if (!freecam_active)
     {
         VectorCopy(vkpt_refdef.fd->vieworg, freecam_vieworg);
         VectorCopy(vkpt_refdef.fd->viewangles, freecam_viewangles);
         freecam_zoom = 1.f;
         freecam_player_model = cl_player_model->integer;
         freecam_active = qtrue;
     }
     vec3_t prev_vieworg;
     vec3_t prev_viewangles;
     VectorCopy(freecam_vieworg, prev_vieworg);
     VectorCopy(freecam_viewangles, prev_viewangles);
     float prev_zoom = freecam_zoom;
     vec3_t velocity = { 0.f };
     if (freecam_keystate[0]) velocity[0] += 1.f;
     if (freecam_keystate[1]) velocity[0] -= 1.f;
     if (freecam_keystate[2]) velocity[1] += 1.f;
     if (freecam_keystate[3]) velocity[1] -= 1.f;
     if (freecam_keystate[4]) velocity[2] += 1.f;
     if (freecam_keystate[5]) velocity[2] -= 1.f;
     if (Key_IsDown(K_SHIFT))
         VectorScale(velocity, 5.f, velocity);
     else if (Key_IsDown(K_CTRL))
         VectorScale(velocity, 0.1f, velocity);
     vec3_t forward, right, up;
     AngleVectors(freecam_viewangles, forward, right, up);
     float speed = 100.f;
     VectorMA(freecam_vieworg, velocity[0] * frame_time * speed, forward, freecam_vieworg);
     VectorMA(freecam_vieworg, velocity[1] * frame_time * speed, right, freecam_vieworg);
     VectorMA(freecam_vieworg, velocity[2] * frame_time * speed, up, freecam_vieworg);
     vkpt_freecam_mousemove();
     VectorCopy(freecam_vieworg, vkpt_refdef.fd->vieworg);
     VectorCopy(freecam_viewangles, vkpt_refdef.fd->viewangles);
     vkpt_refdef.fd->fov_x = RAD2DEG(atanf(tanf(DEG2RAD(vkpt_refdef.fd->fov_x) * 0.5f) / freecam_zoom)) * 2.f;
     vkpt_refdef.fd->fov_y = RAD2DEG(atanf(tanf(DEG2RAD(vkpt_refdef.fd->fov_y) * 0.5f) / freecam_zoom)) * 2.f;
     if (!VectorCompare(freecam_vieworg, prev_vieworg) || !VectorCompare(freecam_viewangles, prev_viewangles))
     {
         if (freecam_player_model != CL_PLAYER_MODEL_DISABLED && cl_player_model->integer != CL_PLAYER_MODEL_THIRD_PERSON)
             Cvar_SetByVar(cl_player_model, va("%d", CL_PLAYER_MODEL_THIRD_PERSON), FROM_CODE);
         vkpt_reset_accumulation();
     }
     if (freecam_zoom != prev_zoom)
     {
         // zoom doesn't reset the player model, but does reset the accumulation
         vkpt_reset_accumulation();
     }
 }
Referenced by R_RenderFrame_RTX().
vkpt_get_profiler_result()
double vkpt_get_profiler_result (int idx)
Definition at line 183 of file profiler.c.
 {
     double ms = (double)(query_pool_results[idx * 2 + 1] - query_pool_results[idx * 2 + 0]) * 1e-6;
     return ms;
 }
Referenced by draw_query(), and drs_process().
vkpt_god_rays_create_pipelines()
VkResult vkpt_god_rays_create_pipelines ()
Definition at line 73 of file god_rays.c.
 {
     create_pipeline_layout();
     create_pipelines();
     create_descriptor_set();
     // this is a noop outside a shader reload
     update_descriptor_set();
     return VK_SUCCESS;
 }
vkpt_god_rays_destroy_pipelines()
VkResult vkpt_god_rays_destroy_pipelines ()
Definition at line 85 of file god_rays.c.
 {
     for (size_t i = 0; i < LENGTH(god_rays.pipelines); i++) {
         if (god_rays.pipelines[i]) {
             vkDestroyPipeline(qvk.device, god_rays.pipelines[i], NULL);
             god_rays.pipelines[i] = NULL;
         }
     }
     if (god_rays.pipeline_layout) {
         vkDestroyPipelineLayout(qvk.device, god_rays.pipeline_layout, NULL);
         god_rays.pipeline_layout = NULL;
     }
     if (god_rays.descriptor_set_layout) {
         vkDestroyDescriptorSetLayout(qvk.device, god_rays.descriptor_set_layout, NULL);
         god_rays.descriptor_set_layout = NULL;
     }
     return VK_SUCCESS;
 }
vkpt_god_rays_enabled()
qboolean vkpt_god_rays_enabled (const sun_light_t * sun_light)
Definition at line 379 of file god_rays.c.
 {
     return god_rays.enable->integer
         && god_rays.intensity->value > 0.f
         && sun_light->visible
         && !physical_sky_space->integer;  // god rays look weird in space because they also appear outside of the station
 }
Referenced by R_RenderFrame_RTX().
vkpt_god_rays_noop()
VkResult vkpt_god_rays_noop ()
Definition at line 116 of file god_rays.c.
 {
     return VK_SUCCESS;
 }
vkpt_god_rays_prepare_ubo()
void vkpt_god_rays_prepare_ubo (QVKUniformBuffer_t * ubo, const aabb_t * world_aabb, const float * proj, const float * view, const float * shadowmap_viewproj, float shadowmap_depth_scale)
Definition at line 203 of file god_rays.c.
 {
     VectorAdd(world_aabb->mins, world_aabb->maxs, ubo->world_center);
     VectorScale(ubo->world_center, 0.5f, ubo->world_center);
     VectorSubtract(world_aabb->maxs, world_aabb->mins, ubo->world_size);
     VectorScale(ubo->world_size, 0.5f, ubo->world_half_size_inv);
     ubo->world_half_size_inv[0] = 1.f / ubo->world_half_size_inv[0];
     ubo->world_half_size_inv[1] = 1.f / ubo->world_half_size_inv[1];
     ubo->world_half_size_inv[2] = 1.f / ubo->world_half_size_inv[2];
     ubo->shadow_map_depth_scale = shadowmap_depth_scale;
     ubo->god_rays_intensity = max(0.f, god_rays.intensity->value);
     ubo->god_rays_eccentricity = god_rays.eccentricity->value;
     // Shadow parameters
     memcpy(ubo->shadow_map_VP, shadowmap_viewproj, 16 * sizeof(float));
 }
Referenced by R_RenderFrame_RTX().
vkpt_god_rays_update_images()
VkResult vkpt_god_rays_update_images ()
Definition at line 108 of file god_rays.c.
 {
     create_image_views();
     update_descriptor_set();
     return VK_SUCCESS;
 }
vkpt_image_copy()
void vkpt_image_copy (VkCommandBuffer cmd_buf, int src_image_index, int dst_image_index, VkOffset2D src_offset, VkOffset2D dst_offset, VkExtent2D size)
Definition at line 111 of file mgpu.c.
 {
     VkImageSubresourceRange subresource_range = {
         .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
         .baseMipLevel = 0,
         .levelCount = 1,
         .baseArrayLayer = 0,
         .layerCount = 1
     };
     VkImageSubresourceLayers subresource_layers = {
         .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
         .mipLevel = 0,
         .baseArrayLayer = 0,
         .layerCount = 1
     };
     VkImageCopy copy_region = {
         .srcSubresource = subresource_layers,
         .srcOffset.x = src_offset.x,
         .srcOffset.y = src_offset.y,
         .srcOffset.z = 0,
         .dstSubresource = subresource_layers,
         .dstOffset.x = dst_offset.x,
         .dstOffset.y = dst_offset.y,
         .dstOffset.z = 0,
         .extent.width = size.width,
         .extent.height = size.height,
         .extent.depth = 1
     };
     VkMemoryBarrier mem_barrier = {
         .sType = VK_STRUCTURE_TYPE_MEMORY_BARRIER,
         .pNext = NULL,
         .srcAccessMask = VK_ACCESS_MEMORY_READ_BIT | VK_ACCESS_MEMORY_WRITE_BIT,
         .dstAccessMask = VK_ACCESS_MEMORY_READ_BIT | VK_ACCESS_MEMORY_WRITE_BIT,
     };
     vkCmdPipelineBarrier(cmd_buf,
         VK_PIPELINE_STAGE_ALL_COMMANDS_BIT, VK_PIPELINE_STAGE_ALL_COMMANDS_BIT,
         0,
         1, &mem_barrier,
         0, NULL,
         0, NULL);
     vkCmdCopyImage(cmd_buf,
         qvk.images[src_image_index], VK_IMAGE_LAYOUT_GENERAL,
         qvk.images[dst_image_index], VK_IMAGE_LAYOUT_GENERAL,
         1, &copy_region);
 }
vkpt_init_light_textures()
void vkpt_init_light_textures ()
vkpt_initialize_god_rays()
VkResult vkpt_initialize_god_rays ()
Definition at line 51 of file god_rays.c.
 {
     memset(&god_rays, 0, sizeof(god_rays));
     VkPhysicalDeviceProperties properties;
     vkGetPhysicalDeviceProperties(qvk.physical_device, &properties);
     god_rays.intensity = Cvar_Get("gr_intensity", "2.0", 0);
     god_rays.eccentricity = Cvar_Get("gr_eccentricity", "0.75", 0);
     god_rays.enable = Cvar_Get("gr_enable", "1", 0);
     return VK_SUCCESS;
 }
vkpt_interleave()
VkResult vkpt_interleave (VkCommandBuffer cmd_buf)
Definition at line 492 of file asvgf.c.
 {
     VkDescriptorSet desc_sets[] = {
         qvk.desc_set_ubo,
         qvk_get_current_desc_set_textures(),
         qvk.desc_set_vertex_buffer
     };
 #ifdef VKPT_DEVICE_GROUPS
     if (qvk.device_count > 1) {
         BEGIN_PERF_MARKER(cmd_buf, PROFILER_MGPU_TRANSFERS);
         // create full interleaved motion and color buffers on GPU 0
         VkOffset2D offset_left = { 0, 0 };
         VkOffset2D offset_right = { qvk.extent_render.width / 2, 0 };
         VkExtent2D extent = { qvk.extent_render.width / 2, qvk.extent_render.height };
         vkpt_mgpu_image_copy(cmd_buf,
                             VKPT_IMG_PT_MOTION,
                             VKPT_IMG_PT_MOTION,
                             1,
                             0,
                             offset_left,
                             offset_right,
                             extent);
         vkpt_mgpu_image_copy(cmd_buf,
                             VKPT_IMG_ASVGF_COLOR,
                             VKPT_IMG_ASVGF_COLOR,
                             1,
                             0,
                             offset_left,
                             offset_right,
                             extent);
         vkpt_mgpu_global_barrier(cmd_buf);
         END_PERF_MARKER(cmd_buf, PROFILER_MGPU_TRANSFERS);
     }
 #endif
     BEGIN_PERF_MARKER(cmd_buf, PROFILER_INTERLEAVE);
     vkCmdBindPipeline(cmd_buf, VK_PIPELINE_BIND_POINT_COMPUTE, pipeline_asvgf[CHECKERBOARD_INTERLEAVE]);
     vkCmdBindDescriptorSets(cmd_buf, VK_PIPELINE_BIND_POINT_COMPUTE,
         pipeline_layout_general, 0, LENGTH(desc_sets), desc_sets, 0, 0);
     set_current_gpu(cmd_buf, 0);
     // dispatch using the image dimensions, not render dimensions - to clear the unused area with black color
     vkCmdDispatch(cmd_buf,
         (qvk.extent_screen_images.width + 15) / 16,
         (qvk.extent_screen_images.height + 15) / 16,
         1);
     END_PERF_MARKER(cmd_buf, PROFILER_INTERLEAVE);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_FLAT_COLOR]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_FLAT_MOTION]);
     return VK_SUCCESS;
 }
Referenced by R_RenderFrame_RTX().
vkpt_light_buffer_reset_counts()
void vkpt_light_buffer_reset_counts ()
Definition at line 131 of file vertex_buffer.c.
 {
     memset(max_cluster_model_lights, 0, sizeof(max_cluster_model_lights));
     max_model_lights = 0;
 }
Referenced by R_BeginRegistration_RTX().
vkpt_light_buffer_upload_staging()
VkResult vkpt_light_buffer_upload_staging (VkCommandBuffer cmd_buf)
Definition at line 69 of file vertex_buffer.c.
 {
     BufferResource_t* staging = qvk.buf_light_staging + qvk.current_frame_index;
     assert(!staging->is_mapped);
     VkBufferCopy copyRegion = {
         .size = sizeof(LightBuffer),
     };
     vkCmdCopyBuffer(cmd_buf, staging->buffer, qvk.buf_light.buffer, 1, &copyRegion);
     int buffer_idx = qvk.frame_counter % 3;
     if (qvk.buf_light_stats[buffer_idx].buffer)
     {
         vkCmdFillBuffer(cmd_buf, qvk.buf_light_stats[buffer_idx].buffer, 0, qvk.buf_light_stats[buffer_idx].size, 0);
     }
     return VK_SUCCESS;
 }
Referenced by R_RenderFrame_RTX().
vkpt_light_buffer_upload_to_staging()
VkResult vkpt_light_buffer_upload_to_staging (qboolean render_world, bsp_mesh_t * bsp_mesh, bsp_t * bsp, int num_model_lights, light_poly_t * transformed_model_lights, const float * sky_radiance)
Definition at line 310 of file vertex_buffer.c.
 {
     assert(bsp_mesh);
     BufferResource_t* staging = qvk.buf_light_staging + qvk.current_frame_index;
     LightBuffer *lbo = (LightBuffer *)buffer_map(staging);
     assert(lbo);
     if (render_world)
     {
         assert(bsp_mesh->num_clusters + 1 < MAX_LIGHT_LISTS);
         assert(bsp_mesh->num_cluster_lights < MAX_LIGHT_LIST_NODES);
         assert(MAT_GetNumPBRMaterials() < MAX_PBR_MATERIALS);
         assert(bsp_mesh->num_light_polys + num_model_lights < MAX_LIGHT_POLYS);
         int model_light_offset = bsp_mesh->num_light_polys;
         max_model_lights = max(max_model_lights, num_model_lights);
         if(max_model_lights > 0)
         {
             // If any of the BSP models contain lights, inject these lights right into the visibility lists.
             // The shader doesn't know that these lights are dynamic.
             inject_model_lights(bsp_mesh, bsp, num_model_lights, transformed_model_lights, model_light_offset, lbo->light_list_offsets, lbo->light_list_lights);
         }
         else
         {
             memcpy(lbo->light_list_offsets, bsp_mesh->cluster_light_offsets, (bsp_mesh->num_clusters + 1) * sizeof(uint32_t));
             memcpy(lbo->light_list_lights, bsp_mesh->cluster_lights, bsp_mesh->num_cluster_lights * sizeof(uint32_t));
         }
         for (int nlight = 0; nlight < bsp_mesh->num_light_polys; nlight++)
         {
             light_poly_t* light = bsp_mesh->light_polys + nlight;
             float* vblight = lbo->light_polys + nlight * (LIGHT_POLY_VEC4S * 4);
             copy_light(light, vblight, sky_radiance);
         }
         for (int nlight = 0; nlight < num_model_lights; nlight++)
         {
             light_poly_t* light = transformed_model_lights + nlight;
             float* vblight = lbo->light_polys + (nlight + model_light_offset) * (LIGHT_POLY_VEC4S * 4);
             copy_light(light, vblight, sky_radiance);
         }
     }
     else
     {
         lbo->light_list_offsets[0] = 0;
         lbo->light_list_offsets[1] = 0;
     }
     /* effects.c declares this - hence the assert below:
         typedef struct clightstyle_s {
             ...
             float   map[MAX_QPATH];
         } clightstyle_t;
     */
     assert(MAX_LIGHT_STYLES == MAX_QPATH);
     for (int nstyle = 0; nstyle < MAX_LIGHT_STYLES; nstyle++)
     {
         float style_scale = 1.f;
         if (vkpt_refdef.fd->lightstyles)
         {
             style_scale = vkpt_refdef.fd->lightstyles[nstyle].white;
             style_scale = max(0, min(1, style_scale));
         }
         lbo->light_styles[nstyle] = style_scale;
     }
     // materials
     int nmaterials = MAT_GetNumPBRMaterials();
     pbr_material_t const * materials = MAT_GetPBRMaterialsTable();
     for (int nmat = 0; nmat < nmaterials; nmat++)
     {
         pbr_material_t const * material = materials + nmat;
         uint32_t* mat_data = lbo->material_table + nmat * 4;
         memset(mat_data, 0, sizeof(uint32_t) * 4);
         if (material->image_diffuse) mat_data[0] |= (material->image_diffuse - r_images);
         if (material->image_normals) mat_data[0] |= (material->image_normals - r_images) << 16;
         if (material->image_emissive) mat_data[1] |= (material->image_emissive - r_images);
         mat_data[1] |= (material->num_frames & 0x000f) << 28;
         mat_data[1] |= (material->next_frame & 0x0fff) << 16;
         mat_data[2] = floatToHalf(material->bump_scale);
         mat_data[2] |= floatToHalf(material->rough_override) << 16;
         mat_data[3] = floatToHalf(material->specular_scale);
         mat_data[3] |= floatToHalf(material->emissive_scale) << 16;
     }
     memcpy(lbo->cluster_debug_mask, cluster_debug_mask, MAX_LIGHT_LISTS / 8);
     buffer_unmap(staging);
     lbo = NULL;
     return VK_SUCCESS;
 }
Referenced by R_RenderFrame_RTX().
vkpt_light_stats_create()
VkResult vkpt_light_stats_create (bsp_mesh_t * bsp_mesh)
Definition at line 699 of file vertex_buffer.c.
 {
     vkpt_light_stats_destroy();
     // Light statistics: 2 uints (shadowed, unshadowed) per light per surface orientation (6) per cluster.
     uint32_t num_stats = bsp_mesh->num_clusters * bsp_mesh->num_light_polys * 6 * 2;
     // Handle rare cases when the map has zero lights
     if (num_stats == 0)
         num_stats = 1;
     for (int frame = 0; frame < NUM_LIGHT_STATS_BUFFERS; frame++)
     {
         buffer_create(qvk.buf_light_stats + frame, sizeof(uint32_t) * num_stats,
             VK_BUFFER_USAGE_TRANSFER_DST_BIT | VK_BUFFER_USAGE_STORAGE_BUFFER_BIT,
             VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
     }
     assert(NUM_LIGHT_STATS_BUFFERS == 3);
     VkDescriptorBufferInfo light_stats_buf_info[] = { {
             .buffer = qvk.buf_light_stats[0].buffer,
             .offset = 0,
             .range = qvk.buf_light_stats[0].size,
         }, {
             .buffer = qvk.buf_light_stats[1].buffer,
             .offset = 0,
             .range = qvk.buf_light_stats[1].size,
         }, {
             .buffer = qvk.buf_light_stats[2].buffer,
             .offset = 0,
             .range = qvk.buf_light_stats[2].size,
         } };
     VkWriteDescriptorSet output_buf_write = {
         .sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,
         .dstSet = qvk.desc_set_vertex_buffer,
         .dstBinding = 6,
         .dstArrayElement = 0,
         .descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
         .descriptorCount = LENGTH(light_stats_buf_info),
         .pBufferInfo = light_stats_buf_info,
     };
     vkUpdateDescriptorSets(qvk.device, 1, &output_buf_write, 0, NULL);
     return VK_SUCCESS;
 }
Referenced by R_BeginRegistration_RTX().
vkpt_light_stats_destroy()
VkResult vkpt_light_stats_destroy ()
Definition at line 748 of file vertex_buffer.c.
 {
     for (int frame = 0; frame < NUM_LIGHT_STATS_BUFFERS; frame++)
     {
         buffer_destroy(qvk.buf_light_stats + frame);
     }
     return VK_SUCCESS;
 }
Referenced by vkpt_destroy_all(), and vkpt_light_stats_create().
vkpt_load_shader_modules()
VkResult vkpt_load_shader_modules ()
Definition at line 1162 of file main.c.
 {
     VkResult ret = VK_SUCCESS;
 #define SHADER_MODULE_DO(a) do { \
     qvk.shader_modules[a] = create_shader_module_from_file(shader_module_file_names[a], #a); \
     ret = (ret == VK_SUCCESS && qvk.shader_modules[a]) ? VK_SUCCESS : VK_ERROR_INITIALIZATION_FAILED; \
     if(qvk.shader_modules[a]) { \
         ATTACH_LABEL_VARIABLE_NAME((uint64_t)qvk.shader_modules[a], SHADER_MODULE, #a); \
     }\
     } while(0);
     LIST_SHADER_MODULES
 #undef SHADER_MODULE_DO
     return ret;
 }
Referenced by R_Init_RTX(), and vkpt_reload_shader().
vkpt_normalize_normal_map()
void vkpt_normalize_normal_map (image_t * image)
Definition at line 592 of file textures.c.
 {
     int w = image->upload_width;
     int h = image->upload_height;
     byte* current_pixel = image->pix_data;
     for (int y = 0; y < h; y++) {
         for (int x = 0; x < w; x++)
         {
             vec3_t color;
             color[0] = decode_linear(current_pixel[0]);
             color[1] = decode_linear(current_pixel[1]);
             color[2] = decode_linear(current_pixel[2]);
             color[0] = color[0] * 2.f - 1.f;
             color[1] = color[1] * 2.f - 1.f;
             if (VectorNormalize(color) == 0.f)
             {
                 color[0] = 0.f;
                 color[1] = 0.f;
                 color[2] = 1.f;
             }
             color[0] = color[0] * 0.5f + 0.5f;
             color[1] = color[1] * 0.5f + 0.5f;
             current_pixel[0] = encode_linear(color[0]);
             current_pixel[1] = encode_linear(color[1]);
             current_pixel[2] = encode_linear(color[2]);
             current_pixel += 4;
         }
     }
     image->processing_complete = qtrue;
 }
Referenced by bsp_mesh_register_textures(), and IMG_ReloadAll().
vkpt_profiler_destroy()
VkResult vkpt_profiler_destroy ()
Definition at line 42 of file profiler.c.
 {
     vkDestroyQueryPool(qvk.device, query_pool, NULL);
     return VK_SUCCESS;
 }
vkpt_profiler_initialize()
VkResult vkpt_profiler_initialize ()
Definition at line 30 of file profiler.c.
 {
     VkQueryPoolCreateInfo query_pool_info = {
         .sType = VK_STRUCTURE_TYPE_QUERY_POOL_CREATE_INFO,
         .queryType = VK_QUERY_TYPE_TIMESTAMP,
         .queryCount = MAX_FRAMES_IN_FLIGHT * NUM_PROFILER_ENTRIES * 2,
     };
     vkCreateQueryPool(qvk.device, &query_pool_info, NULL, &query_pool);
     return VK_SUCCESS;
 }
vkpt_profiler_next_frame()
VkResult vkpt_profiler_next_frame (VkCommandBuffer cmd_buf)
Definition at line 66 of file profiler.c.
 {
     qboolean any_queries_used = qfalse;
     for (int idx = 0; idx < NUM_PROFILER_QUERIES_PER_FRAME; idx++)
     {
         if (profiler_queries_used[idx + qvk.current_frame_index * NUM_PROFILER_QUERIES_PER_FRAME])
         {
             any_queries_used = qtrue;
             break;
         }
     }
     if (any_queries_used)
     {
         VkResult result = vkGetQueryPoolResults(qvk.device, query_pool,
             NUM_PROFILER_QUERIES_PER_FRAME * qvk.current_frame_index,
             NUM_PROFILER_QUERIES_PER_FRAME,
             sizeof(query_pool_results),
             query_pool_results,
             sizeof(query_pool_results[0]),
             VK_QUERY_RESULT_64_BIT | VK_QUERY_RESULT_WITH_AVAILABILITY_BIT);
         if (result != VK_SUCCESS && result != VK_NOT_READY)
         {
             Com_EPrintf("Failed call to vkGetQueryPoolResults, error code = %d\n", result);
             any_queries_used = qfalse;
         }
     }
     if (any_queries_used)
     {
         for (int idx = 0; idx < NUM_PROFILER_QUERIES_PER_FRAME; idx++)
         {
             if (!profiler_queries_used[idx + qvk.current_frame_index * NUM_PROFILER_QUERIES_PER_FRAME])
                 query_pool_results[idx] = 0;
         }
     }
     else
     {
         memset(query_pool_results, 0, sizeof(query_pool_results));
     }
     vkCmdResetQueryPool(cmd_buf, query_pool,
             NUM_PROFILER_QUERIES_PER_FRAME * qvk.current_frame_index,
             NUM_PROFILER_QUERIES_PER_FRAME);
     memset(profiler_queries_used + qvk.current_frame_index * NUM_PROFILER_QUERIES_PER_FRAME, 0, sizeof(qboolean) * NUM_PROFILER_QUERIES_PER_FRAME);
     return VK_SUCCESS;
 }
Referenced by R_BeginFrame_RTX().
vkpt_profiler_query()
VkResult vkpt_profiler_query (VkCommandBuffer cmd_buf, int idx, VKPTProfilerAction action)
Definition at line 49 of file profiler.c.
 {
     idx = idx * 2 + action + qvk.current_frame_index * NUM_PROFILER_QUERIES_PER_FRAME;
     set_current_gpu(cmd_buf, 0);
     vkCmdWriteTimestamp(cmd_buf, VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT,
             query_pool, idx);
     set_current_gpu(cmd_buf, ALL_GPUS);
     profiler_queries_used[idx] = qtrue;
     return VK_SUCCESS;
 }
Referenced by begin_perf_marker(), end_perf_marker(), and R_RenderFrame_RTX().
vkpt_pt_create_all_dynamic()
VkResult vkpt_pt_create_all_dynamic (VkCommandBuffer cmd_buf, int idx, VkBuffer vertex_buffer, const EntityUploadInfo * upload_info)
Definition at line 781 of file path_tracer.c.
 {
     scratch_buf_ptr = 0;
     vkpt_pt_create_dynamic(cmd_buf, qvk.current_frame_index, qvk.buf_vertex.buffer,
         offsetof(VertexBuffer, positions_instanced), upload_info->dynamic_vertex_num);
     vkpt_pt_create_transparent_models(cmd_buf, qvk.current_frame_index, qvk.buf_vertex.buffer,
         offsetof(VertexBuffer, positions_instanced), upload_info->transparent_model_vertex_num,
         upload_info->transparent_model_vertex_offset);
     vkpt_pt_create_viewer_models(cmd_buf, qvk.current_frame_index, qvk.buf_vertex.buffer,
         offsetof(VertexBuffer, positions_instanced), upload_info->viewer_model_vertex_num,
         upload_info->viewer_model_vertex_offset);
     vkpt_pt_create_viewer_weapon(cmd_buf, qvk.current_frame_index, qvk.buf_vertex.buffer,
         offsetof(VertexBuffer, positions_instanced), upload_info->viewer_weapon_vertex_num,
         upload_info->viewer_weapon_vertex_offset);
     vkpt_pt_create_explosions(cmd_buf, qvk.current_frame_index, qvk.buf_vertex.buffer,
         offsetof(VertexBuffer, positions_instanced), upload_info->explosions_vertex_num,
         upload_info->explosions_vertex_offset);
     MEM_BARRIER_BUILD_ACCEL(cmd_buf);
     scratch_buf_ptr = 0;
     return VK_SUCCESS;
 }
Referenced by R_RenderFrame_RTX().
vkpt_pt_create_pipelines()
VkResult vkpt_pt_create_pipelines ()
Definition at line 1216 of file path_tracer.c.
 {
     VkSpecializationMapEntry specEntry = {
         .constantID = 0,
         .offset = 0,
         .size = sizeof(uint32_t),
     };
     uint32_t numbers[2] = { 0, 1 };
     VkSpecializationInfo specInfo[2] = {
         {
             .mapEntryCount = 1,
             .pMapEntries = &specEntry,
             .dataSize = sizeof(uint32_t),
             .pData = &numbers[0],
         },
         {
             .mapEntryCount = 1,
             .pMapEntries = &specEntry,
             .dataSize = sizeof(uint32_t),
             .pData = &numbers[1],
         }
     };
     VkPipelineShaderStageCreateInfo shader_stages[] = {
         SHADER_STAGE(QVK_MOD_PRIMARY_RAYS_RGEN,               VK_SHADER_STAGE_RAYGEN_BIT_NV),
         SHADER_STAGE_SPEC(QVK_MOD_REFLECT_REFRACT_RGEN,       VK_SHADER_STAGE_RAYGEN_BIT_NV, &specInfo[0]),
         SHADER_STAGE_SPEC(QVK_MOD_REFLECT_REFRACT_RGEN,       VK_SHADER_STAGE_RAYGEN_BIT_NV, &specInfo[1]),
         SHADER_STAGE_SPEC(QVK_MOD_DIRECT_LIGHTING_RGEN,       VK_SHADER_STAGE_RAYGEN_BIT_NV, &specInfo[0]),
         SHADER_STAGE_SPEC(QVK_MOD_DIRECT_LIGHTING_RGEN,       VK_SHADER_STAGE_RAYGEN_BIT_NV, &specInfo[1]),
         SHADER_STAGE_SPEC(QVK_MOD_INDIRECT_LIGHTING_RGEN,     VK_SHADER_STAGE_RAYGEN_BIT_NV, &specInfo[0]),
         SHADER_STAGE_SPEC(QVK_MOD_INDIRECT_LIGHTING_RGEN,     VK_SHADER_STAGE_RAYGEN_BIT_NV, &specInfo[1]),
         SHADER_STAGE(QVK_MOD_PATH_TRACER_RMISS,               VK_SHADER_STAGE_MISS_BIT_NV),
         SHADER_STAGE(QVK_MOD_PATH_TRACER_SHADOW_RMISS,        VK_SHADER_STAGE_MISS_BIT_NV),
         SHADER_STAGE(QVK_MOD_PATH_TRACER_RCHIT,               VK_SHADER_STAGE_CLOSEST_HIT_BIT_NV),
         SHADER_STAGE(QVK_MOD_PATH_TRACER_PARTICLE_RAHIT,      VK_SHADER_STAGE_ANY_HIT_BIT_NV),
         SHADER_STAGE(QVK_MOD_PATH_TRACER_BEAM_RAHIT,          VK_SHADER_STAGE_ANY_HIT_BIT_NV),
         SHADER_STAGE(QVK_MOD_PATH_TRACER_EXPLOSION_RAHIT,     VK_SHADER_STAGE_ANY_HIT_BIT_NV),
         SHADER_STAGE(QVK_MOD_PATH_TRACER_SPRITE_RAHIT,        VK_SHADER_STAGE_ANY_HIT_BIT_NV),
     };
     VkRayTracingShaderGroupCreateInfoNV rt_shader_group_info[] = {
         [SBT_RGEN_PRIMARY_RAYS] = {
             .sType              = VK_STRUCTURE_TYPE_RAY_TRACING_SHADER_GROUP_CREATE_INFO_NV,
             .type               = VK_RAY_TRACING_SHADER_GROUP_TYPE_GENERAL_NV,
             .generalShader      = 0,
             .closestHitShader   = VK_SHADER_UNUSED_NV,
             .anyHitShader       = VK_SHADER_UNUSED_NV,
             .intersectionShader = VK_SHADER_UNUSED_NV
         },
         [SBT_RGEN_REFLECT_REFRACT1] = {
             .sType              = VK_STRUCTURE_TYPE_RAY_TRACING_SHADER_GROUP_CREATE_INFO_NV,
             .type               = VK_RAY_TRACING_SHADER_GROUP_TYPE_GENERAL_NV,
             .generalShader      = 1,
             .closestHitShader   = VK_SHADER_UNUSED_NV,
             .anyHitShader       = VK_SHADER_UNUSED_NV,
             .intersectionShader = VK_SHADER_UNUSED_NV
         },
         [SBT_RGEN_REFLECT_REFRACT2] = {
             .sType              = VK_STRUCTURE_TYPE_RAY_TRACING_SHADER_GROUP_CREATE_INFO_NV,
             .type               = VK_RAY_TRACING_SHADER_GROUP_TYPE_GENERAL_NV,
             .generalShader      = 2,
             .closestHitShader   = VK_SHADER_UNUSED_NV,
             .anyHitShader       = VK_SHADER_UNUSED_NV,
             .intersectionShader = VK_SHADER_UNUSED_NV
         },
         [SBT_RGEN_DIRECT_LIGHTING] = {
             .sType              = VK_STRUCTURE_TYPE_RAY_TRACING_SHADER_GROUP_CREATE_INFO_NV,
             .type               = VK_RAY_TRACING_SHADER_GROUP_TYPE_GENERAL_NV,
             .generalShader      = 3,
             .closestHitShader   = VK_SHADER_UNUSED_NV,
             .anyHitShader       = VK_SHADER_UNUSED_NV,
             .intersectionShader = VK_SHADER_UNUSED_NV
         },
         [SBT_RGEN_DIRECT_LIGHTING_CAUSTICS] = {
             .sType              = VK_STRUCTURE_TYPE_RAY_TRACING_SHADER_GROUP_CREATE_INFO_NV,
             .type               = VK_RAY_TRACING_SHADER_GROUP_TYPE_GENERAL_NV,
             .generalShader      = 4,
             .closestHitShader   = VK_SHADER_UNUSED_NV,
             .anyHitShader       = VK_SHADER_UNUSED_NV,
             .intersectionShader = VK_SHADER_UNUSED_NV
         },
         [SBT_RGEN_INDIRECT_LIGHTING_FIRST] = {
             .sType              = VK_STRUCTURE_TYPE_RAY_TRACING_SHADER_GROUP_CREATE_INFO_NV,
             .type               = VK_RAY_TRACING_SHADER_GROUP_TYPE_GENERAL_NV,
             .generalShader      = 5,
             .closestHitShader   = VK_SHADER_UNUSED_NV,
             .anyHitShader       = VK_SHADER_UNUSED_NV,
             .intersectionShader = VK_SHADER_UNUSED_NV
         },
         [SBT_RGEN_INDIRECT_LIGHTING_SECOND] = {
             .sType              = VK_STRUCTURE_TYPE_RAY_TRACING_SHADER_GROUP_CREATE_INFO_NV,
             .type               = VK_RAY_TRACING_SHADER_GROUP_TYPE_GENERAL_NV,
             .generalShader      = 6,
             .closestHitShader   = VK_SHADER_UNUSED_NV,
             .anyHitShader       = VK_SHADER_UNUSED_NV,
             .intersectionShader = VK_SHADER_UNUSED_NV
         },
         [SBT_RMISS_PATH_TRACER] = {
             .sType              = VK_STRUCTURE_TYPE_RAY_TRACING_SHADER_GROUP_CREATE_INFO_NV,
             .type               = VK_RAY_TRACING_SHADER_GROUP_TYPE_GENERAL_NV,
             .generalShader      = 7,
             .closestHitShader   = VK_SHADER_UNUSED_NV,
             .anyHitShader       = VK_SHADER_UNUSED_NV,
             .intersectionShader = VK_SHADER_UNUSED_NV
         },
         [SBT_RMISS_SHADOW] = {
             .sType              = VK_STRUCTURE_TYPE_RAY_TRACING_SHADER_GROUP_CREATE_INFO_NV,
             .type               = VK_RAY_TRACING_SHADER_GROUP_TYPE_GENERAL_NV,
             .generalShader      = 8,
             .closestHitShader   = VK_SHADER_UNUSED_NV,
             .anyHitShader       = VK_SHADER_UNUSED_NV,
             .intersectionShader = VK_SHADER_UNUSED_NV
         },
         [SBT_RCHIT_OPAQUE] = {
             .sType              = VK_STRUCTURE_TYPE_RAY_TRACING_SHADER_GROUP_CREATE_INFO_NV,
             .type               = VK_RAY_TRACING_SHADER_GROUP_TYPE_TRIANGLES_HIT_GROUP_NV,
             .generalShader      = VK_SHADER_UNUSED_NV,
             .closestHitShader   = 9,
             .anyHitShader       = VK_SHADER_UNUSED_NV,
             .intersectionShader = VK_SHADER_UNUSED_NV
         },
         [SBT_RAHIT_PARTICLE] = {
             .sType              = VK_STRUCTURE_TYPE_RAY_TRACING_SHADER_GROUP_CREATE_INFO_NV,
             .type               = VK_RAY_TRACING_SHADER_GROUP_TYPE_TRIANGLES_HIT_GROUP_NV,
             .generalShader      = VK_SHADER_UNUSED_NV,
             .closestHitShader   = VK_SHADER_UNUSED_NV,
             .anyHitShader       = 10,
             .intersectionShader = VK_SHADER_UNUSED_NV
         },
         [SBT_RAHIT_BEAM] = {
             .sType              = VK_STRUCTURE_TYPE_RAY_TRACING_SHADER_GROUP_CREATE_INFO_NV,
             .type               = VK_RAY_TRACING_SHADER_GROUP_TYPE_TRIANGLES_HIT_GROUP_NV,
             .generalShader      = VK_SHADER_UNUSED_NV,
             .closestHitShader   = VK_SHADER_UNUSED_NV,
             .anyHitShader       = 11,
             .intersectionShader = VK_SHADER_UNUSED_NV
         },
         [SBT_RAHIT_EXPLOSION] = {
             .sType              = VK_STRUCTURE_TYPE_RAY_TRACING_SHADER_GROUP_CREATE_INFO_NV,
             .type               = VK_RAY_TRACING_SHADER_GROUP_TYPE_TRIANGLES_HIT_GROUP_NV,
             .generalShader      = VK_SHADER_UNUSED_NV,
             .closestHitShader   = VK_SHADER_UNUSED_NV,
             .anyHitShader       = 12,
             .intersectionShader = VK_SHADER_UNUSED_NV
         },
         [SBT_RAHIT_SPRITE] = {
             .sType              = VK_STRUCTURE_TYPE_RAY_TRACING_SHADER_GROUP_CREATE_INFO_NV,
             .type               = VK_RAY_TRACING_SHADER_GROUP_TYPE_TRIANGLES_HIT_GROUP_NV,
             .generalShader      = VK_SHADER_UNUSED_NV,
             .closestHitShader   = VK_SHADER_UNUSED_NV,
             .anyHitShader       = 13,
             .intersectionShader = VK_SHADER_UNUSED_NV
         },
         [SBT_RCHIT_EMPTY] = {
             .sType              = VK_STRUCTURE_TYPE_RAY_TRACING_SHADER_GROUP_CREATE_INFO_NV,
             .type               = VK_RAY_TRACING_SHADER_GROUP_TYPE_TRIANGLES_HIT_GROUP_NV,
             .generalShader      = VK_SHADER_UNUSED_NV,
             .closestHitShader   = VK_SHADER_UNUSED_NV,
             .anyHitShader       = VK_SHADER_UNUSED_NV,
             .intersectionShader = VK_SHADER_UNUSED_NV
         },
     };
     VkRayTracingPipelineCreateInfoNV rt_pipeline_info = {
         .sType             = VK_STRUCTURE_TYPE_RAY_TRACING_PIPELINE_CREATE_INFO_NV,
         .stageCount        = LENGTH(shader_stages),
         .pStages           = shader_stages,
         .groupCount        = LENGTH(rt_shader_group_info),
         .pGroups           = rt_shader_group_info,
         .layout            = rt_pipeline_layout,
         .maxRecursionDepth = 1,
     };
     _VK(qvkCreateRayTracingPipelinesNV(qvk.device, NULL, 1, &rt_pipeline_info,     NULL, &rt_pipeline    ));
     uint32_t num_groups = LENGTH(rt_shader_group_info);
     uint32_t shader_binding_table_size = rt_properties.shaderGroupHandleSize * num_groups;
     /* pt */
     _VK(buffer_create(&buf_shader_binding_table, shader_binding_table_size,
                 VK_BUFFER_USAGE_TRANSFER_SRC_BIT, VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT));
     void *shader_binding_table = buffer_map(&buf_shader_binding_table);
     _VK(qvkGetRayTracingShaderGroupHandlesNV(qvk.device, rt_pipeline, 0, num_groups,
                 shader_binding_table_size, shader_binding_table));
     buffer_unmap(&buf_shader_binding_table);
     shader_binding_table = NULL;
     return VK_SUCCESS;
 }
vkpt_pt_create_static()
VkResult vkpt_pt_create_static (VkBuffer vertex_buffer, size_t buffer_offset, int num_vertices, int num_vertices_transparent, int num_vertices_sky, int num_vertices_custom_sky)
Definition at line 574 of file path_tracer.c.
 {
     VkCommandBuffer cmd_buf = vkpt_begin_command_buffer(&qvk.cmd_buffers_graphics);
     scratch_buf_ptr = 0;
     VkResult ret = vkpt_pt_create_accel_bottom(
         vertex_buffer,
         buffer_offset,
         num_vertices,
         &accel_static,
         NULL,
         &mem_accel_static,
         cmd_buf,
         VK_FALSE);
     MEM_BARRIER_BUILD_ACCEL(cmd_buf);
     scratch_buf_ptr = 0;
     ret = vkpt_pt_create_accel_bottom(
         vertex_buffer,
         buffer_offset + num_vertices * sizeof(float) * 3,
         num_vertices_transparent,
         &accel_transparent,
         NULL,
         &mem_accel_transparent,
         cmd_buf,
         VK_FALSE);
     MEM_BARRIER_BUILD_ACCEL(cmd_buf);
     scratch_buf_ptr = 0;
     ret = vkpt_pt_create_accel_bottom(
         vertex_buffer,
         buffer_offset + (num_vertices + num_vertices_transparent) * sizeof(float) * 3,
         num_vertices_sky,
         &accel_sky,
         NULL,
         &mem_accel_sky,
         cmd_buf,
         VK_FALSE);
     MEM_BARRIER_BUILD_ACCEL(cmd_buf);
     scratch_buf_ptr = 0;
     ret = vkpt_pt_create_accel_bottom(
         vertex_buffer,
         buffer_offset + (num_vertices + num_vertices_transparent + num_vertices_sky) * sizeof(float) * 3,
         num_vertices_custom_sky,
         &accel_custom_sky,
         NULL,
         &mem_accel_custom_sky,
         cmd_buf,
         VK_FALSE);
     MEM_BARRIER_BUILD_ACCEL(cmd_buf);
     scratch_buf_ptr = 0;
     transparent_primitive_offset = num_vertices / 3;
     sky_primitive_offset = transparent_primitive_offset + num_vertices_transparent / 3;
     custom_sky_primitive_offset = sky_primitive_offset + num_vertices_sky / 3;
     vkpt_submit_command_buffer_simple(cmd_buf, qvk.queue_graphics, qtrue);
     vkpt_wait_idle(qvk.queue_graphics, &qvk.cmd_buffers_graphics);
     return ret;
 }
Referenced by R_BeginRegistration_RTX().
vkpt_pt_create_toplevel()
VkResult vkpt_pt_create_toplevel (VkCommandBuffer cmd_buf, int idx, qboolean include_world, qboolean weapon_left_handed)
Definition at line 852 of file path_tracer.c.
 {
     QvkGeometryInstance_t instances[INSTANCE_MAX_NUM];
     int num_instances = 0;
     if (include_world)
     {
         append_blas(instances, &num_instances, accel_static, 0, AS_FLAG_OPAQUE, 0, 0);
         append_blas(instances, &num_instances, accel_transparent, transparent_primitive_offset, AS_FLAG_TRANSPARENT, 0, 0);
         append_blas(instances, &num_instances, accel_sky, AS_INSTANCE_FLAG_SKY | sky_primitive_offset, AS_FLAG_SKY, 0, 0);
         append_blas(instances, &num_instances, accel_custom_sky, AS_INSTANCE_FLAG_SKY | custom_sky_primitive_offset, AS_FLAG_CUSTOM_SKY, 0, 0);
     }
     append_blas(instances, &num_instances, accel_dynamic[idx], AS_INSTANCE_FLAG_DYNAMIC, AS_FLAG_OPAQUE, 0, 0);
     if (transparent_models_present)
     {
         append_blas(instances, &num_instances, accel_transparent_models[idx], AS_INSTANCE_FLAG_DYNAMIC | transparent_model_primitive_offset, AS_FLAG_TRANSPARENT, 0, 0);
     }
     if (cl_player_model->integer == CL_PLAYER_MODEL_FIRST_PERSON)
     {
         append_blas(instances, &num_instances, accel_viewer_models[idx], AS_INSTANCE_FLAG_DYNAMIC | viewer_model_primitive_offset, AS_FLAG_VIEWER_MODELS, VK_GEOMETRY_INSTANCE_TRIANGLE_CULL_DISABLE_BIT_NV, 0);
         append_blas(instances, &num_instances, accel_viewer_weapon[idx], AS_INSTANCE_FLAG_DYNAMIC | viewer_weapon_primitive_offset, AS_FLAG_VIEWER_WEAPON, weapon_left_handed ? VK_GEOMETRY_INSTANCE_TRIANGLE_FRONT_COUNTERCLOCKWISE_BIT_NV : 0, 0);
     }
     int particle_num, beam_num, sprite_num;
     get_transparency_counts(&particle_num, &beam_num, &sprite_num);
     if (cvar_pt_enable_particles->integer != 0 && particle_num > 0)
     {
         append_blas(instances, &num_instances, get_transparency_particle_blas(), 0, AS_FLAG_PARTICLES, VK_GEOMETRY_INSTANCE_TRIANGLE_CULL_DISABLE_BIT_NV, 1);
     }
     if (cvar_pt_enable_beams->integer != 0 && beam_num > 0)
     {
         append_blas(instances, &num_instances, get_transparency_beam_blas(), 0, AS_FLAG_PARTICLES, VK_GEOMETRY_INSTANCE_TRIANGLE_CULL_DISABLE_BIT_NV, 2);
     }
     if (cvar_pt_enable_sprites->integer != 0 && sprite_num > 0)
     {
         append_blas(instances, &num_instances, get_transparency_sprite_blas(), 0, AS_FLAG_EXPLOSIONS, VK_GEOMETRY_INSTANCE_TRIANGLE_CULL_DISABLE_BIT_NV, 4);
     }
     if(explosions_present)
     {
         append_blas(instances, &num_instances, accel_explosions[idx], AS_INSTANCE_FLAG_DYNAMIC | explosions_primitive_offset, AS_FLAG_EXPLOSIONS, 0, 3);
     }
     void *instance_data = buffer_map(buf_instances + idx);
     memcpy(instance_data, &instances, sizeof(QvkGeometryInstance_t) * num_instances);
     buffer_unmap(buf_instances + idx);
     instance_data = NULL;
     VkAccelerationStructureCreateInfoNV accel_create_info = {
         .sType = VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_CREATE_INFO_NV,
         .info = {
             .sType = VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_INFO_NV,
             .instanceCount = num_instances,
             .geometryCount = 0,
             .pGeometries   = NULL,
             .type         = VK_ACCELERATION_STRUCTURE_TYPE_TOP_LEVEL_NV
         }
     };
     if (accel_top_match[idx].instanceCount < accel_create_info.info.instanceCount) {
         vkpt_pt_destroy_toplevel(idx);
         qvkCreateAccelerationStructureNV(qvk.device, &accel_create_info, NULL, accel_top + idx);
         /* XXX: do allocation only once with safety margin */
         VkAccelerationStructureMemoryRequirementsInfoNV mem_req_info = {
             .sType = VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_MEMORY_REQUIREMENTS_INFO_NV,
             .accelerationStructure = accel_top[idx],
             .type = VK_ACCELERATION_STRUCTURE_MEMORY_REQUIREMENTS_TYPE_OBJECT_NV
         };
         VkMemoryRequirements2 mem_req = { 0 };
         mem_req.sType = VK_STRUCTURE_TYPE_MEMORY_REQUIREMENTS_2;
         qvkGetAccelerationStructureMemoryRequirementsNV(qvk.device, &mem_req_info, &mem_req);
         _VK(allocate_gpu_memory(mem_req.memoryRequirements, mem_accel_top + idx));
         VkBindAccelerationStructureMemoryInfoNV bind_info = {
             .sType = VK_STRUCTURE_TYPE_BIND_ACCELERATION_STRUCTURE_MEMORY_INFO_NV,
             .accelerationStructure = accel_top[idx],
             .memory = mem_accel_top[idx],
         };
         _VK(qvkBindAccelerationStructureMemoryNV(qvk.device, 1, &bind_info));
         assert(get_scratch_buffer_size(accel_top[idx]) < SIZE_SCRATCH_BUFFER);
         accel_top_match[idx].instanceCount = accel_create_info.info.instanceCount;
     }
     VkAccelerationStructureInfoNV as_info = {
         .sType = VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_INFO_NV,
         .type = VK_ACCELERATION_STRUCTURE_TYPE_TOP_LEVEL_NV,
         .geometryCount = 0,
         .pGeometries = NULL,
         .instanceCount = num_instances,
     };
     qvkCmdBuildAccelerationStructureNV(
             cmd_buf,
             &as_info,
             buf_instances[idx].buffer, /* instance buffer */
             0 /* instance offset */,
             VK_FALSE,  /* update */
             accel_top[idx],
             VK_NULL_HANDLE, /* source acceleration structure ?? */
             buf_accel_scratch.buffer,
             0 /* scratch offset */);
     MEM_BARRIER_BUILD_ACCEL(cmd_buf); /* probably not needed here but doesn't matter */
     return VK_SUCCESS;
 }
Referenced by R_RenderFrame_RTX().
vkpt_pt_destroy()
VkResult vkpt_pt_destroy ()
Definition at line 1196 of file path_tracer.c.
 {
     for(int i = 0; i < MAX_FRAMES_IN_FLIGHT; i++) {
         vkpt_pt_destroy_toplevel(i);
         buffer_destroy(buf_instances + i);
         vkpt_pt_destroy_dynamic(i);
         vkpt_pt_destroy_transparent_models(i);
         vkpt_pt_destroy_viewer_models(i);
         vkpt_pt_destroy_viewer_weapon(i);
         vkpt_pt_destroy_explosions(i);
     }
     vkpt_pt_destroy_static();
     buffer_destroy(&buf_accel_scratch);
     vkDestroyDescriptorSetLayout(qvk.device, rt_descriptor_set_layout, NULL);
     vkDestroyPipelineLayout(qvk.device, rt_pipeline_layout, NULL);
     vkDestroyDescriptorPool(qvk.device, rt_descriptor_pool, NULL);
     return VK_SUCCESS;
 }
vkpt_pt_destroy_pipelines()
VkResult vkpt_pt_destroy_pipelines ()
Definition at line 1410 of file path_tracer.c.
 {
     buffer_destroy(&buf_shader_binding_table);
     vkDestroyPipeline(qvk.device, rt_pipeline, NULL);
     return VK_SUCCESS;
 }
vkpt_pt_destroy_static()
VkResult vkpt_pt_destroy_static ()
Definition at line 345 of file path_tracer.c.
 {
     if(mem_accel_static) {
         vkFreeMemory(qvk.device, mem_accel_static, NULL);
         mem_accel_static = VK_NULL_HANDLE;
     }
     if (mem_accel_transparent) {
         vkFreeMemory(qvk.device, mem_accel_transparent, NULL);
         mem_accel_transparent = VK_NULL_HANDLE;
     }
     if (mem_accel_sky) {
         vkFreeMemory(qvk.device, mem_accel_sky, NULL);
         mem_accel_sky = VK_NULL_HANDLE;
     }
     if (mem_accel_custom_sky) {
         vkFreeMemory(qvk.device, mem_accel_custom_sky, NULL);
         mem_accel_custom_sky = VK_NULL_HANDLE;
     }
     if(accel_static) {
         qvkDestroyAccelerationStructureNV(qvk.device, accel_static, NULL);
         accel_static = VK_NULL_HANDLE;
     }
     if (accel_transparent) {
         qvkDestroyAccelerationStructureNV(qvk.device, accel_transparent, NULL);
         accel_transparent = VK_NULL_HANDLE;
     }
     if (accel_sky) {
         qvkDestroyAccelerationStructureNV(qvk.device, accel_sky, NULL);
         accel_sky = VK_NULL_HANDLE;
     }
     if (accel_custom_sky) {
         qvkDestroyAccelerationStructureNV(qvk.device, accel_custom_sky, NULL);
         accel_custom_sky = VK_NULL_HANDLE;
     }
     return VK_SUCCESS;
 }
Referenced by R_BeginRegistration_RTX(), and vkpt_pt_destroy().
vkpt_pt_init()
VkResult vkpt_pt_init ()
Definition at line 134 of file path_tracer.c.
 {
     VkPhysicalDeviceProperties2 dev_props2 = {
         .sType      = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2,
         .pNext      = &rt_properties,
     };
     vkGetPhysicalDeviceProperties2(qvk.physical_device, &dev_props2);
     Com_Printf("Maximum recursion depth: %d\n",  rt_properties.maxRecursionDepth);
     Com_Printf("Shader group handle size: %d\n", rt_properties.shaderGroupHandleSize);
     buffer_create(&buf_accel_scratch, SIZE_SCRATCH_BUFFER, VK_BUFFER_USAGE_RAY_TRACING_BIT_NV,
             VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
     for(int i = 0; i < MAX_FRAMES_IN_FLIGHT; i++) {
         buffer_create(buf_instances + i, INSTANCE_MAX_NUM * sizeof(QvkGeometryInstance_t), VK_BUFFER_USAGE_RAY_TRACING_BIT_NV,
                 VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
     }
     /* create descriptor set layout */
     VkDescriptorSetLayoutBinding bindings[] = {
         {
             .binding         = RAY_GEN_ACCEL_STRUCTURE_BINDING_IDX,
             .descriptorType  = VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_NV,
             .descriptorCount = 1,
             .stageFlags      = VK_SHADER_STAGE_RAYGEN_BIT_NV,
         },
         {
             .binding         = RAY_GEN_PARTICLE_COLOR_BUFFER_BINDING_IDX,
             .descriptorType  = VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER,
             .descriptorCount = 1,
             .stageFlags      = VK_SHADER_STAGE_ANY_HIT_BIT_NV,
         },
         {
             .binding         = RAY_GEN_BEAM_COLOR_BUFFER_BINDING_IDX,
             .descriptorType  = VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER,
             .descriptorCount = 1,
             .stageFlags      = VK_SHADER_STAGE_ANY_HIT_BIT_NV,
         },
         {
             .binding         = RAY_GEN_SPRITE_INFO_BUFFER_BINDING_IDX,
             .descriptorType  = VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER,
             .descriptorCount = 1,
             .stageFlags      = VK_SHADER_STAGE_ANY_HIT_BIT_NV,
         },
     };
     VkDescriptorSetLayoutCreateInfo layout_info = {
         .sType        = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO,
         .bindingCount = LENGTH(bindings),
         .pBindings    = bindings
     };
     _VK(vkCreateDescriptorSetLayout(qvk.device, &layout_info, NULL, &rt_descriptor_set_layout));
     ATTACH_LABEL_VARIABLE(rt_descriptor_set_layout, DESCRIPTOR_SET_LAYOUT);
     VkDescriptorSetLayout desc_set_layouts[] = {
         rt_descriptor_set_layout,
         qvk.desc_set_layout_ubo,
         qvk.desc_set_layout_textures,
         qvk.desc_set_layout_vertex_buffer
     };
     /* create pipeline */
     VkPushConstantRange push_constant_range = {
         .stageFlags     = VK_SHADER_STAGE_RAYGEN_BIT_NV,
         .offset         = 0,
         .size           = sizeof(int) * 2,
     };
     VkPipelineLayoutCreateInfo pipeline_layout_create_info = {
         .sType          = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO,
         .setLayoutCount = LENGTH(desc_set_layouts),
         .pSetLayouts    = desc_set_layouts,
         .pushConstantRangeCount = 1,
         .pPushConstantRanges = &push_constant_range,
     };
     _VK(vkCreatePipelineLayout(qvk.device, &pipeline_layout_create_info, NULL, &rt_pipeline_layout));
     ATTACH_LABEL_VARIABLE(rt_pipeline_layout, PIPELINE_LAYOUT);
     VkDescriptorPoolSize pool_sizes[] = {
         { VK_DESCRIPTOR_TYPE_STORAGE_IMAGE,             MAX_FRAMES_IN_FLIGHT },
         { VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_NV, MAX_FRAMES_IN_FLIGHT }
     };
     VkDescriptorPoolCreateInfo pool_create_info = {
         .sType         = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO,
         .maxSets       = MAX_FRAMES_IN_FLIGHT,
         .poolSizeCount = LENGTH(pool_sizes),
         .pPoolSizes    = pool_sizes
     };
     _VK(vkCreateDescriptorPool(qvk.device, &pool_create_info, NULL, &rt_descriptor_pool));
     ATTACH_LABEL_VARIABLE(rt_descriptor_pool, DESCRIPTOR_POOL);
     VkDescriptorSetAllocateInfo descriptor_set_alloc_info = {
         .sType              = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO,
         .descriptorPool     = rt_descriptor_pool,
         .descriptorSetCount = 1,
         .pSetLayouts        = &rt_descriptor_set_layout,
     };
     for(int i = 0; i < MAX_FRAMES_IN_FLIGHT; i++) {
         _VK(vkAllocateDescriptorSets(qvk.device, &descriptor_set_alloc_info, rt_descriptor_set + i));
         ATTACH_LABEL_VARIABLE(rt_descriptor_set[i], DESCRIPTOR_SET);
     }
     cvar_pt_enable_particles = Cvar_Get("pt_enable_particles", "1", 0);
     cvar_pt_enable_beams = Cvar_Get("pt_enable_beams", "1", 0);
     cvar_pt_enable_sprites= Cvar_Get("pt_enable_sprites", "1", 0);
     return VK_SUCCESS;
 }
vkpt_pt_trace_lighting()
VkResult vkpt_pt_trace_lighting (VkCommandBuffer cmd_buf, float num_bounce_rays)
Definition at line 1105 of file path_tracer.c.
 {
     int frame_idx = qvk.frame_counter & 1;
     setup_rt_pipeline(cmd_buf);
     BEGIN_PERF_MARKER(cmd_buf, PROFILER_DIRECT_LIGHTING);
     for (int i = 0; i < qvk.device_count; i++)
     {
         set_current_gpu(cmd_buf, i);
         int idx = qvk.device_count == 1 ? -1 : i;
         vkCmdPushConstants(cmd_buf, rt_pipeline_layout, VK_SHADER_STAGE_RAYGEN_BIT_NV, 0, sizeof(int), &idx);
         int rgen_index = SBT_RGEN_DIRECT_LIGHTING;
         if (cvar_pt_caustics->value != 0)
             rgen_index = SBT_RGEN_DIRECT_LIGHTING_CAUSTICS;
         qvkCmdTraceRaysNV(cmd_buf,
             buf_shader_binding_table.buffer, rgen_index * rt_properties.shaderGroupHandleSize,
             buf_shader_binding_table.buffer, 0, rt_properties.shaderGroupHandleSize,
             buf_shader_binding_table.buffer, 0, rt_properties.shaderGroupHandleSize,
             VK_NULL_HANDLE, 0, 0,
             qvk.extent_render.width / 2, qvk.extent_render.height, qvk.device_count == 1 ? 2 : 1);
     }
     set_current_gpu(cmd_buf, ALL_GPUS);
     END_PERF_MARKER(cmd_buf, PROFILER_DIRECT_LIGHTING);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_COLOR_LF_SH]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_COLOR_LF_COCG]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_COLOR_HF]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_COLOR_SPEC]);
     BUFFER_BARRIER(cmd_buf,
         .srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT,
         .dstAccessMask = VK_ACCESS_TRANSFER_READ_BIT,
         .buffer = qvk.buf_readback.buffer,
         .offset = 0,
         .size = VK_WHOLE_SIZE,
     );
     BEGIN_PERF_MARKER(cmd_buf, PROFILER_INDIRECT_LIGHTING);
     if (num_bounce_rays > 0)
     {
         for (int i = 0; i < qvk.device_count; i++)
         {
             set_current_gpu(cmd_buf, i);
             int idx = qvk.device_count == 1 ? -1 : i;
             vkCmdPushConstants(cmd_buf, rt_pipeline_layout, VK_SHADER_STAGE_RAYGEN_BIT_NV, 0, sizeof(idx), &idx);
             for (int bounce_ray = 0; bounce_ray < (int)ceilf(num_bounce_rays); bounce_ray++)
             {
                 int height;
                 if (num_bounce_rays == 0.5f)
                     height = qvk.extent_render.height / 2;
                 else
                     height = qvk.extent_render.height;
                 int rgen_index = (bounce_ray == 0)
                     ? SBT_RGEN_INDIRECT_LIGHTING_FIRST
                     : SBT_RGEN_INDIRECT_LIGHTING_SECOND;
                 qvkCmdTraceRaysNV(cmd_buf,
                     buf_shader_binding_table.buffer, rgen_index * rt_properties.shaderGroupHandleSize,
                     buf_shader_binding_table.buffer, 0, rt_properties.shaderGroupHandleSize,
                     buf_shader_binding_table.buffer, 0, rt_properties.shaderGroupHandleSize,
                     VK_NULL_HANDLE, 0, 0,
                     qvk.extent_render.width / 2, height, qvk.device_count == 1 ? 2 : 1);
                 BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_COLOR_LF_SH]);
                 BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_COLOR_LF_COCG]);
                 BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_COLOR_HF]);
                 BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_COLOR_SPEC]);
                 BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_BOUNCE_THROUGHPUT]);
             }
         }
     }
     END_PERF_MARKER(cmd_buf, PROFILER_INDIRECT_LIGHTING);
     set_current_gpu(cmd_buf, ALL_GPUS);
     return VK_SUCCESS;
 }
Referenced by R_RenderFrame_RTX().
vkpt_pt_trace_primary_rays()
VkResult vkpt_pt_trace_primary_rays (VkCommandBuffer cmd_buf)
Definition at line 1009 of file path_tracer.c.
 {
     int frame_idx = qvk.frame_counter & 1;
     BUFFER_BARRIER(cmd_buf,
             .srcAccessMask = VK_ACCESS_TRANSFER_READ_BIT,
             .dstAccessMask = VK_ACCESS_SHADER_WRITE_BIT,
             .buffer = qvk.buf_readback.buffer,
             .offset = 0,
             .size = VK_WHOLE_SIZE,
     );
     setup_rt_pipeline(cmd_buf);
     BEGIN_PERF_MARKER(cmd_buf, PROFILER_PRIMARY_RAYS);
     for(int i = 0; i < qvk.device_count; i++)
     {
         set_current_gpu(cmd_buf, i);
         int idx = qvk.device_count == 1 ? -1 : i;
         vkCmdPushConstants(cmd_buf, rt_pipeline_layout, VK_SHADER_STAGE_RAYGEN_BIT_NV, 0, sizeof(int), &idx);
         qvkCmdTraceRaysNV(cmd_buf,
                 buf_shader_binding_table.buffer, SBT_RGEN_PRIMARY_RAYS * rt_properties.shaderGroupHandleSize,
                 buf_shader_binding_table.buffer, 0, rt_properties.shaderGroupHandleSize,
                 buf_shader_binding_table.buffer, 0, rt_properties.shaderGroupHandleSize,
                 VK_NULL_HANDLE, 0, 0,
                 qvk.extent_render.width / 2, qvk.extent_render.height, qvk.device_count == 1 ? 2 : 1);
     }
     set_current_gpu(cmd_buf, ALL_GPUS);
     END_PERF_MARKER(cmd_buf, PROFILER_PRIMARY_RAYS);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_VISBUF]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_TRANSPARENT]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_TEX_GRADIENTS]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_MOTION]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_SHADING_POSITION]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_VIEW_DIRECTION]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_THROUGHPUT]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_BOUNCE_THROUGHPUT]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_GODRAYS_THROUGHPUT_DIST]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_ALBEDO]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_METALLIC]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_CLUSTER]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_VIEW_DEPTH_A + frame_idx]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_NORMAL_A + frame_idx]);
     return VK_SUCCESS;
 }
Referenced by R_RenderFrame_RTX().
vkpt_pt_trace_reflections()
VkResult vkpt_pt_trace_reflections (VkCommandBuffer cmd_buf, int bounce)
Definition at line 1063 of file path_tracer.c.
 {
     int frame_idx = qvk.frame_counter & 1;
     setup_rt_pipeline(cmd_buf);
     for (int i = 0; i < qvk.device_count; i++)
     {
         set_current_gpu(cmd_buf, i);
         int idx = qvk.device_count == 1 ? -1 : i;
         vkCmdPushConstants(cmd_buf, rt_pipeline_layout, VK_SHADER_STAGE_RAYGEN_BIT_NV, 0, sizeof(int), &idx);
         vkCmdPushConstants(cmd_buf, rt_pipeline_layout, VK_SHADER_STAGE_RAYGEN_BIT_NV, sizeof(int), sizeof(int), &bounce);
         int shader = (bounce == 0) ? SBT_RGEN_REFLECT_REFRACT1 : SBT_RGEN_REFLECT_REFRACT2;
         qvkCmdTraceRaysNV(cmd_buf,
             buf_shader_binding_table.buffer, shader * rt_properties.shaderGroupHandleSize,
             buf_shader_binding_table.buffer, 0, rt_properties.shaderGroupHandleSize,
             buf_shader_binding_table.buffer, 0, rt_properties.shaderGroupHandleSize,
             VK_NULL_HANDLE, 0, 0,
             qvk.extent_render.width / 2, qvk.extent_render.height, qvk.device_count == 1 ? 2 : 1);
     }
     set_current_gpu(cmd_buf, ALL_GPUS);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_TRANSPARENT]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_MOTION]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_SHADING_POSITION]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_VIEW_DIRECTION]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_THROUGHPUT]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_GODRAYS_THROUGHPUT_DIST]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_ALBEDO]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_METALLIC]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_CLUSTER]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_VIEW_DEPTH_A + frame_idx]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_PT_NORMAL_A + frame_idx]);
     return VK_SUCCESS;
 }
Referenced by R_RenderFrame_RTX().
vkpt_pt_update_descripter_set_bindings()
VkResult vkpt_pt_update_descripter_set_bindings (int idx)
Definition at line 251 of file path_tracer.c.
 {
     /* update descriptor set bindings */
     VkWriteDescriptorSetAccelerationStructureNV desc_accel_struct_info = {
         .sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET_ACCELERATION_STRUCTURE_NV,
         .accelerationStructureCount = 1,
         .pAccelerationStructures    = accel_top + idx
     };
     VkBufferView particle_color_buffer_view = get_transparency_particle_color_buffer_view();
     VkBufferView beam_color_buffer_view = get_transparency_beam_color_buffer_view();
     VkBufferView sprite_info_buffer_view = get_transparency_sprite_info_buffer_view();
     VkWriteDescriptorSet writes[] = {
         {
             .sType           = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,
             .pNext           = &desc_accel_struct_info,
             .dstSet          = rt_descriptor_set[idx],
             .dstBinding      = RAY_GEN_ACCEL_STRUCTURE_BINDING_IDX,
             .descriptorCount = 1,
             .descriptorType  = VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_NV
         },
         {
             .sType           = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,
             .dstSet          = rt_descriptor_set[idx],
             .dstBinding      = RAY_GEN_PARTICLE_COLOR_BUFFER_BINDING_IDX,
             .descriptorCount = 1,
             .descriptorType  = VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER,
             .pTexelBufferView = &particle_color_buffer_view
         },
         {
             .sType           = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,
             .dstSet          = rt_descriptor_set[idx],
             .dstBinding      = RAY_GEN_BEAM_COLOR_BUFFER_BINDING_IDX,
             .descriptorCount = 1,
             .descriptorType  = VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER,
             .pTexelBufferView = &beam_color_buffer_view
         },
         {
             .sType           = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,
             .dstSet          = rt_descriptor_set[idx],
             .dstBinding      = RAY_GEN_SPRITE_INFO_BUFFER_BINDING_IDX,
             .descriptorCount = 1,
             .descriptorType  = VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER,
             .pTexelBufferView = &sprite_info_buffer_view
         },
     };
     vkUpdateDescriptorSets(qvk.device, LENGTH(writes), writes, 0, NULL);
     return VK_SUCCESS;
 }
Referenced by R_RenderFrame_RTX().
vkpt_readback()
VkResult vkpt_readback (struct ReadbackBuffer * dst)
Definition at line 659 of file vertex_buffer.c.
 {
     BufferResource_t* buffer = &qvk.buf_readback_staging[qvk.current_frame_index];
     void* mapped = buffer_map(buffer);
     if (mapped == NULL)
         return VK_ERROR_MEMORY_MAP_FAILED;
     memcpy(dst, mapped, sizeof(ReadbackBuffer));
     buffer_unmap(buffer);
     return VK_SUCCESS;
 }
Referenced by process_render_feedback().
vkpt_record_god_rays_filter_command_buffer()
void vkpt_record_god_rays_filter_command_buffer (VkCommandBuffer command_buffer)
Definition at line 169 of file god_rays.c.
 {
     BARRIER_COMPUTE(command_buffer, qvk.images[VKPT_IMG_PT_TRANSPARENT]);
     const VkImageSubresourceRange subresource_range = {
         .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
         .levelCount = 1,
         .layerCount = 1
     };
     vkCmdBindPipeline(command_buffer, VK_PIPELINE_BIND_POINT_COMPUTE, god_rays.pipelines[1]);
     VkDescriptorSet desc_sets[] = {
         god_rays.descriptor_set,
         qvk.desc_set_vertex_buffer,
         qvk.desc_set_ubo,
         qvk_get_current_desc_set_textures(),
     };
     vkCmdBindDescriptorSets(command_buffer, VK_PIPELINE_BIND_POINT_COMPUTE, god_rays.pipeline_layout, 0, LENGTH(desc_sets),
         desc_sets, 0, NULL);
     int pass = 0;
     vkCmdPushConstants(command_buffer, god_rays.pipeline_layout, VK_SHADER_STAGE_COMPUTE_BIT, 0, sizeof(int), &pass);
     uint32_t group_size = FILTER_THREAD_GROUP_SIZE;
     uint32_t group_num_x = (qvk.extent_render.width / qvk.device_count + (group_size - 1)) / group_size;
     uint32_t group_num_y = (qvk.extent_render.height + (group_size - 1)) / group_size;
     vkCmdDispatch(command_buffer, group_num_x, group_num_y, 1);
     BARRIER_COMPUTE(command_buffer, qvk.images[VKPT_IMG_PT_TRANSPARENT]);
 }
Referenced by R_RenderFrame_RTX().
vkpt_record_god_rays_trace_command_buffer()
void vkpt_record_god_rays_trace_command_buffer (VkCommandBuffer command_buffer, int pass)
Definition at line 140 of file god_rays.c.
 {
     BARRIER_COMPUTE(command_buffer, qvk.images[VKPT_IMG_PT_GODRAYS_THROUGHPUT_DIST]);
     BARRIER_COMPUTE(command_buffer, qvk.images[VKPT_IMG_ASVGF_COLOR]);
     vkCmdBindPipeline(command_buffer, VK_PIPELINE_BIND_POINT_COMPUTE, god_rays.pipelines[0]);
     VkDescriptorSet desc_sets[] = {
         god_rays.descriptor_set,
         qvk.desc_set_vertex_buffer,
         qvk.desc_set_ubo,
         qvk_get_current_desc_set_textures(),
     };
     vkCmdBindDescriptorSets(command_buffer, VK_PIPELINE_BIND_POINT_COMPUTE, god_rays.pipeline_layout, 0, LENGTH(desc_sets),
         desc_sets, 0, NULL);
     vkCmdPushConstants(command_buffer, god_rays.pipeline_layout, VK_SHADER_STAGE_COMPUTE_BIT, 0, sizeof(int), &pass);
     uint32_t group_size = THREAD_GROUP_SIZE;
     uint32_t group_num_x = (qvk.extent_render.width / (2 * qvk.device_count) + (group_size - 1)) / group_size;
     uint32_t group_num_y = (qvk.extent_render.height / 2 + (group_size - 1)) / group_size;
     vkCmdDispatch(command_buffer, group_num_x, group_num_y, 1);
     BARRIER_COMPUTE(command_buffer, qvk.images[VKPT_IMG_PT_GODRAYS_THROUGHPUT_DIST]);
     BARRIER_COMPUTE(command_buffer, qvk.images[VKPT_IMG_ASVGF_COLOR]);
 }
Referenced by R_RenderFrame_RTX().
vkpt_reset_accumulation()
void vkpt_reset_accumulation ()
Definition at line 219 of file main.c.
 {
     num_accumulated_frames = 0;
 }
Referenced by physical_sky_cvar_changed(), and vkpt_freecam_update().
vkpt_reset_command_buffers()
void vkpt_reset_command_buffers (cmd_buf_group_t * group)
Definition at line 3392 of file main.c.
 {
     group->used_this_frame = 0;
 #ifdef _DEBUG
     for (int i = 0; i < group->count_per_frame; i++)
     {
         void* addr = group->buffer_begin_addrs[group->count_per_frame * qvk.current_frame_index + i];
         assert(addr == 0);
     }
 #endif
 }
Referenced by R_BeginFrame_RTX(), and vkpt_wait_idle().
vkpt_shadow_map_create_pipelines()
VkResult vkpt_shadow_map_create_pipelines ()
Definition at line 209 of file shadow_map.c.
 {
     LOG_FUNC();
     VkPipelineShaderStageCreateInfo shader_info[] = {
         SHADER_STAGE(QVK_MOD_SHADOW_MAP_VERT, VK_SHADER_STAGE_VERTEX_BIT)
     };
     VkVertexInputBindingDescription vertex_binding_desc = {
         .binding = 0,
         .stride = sizeof(float) * 3,
         .inputRate = VK_VERTEX_INPUT_RATE_VERTEX
     };
     VkVertexInputAttributeDescription vertex_attribute_desc = {
         .location = 0,
         .binding = 0,
         .format = VK_FORMAT_R32G32B32_SFLOAT,
         .offset = 0
     };
     VkPipelineVertexInputStateCreateInfo vertex_input_info = {
         .sType                           = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO,
         .vertexBindingDescriptionCount   = 1,
         .pVertexBindingDescriptions      = &vertex_binding_desc,
         .vertexAttributeDescriptionCount = 1,
         .pVertexAttributeDescriptions    = &vertex_attribute_desc,
     };
     VkPipelineInputAssemblyStateCreateInfo input_assembly_info = {
         .sType    = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO,
         .topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST,
     };
     VkViewport viewport = {
         .x        = 0.0f,
         .y        = 0.0f,
         .width    = (float)SHADOWMAP_SIZE,
         .height   = (float)SHADOWMAP_SIZE,
         .minDepth = 0.0f,
         .maxDepth = 1.0f,
     };
     VkRect2D scissor = {
         .offset = { 0, 0 },
         .extent = { SHADOWMAP_SIZE, SHADOWMAP_SIZE }
     };
     VkPipelineViewportStateCreateInfo viewport_state = {
         .sType         = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO,
         .viewportCount = 1,
         .pViewports    = &viewport,
         .scissorCount  = 1,
         .pScissors     = &scissor,
     };
     VkPipelineRasterizationStateCreateInfo rasterizer_state = {
         .sType                   = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO,
         .polygonMode             = VK_POLYGON_MODE_FILL,
         .lineWidth               = 1.0f,
         .cullMode                = VK_CULL_MODE_FRONT_BIT,
         .frontFace               = VK_FRONT_FACE_CLOCKWISE,
     };
     VkPipelineMultisampleStateCreateInfo multisample_state = {
         .sType                 = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO,
         .sampleShadingEnable   = VK_FALSE,
         .rasterizationSamples  = VK_SAMPLE_COUNT_1_BIT,
         .minSampleShading      = 1.0f,
         .pSampleMask           = NULL,
         .alphaToCoverageEnable = VK_FALSE,
         .alphaToOneEnable      = VK_FALSE,
     };
     VkPipelineDepthStencilStateCreateInfo depth_stencil_state = {
         .sType = VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO,
         .depthTestEnable = VK_TRUE,
         .depthWriteEnable = VK_TRUE,
         .depthCompareOp = VK_COMPARE_OP_LESS,
     };
     VkDynamicState dynamic_states[] = {
         VK_DYNAMIC_STATE_VIEWPORT,
         VK_DYNAMIC_STATE_SCISSOR
     };
     VkPipelineDynamicStateCreateInfo dynamic_state_info = {
         .sType = VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO,
         .dynamicStateCount = LENGTH(dynamic_states),
         .pDynamicStates = dynamic_states
     };
     VkGraphicsPipelineCreateInfo pipeline_info = {
         .sType      = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO,
         .stageCount = LENGTH(shader_info),
         .pStages    = shader_info,
         .pVertexInputState   = &vertex_input_info,
         .pInputAssemblyState = &input_assembly_info,
         .pViewportState      = &viewport_state,
         .pRasterizationState = &rasterizer_state,
         .pMultisampleState   = &multisample_state,
         .pDepthStencilState  = &depth_stencil_state,
         .pColorBlendState    = NULL,
         .pDynamicState       = &dynamic_state_info,
         .layout              = pipeline_layout_smap,
         .renderPass          = render_pass_smap,
         .subpass             = 0,
         .basePipelineHandle  = VK_NULL_HANDLE,
         .basePipelineIndex   = -1,
     };
     _VK(vkCreateGraphicsPipelines(qvk.device, VK_NULL_HANDLE, 1, &pipeline_info, NULL, &pipeline_smap));
     ATTACH_LABEL_VARIABLE(pipeline_smap, PIPELINE);
     VkImageView attachments[] = {
         imv_smap_depth
     };
     VkFramebufferCreateInfo fb_create_info = {
         .sType           = VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO,
         .renderPass      = render_pass_smap,
         .attachmentCount = 1,
         .pAttachments    = attachments,
         .width           = SHADOWMAP_SIZE,
         .height          = SHADOWMAP_SIZE,
         .layers          = 1,
     };
     _VK(vkCreateFramebuffer(qvk.device, &fb_create_info, NULL, &framebuffer_smap));
     ATTACH_LABEL_VARIABLE(framebuffer_smap, FRAMEBUFFER);
     attachments[0] = imv_smap_depth2;
     _VK(vkCreateFramebuffer(qvk.device, &fb_create_info, NULL, &framebuffer_smap2));
     ATTACH_LABEL_VARIABLE(framebuffer_smap2, FRAMEBUFFER);
     return VK_SUCCESS;
 }
vkpt_shadow_map_destroy()
VkResult vkpt_shadow_map_destroy ()
Definition at line 182 of file shadow_map.c.
 {
     vkDestroyImageView(qvk.device, imv_smap_depth, NULL);
     imv_smap_depth = VK_NULL_HANDLE;
     vkDestroyImageView(qvk.device, imv_smap_depth2, NULL);
     imv_smap_depth2 = VK_NULL_HANDLE;
     vkDestroyImageView(qvk.device, imv_smap_depth_array, NULL);
     imv_smap_depth_array = VK_NULL_HANDLE;
     vkDestroyImage(qvk.device, img_smap, NULL);
     img_smap = VK_NULL_HANDLE;
     vkFreeMemory(qvk.device, mem_smap, NULL);
     mem_smap = VK_NULL_HANDLE;
     vkDestroyRenderPass(qvk.device, render_pass_smap, NULL);
     render_pass_smap = VK_NULL_HANDLE;
     vkDestroyPipelineLayout(qvk.device, pipeline_layout_smap, NULL);
     pipeline_layout_smap = VK_NULL_HANDLE;
     return VK_SUCCESS;
 }
vkpt_shadow_map_destroy_pipelines()
VkResult vkpt_shadow_map_destroy_pipelines ()
Definition at line 351 of file shadow_map.c.
 {
     LOG_FUNC();
     vkDestroyFramebuffer(qvk.device, framebuffer_smap, NULL);
     framebuffer_smap = VK_NULL_HANDLE;
     vkDestroyFramebuffer(qvk.device, framebuffer_smap2, NULL);
     framebuffer_smap2 = VK_NULL_HANDLE;
     vkDestroyPipeline(qvk.device, pipeline_smap, NULL);
     pipeline_smap = VK_NULL_HANDLE;
     return VK_SUCCESS;
 }
vkpt_shadow_map_get_view()
VkImageView vkpt_shadow_map_get_view ()
Definition at line 203 of file shadow_map.c.
 {
     return imv_smap_depth_array;
 }
Referenced by create_image_views().
vkpt_shadow_map_initialize()
VkResult vkpt_shadow_map_initialize ()
Definition at line 87 of file shadow_map.c.
 {
     create_render_pass();
     VkPushConstantRange push_constant_range = {
         .stageFlags = VK_SHADER_STAGE_VERTEX_BIT,
         .offset = 0,
         .size = sizeof(float) * 16,
     };
     CREATE_PIPELINE_LAYOUT(qvk.device, &pipeline_layout_smap,
         .pushConstantRangeCount = 1,
         .pPushConstantRanges = &push_constant_range,
     );
     VkImageCreateInfo img_info = {
         .sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO,
         .extent = {
             .width = SHADOWMAP_SIZE,
             .height = SHADOWMAP_SIZE,
             .depth = 1,
         },
         .imageType = VK_IMAGE_TYPE_2D,
         .format = VK_FORMAT_D32_SFLOAT,
         .mipLevels = 1,
         .arrayLayers = 2,
         .samples = VK_SAMPLE_COUNT_1_BIT,
         .tiling = VK_IMAGE_TILING_OPTIMAL,
         .usage = VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT
                | VK_IMAGE_USAGE_SAMPLED_BIT,
         .sharingMode = VK_SHARING_MODE_EXCLUSIVE,
         .queueFamilyIndexCount = qvk.queue_idx_graphics,
         .initialLayout = VK_IMAGE_LAYOUT_UNDEFINED,
     };
     _VK(vkCreateImage(qvk.device, &img_info, NULL, &img_smap));
     ATTACH_LABEL_VARIABLE(img_smap, IMAGE);
     VkMemoryRequirements mem_req;
     vkGetImageMemoryRequirements(qvk.device, img_smap, &mem_req);
     _VK(allocate_gpu_memory(mem_req, &mem_smap));
     _VK(vkBindImageMemory(qvk.device, img_smap, mem_smap, 0));
     VkImageViewCreateInfo img_view_info = {
         .sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO,
         .viewType = VK_IMAGE_VIEW_TYPE_2D,
         .format = VK_FORMAT_D32_SFLOAT,
         .image = img_smap,
         .subresourceRange = {
             .aspectMask = VK_IMAGE_ASPECT_DEPTH_BIT,
             .baseMipLevel = 0,
             .levelCount = 1,
             .baseArrayLayer = 0,
             .layerCount = 1,
         },
         .components = {
             VK_COMPONENT_SWIZZLE_R,
             VK_COMPONENT_SWIZZLE_G,
             VK_COMPONENT_SWIZZLE_B,
             VK_COMPONENT_SWIZZLE_A,
         },
     };
     _VK(vkCreateImageView(qvk.device, &img_view_info, NULL, &imv_smap_depth));
     ATTACH_LABEL_VARIABLE(imv_smap_depth, IMAGE_VIEW);
     img_view_info.subresourceRange.baseArrayLayer = 1;
     _VK(vkCreateImageView(qvk.device, &img_view_info, NULL, &imv_smap_depth2));
     ATTACH_LABEL_VARIABLE(imv_smap_depth2, IMAGE_VIEW);
     img_view_info.viewType = VK_IMAGE_VIEW_TYPE_2D_ARRAY;
     img_view_info.subresourceRange.baseArrayLayer = 0;
     img_view_info.subresourceRange.layerCount = 2;
     _VK(vkCreateImageView(qvk.device, &img_view_info, NULL, &imv_smap_depth_array));
     ATTACH_LABEL_VARIABLE(imv_smap_depth_array, IMAGE_VIEW);
     VkCommandBuffer cmd_buf = vkpt_begin_command_buffer(&qvk.cmd_buffers_graphics);
     IMAGE_BARRIER(cmd_buf,
         .image = img_smap,
         .subresourceRange = { .aspectMask = VK_IMAGE_ASPECT_DEPTH_BIT,.levelCount = 1,.layerCount = 2 },
         .srcAccessMask = VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT | VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT,
         .dstAccessMask = VK_ACCESS_SHADER_READ_BIT,
         .oldLayout = VK_IMAGE_LAYOUT_UNDEFINED,
         .newLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
     );
     vkpt_submit_command_buffer_simple(cmd_buf, qvk.queue_graphics, qtrue);
     return VK_SUCCESS;
 }
vkpt_shadow_map_render()
VkResult vkpt_shadow_map_render (VkCommandBuffer cmd_buf, float * view_projection_matrix, int num_static_verts, int num_dynamic_verts, int transparent_offset, int num_transparent_verts)
Definition at line 364 of file shadow_map.c.
 {
     IMAGE_BARRIER(cmd_buf,
         .image = img_smap,
         .subresourceRange = { .aspectMask = VK_IMAGE_ASPECT_DEPTH_BIT, .levelCount = 1, .layerCount = 2 },
         .srcAccessMask = VK_ACCESS_SHADER_READ_BIT,
         .dstAccessMask = VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT | VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT,
         .oldLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
         .newLayout = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL,
     );
     VkClearValue clear_depth = { .depthStencil = { .depth = 1.f } };
     VkRenderPassBeginInfo render_pass_info = {
         .sType             = VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO,
         .renderPass        = render_pass_smap,
         .framebuffer       = framebuffer_smap,
         .renderArea.offset = { 0, 0 },
         .renderArea.extent = { SHADOWMAP_SIZE, SHADOWMAP_SIZE },
         .clearValueCount   = 1,
         .pClearValues      = &clear_depth
     };
     vkCmdBeginRenderPass(cmd_buf, &render_pass_info, VK_SUBPASS_CONTENTS_INLINE);
     vkCmdBindPipeline(cmd_buf, VK_PIPELINE_BIND_POINT_GRAPHICS, pipeline_smap);
     VkViewport viewport =
     {
         .width = (float)SHADOWMAP_SIZE,
         .height = (float)SHADOWMAP_SIZE,
         .minDepth = 0,
         .maxDepth = 1.0f,
     };
     vkCmdSetViewport(cmd_buf, 0, 1, &viewport);
     VkRect2D scissor =
     {
         .extent.width = SHADOWMAP_SIZE,
         .extent.height = SHADOWMAP_SIZE,
         .offset.x = 0,
         .offset.y = 0,
     };
     vkCmdSetScissor(cmd_buf, 0, 1, &scissor);
     vkCmdPushConstants(cmd_buf, pipeline_layout_smap, VK_SHADER_STAGE_VERTEX_BIT, 0, sizeof(float) * 16, view_projection_matrix);
     VkDeviceSize vertex_offset = offsetof(struct VertexBuffer, positions_bsp);
     vkCmdBindVertexBuffers(cmd_buf, 0, 1, &qvk.buf_vertex.buffer, &vertex_offset);
     vkCmdDraw(cmd_buf, num_static_verts, 1, 0, 0);
     vertex_offset = offsetof(struct VertexBuffer, positions_instanced);
     vkCmdBindVertexBuffers(cmd_buf, 0, 1, &qvk.buf_vertex.buffer, &vertex_offset);
     vkCmdDraw(cmd_buf, num_dynamic_verts, 1, 0, 0);
     vkCmdEndRenderPass(cmd_buf);
     render_pass_info.framebuffer = framebuffer_smap2;
     vkCmdBeginRenderPass(cmd_buf, &render_pass_info, VK_SUBPASS_CONTENTS_INLINE);
     vertex_offset = offsetof(struct VertexBuffer, positions_bsp);
     vkCmdBindVertexBuffers(cmd_buf, 0, 1, &qvk.buf_vertex.buffer, &vertex_offset);
     vkCmdDraw(cmd_buf, num_transparent_verts, 1, transparent_offset, 0);
     vkCmdEndRenderPass(cmd_buf);
     IMAGE_BARRIER(cmd_buf,
         .image = img_smap,
         .subresourceRange = { .aspectMask = VK_IMAGE_ASPECT_DEPTH_BIT,.levelCount = 1,.layerCount = 2 },
         .srcAccessMask = VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT | VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT,
         .dstAccessMask = VK_ACCESS_SHADER_READ_BIT,
         .oldLayout = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL,
         .newLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
         );
     return VK_SUCCESS;
 }
Referenced by R_RenderFrame_RTX().
vkpt_shadow_map_setup()
void vkpt_shadow_map_setup (const sun_light_t * light, const float * bbox_min, const float * bbox_max, float * VP, float * depth_scale, qboolean random_sampling)
Definition at line 460 of file shadow_map.c.
 {
     vec3_t up_dir = { 0.0f, 0.0f, 1.0f };
     if (light->direction[2] >= 0.99f)
         VectorSet(up_dir, 1.f, 0.f, 0.f);
     vec3_t look_dir;
     VectorScale(light->direction, -1.f, look_dir);
     VectorNormalize(look_dir);
     vec3_t left_dir;
     CrossProduct(up_dir, look_dir, left_dir);
     VectorNormalize(left_dir);
     CrossProduct(look_dir, left_dir, up_dir);
     VectorNormalize(up_dir);
     if (random_sampling)
     {
         float u, v;
         sample_disk(&u, &v);
         VectorMA(look_dir, u * light->angular_size_rad * 0.5f, left_dir, look_dir);
         VectorMA(look_dir, v * light->angular_size_rad * 0.5f, up_dir, look_dir);
         VectorNormalize(look_dir);
         CrossProduct(up_dir, look_dir, left_dir);
         VectorNormalize(left_dir);
         CrossProduct(look_dir, left_dir, up_dir);
         VectorNormalize(up_dir);
     }
     float view_matrix[16] = {
         left_dir[0], up_dir[0], look_dir[0], 0.f,
         left_dir[1], up_dir[1], look_dir[1], 0.f,
         left_dir[2], up_dir[2], look_dir[2], 0.f,
         0.f, 0.f, 0.f, 1.f
     };
     vec3_t view_aabb_min = { FLT_MAX, FLT_MAX, FLT_MAX };
     vec3_t view_aabb_max = { -FLT_MAX, -FLT_MAX, -FLT_MAX };
     for (int i = 0; i < 8; i++)
     {
         float corner[4];
         corner[0] = (i & 1) ? bbox_max[0] : bbox_min[0];
         corner[1] = (i & 2) ? bbox_max[1] : bbox_min[1];
         corner[2] = (i & 4) ? bbox_max[2] : bbox_min[2];
         corner[3] = 1.f;
         float view_corner[4];
         mult_matrix_vector(view_corner, view_matrix, corner);
         view_aabb_min[0] = min(view_aabb_min[0], view_corner[0]);
         view_aabb_min[1] = min(view_aabb_min[1], view_corner[1]);
         view_aabb_min[2] = min(view_aabb_min[2], view_corner[2]);
         view_aabb_max[0] = max(view_aabb_max[0], view_corner[0]);
         view_aabb_max[1] = max(view_aabb_max[1], view_corner[1]);
         view_aabb_max[2] = max(view_aabb_max[2], view_corner[2]);
     }
     vec3_t diagonal;
     VectorSubtract(view_aabb_max, view_aabb_min, diagonal);
     float maxXY = max(diagonal[0], diagonal[1]);
     vec3_t diff;
     diff[0] = (maxXY - diagonal[0]) * 0.5f;
     diff[1] = (maxXY - diagonal[1]) * 0.5f;
     diff[2] = 0.f;
     VectorSubtract(view_aabb_min, diff, view_aabb_min);
     VectorAdd(view_aabb_max, diff, view_aabb_max);
     float projection_matrix[16];
     create_orthographic_matrix(projection_matrix, view_aabb_min[0], view_aabb_max[0], view_aabb_min[1], view_aabb_max[1], view_aabb_min[2], view_aabb_max[2]);
     mult_matrix_matrix(VP, projection_matrix, view_matrix);
     *depth_scale = view_aabb_max[2] - view_aabb_min[2];
 }
Referenced by R_RenderFrame_RTX().
vkpt_submit_command_buffer()
void vkpt_submit_command_buffer (VkCommandBuffer cmd_buf, VkQueue queue, uint32_t execute_device_mask, int wait_semaphore_count, VkSemaphore * wait_semaphores, VkPipelineStageFlags * wait_stages, uint32_t * wait_device_indices, int signal_semaphore_count, VkSemaphore * signal_semaphores, uint32_t * signal_device_indices, VkFence fence)
Definition at line 3411 of file main.c.
 {
     _VK(vkEndCommandBuffer(cmd_buf));
     VkSubmitInfo submit_info = {
         .sType = VK_STRUCTURE_TYPE_SUBMIT_INFO,
         .waitSemaphoreCount = wait_semaphore_count,
         .pWaitSemaphores = wait_semaphores,
         .pWaitDstStageMask = wait_stages,
         .signalSemaphoreCount = signal_semaphore_count,
         .pSignalSemaphores = signal_semaphores,
         .commandBufferCount = 1,
         .pCommandBuffers = &cmd_buf,
     };
 #ifdef VKPT_DEVICE_GROUPS
     VkDeviceGroupSubmitInfoKHR device_group_submit_info = {
         .sType = VK_STRUCTURE_TYPE_DEVICE_GROUP_SUBMIT_INFO_KHR,
         .pNext = NULL,
         .waitSemaphoreCount = wait_semaphore_count,
         .pWaitSemaphoreDeviceIndices = wait_device_indices,
         .commandBufferCount = 1,
         .pCommandBufferDeviceMasks = &execute_device_mask,
         .signalSemaphoreCount = signal_semaphore_count,
         .pSignalSemaphoreDeviceIndices = signal_device_indices,
     };
     if (qvk.device_count > 1) {
         submit_info.pNext = &device_group_submit_info;
     }
 #endif
     _VK(vkQueueSubmit(queue, 1, &submit_info, fence));
 #ifdef _DEBUG
     cmd_buf_group_t* groups[] = { &qvk.cmd_buffers_graphics, &qvk.cmd_buffers_compute, &qvk.cmd_buffers_transfer };
     for (int ngroup = 0; ngroup < LENGTH(groups); ngroup++)
     {
         cmd_buf_group_t* group = groups[ngroup];
         for (int i = 0; i < MAX_FRAMES_IN_FLIGHT * group->count_per_frame; i++)
         {
             if (group->buffers[i] == cmd_buf)
             {
                 group->buffer_begin_addrs[i] = NULL;
                 return;
             }
         }
     }
 #endif
 }
Referenced by R_EndFrame_RTX(), R_RenderFrame_RTX(), vkpt_submit_command_buffer_simple(), and vkpt_vertex_buffer_upload_staging().
vkpt_submit_command_buffer_simple()
void vkpt_submit_command_buffer_simple (VkCommandBuffer cmd_buf, VkQueue queue, qboolean all_gpus)
Definition at line 3473 of file main.c.
 {
     vkpt_submit_command_buffer(cmd_buf, queue, all_gpus ? (1 << qvk.device_count) - 1 : 1, 0, NULL, NULL, NULL, 0, NULL, NULL, 0);
 }
Referenced by change_image_layouts(), create_invalid_texture(), create_swapchain(), fill_index_buffer(), FillVertexAndIndexBuffers(), IMG_ReadPixels_RTX(), load_blue_noise(), R_BeginFrame_RTX(), R_RenderFrame_RTX(), UploadImage(), vkpt_create_images(), vkpt_pt_create_static(), vkpt_shadow_map_initialize(), vkpt_textures_end_registration(), and vkpt_textures_upload_envmap().
vkpt_taa()
VkResult vkpt_taa (VkCommandBuffer cmd_buf)
Definition at line 555 of file asvgf.c.
 {
     VkDescriptorSet desc_sets[] = {
         qvk.desc_set_ubo,
         qvk_get_current_desc_set_textures(),
         qvk.desc_set_vertex_buffer
     };
     BEGIN_PERF_MARKER(cmd_buf, PROFILER_ASVGF_TAA);
     vkCmdBindPipeline(cmd_buf, VK_PIPELINE_BIND_POINT_COMPUTE, pipeline_asvgf[TAA]);
     vkCmdBindDescriptorSets(cmd_buf, VK_PIPELINE_BIND_POINT_COMPUTE,
         pipeline_layout_taa, 0, LENGTH(desc_sets), desc_sets, 0, 0);
     VkExtent2D dispatch_size = qvk.extent_render;
     if(dispatch_size.width < qvk.extent_screen_images.width)
         dispatch_size.width += 8;
     if (dispatch_size.height < qvk.extent_screen_images.height)
         dispatch_size.height += 8;
     vkCmdDispatch(cmd_buf,
             (dispatch_size.width + 15) / 16,
             (dispatch_size.height + 15) / 16,
             1);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_ASVGF_TAA_A]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_ASVGF_TAA_B]);
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_ASVGF_TAA_B]);
     END_PERF_MARKER(cmd_buf, PROFILER_ASVGF_TAA);
     return VK_SUCCESS;
 }
Referenced by R_RenderFrame_RTX().
vkpt_textures_destroy()
VkResult vkpt_textures_destroy ()
Definition at line 1045 of file textures.c.
 {
     destroy_tex_images();
     vkDestroyDescriptorSetLayout(qvk.device, qvk.desc_set_layout_textures, NULL);
     vkDestroyDescriptorPool(qvk.device, desc_pool_textures, NULL);
     vkFreeMemory      (qvk.device, mem_blue_noise,      NULL);
     vkDestroyImage    (qvk.device, img_blue_noise,      NULL);
     vkDestroyImageView(qvk.device, imv_blue_noise,      NULL);
     vkDestroySampler  (qvk.device, qvk.tex_sampler,         NULL);
     vkDestroySampler  (qvk.device, qvk.tex_sampler_nearest, NULL);
     vkDestroySampler  (qvk.device, qvk.tex_sampler_linear_clamp, NULL);
     if(imv_envmap != VK_NULL_HANDLE) {
         vkDestroyImageView(qvk.device, imv_envmap, NULL);
         imv_envmap = NULL;
     }
     if(img_envmap != VK_NULL_HANDLE) {
         vkDestroyImage(qvk.device, img_envmap, NULL);
         img_envmap = NULL;
     }
     if (mem_envmap != VK_NULL_HANDLE) {
         vkFreeMemory(qvk.device, mem_envmap, NULL);
         mem_envmap = VK_NULL_HANDLE;
     }
     destroy_invalid_texture();
     destroy_device_memory_allocator(tex_device_memory_allocator);
     tex_device_memory_allocator = NULL;
     LOG_FUNC();
     return VK_SUCCESS;
 }
vkpt_textures_destroy_unused()
void vkpt_textures_destroy_unused ()
Definition at line 144 of file textures.c.
 {
     textures_destroy_unused_set((qvk.frame_counter) % DESTROY_LATENCY);
 }
Referenced by R_BeginFrame_RTX(), and R_Shutdown_RTX().
vkpt_textures_end_registration()
VkResult vkpt_textures_end_registration ()
Definition at line 1087 of file textures.c.
 {
     if(!image_loading_dirty_flag)
         return VK_SUCCESS;
     image_loading_dirty_flag = 0;
     VkImageCreateInfo img_info = {
         .sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO,
         .extent = {
             .width  = 1337,
             .height = 1337,
             .depth  = 1
         },
         .imageType             = VK_IMAGE_TYPE_2D,
         .format                = VK_FORMAT_UNDEFINED,
         .mipLevels             = 1,
         .arrayLayers           = 1,
         .samples               = VK_SAMPLE_COUNT_1_BIT,
         .tiling                = VK_IMAGE_TILING_OPTIMAL,
         .usage                 = VK_IMAGE_USAGE_TRANSFER_DST_BIT
                                | VK_IMAGE_USAGE_TRANSFER_SRC_BIT
                                | VK_IMAGE_USAGE_SAMPLED_BIT,
         .sharingMode           = VK_SHARING_MODE_EXCLUSIVE,
         .queueFamilyIndexCount = qvk.queue_idx_graphics,
         .initialLayout         = VK_IMAGE_LAYOUT_UNDEFINED,
     };
     VkImageViewCreateInfo img_view_info = {
         .sType      = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO,
         .viewType   = VK_IMAGE_VIEW_TYPE_2D,
         .format     = VK_FORMAT_UNDEFINED,
         .subresourceRange = {
             .aspectMask     = VK_IMAGE_ASPECT_COLOR_BIT,
             .baseMipLevel   = 0,
             .levelCount     = 1,
             .baseArrayLayer = 0,
             .layerCount     = 1
         },
         .components     = {
             VK_COMPONENT_SWIZZLE_R,
             VK_COMPONENT_SWIZZLE_G,
             VK_COMPONENT_SWIZZLE_B,
             VK_COMPONENT_SWIZZLE_A
         },
     };
 #ifdef VKPT_DEVICE_GROUPS
     if (qvk.device_count > 1) {
         mem_alloc_flags_broadcast.deviceMask = (1 << qvk.device_count) - 1;
     }
 #endif
     uint32_t new_image_num = 0;
     size_t   total_size = 0;
     for(int i = 0; i < MAX_RIMAGES; i++) {
         image_t *q_img = r_images + i;
         if (tex_images[i] != VK_NULL_HANDLE || !q_img->registration_sequence || q_img->pix_data == NULL)
             continue;
         img_info.extent.width = q_img->upload_width;
         img_info.extent.height = q_img->upload_height;
         img_info.mipLevels = get_num_miplevels(q_img->upload_width, q_img->upload_height);
         img_info.format = q_img->is_srgb ? VK_FORMAT_R8G8B8A8_SRGB : VK_FORMAT_R8G8B8A8_UNORM;
         _VK(vkCreateImage(qvk.device, &img_info, NULL, tex_images + i));
         ATTACH_LABEL_VARIABLE(tex_images[i], IMAGE);
         VkMemoryRequirements mem_req;
         vkGetImageMemoryRequirements(qvk.device, tex_images[i], &mem_req);
         assert(!(mem_req.alignment & (mem_req.alignment - 1)));
         total_size += mem_req.alignment - 1;
         total_size &= ~(mem_req.alignment - 1);
         total_size += mem_req.size;
         DeviceMemory* image_memory = tex_image_memory + i;
         image_memory->size = mem_req.size;
         image_memory->alignment = mem_req.alignment;
         image_memory->memory_type = get_memory_type(mem_req.memoryTypeBits, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
         allocate_device_memory(tex_device_memory_allocator, image_memory);
         VkBindImageMemoryInfo* bind_info = tex_bind_image_info + new_image_num;
         bind_info->sType = VK_STRUCTURE_TYPE_BIND_IMAGE_MEMORY_INFO;
         bind_info->image = tex_images[i];
         bind_info->memory = image_memory->memory;
         bind_info->memoryOffset = image_memory->memory_offset;
         new_image_num++;
     }
     if (new_image_num == 0)
         return VK_SUCCESS;
     vkBindImageMemory2(qvk.device, new_image_num, tex_bind_image_info);
     BufferResource_t buf_img_upload;
     buffer_create(&buf_img_upload, total_size, VK_BUFFER_USAGE_TRANSFER_SRC_BIT,
         VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
     VkCommandBuffer cmd_buf = vkpt_begin_command_buffer(&qvk.cmd_buffers_graphics);
     char *staging_buffer = buffer_map(&buf_img_upload);
     size_t offset = 0;
     for(int i = 0; i < MAX_RIMAGES; i++) {
         image_t *q_img = r_images + i;
         if (tex_images[i] == VK_NULL_HANDLE || tex_image_views[i] != VK_NULL_HANDLE)
             continue;
         int num_mip_levels = get_num_miplevels(q_img->upload_width, q_img->upload_height);
         VkMemoryRequirements mem_req;
         vkGetImageMemoryRequirements(qvk.device, tex_images[i], &mem_req);
         assert(!(mem_req.alignment & (mem_req.alignment - 1)));
         offset += mem_req.alignment - 1;
         offset &= ~(mem_req.alignment - 1);
         uint32_t wd = q_img->upload_width;
         uint32_t ht = q_img->upload_height;
         VkImageSubresourceRange subresource_range = {
             .aspectMask     = VK_IMAGE_ASPECT_COLOR_BIT,
             .baseMipLevel   = 0,
             .levelCount     = num_mip_levels,
             .baseArrayLayer = 0,
             .layerCount     = 1
         };
         IMAGE_BARRIER(cmd_buf,
                 .image            = tex_images[i],
                 .subresourceRange = subresource_range,
                 .srcAccessMask    = 0,
                 .dstAccessMask    = VK_ACCESS_TRANSFER_WRITE_BIT,
                 .oldLayout        = VK_IMAGE_LAYOUT_UNDEFINED,
                 .newLayout        = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL
         );
         {
             memcpy(staging_buffer + offset, q_img->pix_data, wd * ht * 4);
             VkBufferImageCopy cpy_info = {
                 .bufferOffset = offset,
                 .imageSubresource = {
                     .aspectMask     = VK_IMAGE_ASPECT_COLOR_BIT,
                     .mipLevel       = 0,
                     .baseArrayLayer = 0,
                     .layerCount     = 1,
                 },
                 .imageOffset    = { 0, 0, 0 },
                 .imageExtent    = { wd, ht, 1 }
             };
             vkCmdCopyBufferToImage(cmd_buf, buf_img_upload.buffer, tex_images[i],
                 VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &cpy_info);
         }
         subresource_range.levelCount = 1;
         for (int mip = 1; mip < num_mip_levels; mip++)
         {
             subresource_range.baseMipLevel = mip - 1;
             IMAGE_BARRIER(cmd_buf,
                 .image = tex_images[i],
                 .subresourceRange = subresource_range,
                 .srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT,
                 .dstAccessMask = VK_ACCESS_TRANSFER_READ_BIT,
                 .oldLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
                 .newLayout = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
                 );
             int nwd = (wd > 1) ? (wd >> 1) : wd;
             int nht = (ht > 1) ? (ht >> 1) : ht;
             VkImageBlit region = {
                 .srcSubresource = {
                     .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                     .mipLevel = mip - 1,
                     .baseArrayLayer = 0,
                     .layerCount = 1
                 },
                 .srcOffsets = {
                     { 0, 0, 0 },
                     { wd, ht, 1 } },
                 .dstSubresource = {
                     .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                     .mipLevel = mip,
                     .baseArrayLayer = 0,
                     .layerCount = 1
                 },
                 .dstOffsets = {
                     { 0, 0, 0 },
                     { nwd, nht, 1 } }
             };
             vkCmdBlitImage(
                 cmd_buf,
                 tex_images[i], VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
                 tex_images[i], VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
                 1, &region,
                 VK_FILTER_LINEAR);
             subresource_range.baseMipLevel = mip - 1;
             IMAGE_BARRIER(cmd_buf,
                 .image = tex_images[i],
                 .subresourceRange = subresource_range,
                 .srcAccessMask = VK_ACCESS_TRANSFER_READ_BIT,
                 .dstAccessMask = VK_ACCESS_SHADER_READ_BIT,
                 .oldLayout = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
                 .newLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
                 );
             wd = nwd;
             ht = nht;
         }
         subresource_range.baseMipLevel = num_mip_levels - 1;
         IMAGE_BARRIER(cmd_buf,
             .image = tex_images[i],
             .subresourceRange = subresource_range,
             .srcAccessMask = VK_ACCESS_TRANSFER_READ_BIT,
             .dstAccessMask = VK_ACCESS_SHADER_READ_BIT,
             .oldLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
             .newLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
             );
         img_view_info.image = tex_images[i];
         img_view_info.subresourceRange.levelCount = num_mip_levels;
         img_view_info.format = q_img->is_srgb ? VK_FORMAT_R8G8B8A8_SRGB : VK_FORMAT_R8G8B8A8_UNORM;
         _VK(vkCreateImageView(qvk.device, &img_view_info, NULL, tex_image_views + i));
         ATTACH_LABEL_VARIABLE(tex_image_views[i], IMAGE_VIEW);
         offset += mem_req.size;
     }
     buffer_unmap(&buf_img_upload);
     staging_buffer = NULL;
     vkpt_submit_command_buffer_simple(cmd_buf, qvk.queue_graphics, qtrue);
     const uint32_t destroy_frame_index = (qvk.frame_counter + MAX_FRAMES_IN_FLIGHT) % DESTROY_LATENCY;
     UnusedResources* unused_resources = texture_system.unused_resources + destroy_frame_index;
     const uint32_t unused_index = unused_resources->buffer_num++;
     unused_resources->buffers[unused_index] = buf_img_upload.buffer;
     unused_resources->buffer_memory[unused_index] = buf_img_upload.memory;
     memset(descriptor_set_dirty_flags, 0xff, sizeof(descriptor_set_dirty_flags));
     return VK_SUCCESS;
 }
Referenced by R_BeginFrame_RTX().
vkpt_textures_initialize()
VkResult vkpt_textures_initialize ()
Definition at line 821 of file textures.c.
 {
     memset(descriptor_set_dirty_flags, 0xff, sizeof(descriptor_set_dirty_flags));
     memset(&texture_system, 0, sizeof(texture_system));
     tex_device_memory_allocator = create_device_memory_allocator(qvk.device);
     create_invalid_texture();
     VkSamplerCreateInfo sampler_info = {
         .sType                   = VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO,
         .magFilter               = VK_FILTER_LINEAR,
         .minFilter               = VK_FILTER_LINEAR,
         .addressModeU            = VK_SAMPLER_ADDRESS_MODE_REPEAT,
         .addressModeV            = VK_SAMPLER_ADDRESS_MODE_REPEAT,
         .addressModeW            = VK_SAMPLER_ADDRESS_MODE_REPEAT,
         .anisotropyEnable        = VK_TRUE,
         .maxAnisotropy           = 16,
         .borderColor             = VK_BORDER_COLOR_INT_OPAQUE_BLACK,
         .unnormalizedCoordinates = VK_FALSE,
         .mipmapMode              = VK_SAMPLER_MIPMAP_MODE_LINEAR,
         .minLod                  = 0.0f,
         .maxLod                  = 128.0f,
     };
     _VK(vkCreateSampler(qvk.device, &sampler_info, NULL, &qvk.tex_sampler));
     ATTACH_LABEL_VARIABLE(qvk.tex_sampler, SAMPLER);
     VkSamplerCreateInfo sampler_nearest_info = {
         .sType                   = VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO,
         .magFilter               = VK_FILTER_NEAREST,
         .minFilter               = VK_FILTER_NEAREST,
         .addressModeU            = VK_SAMPLER_ADDRESS_MODE_REPEAT,
         .addressModeV            = VK_SAMPLER_ADDRESS_MODE_REPEAT,
         .addressModeW            = VK_SAMPLER_ADDRESS_MODE_REPEAT,
         .anisotropyEnable        = VK_FALSE,
         .maxAnisotropy           = 16,
         .borderColor             = VK_BORDER_COLOR_INT_OPAQUE_BLACK,
         .unnormalizedCoordinates = VK_FALSE,
         .mipmapMode              = VK_SAMPLER_MIPMAP_MODE_NEAREST,
     };
     _VK(vkCreateSampler(qvk.device, &sampler_nearest_info, NULL, &qvk.tex_sampler_nearest));
     ATTACH_LABEL_VARIABLE(qvk.tex_sampler_nearest, SAMPLER);
     VkSamplerCreateInfo sampler_linear_clamp_info = {
         .sType                   = VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO,
         .magFilter               = VK_FILTER_LINEAR,
         .minFilter               = VK_FILTER_LINEAR,
         .addressModeU            = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE,
         .addressModeV            = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE,
         .addressModeW            = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE,
         .anisotropyEnable        = VK_FALSE,
         .maxAnisotropy           = 16,
         .borderColor             = VK_BORDER_COLOR_INT_OPAQUE_BLACK,
         .unnormalizedCoordinates = VK_FALSE,
         .mipmapMode              = VK_SAMPLER_MIPMAP_MODE_LINEAR,
     };
     _VK(vkCreateSampler(qvk.device, &sampler_linear_clamp_info, NULL, &qvk.tex_sampler_linear_clamp));
     ATTACH_LABEL_VARIABLE(qvk.tex_sampler_linear_clamp, SAMPLER);
     VkDescriptorSetLayoutBinding layout_bindings[] = {
         {
             .descriptorType  = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
             .descriptorCount = MAX_RIMAGES,
             .binding         = 0,
             .stageFlags      = VK_SHADER_STAGE_ALL,
         },
 #define IMG_DO(_name, _binding, ...) \
         { \
             .descriptorType  = VK_DESCRIPTOR_TYPE_STORAGE_IMAGE, \
             .descriptorCount = 1, \
             .binding         = BINDING_OFFSET_IMAGES + _binding, \
             .stageFlags      = VK_SHADER_STAGE_ALL, \
         },
     LIST_IMAGES
     LIST_IMAGES_A_B
 #undef IMG_DO
 #define IMG_DO(_name, _binding, ...) \
         { \
             .descriptorType  = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, \
             .descriptorCount = 1, \
             .binding         = BINDING_OFFSET_TEXTURES + _binding, \
             .stageFlags      = VK_SHADER_STAGE_ALL, \
         },
     LIST_IMAGES
     LIST_IMAGES_A_B
 #undef IMG_DO
         {
             .descriptorType  = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
             .descriptorCount = 1,
             .binding         = BINDING_OFFSET_BLUE_NOISE,
             .stageFlags      = VK_SHADER_STAGE_ALL,
         },
         {
             .descriptorType  = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
             .descriptorCount = 1,
             .binding         = BINDING_OFFSET_ENVMAP,
             .stageFlags      = VK_SHADER_STAGE_ALL,
         },
         {
             .descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
             .descriptorCount = 1,
             .binding = BINDING_OFFSET_PHYSICAL_SKY,
             .stageFlags = VK_SHADER_STAGE_ALL,
         },
         {
             .descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_IMAGE,
             .descriptorCount = 1,
             .binding = BINDING_OFFSET_PHYSICAL_SKY_IMG,
             .stageFlags = VK_SHADER_STAGE_ALL,
         },
         {
             .descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
             .descriptorCount = 1,
             .binding = BINDING_OFFSET_SKY_TRANSMITTANCE,
             .stageFlags = VK_SHADER_STAGE_ALL,
         },
         {
             .descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
             .descriptorCount = 1,
             .binding = BINDING_OFFSET_SKY_SCATTERING,
             .stageFlags = VK_SHADER_STAGE_ALL,
         },
         {
             .descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
             .descriptorCount = 1,
             .binding = BINDING_OFFSET_SKY_IRRADIANCE,
             .stageFlags = VK_SHADER_STAGE_ALL,
         },
         {
             .descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
             .descriptorCount = 1,
             .binding = BINDING_OFFSET_SKY_CLOUDS,
             .stageFlags = VK_SHADER_STAGE_ALL,
         },
         {
             .descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
             .descriptorCount = 1,
             .binding = BINDING_OFFSET_TERRAIN_ALBEDO,
             .stageFlags = VK_SHADER_STAGE_ALL,
         },
         {
             .descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
             .descriptorCount = 1,
             .binding = BINDING_OFFSET_TERRAIN_NORMALS,
             .stageFlags = VK_SHADER_STAGE_ALL,
         },
         {
             .descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
             .descriptorCount = 1,
             .binding = BINDING_OFFSET_TERRAIN_DEPTH,
             .stageFlags = VK_SHADER_STAGE_ALL,
         },
         {
             .descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
             .descriptorCount = 1,
             .binding = BINDING_OFFSET_TERRAIN_SHADOWMAP,
             .stageFlags = VK_SHADER_STAGE_ALL,
         }
     };
     VkDescriptorSetLayoutCreateInfo layout_info = {
         .sType        = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO,
         .bindingCount = LENGTH(layout_bindings),
         .pBindings    = layout_bindings,
     };
     _VK(vkCreateDescriptorSetLayout(qvk.device, &layout_info, NULL, &qvk.desc_set_layout_textures));
     ATTACH_LABEL_VARIABLE(qvk.desc_set_layout_textures, DESCRIPTOR_SET_LAYOUT);
     VkDescriptorPoolSize pool_size = {
         .type            = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
         .descriptorCount = MAX_RIMAGES + 2 * NUM_VKPT_IMAGES + 128,
     };
     VkDescriptorPoolCreateInfo pool_info = {
         .sType         = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO,
         .poolSizeCount = 1,
         .pPoolSizes    = &pool_size,
         .maxSets       = 2,
     };
     _VK(vkCreateDescriptorPool(qvk.device, &pool_info, NULL, &desc_pool_textures));
     ATTACH_LABEL_VARIABLE(desc_pool_textures, DESCRIPTOR_POOL);
     VkDescriptorSetAllocateInfo descriptor_set_alloc_info = {
         .sType              = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO,
         .descriptorPool     = desc_pool_textures,
         .descriptorSetCount = 1,
         .pSetLayouts        = &qvk.desc_set_layout_textures,
     };
     _VK(vkAllocateDescriptorSets(qvk.device, &descriptor_set_alloc_info, &qvk.desc_set_textures_even));
     _VK(vkAllocateDescriptorSets(qvk.device, &descriptor_set_alloc_info, &qvk.desc_set_textures_odd));
     ATTACH_LABEL_VARIABLE(qvk.desc_set_textures_even, DESCRIPTOR_SET);
     ATTACH_LABEL_VARIABLE(qvk.desc_set_textures_odd, DESCRIPTOR_SET);
     if(load_blue_noise() != VK_SUCCESS)
         return VK_ERROR_INITIALIZATION_FAILED;
     LOG_FUNC();
     return VK_SUCCESS;
 }
vkpt_textures_prefetch()
void vkpt_textures_prefetch ()
Definition at line 75 of file textures.c.
 {
     byte* buffer = NULL;
     ssize_t buffer_size = 0;
     char const * filename = "prefetch.txt";
     buffer_size = FS_LoadFile(filename, (void**)&buffer);
     if (buffer == NULL)
     {
         Com_EPrintf("Can't load '%s'\n", filename);
         return;
     }
     char const * ptr = buffer;
     char linebuf[MAX_QPATH];
     while (sgets(linebuf, sizeof(linebuf), &ptr))
     {
         char* line = strtok(linebuf, " \t\r\n");
         if (!line)
             continue;
         image_t const * img1 = IMG_Find(line, IT_SKIN, IF_PERMANENT | IF_SRGB);
         char other_name[MAX_QPATH];
         // attempt loading a matching normal map
         if (!Q_strlcpy(other_name, line, strlen(line) - 3))
             continue;
         Q_concat(other_name, sizeof(other_name), other_name, "_n.tga", NULL);
         FS_NormalizePath(other_name, other_name);
         image_t const * img2 = IMG_Find(other_name, IT_SKIN, IF_PERMANENT);
         /* if (img2 != R_NOTEXTURE)
             Com_Printf("Prefetched '%s' (%d)\n", other_name, (int)(img2 - r_images)); */
         // attempt loading a matching emissive map
         if (!Q_strlcpy(other_name, line, strlen(line) - 3))
             continue;
         Q_concat(other_name, sizeof(other_name), other_name, "_light.tga", NULL);
         FS_NormalizePath(other_name, other_name);
         image_t const * img3 = IMG_Find(other_name, IT_SKIN, IF_PERMANENT | IF_SRGB);
     }
     // Com_Printf("Loaded '%s'\n", filename);
     FS_FreeFile(buffer);
 }
Referenced by vkpt_initialize_all().
vkpt_textures_update_descriptor_set()
void vkpt_textures_update_descriptor_set ()
Definition at line 1346 of file textures.c.
 {
     if (!descriptor_set_dirty_flags[qvk.current_frame_index])
         return;
     descriptor_set_dirty_flags[qvk.current_frame_index] = 0;
     for(int i = 0; i < MAX_RIMAGES; i++) {
         image_t *q_img = r_images + i;
         VkImageView image_view = tex_image_views[i];
         if (image_view == VK_NULL_HANDLE)
             image_view = tex_invalid_texture_image_view;
         VkSampler sampler = qvk.tex_sampler;
         if (!strcmp(q_img->name, "pics/conchars.pcx") || !strcmp(q_img->name, "pics/ch1.pcx"))
             sampler = qvk.tex_sampler_nearest;
         else if (q_img->type == IT_SPRITE)
             sampler = qvk.tex_sampler_linear_clamp;
         VkDescriptorImageInfo img_info = {
             .imageLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
             .imageView   = image_view,
             .sampler     = sampler,
         };
         if (i >= VKPT_IMG_BLOOM_HBLUR &&
             i <= VKPT_IMG_BLOOM_VBLUR) {
             img_info.sampler = qvk.tex_sampler_linear_clamp;
         }
         VkWriteDescriptorSet descriptor_set_write = {
             .sType           = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,
             .dstSet          = qvk_get_current_desc_set_textures(),
             .dstBinding      = GLOBAL_TEXTURES_TEX_ARR_BINDING_IDX,
             .dstArrayElement = i,
             .descriptorType  = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
             .descriptorCount = 1,
             .pImageInfo      = &img_info,
         };
         vkUpdateDescriptorSets(qvk.device, 1, &descriptor_set_write, 0, NULL);
     }
 }
Referenced by R_BeginFrame_RTX().
vkpt_textures_upload_envmap()
VkResult vkpt_textures_upload_envmap (int w, int h, byte * data)
Definition at line 150 of file textures.c.
 {
     vkDeviceWaitIdle(qvk.device);
     if(imv_envmap != VK_NULL_HANDLE) {
         vkDestroyImageView(qvk.device, imv_envmap, NULL);
         imv_envmap = NULL;
     }
     if(img_envmap != VK_NULL_HANDLE) {
         vkDestroyImage(qvk.device, img_envmap, NULL);
         img_envmap = NULL;
     }
     const int num_images = 6;
     size_t img_size = w * h * 4;
     BufferResource_t buf_img_upload;
     buffer_create(&buf_img_upload, img_size * num_images, VK_BUFFER_USAGE_TRANSFER_SRC_BIT,
         VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
     byte *envmap = (byte *) buffer_map(&buf_img_upload);
     memcpy(envmap, data, img_size * num_images);
     buffer_unmap(&buf_img_upload);
     envmap = NULL;
     VkImageCreateInfo img_info = {
         .sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO,
         .extent = {
             .width  = w,
             .height = h,
             .depth  = 1,
         },
         .imageType             = VK_IMAGE_TYPE_2D,
         .format                = VK_FORMAT_R8G8B8A8_UNORM,
         .mipLevels             = 1,
         .arrayLayers           = num_images,
         .samples               = VK_SAMPLE_COUNT_1_BIT,
         .tiling                = VK_IMAGE_TILING_OPTIMAL,
         .usage                 = VK_IMAGE_USAGE_STORAGE_BIT
                                | VK_IMAGE_USAGE_TRANSFER_DST_BIT
                                | VK_IMAGE_USAGE_SAMPLED_BIT,
         .flags                 = VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT,
         .sharingMode           = VK_SHARING_MODE_EXCLUSIVE,
         .queueFamilyIndexCount = qvk.queue_idx_graphics,
         .initialLayout         = VK_IMAGE_LAYOUT_UNDEFINED,
     };
     _VK(vkCreateImage(qvk.device, &img_info, NULL, &img_envmap));
     ATTACH_LABEL_VARIABLE(img_envmap, IMAGE);
     VkMemoryRequirements mem_req;
     vkGetImageMemoryRequirements(qvk.device, img_envmap, &mem_req);
     assert(mem_req.size >= buf_img_upload.size);
     _VK(allocate_gpu_memory(mem_req, &mem_envmap));
     _VK(vkBindImageMemory(qvk.device, img_envmap, mem_envmap, 0));
     VkImageViewCreateInfo img_view_info = {
         .sType      = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO,
         .viewType   = VK_IMAGE_VIEW_TYPE_CUBE,
         .format     = VK_FORMAT_R8G8B8A8_UNORM,
         .image      = img_envmap,
         .subresourceRange = {
             .aspectMask     = VK_IMAGE_ASPECT_COLOR_BIT,
             .baseMipLevel   = 0,
             .levelCount     = 1,
             .baseArrayLayer = 0,
             .layerCount     = num_images,
         },
         .components     = {
             VK_COMPONENT_SWIZZLE_R,
             VK_COMPONENT_SWIZZLE_G,
             VK_COMPONENT_SWIZZLE_B,
             VK_COMPONENT_SWIZZLE_A,
         },
     };
     _VK(vkCreateImageView(qvk.device, &img_view_info, NULL, &imv_envmap));
     ATTACH_LABEL_VARIABLE(imv_envmap, IMAGE_VIEW);
     VkCommandBuffer cmd_buf = vkpt_begin_command_buffer(&qvk.cmd_buffers_graphics);
     for(int layer = 0; layer < num_images; layer++) {
         VkImageSubresourceRange subresource_range = {
             .aspectMask     = VK_IMAGE_ASPECT_COLOR_BIT,
             .baseMipLevel   = 0,
             .levelCount     = 1,
             .baseArrayLayer = layer,
             .layerCount     = 1,
         };
         IMAGE_BARRIER(cmd_buf,
                 .image            = img_envmap,
                 .subresourceRange = subresource_range,
                 .srcAccessMask    = 0,
                 .dstAccessMask    = VK_ACCESS_TRANSFER_WRITE_BIT,
                 .oldLayout        = VK_IMAGE_LAYOUT_UNDEFINED,
                 .newLayout        = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL
         );
         VkBufferImageCopy cpy_info = {
             .bufferOffset = img_size * layer,
             .imageSubresource = {
                 .aspectMask     = VK_IMAGE_ASPECT_COLOR_BIT,
                 .mipLevel       = 0,
                 .baseArrayLayer = layer,
                 .layerCount     = 1,
             },
             .imageOffset    = { 0, 0, 0 },
             .imageExtent    = { w, h, 1 }
         };
         vkCmdCopyBufferToImage(cmd_buf, buf_img_upload.buffer, img_envmap,
             VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &cpy_info);
         IMAGE_BARRIER(cmd_buf,
                 .image            = img_envmap,
                 .subresourceRange = subresource_range,
                 .srcAccessMask    = VK_ACCESS_TRANSFER_WRITE_BIT,
                 .dstAccessMask    = VK_ACCESS_SHADER_READ_BIT,
                 .oldLayout        = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
                 .newLayout        = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
         );
     }
     vkpt_submit_command_buffer_simple(cmd_buf, qvk.queue_graphics, qtrue);
     {
     VkDescriptorImageInfo desc_img_info = {
         .imageLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
         .imageView   = imv_envmap,
         .sampler     = qvk.tex_sampler,
     };
     VkWriteDescriptorSet s = {
         .sType           = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,
         .dstSet          = qvk.desc_set_textures_even,
         .dstBinding      = BINDING_OFFSET_ENVMAP,
         .dstArrayElement = 0,
         .descriptorType  = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
         .descriptorCount = 1,
         .pImageInfo      = &desc_img_info,
     };
     vkUpdateDescriptorSets(qvk.device, 1, &s, 0, NULL);
     s.dstSet = qvk.desc_set_textures_odd;
     vkUpdateDescriptorSets(qvk.device, 1, &s, 0, NULL);
     }
     vkQueueWaitIdle(qvk.queue_graphics);
     buffer_destroy(&buf_img_upload);
     return VK_SUCCESS;
 }
Referenced by R_SetSky_RTX().
vkpt_tone_mapping_create_pipelines()
VkResult vkpt_tone_mapping_create_pipelines ()
Definition at line 146 of file tone_mapping.c.
 {
     VkComputePipelineCreateInfo pipeline_info[TM_NUM_PIPELINES] = {
         [TONE_MAPPING_HISTOGRAM] = {
             .sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
             .stage = SHADER_STAGE(QVK_MOD_TONE_MAPPING_HISTOGRAM_COMP, VK_SHADER_STAGE_COMPUTE_BIT),
             .layout = pipeline_layout_tone_mapping_histogram,
         },
         [TONE_MAPPING_CURVE] = {
             .sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
             .stage = SHADER_STAGE(QVK_MOD_TONE_MAPPING_CURVE_COMP, VK_SHADER_STAGE_COMPUTE_BIT),
             .layout = pipeline_layout_tone_mapping_curve,
         },
         [TONE_MAPPING_APPLY] = {
             .sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
             .stage = SHADER_STAGE(QVK_MOD_TONE_MAPPING_APPLY_COMP, VK_SHADER_STAGE_COMPUTE_BIT),
             .layout = pipeline_layout_tone_mapping_apply,
         },
     };
     _VK(vkCreateComputePipelines(qvk.device, 0, LENGTH(pipeline_info), pipeline_info, 0, pipelines));
     reset_required = 1;
     return VK_SUCCESS;
 }
vkpt_tone_mapping_destroy()
VkResult vkpt_tone_mapping_destroy ()
Definition at line 126 of file tone_mapping.c.
 {
     vkDestroyPipelineLayout(qvk.device, pipeline_layout_tone_mapping_histogram, NULL);
     vkDestroyPipelineLayout(qvk.device, pipeline_layout_tone_mapping_curve, NULL);
     vkDestroyPipelineLayout(qvk.device, pipeline_layout_tone_mapping_apply, NULL);
     return VK_SUCCESS;
 }
vkpt_tone_mapping_destroy_pipelines()
VkResult vkpt_tone_mapping_destroy_pipelines ()
Definition at line 207 of file tone_mapping.c.
 {
     for (int i = 0; i < TM_NUM_PIPELINES; i++)
         vkDestroyPipeline(qvk.device, pipelines[i], NULL);
     return VK_SUCCESS;
 }
vkpt_tone_mapping_initialize()
VkResult vkpt_tone_mapping_initialize ()
Definition at line 76 of file tone_mapping.c.
 {
     VkDescriptorSetLayout desc_set_layouts[] = {
         qvk.desc_set_layout_ubo,
         qvk.desc_set_layout_textures,
         qvk.desc_set_layout_vertex_buffer
     };
     VkPushConstantRange push_constant_range_curve = {
         .stageFlags = VK_SHADER_STAGE_COMPUTE_BIT,
         .offset = 0,
         .size = 16*sizeof(float)
     };
     VkPushConstantRange push_constant_range_apply = {
         .stageFlags = VK_SHADER_STAGE_COMPUTE_BIT,
         .offset = 0,
         .size = 3*sizeof(float)
     };
     CREATE_PIPELINE_LAYOUT(qvk.device, &pipeline_layout_tone_mapping_histogram,
         .setLayoutCount = LENGTH(desc_set_layouts),
         .pSetLayouts = desc_set_layouts,
         .pushConstantRangeCount = 0,
         .pPushConstantRanges = NULL
     );
     ATTACH_LABEL_VARIABLE(pipeline_layout_tone_mapping_histogram, PIPELINE_LAYOUT);
     CREATE_PIPELINE_LAYOUT(qvk.device, &pipeline_layout_tone_mapping_curve,
         .setLayoutCount = LENGTH(desc_set_layouts),
         .pSetLayouts = desc_set_layouts,
         .pushConstantRangeCount = 1,
         .pPushConstantRanges = &push_constant_range_curve
     );
     ATTACH_LABEL_VARIABLE(pipeline_layout_tone_mapping_curve, PIPELINE_LAYOUT);
     CREATE_PIPELINE_LAYOUT(qvk.device, &pipeline_layout_tone_mapping_apply,
         .setLayoutCount = LENGTH(desc_set_layouts),
         .pSetLayouts = desc_set_layouts,
         .pushConstantRangeCount = 1,
         .pPushConstantRanges = &push_constant_range_apply
     );
     ATTACH_LABEL_VARIABLE(pipeline_layout_tone_mapping_apply, PIPELINE_LAYOUT);
     return VK_SUCCESS;
 }
vkpt_tone_mapping_record_cmd_buffer()
VkResult vkpt_tone_mapping_record_cmd_buffer (VkCommandBuffer cmd_buf, float frame_time)
Definition at line 241 of file tone_mapping.c.
 {
     if (reset_required)
     {
         // Clear the histogram image.
         vkpt_tone_mapping_reset(cmd_buf);
     }
     VkDescriptorSet desc_sets[] = {
         qvk.desc_set_ubo,
         qvk_get_current_desc_set_textures(),
         qvk.desc_set_vertex_buffer
     };
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_TAA_OUTPUT]);
     // Record instructions to run the compute shader that updates the histogram.
     vkCmdBindPipeline(cmd_buf, VK_PIPELINE_BIND_POINT_COMPUTE, pipelines[TONE_MAPPING_HISTOGRAM]);
     vkCmdBindDescriptorSets(cmd_buf, VK_PIPELINE_BIND_POINT_COMPUTE,
         pipeline_layout_tone_mapping_histogram, 0, LENGTH(desc_sets), desc_sets, 0, 0);
     vkCmdDispatch(cmd_buf,
         (qvk.extent_render.width + 15) / 16,
         (qvk.extent_render.height + 15) / 16,
         1);
     BUFFER_BARRIER(cmd_buf,
         .buffer = qvk.buf_tonemap.buffer,
         .offset = 0,
         .size = VK_WHOLE_SIZE,
         .srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT,
         .dstAccessMask = VK_ACCESS_SHADER_READ_BIT
     );
     // Record instructions to run the compute shader that computes the tone
     // curve and autoexposure constants from the histogram.
     vkCmdBindPipeline(cmd_buf, VK_PIPELINE_BIND_POINT_COMPUTE, pipelines[TONE_MAPPING_CURVE]);
     vkCmdBindDescriptorSets(cmd_buf, VK_PIPELINE_BIND_POINT_COMPUTE,
         pipeline_layout_tone_mapping_curve, 0, LENGTH(desc_sets), desc_sets, 0, 0);
     // Compute the push constants for the tone curve generation shader:
     // whether to ignore previous tone curve results, how much to blend this
     // frame's tone curve with the previous frame's tone curve, and the kernel
     // used to filter the tone curve's slopes.
     // This is one of the things we added to Eilertsen's tone mapper, and helps
     // prevent artifacts that occur when the tone curve's slopes become flat or
     // change too suddenly (much like when you specify a curve in an image
     // processing application that is too intense). This especially helps on
     // shadow edges in some scenes.
     // In addition, we assume the kernel is symmetric; this allows us to only
     // specify half of it in our push constant buffer.
     // Note that the second argument of Cvar_Get only specifies the default
     // value in code if none is set; the value of tm_slope_blur_sigma specified
     // in global_ubo.h will override this.
     float slope_blur_sigma = Cvar_Get("tm_slope_blur_sigma", "6.0", 0)->value;
     float push_constants_tm2_curve[16] = {
          reset_required ? 1.0 : 0.0, // 1 means reset the histogram
          frame_time, // Frame time
          0.0, 0.0, 0.0, 0.0, // Slope kernel filter
          0.0, 0.0, 0.0, 0.0,
          0.0, 0.0, 0.0, 0.0,
          0.0, 0.0
     };
     // Compute Gaussian curve and sum, taking symmetry into account.
     float gaussian_sum = 0.0;
     for (int i = 0; i < 14; ++i)
     {
         float kernel_value = exp(-i * i / (2.0 * slope_blur_sigma * slope_blur_sigma));
         gaussian_sum += kernel_value * (i == 0 ? 1 : 2);
         push_constants_tm2_curve[i + 2] = kernel_value;
     }
     // Normalize the result (since even with an analytic normalization factor,
     // the results may not sum to one).
     for (int i = 0; i < 14; ++i) {
         push_constants_tm2_curve[i + 2] /= gaussian_sum;
     }
     vkCmdPushConstants(cmd_buf, pipeline_layout_tone_mapping_curve,
         VK_SHADER_STAGE_COMPUTE_BIT, 0, sizeof(push_constants_tm2_curve), push_constants_tm2_curve);
     vkCmdDispatch(cmd_buf, 1, 1, 1);
     BUFFER_BARRIER(cmd_buf,
         .buffer = qvk.buf_tonemap.buffer,
         .offset = 0,
         .size = VK_WHOLE_SIZE,
         .srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT,
         .dstAccessMask = VK_ACCESS_SHADER_READ_BIT
     );
     // Record instructions to apply our tone curve to the final image, apply
     // the autoexposure tone mapper to the final image, and blend the results
     // of the two techniques.
     vkCmdBindPipeline(cmd_buf, VK_PIPELINE_BIND_POINT_COMPUTE, pipelines[TONE_MAPPING_APPLY]);
     vkCmdBindDescriptorSets(cmd_buf, VK_PIPELINE_BIND_POINT_COMPUTE,
         pipeline_layout_tone_mapping_apply, 0, LENGTH(desc_sets), desc_sets, 0, 0);
     // At the end of the hue-preserving tone mapper, the luminance of every
     // pixel is mapped to the range [0,1]. However, because this tone
     // mapper adjusts luminance while preserving hue and saturation, the values
     // of some RGB channels may lie outside [0,1]. To finish off the tone
     // mapping pipeline and since we want the brightest colors in the scene to
     // be desaturated a bit for display, we apply a subtle user-configurable
     // Reinhard tone mapping curve to the brighest values in the image at this
     // point, preserving pixels with luminance below tm_knee_start.
     //
     // If we wanted to support an arbitrary SDR color grading pipeline here or
     // implement an additional filmic tone mapping pass, for instance, this is
     // roughly around where it would be applied. For applications that need to
     // output both SDR and HDR images but for which creating custom grades
     // for each format is impractical, one common approach is to
     // (roughly) use the HDR->SDR transformation to map an SDR color grading
     // function back to an HDR color grading function.
     // Defines the white point and where we switch from an identity transform
     // to a Reinhard transform in the additional tone mapper we apply at the
     // end of the previous tone mapping pipeline.
     // Must be between 0 and 1; pixels with luminances above this value have
     // their RGB values slowly clamped to 1, up to tm_white_point.
     float knee_start = Cvar_Get("tm_knee_start", "0.9", 0)->value;
     // Should be greater than 1; defines those RGB values that get mapped to 1.
     float knee_white_point = Cvar_Get("tm_white_point", "10.0", 0)->value;
     // We modify Reinhard to smoothly blend with the identity transform up to tm_knee_start.
     // We need to find w, a, and b such that in y(x) = (wx+a)/(x+b),
     // * y(knee_start) = tm_knee_start
     // * dy/dx(knee_start) = 1
     // * y(knee_white_point) = tm_white_point.
     // The solution is as follows:
     float knee_w = (knee_start*(knee_start - 2.0) + knee_white_point) / (knee_white_point - 1.0);
     float knee_a = -knee_start * knee_start;
     float knee_b = knee_w - 2.0*knee_start;
     float push_constants_tm2_apply[3] = {
         knee_w, // knee_w in piecewise knee adjustment
         knee_a, // knee_a in piecewise knee adjustment
         knee_b, // knee_b in piecewise knee adjustment
     };
     vkCmdPushConstants(cmd_buf, pipeline_layout_tone_mapping_apply,
         VK_SHADER_STAGE_COMPUTE_BIT, 0, sizeof(push_constants_tm2_apply), push_constants_tm2_apply);
     vkCmdDispatch(cmd_buf,
         (qvk.extent_render.width + 15) / 16,
         (qvk.extent_render.height + 15) / 16,
         1);
     // Because VKPT_IMG_TAA_OUTPUT changed, we make sure to wait for the image
     // to be written before continuing. This could be ensured in several
     // other ways as well.
     BARRIER_COMPUTE(cmd_buf, qvk.images[VKPT_IMG_TAA_OUTPUT]);
     reset_required = 0;
     return VK_SUCCESS;
 }
Referenced by R_RenderFrame_RTX().
vkpt_tone_mapping_request_reset()
void vkpt_tone_mapping_request_reset ()
Definition at line 138 of file tone_mapping.c.
 {
     reset_required = 1;
 }
Referenced by R_BeginRegistration_RTX().
vkpt_tone_mapping_reset()
VkResult vkpt_tone_mapping_reset (VkCommandBuffer cmd_buf)
Definition at line 176 of file tone_mapping.c.
 {
     VkClearColorValue clear_histogram = {
         .uint32 = { 0, 0, 0, 0 }
     };
     BUFFER_BARRIER(cmd_buf,
         .buffer = qvk.buf_tonemap.buffer,
         .offset = 0,
         .size = VK_WHOLE_SIZE,
         .srcAccessMask = 0,
         .dstAccessMask = 0
     );
     vkCmdFillBuffer(cmd_buf, qvk.buf_tonemap.buffer,
         0, VK_WHOLE_SIZE, 0);
     BUFFER_BARRIER(cmd_buf,
         .buffer = qvk.buf_tonemap.buffer,
         .offset = 0,
         .size = VK_WHOLE_SIZE,
         .srcAccessMask = 0,
         .dstAccessMask = VK_ACCESS_SHADER_WRITE_BIT
     );
     return VK_SUCCESS;
 }
Referenced by vkpt_tone_mapping_record_cmd_buffer().
vkpt_uniform_buffer_create()
VkResult vkpt_uniform_buffer_create ()
Definition at line 30 of file uniform_buffer.c.
 {
     VkDescriptorSetLayoutBinding ubo_layout_bindings[2] = { 0 };
     ubo_layout_bindings[0].descriptorType  = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER;
     ubo_layout_bindings[0].descriptorCount  = 1;
     ubo_layout_bindings[0].binding  = GLOBAL_UBO_BINDING_IDX;
     ubo_layout_bindings[0].stageFlags  = VK_SHADER_STAGE_ALL;
     ubo_layout_bindings[1].descriptorType  = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
     ubo_layout_bindings[1].descriptorCount  = 1;
     ubo_layout_bindings[1].binding  = GLOBAL_INSTANCE_BUFFER_BINDING_IDX;
     ubo_layout_bindings[1].stageFlags  = VK_SHADER_STAGE_ALL;
     VkDescriptorSetLayoutCreateInfo layout_info = {
         .sType        = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO,
         .bindingCount = LENGTH(ubo_layout_bindings),
         .pBindings    = ubo_layout_bindings,
     };
     _VK(vkCreateDescriptorSetLayout(qvk.device, &layout_info, NULL, &qvk.desc_set_layout_ubo));
     const VkMemoryPropertyFlags host_memory_flags = VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_CACHED_BIT |
         VK_MEMORY_PROPERTY_HOST_COHERENT_BIT;
     const VkMemoryPropertyFlags device_memory_flags = VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT;
     VkPhysicalDeviceProperties properties;
     vkGetPhysicalDeviceProperties(qvk.physical_device, &properties);
     ubo_alignment = properties.limits.minUniformBufferOffsetAlignment;
     const size_t buffer_size = align(sizeof(QVKUniformBuffer_t), ubo_alignment) + sizeof(QVKInstanceBuffer_t);
     for(int i = 0; i < MAX_FRAMES_IN_FLIGHT; i++)
         buffer_create(host_uniform_buffers + i, buffer_size, VK_BUFFER_USAGE_TRANSFER_SRC_BIT, host_memory_flags);
     buffer_create(&device_uniform_buffer, buffer_size, VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT | VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT,
         device_memory_flags);
     VkDescriptorPoolSize pool_size = {
         .type            = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
         .descriptorCount = MAX_FRAMES_IN_FLIGHT,
     };
     VkDescriptorPoolCreateInfo pool_info = {
         .sType         = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO,
         .poolSizeCount = 1,
         .pPoolSizes    = &pool_size,
         .maxSets       = MAX_FRAMES_IN_FLIGHT,
     };
     _VK(vkCreateDescriptorPool(qvk.device, &pool_info, NULL, &desc_pool_ubo));
     VkDescriptorSetAllocateInfo descriptor_set_alloc_info = {
         .sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO,
         .descriptorPool = desc_pool_ubo,
         .descriptorSetCount = 1,
         .pSetLayouts = &qvk.desc_set_layout_ubo,
     };
     _VK(vkAllocateDescriptorSets(qvk.device, &descriptor_set_alloc_info, &qvk.desc_set_ubo));
     VkDescriptorBufferInfo buf_info = {
         .buffer = device_uniform_buffer.buffer,
         .offset = 0,
         .range  = sizeof(QVKUniformBuffer_t),
     };
     VkDescriptorBufferInfo buf1_info = {
         .buffer = device_uniform_buffer.buffer,
         .offset = align(sizeof(QVKUniformBuffer_t), ubo_alignment),
         .range  = sizeof(QVKInstanceBuffer_t),
     };
     VkWriteDescriptorSet writes[2] = { 0 };
     writes[0].sType           = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,
     writes[0].dstSet          = qvk.desc_set_ubo,
     writes[0].dstBinding      = GLOBAL_UBO_BINDING_IDX,
     writes[0].dstArrayElement = 0,
     writes[0].descriptorType  = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
     writes[0].descriptorCount = 1,
     writes[0].pBufferInfo     = &buf_info,
     writes[1].sType           = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,
     writes[1].dstSet          = qvk.desc_set_ubo,
     writes[1].dstBinding      = GLOBAL_INSTANCE_BUFFER_BINDING_IDX,
     writes[1].dstArrayElement = 0,
     writes[1].descriptorType  = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
     writes[1].descriptorCount = 1,
     writes[1].pBufferInfo     = &buf1_info,
     vkUpdateDescriptorSets(qvk.device, LENGTH(writes), writes, 0, NULL);
     return VK_SUCCESS;
 }
vkpt_uniform_buffer_destroy()
VkResult vkpt_uniform_buffer_destroy ()
Definition at line 127 of file uniform_buffer.c.
 {
     vkDestroyDescriptorPool(qvk.device, desc_pool_ubo, NULL);
     vkDestroyDescriptorSetLayout(qvk.device, qvk.desc_set_layout_ubo, NULL);
     desc_pool_ubo = VK_NULL_HANDLE;
     qvk.desc_set_layout_ubo = VK_NULL_HANDLE;
     for(int i = 0; i < MAX_FRAMES_IN_FLIGHT; i++)
         buffer_destroy(host_uniform_buffers + i);
     buffer_destroy(&device_uniform_buffer);
     return VK_SUCCESS;
 }
vkpt_uniform_buffer_update()
VkResult vkpt_uniform_buffer_update (VkCommandBuffer command_buffer)
Definition at line 142 of file uniform_buffer.c.
 {
     BufferResource_t *ubo = host_uniform_buffers + qvk.current_frame_index;
     assert(ubo);
     assert(ubo->memory != VK_NULL_HANDLE);
     assert(ubo->buffer != VK_NULL_HANDLE);
     assert(qvk.current_frame_index < MAX_FRAMES_IN_FLIGHT);
     QVKUniformBuffer_t *mapped_ubo = buffer_map(ubo);
     assert(mapped_ubo);
     memcpy(mapped_ubo, &vkpt_refdef.uniform_buffer, sizeof(QVKUniformBuffer_t));
     const size_t offset = align(sizeof(QVKUniformBuffer_t), ubo_alignment);
     memcpy((uint8_t*)mapped_ubo + offset, &vkpt_refdef.uniform_instance_buffer, sizeof(QVKInstanceBuffer_t));
     buffer_unmap(ubo);
     mapped_ubo = NULL;
     VkBufferCopy copy = { 0 };
     copy.size = align(sizeof(QVKUniformBuffer_t), ubo_alignment) + sizeof(QVKInstanceBuffer_t);
     vkCmdCopyBuffer(command_buffer, ubo->buffer, device_uniform_buffer.buffer, 1, &copy);
     VkBufferMemoryBarrier barrier = {
         .sType = VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER,
         .srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT,
         .dstAccessMask = VK_ACCESS_UNIFORM_READ_BIT | VK_ACCESS_SHADER_READ_BIT,
         .srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED,
         .dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED,
         .buffer = device_uniform_buffer.buffer,
         .size = copy.size
     };
     vkCmdPipelineBarrier(command_buffer, VK_PIPELINE_STAGE_TRANSFER_BIT, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
         0, 0, NULL, 1, &barrier, 0, NULL);
     return VK_SUCCESS;
 }
Referenced by R_RenderFrame_RTX().
vkpt_vertex_buffer_create()
VkResult vkpt_vertex_buffer_create ()
Definition at line 492 of file vertex_buffer.c.
 {
     VkDescriptorSetLayoutBinding vbo_layout_bindings[] = {
         {
             .descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
             .descriptorCount = 1,
             .binding = VERTEX_BUFFER_BINDING_IDX,
             .stageFlags = VK_SHADER_STAGE_ALL,
         },
         {
             .descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
             .descriptorCount = 1,
             .binding = LIGHT_BUFFER_BINDING_IDX,
             .stageFlags = VK_SHADER_STAGE_ALL,
         },
         {
             .descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
             .descriptorCount = 1,
             .binding = READBACK_BUFFER_BINDING_IDX,
             .stageFlags = VK_SHADER_STAGE_ALL,
         },
         {
             .descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
             .descriptorCount = 1,
             .binding = TONE_MAPPING_BUFFER_BINDING_IDX,
             .stageFlags = VK_SHADER_STAGE_ALL,
         },
         {
             .descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
             .descriptorCount = 1,
             .binding = SUN_COLOR_BUFFER_BINDING_IDX,
             .stageFlags = VK_SHADER_STAGE_ALL,
         },
         {
             .descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
             .descriptorCount = 1,
             .binding = SUN_COLOR_UBO_BINDING_IDX,
             .stageFlags = VK_SHADER_STAGE_ALL,
         },
         {
             .descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
             .descriptorCount = 3,
             .binding = LIGHT_STATS_BUFFER_BINDING_IDX,
             .stageFlags = VK_SHADER_STAGE_ALL,
         }
     };
     VkDescriptorSetLayoutCreateInfo layout_info = {
         .sType        = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO,
         .bindingCount = LENGTH(vbo_layout_bindings),
         .pBindings    = vbo_layout_bindings,
     };
     _VK(vkCreateDescriptorSetLayout(qvk.device, &layout_info, NULL, &qvk.desc_set_layout_vertex_buffer));
     // Com_Printf("allocating %.02f MB of memory for vertex buffer\n", (double) sizeof(VertexBuffer) / (1024.0 * 1024.0));
     buffer_create(&qvk.buf_vertex, sizeof(VertexBuffer),
         VK_BUFFER_USAGE_TRANSFER_DST_BIT | VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_VERTEX_BUFFER_BIT,
         VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
     // Com_Printf("allocating %.02f MB of memory for staging vertex buffer\n", (double) sizeof(VertexBuffer) / (1024.0 * 1024.0));
     buffer_create(&qvk.buf_vertex_staging, sizeof(VertexBuffer),
         VK_BUFFER_USAGE_TRANSFER_SRC_BIT,
         VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
     buffer_create(&qvk.buf_light, sizeof(LightBuffer),
         VK_BUFFER_USAGE_TRANSFER_DST_BIT | VK_BUFFER_USAGE_STORAGE_BUFFER_BIT,
         VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
     for (int frame = 0; frame < MAX_FRAMES_IN_FLIGHT; frame++)
     {
         buffer_create(qvk.buf_light_staging + frame, sizeof(LightBuffer),
             VK_BUFFER_USAGE_TRANSFER_SRC_BIT,
             VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
     }
     buffer_create(&qvk.buf_readback, sizeof(ReadbackBuffer),
         VK_BUFFER_USAGE_TRANSFER_SRC_BIT | VK_BUFFER_USAGE_STORAGE_BUFFER_BIT,
         VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
     buffer_create(&qvk.buf_tonemap, sizeof(ToneMappingBuffer),
         VK_BUFFER_USAGE_TRANSFER_DST_BIT | VK_BUFFER_USAGE_STORAGE_BUFFER_BIT,
         VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
     buffer_create(&qvk.buf_sun_color, sizeof(SunColorBuffer),
         VK_BUFFER_USAGE_TRANSFER_DST_BIT | VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT,
         VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
     for (int frame = 0; frame < MAX_FRAMES_IN_FLIGHT; frame++)
     {
         buffer_create(qvk.buf_readback_staging + frame, sizeof(ReadbackBuffer),
             VK_BUFFER_USAGE_TRANSFER_DST_BIT,
             VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
     }
     VkDescriptorPoolSize pool_size = {
         .type            = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
         .descriptorCount = LENGTH(vbo_layout_bindings),
     };
     VkDescriptorPoolCreateInfo pool_info = {
         .sType         = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO,
         .poolSizeCount = 1,
         .pPoolSizes    = &pool_size,
         .maxSets       = 1,
     };
     _VK(vkCreateDescriptorPool(qvk.device, &pool_info, NULL, &desc_pool_vertex_buffer));
     VkDescriptorSetAllocateInfo descriptor_set_alloc_info = {
         .sType              = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO,
         .descriptorPool     = desc_pool_vertex_buffer,
         .descriptorSetCount = 1,
         .pSetLayouts        = &qvk.desc_set_layout_vertex_buffer,
     };
     _VK(vkAllocateDescriptorSets(qvk.device, &descriptor_set_alloc_info, &qvk.desc_set_vertex_buffer));
     VkDescriptorBufferInfo buf_info = {
         .buffer = qvk.buf_vertex.buffer,
         .offset = 0,
         .range  = sizeof(VertexBuffer),
     };
     VkWriteDescriptorSet output_buf_write = {
         .sType           = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,
         .dstSet          = qvk.desc_set_vertex_buffer,
         .dstBinding      = 0,
         .dstArrayElement = 0,
         .descriptorType  = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
         .descriptorCount = 1,
         .pBufferInfo     = &buf_info,
     };
     vkUpdateDescriptorSets(qvk.device, 1, &output_buf_write, 0, NULL);
     output_buf_write.dstBinding = 1;
     buf_info.buffer = qvk.buf_light.buffer;
     buf_info.range = sizeof(LightBuffer);
     vkUpdateDescriptorSets(qvk.device, 1, &output_buf_write, 0, NULL);
     output_buf_write.dstBinding = 2;
     buf_info.buffer = qvk.buf_readback.buffer;
     buf_info.range = sizeof(ReadbackBuffer);
     vkUpdateDescriptorSets(qvk.device, 1, &output_buf_write, 0, NULL);
     output_buf_write.dstBinding = 3;
     buf_info.buffer = qvk.buf_tonemap.buffer;
     buf_info.range = sizeof(ToneMappingBuffer);
     vkUpdateDescriptorSets(qvk.device, 1, &output_buf_write, 0, NULL);
     output_buf_write.dstBinding = 4;
     buf_info.buffer = qvk.buf_sun_color.buffer;
     buf_info.range = sizeof(SunColorBuffer);
     vkUpdateDescriptorSets(qvk.device, 1, &output_buf_write, 0, NULL);
     output_buf_write.dstBinding = 5;
     output_buf_write.descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER;
     buf_info.buffer = qvk.buf_sun_color.buffer;
     buf_info.range = sizeof(SunColorBuffer);
     vkUpdateDescriptorSets(qvk.device, 1, &output_buf_write, 0, NULL);
     return VK_SUCCESS;
 }
vkpt_vertex_buffer_create_instance()
VkResult vkpt_vertex_buffer_create_instance (VkCommandBuffer cmd_buf, uint32_t num_instances, qboolean update_world_animations)
Definition at line 818 of file vertex_buffer.c.
 {
     VkDescriptorSet desc_sets[] = {
         qvk.desc_set_ubo,
         qvk.desc_set_vertex_buffer
     };
     vkCmdBindPipeline(cmd_buf, VK_PIPELINE_BIND_POINT_COMPUTE, pipeline_instance_geometry);
     vkCmdBindDescriptorSets(cmd_buf, VK_PIPELINE_BIND_POINT_COMPUTE,
         pipeline_layout_instance_geometry, 0, LENGTH(desc_sets), desc_sets, 0, 0);
     vkCmdDispatch(cmd_buf, num_instances, 1, 1);
     if (update_world_animations)
     {
         vkCmdBindPipeline(cmd_buf, VK_PIPELINE_BIND_POINT_COMPUTE, pipeline_animate_materials);
         int num_groups = (((vkpt_refdef.bsp_mesh_world.world_idx_count + vkpt_refdef.bsp_mesh_world.world_transparent_count) / 3) + 255) / 256;
         vkCmdDispatch(cmd_buf, num_groups, 1, 1);
     }
     VkBufferMemoryBarrier barrier = {
         .sType               = VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER,
         .srcAccessMask       = VK_ACCESS_SHADER_WRITE_BIT,
         .dstAccessMask       = VK_ACCESS_SHADER_READ_BIT,
         .buffer              = qvk.buf_vertex.buffer,
         .size                = qvk.buf_vertex.size,
         .srcQueueFamilyIndex = qvk.queue_idx_graphics,
         .dstQueueFamilyIndex = qvk.queue_idx_graphics
     };
     vkCmdPipelineBarrier(
             cmd_buf,
             VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
             VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
             0,
             0, NULL,
             1, &barrier,
             0, NULL);
     return VK_SUCCESS;
 }
Referenced by R_RenderFrame_RTX().
vkpt_vertex_buffer_create_pipelines()
VkResult vkpt_vertex_buffer_create_pipelines ()
Definition at line 759 of file vertex_buffer.c.
 {
     assert(!pipeline_instance_geometry);
     assert(!pipeline_animate_materials);
     assert(!pipeline_layout_instance_geometry);
     assert(qvk.desc_set_layout_ubo);
     assert(qvk.desc_set_layout_vertex_buffer);
     VkDescriptorSetLayout desc_set_layouts[] = {
         qvk.desc_set_layout_ubo, qvk.desc_set_layout_vertex_buffer
     };
     CREATE_PIPELINE_LAYOUT(qvk.device, &pipeline_layout_instance_geometry,
         .setLayoutCount         = LENGTH(desc_set_layouts),
         .pSetLayouts            = desc_set_layouts,
     );
     VkComputePipelineCreateInfo compute_pipeline_info[] = {
         {
             .sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
             .stage = SHADER_STAGE(QVK_MOD_INSTANCE_GEOMETRY_COMP, VK_SHADER_STAGE_COMPUTE_BIT),
             .layout = pipeline_layout_instance_geometry
         },
         {
             .sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
             .stage = SHADER_STAGE(QVK_MOD_ANIMATE_MATERIALS_COMP, VK_SHADER_STAGE_COMPUTE_BIT),
             .layout = pipeline_layout_instance_geometry
         },
     };
     VkPipeline pipelines[2];
     _VK(vkCreateComputePipelines(qvk.device, 0, LENGTH(compute_pipeline_info), compute_pipeline_info, 0, pipelines));
     pipeline_instance_geometry = pipelines[0];
     pipeline_animate_materials = pipelines[1];
     return VK_SUCCESS;
 }
vkpt_vertex_buffer_destroy()
VkResult vkpt_vertex_buffer_destroy ()
Definition at line 675 of file vertex_buffer.c.
 {
     vkDestroyDescriptorPool(qvk.device, desc_pool_vertex_buffer, NULL);
     vkDestroyDescriptorSetLayout(qvk.device, qvk.desc_set_layout_vertex_buffer, NULL);
     desc_pool_vertex_buffer = VK_NULL_HANDLE;
     qvk.desc_set_layout_vertex_buffer = VK_NULL_HANDLE;
     buffer_destroy(&qvk.buf_vertex);
     buffer_destroy(&qvk.buf_vertex_staging);
     buffer_destroy(&qvk.buf_light);
     buffer_destroy(&qvk.buf_readback);
     for (int frame = 0; frame < MAX_FRAMES_IN_FLIGHT; frame++)
     {
         buffer_destroy(qvk.buf_light_staging + frame);
         buffer_destroy(qvk.buf_readback_staging + frame);
     }
     buffer_destroy(&qvk.buf_tonemap);
     buffer_destroy(&qvk.buf_sun_color);
     return VK_SUCCESS;
 }
vkpt_vertex_buffer_destroy_pipelines()
VkResult vkpt_vertex_buffer_destroy_pipelines ()
Definition at line 800 of file vertex_buffer.c.
 {
     assert(pipeline_instance_geometry);
     assert(pipeline_animate_materials);
     assert(pipeline_layout_instance_geometry);
     vkDestroyPipeline(qvk.device, pipeline_instance_geometry, NULL);
     vkDestroyPipeline(qvk.device, pipeline_animate_materials, NULL);
     vkDestroyPipelineLayout(qvk.device, pipeline_layout_instance_geometry, NULL);
     pipeline_instance_geometry = VK_NULL_HANDLE;
     pipeline_animate_materials = VK_NULL_HANDLE;
     pipeline_layout_instance_geometry = VK_NULL_HANDLE;
     return VK_SUCCESS;
 }
vkpt_vertex_buffer_upload_bsp_mesh_to_staging()
VkResult vkpt_vertex_buffer_upload_bsp_mesh_to_staging (bsp_mesh_t * bsp_mesh)
Definition at line 90 of file vertex_buffer.c.
 {
     assert(bsp_mesh);
     VertexBuffer *vbo = (VertexBuffer *) buffer_map(&qvk.buf_vertex_staging);
     assert(vbo);
     int num_vertices = bsp_mesh->num_vertices;
     if (num_vertices > MAX_VERT_BSP)
     {
         assert(!"Vertex buffer overflow");
         num_vertices = MAX_VERT_BSP;
     }
     memcpy(vbo->positions_bsp,  bsp_mesh->positions, num_vertices * sizeof(float) * 3   );
     memcpy(vbo->tex_coords_bsp, bsp_mesh->tex_coords,num_vertices * sizeof(float) * 2   );
     memcpy(vbo->tangents_bsp,   bsp_mesh->tangents,  num_vertices * sizeof(float));
     memcpy(vbo->materials_bsp,  bsp_mesh->materials, num_vertices * sizeof(uint32_t) / 3);
     memcpy(vbo->clusters_bsp, bsp_mesh->clusters, num_vertices * sizeof(uint32_t) / 3);
     memcpy(vbo->texel_density_bsp, bsp_mesh->texel_density, num_vertices * sizeof(float) / 3);
     int num_clusters = bsp_mesh->num_clusters;
     if (num_clusters > MAX_LIGHT_LISTS)
     {
         assert(!"Visibility buffer overflow");
         num_clusters = MAX_LIGHT_LISTS;
     }
     memcpy(vbo->sky_visibility, bsp_mesh->sky_visibility, (num_clusters + 7) / 8);
     buffer_unmap(&qvk.buf_vertex_staging);
     vbo = NULL;
     return VK_SUCCESS;
 }
Referenced by R_BeginRegistration_RTX().
vkpt_vertex_buffer_upload_models_to_staging()
VkResult vkpt_vertex_buffer_upload_models_to_staging ()
Definition at line 412 of file vertex_buffer.c.
 {
     VertexBuffer *vbo = (VertexBuffer *) buffer_map(&qvk.buf_vertex_staging);
     assert(vbo);
     int idx_offset = 0;
     int vertex_offset = 0;
     for(int i = 0; i < MAX_MODELS; i++) {
         if(!r_models[i].meshes) {
             continue;
         }
         for (int nmesh = 0; nmesh < r_models[i].nummeshes; nmesh++)
         {
             maliasmesh_t *m = r_models[i].meshes + nmesh;
             m->idx_offset = idx_offset;
             m->vertex_offset = vertex_offset;
             assert(r_models[i].numframes > 0);
             int num_verts = r_models[i].numframes * m->numverts;
             assert(num_verts > 0);
 #if 0
             for (int j = 0; j < num_verts; j++)
                 Com_Printf("%f %f %f\n",
                     m->positions[j][0],
                     m->positions[j][1],
                     m->positions[j][2]);
             for (int j = 0; j < m->numtris; j++)
                 Com_Printf("%d %d %d\n",
                     m->indices[j * 3 + 0],
                     m->indices[j * 3 + 1],
                     m->indices[j * 3 + 2]);
 #endif
 #if 0
             char buf[1024];
             snprintf(buf, sizeof buf, "model_%04d.obj", i);
             FILE *f = fopen(buf, "wb+");
             assert(f);
             for (int j = 0; j < m->numverts; j++) {
                 fprintf(f, "v %f %f %f\n",
                     m->positions[j][0],
                     m->positions[j][1],
                     m->positions[j][2]);
             }
             for (int j = 0; j < m->numindices / 3; j++) {
                 fprintf(f, "f %d %d %d\n",
                     m->indices[j * 3 + 0] + 1,
                     m->indices[j * 3 + 1] + 1,
                     m->indices[j * 3 + 2] + 1);
             }
             fclose(f);
 #endif
             memcpy(vbo->positions_model + vertex_offset * 3, m->positions, sizeof(float) * 3 * num_verts);
             memcpy(vbo->normals_model + vertex_offset * 3, m->normals, sizeof(float) * 3 * num_verts);
             memcpy(vbo->tex_coords_model + vertex_offset * 2, m->tex_coords, sizeof(float) * 2 * num_verts);
             memcpy(vbo->tangents_model + vertex_offset * 4, m->tangents, sizeof(float) * 4 * num_verts);
             memcpy(vbo->idx_model + idx_offset, m->indices, sizeof(uint32_t) * m->numindices);
             vertex_offset += num_verts;
             idx_offset += m->numtris * 3;
             assert(vertex_offset < MAX_VERT_MODEL);
             assert(idx_offset < MAX_IDX_MODEL);
         }
     }
     buffer_unmap(&qvk.buf_vertex_staging);
     vbo = NULL;
     // Com_Printf("uploaded %d vert, %d idx\n", vertex_offset, idx_offset);
     return VK_SUCCESS;
 }
Referenced by R_BeginFrame_RTX().
vkpt_vertex_buffer_upload_staging()
VkResult vkpt_vertex_buffer_upload_staging ()
Definition at line 36 of file vertex_buffer.c.
 {
     vkWaitForFences(qvk.device, 1, &qvk.fence_vertex_sync, VK_TRUE, ~((uint64_t)0));
     vkResetFences(qvk.device, 1, &qvk.fence_vertex_sync);
     VkCommandBuffer cmd_buf = vkpt_begin_command_buffer(&qvk.cmd_buffers_graphics);
     VkBufferCopy copyRegion = {
         .size = sizeof(VertexBuffer),
     };
     vkCmdCopyBuffer(cmd_buf, qvk.buf_vertex_staging.buffer, qvk.buf_vertex.buffer, 1, &copyRegion);
     BUFFER_BARRIER(cmd_buf,
         .srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT,
         .dstAccessMask = VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_NV,
         .buffer = qvk.buf_vertex.buffer,
         .offset = 0,
         .size = VK_WHOLE_SIZE,
     );
     if (qvk.buf_light_stats[0].buffer)
     {
         vkCmdFillBuffer(cmd_buf, qvk.buf_light_stats[0].buffer, 0, qvk.buf_light_stats[0].size, 0);
         vkCmdFillBuffer(cmd_buf, qvk.buf_light_stats[1].buffer, 0, qvk.buf_light_stats[1].size, 0);
         vkCmdFillBuffer(cmd_buf, qvk.buf_light_stats[2].buffer, 0, qvk.buf_light_stats[2].size, 0);
     }
     vkpt_submit_command_buffer(cmd_buf, qvk.queue_graphics, (1 << qvk.device_count) - 1, 0, NULL, NULL, NULL, 0, NULL, NULL, qvk.fence_vertex_sync);
     return VK_SUCCESS;
 }
Referenced by R_BeginFrame_RTX(), and R_BeginRegistration_RTX().
vkpt_wait_idle()
void vkpt_wait_idle (VkQueue queue, cmd_buf_group_t * group)
Definition at line 3405 of file main.c.
 {
     vkQueueWaitIdle(queue);
     vkpt_reset_command_buffers(group);
 }
Referenced by change_image_layouts(), create_swapchain(), fill_index_buffer(), IMG_ReadPixels_RTX(), and vkpt_pt_create_static().
Variable Documentation
draw
drawStatic_t draw
Definition at line 21 of file draw.c.
Referenced by _GL_StretchPic(), draw_char(), enqueue_stretch_pic(), GL_Setup2D(), R_ClearColor(), R_ClearColor_GL(), R_ClearColor_RTX(), R_DrawFixedData(), R_DrawPic(), R_DrawPic_GL(), R_DrawStretchData(), R_DrawStretchPic(), R_DrawStretchPic_GL(), R_DrawStretchPic_RTX(), R_InitDraw(), R_SetAlpha(), R_SetAlpha_GL(), R_SetAlpha_RTX(), R_SetAlphaScale_RTX(), R_SetClipRect(), R_SetClipRect_GL(), R_SetColor(), R_SetColor_GL(), R_SetColor_RTX(), R_SetScale_GL(), R_SetScale_RTX(), and SCR_DrawLayout().
qvk
QVK_t qvk
Definition at line 377 of file main.c.
Referenced by allocate_and_bind_memory_to_blas(), allocate_and_bind_memory_to_buffers(), allocate_gpu_memory(), append_blas(), buffer_create(), buffer_destroy(), buffer_map(), buffer_unmap(), calculate_scratch_buffer_size(), change_image_layouts(), compute_push_constants(), create_blas(), create_buffer_views(), create_buffers(), create_command_pool_and_fences(), create_descriptor_set(), create_image_views(), create_invalid_texture(), create_pipeline_layout(), create_pipelines(), create_readback_image(), create_render_pass(), create_shader_module_from_file(), create_sub_allocator(), create_swapchain(), CreateShadowMap(), destroy_invalid_texture(), destroy_readback_image(), destroy_swapchain(), destroy_tex_images(), destroy_transparency(), destroy_vulkan(), destroyEnvTexture(), draw_profiler(), fill_index_buffer(), FillVertexAndIndexBuffers(), get_memory_type(), get_render_extent(), get_scratch_buffer_size(), get_screen_image_extent(), IMG_ReadPixels_RTX(), IMG_ReloadAll(), IMG_Unload_RTX(), init_vulkan(), initializeEnvTexture(), load_blue_noise(), prepare_ubo(), qvk_get_current_desc_set_textures(), R_BeginFrame_RTX(), R_BeginRegistration_RTX(), R_EndFrame_RTX(), R_Init_RTX(), R_ModeChanged_RTX(), R_RenderFrame_RTX(), R_Shutdown_RTX(), recreate_swapchain(), ReleaseInfo(), ReleaseShadowmap(), reset_sun_color_buffer(), set_current_gpu(), setup_rt_pipeline(), textures_destroy_unused_set(), update_descriptor_set(), UploadImage(), vkpt_asvgf_create_gradient_samples(), vkpt_asvgf_create_pipelines(), vkpt_asvgf_destroy(), vkpt_asvgf_destroy_pipelines(), vkpt_asvgf_filter(), vkpt_asvgf_initialize(), vkpt_begin_command_buffer(), vkpt_bloom_create_pipelines(), vkpt_bloom_destroy(), vkpt_bloom_destroy_pipelines(), vkpt_bloom_initialize(), vkpt_bloom_record_cmd_buffer(), vkpt_compositing(), vkpt_create_images(), vkpt_destroy_all(), vkpt_destroy_god_rays(), vkpt_destroy_images(), vkpt_draw_create_pipelines(), vkpt_draw_destroy(), vkpt_draw_destroy_pipelines(), vkpt_draw_get_extent(), vkpt_draw_initialize(), vkpt_draw_submit_stretch_pics(), vkpt_evaluate_sun_light(), vkpt_final_blit_filtered(), vkpt_final_blit_simple(), vkpt_free_command_buffers(), vkpt_god_rays_destroy_pipelines(), vkpt_image_copy(), vkpt_initialize_all(), vkpt_initialize_god_rays(), vkpt_interleave(), vkpt_light_buffer_upload_staging(), vkpt_light_buffer_upload_to_staging(), vkpt_light_stats_create(), vkpt_light_stats_destroy(), vkpt_physical_sky_create_pipelines(), vkpt_physical_sky_destroy(), vkpt_physical_sky_destroy_pipelines(), vkpt_physical_sky_initialize(), vkpt_physical_sky_record_cmd_buffer(), vkpt_profiler_destroy(), vkpt_profiler_initialize(), vkpt_profiler_next_frame(), vkpt_profiler_query(), vkpt_pt_create_accel_bottom(), vkpt_pt_create_all_dynamic(), vkpt_pt_create_pipelines(), vkpt_pt_create_static(), vkpt_pt_create_toplevel(), vkpt_pt_destroy(), vkpt_pt_destroy_dynamic(), vkpt_pt_destroy_explosions(), vkpt_pt_destroy_pipelines(), vkpt_pt_destroy_static(), vkpt_pt_destroy_toplevel(), vkpt_pt_destroy_transparent_models(), vkpt_pt_destroy_viewer_models(), vkpt_pt_destroy_viewer_weapon(), vkpt_pt_init(), vkpt_pt_trace_lighting(), vkpt_pt_trace_primary_rays(), vkpt_pt_trace_reflections(), vkpt_pt_update_descripter_set_bindings(), vkpt_readback(), vkpt_record_god_rays_filter_command_buffer(), vkpt_record_god_rays_trace_command_buffer(), vkpt_reset_command_buffers(), vkpt_shadow_map_create_pipelines(), vkpt_shadow_map_destroy(), vkpt_shadow_map_destroy_pipelines(), vkpt_shadow_map_initialize(), vkpt_shadow_map_render(), vkpt_submit_command_buffer(), vkpt_submit_command_buffer_simple(), vkpt_taa(), vkpt_textures_destroy(), vkpt_textures_destroy_unused(), vkpt_textures_end_registration(), vkpt_textures_initialize(), vkpt_textures_update_descriptor_set(), vkpt_textures_upload_envmap(), vkpt_tone_mapping_create_pipelines(), vkpt_tone_mapping_destroy(), vkpt_tone_mapping_destroy_pipelines(), vkpt_tone_mapping_initialize(), vkpt_tone_mapping_record_cmd_buffer(), vkpt_tone_mapping_reset(), vkpt_uniform_buffer_create(), vkpt_uniform_buffer_destroy(), vkpt_uniform_buffer_update(), vkpt_uniform_precomputed_buffer_create(), vkpt_uniform_precomputed_buffer_destroy(), vkpt_uniform_precomputed_buffer_update(), vkpt_vertex_buffer_create(), vkpt_vertex_buffer_create_instance(), vkpt_vertex_buffer_create_pipelines(), vkpt_vertex_buffer_destroy(), vkpt_vertex_buffer_destroy_pipelines(), vkpt_vertex_buffer_upload_bsp_mesh_to_staging(), vkpt_vertex_buffer_upload_models_to_staging(), and vkpt_vertex_buffer_upload_staging().
vkpt_refdef
vkpt_refdef_t vkpt_refdef
Definition at line 372 of file main.c.
Referenced by fill_model_instance(), prepare_entities(), prepare_ubo(), process_bsp_entity(), process_regular_entity(), process_render_feedback(), R_BeginFrame_RTX(), R_BeginRegistration_RTX(), R_RenderFrame_RTX(), vkpt_freecam_update(), vkpt_print_material(), vkpt_set_material(), vkpt_show_pvs(), vkpt_uniform_buffer_update(), write_beam_geometry(), write_particle_geometry(), and write_sprite_geometry().