Quake II RTX doxygen: C:/entry/dev/Q2RTX/src/shared/shared.c File Reference
shared.c File Reference
#include "shared/shared.h"
Functions
void AngleVectors (vec3_t angles, vec3_t forward, vec3_t right, vec3_t up)
vec_t VectorNormalize (vec3_t v)
vec_t VectorNormalize2 (vec3_t v, vec3_t out)
void ClearBounds (vec3_t mins, vec3_t maxs)
void AddPointToBounds (const vec3_t v, vec3_t mins, vec3_t maxs)
void UnionBounds (vec3_t a[2], vec3_t b[2], vec3_t c[2])
vec_t RadiusFromBounds (const vec3_t mins, const vec3_t maxs)
char * COM_SkipPath (const char *pathname)
void COM_StripExtension (const char *in, char *out, size_t size)
char * COM_FileExtension (const char *in)
void COM_FileBase (char *in, char *out)
void COM_FilePath (const char *in, char *out, size_t size)
size_t COM_DefaultExtension (char *path, const char *ext, size_t size)
qboolean COM_IsFloat (const char *s)
qboolean COM_IsUint (const char *s)
qboolean COM_IsPath (const char *s)
qboolean COM_IsWhite (const char *s)
int SortStrcmp (const void *p1, const void *p2)
int SortStricmp (const void *p1, const void *p2)
size_t COM_strclr (char *s)
char * va (const char *format,...)
char * COM_Parse (const char **data_p)
size_t COM_Compress (char *data)
int Q_strncasecmp (const char *s1, const char *s2, size_t n)
int Q_strcasecmp (const char *s1, const char *s2)
char * Q_strcasestr (const char *s1, const char *s2)
size_t Q_strlcpy (char *dst, const char *src, size_t size)
size_t Q_strlcat (char *dst, const char *src, size_t size)
size_t Q_concat (char *dest, size_t size,...)
size_t Q_vsnprintf (char *dest, size_t size, const char *fmt, va_list argptr)
size_t Q_vscnprintf (char *dest, size_t size, const char *fmt, va_list argptr)
size_t Q_snprintf (char *dest, size_t size, const char *fmt,...)
size_t Q_scnprintf (char *dest, size_t size, const char *fmt,...)
char * Q_strchrnul (const char *s, int c)
void * Q_memccpy (void *dst, const void *src, int c, size_t size)
void Q_setenv (const char *name, const char *value)
char * Info_ValueForKey (const char *s, const char *key)
void Info_RemoveKey (char *s, const char *key)
qboolean Info_Validate (const char *s)
size_t Info_SubValidate (const char *s)
qboolean Info_SetValueForKey (char *s, const char *key, const char *value)
void Info_NextPair (const char **string, char *key, char *value)
void Info_Print (const char *infostring)
Variables
vec3_t vec3_origin = { 0, 0, 0 }
static char com_token [4][MAX_TOKEN_CHARS]
static int com_tokidx
Function Documentation
AddPointToBounds()
void AddPointToBounds (const vec3_t v, vec3_t mins, vec3_t maxs)
Definition at line 97 of file shared.c.
 {
     int        i;
     vec_t    val;
     for (i = 0; i < 3; i++) {
         val = v[i];
         if (val < mins[i])
             mins[i] = val;
         if (val > maxs[i])
             maxs[i] = val;
     }
 }
Referenced by Think_SpawnDoorTrigger().
AngleVectors()
void AngleVectors (vec3_t angles, vec3_t forward, vec3_t right, vec3_t up)
Definition at line 23 of file shared.c.
 {
     float        angle;
     float        sr, sp, sy, cr, cp, cy;
     angle = angles[YAW] * (M_PI * 2 / 360);
     sy = sin(angle);
     cy = cos(angle);
     angle = angles[PITCH] * (M_PI * 2 / 360);
     sp = sin(angle);
     cp = cos(angle);
     angle = angles[ROLL] * (M_PI * 2 / 360);
     sr = sin(angle);
     cr = cos(angle);
     if (forward) {
         forward[0] = cp * cy;
         forward[1] = cp * sy;
         forward[2] = -sp;
     }
     if (right) {
         right[0] = (-1 * sr * sp * cy + -1 * cr * -sy);
         right[1] = (-1 * sr * sp * sy + -1 * cr * cy);
         right[2] = -1 * sr * cp;
     }
     if (up) {
         up[0] = (cr * sp * cy + -sr * -sy);
         up[1] = (cr * sp * sy + -sr * cy);
         up[2] = cr * cp;
     }
 }
Referenced by actorMachineGun(), ai_run(), Blaster_Fire(), boss2_firebullet_left(), boss2_firebullet_right(), Boss2Rocket(), Chaingun_Fire(), CheckPowerArmor(), ChickRocket(), CL_AddExplosionLight(), CL_AddPacketEntities(), CL_AddPlayerBeams(), CL_AddViewWeapon(), CL_CalcViewValues(), CL_MuzzleFlash(), CL_MuzzleFlash2(), CL_SetupThirdPersionView(), CL_TrackerTrail(), ClientEndServerFrame(), CM_TransformedPointContents(), Drop_Item(), fire_flaregun(), fire_grenade(), fire_grenade2(), fire_hit(), fire_lead(), flare_sparks(), floater_fire_blaster(), floater_zap(), flyer_fire(), G_SetMovedir(), gib_touch(), GladiatorGun(), GunnerFire(), GunnerGrenade(), hover_fire_blaster(), InfantryMachineGun(), infront(), jorg_firebullet_left(), jorg_firebullet_right(), jorgBFG(), Machinegun_Fire(), makronBFG(), MakronHyperblaster(), MakronRailgun(), medic_cable_attack(), medic_fire_blaster(), mutant_jump_takeoff(), MVD_HitPlayer(), parasite_drain_attack(), PM_ClampAngles(), Pmove(), R_AliasSetUpLerpData(), R_AliasSetUpTransform(), R_SetupFrame(), RotatedBBox(), soldier_fire(), SP_func_door_secret(), supertankMachineGun(), supertankRocket(), SV_Push(), TankBlaster(), TankMachineGun(), TankRocket(), Touch_Multi(), turret_breach_fire(), UpdateChaseCam(), vkpt_freecam_update(), weapon_bfg_fire(), weapon_flaregun_fire(), weapon_grenade_fire(), weapon_grenadelauncher_fire(), weapon_railgun_fire(), Weapon_RocketLauncher_Fire(), weapon_shotgun_fire(), and weapon_supershotgun_fire().
ClearBounds()
void ClearBounds (vec3_t mins, vec3_t maxs)
Definition at line 91 of file shared.c.
 {
     mins[0] = mins[1] = mins[2] = 99999;
     maxs[0] = maxs[1] = maxs[2] = -99999;
 }
Referenced by MOD_LoadMD2_GL(), and MOD_LoadMD2_RTX().
COM_Compress()
size_t COM_Compress (char * data)
Definition at line 543 of file shared.c.
 {
     int     c, n = 0;
     char    *s = data, *d = data;
     while (*s) {
         // skip whitespace
         if (*s <= ' ') {
             if (n == 0) {
                 n = ' ';
             }
             do {
                 c = *s++;
                 if (c == '\n') {
                     n = '\n';
                 }
                 if (!c) {
                     goto finish;
                 }
             } while (*s <= ' ');
         }
         // skip // comments
         if (s[0] == '/' && s[1] == '/') {
             n = ' ';
             s += 2;
             while (*s && *s != '\n') {
                 s++;
             }
             continue;
         }
         // skip /* */ comments
         if (s[0] == '/' && s[1] == '*') {
             n = ' ';
             s += 2;
             while (*s) {
                 if (s[0] == '*' && s[1] == '/') {
                     s += 2;
                     break;
                 }
                 if (*s == '\n') {
                     n = '\n';
                 }
                 s++;
             }
             continue;
         }
         // add whitespace character
         if (n) {
             *d++ = n;
             n = 0;
         }
         // handle quoted strings specially
         if (*s == '\"') {
             s++;
             *d++ = '\"';
             do {
                 c = *s++;
                 if (!c) {
                     goto finish;
                 }
                 *d++ = c;
             } while (c != '\"');
             continue;
         }
         // handle line feed escape
         if (*s == '\\' && s[1] == '\n') {
             s += 2;
             continue;
         }
         if (*s == '\\' && s[1] == '\r' && s[2] == '\n') {
             s += 3;
             continue;
         }
         // parse a regular word
         do {
             *d++ = *s++;
         } while (*s > ' ');
     }
 finish:
     *d = 0;
     return d - data;
 }
Referenced by Cmd_ExecuteFile(), and Parse_File().
COM_DefaultExtension()
size_t COM_DefaultExtension (char * path, const char * ext, size_t size)
Definition at line 279 of file shared.c.
 {
     char    *src;
     size_t  len;
     if (*path) {
         len = strlen(path);
         src = path + len - 1;
         while (*src != '/' && src != path) {
             if (*src == '.')
                 return len;                 // it has an extension
             src--;
         }
     }
     len = Q_strlcat(path, ext, size);
     return len;
 }
Referenced by CL_PlaySound_f(), and R_RegisterImage().
COM_FileBase()
void COM_FileBase (char * in, char * out)
Definition at line 229 of file shared.c.
 {
     char *s, *s2;
     s = in + strlen(in) - 1;
     while (s != in && *s != '.')
         s--;
     for (s2 = s; s2 != in && *s2 != '/'; s2--)
         ;
     if (s - s2 < 2)
         out[0] = 0;
     else {
         s--;
         strncpy(out, s2 + 1, s - s2);
         out[s - s2] = 0;
     }
 }
COM_FileExtension()
char* COM_FileExtension (const char * in)
Definition at line 199 of file shared.c.
 {
     const char *s;
     const char *last;
     if (!in) {
         Com_Error(ERR_FATAL, "%s: NULL", __func__);
     }
     s = in + strlen(in);
     last = s;
     while (s != in) {
         if (*s == '/') {
             break;
         }
         if (*s == '.') {
             return (char *)s;
         }
         s--;
     }
     return (char *)last;
 }
Referenced by check_file_len(), Com_MapList_m(), FS_ListFiles(), and Sys_ListFiles_r().
COM_FilePath()
void COM_FilePath (const char * in, char * out, size_t size)
Definition at line 257 of file shared.c.
 {
     char *s;
     Q_strlcpy(out, in, size);
     s = strrchr(out, '/');
     if (s) {
         *s = 0;
     } else {
         *out = 0;
     }
 }
COM_IsFloat()
qboolean COM_IsFloat (const char * s)
Definition at line 307 of file shared.c.
 {
     int c, dot = '.';
     if (*s == '-') {
         s++;
     }
     if (!*s) {
         return qfalse;
     }
     do {
         c = *s++;
         if (c == dot) {
             dot = 0;
         } else if (!Q_isdigit(c)) {
             return qfalse;
         }
     } while (*s);
     return qtrue;
 }
Referenced by Cmd_If_f(), and Cvar_Inc_f().
COM_IsPath()
qboolean COM_IsPath (const char * s)
Definition at line 348 of file shared.c.
 {
     int c;
     if (!*s) {
         return qfalse;
     }
     do {
         c = *s++;
         if (!Q_ispath(c)) {
             return qfalse;
         }
     } while (*s);
     return qtrue;
 }
Referenced by CL_ParsePlayerSkin(), fs_game_changed(), SV_Loadgame_f(), and SV_Savegame_f().
COM_IsUint()
qboolean COM_IsUint (const char * s)
Definition at line 330 of file shared.c.
 {
     int c;
     if (!*s) {
         return qfalse;
     }
     do {
         c = *s++;
         if (!Q_isdigit(c)) {
             return qfalse;
         }
     } while (*s);
     return qtrue;
 }
Referenced by AC_Info_f(), cl_chat_sound_changed(), Com_ParseColor(), gtv_set_conn(), MVD_SetChannel(), MVD_SetPlayer(), NET_StringPairToAdr(), SV_DelFilterCmd_f(), SV_DelMatch_f(), SV_GetPlayer(), and UI_StatusEvent().
COM_IsWhite()
qboolean COM_IsWhite (const char * s)
Definition at line 366 of file shared.c.
 {
     int c;
     while (*s) {
         c = *s++;
         if (Q_isgraph(c)) {
             return qfalse;
         }
     }
     return qtrue;
 }
Referenced by parse_userinfo(), SV_UpdateUserinfo(), and UI_StatusEvent().
COM_Parse()
char* COM_Parse (const char ** data_p)
Definition at line 455 of file shared.c.
 {
     int         c;
     int         len;
     const char  *data;
     char        *s = com_token[com_tokidx++ & 3];
     data = *data_p;
     len = 0;
     s[0] = 0;
     if (!data) {
         *data_p = NULL;
         return s;
     }
 // skip whitespace
 skipwhite:
     while ((c = *data) <= ' ') {
         if (c == 0) {
             *data_p = NULL;
             return s;
         }
         data++;
     }
 // skip // comments
     if (c == '/' && data[1] == '/') {
         data += 2;
         while (*data && *data != '\n')
             data++;
         goto skipwhite;
     }
 // skip /* */ comments
     if (c == '/' && data[1] == '*') {
         data += 2;
         while (*data) {
             if (data[0] == '*' && data[1] == '/') {
                 data += 2;
                 break;
             }
             data++;
         }
         goto skipwhite;
     }
 // handle quoted strings specially
     if (c == '\"') {
         data++;
         while (1) {
             c = *data++;
             if (c == '\"' || !c) {
                 goto finish;
             }
             if (len < MAX_TOKEN_CHARS - 1) {
                 s[len++] = c;
             }
         }
     }
 // parse a regular word
     do {
         if (len < MAX_TOKEN_CHARS - 1) {
             s[len++] = c;
         }
         data++;
         c = *data;
     } while (c > 32);
 finish:
     s[len] = 0;
     *data_p = data;
     return s;
 }
Referenced by CL_ParseStatusResponse(), ED_ParseEdict(), MVD_ParseEntityString(), SCR_ExecuteLayoutString(), SpawnEntities(), and TH_DrawLayoutString().
COM_SkipPath()
char* COM_SkipPath (const char * pathname)
Definition at line 152 of file shared.c.
 {
     char    *last;
     if (!pathname) {
         Com_Error(ERR_FATAL, "%s: NULL", __func__);
     }
     last = (char *)pathname;
     while (*pathname) {
         if (*pathname == '/')
             last = (char *)pathname + 1;
         pathname++;
     }
     return last;
 }
Referenced by CL_PlayDemo_f(), demo_play_next(), and FS_ListFiles().
COM_strclr()
size_t COM_strclr (char * s)
Definition at line 398 of file shared.c.
 {
     char *p;
     int c;
     size_t len;
     p = s;
     len = 0;
     while (*s) {
         c = *s++;
         c &= 127;
         if (Q_isprint(c)) {
             *p++ = c;
             len++;
         }
     }
     *p = 0;
     return len;
 }
Referenced by CL_CheckForIgnore(), CL_Name_g(), CL_ParseCenterPrint(), and CL_ParsePrint().
COM_StripExtension()
void COM_StripExtension (const char * in, char * out, size_t size)
Definition at line 174 of file shared.c.
 {
     char *s;
     Q_strlcpy(out, in, size);
     s = out + strlen(out);
     while (s != out) {
         if (*s == '/') {
             break;
         }
         if (*s == '.') {
             *s = 0;
             break;
         }
         s--;
     }
 }
Referenced by IconOfSkinExists(), and PlayerModel_Load().
Info_NextPair()
void Info_NextPair (const char ** string, char * key, char * value)
Definition at line 1189 of file shared.c.
 {
     char        *o;
     const char  *s;
     *value = *key = 0;
     s = *string;
     if (!s) {
         return;
     }
     if (*s == '\\')
         s++;
     if (!*s) {
         *string = NULL;
         return;
     }
     o = key;
     while (*s && *s != '\\') {
         *o++ = *s++;
     }
     *o = 0;
     if (!*s) {
         *string = NULL;
         return;
     }
     o = value;
     s++;
     while (*s && *s != '\\') {
         *o++ = *s++;
     }
     *o = 0;
     *string = s;
 }
Referenced by Info_Print(), and UI_StatusEvent().
Info_Print()
void Info_Print (const char * infostring)
Definition at line 1235 of file shared.c.
 {
     char    key[MAX_INFO_STRING];
     char    value[MAX_INFO_STRING];
     while (1) {
         Info_NextPair(&infostring, key, value);
         if (!infostring)
             break;
         if (!key[0])
             strcpy(key, "<MISSING KEY>");
         if (!value[0])
             strcpy(value, "<MISSING VALUE>");
         Com_Printf("%-20s %s\n", key, value);
     }
 }
Referenced by CL_DumpStatusResponse(), CL_Userinfo_f(), SV_DumpUser_f(), SV_Serverinfo_f(), and SV_ShowServerInfo_f().
Info_RemoveKey()
void Info_RemoveKey (char * s, const char * key)
Definition at line 991 of file shared.c.
 {
     char    *start;
     char    pkey[MAX_INFO_STRING];
     char    *o;
     while (1) {
         start = s;
         if (*s == '\\')
             s++;
         o = pkey;
         while (*s != '\\') {
             if (!*s)
                 return;
             *o++ = *s++;
         }
         *o = 0;
         s++;
         while (*s != '\\' && *s) {
             s++;
         }
         if (!strcmp(key, pkey)) {
             o = start; // remove this part
             while (*s) {
                 *o++ = *s++;
             }
             *o = 0;
             s = start;
             continue; // search for duplicates
         }
         if (!*s)
             return;
     }
 }
Referenced by Com_TestInfo_f(), Info_SetValueForKey(), and parse_userinfo().
Info_SetValueForKey()
qboolean Info_SetValueForKey (char * s, const char * key, const char * value)
Definition at line 1137 of file shared.c.
 {
     char    newi[MAX_INFO_STRING], *v;
     size_t  l, kl, vl;
     int     c;
     // validate key
     kl = Info_SubValidate(key);
     if (kl >= MAX_QPATH) {
         return qfalse;
     }
     // validate value
     vl = Info_SubValidate(value);
     if (vl >= MAX_QPATH) {
         return qfalse;
     }
     Info_RemoveKey(s, key);
     if (!vl) {
         return qtrue;
     }
     l = strlen(s);
     if (l + kl + vl + 2 >= MAX_INFO_STRING) {
         return qfalse;
     }
     newi[0] = '\\';
     memcpy(newi + 1, key, kl);
     newi[kl + 1] = '\\';
     memcpy(newi + kl + 2, value, vl + 1);
     // only copy ascii values
     s += l;
     v = newi;
     while (*v) {
         c = *v++;
         c &= 127;        // strip high bits
         if (Q_isprint(c))
             *s++ = c;
     }
     *s = 0;
     return qtrue;
 }
Referenced by ClientConnect(), Com_TestInfo_f(), parse_userinfo(), SV_ParseDeltaUserinfo(), and SV_UpdateUserinfo().
Info_SubValidate()
size_t Info_SubValidate (const char * s)
Definition at line 1112 of file shared.c.
 {
     size_t len;
     int c;
     len = 0;
     while (*s) {
         c = *s++;
         c &= 127;       // strip high bits
         if (c == '\\' || c == '\"' || c == ';') {
             return SIZE_MAX;  // illegal characters
         }
         if (++len == MAX_QPATH) {
             return MAX_QPATH;  // oversize value
         }
     }
     return len;
 }
Referenced by Info_SetValueForKey(), and validate_info_cvar().
Info_Validate()
qboolean Info_Validate (const char * s)
Definition at line 1040 of file shared.c.
 {
     size_t len, total;
     int c;
     total = 0;
     while (1) {
         //
         // validate key
         //
         if (*s == '\\') {
             s++;
             if (++total == MAX_INFO_STRING) {
                 return qfalse;    // oversize infostring
             }
         }
         if (!*s) {
             return qfalse;    // missing key
         }
         len = 0;
         while (*s != '\\') {
             c = *s++;
             if (!Q_isprint(c) || c == '\"' || c == ';') {
                 return qfalse;    // illegal characters
             }
             if (++len == MAX_INFO_KEY) {
                 return qfalse;    // oversize key
             }
             if (++total == MAX_INFO_STRING) {
                 return qfalse;    // oversize infostring
             }
             if (!*s) {
                 return qfalse;    // missing value
             }
         }
         //
         // validate value
         //
         s++;
         if (++total == MAX_INFO_STRING) {
             return qfalse;    // oversize infostring
         }
         if (!*s) {
             return qfalse;    // missing value
         }
         len = 0;
         while (*s != '\\') {
             c = *s++;
             if (!Q_isprint(c) || c == '\"' || c == ';') {
                 return qfalse;    // illegal characters
             }
             if (++len == MAX_INFO_VALUE) {
                 return qfalse;    // oversize value
             }
             if (++total == MAX_INFO_STRING) {
                 return qfalse;    // oversize infostring
             }
             if (!*s) {
                 return qtrue;    // end of string
             }
         }
     }
     return qfalse; // quiet compiler warning
 }
Referenced by CL_ParseStatusResponse(), ClientUserinfoChanged(), Com_TestInfo_f(), parse_userinfo(), and SV_UpdateUserinfo().
Info_ValueForKey()
char* Info_ValueForKey (const char * s, const char * key)
Definition at line 945 of file shared.c.
 {
     // use 4 buffers so compares work without stomping on each other
     static char value[4][MAX_INFO_STRING];
     static int  valueindex;
     char        pkey[MAX_INFO_STRING];
     char        *o;
     valueindex++;
     if (*s == '\\')
         s++;
     while (1) {
         o = pkey;
         while (*s != '\\') {
             if (!*s)
                 goto fail;
             *o++ = *s++;
         }
         *o = 0;
         s++;
         o = value[valueindex & 3];
         while (*s != '\\' && *s) {
             *o++ = *s++;
         }
         *o = 0;
         if (!strcmp(key, pkey))
             return value[valueindex & 3];
         if (!*s)
             goto fail;
         s++;
     }
 fail:
     o = value[valueindex & 3];
     *o = 0;
     return o;
 }
Referenced by ClientConnect(), ClientTeam(), ClientUserinfoChanged(), ColorForStatus(), dummy_create(), IsFemale(), IsNeutral(), MVD_GameClientUserinfoChanged(), parse_userinfo(), PutClientInServer(), spectator_respawn(), SV_UpdateUserinfo(), SV_UserinfoChanged(), SVC_DirectConnect(), and UI_StatusEvent().
Q_concat()
size_t Q_concat (char * dest, size_t size, ...)
Definition at line 758 of file shared.c.
 {
     va_list argptr;
     const char *s;
     size_t len, total = 0;
     va_start(argptr, size);
     while ((s = va_arg(argptr, const char *)) != NULL) {
         len = strlen(s);
         if (total + len < size) {
             memcpy(dest, s, len);
             dest += len;
         }
         total += len;
     }
     va_end(argptr);
     if (size) {
         *dest = 0;
     }
     return total;
 }
Referenced by bsp_mesh_register_textures(), BuildName(), check_player(), CL_AddPacketEntities(), CL_LoadClientinfo(), CL_RequestNextDownload(), Cmd_PrintHelp(), Cvar_BitInfo(), easy_open_read(), easy_open_write(), FS_LastModified(), FS_WhereIs_f(), GL_LoadWorld(), Keybind_Draw(), LoadCache(), LOC_LoadLocations(), MOD_LoadMD2_RTX(), open_file_read(), open_file_write(), override_entity_string(), parseMaterialsTable(), PlayerModel_Load(), Pop(), ProcessTexinfo(), Prompt_CompleteCommand(), q_printf(), R_BeginRegistration(), R_BeginRegistration_GL(), R_BeginRegistration_RTX(), R_RegisterImage(), R_SetSky(), R_SetSky_GL(), R_SetSky_RTX(), ReloadMedia(), S_RegisterSexedSound(), S_RegisterSound(), SCR_DrawInventory(), SV_LoadGameLibrary(), SV_ParseMapCmd(), SV_SpawnServer(), Sys_ListFiles_r(), V_Gun_Model_f(), vkpt_textures_prefetch(), and WriteCache().
Q_memccpy()
void* Q_memccpy (void * dst, const void * src, int c, size_t size)
Definition at line 895 of file shared.c.
 {
     byte *d = dst;
     const byte *s = src;
     while (size--) {
         if ((*d++ = *s++) == c) {
             return d;
         }
     }
     return NULL;
 }
Referenced by check_skins(), MOD_LoadMD2(), MOD_LoadMD2_GL(), MOD_LoadMD2_RTX(), and MOD_LoadSP2().
Q_scnprintf()
size_t Q_scnprintf (char * dest, size_t size, const char * fmt, ...)
Definition at line 867 of file shared.c.
 {
     va_list argptr;
     size_t  ret;
     va_start(argptr, fmt);
     ret = Q_vscnprintf(dest, size, fmt, argptr);
     va_end(argptr);
     return ret;
 }
Referenced by BuildList(), CL_Ammo_m(), CL_Armor_m(), CL_Cluster_m(), CL_ClusterThere_m(), CL_DemoPos_m(), CL_Fps_m(), CL_HdrColor_m(), CL_Health_m(), CL_Lag_m(), CL_Material_m(), CL_Material_Override_m(), CL_Mps_m(), CL_NumLightPolys_m(), CL_Ping_m(), CL_Pps_m(), CL_ResolutionScale_m(), CL_Timer_m(), CL_Ups_m(), CL_ViewDir_m(), CL_ViewPos_m(), CL_WeaponModel_m(), Com_FormatSize(), Com_FormatSizeLong(), Com_FormatTime(), Com_FormatTimeLong(), Com_Random_m(), Com_TestSnprintf_f(), draw_percent_bar(), format_demo_status(), GL_ViewCluster_m(), HUD_DrawNumber(), MVD_LayoutChannels(), MVD_LayoutFollow(), MVD_LayoutMenu(), NET_DnRate_m(), NET_UpRate_m(), R_Fps_m(), SVC_Info(), TH_DrawLayoutString(), TH_DrawNumber(), and VID_GetDefaultModeList().
Q_setenv()
void Q_setenv (const char * name, const char * value)
Definition at line 909 of file shared.c.
 {
 #ifdef _WIN32
     if (!value) {
         value = "";
     }
 #if (_MSC_VER >= 1400)
     _putenv_s(name, value);
 #else
     _putenv(va("%s=%s", name, value));
 #endif
 #else // _WIN32
     if (value) {
         setenv(name, value, 1);
     } else {
         unsetenv(name);
     }
 #endif // !_WIN32
 }
Q_snprintf()
size_t Q_snprintf (char * dest, size_t size, const char * fmt, ...)
Definition at line 846 of file shared.c.
 {
     va_list argptr;
     size_t  ret;
     va_start(argptr, fmt);
     ret = Q_vsnprintf(dest, size, fmt, argptr);
     va_end(argptr);
     return ret;
 }
Referenced by AC_LoadChecks(), AC_ParseViolation(), append_extra_userinfo(), bsp_mesh_create_from_bsp(), bsp_mesh_load_custom_sky(), CL_CheckForResend(), CL_IgnoreNick_f(), CL_InitLocal(), CL_MuzzleFlash(), CL_MuzzleFlash2(), CL_RegisterTEntSounds(), CL_UnIgnoreNick_f(), Cmd_PlayerList_f(), Cmd_Players_f(), Cmd_Say_f(), Com_Quit(), Com_TestSnprintf_f(), Con_DrawSolidConsole(), copy_file(), create_screenshot(), CreateTargetChangeLevel(), Cvar_ClampInteger(), Cvar_ClampValue(), Cvar_Inc_f(), Cvar_SetInteger(), Cvar_SetValue(), DeathmatchScoreboardMessage(), evaluate_reference_mode(), ExitLevel(), finish_download(), format_mask(), FS_Restart(), func_clock_format_countdown(), func_clock_think(), HelpComputer(), HTTP_QueueDownload(), HTTP_SetServer(), http_strerror(), inet_ntop4(), Key_Event(), load_sky_and_lava_clusters(), MVD_Connect_f(), MVD_GameInit(), MVD_LayoutChannels(), MVD_LayoutClients(), MVD_Play_f(), MVD_Say_f(), NET_AdrToString(), PlayDemo(), qvk_result_to_string(), read_level_file(), read_server_file(), remove_file(), scr_crosshair_changed(), SCR_DrawFPS(), SCR_DrawInventory(), SCR_ExecuteLayoutString(), SCR_PlayCinematic(), SCR_ScoreShot_f(), SkyLoadScatterParameters(), SP_target_speaker(), start_download(), SV_GetSaveInfo(), SV_ListMasters_f(), SV_StatusString(), SVCmd_WriteIP_f(), TCP_OpenSocket(), UDP_OpenSocket(), UI_Init(), UpdateStatus(), userinfo_ip_string(), VID_SetGeometry(), vtos(), write_level_file(), and write_server_file().
Q_strcasecmp()
int Q_strcasecmp (const char * s1, const char * s2)
Definition at line 666 of file shared.c.
 {
     int        c1, c2;
     do {
         c1 = *s1++;
         c2 = *s2++;
         if (c1 != c2) {
             c1 = Q_tolower(c1);
             c2 = Q_tolower(c2);
             if (c1 < c2)
                 return -1;
             if (c1 > c2)
                 return 1;        /* strings not equal */
         }
     } while (c1);
     return 0;        /* strings are equal */
 }
Referenced by CL_AddPacketEntities(), CL_InitLocal(), find_dup(), MAT_FindPBRMaterial(), and validateMaterialsTable().
Q_strcasestr()
char* Q_strcasestr (const char * s1, const char * s2)
Definition at line 687 of file shared.c.
 {
     size_t l1, l2;
     l2 = strlen(s2);
     if (!l2) {
         return (char *)s1;
     }
     l1 = strlen(s1);
     while (l1 >= l2) {
         l1--;
         if (!Q_strncasecmp(s1, s2, l2)) {
             return (char *)s1;
         }
         s1++;
     }
     return NULL;
 }
Q_strchrnul()
char* Q_strchrnul (const char * s, int c)
Definition at line 879 of file shared.c.
 {
     while (*s && *s != c) {
         s++;
     }
     return (char *)s;
 }
Referenced by AC_SimpleParse(), and CL_ParseStatusResponse().
Q_strlcat()
size_t Q_strlcat (char * dst, const char * src, size_t size)
Definition at line 735 of file shared.c.
 {
     size_t ret, len = strlen(dst);
     if (len >= size) {
         Com_Error(ERR_FATAL, "%s: already overflowed", __func__);
     }
     ret = Q_strlcpy(dst + len, src, size - len);
     ret += len;
     return ret;
 }
Referenced by Cmd_Exec_f(), COM_DefaultExtension(), easy_open_read(), and IconOfSkinExists().
Q_strlcpy()
size_t Q_strlcpy (char * dst, const char * src, size_t size)
Definition at line 715 of file shared.c.
 {
     size_t ret = strlen(src);
     if (size) {
         size_t len = ret >= size ? size - 1 : ret;
         memcpy(dst, src, len);
         dst[len] = 0;
     }
     return ret;
 }
Referenced by AC_ParseHash(), BuildName(), CL_Changing_f(), CL_CheckForIgnore(), CL_Connect_f(), CL_ConnectionlessPacket(), CL_FixUpGender(), CL_Mapname_m(), CL_Name_g(), CL_ParseStatusResponse(), CL_PlayDemo_f(), CL_RequestNextDownload(), CL_Server_m(), Cmd_ArgsBuffer(), Cmd_ArgvBuffer(), Cmd_PrintHelp(), Cmd_TokenizeString(), COM_FilePath(), Com_SetLastError(), COM_StripExtension(), Com_TestInfo_f(), create_channel(), demo_play_next(), dummy_create(), easy_open_read(), HTTP_SetServer(), IF_Replace(), LOC_Here_m(), LOC_There_m(), MOD_LoadMD2_RTX(), MVD_Connect_f(), MVD_Control_f(), MVD_GameInit(), MVD_ParseEntityString(), MVD_Play_f(), MVD_Spawn(), NET_StringToAdr(), parse_info_string(), parse_userinfo(), PlayerModel_Load(), Push(), Q_strlcat(), ReadLevel(), S_RegisterSound(), SCR_AddToChatHUD(), SCR_CenterPrint(), set_player_name(), SV_NextServer_f(), SV_SpawnServer(), SV_UserinfoChanged(), SVC_DirectConnect(), VID_GetDefaultModeList(), and vkpt_textures_prefetch().
Q_strncasecmp()
int Q_strncasecmp (const char * s1, const char * s2, size_t n)
Definition at line 642 of file shared.c.
 {
     int        c1, c2;
     do {
         c1 = *s1++;
         c2 = *s2++;
         if (!n--)
             return 0;        /* strings are equal until end point */
         if (c1 != c2) {
             c1 = Q_tolower(c1);
             c2 = Q_tolower(c2);
             if (c1 < c2)
                 return -1;
             if (c1 > c2)
                 return 1;        /* strings not equal */
         }
     } while (c1);
     return 0;        /* strings are equal */
 }
Referenced by CL_Connect_f(), Prompt_AddMatch(), and Q_strcasestr().
Q_vscnprintf()
size_t Q_vscnprintf (char * dest, size_t size, const char * fmt, va_list argptr)
Definition at line 823 of file shared.c.
 {
     size_t ret;
     if (!size)
         return 0;
     ret = Q_vsnprintf(dest, size, fmt, argptr);
     if (ret < size)
         return ret;
     return size - 1;
 }
Referenced by Com_Error(), Com_LPrintf(), and Q_scnprintf().
Q_vsnprintf()
size_t Q_vsnprintf (char * dest, size_t size, const char * fmt, va_list argptr)
Definition at line 791 of file shared.c.
 {
     int ret;
     if (size > INT_MAX)
         Com_Error(ERR_FATAL, "%s: bad buffer size", __func__);
 #ifdef _WIN32
     if (size) {
         ret = _vsnprintf(dest, size - 1, fmt, argptr);
         if (ret < 0 || ret >= size - 1)
             dest[size - 1] = 0;
     } else {
         ret = _vscprintf(fmt, argptr);
     }
 #else
     ret = vsnprintf(dest, size, fmt, argptr);
 #endif
     // exploit the fact -1 becomes SIZE_MAX > size
     return (size_t)ret;
 }
Referenced by AC_Announce(), Com_Error(), Com_LPrintf(), Con_Printf(), FS_FPrintf(), MVD_BroadcastPrintf(), MVD_Destroyf(), Netchan_OutOfBand(), PF_bprintf(), PF_centerprintf(), PF_cprintf(), PF_dprintf(), PF_error(), q_printf(), Q_snprintf(), Q_vscnprintf(), SV_BroadcastCommand(), SV_BroadcastPrintf(), SV_ClientCommand(), SV_ClientPrintf(), Sys_Error(), and va().
RadiusFromBounds()
vec_t RadiusFromBounds (const vec3_t mins, const vec3_t maxs)
Definition at line 127 of file shared.c.
 {
     int     i;
     vec3_t  corner;
     vec_t   a, b;
     for (i = 0; i < 3; i++) {
         a = Q_fabs(mins[i]);
         b = Q_fabs(maxs[i]);
         corner[i] = a > b ? a : b;
     }
     return VectorLength(corner);
 }
Referenced by LOAD(), MOD_LoadMD2_GL(), and MOD_LoadMD2_RTX().
SortStrcmp()
int SortStrcmp (const void * p1, const void * p2)
Definition at line 380 of file shared.c.
 {
     return strcmp(*(const char **)p1, *(const char **)p2);
 }
Referenced by Prompt_CompleteCommand(), and Prompt_ShowIndividualMatches().
SortStricmp()
int SortStricmp (const void * p1, const void * p2)
Definition at line 385 of file shared.c.
 {
     return Q_stricmp(*(const char **)p1, *(const char **)p2);
 }
Referenced by Prompt_CompleteCommand().
UnionBounds()
void UnionBounds (vec3_t a[2], vec3_t b[2], vec3_t c[2])
Definition at line 111 of file shared.c.
 {
     c[0][0] = b[0][0] < a[0][0] ? b[0][0] : a[0][0];
     c[0][1] = b[0][1] < a[0][1] ? b[0][1] : a[0][1];
     c[0][2] = b[0][2] < a[0][2] ? b[0][2] : a[0][2];
     c[1][0] = b[1][0] > a[1][0] ? b[1][0] : a[1][0];
     c[1][1] = b[1][1] > a[1][1] ? b[1][1] : a[1][1];
     c[1][2] = b[1][2] > a[1][2] ? b[1][2] : a[1][2];
 }
Referenced by cull_lerped_model().
va()
char* va (const char * format, ...)
Definition at line 429 of file shared.c.
 {
     va_list         argptr;
     static char     buffers[2][0x2800];
     static int      index;
     index ^= 1;
     va_start(argptr, format);
     Q_vsnprintf(buffers[index], sizeof(buffers[0]), format, argptr);
     va_end(argptr);
     return buffers[index];
 }
Referenced by Activate(), CheckNeedPass(), CL_Begin(), CL_FollowIP_f(), CL_InitDemos(), CL_InitLocal(), CL_PingServers_f(), CL_PlayDemo_f(), CL_Seek_f(), ClientUserinfoChanged(), Cmd_Option_c(), Com_Address_g(), Com_Error(), Con_Say(), Connect(), Expose(), InitGame(), InitialiseSkyCVars(), insane_die(), insane_pain(), list_save_dir(), MVD_ChangeLevel(), MVD_GameInit(), MVD_GameRunFrame(), MVD_SwitchChannel(), NET_OpenServer(), Netchan_Init(), P_DamageFeedback(), Parse_Bitmap(), ParseAddressBook(), player_die(), Pop(), Q_setenv(), QAL_Init(), R_BeginRegistration_RTX(), R_InterceptKey_RTX(), redirect(), Savegame_Push(), SCR_FinishCinematic(), SCR_PlayCinematic(), SCR_ReadNextFrame(), SCR_StopCinematic(), SP_worldspawn(), SpawnEntities(), start_udp_download(), SV_GetSaveInfo(), SV_Init(), SV_Loadgame_f(), SV_ParseMapCmd(), Sys_GetProcAddress(), Sys_LoadLibrary(), UI_Draw(), UI_ErrorEvent(), UI_StatusEvent(), vkpt_freecam_reset(), vkpt_freecam_update(), and vkpt_next_sun_preset().
VectorNormalize()
vec_t VectorNormalize (vec3_t v)
Definition at line 55 of file shared.c.
 {
     float    length, ilength;
     length = v[0] * v[0] + v[1] * v[1] + v[2] * v[2];
     length = sqrtf(length);         // FIXME
     if (length) {
         ilength = 1 / length;
         v[0] *= ilength;
         v[1] *= ilength;
         v[2] *= ilength;
     }
     return length;
 }
Referenced by actorMachineGun(), AL_AddLoopSounds(), bfg_think(), boss2_firebullet_left(), boss2_firebullet_right(), Boss2Rocket(), CheckPowerArmor(), ChickRocket(), CL_AddBeams(), CL_AddPlayerBeams(), CL_BlasterTrail(), CL_BlasterTrail2(), CL_BubbleTrail(), CL_BubbleTrail2(), CL_DebugTrail(), CL_DiminishingTrail(), CL_FlagTrail(), CL_ForceWall(), CL_Heatbeam(), CL_IonripperTrail(), CL_MonsterPlasma_Shell(), CL_Nukeblast(), CL_OldRailTrail(), CL_ParticleEffect(), CL_ParticleEffectWaterSplash(), CL_QuadTrail(), CL_RailLights(), CL_RailSpiral(), CL_RocketTrail(), CL_SmokeTrail(), CL_TagTrail(), CL_TeleportParticles(), CL_Tracker_Explode(), CL_Tracker_Shell(), CL_TrackerTrail(), CL_TrapParticles(), CL_Widowbeamout(), CL_WidowSplash(), collect_ligth_polys(), compute_world_tangents(), fire_blaster(), fire_hit(), fire_lead(), func_explosive_explode(), get_triangle_off_center(), GladiatorGun(), GunnerFire(), InfantryMachineGun(), infront(), jorg_firebullet_left(), jorg_firebullet_right(), jorgBFG(), light_affects_cluster(), makronBFG(), MakronRailgun(), MakronSpawn(), MOD_LoadMD2_RTX(), Move_Calc(), mutant_jump_touch(), P_DamageFeedback(), PM_AirMove(), PM_CheckSpecialMovement(), PM_DeadMove(), PM_FlyMove(), PM_WaterMove(), prepare_camera(), R_DrawBeam(), R_IMFlatShadedQuad(), R_ViewChanged(), soldier_fire(), supertankMachineGun(), supertankRocket(), T_Damage(), TankRocket(), target_laser_think(), UpdateChaseCam(), vkpt_build_beam_lights(), vkpt_build_cylinder_light(), vkpt_normalize_normal_map(), vkpt_physical_sky_update_ubo(), vkpt_shadow_map_setup(), write_beam_geometry(), write_particle_geometry(), and write_sprite_geometry().
VectorNormalize2()
vec_t VectorNormalize2 (vec3_t v, vec3_t out)
Definition at line 73 of file shared.c.
 {
     float    length, ilength;
     length = v[0] * v[0] + v[1] * v[1] + v[2] * v[2];
     length = sqrtf(length);         // FIXME
     if (length) {
         ilength = 1 / length;
         out[0] = v[0] * ilength;
         out[1] = v[1] * ilength;
         out[2] = v[2] * ilength;
     }
     return length;
 }
Referenced by compute_world_tangents(), computeTangents(), create_look_at_matrix(), R_SetSky_GL(), and R_SetSky_RTX().
Variable Documentation
com_token
char com_token[4][MAX_TOKEN_CHARS] static
Definition at line 444 of file shared.c.
Referenced by COM_Parse(), and SpawnEntities().
com_tokidx
int com_tokidx static
Definition at line 445 of file shared.c.
Referenced by COM_Parse().
vec3_origin
vec3_t vec3_origin = { 0, 0, 0 }
Definition at line 21 of file shared.c.
Referenced by AngleMove_Final(), bfg_explode(), bfg_think(), blaster_touch(), CanDamage(), CL_AddPlayerBeams(), CL_WidowSplash(), Cmd_Kill_f(), CopyToBodyQue(), D_DrawSurfaces(), door_blocked(), door_secret_blocked(), door_secret_move6(), door_secret_use(), fire_hit(), flare_sparks(), floater_zap(), func_explosive_use(), func_object_touch(), Grenade_Explode(), hurt_touch(), InitTrigger(), KillBox(), LOC_FindClosest(), LOC_There_m(), M_CheckBottom(), M_WorldEffects(), MakronSpawn(), MVD_HitPlayer(), P_FallingDamage(), P_WorldEffects(), parasite_drain_attack(), plat_blocked(), PM_FlyMove(), PM_StepSlideMove_(), R_DrawEntities(), rotating_blocked(), rotating_touch(), rotating_use(), SP_trigger_multiple(), SV_FlyMove(), SV_Physics_Toss(), SV_Push(), SV_Trace(), T_RadiusDamage(), target_laser_think(), Touch_Multi(), train_blocked(), turret_blocked(), UpdateChaseCam(), use_target_changelevel(), visible(), and Weapon_Blaster_Fire().