Quake II RTX doxygen: C:/entry/dev/Q2RTX/src/refresh/gl/qgl/dynamic.c File Reference
dynamic.c File Reference
#include "shared/shared.h"
#include "common/common.h"
#include "client/video.h"
#include "dynamic.h"
Macros
#define QGL(x) qgl##x##_t qgl##x
#define QGL(x) qgl##x = NULL
#define GCA(x) VID_GetCoreAddr("gl"#x)
#define GPA(x) VID_GetProcAddr("gl"#x)
#define QGL(x) if ((qgl##x = GCA(x)) == NULL) return qfalse;
#define QGL(x) qgl##x = GPA(x)
Functions
void QGL_Shutdown (void)
void QGL_ShutdownExtensions (unsigned mask)
qboolean QGL_Init (void)
void QGL_InitExtensions (unsigned mask)
unsigned QGL_ParseExtensionString (const char *s)
Variables
QGL_core_IMP QGL_ARB_fragment_program_IMP QGL_ARB_multitexture_IMP QGL_ARB_vertex_buffer_object_IMP QGL_EXT_compiled_vertex_array_IMP qglGenerateMipmap_t qglGenerateMipmap
Macro Definition Documentation
GCA
#define GCA (x) VID_GetCoreAddr("gl"#x)
Definition at line 667 of file dynamic.c.
GPA
#define GPA (x) VID_GetProcAddr("gl"#x)
Definition at line 668 of file dynamic.c.
QGL [1/4]
#define QGL (x) qgl##x##_t qgl##x
Definition at line 26 of file dynamic.c.
QGL [2/4]
#define QGL (x) qgl##x = NULL
Definition at line 26 of file dynamic.c.
QGL [3/4]
#define QGL (x) if ((qgl##x = GCA(x)) == NULL) return qfalse;
Definition at line 26 of file dynamic.c.
QGL [4/4]
#define QGL (x) qgl##x = GPA(x)
Definition at line 26 of file dynamic.c.
Function Documentation
QGL_Init()
qboolean QGL_Init (void)
Definition at line 670 of file dynamic.c.
 {
 #ifdef _DEBUG
 #define QGL(x)  if ((qgl##x = dll##x = GCA(x)) == NULL) return qfalse;
 #else
 #define QGL(x)  if ((qgl##x = GCA(x)) == NULL)          return qfalse;
 #endif
     QGL_core_IMP
 #undef QGL
     return qtrue;
 }
QGL_InitExtensions()
void QGL_InitExtensions (unsigned mask)
Definition at line 683 of file dynamic.c.
 {
 #ifdef _DEBUG
 #define QGL(x)  qgl##x = dll##x = GPA(x)
 #else
 #define QGL(x)  qgl##x = GPA(x)
 #endif
     if (mask & QGL_ARB_fragment_program) {
         QGL_ARB_fragment_program_IMP
     }
     if (mask & QGL_ARB_multitexture) {
         QGL_ARB_multitexture_IMP
     }
     if (mask & QGL_ARB_vertex_buffer_object) {
         QGL_ARB_vertex_buffer_object_IMP
     }
     if (mask & QGL_EXT_compiled_vertex_array) {
         QGL_EXT_compiled_vertex_array_IMP
     }
     if (mask & QGL_3_0_core_functions) {
         qglGenerateMipmap = GPA(GenerateMipmap);
     }
 #undef QGL
 }
Referenced by GL_InitPrograms(), GL_PostInit(), and GL_SetupConfig().
QGL_ParseExtensionString()
unsigned QGL_ParseExtensionString (const char * s)
Definition at line 712 of file dynamic.c.
 {
     // must match defines in dynamic.h!
     static const char *const extnames[] = {
         "GL_ARB_fragment_program",
         "GL_ARB_multitexture",
         "GL_ARB_vertex_buffer_object",
         "GL_EXT_compiled_vertex_array",
         "GL_EXT_texture_filter_anisotropic",
         NULL
     };
     return Com_ParseExtensionString(s, extnames);
 }
Referenced by GL_SetupConfig().
QGL_Shutdown()
void QGL_Shutdown (void)
Definition at line 631 of file dynamic.c.
 {
 #ifdef _DEBUG
 #define QGL(x)  qgl##x = dll##x = NULL
 #else
 #define QGL(x)  qgl##x = NULL
 #endif
     QGL_core_IMP
     QGL_ShutdownExtensions(~0);
 }
QGL_ShutdownExtensions()
void QGL_ShutdownExtensions (unsigned mask)
Definition at line 643 of file dynamic.c.
 {
     if (mask & QGL_ARB_fragment_program) {
         QGL_ARB_fragment_program_IMP
     }
     if (mask & QGL_ARB_multitexture) {
         QGL_ARB_multitexture_IMP
     }
     if (mask & QGL_ARB_vertex_buffer_object) {
         QGL_ARB_vertex_buffer_object_IMP
     }
     if (mask & QGL_EXT_compiled_vertex_array) {
         QGL_EXT_compiled_vertex_array_IMP
     }
     if (mask & QGL_3_0_core_functions) {
         qglGenerateMipmap = NULL;
     }
 #undef QGL
 }
Referenced by GL_ShutdownPrograms(), QGL_Shutdown(), and R_Shutdown_GL().
Variable Documentation
qglGenerateMipmap
QGL_core_IMP QGL_ARB_fragment_program_IMP QGL_ARB_multitexture_IMP QGL_ARB_vertex_buffer_object_IMP QGL_EXT_compiled_vertex_array_IMP qglGenerateMipmap_t qglGenerateMipmap
Definition at line 34 of file dynamic.c.
Referenced by GL_Upload32(), QGL_InitExtensions(), and QGL_ShutdownExtensions().