Quake II RTX doxygen: C:/entry/dev/Q2RTX/src/refresh/vkpt/matrix.c File Reference
matrix.c File Reference
#include "vkpt.h"
Functions
void create_entity_matrix (float matrix[16], entity_t *e, qboolean enable_left_hand)
void create_projection_matrix (float matrix[16], float znear, float zfar, float fov_x, float fov_y)
void create_orthographic_matrix (float matrix[16], float xmin, float xmax, float ymin, float ymax, float znear, float zfar)
void create_view_matrix (float matrix[16], refdef_t *fd)
void inverse (const float *m, float *inv)
void mult_matrix_matrix (float *p, const float *a, const float *b)
void mult_matrix_vector (float *p, const float *a, const float *b)
Function Documentation
create_entity_matrix()
void create_entity_matrix (float matrix[16], entity_t * e, qboolean enable_left_hand)
Definition at line 23 of file matrix.c.
 {
     vec3_t axis[3];
     vec3_t origin;
     origin[0] = (1.f-e->backlerp) * e->origin[0] + e->backlerp * e->oldorigin[0];
     origin[1] = (1.f-e->backlerp) * e->origin[1] + e->backlerp * e->oldorigin[1];
     origin[2] = (1.f-e->backlerp) * e->origin[2] + e->backlerp * e->oldorigin[2];
     AnglesToAxis(e->angles, axis);
     float scale = (e->scale > 0.f) ? e->scale : 1.f;
     vec3_t scales = { scale, scale, scale };
     if ((e->flags & RF_LEFTHAND) && enable_left_hand)
     {
         scales[1] *= -1.f;
     }
     matrix[0]  = axis[0][0] * scales[0];
     matrix[4]  = axis[1][0] * scales[1];
     matrix[8]  = axis[2][0] * scales[2];
     matrix[12] = origin[0];
     matrix[1]  = axis[0][1] * scales[0];
     matrix[5]  = axis[1][1] * scales[1];
     matrix[9]  = axis[2][1] * scales[2];
     matrix[13] = origin[1];
     matrix[2]  = axis[0][2] * scales[0];
     matrix[6]  = axis[1][2] * scales[1];
     matrix[10] = axis[2][2] * scales[2];
     matrix[14] = origin[2];
     matrix[3]  = 0.0f;
     matrix[7]  = 0.0f;
     matrix[11] = 0.0f;
     matrix[15] = 1.0f;
 }
Referenced by process_bsp_entity(), and process_regular_entity().
create_orthographic_matrix()
void create_orthographic_matrix (float matrix[16], float xmin, float xmax, float ymin, float ymax, float znear, float zfar)
Definition at line 100 of file matrix.c.
 {
     float width, height, depth;
     width = xmax - xmin;
     height = ymax - ymin;
     depth = zfar - znear;
     matrix[0] = 2 / width;
     matrix[4] = 0;
     matrix[8] = 0;
     matrix[12] = -(xmax + xmin) / width;
     matrix[1] = 0;
     matrix[5] = 2 / height;
     matrix[9] = 0;
     matrix[13] = -(ymax + ymin) / height;
     matrix[2] = 0;
     matrix[6] = 0;
     matrix[10] = 1 / depth;
     matrix[14] = -znear / depth;
     matrix[3] = 0;
     matrix[7] = 0;
     matrix[11] = 0;
     matrix[15] = 1;
 }
Referenced by vkpt_shadow_map_setup().
create_projection_matrix()
void create_projection_matrix (float matrix[16], float znear, float zfar, float fov_x, float fov_y)
Definition at line 63 of file matrix.c.
 {
     float xmin, xmax, ymin, ymax;
     float width, height, depth;
     ymax = znear * tan(fov_y * M_PI / 360.0);
     ymin = -ymax;
     xmax = znear * tan(fov_x * M_PI / 360.0);
     xmin = -xmax;
     width = xmax - xmin;
     height = ymax - ymin;
     depth = zfar - znear;
     matrix[0] = 2 * znear / width;
     matrix[4] = 0;
     matrix[8] = (xmax + xmin) / width;
     matrix[12] = 0;
     matrix[1] = 0;
     matrix[5] = -2 * znear / height;
     matrix[9] = (ymax + ymin) / height;
     matrix[13] = 0;
     matrix[2] = 0;
     matrix[6] = 0;
     matrix[10] = (zfar + znear) / depth;
     matrix[14] = 2 * zfar * znear / depth;
     matrix[3] = 0;
     matrix[7] = 0;
     matrix[11] = 1;
     matrix[15] = 0;
 }
Referenced by prepare_ubo().
create_view_matrix()
void create_view_matrix (float matrix[16], refdef_t * fd)
Definition at line 131 of file matrix.c.
 {
     vec3_t viewaxis[3];
     AnglesToAxis(fd->viewangles, viewaxis);
     matrix[0]  = -viewaxis[1][0];
     matrix[4]  = -viewaxis[1][1];
     matrix[8]  = -viewaxis[1][2];
     matrix[12] = DotProduct(viewaxis[1], fd->vieworg);
     matrix[1]  = viewaxis[2][0];
     matrix[5]  = viewaxis[2][1];
     matrix[9]  = viewaxis[2][2];
     matrix[13] = -DotProduct(viewaxis[2], fd->vieworg);
     matrix[2]  = viewaxis[0][0];
     matrix[6]  = viewaxis[0][1];
     matrix[10] = viewaxis[0][2];
     matrix[14] = -DotProduct(viewaxis[0], fd->vieworg);
     matrix[3]  = 0;
     matrix[7]  = 0;
     matrix[11] = 0;
     matrix[15] = 1;
 }
Referenced by prepare_ubo().
inverse()
void inverse (const float * m, float * inv)
Definition at line 158 of file matrix.c.
 {
     inv[0] = m[5]  * m[10] * m[15] -
              m[5]  * m[11] * m[14] -
              m[9]  * m[6]  * m[15] +
              m[9]  * m[7]  * m[14] +
              m[13] * m[6]  * m[11] -
              m[13] * m[7]  * m[10];
     inv[1] = -m[1]  * m[10] * m[15] +
               m[1]  * m[11] * m[14] +
               m[9]  * m[2] * m[15] -
               m[9]  * m[3] * m[14] -
               m[13] * m[2] * m[11] +
               m[13] * m[3] * m[10];
     inv[2] = m[1]  * m[6] * m[15] -
              m[1]  * m[7] * m[14] -
              m[5]  * m[2] * m[15] +
              m[5]  * m[3] * m[14] +
              m[13] * m[2] * m[7] -
              m[13] * m[3] * m[6];
     inv[3] = -m[1] * m[6] * m[11] +
               m[1] * m[7] * m[10] +
               m[5] * m[2] * m[11] -
               m[5] * m[3] * m[10] -
               m[9] * m[2] * m[7] +
               m[9] * m[3] * m[6];
     inv[4] = -m[4]  * m[10] * m[15] +
               m[4]  * m[11] * m[14] +
               m[8]  * m[6]  * m[15] -
               m[8]  * m[7]  * m[14] -
               m[12] * m[6]  * m[11] +
               m[12] * m[7]  * m[10];
     inv[5] = m[0]  * m[10] * m[15] -
              m[0]  * m[11] * m[14] -
              m[8]  * m[2] * m[15] +
              m[8]  * m[3] * m[14] +
              m[12] * m[2] * m[11] -
              m[12] * m[3] * m[10];
     inv[6] = -m[0]  * m[6] * m[15] +
               m[0]  * m[7] * m[14] +
               m[4]  * m[2] * m[15] -
               m[4]  * m[3] * m[14] -
               m[12] * m[2] * m[7] +
               m[12] * m[3] * m[6];
     inv[7] = m[0] * m[6] * m[11] -
              m[0] * m[7] * m[10] -
              m[4] * m[2] * m[11] +
              m[4] * m[3] * m[10] +
              m[8] * m[2] * m[7] -
              m[8] * m[3] * m[6];
     inv[8] = m[4]  * m[9] * m[15] -
              m[4]  * m[11] * m[13] -
              m[8]  * m[5] * m[15] +
              m[8]  * m[7] * m[13] +
              m[12] * m[5] * m[11] -
              m[12] * m[7] * m[9];
     inv[9] = -m[0]  * m[9] * m[15] +
               m[0]  * m[11] * m[13] +
               m[8]  * m[1] * m[15] -
               m[8]  * m[3] * m[13] -
               m[12] * m[1] * m[11] +
               m[12] * m[3] * m[9];
     inv[10] = m[0]  * m[5] * m[15] -
               m[0]  * m[7] * m[13] -
               m[4]  * m[1] * m[15] +
               m[4]  * m[3] * m[13] +
               m[12] * m[1] * m[7] -
               m[12] * m[3] * m[5];
     inv[11] = -m[0] * m[5] * m[11] +
                m[0] * m[7] * m[9] +
                m[4] * m[1] * m[11] -
                m[4] * m[3] * m[9] -
                m[8] * m[1] * m[7] +
                m[8] * m[3] * m[5];
     inv[12] = -m[4]  * m[9] * m[14] +
                m[4]  * m[10] * m[13] +
                m[8]  * m[5] * m[14] -
                m[8]  * m[6] * m[13] -
                m[12] * m[5] * m[10] +
                m[12] * m[6] * m[9];
     inv[13] = m[0]  * m[9] * m[14] -
               m[0]  * m[10] * m[13] -
               m[8]  * m[1] * m[14] +
               m[8]  * m[2] * m[13] +
               m[12] * m[1] * m[10] -
               m[12] * m[2] * m[9];
     inv[14] = -m[0]  * m[5] * m[14] +
                m[0]  * m[6] * m[13] +
                m[4]  * m[1] * m[14] -
                m[4]  * m[2] * m[13] -
                m[12] * m[1] * m[6] +
                m[12] * m[2] * m[5];
     inv[15] = m[0] * m[5] * m[10] -
               m[0] * m[6] * m[9] -
               m[4] * m[1] * m[10] +
               m[4] * m[2] * m[9] +
               m[8] * m[1] * m[6] -
               m[8] * m[2] * m[5];
     float det = m[0] * inv[0] + m[1] * inv[4] + m[2] * inv[8] + m[3] * inv[12];
     det = 1.0f / det;
     for(int i = 0; i < 16; i++)
         inv[i] = inv[i] * det;
 }
Referenced by prepare_ubo().
mult_matrix_matrix()
void mult_matrix_matrix (float * p, const float * a, const float * b)
Definition at line 281 of file matrix.c.
 {
     for(int i = 0; i < 4; i++) {
         for(int j = 0; j < 4; j++) {
             p[i * 4 + j] =
                 a[0 * 4 + j] * b[i * 4 + 0] +
                 a[1 * 4 + j] * b[i * 4 + 1] +
                 a[2 * 4 + j] * b[i * 4 + 2] +
                 a[3 * 4 + j] * b[i * 4 + 3];
         }
     }
 }
Referenced by prepare_ubo(), UpdateTerrainShadowMapView(), and vkpt_shadow_map_setup().
mult_matrix_vector()
void mult_matrix_vector (float * p, const float * a, const float * b)
Definition at line 295 of file matrix.c.
 {
     int j;
     for (j = 0; j < 4; j++) {
         p[j] =
             a[0 * 4 + j] * b[0] +
             a[1 * 4 + j] * b[1] +
             a[2 * 4 + j] * b[2] +
             a[3 * 4 + j] * b[3];
     }
 }
Referenced by process_regular_entity(), transform_point(), and vkpt_shadow_map_setup().