Quake II RTX doxygen: C:/entry/dev/Q2RTX/src/windows/ascii.c File Reference
ascii.c File Reference
#include <windows.h>
Functions
HANDLE WINAPI FindFirstFileA (LPCSTR path, LPWIN32_FIND_DATAA data)
BOOL WINAPI FindNextFileA (HANDLE handle, LPWIN32_FIND_DATAA data)
HINSTANCE WINAPI LoadLibraryA (LPCSTR path)
int WINAPI MessageBoxA (HWND hWnd, LPCSTR lpText, LPCSTR lpCaption, UINT uType)
BOOL WINAPI CreateDirectoryA (LPCSTR lpPathName, LPSECURITY_ATTRIBUTES lpSecurityAttributes)
BOOL WINAPI GetFileAttributesExA (LPCSTR lpFileName, GET_FILEEX_INFO_LEVELS fInfoLevelId, LPVOID lpFileInformation)
DWORD WINAPI GetModuleFileNameA (HMODULE hModule, LPSTR lpFileName, DWORD nSize)
Function Documentation
CreateDirectoryA()
BOOL WINAPI CreateDirectoryA (LPCSTR lpPathName, LPSECURITY_ATTRIBUTES lpSecurityAttributes)
Definition at line 62 of file ascii.c.
 {
     WCHAR wbuffer[MAX_PATH];
     if (!MultiByteToWideChar(CP_ACP, 0, lpPathName, -1, wbuffer, MAX_PATH)) {
         return FALSE;
     }
     return CreateDirectoryW(wbuffer, lpSecurityAttributes);
 }
FindFirstFileA()
HANDLE WINAPI FindFirstFileA (LPCSTR path, LPWIN32_FIND_DATAA data)
Definition at line 3 of file ascii.c.
 {
     WCHAR wbuffer[MAX_PATH];
     HANDLE ret;
     WIN32_FIND_DATAW wdata;
     if (!MultiByteToWideChar(CP_ACP, 0, path, -1, wbuffer, MAX_PATH)) {
         return INVALID_HANDLE_VALUE;
     }
     ret = FindFirstFileW(wbuffer, &wdata);
     if (ret != INVALID_HANDLE_VALUE) {
         memcpy(data, &wdata, FIELD_OFFSET(WIN32_FIND_DATAA, cFileName));
         WideCharToMultiByte(CP_ACP, 0, wdata.cFileName, -1, data->cFileName, MAX_PATH, NULL, NULL);
     }
     return ret;
 }
Referenced by Sys_ListFiles_r().
FindNextFileA()
BOOL WINAPI FindNextFileA (HANDLE handle, LPWIN32_FIND_DATAA data)
Definition at line 22 of file ascii.c.
 {
     BOOL ret;
     WIN32_FIND_DATAW wdata;
     ret = FindNextFileW(handle, &wdata);
     if (ret != FALSE) {
         memcpy(data, &wdata, FIELD_OFFSET(WIN32_FIND_DATAA, cFileName));
         WideCharToMultiByte(CP_ACP, 0, wdata.cFileName, -1, data->cFileName, MAX_PATH, NULL, NULL);
     }
     return ret;
 }
Referenced by Sys_ListFiles_r().
GetFileAttributesExA()
BOOL WINAPI GetFileAttributesExA (LPCSTR lpFileName, GET_FILEEX_INFO_LEVELS fInfoLevelId, LPVOID lpFileInformation)
Definition at line 73 of file ascii.c.
 {
     WCHAR wbuffer[MAX_PATH];
     if (!MultiByteToWideChar(CP_ACP, 0, lpFileName, -1, wbuffer, MAX_PATH)) {
         return FALSE;
     }
     return GetFileAttributesExW(wbuffer, fInfoLevelId, lpFileInformation);
 }
GetModuleFileNameA()
DWORD WINAPI GetModuleFileNameA (HMODULE hModule, LPSTR lpFileName, DWORD nSize)
Definition at line 84 of file ascii.c.
 {
     WCHAR wbuffer[MAX_PATH];
     DWORD ret;
     if (nSize > MAX_PATH) {
         nSize = MAX_PATH;
     }
     ret = GetModuleFileNameW(hModule, wbuffer, nSize);
     if (ret) {
         if (!WideCharToMultiByte(CP_ACP, 0, wbuffer, ret, lpFileName, ret, NULL, NULL)) {
             return 0;
         }
     }
     return ret;
 }
Referenced by fix_current_directory().
LoadLibraryA()
HINSTANCE WINAPI LoadLibraryA (LPCSTR path)
Definition at line 36 of file ascii.c.
 {
     WCHAR wbuffer[MAX_PATH];
     if (!MultiByteToWideChar(CP_ACP, 0, path, -1, wbuffer, MAX_PATH)) {
         return NULL;
     }
     return LoadLibraryW(wbuffer);
 }
Referenced by Sys_LoadLibrary().
MessageBoxA()
int WINAPI MessageBoxA (HWND hWnd, LPCSTR lpText, LPCSTR lpCaption, UINT uType)
Definition at line 47 of file ascii.c.
 {
     WCHAR wText[4096];
     WCHAR wCaption[256];
     if (!MultiByteToWideChar(CP_ACP, 0, lpText, -1, wText, 4096)) {
         return 0;
     }
     if (!MultiByteToWideChar(CP_ACP, 0, lpCaption, -1, wCaption, 256)) {
         return 0;
     }
     return MessageBoxW(hWnd, wText, wCaption, uType);
 }
Referenced by Sys_Error().