Quake II RTX doxygen: C:/entry/dev/Q2RTX/src/baseq2/m_supertank.c File Reference
m_supertank.c File Reference
#include "g_local.h"
#include "m_supertank.h"
Functions
qboolean visible (edict_t *self, edict_t *other)
void BossExplode (edict_t *self)
void TreadSound (edict_t *self)
void supertank_search (edict_t *self)
void supertank_dead (edict_t *self)
void supertankRocket (edict_t *self)
void supertankMachineGun (edict_t *self)
void supertank_reattack1 (edict_t *self)
void supertank_stand (edict_t *self)
void supertank_forward (edict_t *self)
void supertank_walk (edict_t *self)
void supertank_run (edict_t *self)
void supertank_pain (edict_t *self, edict_t *other, float kick, int damage)
void supertank_attack (edict_t *self)
void supertank_die (edict_t *self, edict_t *inflictor, edict_t *attacker, int damage, vec3_t point)
void SP_monster_supertank (edict_t *self)
Variables
static int sound_pain1
static int sound_pain2
static int sound_pain3
static int sound_death
static int sound_search1
static int sound_search2
static int tread_sound
mframe_t supertank_frames_stand []
mmove_t supertank_move_stand = {FRAME_stand_1, FRAME_stand_60, supertank_frames_stand, NULL}
mframe_t supertank_frames_run []
mmove_t supertank_move_run = {FRAME_forwrd_1, FRAME_forwrd_18, supertank_frames_run, NULL}
mframe_t supertank_frames_forward []
mmove_t supertank_move_forward = {FRAME_forwrd_1, FRAME_forwrd_18, supertank_frames_forward, NULL}
mframe_t supertank_frames_turn_right []
mmove_t supertank_move_turn_right = {FRAME_right_1, FRAME_right_18, supertank_frames_turn_right, supertank_run}
mframe_t supertank_frames_turn_left []
mmove_t supertank_move_turn_left = {FRAME_left_1, FRAME_left_18, supertank_frames_turn_left, supertank_run}
mframe_t supertank_frames_pain3 []
mmove_t supertank_move_pain3 = {FRAME_pain3_9, FRAME_pain3_12, supertank_frames_pain3, supertank_run}
mframe_t supertank_frames_pain2 []
mmove_t supertank_move_pain2 = {FRAME_pain2_5, FRAME_pain2_8, supertank_frames_pain2, supertank_run}
mframe_t supertank_frames_pain1 []
mmove_t supertank_move_pain1 = {FRAME_pain1_1, FRAME_pain1_4, supertank_frames_pain1, supertank_run}
mframe_t supertank_frames_death1 []
mmove_t supertank_move_death = {FRAME_death_1, FRAME_death_24, supertank_frames_death1, supertank_dead}
mframe_t supertank_frames_backward []
mmove_t supertank_move_backward = {FRAME_backwd_1, FRAME_backwd_18, supertank_frames_backward, NULL}
mframe_t supertank_frames_attack4 []
mmove_t supertank_move_attack4 = {FRAME_attak4_1, FRAME_attak4_6, supertank_frames_attack4, supertank_run}
mframe_t supertank_frames_attack3 []
mmove_t supertank_move_attack3 = {FRAME_attak3_1, FRAME_attak3_27, supertank_frames_attack3, supertank_run}
mframe_t supertank_frames_attack2 []
mmove_t supertank_move_attack2 = {FRAME_attak2_1, FRAME_attak2_27, supertank_frames_attack2, supertank_run}
mframe_t supertank_frames_attack1 []
mmove_t supertank_move_attack1 = {FRAME_attak1_1, FRAME_attak1_6, supertank_frames_attack1, supertank_reattack1}
mframe_t supertank_frames_end_attack1 []
mmove_t supertank_move_end_attack1 = {FRAME_attak1_7, FRAME_attak1_20, supertank_frames_end_attack1, supertank_run}
Function Documentation
BossExplode()
void BossExplode (edict_t * self)
Definition at line 569 of file m_supertank.c.
 {
     vec3_t  org;
     int     n;
     self->think = BossExplode;
     VectorCopy(self->s.origin, org);
     org[2] += 24 + (rand() & 15);
     switch (self->count++) {
     case 0:
         org[0] -= 24;
         org[1] -= 24;
         break;
     case 1:
         org[0] += 24;
         org[1] += 24;
         break;
     case 2:
         org[0] += 24;
         org[1] -= 24;
         break;
     case 3:
         org[0] -= 24;
         org[1] += 24;
         break;
     case 4:
         org[0] -= 48;
         org[1] -= 48;
         break;
     case 5:
         org[0] += 48;
         org[1] += 48;
         break;
     case 6:
         org[0] -= 48;
         org[1] += 48;
         break;
     case 7:
         org[0] += 48;
         org[1] -= 48;
         break;
     case 8:
         self->s.sound = 0;
         for (n = 0; n < 4; n++)
             ThrowGib(self, "models/objects/gibs/sm_meat/tris.md2", 500, GIB_ORGANIC);
         for (n = 0; n < 8; n++)
             ThrowGib(self, "models/objects/gibs/sm_metal/tris.md2", 500, GIB_METALLIC);
         ThrowGib(self, "models/objects/gibs/chest/tris.md2", 500, GIB_ORGANIC);
         ThrowHead(self, "models/objects/gibs/gear/tris.md2", 500, GIB_METALLIC);
         self->deadflag = DEAD_DEAD;
         return;
     }
     gi.WriteByte(svc_temp_entity);
     gi.WriteByte(TE_EXPLOSION1);
     gi.WritePosition(org);
     gi.multicast(self->s.origin, MULTICAST_PVS);
     self->nextthink = level.time + 0.1;
 }
SP_monster_supertank()
void SP_monster_supertank (edict_t * self)
Definition at line 646 of file m_supertank.c.
 {
     if (deathmatch->value) {
         G_FreeEdict(self);
         return;
     }
     sound_pain1 = gi.soundindex("bosstank/btkpain1.wav");
     sound_pain2 = gi.soundindex("bosstank/btkpain2.wav");
     sound_pain3 = gi.soundindex("bosstank/btkpain3.wav");
     sound_death = gi.soundindex("bosstank/btkdeth1.wav");
     sound_search1 = gi.soundindex("bosstank/btkunqv1.wav");
     sound_search2 = gi.soundindex("bosstank/btkunqv2.wav");
 //  self->s.sound = gi.soundindex ("bosstank/btkengn1.wav");
     tread_sound = gi.soundindex("bosstank/btkengn1.wav");
     self->movetype = MOVETYPE_STEP;
     self->solid = SOLID_BBOX;
     self->s.modelindex = gi.modelindex("models/monsters/boss1/tris.md2");
     VectorSet(self->mins, -64, -64, 0);
     VectorSet(self->maxs, 64, 64, 112);
     self->health = 1500;
     self->gib_health = -500;
     self->mass = 800;
     self->pain = supertank_pain;
     self->die = supertank_die;
     self->monsterinfo.stand = supertank_stand;
     self->monsterinfo.walk = supertank_walk;
     self->monsterinfo.run = supertank_run;
     self->monsterinfo.dodge = NULL;
     self->monsterinfo.attack = supertank_attack;
     self->monsterinfo.search = supertank_search;
     self->monsterinfo.melee = NULL;
     self->monsterinfo.sight = NULL;
     gi.linkentity(self);
     self->monsterinfo.currentmove = &supertank_move_stand;
     self->monsterinfo.scale = MODEL_SCALE;
     walkmonster_start(self);
 }
supertank_attack()
void supertank_attack (edict_t * self)
Definition at line 528 of file m_supertank.c.
 {
     vec3_t  vec;
     float   range;
     //float r;
     VectorSubtract(self->enemy->s.origin, self->s.origin, vec);
     range = VectorLength(vec);
     //r = random();
     // Attack 1 == Chaingun
     // Attack 2 == Rocket Launcher
     if (range <= 160) {
         self->monsterinfo.currentmove = &supertank_move_attack1;
     } else {
         // fire rockets more often at distance
         if (random() < 0.3)
             self->monsterinfo.currentmove = &supertank_move_attack1;
         else
             self->monsterinfo.currentmove = &supertank_move_attack2;
     }
 }
Referenced by SP_monster_supertank().
supertank_dead()
void supertank_dead (edict_t * self)
Definition at line 558 of file m_supertank.c.
 {
     VectorSet(self->mins, -60, -60, 0);
     VectorSet(self->maxs, 60, 60, 72);
     self->movetype = MOVETYPE_TOSS;
     self->svflags |= SVF_DEADMONSTER;
     self->nextthink = 0;
     gi.linkentity(self);
 }
supertank_die()
void supertank_die (edict_t * self, edict_t * inflictor, edict_t * attacker, int damage, vec3_t point)
Definition at line 631 of file m_supertank.c.
 {
     gi.sound(self, CHAN_VOICE, sound_death, 1, ATTN_NORM, 0);
     self->deadflag = DEAD_DEAD;
     self->takedamage = DAMAGE_NO;
     self->count = 0;
     self->monsterinfo.currentmove = &supertank_move_death;
 }
Referenced by SP_monster_supertank().
supertank_forward()
void supertank_forward (edict_t * self)
Definition at line 185 of file m_supertank.c.
 {
     self->monsterinfo.currentmove = &supertank_move_forward;
 }
supertank_pain()
void supertank_pain (edict_t * self, edict_t * other, float kick, int damage)
Definition at line 435 of file m_supertank.c.
 {
     if (self->health < (self->max_health / 2))
         self->s.skinnum = 1;
     if (level.time < self->pain_debounce_time)
         return;
     // Lessen the chance of him going into his pain frames
     if (damage <= 25)
         if (random() < 0.2)
             return;
     // Don't go into pain if he's firing his rockets
     if (skill->value >= 2)
         if ((self->s.frame >= FRAME_attak2_1) && (self->s.frame <= FRAME_attak2_14))
             return;
     self->pain_debounce_time = level.time + 3;
     if (skill->value == 3)
         return;     // no pain anims in nightmare
     if (damage <= 10) {
         gi.sound(self, CHAN_VOICE, sound_pain1, 1, ATTN_NORM, 0);
         self->monsterinfo.currentmove = &supertank_move_pain1;
     } else if (damage <= 25) {
         gi.sound(self, CHAN_VOICE, sound_pain3, 1, ATTN_NORM, 0);
         self->monsterinfo.currentmove = &supertank_move_pain2;
     } else {
         gi.sound(self, CHAN_VOICE, sound_pain2, 1, ATTN_NORM, 0);
         self->monsterinfo.currentmove = &supertank_move_pain3;
     }
 }
Referenced by SP_monster_supertank().
supertank_reattack1()
void supertank_reattack1 (edict_t * self)
Definition at line 424 of file m_supertank.c.
 {
     if (visible(self, self->enemy))
         if (random() < 0.9)
             self->monsterinfo.currentmove = &supertank_move_attack1;
         else
             self->monsterinfo.currentmove = &supertank_move_end_attack1;
     else
         self->monsterinfo.currentmove = &supertank_move_end_attack1;
 }
supertank_run()
void supertank_run (edict_t * self)
Definition at line 195 of file m_supertank.c.
 {
     if (self->monsterinfo.aiflags & AI_STAND_GROUND)
         self->monsterinfo.currentmove = &supertank_move_stand;
     else
         self->monsterinfo.currentmove = &supertank_move_run;
 }
Referenced by SP_monster_supertank().
supertank_search()
void supertank_search (edict_t * self)
Definition at line 47 of file m_supertank.c.
 {
     if (random() < 0.5)
         gi.sound(self, CHAN_VOICE, sound_search1, 1, ATTN_NORM, 0);
     else
         gi.sound(self, CHAN_VOICE, sound_search2, 1, ATTN_NORM, 0);
 }
Referenced by SP_monster_supertank().
supertank_stand()
void supertank_stand (edict_t * self)
Definition at line 130 of file m_supertank.c.
 {
     self->monsterinfo.currentmove = &supertank_move_stand;
 }
Referenced by SP_monster_supertank().
supertank_walk()
void supertank_walk (edict_t * self)
Definition at line 190 of file m_supertank.c.
 {
     self->monsterinfo.currentmove = &supertank_move_forward;
 }
Referenced by SP_monster_supertank().
supertankMachineGun()
void supertankMachineGun (edict_t * self)
Definition at line 498 of file m_supertank.c.
 {
     vec3_t  dir;
     vec3_t  vec;
     vec3_t  start;
     vec3_t  forward, right;
     int     flash_number;
     flash_number = MZ2_SUPERTANK_MACHINEGUN_1 + (self->s.frame - FRAME_attak1_1);
     //FIXME!!!
     dir[0] = 0;
     dir[1] = self->s.angles[1];
     dir[2] = 0;
     AngleVectors(dir, forward, right, NULL);
     G_ProjectSource(self->s.origin, monster_flash_offset[flash_number], forward, right, start);
     if (self->enemy) {
         VectorCopy(self->enemy->s.origin, vec);
         VectorMA(vec, 0, self->enemy->velocity, vec);
         vec[2] += self->enemy->viewheight;
         VectorSubtract(vec, start, forward);
         VectorNormalize(forward);
     }
     monster_fire_bullet(self, start, forward, 6, 4, DEFAULT_BULLET_HSPREAD, DEFAULT_BULLET_VSPREAD, flash_number);
 }
supertankRocket()
void supertankRocket (edict_t * self)
Definition at line 472 of file m_supertank.c.
 {
     vec3_t  forward, right;
     vec3_t  start;
     vec3_t  dir;
     vec3_t  vec;
     int     flash_number;
     if (self->s.frame == FRAME_attak2_8)
         flash_number = MZ2_SUPERTANK_ROCKET_1;
     else if (self->s.frame == FRAME_attak2_11)
         flash_number = MZ2_SUPERTANK_ROCKET_2;
     else // (self->s.frame == FRAME_attak2_14)
         flash_number = MZ2_SUPERTANK_ROCKET_3;
     AngleVectors(self->s.angles, forward, right, NULL);
     G_ProjectSource(self->s.origin, monster_flash_offset[flash_number], forward, right, start);
     VectorCopy(self->enemy->s.origin, vec);
     vec[2] += self->enemy->viewheight;
     VectorSubtract(vec, start, dir);
     VectorNormalize(dir);
     monster_fire_rocket(self, start, dir, 50, 500, flash_number);
 }
TreadSound()
void TreadSound (edict_t * self)
Definition at line 42 of file m_supertank.c.
 {
     gi.sound(self, CHAN_VOICE, tread_sound, 1, ATTN_NORM, 0);
 }
visible()
qboolean visible (edict_t * self, edict_t * other)
Definition at line 268 of file g_ai.c.
 {
     vec3_t  spot1;
     vec3_t  spot2;
     trace_t trace;
     VectorCopy(self->s.origin, spot1);
     spot1[2] += self->viewheight;
     VectorCopy(other->s.origin, spot2);
     spot2[2] += other->viewheight;
     trace = gi.trace(spot1, vec3_origin, vec3_origin, spot2, self, MASK_OPAQUE);
     if (trace.fraction == 1.0)
         return qtrue;
     return qfalse;
 }
Referenced by ai_checkattack(), ClientBeginServerFrame(), FindTarget(), get_sunlight(), M_ReactToDamage(), PlayerTrail_PickFirst(), supertank_reattack1(), tank_reattack_blaster(), tank_refire_rocket(), and turret_driver_think().
Variable Documentation
sound_death
int sound_death static
Definition at line 34 of file m_supertank.c.
Referenced by SP_monster_supertank(), and supertank_die().
sound_pain1
int sound_pain1 static
Definition at line 31 of file m_supertank.c.
Referenced by SP_monster_supertank(), and supertank_pain().
sound_pain2
int sound_pain2 static
Definition at line 32 of file m_supertank.c.
Referenced by SP_monster_supertank(), and supertank_pain().
sound_pain3
int sound_pain3 static
Definition at line 33 of file m_supertank.c.
Referenced by SP_monster_supertank(), and supertank_pain().
sound_search1
int sound_search1 static
Definition at line 35 of file m_supertank.c.
Referenced by SP_monster_supertank(), and supertank_search().
sound_search2
int sound_search2 static
Definition at line 36 of file m_supertank.c.
Referenced by SP_monster_supertank(), and supertank_search().
supertank_frames_attack1
mframe_t supertank_frames_attack1[]
Initial value:
= {
    { ai_charge,  0,  supertankMachineGun },
    { ai_charge,  0,  supertankMachineGun },
    { ai_charge,  0,  supertankMachineGun },
    { ai_charge,  0,  supertankMachineGun },
    { ai_charge,  0,  supertankMachineGun },
    { ai_charge,  0,  supertankMachineGun },
}
Definition at line 394 of file m_supertank.c.
supertank_frames_attack2
mframe_t supertank_frames_attack2[]
Initial value:
= {
    { ai_charge,  0,  NULL },
    { ai_charge,  0,  NULL },
    { ai_charge,  0,  NULL },
    { ai_charge,  0,  NULL },
    { ai_charge,  0,  NULL },
    { ai_charge,  0,  NULL },
    { ai_charge,  0,  NULL },
    { ai_charge,  0,  supertankRocket },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  supertankRocket },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  supertankRocket },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL }
}
Definition at line 363 of file m_supertank.c.
supertank_frames_attack3
mframe_t supertank_frames_attack3[]
Initial value:
= {
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL }
}
Definition at line 332 of file m_supertank.c.
supertank_frames_attack4
mframe_t supertank_frames_attack4[]
Initial value:
= {
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL }
}
Definition at line 322 of file m_supertank.c.
supertank_frames_backward
mframe_t supertank_frames_backward[]
Initial value:
= {
    { ai_walk, 0, TreadSound },
    { ai_walk, 0, NULL },
    { ai_walk, 0, NULL },
    { ai_walk, 0, NULL },
    { ai_walk, 0, NULL },
    { ai_walk, 0, NULL },
    { ai_walk, 0, NULL },
    { ai_walk, 0, NULL },
    { ai_walk, 0, NULL },
    { ai_walk, 0, NULL },
    { ai_walk, 0, NULL },
    { ai_walk, 0, NULL },
    { ai_walk, 0, NULL },
    { ai_walk, 0, NULL },
    { ai_walk, 0, NULL },
    { ai_walk, 0, NULL },
    { ai_walk, 0, NULL },
    { ai_walk, 0, NULL }
}
Definition at line 300 of file m_supertank.c.
supertank_frames_death1
mframe_t supertank_frames_death1[]
Initial value:
= {
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  BossExplode }
}
Definition at line 272 of file m_supertank.c.
supertank_frames_end_attack1
mframe_t supertank_frames_end_attack1[]
Initial value:
= {
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL }
}
Definition at line 405 of file m_supertank.c.
supertank_frames_forward
mframe_t supertank_frames_forward[]
Initial value:
= {
    { ai_walk, 4, TreadSound },
    { ai_walk, 4, NULL },
    { ai_walk, 4, NULL },
    { ai_walk, 4, NULL },
    { ai_walk, 4, NULL },
    { ai_walk, 4, NULL },
    { ai_walk, 4, NULL },
    { ai_walk, 4, NULL },
    { ai_walk, 4, NULL },
    { ai_walk, 4, NULL },
    { ai_walk, 4, NULL },
    { ai_walk, 4, NULL },
    { ai_walk, 4, NULL },
    { ai_walk, 4, NULL },
    { ai_walk, 4, NULL },
    { ai_walk, 4, NULL },
    { ai_walk, 4, NULL },
    { ai_walk, 4, NULL }
}
Definition at line 163 of file m_supertank.c.
supertank_frames_pain1
mframe_t supertank_frames_pain1[]
Initial value:
= {
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL }
}
Definition at line 264 of file m_supertank.c.
supertank_frames_pain2
mframe_t supertank_frames_pain2[]
Initial value:
= {
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL }
}
Definition at line 256 of file m_supertank.c.
supertank_frames_pain3
mframe_t supertank_frames_pain3[]
Initial value:
= {
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL }
}
Definition at line 248 of file m_supertank.c.
supertank_frames_run
mframe_t supertank_frames_run[]
Initial value:
= {
    { ai_run, 12, TreadSound },
    { ai_run, 12, NULL },
    { ai_run, 12, NULL },
    { ai_run, 12, NULL },
    { ai_run, 12, NULL },
    { ai_run, 12, NULL },
    { ai_run, 12, NULL },
    { ai_run, 12, NULL },
    { ai_run, 12, NULL },
    { ai_run, 12, NULL },
    { ai_run, 12, NULL },
    { ai_run, 12, NULL },
    { ai_run, 12, NULL },
    { ai_run, 12, NULL },
    { ai_run, 12, NULL },
    { ai_run, 12, NULL },
    { ai_run, 12, NULL },
    { ai_run, 12, NULL }
}
Definition at line 136 of file m_supertank.c.
supertank_frames_stand
mframe_t supertank_frames_stand[]
Definition at line 66 of file m_supertank.c.
supertank_frames_turn_left
mframe_t supertank_frames_turn_left[]
Initial value:
= {
    { ai_move,    0,  TreadSound },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL }
}
Definition at line 225 of file m_supertank.c.
supertank_frames_turn_right
mframe_t supertank_frames_turn_right[]
Initial value:
= {
    { ai_move,    0,  TreadSound },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL },
    { ai_move,    0,  NULL }
}
Definition at line 203 of file m_supertank.c.
supertank_move_attack1
mmove_t supertank_move_attack1 = {FRAME_attak1_1, FRAME_attak1_6, supertank_frames_attack1, supertank_reattack1}
Definition at line 403 of file m_supertank.c.
Referenced by supertank_attack(), and supertank_reattack1().
supertank_move_attack2
mmove_t supertank_move_attack2 = {FRAME_attak2_1, FRAME_attak2_27, supertank_frames_attack2, supertank_run}
Definition at line 392 of file m_supertank.c.
Referenced by supertank_attack().
supertank_move_attack3
mmove_t supertank_move_attack3 = {FRAME_attak3_1, FRAME_attak3_27, supertank_frames_attack3, supertank_run}
Definition at line 361 of file m_supertank.c.
supertank_move_attack4
mmove_t supertank_move_attack4 = {FRAME_attak4_1, FRAME_attak4_6, supertank_frames_attack4, supertank_run}
Definition at line 330 of file m_supertank.c.
supertank_move_backward
mmove_t supertank_move_backward = {FRAME_backwd_1, FRAME_backwd_18, supertank_frames_backward, NULL}
Definition at line 320 of file m_supertank.c.
supertank_move_death
mmove_t supertank_move_death = {FRAME_death_1, FRAME_death_24, supertank_frames_death1, supertank_dead}
Definition at line 298 of file m_supertank.c.
Referenced by supertank_die().
supertank_move_end_attack1
mmove_t supertank_move_end_attack1 = {FRAME_attak1_7, FRAME_attak1_20, supertank_frames_end_attack1, supertank_run}
Definition at line 421 of file m_supertank.c.
Referenced by supertank_reattack1().
supertank_move_forward
mmove_t supertank_move_forward = {FRAME_forwrd_1, FRAME_forwrd_18, supertank_frames_forward, NULL}
Definition at line 183 of file m_supertank.c.
Referenced by supertank_forward(), and supertank_walk().
supertank_move_pain1
mmove_t supertank_move_pain1 = {FRAME_pain1_1, FRAME_pain1_4, supertank_frames_pain1, supertank_run}
Definition at line 270 of file m_supertank.c.
Referenced by supertank_pain().
supertank_move_pain2
mmove_t supertank_move_pain2 = {FRAME_pain2_5, FRAME_pain2_8, supertank_frames_pain2, supertank_run}
Definition at line 262 of file m_supertank.c.
Referenced by supertank_pain().
supertank_move_pain3
mmove_t supertank_move_pain3 = {FRAME_pain3_9, FRAME_pain3_12, supertank_frames_pain3, supertank_run}
Definition at line 254 of file m_supertank.c.
Referenced by supertank_pain().
supertank_move_run
mmove_t supertank_move_run = {FRAME_forwrd_1, FRAME_forwrd_18, supertank_frames_run, NULL}
Definition at line 156 of file m_supertank.c.
Referenced by supertank_run().
supertank_move_stand
mmove_t supertank_move_stand = {FRAME_stand_1, FRAME_stand_60, supertank_frames_stand, NULL}
Definition at line 128 of file m_supertank.c.
Referenced by SP_monster_supertank(), supertank_run(), and supertank_stand().
supertank_move_turn_left
mmove_t supertank_move_turn_left = {FRAME_left_1, FRAME_left_18, supertank_frames_turn_left, supertank_run}
Definition at line 245 of file m_supertank.c.
supertank_move_turn_right
mmove_t supertank_move_turn_right = {FRAME_right_1, FRAME_right_18, supertank_frames_turn_right, supertank_run}
Definition at line 223 of file m_supertank.c.
tread_sound
int tread_sound static
Definition at line 38 of file m_supertank.c.
Referenced by SP_monster_supertank(), and TreadSound().