Quake II RTX doxygen: C:/entry/dev/Q2RTX/src/client/client.h File Reference
client.h File Reference
#include "shared/shared.h"
#include "shared/list.h"
#include "common/bsp.h"
#include "common/cmd.h"
#include "common/cmodel.h"
#include "common/common.h"
#include "common/cvar.h"
#include "common/field.h"
#include "common/files.h"
#include "common/pmove.h"
#include "common/math.h"
#include "common/msg.h"
#include "common/net/chan.h"
#include "common/net/net.h"
#include "common/prompt.h"
#include "common/protocol.h"
#include "common/sizebuf.h"
#include "common/zone.h"
#include "system/system.h"
#include "refresh/refresh.h"
#include "server/server.h"
#include "client/client.h"
#include "client/input.h"
#include "client/keys.h"
#include "client/sound/sound.h"
#include "client/ui.h"
#include "client/video.h"
Classes
struct explosion_t
struct centity_s
struct clientinfo_s
struct client_history_t
struct server_frame_t
struct client_state_s
struct dlqueue_t
struct client_static_s
struct tent_params_t
struct mz_params_t
struct snd_params_t
struct cl_sustain_s
struct cparticle_s
Macros
#define MAX_EXPLOSIONS 32
#define MAX_CLIENTWEAPONMODELS 20
#define FF_SERVERDROP (1<<4)
#define FF_BADFRAME (1<<5)
#define FF_OLDFRAME (1<<6)
#define FF_OLDENT (1<<7)
#define FF_NODELTA (1<<8)
#define CL_FRAMETIME BASE_FRAMETIME
#define CL_1_FRAMETIME BASE_1_FRAMETIME
#define CL_FRAMEDIV 1
#define CL_FRAMESYNC 1
#define CL_KEYPS &cl.frame.ps
#define CL_OLDKEYPS &cl.oldframe.ps
#define CL_KEYLERPFRAC cl.lerpfrac
#define CONNECT_DELAY 3000u
#define CONNECT_INSTANT CONNECT_DELAY
#define CONNECT_FAST (CONNECT_DELAY - 1000u)
#define FOR_EACH_DLQ(q) LIST_FOR_EACH(dlqueue_t, q, &cls.download.queue, entry)
#define FOR_EACH_DLQ_SAFE(q, n) LIST_FOR_EACH_SAFE(dlqueue_t, q, n, &cls.download.queue, entry)
#define C_FPS cls.measure.fps[0]
#define R_FPS cls.measure.fps[1]
#define C_MPS cls.measure.fps[2]
#define C_PPS cls.measure.fps[3]
#define C_FRAMES cls.measure.frames[0]
#define R_FRAMES cls.measure.frames[1]
#define M_FRAMES cls.measure.frames[2]
#define P_FRAMES cls.measure.frames[3]
#define RECENT_ADDR 4
#define RECENT_MASK (RECENT_ADDR - 1)
#define NOPART_GRENADE_EXPLOSION 1
#define NOPART_GRENADE_TRAIL 2
#define NOPART_ROCKET_EXPLOSION 4
#define NOPART_ROCKET_TRAIL 8
#define NOPART_BLOOD 16
#define NOEXP_GRENADE 1
#define NOEXP_ROCKET 2
#define SHOWNET(...)
#define SHOWCLAMP(...)
#define SHOWMISS(...)
#define CL_PLAYER_MODEL_DISABLED 0
#define CL_PLAYER_MODEL_ONLY_GUN 1
#define CL_PLAYER_MODEL_FIRST_PERSON 2
#define CL_PLAYER_MODEL_THIRD_PERSON 3
#define V_AddLight(org, intensity, r, g, b)
#define V_AddLightEx(org, intensity, r, g, b, radius)
#define PARTICLE_GRAVITY 120
#define BLASTER_PARTICLE_COLOR 0xe0
#define INSTANT_PARTICLE -10000.0
#define HTTP_Init() (void)0
#define HTTP_Shutdown() (void)0
#define HTTP_SetServer(url) (void)0
#define HTTP_QueueDownload(path, type) Q_ERR_NOSYS
#define HTTP_RunDownloads() (void)0
#define HTTP_CleanupDownloads() (void)0
#define CL_GTV_EmitFrame() (void)0
#define CL_GTV_WriteMessage(data, len) (void)0
#define CL_GTV_Resume() (void)0
#define CL_GTV_Suspend() (void)0
#define CL_GTV_Transmit() (void)0
#define CL_GTV_Run() (void)0
#define CL_GTV_Init() (void)0
#define CL_GTV_Shutdown() (void)0
Typedefs
typedef struct centity_s centity_t
typedef struct clientinfo_s clientinfo_t
typedef struct client_state_s client_state_t
typedef struct client_static_s client_static_t
typedef struct cl_sustain_s cl_sustain_t
typedef struct cparticle_s cparticle_t
Enumerations
enum connstate_t {
ca_uninitialized, ca_disconnected, ca_challenging, ca_connecting,
ca_connected, ca_loading, ca_precached, ca_active,
ca_cinematic
}
enum dltype_t { DL_OTHER, DL_MAP, DL_MODEL }
enum dlstate_t { DL_PENDING, DL_RUNNING, DL_DONE }
enum load_state_t {
LOAD_NONE, LOAD_MAP, LOAD_MODELS, LOAD_IMAGES,
LOAD_CLIENTS, LOAD_SOUNDS
}
Functions
void CL_Init (void)
void CL_Quit_f (void)
void CL_Disconnect (error_type_t type)
void CL_UpdateRecordingSetting (void)
void CL_Begin (void)
void CL_CheckForResend (void)
void CL_ClearState (void)
void CL_RestartFilesystem (qboolean total)
void CL_RestartRefresh (qboolean total)
void CL_ClientCommand (const char *string)
void CL_SendRcon (const netadr_t *adr, const char *pass, const char *cmd)
const char * CL_Server_g (const char *partial, int argnum, int state)
void CL_CheckForPause (void)
void CL_UpdateFrameTimes (void)
qboolean CL_CheckForIgnore (const char *s)
void CL_WriteConfig (void)
void CL_ParsePlayerSkin (char *name, char *model, char *skin, const char *s)
void CL_LoadClientinfo (clientinfo_t *ci, const char *s)
void CL_LoadState (load_state_t state)
void CL_RegisterSounds (void)
void CL_RegisterBspModels (void)
void CL_RegisterVWepModels (void)
void CL_PrepRefresh (void)
void CL_UpdateConfigstring (int index)
qerror_t CL_QueueDownload (const char *path, dltype_t type)
qboolean CL_IgnoreDownload (const char *path)
void CL_FinishDownload (dlqueue_t *q)
void CL_CleanupDownloads (void)
void CL_LoadDownloadIgnores (void)
void CL_HandleDownload (byte *data, int size, int percent, int compressed)
qboolean CL_CheckDownloadExtension (const char *ext)
void CL_StartNextDownload (void)
void CL_RequestNextDownload (void)
void CL_ResetPrecacheCheck (void)
void CL_InitDownloads (void)
void IN_Init (void)
void IN_Shutdown (void)
void IN_Frame (void)
void IN_Activate (void)
void CL_RegisterInput (void)
void CL_UpdateCmd (int msec)
void CL_FinalizeCmd (void)
void CL_SendCmd (void)
void CL_ParseServerMessage (void)
void CL_SeekDemoMessage (void)
void CL_DeltaFrame (void)
void CL_AddEntities (void)
void CL_CalcViewValues (void)
void CL_GetEntitySoundOrigin (int ent, vec3_t org)
void V_Init (void)
void V_Shutdown (void)
void V_RenderView (void)
void V_AddEntity (entity_t *ent)
void V_AddParticle (particle_t *p)
void CL_UpdateBlendSetting (void)
void CL_SmokeAndFlash (vec3_t origin)
void CL_RegisterTEntSounds (void)
void CL_RegisterTEntModels (void)
void CL_ParseTEnt (void)
void CL_AddTEnts (void)
void CL_ClearTEnts (void)
void CL_InitTEnts (void)
void CL_PredictAngles (void)
void CL_PredictMovement (void)
void CL_CheckPredictionError (void)
void CL_BigTeleportParticles (vec3_t org)
void CL_RocketTrail (vec3_t start, vec3_t end, centity_t *old)
void CL_DiminishingTrail (vec3_t start, vec3_t end, centity_t *old, int flags)
void CL_FlyEffect (centity_t *ent, vec3_t origin)
void CL_BfgParticles (entity_t *ent)
void CL_ItemRespawnParticles (vec3_t org)
void CL_InitEffects (void)
void CL_ClearEffects (void)
void CL_BlasterParticles (vec3_t org, vec3_t dir)
void CL_ExplosionParticles (vec3_t org)
void CL_BFGExplosionParticles (vec3_t org)
void CL_BlasterTrail (vec3_t start, vec3_t end)
void CL_QuadTrail (vec3_t start, vec3_t end)
void CL_OldRailTrail (void)
void CL_BubbleTrail (vec3_t start, vec3_t end)
void CL_FlagTrail (vec3_t start, vec3_t end, int color)
void CL_MuzzleFlash (void)
void CL_MuzzleFlash2 (void)
void CL_TeleporterParticles (vec3_t org)
void CL_TeleportParticles (vec3_t org)
void CL_ParticleEffect (vec3_t org, vec3_t dir, int color, int count)
void CL_ParticleEffectWaterSplash (vec3_t org, vec3_t dir, int color, int count)
void CL_BloodParticleEffect (vec3_t org, vec3_t dir, int color, int count)
void CL_ParticleEffect2 (vec3_t org, vec3_t dir, int color, int count)
cparticle_t * CL_AllocParticle (void)
void CL_RunParticles (void)
void CL_AddParticles (void)
void CL_BlasterParticles2 (vec3_t org, vec3_t dir, unsigned int color)
void CL_BlasterTrail2 (vec3_t start, vec3_t end)
void CL_DebugTrail (vec3_t start, vec3_t end)
void CL_SmokeTrail (vec3_t start, vec3_t end, int colorStart, int colorRun, int spacing)
void CL_ForceWall (vec3_t start, vec3_t end, int color)
void CL_GenericParticleEffect (vec3_t org, vec3_t dir, int color, int count, int numcolors, int dirspread, float alphavel)
void CL_BubbleTrail2 (vec3_t start, vec3_t end, int dist)
void CL_Heatbeam (vec3_t start, vec3_t end)
void CL_ParticleSteamEffect (vec3_t org, vec3_t dir, int color, int count, int magnitude)
void CL_TrackerTrail (vec3_t start, vec3_t end, int particleColor)
void CL_Tracker_Explode (vec3_t origin)
void CL_TagTrail (vec3_t start, vec3_t end, int color)
void CL_Tracker_Shell (vec3_t origin)
void CL_MonsterPlasma_Shell (vec3_t origin)
void CL_ColorExplosionParticles (vec3_t org, int color, int run)
void CL_ParticleSmokeEffect (vec3_t org, vec3_t dir, int color, int count, int magnitude)
void CL_Widowbeamout (cl_sustain_t *self)
void CL_Nukeblast (cl_sustain_t *self)
void CL_WidowSplash (void)
void CL_IonripperTrail (vec3_t start, vec3_t end)
void CL_TrapParticles (entity_t *ent)
void CL_ParticleEffect3 (vec3_t org, vec3_t dir, int color, int count)
void CL_ParticleSteamEffect2 (cl_sustain_t *self)
void CL_InitDemos (void)
void CL_CleanupDemos (void)
void CL_DemoFrame (int msec)
qboolean CL_WriteDemoMessage (sizebuf_t *buf)
void CL_EmitDemoFrame (void)
void CL_EmitDemoSnapshot (void)
void CL_FirstDemoFrame (void)
void CL_Stop_f (void)
demoInfo_t * CL_GetDemoInfo (const char *path, demoInfo_t *info)
void LOC_Init (void)
void LOC_LoadLocations (void)
void LOC_FreeLocations (void)
void LOC_UpdateCvars (void)
void LOC_AddLocationsToScene (void)
void Con_Init (void)
void Con_PostInit (void)
void Con_Shutdown (void)
void Con_DrawConsole (void)
void Con_RunConsole (void)
void Con_Print (const char *txt)
void Con_ClearNotify_f (void)
void Con_ToggleConsole_f (void)
void Con_ClearTyping (void)
void Con_Close (qboolean force)
void Con_Popup (qboolean force)
void Con_SkipNotify (qboolean skip)
void Con_RegisterMedia (void)
void Con_CheckResize (void)
void Key_Console (int key)
void Key_Message (int key)
void Char_Console (int key)
void Char_Message (int key)
void CL_InitRefresh (void)
void CL_ShutdownRefresh (void)
void CL_RunRefresh (void)
void SCR_Init (void)
void SCR_Shutdown (void)
void SCR_UpdateScreen (void)
void SCR_SizeUp (void)
void SCR_SizeDown (void)
void SCR_CenterPrint (const char *str)
void SCR_FinishCinematic (void)
void SCR_PlayCinematic (const char *name)
void SCR_RunCinematic ()
void SCR_BeginLoadingPlaque (void)
void SCR_EndLoadingPlaque (void)
void SCR_DebugGraph (float value, int color)
void SCR_TouchPics (void)
void SCR_RegisterMedia (void)
void SCR_ModeChanged (void)
void SCR_LagSample (void)
void SCR_LagClear (void)
void SCR_SetCrosshairColor (void)
qhandle_t SCR_GetFont (void)
void SCR_SetHudAlpha (float alpha)
float SCR_FadeAlpha (unsigned startTime, unsigned visTime, unsigned fadeTime)
int SCR_DrawStringEx (int x, int y, int flags, size_t maxlen, const char *s, qhandle_t font)
void SCR_DrawStringMulti (int x, int y, int flags, size_t maxlen, const char *s, qhandle_t font)
void SCR_ClearChatHUD_f (void)
void SCR_AddToChatHUD (const char *text)
void CL_InitAscii (void)
byte COM_BlockSequenceCRCByte (byte *base, size_t length, int sequence)
void FX_Init (void)
Variables
explosion_t cl_explosions [MAX_EXPLOSIONS]
centity_t cl_entities [MAX_EDICTS]
client_state_t cl
client_static_t cls
cmdbuf_t cl_cmdbuf
char cl_cmdbuf_text [MAX_STRING_CHARS]
cvar_t * cl_gun
cvar_t * cl_gunalpha
cvar_t * cl_predict
cvar_t * cl_footsteps
cvar_t * cl_noskins
cvar_t * cl_kickangles
cvar_t * cl_rollhack
cvar_t * cl_noglow
cvar_t * cl_nolerp
cvar_t * cl_vwep
cvar_t * cl_disable_particles
cvar_t * cl_disable_explosions
cvar_t * cl_explosion_sprites
cvar_t * cl_explosion_frametime
cvar_t * cl_chat_notify
cvar_t * cl_chat_sound
cvar_t * cl_chat_filter
cvar_t * cl_disconnectcmd
cvar_t * cl_changemapcmd
cvar_t * cl_beginmapcmd
cvar_t * cl_gibs
cvar_t * cl_player_model
cvar_t * cl_thirdperson_angle
cvar_t * cl_thirdperson_range
cvar_t * cl_async
cvar_t * info_password
cvar_t * info_spectator
cvar_t * info_name
cvar_t * info_skin
cvar_t * info_rate
cvar_t * info_fov
cvar_t * info_msg
cvar_t * info_hand
cvar_t * info_gender
cvar_t * info_uf
tent_params_t te
mz_params_t mz
snd_params_t snd
int gun_frame
qhandle_t gun_model
vrect_t scr_vrect
Macro Definition Documentation
BLASTER_PARTICLE_COLOR
#define BLASTER_PARTICLE_COLOR 0xe0
Definition at line 777 of file client.h.
C_FPS
#define C_FPS cls.measure.fps[0]
Definition at line 393 of file client.h.
C_FRAMES
#define C_FRAMES cls.measure.frames[0]
Definition at line 397 of file client.h.
C_MPS
#define C_MPS cls.measure.fps[2]
Definition at line 395 of file client.h.
C_PPS
#define C_PPS cls.measure.fps[3]
Definition at line 396 of file client.h.
CL_1_FRAMETIME
#define CL_1_FRAMETIME BASE_1_FRAMETIME
Definition at line 162 of file client.h.
CL_FRAMEDIV
#define CL_FRAMEDIV 1
Definition at line 163 of file client.h.
CL_FRAMESYNC
#define CL_FRAMESYNC 1
Definition at line 164 of file client.h.
CL_FRAMETIME
#define CL_FRAMETIME BASE_FRAMETIME
Definition at line 161 of file client.h.
CL_GTV_EmitFrame
#define CL_GTV_EmitFrame () (void)0
Definition at line 1015 of file client.h.
CL_GTV_Init
#define CL_GTV_Init () (void)0
Definition at line 1021 of file client.h.
CL_GTV_Resume
#define CL_GTV_Resume () (void)0
Definition at line 1017 of file client.h.
CL_GTV_Run
#define CL_GTV_Run () (void)0
Definition at line 1020 of file client.h.
CL_GTV_Shutdown
#define CL_GTV_Shutdown () (void)0
Definition at line 1022 of file client.h.
CL_GTV_Suspend
#define CL_GTV_Suspend () (void)0
Definition at line 1018 of file client.h.
CL_GTV_Transmit
#define CL_GTV_Transmit () (void)0
Definition at line 1019 of file client.h.
CL_GTV_WriteMessage
#define CL_GTV_WriteMessage (data, len) (void)0
Definition at line 1016 of file client.h.
CL_KEYLERPFRAC
#define CL_KEYLERPFRAC cl.lerpfrac
Definition at line 167 of file client.h.
CL_KEYPS
#define CL_KEYPS &cl.frame.ps
Definition at line 165 of file client.h.
CL_OLDKEYPS
#define CL_OLDKEYPS &cl.oldframe.ps
Definition at line 166 of file client.h.
CL_PLAYER_MODEL_DISABLED
#define CL_PLAYER_MODEL_DISABLED 0
Definition at line 553 of file client.h.
CL_PLAYER_MODEL_FIRST_PERSON
#define CL_PLAYER_MODEL_FIRST_PERSON 2
Definition at line 555 of file client.h.
CL_PLAYER_MODEL_ONLY_GUN
#define CL_PLAYER_MODEL_ONLY_GUN 1
Definition at line 554 of file client.h.
CL_PLAYER_MODEL_THIRD_PERSON
#define CL_PLAYER_MODEL_THIRD_PERSON 3
Definition at line 556 of file client.h.
CONNECT_DELAY
#define CONNECT_DELAY 3000u
Definition at line 327 of file client.h.
CONNECT_FAST
#define CONNECT_FAST (CONNECT_DELAY - 1000u)
Definition at line 330 of file client.h.
CONNECT_INSTANT
#define CONNECT_INSTANT CONNECT_DELAY
Definition at line 329 of file client.h.
FF_BADFRAME
#define FF_BADFRAME (1<<5)
Definition at line 146 of file client.h.
FF_NODELTA
#define FF_NODELTA (1<<8)
Definition at line 149 of file client.h.
FF_OLDENT
#define FF_OLDENT (1<<7)
Definition at line 148 of file client.h.
FF_OLDFRAME
#define FF_OLDFRAME (1<<6)
Definition at line 147 of file client.h.
FF_SERVERDROP
#define FF_SERVERDROP (1<<4)
Definition at line 145 of file client.h.
FOR_EACH_DLQ
#define FOR_EACH_DLQ (q) LIST_FOR_EACH(dlqueue_t, q, &cls.download.queue, entry)
Definition at line 344 of file client.h.
FOR_EACH_DLQ_SAFE
#define FOR_EACH_DLQ_SAFE (q, n) LIST_FOR_EACH_SAFE(dlqueue_t, q, n, &cls.download.queue, entry)
Definition at line 346 of file client.h.
HTTP_CleanupDownloads
#define HTTP_CleanupDownloads () (void)0
Definition at line 998 of file client.h.
HTTP_Init
#define HTTP_Init () (void)0
Definition at line 993 of file client.h.
HTTP_QueueDownload
#define HTTP_QueueDownload (path, type) Q_ERR_NOSYS
Definition at line 996 of file client.h.
HTTP_RunDownloads
#define HTTP_RunDownloads () (void)0
Definition at line 997 of file client.h.
HTTP_SetServer
#define HTTP_SetServer (url) (void)0
Definition at line 995 of file client.h.
HTTP_Shutdown
#define HTTP_Shutdown () (void)0
Definition at line 994 of file client.h.
INSTANT_PARTICLE
#define INSTANT_PARTICLE -10000.0
Definition at line 778 of file client.h.
M_FRAMES
#define M_FRAMES cls.measure.frames[2]
Definition at line 399 of file client.h.
MAX_CLIENTWEAPONMODELS
#define MAX_CLIENTWEAPONMODELS 20
Definition at line 110 of file client.h.
MAX_EXPLOSIONS
#define MAX_EXPLOSIONS 32
Definition at line 58 of file client.h.
NOEXP_GRENADE
#define NOEXP_GRENADE 1
Definition at line 501 of file client.h.
NOEXP_ROCKET
#define NOEXP_ROCKET 2
Definition at line 502 of file client.h.
NOPART_BLOOD
#define NOPART_BLOOD 16
Definition at line 499 of file client.h.
NOPART_GRENADE_EXPLOSION
#define NOPART_GRENADE_EXPLOSION 1
Definition at line 495 of file client.h.
NOPART_GRENADE_TRAIL
#define NOPART_GRENADE_TRAIL 2
Definition at line 496 of file client.h.
NOPART_ROCKET_EXPLOSION
#define NOPART_ROCKET_EXPLOSION 4
Definition at line 497 of file client.h.
NOPART_ROCKET_TRAIL
#define NOPART_ROCKET_TRAIL 8
Definition at line 498 of file client.h.
P_FRAMES
#define P_FRAMES cls.measure.frames[3]
Definition at line 400 of file client.h.
PARTICLE_GRAVITY
#define PARTICLE_GRAVITY 120
Definition at line 776 of file client.h.
R_FPS
#define R_FPS cls.measure.fps[1]
Definition at line 394 of file client.h.
R_FRAMES
#define R_FRAMES cls.measure.frames[1]
Definition at line 398 of file client.h.
RECENT_ADDR
#define RECENT_ADDR 4
Definition at line 431 of file client.h.
RECENT_MASK
#define RECENT_MASK (RECENT_ADDR - 1)
Definition at line 432 of file client.h.
SHOWCLAMP
#define SHOWCLAMP (...)
Definition at line 532 of file client.h.
SHOWMISS
#define SHOWMISS (...)
Definition at line 533 of file client.h.
SHOWNET
#define SHOWNET (...)
Definition at line 531 of file client.h.
V_AddLight
#define V_AddLight (org, intensity, r, g, b)
Definition at line 728 of file client.h.
V_AddLightEx
#define V_AddLightEx (org, intensity, r, g, b, radius)
Definition at line 729 of file client.h.
Typedef Documentation
centity_t
typedef struct centity_s centity_t
cl_sustain_t
typedef struct cl_sustain_s cl_sustain_t
client_state_t
typedef struct client_state_s client_state_t
client_static_t
typedef struct client_static_s client_static_t
clientinfo_t
typedef struct clientinfo_s clientinfo_t
cparticle_t
typedef struct cparticle_s cparticle_t
Enumeration Type Documentation
connstate_t
enum connstate_t
Enumerator
ca_uninitialized
ca_disconnected
ca_challenging
ca_connecting
ca_connected
ca_loading
ca_precached
ca_active
ca_cinematic
Definition at line 332 of file client.h.
              {
     ca_uninitialized,
     ca_disconnected,    // not talking to a server
     ca_challenging,     // sending getchallenge packets to the server
     ca_connecting,      // sending connect packets to the server
     ca_connected,       // netchan_t established, waiting for svc_serverdata
     ca_loading,         // loading level data
     ca_precached,       // loaded level data, waiting for svc_frame
     ca_active,          // game views should be displayed
     ca_cinematic        // running a cinematic
 } connstate_t;
dlstate_t
enum dlstate_t
Enumerator
DL_PENDING
DL_RUNNING
DL_DONE
Definition at line 361 of file client.h.
              {
     DL_PENDING,
     DL_RUNNING,
     DL_DONE
 } dlstate_t;
dltype_t
enum dltype_t
Enumerator
DL_OTHER
DL_MAP
DL_MODEL
Definition at line 349 of file client.h.
              {
     // generic types
     DL_OTHER,
     DL_MAP,
     DL_MODEL,
 #if USE_CURL
     // special types
     DL_LIST,
     DL_PAK
 #endif
 } dltype_t;
load_state_t
enum load_state_t
Enumerator
LOAD_NONE
LOAD_MAP
LOAD_MODELS
LOAD_IMAGES
LOAD_CLIENTS
LOAD_SOUNDS
Definition at line 606 of file client.h.
              {
     LOAD_NONE,
     LOAD_MAP,
     LOAD_MODELS,
     LOAD_IMAGES,
     LOAD_CLIENTS,
     LOAD_SOUNDS
 } load_state_t;
Function Documentation
Char_Console()
void Char_Console (int key)
Definition at line 1229 of file console.c.
 {
     if (IF_CharEvent(&con.prompt.inputLine, key)) {
         Con_InteractiveMode();
     }
 }
Referenced by Key_Event().
Char_Message()
void Char_Message (int key)
Definition at line 1289 of file console.c.
 {
     IF_CharEvent(&con.chatPrompt.inputLine, key);
 }
Referenced by Key_Event().
CL_AddEntities()
void CL_AddEntities (void)
Definition at line 1378 of file entities.c.
 {
     CL_CalcViewValues();
     CL_FinishViewValues();
     CL_AddPacketEntities();
     CL_AddTEnts();
     CL_AddParticles();
 #if USE_DLIGHTS
     CL_AddDLights();
 #endif
 #if USE_LIGHTSTYLES
     CL_AddLightStyles();
 #endif
 #if CL_RTX_SHADERBALLS
     CL_AddShaderBalls();
 #endif
     LOC_AddLocationsToScene();
 }
Referenced by V_RenderView().
CL_AddParticles()
void CL_AddParticles (void)
Definition at line 1989 of file effects.c.
 {
     cparticle_t     *p, *next;
     float           alpha;
     float           time = 0, time2;
     int             color;
     cparticle_t     *active, *tail;
     particle_t      *part;
     active = NULL;
     tail = NULL;
     for (p = active_particles; p; p = next) {
         next = p->next;
         if (p->alphavel != INSTANT_PARTICLE) {
             time = (cl.time - p->time) * 0.001;
             alpha = p->alpha + time * p->alphavel;
             if (alpha <= 0) {
                 // faded out
                 p->next = free_particles;
                 free_particles = p;
                 continue;
             }
         } else {
             alpha = p->alpha;
         }
         if (r_numparticles >= MAX_PARTICLES)
             break;
         part = &r_particles[r_numparticles++];
         p->next = NULL;
         if (!tail)
             active = tail = p;
         else {
             tail->next = p;
             tail = p;
         }
         if (alpha > 1.0)
             alpha = 1;
         color = p->color;
         time2 = time * time;
         part->origin[0] = p->org[0] + p->vel[0] * time + p->accel[0] * time2;
         part->origin[1] = p->org[1] + p->vel[1] * time + p->accel[1] * time2;
         part->origin[2] = p->org[2] + p->vel[2] * time + p->accel[2] * time2;
         if (color == -1) {
             part->rgba.u8[0] = p->rgba.u8[0];
             part->rgba.u8[1] = p->rgba.u8[1];
             part->rgba.u8[2] = p->rgba.u8[2];
             part->rgba.u8[3] = p->rgba.u8[3] * alpha;
         }
         part->color = color;
         part->brightness = p->brightness;
         part->alpha = alpha;
         part->radius = 0.f;
         if (p->alphavel == INSTANT_PARTICLE) {
             p->alphavel = 0.0;
             p->alpha = 0.0;
         }
     }
     active_particles = active;
 }
Referenced by CL_AddEntities().
CL_AddTEnts()
void CL_AddTEnts (void)
Definition at line 1445 of file tent.c.
 {
     CL_AddBeams();
     CL_AddPlayerBeams();
     CL_AddExplosions();
     CL_ProcessSustain();
     CL_AddLasers();
 }
Referenced by CL_AddEntities().
CL_AllocParticle()
cparticle_t* CL_AllocParticle (void)
Definition at line 856 of file effects.c.
 {
     cparticle_t *p;
     if (!free_particles)
         return NULL;
     p = free_particles;
     free_particles = p->next;
     p->next = active_particles;
     active_particles = p;
     return p;
 }
Referenced by CL_BFGExplosionParticles(), CL_BfgParticles(), CL_BigTeleportParticles(), CL_BlasterParticles(), CL_BlasterParticles2(), CL_BlasterTrail(), CL_BlasterTrail2(), CL_BloodParticleEffect(), CL_BubbleTrail(), CL_BubbleTrail2(), CL_ColorExplosionParticles(), CL_DebugTrail(), CL_DiminishingTrail(), CL_ExplosionParticles(), CL_FlagTrail(), CL_FlyParticles(), CL_ForceWall(), CL_GenericParticleEffect(), CL_Heatbeam(), CL_IonripperTrail(), CL_ItemRespawnParticles(), CL_LogoutEffect(), CL_MonsterPlasma_Shell(), CL_Nukeblast(), CL_OldRailTrail(), CL_ParticleEffect(), CL_ParticleEffect2(), CL_ParticleEffect3(), CL_ParticleEffectWaterSplash(), CL_ParticleSmokeEffect(), CL_ParticleSteamEffect(), CL_ParticleSteamEffect2(), CL_QuadTrail(), CL_RailSpiral(), CL_RocketTrail(), CL_SmokeTrail(), CL_TagTrail(), CL_TeleporterParticles(), CL_TeleportParticles(), CL_Tracker_Explode(), CL_Tracker_Shell(), CL_TrackerTrail(), CL_TrapParticles(), CL_Widowbeamout(), and CL_WidowSplash().
CL_Begin()
void CL_Begin (void)
Definition at line 1757 of file main.c.
 {
 #if USE_REF == REF_GL
     if (!Q_stricmp(cl.gamedir, "gloom")) {
         // cheat protect our custom modulate cvars
         gl_modulate_world->flags |= CVAR_CHEAT;
         gl_modulate_entities->flags |= CVAR_CHEAT;
         gl_brightness->flags |= CVAR_CHEAT;
     }
 #endif
     Cvar_FixCheats();
     CL_PrepRefresh();
     CL_LoadState(LOAD_SOUNDS);
     CL_RegisterSounds();
     LOC_LoadLocations();
     CL_LoadState(LOAD_NONE);
     cls.state = ca_precached;
 #if USE_FPS
     CL_UpdateRateSetting();
 #endif
     CL_ClientCommand(va("begin %i\n", precache_spawncount));
     CL_UpdateGunSetting();
     CL_UpdateBlendSetting();
     CL_UpdateGibSetting();
     CL_UpdateFootstepsSetting();
     CL_UpdatePredictSetting();
     CL_UpdateRecordingSetting();
 }
Referenced by CL_RequestNextDownload().
CL_BFGExplosionParticles()
void CL_BFGExplosionParticles (vec3_t org)
Definition at line 1905 of file effects.c.
 {
     int         i, j;
     cparticle_t *p;
     const int count = 256 * cl_particle_num_factor->value;
     for (i = 0; i < count; i++) {
         p = CL_AllocParticle();
         if (!p)
             return;
         p->time = cl.time;
         p->color = 0xd0 + (rand() & 7);
         p->brightness = cvar_pt_particle_emissive->value;
         for (j = 0; j < 3; j++) {
             p->org[j] = org[j] + ((rand() % 32) - 16);
             p->vel[j] = (rand() % 384) - 192;
         }
         p->accel[0] = p->accel[1] = 0;
         p->accel[2] = -PARTICLE_GRAVITY;
         p->alpha = 1.0;
         p->alphavel = -0.8 / (0.5 + frand() * 0.3);
     }
 }
Referenced by CL_ParseTEnt().
CL_BfgParticles()
void CL_BfgParticles (entity_t * ent)
Definition at line 1847 of file effects.c.
 {
     int         i;
     cparticle_t *p;
     float       angle;
     float       sp, sy, cp, cy;
     vec3_t      forward;
     float       dist = 64;
     vec3_t      v;
     float       ltime;
     const int count = NUMVERTEXNORMALS * cl_particle_num_factor->value;
     ltime = (float)cl.time / 1000.0;
     for (i = 0; i < count; i++) {
         angle = ltime * avelocities[i][0];
         sy = sin(angle);
         cy = cos(angle);
         angle = ltime * avelocities[i][1];
         sp = sin(angle);
         cp = cos(angle);
         forward[0] = cp * cy;
         forward[1] = cp * sy;
         forward[2] = -sp;
         p = CL_AllocParticle();
         if (!p)
             return;
         p->time = cl.time;
         dist = sin(ltime + i) * 64;
         p->org[0] = ent->origin[0] + bytedirs[i][0] * dist + forward[0] * BEAMLENGTH;
         p->org[1] = ent->origin[1] + bytedirs[i][1] * dist + forward[1] * BEAMLENGTH;
         p->org[2] = ent->origin[2] + bytedirs[i][2] * dist + forward[2] * BEAMLENGTH;
         VectorClear(p->vel);
         VectorClear(p->accel);
         VectorSubtract(p->org, ent->origin, v);
         dist = VectorLength(v) / 90.0;
         p->color = floor(0xd0 + dist * 7);
         p->brightness = cvar_pt_particle_emissive->value;
         p->alpha = 1.0 - dist;
         p->alphavel = INSTANT_PARTICLE;
     }
 }
Referenced by CL_AddPacketEntities().
CL_BigTeleportParticles()
void CL_BigTeleportParticles (vec3_t org)
Definition at line 1256 of file effects.c.
 {
     static const byte   colortable[4] = {2 * 8, 13 * 8, 21 * 8, 18 * 8};
     int         i;
     cparticle_t *p;
     float       angle, dist;
     for (i = 0; i < 4096; i++) {
         p = CL_AllocParticle();
         if (!p)
             return;
         p->time = cl.time;
         p->color = colortable[rand() & 3];
         p->brightness = 1.0f;
         angle = M_PI * 2 * (rand() & 1023) / 1023.0;
         dist = rand() & 31;
         p->org[0] = org[0] + cos(angle) * dist;
         p->vel[0] = cos(angle) * (70 + (rand() & 63));
         p->accel[0] = -cos(angle) * 100;
         p->org[1] = org[1] + sin(angle) * dist;
         p->vel[1] = sin(angle) * (70 + (rand() & 63));
         p->accel[1] = -sin(angle) * 100;
         p->org[2] = org[2] + 8 + (rand() % 90);
         p->vel[2] = -100 + (rand() & 31);
         p->accel[2] = PARTICLE_GRAVITY * 4;
         p->alpha = 1.0;
         p->alphavel = -0.3 / (0.5 + frand() * 0.3);
     }
 }
Referenced by CL_ParseTEnt().
CL_BlasterParticles()
void CL_BlasterParticles (vec3_t org, vec3_t dir)
Definition at line 1300 of file effects.c.
 {
     int         i, j;
     cparticle_t *p;
     float       d;
     const int count = 40 * cl_particle_num_factor->value;
     for (i = 0; i < count; i++) {
         p = CL_AllocParticle();
         if (!p)
             return;
         p->time = cl.time;
         p->color = 0xe0 + (rand() & 7);
         p->brightness = cvar_pt_particle_emissive->value;
         d = rand() & 15;
         for (j = 0; j < 3; j++) {
             p->org[j] = org[j] + ((rand() & 7) - 4) + d * dir[j];
             p->vel[j] = dir[j] * 30 + crand() * 40;
         }
         p->accel[0] = p->accel[1] = 0;
         p->accel[2] = -PARTICLE_GRAVITY;
         p->alpha = 1.0;
         p->alphavel = -1.0 / (0.5 + frand() * 0.3);
     }
 }
Referenced by CL_ParseTEnt().
CL_BlasterParticles2()
void CL_BlasterParticles2 (vec3_t org, vec3_t dir, unsigned int color)
Definition at line 761 of file newfx.c.
 {
     int         i, j;
     cparticle_t *p;
     float       d;
     int         count;
     count = 40;
     for (i = 0; i < count; i++) {
         p = CL_AllocParticle();
         if (!p)
             return;
         p->time = cl.time;
         p->color = color + (rand() & 7);
         d = rand() & 15;
         for (j = 0; j < 3; j++) {
             p->org[j] = org[j] + ((rand() & 7) - 4) + d * dir[j];
             p->vel[j] = dir[j] * 30 + crand() * 40;
         }
         p->accel[0] = p->accel[1] = 0;
         p->accel[2] = -PARTICLE_GRAVITY;
         p->alpha = 1.0;
         p->alphavel = -1.0 / (0.5 + frand() * 0.3);
     }
 }
Referenced by CL_ParseTEnt().
CL_BlasterTrail()
void CL_BlasterTrail (vec3_t start, vec3_t end)
Definition at line 1339 of file effects.c.
 {
     vec3_t      move;
     vec3_t      vec;
     float       len;
     int         j;
     cparticle_t *p;
     int         dec;
     VectorCopy(start, move);
     VectorSubtract(end, start, vec);
     len = VectorNormalize(vec);
     dec = 5;
     VectorScale(vec, 5, vec);
     // FIXME: this is a really silly way to have a loop
     while (len > 0) {
         len -= dec;
         p = CL_AllocParticle();
         if (!p)
             return;
         VectorClear(p->accel);
         p->time = cl.time;
         p->alpha = 1.0;
         p->alphavel = -1.0 / (0.3 + frand() * 0.2);
         p->color = 0xe0;
         p->brightness = cvar_pt_particle_emissive->value;
         for (j = 0; j < 3; j++) {
             p->org[j] = move[j] + crand();
             p->vel[j] = crand() * 5;
             p->accel[j] = 0;
         }
         VectorAdd(move, vec, move);
     }
 }
Referenced by CL_AddPacketEntities().
CL_BlasterTrail2()
void CL_BlasterTrail2 (vec3_t start, vec3_t end)
Definition at line 798 of file newfx.c.
 {
     vec3_t      move;
     vec3_t      vec;
     float       len;
     int         j;
     cparticle_t *p;
     int         dec;
     VectorCopy(start, move);
     VectorSubtract(end, start, vec);
     len = VectorNormalize(vec);
     dec = 5;
     VectorScale(vec, 5, vec);
     // FIXME: this is a really silly way to have a loop
     while (len > 0) {
         len -= dec;
         p = CL_AllocParticle();
         if (!p)
             return;
         VectorClear(p->accel);
         p->time = cl.time;
         p->alpha = 1.0;
         p->alphavel = -1.0 / (0.3 + frand() * 0.2);
         p->color = 0xd0;
         for (j = 0; j < 3; j++) {
             p->org[j] = move[j] + crand();
             p->vel[j] = crand() * 5;
             p->accel[j] = 0;
         }
         VectorAdd(move, vec, move);
     }
 }
Referenced by CL_AddPacketEntities().
CL_BloodParticleEffect()
void CL_BloodParticleEffect (vec3_t org, vec3_t dir, int color, int count)
Definition at line 1006 of file effects.c.
 {
     int         i, j;
     cparticle_t *p;
     float       d;
     // add decal:
     decal_t dec = {
       .pos = {org[0],org[1],org[2]},
       .dir = {dir[0],dir[1],dir[2]},
       .spread = 0.25f,
       .length = 350};
     R_AddDecal(&dec);
     float a[3] = {dir[1], -dir[2], dir[0]};
     float b[3] = {-dir[2], dir[0], dir[1]};
     count *= cl_particle_num_factor->value;
     for (i = 0; i < count; i++) {
         p = CL_AllocParticle();
         if (!p)
             return;
         p->time = cl.time;
         p->color = color + (rand() & 7);
         p->brightness = 0.5f;
         d = (rand() & 31) * 10.0f;
         for (j = 0; j < 3; j++) {
             p->org[j] = org[j] + ((rand() & 7) - 4) + d * (dir[j]
               + a[j] * 0.5f*((rand() & 31) / 32.0f - .5f)
               + b[j] * 0.5f*((rand() & 31) / 32.0f - .5f));
             p->vel[j] = 10.0f*dir[j] + crand() * 20;
         }
         // fake gravity
         p->org[2] -= d*d * .001f;
         p->accel[0] = p->accel[1] = 0;
         p->accel[2] = -PARTICLE_GRAVITY;
         p->alpha = 0.5;
         p->alphavel = -1.0 / (0.5 + frand() * 0.3);
     }
 }
Referenced by CL_ParseTEnt().
CL_BubbleTrail()
void CL_BubbleTrail (vec3_t start, vec3_t end)
Definition at line 1718 of file effects.c.
 {
     vec3_t      move;
     vec3_t      vec;
     float       len;
     int         i, j;
     cparticle_t *p;
     float       dec;
     VectorCopy(start, move);
     VectorSubtract(end, start, vec);
     len = VectorNormalize(vec);
     dec = 32;
     VectorScale(vec, dec, vec);
     for (i = 0; i < len; i += dec) {
         p = CL_AllocParticle();
         if (!p)
             return;
         VectorClear(p->accel);
         p->time = cl.time;
         p->alpha = 1.0;
         p->alphavel = -1.0 / (1 + frand() * 0.2);
         p->color = 4 + (rand() & 7);
         p->brightness = 1.0f;
         for (j = 0; j < 3; j++) {
             p->org[j] = move[j] + crand() * 2;
             p->vel[j] = crand() * 5;
         }
         p->vel[2] += 6;
         VectorAdd(move, vec, move);
     }
 }
Referenced by CL_ParseTEnt().
CL_BubbleTrail2()
void CL_BubbleTrail2 (vec3_t start, vec3_t end, int dist)
Definition at line 228 of file newfx.c.
 {
     vec3_t      move;
     vec3_t      vec;
     float       len;
     int         i, j;
     cparticle_t *p;
     float       dec;
     VectorCopy(start, move);
     VectorSubtract(end, start, vec);
     len = VectorNormalize(vec);
     dec = dist;
     VectorScale(vec, dec, vec);
     for (i = 0; i < len; i += dec) {
         p = CL_AllocParticle();
         if (!p)
             return;
         VectorClear(p->accel);
         p->time = cl.time;
         p->alpha = 1.0;
         p->alphavel = -1.0 / (1 + frand() * 0.1);
         p->color = 4 + (rand() & 7);
         for (j = 0; j < 3; j++) {
             p->org[j] = move[j] + crand() * 2;
             p->vel[j] = crand() * 10;
         }
         p->org[2] -= 4;
         p->vel[2] += 20;
         VectorAdd(move, vec, move);
     }
 }
Referenced by CL_ParseTEnt().
CL_CalcViewValues()
void CL_CalcViewValues (void)
Definition at line 1251 of file entities.c.
 {
     player_state_t *ps, *ops;
     vec3_t viewoffset;
     float lerp;
     if (!cl.frame.valid) {
         return;
     }
     // find states to interpolate between
     ps = &cl.frame.ps;
     ops = &cl.oldframe.ps;
     lerp = cl.lerpfrac;
     // calculate the origin
     if (!cls.demo.playback && cl_predict->integer && !(ps->pmove.pm_flags & PMF_NO_PREDICTION)) {
         // use predicted values
         unsigned delta = cls.realtime - cl.predicted_step_time;
         float backlerp = lerp - 1.0;
         VectorMA(cl.predicted_origin, backlerp, cl.prediction_error, cl.refdef.vieworg);
         // smooth out stair climbing
         if (cl.predicted_step < 127 * 0.125f) {
             delta <<= 1; // small steps
         }
         if (delta < 100) {
             cl.refdef.vieworg[2] -= cl.predicted_step * (100 - delta) * 0.01f;
         }
     } else {
         // just use interpolated values
         cl.refdef.vieworg[0] = ops->pmove.origin[0] * 0.125f +
                                lerp * (ps->pmove.origin[0] - ops->pmove.origin[0]) * 0.125f;
         cl.refdef.vieworg[1] = ops->pmove.origin[1] * 0.125f +
                                lerp * (ps->pmove.origin[1] - ops->pmove.origin[1]) * 0.125f;
         cl.refdef.vieworg[2] = ops->pmove.origin[2] * 0.125f +
                                lerp * (ps->pmove.origin[2] - ops->pmove.origin[2]) * 0.125f;
     }
     // if not running a demo or on a locked frame, add the local angle movement
     if (cls.demo.playback) {
         LerpAngles(ops->viewangles, ps->viewangles, lerp, cl.refdef.viewangles);
     } else if (ps->pmove.pm_type < PM_DEAD) {
         // use predicted values
         VectorCopy(cl.predicted_angles, cl.refdef.viewangles);
     } else if (ops->pmove.pm_type < PM_DEAD && cls.serverProtocol > PROTOCOL_VERSION_DEFAULT) {
         // lerp from predicted angles, since enhanced servers
         // do not send viewangles each frame
         LerpAngles(cl.predicted_angles, ps->viewangles, lerp, cl.refdef.viewangles);
     } else {
         // just use interpolated values
         LerpAngles(ops->viewangles, ps->viewangles, lerp, cl.refdef.viewangles);
     }
 #if USE_SMOOTH_DELTA_ANGLES
     cl.delta_angles[0] = LerpShort(ops->pmove.delta_angles[0], ps->pmove.delta_angles[0], lerp);
     cl.delta_angles[1] = LerpShort(ops->pmove.delta_angles[1], ps->pmove.delta_angles[1], lerp);
     cl.delta_angles[2] = LerpShort(ops->pmove.delta_angles[2], ps->pmove.delta_angles[2], lerp);
 #endif
     // don't interpolate blend color
     Vector4Copy(ps->blend, cl.refdef.blend);
 #if USE_FPS
     ps = &cl.keyframe.ps;
     ops = &cl.oldkeyframe.ps;
     lerp = cl.keylerpfrac;
 #endif
     // interpolate field of view
     cl.fov_x = lerp_client_fov(ops->fov, ps->fov, lerp);
     cl.fov_y = V_CalcFov(cl.fov_x, 4, 3);
     LerpVector(ops->viewoffset, ps->viewoffset, lerp, viewoffset);
     AngleVectors(cl.refdef.viewangles, cl.v_forward, cl.v_right, cl.v_up);
     VectorCopy(cl.refdef.vieworg, cl.playerEntityOrigin);
     VectorCopy(cl.refdef.viewangles, cl.playerEntityAngles);
     if (cl.playerEntityAngles[PITCH] > 180) {
         cl.playerEntityAngles[PITCH] -= 360;
     }
     cl.playerEntityAngles[PITCH] = cl.playerEntityAngles[PITCH] / 3;
     VectorAdd(cl.refdef.vieworg, viewoffset, cl.refdef.vieworg);
     VectorCopy(cl.refdef.vieworg, listener_origin);
     VectorCopy(cl.v_forward, listener_forward);
     VectorCopy(cl.v_right, listener_right);
     VectorCopy(cl.v_up, listener_up);
 }
Referenced by CL_AddEntities(), and CL_Frame().
CL_CheckDownloadExtension()
qboolean CL_CheckDownloadExtension (const char * ext)
Definition at line 494 of file download.c.
 {
     static const char allowed[][4] = {
         "pcx", "wal", "wav", "md2", "sp2", "tga", "png",
         "jpg", "bsp", "ent", "txt", "dm2", "loc", "md3"
     };
     int i;
     for (i = 0; i < q_countof(allowed); i++)
         if (!Q_stricmp(ext, allowed[i]))
             return qtrue;
     return qfalse;
 }
Referenced by check_and_queue_download(), and check_file_len().
CL_CheckForIgnore()
qboolean CL_CheckForIgnore (const char * s)
Definition at line 2043 of file main.c.
 {
     char buffer[MAX_STRING_CHARS];
     ignore_t *ignore;
     if (LIST_EMPTY(&cl_ignores)) {
         return qfalse;
     }
     Q_strlcpy(buffer, s, sizeof(buffer));
     COM_strclr(buffer);
     LIST_FOR_EACH(ignore_t, ignore, &cl_ignores, entry) {
         if (Com_WildCmp(ignore->match, buffer)) {
             ignore->hits++;
             return qtrue;
         }
     }
     return qfalse;
 }
Referenced by CL_ParsePrint().
CL_CheckForPause()
void CL_CheckForPause (void)
Definition at line 3056 of file main.c.
 {
     if (cls.state != ca_active) {
         // only pause when active
         Cvar_Set("cl_paused", "0");
         Cvar_Set("sv_paused", "0");
         return;
     }
     if (cls.key_dest & (KEY_CONSOLE | KEY_MENU)) {
         // only pause in single player
         if (cl_paused->integer == 0 && cl_autopause->integer) {
             Cvar_Set("cl_paused", "1");
         }
     } else if (cl_paused->integer == 1) {
         // only resume after automatic pause
         Cvar_Set("cl_paused", "0");
     }
     // hack for demo playback pause/unpause
     if (cls.demo.playback) {
         // don't pause when running timedemo!
         if (cl_paused->integer && !com_timedemo->integer) {
             if (!sv_paused->integer) {
                 Cvar_Set("sv_paused", "1");
                 IN_Activate();
             }
         } else {
             if (sv_paused->integer) {
                 Cvar_Set("sv_paused", "0");
                 IN_Activate();
             }
         }
     }
 }
Referenced by CL_Changing_f(), CL_ClearState(), CL_Disconnect(), CL_Pause_f(), Key_SetDest(), and set_active_state().
CL_CheckForResend()
void CL_CheckForResend (void)
Definition at line 387 of file main.c.
 {
     char tail[MAX_QPATH];
     char userinfo[MAX_INFO_STRING];
     int maxmsglen;
     if (cls.demo.playback) {
         return;
     }
     // if the local server is running and we aren't
     // then connect
     if (cls.state < ca_connecting && sv_running->integer > ss_loading) {
         strcpy(cls.servername, "localhost");
         cls.serverAddress.type = NA_LOOPBACK;
         cls.serverProtocol = cl_protocol->integer;
         if (cls.serverProtocol < PROTOCOL_VERSION_DEFAULT ||
             cls.serverProtocol > PROTOCOL_VERSION_Q2PRO) {
             cls.serverProtocol = PROTOCOL_VERSION_Q2PRO;
         }
         // we don't need a challenge on the localhost
         cls.state = ca_connecting;
         cls.connect_time -= CONNECT_FAST;
         cls.connect_count = 0;
         cls.passive = qfalse;
         Con_Popup(qtrue);
         UI_OpenMenu(UIMENU_NONE);
     }
     // resend if we haven't gotten a reply yet
     if (cls.state != ca_connecting && cls.state != ca_challenging) {
         return;
     }
     if (cls.realtime - cls.connect_time < CONNECT_DELAY) {
         return;
     }
     cls.connect_time = cls.realtime;    // for retransmit requests
     cls.connect_count++;
     if (cls.state == ca_challenging) {
         Com_Printf("Requesting challenge... %i\n", cls.connect_count);
         OOB_PRINT(NS_CLIENT, &cls.serverAddress, "getchallenge\n");
         return;
     }
     //
     // We have gotten a challenge from the server, so try and connect.
     //
     Com_Printf("Requesting connection... %i\n", cls.connect_count);
     cls.userinfo_modified = 0;
     // use maximum allowed msglen for loopback
     maxmsglen = net_maxmsglen->integer;
     if (NET_IsLocalAddress(&cls.serverAddress)) {
         maxmsglen = MAX_PACKETLEN_WRITABLE;
     }
     // add protocol dependent stuff
     switch (cls.serverProtocol) {
     case PROTOCOL_VERSION_R1Q2:
         Q_snprintf(tail, sizeof(tail), " %d %d",
                    maxmsglen, PROTOCOL_VERSION_R1Q2_CURRENT);
         cls.quakePort = net_qport->integer & 0xff;
         break;
     case PROTOCOL_VERSION_Q2PRO:
         Q_snprintf(tail, sizeof(tail), " %d %d %d %d",
                    maxmsglen, net_chantype->integer, USE_ZLIB,
                    PROTOCOL_VERSION_Q2PRO_CURRENT);
         cls.quakePort = net_qport->integer & 0xff;
         break;
     default:
         tail[0] = 0;
         cls.quakePort = net_qport->integer;
         break;
     }
     Cvar_BitInfo(userinfo, CVAR_USERINFO);
     Netchan_OutOfBand(NS_CLIENT, &cls.serverAddress,
                       "connect %i %i %i \"%s\"%s\n", cls.serverProtocol, cls.quakePort,
                       cls.challenge, userinfo, tail);
 }
Referenced by CL_Connect_f(), CL_ConnectionlessPacket(), CL_Frame(), and CL_ParseReconnect().
CL_CheckPredictionError()
void CL_CheckPredictionError (void)
Definition at line 27 of file predict.c.
 {
     int         frame;
     int         delta[3];
     unsigned    cmd;
     int         len;
     if (!cls.netchan) {
         return;
     }
     if (sv_paused->integer) {
         VectorClear(cl.prediction_error);
         return;
     }
     if (!cl_predict->integer || (cl.frame.ps.pmove.pm_flags & PMF_NO_PREDICTION))
         return;
     // calculate the last usercmd_t we sent that the server has processed
     frame = cls.netchan->incoming_acknowledged & CMD_MASK;
     cmd = cl.history[frame].cmdNumber;
     // compare what the server returned with what we had predicted it to be
     VectorSubtract(cl.frame.ps.pmove.origin, cl.predicted_origins[cmd & CMD_MASK], delta);
     // save the prediction error for interpolation
     len = abs(delta[0]) + abs(delta[1]) + abs(delta[2]);
     if (len < 1 || len > 640) {
         // > 80 world units is a teleport or something
         VectorClear(cl.prediction_error);
         return;
     }
     SHOWMISS("prediction miss on %i: %i (%d %d %d)\n",
              cl.frame.number, len, delta[0], delta[1], delta[2]);
     // don't predict steps against server returned data
     if (cl.predicted_step_frame <= cmd)
         cl.predicted_step_frame = cmd + 1;
     VectorCopy(cl.frame.ps.pmove.origin, cl.predicted_origins[cmd & CMD_MASK]);
     // save for error interpolation
     VectorScale(delta, 0.125f, cl.prediction_error);
 }
Referenced by CL_DeltaFrame().
CL_CleanupDemos()
void CL_CleanupDemos (void)
Definition at line 1179 of file demo.c.
 {
     demosnap_t *snap, *next;
     size_t total;
     if (cls.demo.recording) {
         CL_Stop_f();
     }
     if (cls.demo.playback) {
         FS_FCloseFile(cls.demo.playback);
         if (com_timedemo->integer && cls.demo.time_frames) {
             unsigned msec = Sys_Milliseconds();
             if (msec > cls.demo.time_start) {
                 float sec = (msec - cls.demo.time_start) * 0.001f;
                 float fps = cls.demo.time_frames / sec;
                 Com_Printf("%u frames, %3.1f seconds: %3.1f fps\n",
                            cls.demo.time_frames, sec, fps);
             }
         }
     }
     total = 0;
     LIST_FOR_EACH_SAFE(demosnap_t, snap, next, &cls.demo.snapshots, entry) {
         total += snap->msglen;
         Z_Free(snap);
     }
     if (total)
         Com_DPrintf("Freed %"PRIz" bytes of snaps\n", total);
     memset(&cls.demo, 0, sizeof(cls.demo));
     List_Init(&cls.demo.snapshots);
 }
Referenced by CL_Disconnect().
CL_CleanupDownloads()
void CL_CleanupDownloads (void)
Definition at line 136 of file download.c.
 {
     dlqueue_t *q, *n;
     HTTP_CleanupDownloads();
     FOR_EACH_DLQ_SAFE(q, n) {
         Z_Free(q);
     }
     List_Init(&cls.download.queue);
     cls.download.pending = 0;
     cls.download.current = NULL;
     cls.download.percent = 0;
     cls.download.position = 0;
     if (cls.download.file) {
         FS_FCloseFile(cls.download.file);
         cls.download.file = 0;
     }
     cls.download.temp[0] = 0;
 #if USE_ZLIB
     inflateEnd(&cls.download.z);
 #endif
 }
Referenced by CL_Disconnect().
CL_ClearEffects()
void CL_ClearEffects (void)
Definition at line 2067 of file effects.c.
 {
     CL_ClearParticles();
 #if USE_DLIGHTS
     CL_ClearDlights();
 #endif
 }
Referenced by CL_ClearState(), and CL_Seek_f().
CL_ClearState()
void CL_ClearState (void)
Definition at line 699 of file main.c.
 {
     S_StopAllSounds();
     CL_ClearEffects();
 #if USE_LIGHTSTYLES
     CL_ClearLightStyles();
 #endif
     CL_ClearTEnts();
     LOC_FreeLocations();
     // wipe the entire cl structure
     BSP_Free(cl.bsp);
     memset(&cl, 0, sizeof(cl));
     memset(&cl_entities, 0, sizeof(cl_entities));
     if (cls.state > ca_connected) {
         cls.state = ca_connected;
         CL_CheckForPause();
         CL_UpdateFrameTimes();
     }
     // unprotect game cvar
     fs_game->flags &= ~CVAR_ROM;
 #if USE_REF == REF_GL
     // unprotect our custom modulate cvars
     if(gl_modulate_world) gl_modulate_world->flags &= ~CVAR_CHEAT;
     if(gl_modulate_entities) gl_modulate_entities->flags &= ~CVAR_CHEAT;
     if(gl_brightness) gl_brightness->flags &= ~CVAR_CHEAT;
 #endif
 }
Referenced by CL_Disconnect(), and CL_ParseServerData().
CL_ClearTEnts()
void CL_ClearTEnts (void)
Definition at line 1459 of file tent.c.
 {
     CL_ClearBeams();
     CL_ClearExplosions();
     CL_ClearLasers();
     CL_ClearSustains();
 }
Referenced by CL_ClearState(), and CL_Seek_f().
CL_ClientCommand()
void CL_ClientCommand (const char * string)
Definition at line 299 of file main.c.
 {
     if (!cls.netchan) {
         return;
     }
     Com_DDPrintf("%s: %s\n", __func__, string);
     MSG_WriteByte(clc_stringcmd);
     MSG_WriteString(string);
     MSG_FlushTo(&cls.netchan->message);
 }
Referenced by CL_Begin(), CL_ConnectionlessPacket(), CL_ForwardToServer(), CL_ForwardToServer_f(), CL_HandleDownload(), CL_Reconnect_f(), Con_Say(), HTTP_QueueDownload(), Key_Event(), SCR_FinishCinematic(), and start_udp_download().
CL_ColorExplosionParticles()
void CL_ColorExplosionParticles (vec3_t org, int color, int run)
Definition at line 690 of file newfx.c.
 {
     int         i, j;
     cparticle_t *p;
     for (i = 0; i < 128; i++) {
         p = CL_AllocParticle();
         if (!p)
             return;
         p->time = cl.time;
         p->color = color + (rand() % run);
         for (j = 0; j < 3; j++) {
             p->org[j] = org[j] + ((rand() % 32) - 16);
             p->vel[j] = (rand() % 256) - 128;
         }
         p->accel[0] = p->accel[1] = 0;
         p->accel[2] = -PARTICLE_GRAVITY;
         p->alpha = 1.0;
         p->alphavel = -0.4 / (0.6 + frand() * 0.2);
     }
 }
Referenced by CL_ParseTEnt().
CL_DebugTrail()
void CL_DebugTrail (vec3_t start, vec3_t end)
Definition at line 63 of file newfx.c.
 {
     vec3_t      move;
     vec3_t      vec;
     float       len;
     cparticle_t *p;
     float       dec;
     vec3_t      right, up;
     VectorCopy(start, move);
     VectorSubtract(end, start, vec);
     len = VectorNormalize(vec);
     MakeNormalVectors(vec, right, up);
     dec = 3;
     VectorScale(vec, dec, vec);
     VectorCopy(start, move);
     while (len > 0) {
         len -= dec;
         p = CL_AllocParticle();
         if (!p)
             return;
         p->time = cl.time;
         VectorClear(p->accel);
         VectorClear(p->vel);
         p->alpha = 1.0;
         p->alphavel = -0.1;
         p->color = 0x74 + (rand() & 7);
         VectorCopy(move, p->org);
         VectorAdd(move, vec, move);
     }
 }
Referenced by CL_ParseTEnt().
CL_DeltaFrame()
void CL_DeltaFrame (void)
Definition at line 358 of file entities.c.
 {
     centity_t           *ent;
     entity_state_t      *state;
     int                 i, j;
     int                 framenum;
     int                 prevstate = cls.state;
     // getting a valid frame message ends the connection process
     if (cls.state == ca_precached)
         set_active_state();
     // set server time
     framenum = cl.frame.number - cl.serverdelta;
     cl.servertime = framenum * CL_FRAMETIME;
 #if USE_FPS
     cl.keyservertime = (framenum / cl.framediv) * BASE_FRAMETIME;
 #endif
     // rebuild the list of solid entities for this frame
     cl.numSolidEntities = 0;
     // initialize position of the player's own entity from playerstate.
     // this is needed in situations when player entity is invisible, but
     // server sends an effect referencing it's origin (such as MZ_LOGIN, etc)
     ent = &cl_entities[cl.frame.clientNum + 1];
     Com_PlayerToEntityState(&cl.frame.ps, &ent->current);
     for (i = 0; i < cl.frame.numEntities; i++) {
         j = (cl.frame.firstEntity + i) & PARSE_ENTITIES_MASK;
         state = &cl.entityStates[j];
         // set current and prev
         entity_update(state);
         // fire events
         entity_event(state->number);
     }
     if (cls.demo.recording && !cls.demo.paused && !cls.demo.seeking && CL_FRAMESYNC) {
         CL_EmitDemoFrame();
     }
     if (prevstate == ca_precached)
         CL_GTV_Resume();
     else
         CL_GTV_EmitFrame();
     if (cls.demo.playback) {
         // this delta has nothing to do with local viewangles,
         // clear it to avoid interfering with demo freelook hack
         VectorClear(cl.frame.ps.pmove.delta_angles);
     }
     if (cl.oldframe.ps.pmove.pm_type != cl.frame.ps.pmove.pm_type) {
         IN_Activate();
     }
     player_update(&cl.oldframe, &cl.frame, 1);
 #if USE_FPS
     if (CL_FRAMESYNC)
         player_update(&cl.oldkeyframe, &cl.keyframe, cl.framediv);
 #endif
     CL_CheckPredictionError();
     SCR_SetCrosshairColor();
 }
Referenced by CL_ParseFrame(), and CL_Seek_f().
CL_DemoFrame()
void CL_DemoFrame (int msec)
Definition at line 1223 of file demo.c.
 {
     if (cls.state < ca_connected) {
         return;
     }
     if (cls.state != ca_active) {
         parse_next_message(0);
         return;
     }
     if (com_timedemo->integer) {
         parse_next_message(0);
         cl.time = cl.servertime;
         cls.demo.time_frames++;
         return;
     }
     // wait at the end of demo
     if (cls.demo.eof) {
         if (!cl_demowait->integer)
             finish_demo(0);
         return;
     }
     // cl.time has already been advanced for this client frame
     // read the next frame to start lerp cycle again
     while (cl.servertime < cl.time) {
         if (parse_next_message(cl_demowait->integer))
             break;
         if (cls.state != ca_active)
             break;
     }
 }
Referenced by CL_Frame().
CL_DiminishingTrail()
void CL_DiminishingTrail (vec3_t start, vec3_t end, centity_t * old, int flags)
Definition at line 1484 of file effects.c.
 {
     vec3_t      move;
     vec3_t      vec;
     float       len;
     int         j;
     cparticle_t *p;
     float       dec;
     float       orgscale;
     float       velscale;
     VectorCopy(start, move);
     VectorSubtract(end, start, vec);
     len = VectorNormalize(vec);
     dec = 0.5;
     VectorScale(vec, dec, vec);
     if (old->trailcount > 900) {
         orgscale = 4;
         velscale = 15;
     } else if (old->trailcount > 800) {
         orgscale = 2;
         velscale = 10;
     } else {
         orgscale = 1;
         velscale = 5;
     }
     while (len > 0) {
         len -= dec;
         // drop less particles as it flies
         if ((rand() & 1023) < old->trailcount) {
             p = CL_AllocParticle();
             if (!p)
                 return;
             VectorClear(p->accel);
             p->time = cl.time;
             if (flags & EF_GIB) {
                 p->alpha = 1.0;
                 p->alphavel = -1.0 / (1 + frand() * 0.4);
                 p->color = 0xe8 + (rand() & 7);
                 p->brightness = 1.0f;
                 for (j = 0; j < 3; j++) {
                     p->org[j] = move[j] + crand() * orgscale;
                     p->vel[j] = crand() * velscale;
                     p->accel[j] = 0;
                 }
                 p->vel[2] -= PARTICLE_GRAVITY;
             } else if (flags & EF_GREENGIB) {
                 p->alpha = 1.0;
                 p->alphavel = -1.0 / (1 + frand() * 0.4);
                 p->color = 0xdb + (rand() & 7);
                 p->brightness = 1.0f;
                 for (j = 0; j < 3; j++) {
                     p->org[j] = move[j] + crand() * orgscale;
                     p->vel[j] = crand() * velscale;
                     p->accel[j] = 0;
                 }
                 p->vel[2] -= PARTICLE_GRAVITY;
             } else {
                 p->alpha = 1.0;
                 p->alphavel = -1.0 / (1 + frand() * 0.2);
                 p->color = 4 + (rand() & 7);
                 p->brightness = 1.0f;
                 for (j = 0; j < 3; j++) {
                     p->org[j] = move[j] + crand() * orgscale;
                     p->vel[j] = crand() * velscale;
                 }
                 p->accel[2] = 20;
             }
         }
         old->trailcount -= 5;
         if (old->trailcount < 100)
             old->trailcount = 100;
         VectorAdd(move, vec, move);
     }
 }
Referenced by CL_AddPacketEntities(), and CL_RocketTrail().
CL_Disconnect()
void CL_Disconnect (error_type_t type)
Definition at line 740 of file main.c.
 {
     if (!cls.state) {
         return;
     }
     SCR_EndLoadingPlaque(); // get rid of loading plaque
     SCR_ClearChatHUD_f();   // clear chat HUD on server change
     if (cls.state > ca_disconnected && !cls.demo.playback) {
         EXEC_TRIGGER(cl_disconnectcmd);
     }
 #if 0
     if (cls.ref_initialized) {
         R_CinematicSetPalette(NULL);
     }
 #endif
     //cls.connect_time = 0;
     //cls.connect_count = 0;
     cls.passive = qfalse;
 #if USE_ICMP
     cls.errorReceived = qfalse;
 #endif
     if (cls.netchan) {
         // send a disconnect message to the server
         MSG_WriteByte(clc_stringcmd);
         MSG_WriteData("disconnect", 11);
         cls.netchan->Transmit(cls.netchan, msg_write.cursize, msg_write.data, 3);
         SZ_Clear(&msg_write);
         Netchan_Close(cls.netchan);
         cls.netchan = NULL;
     }
     // stop playback and/or recording
     CL_CleanupDemos();
     // stop download
     CL_CleanupDownloads();
     CL_ClearState();
     CL_GTV_Suspend();
     cls.state = ca_disconnected;
     cls.userinfo_modified = 0;
     if (type == ERR_DISCONNECT) {
         UI_OpenMenu(UIMENU_DEFAULT);
     } else {
         UI_OpenMenu(UIMENU_NONE);
     }
     CL_CheckForPause();
     CL_UpdateFrameTimes();
 }
Referenced by CL_Connect_f(), CL_ParseReconnect(), CL_PassiveConnect_f(), CL_PlayDemo_f(), CL_Reconnect_f(), CL_Shutdown(), Com_Error(), finish_demo(), and SV_InitGame().
CL_EmitDemoFrame()
void CL_EmitDemoFrame (void)
Definition at line 186 of file demo.c.
 {
     server_frame_t  *oldframe;
     int             lastframe;
     if (!cl.frame.valid)
         return;
     // the first frame is delta uncompressed
     if (cls.demo.last_server_frame == -1) {
         oldframe = NULL;
         lastframe = -1;
     } else {
         oldframe = &cl.frames[cls.demo.last_server_frame & UPDATE_MASK];
         lastframe = FRAME_PRE;
         if (oldframe->number != cls.demo.last_server_frame || !oldframe->valid ||
             cl.numEntityStates - oldframe->firstEntity > MAX_PARSE_ENTITIES) {
             oldframe = NULL;
             lastframe = -1;
         }
     }
     // emit and flush frame
     emit_delta_frame(oldframe, &cl.frame, lastframe, FRAME_CUR);
     if (cls.demo.buffer.cursize + msg_write.cursize > cls.demo.buffer.maxsize) {
         Com_DPrintf("Demo frame overflowed (%"PRIz" + %"PRIz" > %"PRIz")\n",
                     cls.demo.buffer.cursize, msg_write.cursize, cls.demo.buffer.maxsize);
         cls.demo.frames_dropped++;
         // warn the user if drop rate is too high
         if (cls.demo.frames_written < 10 && cls.demo.frames_dropped == 50)
             Com_WPrintf("Too many demo frames don't fit into %"PRIz" bytes.\n"
                         "Try to increase 'cl_demomsglen' value and restart recording.\n",
                         cls.demo.buffer.maxsize);
     } else {
         SZ_Write(&cls.demo.buffer, msg_write.data, msg_write.cursize);
         cls.demo.last_server_frame = cl.frame.number;
         cls.demo.frames_written++;
     }
     SZ_Clear(&msg_write);
 }
Referenced by CL_DeltaFrame(), and resume_record().
CL_EmitDemoSnapshot()
void CL_EmitDemoSnapshot (void)
Definition at line 773 of file demo.c.
 {
     demosnap_t *snap;
     off_t pos;
     char *from, *to;
     size_t len;
     server_frame_t *lastframe, *frame;
     int i, j, lastnum;
     if (cl_demosnaps->integer <= 0)
         return;
     if (cls.demo.frames_read < cls.demo.last_snapshot + cl_demosnaps->integer * 10)
         return;
     if (!cl.frame.valid)
         return;
     if (!cls.demo.file_size)
         return;
     pos = FS_Tell(cls.demo.playback);
     if (pos < cls.demo.file_offset)
         return;
     // write all the backups, since we can't predict what frame the next
     // delta will come from
     lastframe = NULL;
     lastnum = -1;
     for (i = 0; i < UPDATE_BACKUP; i++) {
         j = cl.frame.number - (UPDATE_BACKUP - 1) + i;
         frame = &cl.frames[j & UPDATE_MASK];
         if (frame->number != j || !frame->valid ||
             cl.numEntityStates - frame->firstEntity > MAX_PARSE_ENTITIES) {
             continue;
         }
         emit_delta_frame(lastframe, frame, lastnum, j);
         lastframe = frame;
         lastnum = frame->number;
     }
     // write configstrings
     for (i = 0; i < MAX_CONFIGSTRINGS; i++) {
         from = cl.baseconfigstrings[i];
         to = cl.configstrings[i];
         if (!strcmp(from, to))
             continue;
         len = strlen(to);
         if (len > MAX_QPATH)
             len = MAX_QPATH;
         MSG_WriteByte(svc_configstring);
         MSG_WriteShort(i);
         MSG_WriteData(to, len);
         MSG_WriteByte(0);
     }
     // write layout
     MSG_WriteByte(svc_layout);
     MSG_WriteString(cl.layout);
     snap = Z_Malloc(sizeof(*snap) + msg_write.cursize - 1);
     snap->framenum = cls.demo.frames_read;
     snap->filepos = pos;
     snap->msglen = msg_write.cursize;
     memcpy(snap->data, msg_write.data, msg_write.cursize);
     List_Append(&cls.demo.snapshots, &snap->entry);
     Com_DPrintf("[%d] snaplen %"PRIz"\n", cls.demo.frames_read, msg_write.cursize);
     SZ_Clear(&msg_write);
     cls.demo.last_snapshot = cls.demo.frames_read;
 }
Referenced by CL_Seek_f(), and parse_next_message().
CL_ExplosionParticles()
void CL_ExplosionParticles (vec3_t org)
Definition at line 1221 of file effects.c.
 {
     int         i, j;
     cparticle_t *p;
     const int count = 256 * cl_particle_num_factor->value;
     for (i = 0; i < count; i++) {
         p = CL_AllocParticle();
         if (!p)
             return;
         p->time = cl.time;
         p->color = 0xe0 + (rand() & 7);
         p->brightness = cvar_pt_particle_emissive->value;
         for (j = 0; j < 3; j++) {
             p->org[j] = org[j] + ((rand() % 32) - 16);
             p->vel[j] = (rand() % 384) - 192;
         }
         p->accel[0] = p->accel[1] = 0;
         p->accel[2] = -PARTICLE_GRAVITY;
         p->alpha = 1.0;
         p->alphavel = -0.8 / (0.5 + frand() * 0.3);
     }
 }
Referenced by CL_ParseTEnt().
CL_FinalizeCmd()
void CL_FinalizeCmd (void)
Definition at line 790 of file input.c.
 {
     vec3_t move;
     // command buffer ticks in sync with cl_maxfps
     if (cmd_buffer.waitCount > 0) {
         cmd_buffer.waitCount--;
     }
     if (cl_cmdbuf.waitCount > 0) {
         cl_cmdbuf.waitCount--;
     }
     if (cls.state != ca_active) {
         return; // not talking to a server
     }
     if (sv_paused->integer) {
         return;
     }
 //
 // figure button bits
 //
     if (in_attack.state & 3)
         cl.cmd.buttons |= BUTTON_ATTACK;
     if (in_use.state & 3)
         cl.cmd.buttons |= BUTTON_USE;
     in_attack.state &= ~2;
     in_use.state &= ~2;
     if (cls.key_dest == KEY_GAME && Key_AnyKeyDown()) {
         cl.cmd.buttons |= BUTTON_ANY;
     }
     if (cl.cmd.msec > 250) {
         cl.cmd.msec = 100;        // time was unreasonable
     }
     // rebuild the movement vector
     VectorClear(move);
     // get basic movement from keyboard
     CL_BaseMove(move);
     // add mouse forward/side movement
     move[0] += cl.mousemove[0];
     move[1] += cl.mousemove[1];
     // clamp to server defined max speed
     CL_ClampSpeed(move);
     // store the movement vector
     cl.cmd.forwardmove = move[0];
     cl.cmd.sidemove = move[1];
     cl.cmd.upmove = move[2];
     // clear all states
     cl.mousemove[0] = 0;
     cl.mousemove[1] = 0;
     KeyClear(&in_right);
     KeyClear(&in_left);
     KeyClear(&in_moveright);
     KeyClear(&in_moveleft);
     KeyClear(&in_up);
     KeyClear(&in_down);
     KeyClear(&in_forward);
     KeyClear(&in_back);
     KeyClear(&in_lookup);
     KeyClear(&in_lookdown);
     cl.cmd.impulse = in_impulse;
     in_impulse = 0;
     // save this command off for prediction
     cl.cmdNumber++;
     cl.cmds[cl.cmdNumber & CMD_MASK] = cl.cmd;
     // clear pending cmd
     memset(&cl.cmd, 0, sizeof(cl.cmd));
 }
Referenced by CL_Frame().
CL_FinishDownload()
void CL_FinishDownload (dlqueue_t * q)
Definition at line 115 of file download.c.
 {
     if (q->state == DL_DONE) {
         Com_Error(ERR_DROP, "%s: already done", __func__);
     }
     if (!cls.download.pending) {
         Com_Error(ERR_DROP, "%s: bad pending count", __func__);
     }
     q->state = DL_DONE;
     cls.download.pending--;
     Com_DPrintf("%s: %s [%d]\n", __func__, q->path, cls.download.pending);
 }
Referenced by abort_downloads(), finish_download(), finish_udp_download(), rescan_queue(), start_download(), and start_udp_download().
CL_FirstDemoFrame()
void CL_FirstDemoFrame (void)
Definition at line 876 of file demo.c.
 {
     ssize_t len, ofs;
     Com_DPrintf("[%d] first frame\n", cl.frame.number);
     // save base configstrings
     memcpy(cl.baseconfigstrings, cl.configstrings, sizeof(cl.baseconfigstrings));
     // obtain file length and offset of the second frame
     len = FS_Length(cls.demo.playback);
     ofs = FS_Tell(cls.demo.playback);
     if (len > 0 && ofs > 0) {
         cls.demo.file_offset = ofs;
         cls.demo.file_size = len - ofs;
     }
     // begin timedemo
     if (com_timedemo->integer) {
         cls.demo.time_frames = 0;
         cls.demo.time_start = Sys_Milliseconds();
     }
     // force initial snapshot
     cls.demo.last_snapshot = INT_MIN;
 }
Referenced by set_active_state().
CL_FlagTrail()
void CL_FlagTrail (vec3_t start, vec3_t end, int color)
Definition at line 1436 of file effects.c.
 {
     vec3_t      move;
     vec3_t      vec;
     float       len;
     int         j;
     cparticle_t *p;
     int         dec;
     VectorCopy(start, move);
     VectorSubtract(end, start, vec);
     len = VectorNormalize(vec);
     dec = 5;
     VectorScale(vec, 5, vec);
     while (len > 0) {
         len -= dec;
         p = CL_AllocParticle();
         if (!p)
             return;
         VectorClear(p->accel);
         p->time = cl.time;
         p->alpha = 1.0;
         p->alphavel = -1.0 / (0.8 + frand() * 0.2);
         p->color = color;
         p->brightness = 1.0f;
         for (j = 0; j < 3; j++) {
             p->org[j] = move[j] + crand() * 16;
             p->vel[j] = crand() * 5;
             p->accel[j] = 0;
         }
         VectorAdd(move, vec, move);
     }
 }
Referenced by CL_AddPacketEntities().
CL_FlyEffect()
void CL_FlyEffect (centity_t * ent, vec3_t origin)
Definition at line 1815 of file effects.c.
 {
     int     n;
     int     count;
     int     starttime;
     if (ent->fly_stoptime < cl.time) {
         starttime = cl.time;
         ent->fly_stoptime = cl.time + 60000;
     } else {
         starttime = ent->fly_stoptime - 60000;
     }
     n = cl.time - starttime;
     if (n < 20000)
         count = n * 162 / 20000.0;
     else {
         n = ent->fly_stoptime - cl.time;
         if (n < 20000)
             count = n * 162 / 20000.0;
         else
             count = 162;
     }
     CL_FlyParticles(origin, count);
 }
Referenced by CL_AddPacketEntities().
CL_ForceWall()
void CL_ForceWall (vec3_t start, vec3_t end, int color)
Definition at line 143 of file newfx.c.
 {
     vec3_t      move;
     vec3_t      vec;
     float       len;
     int         j;
     cparticle_t *p;
     VectorCopy(start, move);
     VectorSubtract(end, start, vec);
     len = VectorNormalize(vec);
     VectorScale(vec, 4, vec);
     // FIXME: this is a really silly way to have a loop
     while (len > 0) {
         len -= 4;
         if (frand() > 0.3) {
             p = CL_AllocParticle();
             if (!p)
                 return;
             VectorClear(p->accel);
             p->time = cl.time;
             p->alpha = 1.0;
             p->alphavel =  -1.0 / (3.0 + frand() * 0.5);
             p->color = color;
             for (j = 0; j < 3; j++) {
                 p->org[j] = move[j] + crand() * 3;
                 p->accel[j] = 0;
             }
             p->vel[0] = 0;
             p->vel[1] = 0;
             p->vel[2] = -40 - (crand() * 10);
         }
         VectorAdd(move, vec, move);
     }
 }
Referenced by CL_ParseTEnt().
CL_GenericParticleEffect()
void CL_GenericParticleEffect (vec3_t org, vec3_t dir, int color, int count, int numcolors, int dirspread, float alphavel)
Definition at line 191 of file newfx.c.
 {
     int         i, j;
     cparticle_t *p;
     float       d;
     for (i = 0; i < count; i++) {
         p = CL_AllocParticle();
         if (!p)
             return;
         p->time = cl.time;
         if (numcolors > 1)
             p->color = color + (rand() & numcolors);
         else
             p->color = color;
         d = rand() & dirspread;
         for (j = 0; j < 3; j++) {
             p->org[j] = org[j] + ((rand() & 7) - 4) + d * dir[j];
             p->vel[j] = crand() * 20;
         }
         p->accel[0] = p->accel[1] = 0;
         p->accel[2] = -PARTICLE_GRAVITY;
         p->alpha = 1.0;
         p->alphavel = -1.0 / (0.5 + frand() * alphavel);
     }
 }
CL_GetDemoInfo()
demoInfo_t* CL_GetDemoInfo (const char * path, demoInfo_t * info)
Definition at line 1091 of file demo.c.
 {
     qhandle_t f;
     int c, index;
     char string[MAX_QPATH];
     int clientNum, type;
     FS_FOpenFile(path, &f, FS_MODE_READ);
     if (!f) {
         return NULL;
     }
     type = read_first_message(f);
     if (type < 0) {
         goto fail;
     }
     if (type == 0) {
         if (MSG_ReadByte() != svc_serverdata) {
             goto fail;
         }
         if (MSG_ReadLong() != PROTOCOL_VERSION_DEFAULT) {
             goto fail;
         }
         MSG_ReadLong();
         MSG_ReadByte();
         MSG_ReadString(NULL, 0);
         clientNum = MSG_ReadShort();
         MSG_ReadString(NULL, 0);
         while (1) {
             c = MSG_ReadByte();
             if (c == -1) {
                 if (read_next_message(f) <= 0) {
                     break;
                 }
                 continue; // parse new message
             }
             if (c != svc_configstring) {
                 break;
             }
             index = MSG_ReadShort();
             if (index < 0 || index >= MAX_CONFIGSTRINGS) {
                 goto fail;
             }
             MSG_ReadString(string, sizeof(string));
             parse_info_string(info, clientNum, index, string);
         }
         info->mvd = qfalse;
     } else {
         if ((MSG_ReadByte() & SVCMD_MASK) != mvd_serverdata) {
             goto fail;
         }
         if (MSG_ReadLong() != PROTOCOL_VERSION_MVD) {
             goto fail;
         }
         MSG_ReadShort();
         MSG_ReadLong();
         MSG_ReadString(NULL, 0);
         clientNum = MSG_ReadShort();
         while (1) {
             index = MSG_ReadShort();
             if (index == MAX_CONFIGSTRINGS) {
                 break;
             }
             if (index < 0 || index >= MAX_CONFIGSTRINGS) {
                 goto fail;
             }
             MSG_ReadString(string, sizeof(string));
             parse_info_string(info, clientNum, index, string);
         }
         info->mvd = qtrue;
     }
     FS_FCloseFile(f);
     return info;
 fail:
     FS_FCloseFile(f);
     return NULL;
 }
Referenced by BuildName().
CL_GetEntitySoundOrigin()
void CL_GetEntitySoundOrigin (int ent, vec3_t org)
Definition at line 1404 of file entities.c.
 {
     centity_t   *ent;
     mmodel_t    *cm;
     vec3_t      mid;
     if (entnum < 0 || entnum >= MAX_EDICTS) {
         Com_Error(ERR_DROP, "%s: bad entnum: %d", __func__, entnum);
     }
     if (!entnum || entnum == listener_entnum) {
         // should this ever happen?
         VectorCopy(listener_origin, org);
         return;
     }
     // interpolate origin
     // FIXME: what should be the sound origin point for RF_BEAM entities?
     ent = &cl_entities[entnum];
     LerpVector(ent->prev.origin, ent->current.origin, cl.lerpfrac, org);
     // offset the origin for BSP models
     if (ent->current.solid == PACKED_BSP) {
         cm = cl.model_clip[ent->current.modelindex];
         if (cm) {
             VectorAvg(cm->mins, cm->maxs, mid);
             VectorAdd(org, mid, org);
         }
     }
 }
Referenced by AL_AddLoopSounds(), and AL_Spatialize().
CL_HandleDownload()
void CL_HandleDownload (byte * data, int size, int percent, int compressed)
Definition at line 424 of file download.c.
 {
     dlqueue_t *q = cls.download.current;
     qerror_t ret;
     if (!q) {
         Com_Error(ERR_DROP, "%s: no download requested", __func__);
     }
     if (size == -1) {
         if (!percent) {
             finish_udp_download("FAIL");
         } else {
             finish_udp_download("STOP");
         }
         return;
     }
     // open the file if not opened yet
     if (!cls.download.file) {
         ret = FS_FOpenFile(cls.download.temp, &cls.download.file, FS_MODE_WRITE);
         if (!cls.download.file) {
             Com_EPrintf("[UDP] Couldn't open %s for writing: %s\n",
                         cls.download.temp, Q_ErrorString(ret));
             finish_udp_download(NULL);
             return;
         }
     }
     if (compressed) {
         if (inflate_udp_download(data, size, compressed))
             return;
     } else {
         if (write_udp_download(data, size))
             return;
     }
     if (percent != 100) {
         // request next block
         // change display routines by zoid
         cls.download.percent = percent;
         cls.download.position += size;
         CL_ClientCommand("nextdl");
     } else {
         // close the file before renaming
         FS_FCloseFile(cls.download.file);
         cls.download.file = 0;
         // rename the temp file to its final name
         ret = FS_RenameFile(cls.download.temp, q->path);
         if (ret) {
             Com_EPrintf("[UDP] Couldn't rename %s to %s: %s\n",
                         cls.download.temp, q->path, Q_ErrorString(ret));
             finish_udp_download(NULL);
         } else {
             finish_udp_download("DONE");
         }
     }
 }
Referenced by CL_ParseDownload().
CL_Heatbeam()
void CL_Heatbeam (vec3_t start, vec3_t end)
Definition at line 266 of file newfx.c.
 {
     vec3_t      move;
     vec3_t      vec;
     float       len;
     int         j;
     cparticle_t *p;
     int         i;
     float       c, s;
     vec3_t      dir;
     float       ltime;
     float       step = 32.0, rstep;
     float       start_pt;
     float       rot;
     float       variance;
     vec3_t      end;
     VectorMA(start, 4096, forward, end);
     VectorCopy(start, move);
     VectorSubtract(end, start, vec);
     len = VectorNormalize(vec);
     ltime = (float) cl.time / 1000.0;
     start_pt = fmod(ltime * 96.0, step);
     VectorMA(move, start_pt, vec, move);
     VectorScale(vec, step, vec);
     rstep = M_PI / 10.0;
     for (i = start_pt; i < len; i += step) {
         if (i > step * 5) // don't bother after the 5th ring
             break;
         for (rot = 0; rot < M_PI * 2; rot += rstep) {
             p = CL_AllocParticle();
             if (!p)
                 return;
             p->time = cl.time;
             VectorClear(p->accel);
             variance = 0.5;
             c = cos(rot) * variance;
             s = sin(rot) * variance;
             // trim it so it looks like it's starting at the origin
             if (i < 10) {
                 VectorScale(cl.v_right, c * (i / 10.0), dir);
                 VectorMA(dir, s * (i / 10.0), cl.v_up, dir);
             } else {
                 VectorScale(cl.v_right, c, dir);
                 VectorMA(dir, s, cl.v_up, dir);
             }
             p->alpha = 0.5;
             p->alphavel = -1000.0;
             p->color = 223 - (rand() & 7);
             for (j = 0; j < 3; j++) {
                 p->org[j] = move[j] + dir[j] * 3;
                 p->vel[j] = 0;
             }
         }
         VectorAdd(move, vec, move);
     }
 }
Referenced by CL_AddPlayerBeams().
CL_IgnoreDownload()
qboolean CL_IgnoreDownload (const char * path)
Definition at line 95 of file download.c.
 {
     string_entry_t *entry;
     for (entry = cls.download.ignores; entry; entry = entry->next) {
         if (Com_WildCmp(entry->string, path)) {
             return qtrue;
         }
     }
     return qfalse;
 }
Referenced by check_and_queue_download(), and check_file_len().
CL_Init()
void CL_Init (void)
Definition at line 3414 of file main.c.
 {
     if (dedicated->integer) {
         return; // nothing running on the client
     }
     if (cl_running->integer) {
         return;
     }
     // all archived variables will now be loaded
     // start with full screen console
     cls.key_dest = KEY_CONSOLE;
 #ifdef _WIN32
     CL_InitRefresh();
     S_Init();   // sound must be initialized after window is created
 #else
     S_Init();
     CL_InitRefresh();
 #endif
     CL_InitLocal();
     IN_Init();
 #if USE_ZLIB
     if (inflateInit2(&cls.z, -MAX_WBITS) != Z_OK) {
         Com_Error(ERR_FATAL, "%s: inflateInit2() failed", __func__);
     }
 #endif
     CL_LoadDownloadIgnores();
     HTTP_Init();
     UI_OpenMenu(UIMENU_DEFAULT);
     Con_PostInit();
     Con_RunConsole();
     cl_cmdbuf.from = FROM_STUFFTEXT;
     cl_cmdbuf.text = cl_cmdbuf_text;
     cl_cmdbuf.maxsize = sizeof(cl_cmdbuf_text);
     cl_cmdbuf.exec = exec_server_string;
     Cvar_Set("cl_running", "1");
 }
Referenced by Qcommon_Init().
CL_InitAscii()
void CL_InitAscii (void)
Definition at line 370 of file ascii.c.
 {
     Cmd_AddCommand("aashot", SCR_ScoreShot_f);
     Cmd_AddCommand("aadump", SCR_ScoreDump_f);
 }
Referenced by CL_InitLocal().
CL_InitDemos()
void CL_InitDemos (void)
Definition at line 1273 of file demo.c.
 {
     cl_demosnaps = Cvar_Get("cl_demosnaps", "10", 0);
     cl_demomsglen = Cvar_Get("cl_demomsglen", va("%d", MAX_PACKETLEN_WRITABLE_DEFAULT), 0);
     cl_demowait = Cvar_Get("cl_demowait", "0", 0);
     Cmd_Register(c_demo);
     List_Init(&cls.demo.snapshots);
 }
Referenced by CL_InitLocal().
CL_InitDownloads()
void CL_InitDownloads (void)
Definition at line 937 of file download.c.
 {
     Cmd_AddCommand("download", CL_Download_f);
     List_Init(&cls.download.queue);
 }
Referenced by CL_InitLocal().
CL_InitEffects()
void CL_InitEffects (void)
Definition at line 2075 of file effects.c.
 {
     int i, j;
     for (i = 0; i < NUMVERTEXNORMALS; i++)
         for (j = 0; j < 3; j++)
             avelocities[i][j] = (rand() & 255) * 0.01f;
 }
Referenced by CL_InitLocal().
CL_InitRefresh()
void CL_InitRefresh (void)
Definition at line 289 of file refresh.c.
 {
     char *modelist;
     if (cls.ref_initialized) {
         return;
     }
     vid_display = Cvar_Get("vid_display", "0", CVAR_ARCHIVE | CVAR_REFRESH);
     vid_displaylist = Cvar_Get("vid_displaylist", "\"<unknown>\" 0", CVAR_ROM);
     Com_SetLastError(NULL);
     modelist = VID_GetDefaultModeList();
     if (!modelist) {
         Com_Error(ERR_FATAL, "Couldn't initialize refresh: %s", Com_GetLastError());
     }
     // Create the video variables so we know how to start the graphics drivers
     vid_rtx = Cvar_Get("vid_rtx",
 #if REF_VKPT
         "1",
 #else
         "0",
 #endif
         CVAR_REFRESH | CVAR_ARCHIVE);
     vid_fullscreen = Cvar_Get("vid_fullscreen", "0", CVAR_ARCHIVE);
     _vid_fullscreen = Cvar_Get("_vid_fullscreen", "1", CVAR_ARCHIVE);
     vid_modelist = Cvar_Get("vid_modelist", modelist, 0);
     vid_geometry = Cvar_Get("vid_geometry", VID_GEOMETRY, CVAR_ARCHIVE);
     Z_Free(modelist);
     if (vid_fullscreen->integer) {
         Cvar_Set("_vid_fullscreen", vid_fullscreen->string);
     } else if (!_vid_fullscreen->integer) {
         Cvar_Set("_vid_fullscreen", "1");
     }
     Com_SetLastError(NULL);
 #if REF_GL && REF_VKPT
     if (vid_rtx->integer)
         R_RegisterFunctionsRTX();
     else
         R_RegisterFunctionsGL();
 #elif REF_GL
     R_RegisterFunctionsGL();
 #elif REF_VKPT
     R_RegisterFunctionsRTX();
 #else
 #error "REF_GL and REF_VKPT are both disabled, at least one has to be enableds"
 #endif
     if (!R_Init(qtrue)) {
         Com_Error(ERR_FATAL, "Couldn't initialize refresh: %s", Com_GetLastError());
     }
     cls.ref_initialized = qtrue;
     vid_geometry->changed = vid_geometry_changed;
     vid_fullscreen->changed = vid_fullscreen_changed;
     vid_modelist->changed = vid_modelist_changed;
     mode_changed = 0;
     FX_Init();
     // Initialize the rest of graphics subsystems
     V_Init();
     SCR_Init();
     UI_Init();
     SCR_RegisterMedia();
     Con_RegisterMedia();
     cvar_modified &= ~(CVAR_FILES | CVAR_REFRESH);
 }
Referenced by CL_Init(), and CL_RestartRefresh().
CL_InitTEnts()
void CL_InitTEnts (void)
Definition at line 1467 of file tent.c.
 {
     cl_railtrail_type = Cvar_Get("cl_railtrail_type", "0", 0);
     cl_railtrail_time = Cvar_Get("cl_railtrail_time", "1.0", 0);
     cl_railcore_color = Cvar_Get("cl_railcore_color", "red", 0);
     cl_railcore_color->changed = cl_railcore_color_changed;
     cl_railcore_color->generator = Com_Color_g;
     cl_railcore_color_changed(cl_railcore_color);
     cl_railcore_width = Cvar_Get("cl_railcore_width", "2", 0);
     cl_railspiral_color = Cvar_Get("cl_railspiral_color", "blue", 0);
     cl_railspiral_color->changed = cl_railspiral_color_changed;
     cl_railspiral_color->generator = Com_Color_g;
     cl_railspiral_color_changed(cl_railspiral_color);
     cl_railspiral_radius = Cvar_Get("cl_railspiral_radius", "3", 0);
 }
Referenced by CL_InitLocal().
CL_IonripperTrail()
void CL_IonripperTrail (vec3_t start, vec3_t end)
Definition at line 843 of file newfx.c.
 {
     vec3_t  move;
     vec3_t  vec;
     float   len;
     int     j;
     cparticle_t *p;
     int     dec;
     int     left = 0;
     VectorCopy(start, move);
     VectorSubtract(ent, start, vec);
     len = VectorNormalize(vec);
     dec = 5;
     VectorScale(vec, 5, vec);
     while (len > 0) {
         len -= dec;
         p = CL_AllocParticle();
         if (!p)
             return;
         VectorClear(p->accel);
         p->time = cl.time;
         p->alpha = 0.5;
         p->alphavel = -1.0 / (0.3 + frand() * 0.2);
         p->color = 0xe4 + (rand() & 3);
         for (j = 0; j < 3; j++) {
             p->org[j] = move[j];
             p->accel[j] = 0;
         }
         if (left) {
             left = 0;
             p->vel[0] = 10;
         } else {
             left = 1;
             p->vel[0] = -10;
         }
         p->vel[1] = 0;
         p->vel[2] = 0;
         VectorAdd(move, vec, move);
     }
 }
Referenced by CL_AddPacketEntities().
CL_ItemRespawnParticles()
void CL_ItemRespawnParticles (vec3_t org)
Definition at line 1183 of file effects.c.
 {
     int         i, j;
     cparticle_t *p;
     const int count = 64 * cl_particle_num_factor->value;
     for (i = 0; i < count; i++) {
         p = CL_AllocParticle();
         if (!p)
             return;
         p->time = cl.time;
         p->color = 0xd4 + (rand() & 3); // green
         p->brightness = 1.0f;
         p->org[0] = org[0] + crand() * 8;
         p->org[1] = org[1] + crand() * 8;
         p->org[2] = org[2] + crand() * 8;
         for (j = 0; j < 3; j++)
             p->vel[j] = crand() * 8;
         p->accel[0] = p->accel[1] = 0;
         p->accel[2] = -PARTICLE_GRAVITY * 0.2;
         p->alpha = 1.0;
         p->alphavel = -1.0 / (1.0 + frand() * 0.3);
     }
 }
Referenced by entity_event().
CL_LoadClientinfo()
void CL_LoadClientinfo (clientinfo_t * ci, const char * s)
Definition at line 104 of file precache.c.
 {
     int         i;
     char        model_name[MAX_QPATH];
     char        skin_name[MAX_QPATH];
     char        model_filename[MAX_QPATH];
     char        skin_filename[MAX_QPATH];
     char        weapon_filename[MAX_QPATH];
     char        icon_filename[MAX_QPATH];
     CL_ParsePlayerSkin(ci->name, model_name, skin_name, s);
     // model file
     Q_concat(model_filename, sizeof(model_filename),
              "players/", model_name, "/tris.md2", NULL);
     ci->model = R_RegisterModel(model_filename);
     if (!ci->model && Q_stricmp(model_name, "male")) {
         strcpy(model_name, "male");
         strcpy(model_filename, "players/male/tris.md2");
         ci->model = R_RegisterModel(model_filename);
     }
     // skin file
     Q_concat(skin_filename, sizeof(skin_filename),
              "players/", model_name, "/", skin_name, ".pcx", NULL);
     ci->skin = R_RegisterSkin(skin_filename);
     // if we don't have the skin and the model was female,
     // see if athena skin exists
     if (!ci->skin && !Q_stricmp(model_name, "female")) {
         strcpy(skin_name, "athena");
         strcpy(skin_filename, "players/female/athena.pcx");
         ci->skin = R_RegisterSkin(skin_filename);
     }
     // if we don't have the skin and the model wasn't male,
     // see if the male has it (this is for CTF's skins)
     if (!ci->skin && Q_stricmp(model_name, "male")) {
         // change model to male
         strcpy(model_name, "male");
         strcpy(model_filename, "players/male/tris.md2");
         ci->model = R_RegisterModel(model_filename);
         // see if the skin exists for the male model
         Q_concat(skin_filename, sizeof(skin_filename),
                  "players/male/", skin_name, ".pcx", NULL);
         ci->skin = R_RegisterSkin(skin_filename);
     }
     // if we still don't have a skin, it means that the male model
     // didn't have it, so default to grunt
     if (!ci->skin) {
         // see if the skin exists for the male model
         strcpy(skin_name, "grunt");
         strcpy(skin_filename, "players/male/grunt.pcx");
         ci->skin = R_RegisterSkin(skin_filename);
     }
     // weapon file
     for (i = 0; i < cl.numWeaponModels; i++) {
         Q_concat(weapon_filename, sizeof(weapon_filename),
                  "players/", model_name, "/", cl.weaponModels[i], NULL);
         ci->weaponmodel[i] = R_RegisterModel(weapon_filename);
         if (!ci->weaponmodel[i] && !Q_stricmp(model_name, "cyborg")) {
             // try male
             Q_concat(weapon_filename, sizeof(weapon_filename),
                      "players/male/", cl.weaponModels[i], NULL);
             ci->weaponmodel[i] = R_RegisterModel(weapon_filename);
         }
     }
     // icon file
     Q_concat(icon_filename, sizeof(icon_filename),
              "/players/", model_name, "/", skin_name, "_i.pcx", NULL);
     ci->icon = R_RegisterPic2(icon_filename);
     strcpy(ci->model_name, model_name);
     strcpy(ci->skin_name, skin_name);
     // base info should be at least partially valid
     if (ci == &cl.baseclientinfo)
         return;
     // must have loaded all data types to be valid
     if (!ci->skin || !ci->icon || !ci->model || !ci->weaponmodel[0]) {
         ci->skin = 0;
         ci->icon = 0;
         ci->model = 0;
         ci->weaponmodel[0] = 0;
         ci->model_name[0] = 0;
         ci->skin_name[0] = 0;
     }
 }
Referenced by cl_noskins_changed(), CL_PrepRefresh(), CL_Skins_f(), and CL_UpdateConfigstring().
CL_LoadDownloadIgnores()
void CL_LoadDownloadIgnores (void)
Definition at line 173 of file download.c.
 {
     string_entry_t *entry, *next;
     char *raw, *data, *p;
     int count, line;
     ssize_t len;
     // free previous entries
     for (entry = cls.download.ignores; entry; entry = next) {
         next = entry->next;
         Z_Free(entry);
     }
     cls.download.ignores = NULL;
     // load new list
     len = FS_LoadFile(CL_DOWNLOAD_IGNORES, (void **)&raw);
     if (!raw) {
         if (len != Q_ERR_NOENT)
             Com_EPrintf("Couldn't load %s: %s\n",
                         CL_DOWNLOAD_IGNORES, Q_ErrorString(len));
         return;
     }
     count = 0;
     line = 1;
     data = raw;
     while (*data) {
         p = strchr(data, '\n');
         if (p) {
             if (p > data && *(p - 1) == '\r')
                 *(p - 1) = 0;
             *p = 0;
         }
         // ignore empty lines and comments
         if (*data && *data != '#' && *data != '/') {
             len = strlen(data);
             if (len < MAX_QPATH) {
                 entry = Z_Malloc(sizeof(*entry) + len);
                 memcpy(entry->string, data, len + 1);
                 entry->next = cls.download.ignores;
                 cls.download.ignores = entry;
                 count++;
             } else {
                 Com_WPrintf("Oversize filter on line %d in %s\n",
                             line, CL_DOWNLOAD_IGNORES);
             }
         }
         if (!p)
             break;
         data = p + 1;
         line++;
     }
     Com_DPrintf("Loaded %d filters from %s\n", count, CL_DOWNLOAD_IGNORES);
     FS_FreeFile(raw);
 }
Referenced by CL_Init(), and CL_RestartFilesystem().
CL_LoadState()
void CL_LoadState (load_state_t state)
Definition at line 541 of file console.c.
 {
     con.loadstate = state;
     SCR_UpdateScreen();
     VID_PumpEvents();
 }
Referenced by CL_Begin(), CL_Precache_f(), CL_PrepRefresh(), CL_RestartFilesystem(), and CL_RestartRefresh().
CL_MonsterPlasma_Shell()
void CL_MonsterPlasma_Shell (vec3_t origin)
Definition at line 493 of file newfx.c.
 {
     vec3_t          dir;
     int             i;
     cparticle_t     *p;
     for (i = 0; i < 40; i++) {
         p = CL_AllocParticle();
         if (!p)
             return;
         VectorClear(p->accel);
         p->time = cl.time;
         p->alpha = 1.0;
         p->alphavel = INSTANT_PARTICLE;
         p->color = 0xe0;
         dir[0] = crand();
         dir[1] = crand();
         dir[2] = crand();
         VectorNormalize(dir);
         VectorMA(origin, 10, dir, p->org);
     }
 }
Referenced by CL_AddPlayerBeams().
CL_MuzzleFlash()
void CL_MuzzleFlash (void)
Definition at line 257 of file effects.c.
 {
 #if USE_DLIGHTS
     vec3_t      fv, rv;
     cdlight_t   *dl;
 #endif
     centity_t   *pl;
     float       volume;
     char        soundname[MAX_QPATH];
 #ifdef _DEBUG
     if (developer->integer)
         CL_CheckEntityPresent(mz.entity, "muzzleflash");
 #endif
     pl = &cl_entities[mz.entity];
 #if USE_DLIGHTS
     dl = CL_AllocDlight(mz.entity);
     VectorCopy(pl->current.origin,  dl->origin);
     AngleVectors(pl->current.angles, fv, rv, NULL);
     VectorMA(dl->origin, 18, fv, dl->origin);
     VectorMA(dl->origin, 16, rv, dl->origin);
     if (mz.silenced)
         dl->radius = 100 + (rand() & 31);
     else
         dl->radius = 200 + (rand() & 31);
     //dl->minlight = 32;
     dl->die = cl.time; // + 0.1;
 #define DL_COLOR(r, g, b)   VectorSet(dl->color, r, g, b)
 #define DL_RADIUS(r)        (dl->radius = r)
 #define DL_DIE(t)           (dl->die = cl.time + t)
 #else
 #define DL_COLOR(r, g, b)
 #define DL_RADIUS(r)
 #define DL_DIE(t)
 #endif
     if (mz.silenced)
         volume = 0.2;
     else
         volume = 1;
     switch (mz.weapon) {
     case MZ_BLASTER:
         DL_COLOR(1, 1, 0);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("weapons/blastf1a.wav"), volume, ATTN_NORM, 0);
         break;
     case MZ_BLUEHYPERBLASTER:
         DL_COLOR(0, 0, 1);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("weapons/hyprbf1a.wav"), volume, ATTN_NORM, 0);
         break;
     case MZ_HYPERBLASTER:
         DL_COLOR(1, 1, 0);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("weapons/hyprbf1a.wav"), volume, ATTN_NORM, 0);
         break;
     case MZ_MACHINEGUN:
         DL_COLOR(1, 1, 0);
         Q_snprintf(soundname, sizeof(soundname), "weapons/machgf%ib.wav", (rand() % 5) + 1);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound(soundname), volume, ATTN_NORM, 0);
         break;
     case MZ_SHOTGUN:
         DL_COLOR(1, 1, 0);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("weapons/shotgf1b.wav"), volume, ATTN_NORM, 0);
         S_StartSound(NULL, mz.entity, CHAN_AUTO,   S_RegisterSound("weapons/shotgr1b.wav"), volume, ATTN_NORM, 0.1);
         break;
     case MZ_SSHOTGUN:
         DL_COLOR(1, 1, 0);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("weapons/sshotf1b.wav"), volume, ATTN_NORM, 0);
         break;
     case MZ_CHAINGUN1:
         DL_RADIUS(200 + (rand() & 31));
         DL_COLOR(1, 0.25, 0);
         Q_snprintf(soundname, sizeof(soundname), "weapons/machgf%ib.wav", (rand() % 5) + 1);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound(soundname), volume, ATTN_NORM, 0);
         break;
     case MZ_CHAINGUN2:
         DL_RADIUS(225 + (rand() & 31));
         DL_COLOR(1, 0.5, 0);
         DL_DIE(0.1);   // long delay
         Q_snprintf(soundname, sizeof(soundname), "weapons/machgf%ib.wav", (rand() % 5) + 1);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound(soundname), volume, ATTN_NORM, 0);
         Q_snprintf(soundname, sizeof(soundname), "weapons/machgf%ib.wav", (rand() % 5) + 1);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound(soundname), volume, ATTN_NORM, 0.05);
         break;
     case MZ_CHAINGUN3:
         DL_RADIUS(250 + (rand() & 31));
         DL_COLOR(1, 1, 0);
         DL_DIE(0.1);   // long delay
         Q_snprintf(soundname, sizeof(soundname), "weapons/machgf%ib.wav", (rand() % 5) + 1);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound(soundname), volume, ATTN_NORM, 0);
         Q_snprintf(soundname, sizeof(soundname), "weapons/machgf%ib.wav", (rand() % 5) + 1);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound(soundname), volume, ATTN_NORM, 0.033);
         Q_snprintf(soundname, sizeof(soundname), "weapons/machgf%ib.wav", (rand() % 5) + 1);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound(soundname), volume, ATTN_NORM, 0.066);
         break;
     case MZ_RAILGUN:
         DL_COLOR(0.5, 0.5, 1.0);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("weapons/railgf1a.wav"), volume, ATTN_NORM, 0);
         break;
     case MZ_ROCKET:
         DL_COLOR(1, 0.5, 0.2);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("weapons/rocklf1a.wav"), volume, ATTN_NORM, 0);
         S_StartSound(NULL, mz.entity, CHAN_AUTO,   S_RegisterSound("weapons/rocklr1b.wav"), volume, ATTN_NORM, 0.1);
         break;
     case MZ_GRENADE:
         DL_COLOR(1, 0.5, 0);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("weapons/grenlf1a.wav"), volume, ATTN_NORM, 0);
         S_StartSound(NULL, mz.entity, CHAN_AUTO,   S_RegisterSound("weapons/grenlr1b.wav"), volume, ATTN_NORM, 0.1);
         break;
     case MZ_BFG:
         DL_COLOR(0, 1, 0);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("weapons/bfg__f1y.wav"), volume, ATTN_NORM, 0);
         break;
     case MZ_LOGIN:
         DL_COLOR(0, 1, 0);
         DL_DIE(1.0);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("weapons/grenlf1a.wav"), 1, ATTN_NORM, 0);
         CL_LogoutEffect(pl->current.origin, mz.weapon);
         break;
     case MZ_LOGOUT:
         DL_COLOR(1, 0, 0);
         DL_DIE(1.0);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("weapons/grenlf1a.wav"), 1, ATTN_NORM, 0);
         CL_LogoutEffect(pl->current.origin, mz.weapon);
         break;
     case MZ_RESPAWN:
         DL_COLOR(1, 1, 0);
         DL_DIE(1.0);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("weapons/grenlf1a.wav"), 1, ATTN_NORM, 0);
         CL_LogoutEffect(pl->current.origin, mz.weapon);
         break;
     case MZ_PHALANX:
         DL_COLOR(1, 0.5, 0.5);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("weapons/plasshot.wav"), volume, ATTN_NORM, 0);
         break;
     case MZ_IONRIPPER:
         DL_COLOR(1, 0.5, 0.5);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("weapons/rippfiref.wav"), volume, ATTN_NORM, 0);
         break;
     case MZ_ETF_RIFLE:
         DL_COLOR(0.9, 0.7, 0);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("weapons/nail1.wav"), volume, ATTN_NORM, 0);
         break;
     case MZ_SHOTGUN2:
         DL_COLOR(1, 1, 0);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("weapons/shotg2.wav"), volume, ATTN_NORM, 0);
         break;
     case MZ_HEATBEAM:
         DL_COLOR(1, 1, 0);
         DL_DIE(100);
 //      S_StartSound (NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("weapons/bfg__l1a.wav"), volume, ATTN_NORM, 0);
         break;
     case MZ_BLASTER2:
         DL_COLOR(0, 1, 0);
         // FIXME - different sound for blaster2 ??
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("weapons/blastf1a.wav"), volume, ATTN_NORM, 0);
         break;
     case MZ_TRACKER:
         // negative flashes handled the same in gl/soft until CL_AddDLights
         DL_COLOR(-1, -1, -1);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("weapons/disint2.wav"), volume, ATTN_NORM, 0);
         break;
     case MZ_NUKE1:
         DL_COLOR(1, 0, 0);
         DL_DIE(100);
         break;
     case MZ_NUKE2:
         DL_COLOR(1, 1, 0);
         DL_DIE(100);
         break;
     case MZ_NUKE4:
         DL_COLOR(0, 0, 1);
         DL_DIE(100);
         break;
     case MZ_NUKE8:
         DL_COLOR(0, 1, 1);
         DL_DIE(100);
         break;
     // Q2RTX
     case MZ_FLARE:
         DL_RADIUS(0);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("weapons/flaregun.wav"), volume, ATTN_NORM, 0);
         break;
     // Q2RTX
     }
     if (vid_rtx->integer)
     {
         // don't add muzzle flashes in RTX mode
         DL_RADIUS(0.f);
     }
 }
Referenced by CL_ParseServerMessage().
CL_MuzzleFlash2()
void CL_MuzzleFlash2 (void)
Definition at line 459 of file effects.c.
 {
     centity_t   *ent;
     vec3_t      origin;
     const vec_t *ofs;
 #if USE_DLIGHTS
     cdlight_t   *dl;
 #endif
     vec3_t      forward, right;
     char        soundname[MAX_QPATH];
     // locate the origin
     ent = &cl_entities[mz.entity];
     AngleVectors(ent->current.angles, forward, right, NULL);
     ofs = monster_flash_offset[mz.weapon];
     origin[0] = ent->current.origin[0] + forward[0] * ofs[0] + right[0] * ofs[1];
     origin[1] = ent->current.origin[1] + forward[1] * ofs[0] + right[1] * ofs[1];
     origin[2] = ent->current.origin[2] + forward[2] * ofs[0] + right[2] * ofs[1] + ofs[2];
 #if USE_DLIGHTS
     dl = CL_AllocDlight(mz.entity);
     VectorCopy(origin,  dl->origin);
     dl->radius = 200 + (rand() & 31);
     //dl->minlight = 32;
     dl->die = cl.time;  // + 0.1;
 #endif
     switch (mz.weapon) {
     case MZ2_INFANTRY_MACHINEGUN_1:
     case MZ2_INFANTRY_MACHINEGUN_2:
     case MZ2_INFANTRY_MACHINEGUN_3:
     case MZ2_INFANTRY_MACHINEGUN_4:
     case MZ2_INFANTRY_MACHINEGUN_5:
     case MZ2_INFANTRY_MACHINEGUN_6:
     case MZ2_INFANTRY_MACHINEGUN_7:
     case MZ2_INFANTRY_MACHINEGUN_8:
     case MZ2_INFANTRY_MACHINEGUN_9:
     case MZ2_INFANTRY_MACHINEGUN_10:
     case MZ2_INFANTRY_MACHINEGUN_11:
     case MZ2_INFANTRY_MACHINEGUN_12:
     case MZ2_INFANTRY_MACHINEGUN_13:
         DL_COLOR(1, 1, 0);
         CL_ParticleEffect(origin, forward, 0, 40);
         CL_SmokeAndFlash(origin);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("infantry/infatck1.wav"), 1, ATTN_NORM, 0);
         break;
     case MZ2_SOLDIER_MACHINEGUN_1:
     case MZ2_SOLDIER_MACHINEGUN_2:
     case MZ2_SOLDIER_MACHINEGUN_3:
     case MZ2_SOLDIER_MACHINEGUN_4:
     case MZ2_SOLDIER_MACHINEGUN_5:
     case MZ2_SOLDIER_MACHINEGUN_6:
     case MZ2_SOLDIER_MACHINEGUN_7:
     case MZ2_SOLDIER_MACHINEGUN_8:
         DL_COLOR(1, 1, 0);
         CL_ParticleEffect(origin, forward, 0, 40);
         CL_SmokeAndFlash(origin);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("soldier/solatck3.wav"), 1, ATTN_NORM, 0);
         break;
     case MZ2_GUNNER_MACHINEGUN_1:
     case MZ2_GUNNER_MACHINEGUN_2:
     case MZ2_GUNNER_MACHINEGUN_3:
     case MZ2_GUNNER_MACHINEGUN_4:
     case MZ2_GUNNER_MACHINEGUN_5:
     case MZ2_GUNNER_MACHINEGUN_6:
     case MZ2_GUNNER_MACHINEGUN_7:
     case MZ2_GUNNER_MACHINEGUN_8:
         DL_COLOR(1, 1, 0);
         CL_ParticleEffect(origin, forward, 0, 40);
         CL_SmokeAndFlash(origin);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("gunner/gunatck2.wav"), 1, ATTN_NORM, 0);
         break;
     case MZ2_ACTOR_MACHINEGUN_1:
     case MZ2_SUPERTANK_MACHINEGUN_1:
     case MZ2_SUPERTANK_MACHINEGUN_2:
     case MZ2_SUPERTANK_MACHINEGUN_3:
     case MZ2_SUPERTANK_MACHINEGUN_4:
     case MZ2_SUPERTANK_MACHINEGUN_5:
     case MZ2_SUPERTANK_MACHINEGUN_6:
     case MZ2_TURRET_MACHINEGUN:
         DL_COLOR(1, 1, 0);
         CL_ParticleEffect(origin, forward, 0, 40);
         CL_SmokeAndFlash(origin);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("infantry/infatck1.wav"), 1, ATTN_NORM, 0);
         break;
     case MZ2_BOSS2_MACHINEGUN_L1:
     case MZ2_BOSS2_MACHINEGUN_L2:
     case MZ2_BOSS2_MACHINEGUN_L3:
     case MZ2_BOSS2_MACHINEGUN_L4:
     case MZ2_BOSS2_MACHINEGUN_L5:
     case MZ2_CARRIER_MACHINEGUN_L1:
     case MZ2_CARRIER_MACHINEGUN_L2:
         DL_COLOR(1, 1, 0);
         CL_ParticleEffect(origin, forward, 0, 40);
         CL_SmokeAndFlash(origin);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("infantry/infatck1.wav"), 1, ATTN_NONE, 0);
         break;
     case MZ2_SOLDIER_BLASTER_1:
     case MZ2_SOLDIER_BLASTER_2:
     case MZ2_SOLDIER_BLASTER_3:
     case MZ2_SOLDIER_BLASTER_4:
     case MZ2_SOLDIER_BLASTER_5:
     case MZ2_SOLDIER_BLASTER_6:
     case MZ2_SOLDIER_BLASTER_7:
     case MZ2_SOLDIER_BLASTER_8:
     case MZ2_TURRET_BLASTER:
         DL_COLOR(1, 1, 0);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("soldier/solatck2.wav"), 1, ATTN_NORM, 0);
         break;
     case MZ2_FLYER_BLASTER_1:
     case MZ2_FLYER_BLASTER_2:
         DL_COLOR(1, 1, 0);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("flyer/flyatck3.wav"), 1, ATTN_NORM, 0);
         break;
     case MZ2_MEDIC_BLASTER_1:
         DL_COLOR(1, 1, 0);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("medic/medatck1.wav"), 1, ATTN_NORM, 0);
         break;
     case MZ2_HOVER_BLASTER_1:
         DL_COLOR(1, 1, 0);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("hover/hovatck1.wav"), 1, ATTN_NORM, 0);
         break;
     case MZ2_FLOAT_BLASTER_1:
         DL_COLOR(1, 1, 0);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("floater/fltatck1.wav"), 1, ATTN_NORM, 0);
         break;
     case MZ2_SOLDIER_SHOTGUN_1:
     case MZ2_SOLDIER_SHOTGUN_2:
     case MZ2_SOLDIER_SHOTGUN_3:
     case MZ2_SOLDIER_SHOTGUN_4:
     case MZ2_SOLDIER_SHOTGUN_5:
     case MZ2_SOLDIER_SHOTGUN_6:
     case MZ2_SOLDIER_SHOTGUN_7:
     case MZ2_SOLDIER_SHOTGUN_8:
         DL_COLOR(1, 1, 0);
         CL_SmokeAndFlash(origin);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("soldier/solatck1.wav"), 1, ATTN_NORM, 0);
         break;
     case MZ2_TANK_BLASTER_1:
     case MZ2_TANK_BLASTER_2:
     case MZ2_TANK_BLASTER_3:
         DL_COLOR(1, 1, 0);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("tank/tnkatck3.wav"), 1, ATTN_NORM, 0);
         break;
     case MZ2_TANK_MACHINEGUN_1:
     case MZ2_TANK_MACHINEGUN_2:
     case MZ2_TANK_MACHINEGUN_3:
     case MZ2_TANK_MACHINEGUN_4:
     case MZ2_TANK_MACHINEGUN_5:
     case MZ2_TANK_MACHINEGUN_6:
     case MZ2_TANK_MACHINEGUN_7:
     case MZ2_TANK_MACHINEGUN_8:
     case MZ2_TANK_MACHINEGUN_9:
     case MZ2_TANK_MACHINEGUN_10:
     case MZ2_TANK_MACHINEGUN_11:
     case MZ2_TANK_MACHINEGUN_12:
     case MZ2_TANK_MACHINEGUN_13:
     case MZ2_TANK_MACHINEGUN_14:
     case MZ2_TANK_MACHINEGUN_15:
     case MZ2_TANK_MACHINEGUN_16:
     case MZ2_TANK_MACHINEGUN_17:
     case MZ2_TANK_MACHINEGUN_18:
     case MZ2_TANK_MACHINEGUN_19:
         DL_COLOR(1, 1, 0);
         CL_ParticleEffect(origin, forward, 0, 40);
         CL_SmokeAndFlash(origin);
         Q_snprintf(soundname, sizeof(soundname), "tank/tnkatk2%c.wav", 'a' + rand() % 5);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound(soundname), 1, ATTN_NORM, 0);
         break;
     case MZ2_CHICK_ROCKET_1:
     case MZ2_TURRET_ROCKET:
         DL_COLOR(1, 0.5, 0.2);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("chick/chkatck2.wav"), 1, ATTN_NORM, 0);
         break;
     case MZ2_TANK_ROCKET_1:
     case MZ2_TANK_ROCKET_2:
     case MZ2_TANK_ROCKET_3:
         DL_COLOR(1, 0.5, 0.2);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("tank/tnkatck1.wav"), 1, ATTN_NORM, 0);
         break;
     case MZ2_SUPERTANK_ROCKET_1:
     case MZ2_SUPERTANK_ROCKET_2:
     case MZ2_SUPERTANK_ROCKET_3:
     case MZ2_BOSS2_ROCKET_1:
     case MZ2_BOSS2_ROCKET_2:
     case MZ2_BOSS2_ROCKET_3:
     case MZ2_BOSS2_ROCKET_4:
     case MZ2_CARRIER_ROCKET_1:
 //  case MZ2_CARRIER_ROCKET_2:
 //  case MZ2_CARRIER_ROCKET_3:
 //  case MZ2_CARRIER_ROCKET_4:
         DL_COLOR(1, 0.5, 0.2);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("tank/rocket.wav"), 1, ATTN_NORM, 0);
         break;
     case MZ2_GUNNER_GRENADE_1:
     case MZ2_GUNNER_GRENADE_2:
     case MZ2_GUNNER_GRENADE_3:
     case MZ2_GUNNER_GRENADE_4:
         DL_COLOR(1, 0.5, 0);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("gunner/gunatck3.wav"), 1, ATTN_NORM, 0);
         break;
     case MZ2_GLADIATOR_RAILGUN_1:
     case MZ2_CARRIER_RAILGUN:
     case MZ2_WIDOW_RAIL:
         DL_COLOR(0.5, 0.5, 1.0);
         break;
     case MZ2_MAKRON_BFG:
         DL_COLOR(0.5, 1, 0.5);
         //S_StartSound (NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("makron/bfg_firef.wav"), 1, ATTN_NORM, 0);
         break;
     case MZ2_MAKRON_BLASTER_1:
     case MZ2_MAKRON_BLASTER_2:
     case MZ2_MAKRON_BLASTER_3:
     case MZ2_MAKRON_BLASTER_4:
     case MZ2_MAKRON_BLASTER_5:
     case MZ2_MAKRON_BLASTER_6:
     case MZ2_MAKRON_BLASTER_7:
     case MZ2_MAKRON_BLASTER_8:
     case MZ2_MAKRON_BLASTER_9:
     case MZ2_MAKRON_BLASTER_10:
     case MZ2_MAKRON_BLASTER_11:
     case MZ2_MAKRON_BLASTER_12:
     case MZ2_MAKRON_BLASTER_13:
     case MZ2_MAKRON_BLASTER_14:
     case MZ2_MAKRON_BLASTER_15:
     case MZ2_MAKRON_BLASTER_16:
     case MZ2_MAKRON_BLASTER_17:
         DL_COLOR(1, 1, 0);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("makron/blaster.wav"), 1, ATTN_NORM, 0);
         break;
     case MZ2_JORG_MACHINEGUN_L1:
     case MZ2_JORG_MACHINEGUN_L2:
     case MZ2_JORG_MACHINEGUN_L3:
     case MZ2_JORG_MACHINEGUN_L4:
     case MZ2_JORG_MACHINEGUN_L5:
     case MZ2_JORG_MACHINEGUN_L6:
         DL_COLOR(1, 1, 0);
         CL_ParticleEffect(origin, forward, 0, 40);
         CL_SmokeAndFlash(origin);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("boss3/xfiref.wav"), 1, ATTN_NORM, 0);
         break;
     case MZ2_JORG_MACHINEGUN_R1:
     case MZ2_JORG_MACHINEGUN_R2:
     case MZ2_JORG_MACHINEGUN_R3:
     case MZ2_JORG_MACHINEGUN_R4:
     case MZ2_JORG_MACHINEGUN_R5:
     case MZ2_JORG_MACHINEGUN_R6:
         DL_COLOR(1, 1, 0);
         CL_ParticleEffect(origin, forward, 0, 40);
         CL_SmokeAndFlash(origin);
         break;
     case MZ2_JORG_BFG_1:
         DL_COLOR(0.5, 1, 0.5);
         break;
     case MZ2_BOSS2_MACHINEGUN_R1:
     case MZ2_BOSS2_MACHINEGUN_R2:
     case MZ2_BOSS2_MACHINEGUN_R3:
     case MZ2_BOSS2_MACHINEGUN_R4:
     case MZ2_BOSS2_MACHINEGUN_R5:
     case MZ2_CARRIER_MACHINEGUN_R1:
     case MZ2_CARRIER_MACHINEGUN_R2:
         DL_COLOR(1, 1, 0);
         CL_ParticleEffect(origin, forward, 0, 40);
         CL_SmokeAndFlash(origin);
         break;
     case MZ2_STALKER_BLASTER:
     case MZ2_DAEDALUS_BLASTER:
     case MZ2_MEDIC_BLASTER_2:
     case MZ2_WIDOW_BLASTER:
     case MZ2_WIDOW_BLASTER_SWEEP1:
     case MZ2_WIDOW_BLASTER_SWEEP2:
     case MZ2_WIDOW_BLASTER_SWEEP3:
     case MZ2_WIDOW_BLASTER_SWEEP4:
     case MZ2_WIDOW_BLASTER_SWEEP5:
     case MZ2_WIDOW_BLASTER_SWEEP6:
     case MZ2_WIDOW_BLASTER_SWEEP7:
     case MZ2_WIDOW_BLASTER_SWEEP8:
     case MZ2_WIDOW_BLASTER_SWEEP9:
     case MZ2_WIDOW_BLASTER_100:
     case MZ2_WIDOW_BLASTER_90:
     case MZ2_WIDOW_BLASTER_80:
     case MZ2_WIDOW_BLASTER_70:
     case MZ2_WIDOW_BLASTER_60:
     case MZ2_WIDOW_BLASTER_50:
     case MZ2_WIDOW_BLASTER_40:
     case MZ2_WIDOW_BLASTER_30:
     case MZ2_WIDOW_BLASTER_20:
     case MZ2_WIDOW_BLASTER_10:
     case MZ2_WIDOW_BLASTER_0:
     case MZ2_WIDOW_BLASTER_10L:
     case MZ2_WIDOW_BLASTER_20L:
     case MZ2_WIDOW_BLASTER_30L:
     case MZ2_WIDOW_BLASTER_40L:
     case MZ2_WIDOW_BLASTER_50L:
     case MZ2_WIDOW_BLASTER_60L:
     case MZ2_WIDOW_BLASTER_70L:
     case MZ2_WIDOW_RUN_1:
     case MZ2_WIDOW_RUN_2:
     case MZ2_WIDOW_RUN_3:
     case MZ2_WIDOW_RUN_4:
     case MZ2_WIDOW_RUN_5:
     case MZ2_WIDOW_RUN_6:
     case MZ2_WIDOW_RUN_7:
     case MZ2_WIDOW_RUN_8:
         DL_COLOR(0, 1, 0);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("tank/tnkatck3.wav"), 1, ATTN_NORM, 0);
         break;
     case MZ2_WIDOW_DISRUPTOR:
         DL_COLOR(-1, -1, -1);
         S_StartSound(NULL, mz.entity, CHAN_WEAPON, S_RegisterSound("weapons/disint2.wav"), 1, ATTN_NORM, 0);
         break;
     case MZ2_WIDOW_PLASMABEAM:
     case MZ2_WIDOW2_BEAMER_1:
     case MZ2_WIDOW2_BEAMER_2:
     case MZ2_WIDOW2_BEAMER_3:
     case MZ2_WIDOW2_BEAMER_4:
     case MZ2_WIDOW2_BEAMER_5:
     case MZ2_WIDOW2_BEAM_SWEEP_1:
     case MZ2_WIDOW2_BEAM_SWEEP_2:
     case MZ2_WIDOW2_BEAM_SWEEP_3:
     case MZ2_WIDOW2_BEAM_SWEEP_4:
     case MZ2_WIDOW2_BEAM_SWEEP_5:
     case MZ2_WIDOW2_BEAM_SWEEP_6:
     case MZ2_WIDOW2_BEAM_SWEEP_7:
     case MZ2_WIDOW2_BEAM_SWEEP_8:
     case MZ2_WIDOW2_BEAM_SWEEP_9:
     case MZ2_WIDOW2_BEAM_SWEEP_10:
     case MZ2_WIDOW2_BEAM_SWEEP_11:
         DL_RADIUS(300 + (rand() & 100));
         DL_COLOR(1, 1, 0);
         DL_DIE(200);
         break;
     }
 }
Referenced by CL_ParseServerMessage().
CL_Nukeblast()
void CL_Nukeblast (cl_sustain_t * self)
Definition at line 551 of file newfx.c.
 {
     static const byte   colortable[4] = {110, 112, 114, 116};
     vec3_t          dir;
     int             i;
     cparticle_t     *p;
     float           ratio;
     ratio = 1.0 - (((float)self->endtime - (float)cl.time) / 1000.0);
     for (i = 0; i < 700; i++) {
         p = CL_AllocParticle();
         if (!p)
             return;
         VectorClear(p->accel);
         p->time = cl.time;
         p->alpha = 1.0;
         p->alphavel = INSTANT_PARTICLE;
         p->color = colortable[rand() & 3];
         dir[0] = crand();
         dir[1] = crand();
         dir[2] = crand();
         VectorNormalize(dir);
         VectorMA(self->org, (200.0 * ratio), dir, p->org);
     }
 }
Referenced by CL_ParseNuke().
CL_OldRailTrail()
void CL_OldRailTrail (void)
Definition at line 1632 of file effects.c.
 {
     vec3_t      move;
     vec3_t      vec;
     float       len;
     int         j;
     cparticle_t *p;
     float       dec;
     vec3_t      right, up;
     int         i;
     float       d, c, s;
     vec3_t      dir;
     byte        clr = 0x74;
     VectorCopy(te.pos1, move);
     VectorSubtract(te.pos2, te.pos1, vec);
     len = VectorNormalize(vec);
     MakeNormalVectors(vec, right, up);
     for (i = 0; i < len; i++) {
         p = CL_AllocParticle();
         if (!p)
             return;
         p->time = cl.time;
         VectorClear(p->accel);
         d = i * 0.1;
         c = cos(d);
         s = sin(d);
         VectorScale(right, c, dir);
         VectorMA(dir, s, up, dir);
         p->alpha = 1.0;
         p->alphavel = -1.0 / (1 + frand() * 0.2);
         p->color = clr + (rand() & 7);
         p->brightness = cvar_pt_particle_emissive->value;
         for (j = 0; j < 3; j++) {
             p->org[j] = move[j] + dir[j] * 3;
             p->vel[j] = dir[j] * 6;
         }
         VectorAdd(move, vec, move);
     }
     dec = 0.75;
     VectorScale(vec, dec, vec);
     VectorCopy(te.pos1, move);
     while (len > 0) {
         len -= dec;
         p = CL_AllocParticle();
         if (!p)
             return;
         p->time = cl.time;
         VectorClear(p->accel);
         p->alpha = 1.0;
         p->alphavel = -1.0 / (0.6 + frand() * 0.2);
         p->color = rand() & 15;
         p->brightness = 1.0f;
         for (j = 0; j < 3; j++) {
             p->org[j] = move[j] + crand() * 3;
             p->vel[j] = crand() * 3;
             p->accel[j] = 0;
         }
         VectorAdd(move, vec, move);
     }
 }
Referenced by CL_RailTrail().
CL_ParsePlayerSkin()
void CL_ParsePlayerSkin (char * name, char * model, char * skin, const char * s)
Definition at line 35 of file precache.c.
 {
     size_t len;
     char *t;
     // configstring parsing guarantees that playerskins can never
     // overflow, but still check the length to be entirely fool-proof
     len = strlen(s);
     if (len >= MAX_QPATH) {
         Com_Error(ERR_DROP, "%s: oversize playerskin", __func__);
     }
     // isolate the player's name
     t = strchr(s, '\\');
     if (t) {
         len = t - s;
         strcpy(model, t + 1);
     } else {
         len = 0;
         strcpy(model, s);
     }
     // copy the player's name
     if (name) {
         memcpy(name, s, len);
         name[len] = 0;
     }
     // isolate the model name
     t = strchr(model, '/');
     if (!t)
         t = strchr(model, '\\');
     if (!t)
         goto default_model;
     *t = 0;
     // isolate the skin name
     strcpy(skin, t + 1);
     // fix empty model to male
     if (t == model)
         strcpy(model, "male");
     // apply restrictions on skins
     if (cl_noskins->integer == 2 || !COM_IsPath(skin))
         goto default_skin;
     if (cl_noskins->integer || !COM_IsPath(model))
         goto default_model;
     return;
 default_skin:
     if (!Q_stricmp(model, "female")) {
         strcpy(model, "female");
         strcpy(skin, "athena");
     } else {
 default_model:
         strcpy(model, "male");
         strcpy(skin, "grunt");
     }
 }
Referenced by check_player(), and CL_LoadClientinfo().
CL_ParseServerMessage()
void CL_ParseServerMessage (void)
Definition at line 1168 of file parse.c.
 {
     int         cmd, extrabits;
     size_t      readcount;
     int         index, bits;
 #ifdef _DEBUG
     if (cl_shownet->integer == 1) {
         Com_LPrintf(PRINT_DEVELOPER, "%"PRIz" ", msg_read.cursize);
     } else if (cl_shownet->integer > 1) {
         Com_LPrintf(PRINT_DEVELOPER, "------------------\n");
     }
 #endif
 //
 // parse the message
 //
     while (1) {
         if (msg_read.readcount > msg_read.cursize) {
             Com_Error(ERR_DROP, "%s: read past end of server message", __func__);
         }
         readcount = msg_read.readcount;
         if ((cmd = MSG_ReadByte()) == -1) {
             SHOWNET(1, "%3"PRIz":END OF MESSAGE\n", msg_read.readcount - 1);
             break;
         }
         extrabits = cmd >> SVCMD_BITS;
         cmd &= SVCMD_MASK;
 #ifdef _DEBUG
         if (cl_shownet->integer > 1) {
             MSG_ShowSVC(cmd);
         }
 #endif
         // other commands
         switch (cmd) {
         default:
 badbyte:
             Com_Error(ERR_DROP, "%s: illegible server message: %d", __func__, cmd);
             break;
         case svc_nop:
             break;
         case svc_disconnect:
             Com_Error(ERR_DISCONNECT, "Server disconnected");
             break;
         case svc_reconnect:
             CL_ParseReconnect();
             return;
         case svc_print:
             CL_ParsePrint();
             break;
         case svc_centerprint:
             CL_ParseCenterPrint();
             break;
         case svc_stufftext:
             CL_ParseStuffText();
             break;
         case svc_serverdata:
             CL_ParseServerData();
             continue;
         case svc_configstring:
             index = MSG_ReadShort();
             CL_ParseConfigstring(index);
             break;
         case svc_sound:
             CL_ParseStartSoundPacket();
             S_ParseStartSound();
             break;
         case svc_spawnbaseline:
             index = MSG_ParseEntityBits(&bits);
             CL_ParseBaseline(index, bits);
             break;
         case svc_temp_entity:
             CL_ParseTEntPacket();
             CL_ParseTEnt();
             break;
         case svc_muzzleflash:
             CL_ParseMuzzleFlashPacket(MZ_SILENCED);
             CL_MuzzleFlash();
             break;
         case svc_muzzleflash2:
             CL_ParseMuzzleFlashPacket(0);
             CL_MuzzleFlash2();
             break;
         case svc_download:
             CL_ParseDownload(cmd);
             continue;
         case svc_frame:
             CL_ParseFrame(extrabits);
             continue;
         case svc_inventory:
             CL_ParseInventory();
             break;
         case svc_layout:
             CL_ParseLayout();
             break;
         case svc_zpacket:
             if (cls.serverProtocol < PROTOCOL_VERSION_R1Q2) {
                 goto badbyte;
             }
             CL_ParseZPacket();
             continue;
         case svc_zdownload:
             if (cls.serverProtocol < PROTOCOL_VERSION_R1Q2) {
                 goto badbyte;
             }
             CL_ParseDownload(cmd);
             continue;
         case svc_gamestate:
             if (cls.serverProtocol != PROTOCOL_VERSION_Q2PRO) {
                 goto badbyte;
             }
             CL_ParseGamestate();
             continue;
         case svc_setting:
             if (cls.serverProtocol < PROTOCOL_VERSION_R1Q2) {
                 goto badbyte;
             }
             CL_ParseSetting();
             continue;
         }
         // if recording demos, copy off protocol invariant stuff
         if (cls.demo.recording && !cls.demo.paused) {
             size_t len = msg_read.readcount - readcount;
             // it is very easy to overflow standard 1390 bytes
             // demo frame with modern servers... attempt to preserve
             // reliable messages at least, assuming they come first
             if (cls.demo.buffer.cursize + len < cls.demo.buffer.maxsize) {
                 SZ_Write(&cls.demo.buffer, msg_read.data + readcount, len);
             } else {
                 cls.demo.others_dropped++;
             }
         }
         // if running GTV server, add current message
         CL_GTV_WriteMessage(msg_read.data + readcount,
                             msg_read.readcount - readcount);
     }
 }
Referenced by CL_PacketEvent(), CL_ParseZPacket(), CL_PlayDemo_f(), and parse_next_message().
CL_ParseTEnt()
void CL_ParseTEnt (void)
Definition at line 1069 of file tent.c.
 {
     explosion_t *ex;
     int r;
     switch (te.type) {
     case TE_BLOOD:          // bullet hitting flesh
         if (!(cl_disable_particles->integer & NOPART_BLOOD))
         {
             // CL_ParticleEffect(te.pos1, te.dir, 0xe8, 60);
             CL_BloodParticleEffect(te.pos1, te.dir, 0xe8, 1000);
         }
         break;
     case TE_GUNSHOT:            // bullet hitting wall
     case TE_SPARKS:
     case TE_BULLET_SPARKS:
         if (te.type == TE_GUNSHOT)
             CL_ParticleEffect(te.pos1, te.dir, 0, 40);
         else
             CL_ParticleEffect(te.pos1, te.dir, 0xe0, 6);
         if (te.type != TE_SPARKS) {
             CL_SmokeAndFlash(te.pos1);
             // impact sound
             r = rand() & 15;
             if (r == 1)
                 S_StartSound(te.pos1, 0, 0, cl_sfx_ric1, 1, ATTN_NORM, 0);
             else if (r == 2)
                 S_StartSound(te.pos1, 0, 0, cl_sfx_ric2, 1, ATTN_NORM, 0);
             else if (r == 3)
                 S_StartSound(te.pos1, 0, 0, cl_sfx_ric3, 1, ATTN_NORM, 0);
         }
         break;
     case TE_SCREEN_SPARKS:
     case TE_SHIELD_SPARKS:
         if (te.type == TE_SCREEN_SPARKS)
             CL_ParticleEffect(te.pos1, te.dir, 0xd0, 40);
         else
             CL_ParticleEffect(te.pos1, te.dir, 0xb0, 40);
         //FIXME : replace or remove this sound
         S_StartSound(te.pos1, 0, 0, cl_sfx_lashit, 1, ATTN_NORM, 0);
         break;
     case TE_SHOTGUN:            // bullet hitting wall
         CL_ParticleEffect(te.pos1, te.dir, 0, 20);
         CL_SmokeAndFlash(te.pos1);
         break;
     case TE_SPLASH:         // bullet hitting water
         if (te.color < 0 || te.color > 6)
             r = 0x00;
         else
             r = splash_color[te.color];
         CL_ParticleEffectWaterSplash(te.pos1, te.dir, r, te.count);
         if (te.color == SPLASH_SPARKS) {
             r = rand() & 3;
             if (r == 0)
                 S_StartSound(te.pos1, 0, 0, cl_sfx_spark5, 1, ATTN_STATIC, 0);
             else if (r == 1)
                 S_StartSound(te.pos1, 0, 0, cl_sfx_spark6, 1, ATTN_STATIC, 0);
             else
                 S_StartSound(te.pos1, 0, 0, cl_sfx_spark7, 1, ATTN_STATIC, 0);
         }
         break;
     case TE_LASER_SPARKS:
         CL_ParticleEffect2(te.pos1, te.dir, te.color, te.count);
         break;
     case TE_BLUEHYPERBLASTER:
         CL_BlasterParticles(te.pos1, te.dir);
         break;
     case TE_BLASTER:            // blaster hitting wall
     case TE_BLASTER2:           // green blaster hitting wall
     case TE_FLECHETTE:          // flechette
     case TE_FLARE:              // flare
         ex = CL_AllocExplosion();
         VectorCopy(te.pos1, ex->ent.origin);
         dirtoangles(ex->ent.angles);
         ex->type = ex_blaster;
         ex->ent.flags = RF_FULLBRIGHT | RF_TRANSLUCENT;
         ex->ent.tent_type = te.type;
         switch (te.type) {
         case TE_BLASTER:
             CL_BlasterParticles(te.pos1, te.dir);
             ex->lightcolor[0] = 1;
             ex->lightcolor[1] = 1;
             break;
         case TE_BLASTER2:
             CL_BlasterParticles2(te.pos1, te.dir, 0xd0);
             ex->ent.skinnum = 1;
             ex->lightcolor[1] = 1;
             break;
         case TE_FLECHETTE:
             CL_BlasterParticles2(te.pos1, te.dir, 0x6f);  // 75
             ex->ent.skinnum = 2;
             ex->lightcolor[0] = 0.19;
             ex->lightcolor[1] = 0.41;
             ex->lightcolor[2] = 0.75;
             break;
         case TE_FLARE:
             CL_BlasterParticles2(te.pos1, te.dir, 0xd0);
             ex->lightcolor[0] = 1;
             ex->lightcolor[1] = 1;
             ex->type = ex_flare;
             break;
         }
         ex->start = cl.servertime - CL_FRAMETIME;
         ex->light = 150;
         ex->ent.model = cl_mod_explode;
         ex->frames = 4;
         if (te.type != TE_FLARE)
         {
             S_StartSound(te.pos1, 0, 0, cl_sfx_lashit, 1, ATTN_NORM, 0);
         }
         else
         {
             // te.count is set to 1 on the first tick of the flare, 0 afterwards
             if (te.count!=0)
                 S_StartSound(NULL, te.entity1, 0, cl_sfx_flare, 0.5, ATTN_NORM, 0);
         }
         break;
     case TE_RAILTRAIL:          // railgun effect
         CL_RailTrail();
         S_StartSound(te.pos2, 0, 0, cl_sfx_railg, 1, ATTN_NORM, 0);
         break;
     case TE_GRENADE_EXPLOSION:
     case TE_GRENADE_EXPLOSION_WATER:
         ex = CL_PlainExplosion(qfalse);
         if (!cl_explosion_sprites->integer)
         {
             ex->frames = 19;
             ex->baseframe = 30;
         }
         if (cl_disable_explosions->integer & NOEXP_GRENADE)
             ex->type = ex_light;
         if (!(cl_disable_particles->integer & NOPART_GRENADE_EXPLOSION))
             CL_ExplosionParticles(te.pos1);
         if (te.type == TE_GRENADE_EXPLOSION_WATER)
             S_StartSound(te.pos1, 0, 0, cl_sfx_watrexp, 1, ATTN_NORM, 0);
         else
             S_StartSound(te.pos1, 0, 0, cl_sfx_grenexp, 1, ATTN_NORM, 0);
         break;
     case TE_EXPLOSION2:
         ex = CL_PlainExplosion(qfalse);
         if (!cl_explosion_sprites->integer)
         {
             ex->frames = 19;
             ex->baseframe = 30;
         }
         CL_ExplosionParticles(te.pos1);
         S_StartSound(te.pos1, 0, 0, cl_sfx_grenexp, 1, ATTN_NORM, 0);
         break;
     case TE_PLASMA_EXPLOSION:
         CL_PlainExplosion(qfalse);
         CL_ExplosionParticles(te.pos1);
         S_StartSound(te.pos1, 0, 0, cl_sfx_rockexp, 1, ATTN_NORM, 0);
         break;
     case TE_ROCKET_EXPLOSION:
     case TE_ROCKET_EXPLOSION_WATER:
         ex = CL_PlainExplosion(qfalse);
         if (cl_disable_explosions->integer & NOEXP_ROCKET)
             ex->type = ex_light;
         if (!(cl_disable_particles->integer & NOPART_ROCKET_EXPLOSION))
             CL_ExplosionParticles(te.pos1);
         if (te.type == TE_ROCKET_EXPLOSION_WATER)
             S_StartSound(te.pos1, 0, 0, cl_sfx_watrexp, 1, ATTN_NORM, 0);
         else
             S_StartSound(te.pos1, 0, 0, cl_sfx_rockexp, 1, ATTN_NORM, 0);
         break;
     case TE_EXPLOSION1:
         CL_PlainExplosion(qfalse);
         CL_ExplosionParticles(te.pos1);
         S_StartSound(te.pos1, 0, 0, cl_sfx_rockexp, 1, ATTN_NORM, 0);
         break;
     case TE_EXPLOSION1_NP:
         CL_PlainExplosion(qfalse);
         S_StartSound(te.pos1, 0, 0, cl_sfx_rockexp, 1, ATTN_NORM, 0);
         break;
     case TE_EXPLOSION1_BIG:
         ex = CL_PlainExplosion(qtrue);
         S_StartSound(te.pos1, 0, 0, cl_sfx_rockexp, 1, ATTN_NORM, 0);
         break;
     case TE_BFG_EXPLOSION:
         ex = CL_AllocExplosion();
         VectorCopy(te.pos1, ex->ent.origin);
         ex->type = ex_poly;
         ex->ent.flags = RF_FULLBRIGHT;
         ex->start = cl.servertime - CL_FRAMETIME;
         ex->light = 350;
         ex->lightcolor[0] = 0.0;
         ex->lightcolor[1] = 1.0;
         ex->lightcolor[2] = 0.0;
         ex->ent.model = cl_mod_bfg_explo;
         ex->ent.flags |= RF_TRANSLUCENT;
         ex->ent.alpha = 0.80;
         ex->frames = 4;
         break;
     case TE_BFG_BIGEXPLOSION:
         CL_BFGExplosionParticles(te.pos1);
         break;
     case TE_BFG_LASER:
         CL_ParseLaser(0xd0d1d2d3);
         break;
     case TE_BUBBLETRAIL:
         CL_BubbleTrail(te.pos1, te.pos2);
         break;
     case TE_PARASITE_ATTACK:
     case TE_MEDIC_CABLE_ATTACK:
         VectorClear(te.offset);
         te.entity2 = 0;
         CL_ParseBeam(cl_mod_parasite_segment);
         break;
     case TE_BOSSTPORT:          // boss teleporting to station
         CL_BigTeleportParticles(te.pos1);
         S_StartSound(te.pos1, 0, 0, S_RegisterSound("misc/bigtele.wav"), 1, ATTN_NONE, 0);
         break;
     case TE_GRAPPLE_CABLE:
         te.entity2 = 0;
         CL_ParseBeam(cl_mod_grapple_cable);
         break;
     case TE_WELDING_SPARKS:
         CL_ParticleEffect2(te.pos1, te.dir, te.color, te.count);
         ex = CL_AllocExplosion();
         VectorCopy(te.pos1, ex->ent.origin);
         ex->type = ex_flash;
         // note to self
         // we need a better no draw flag
         ex->ent.flags = RF_BEAM;
         ex->start = cl.servertime - CL_FRAMETIME;
         ex->light = 100 + (rand() % 75);
         ex->lightcolor[0] = 1.0;
         ex->lightcolor[1] = 1.0;
         ex->lightcolor[2] = 0.3;
         ex->ent.model = cl_mod_flash;
         ex->frames = 2;
         break;
     case TE_GREENBLOOD:
         CL_ParticleEffect2(te.pos1, te.dir, 0xdf, 30);
         break;
     case TE_TUNNEL_SPARKS:
         CL_ParticleEffect3(te.pos1, te.dir, te.color, te.count);
         break;
     case TE_LIGHTNING:
         S_StartSound(NULL, te.entity1, CHAN_WEAPON, cl_sfx_lightning, 1, ATTN_NORM, 0);
         VectorClear(te.offset);
         CL_ParseBeam(cl_mod_lightning);
         break;
     case TE_DEBUGTRAIL:
         CL_DebugTrail(te.pos1, te.pos2);
         break;
     case TE_PLAIN_EXPLOSION:
         CL_PlainExplosion(qfalse);
         break;
     case TE_FLASHLIGHT:
 #if USE_DLIGHTS
         CL_Flashlight(te.entity1, te.pos1);
 #endif
         break;
     case TE_FORCEWALL:
         CL_ForceWall(te.pos1, te.pos2, te.color);
         break;
     case TE_HEATBEAM:
         VectorSet(te.offset, 2, 7, -3);
         CL_ParsePlayerBeam(cl_mod_heatbeam);
         break;
     case TE_MONSTER_HEATBEAM:
         VectorClear(te.offset);
         CL_ParsePlayerBeam(cl_mod_heatbeam);
         break;
     case TE_HEATBEAM_SPARKS:
         CL_ParticleSteamEffect(te.pos1, te.dir, 0x8, 50, 60);
         S_StartSound(te.pos1,  0, 0, cl_sfx_lashit, 1, ATTN_NORM, 0);
         break;
     case TE_HEATBEAM_STEAM:
         CL_ParticleSteamEffect(te.pos1, te.dir, 0xE0, 20, 60);
         S_StartSound(te.pos1,  0, 0, cl_sfx_lashit, 1, ATTN_NORM, 0);
         break;
     case TE_STEAM:
         CL_ParseSteam();
         break;
     case TE_BUBBLETRAIL2:
         CL_BubbleTrail2(te.pos1, te.pos2, 8);
         S_StartSound(te.pos1,  0, 0, cl_sfx_lashit, 1, ATTN_NORM, 0);
         break;
     case TE_MOREBLOOD:
         CL_ParticleEffect(te.pos1, te.dir, 0xe8, 250);
         break;
     case TE_CHAINFIST_SMOKE:
         VectorSet(te.dir, 0, 0, 1);
         CL_ParticleSmokeEffect(te.pos1, te.dir, 0, 20, 20);
         break;
     case TE_ELECTRIC_SPARKS:
         CL_ParticleEffect(te.pos1, te.dir, 0x75, 40);
         //FIXME : replace or remove this sound
         S_StartSound(te.pos1, 0, 0, cl_sfx_lashit, 1, ATTN_NORM, 0);
         break;
     case TE_TRACKER_EXPLOSION:
 #if USE_DLIGHTS
         CL_ColorFlash(te.pos1, 0, 150, -1, -1, -1);
 #endif
         CL_ColorExplosionParticles(te.pos1, 0, 1);
         S_StartSound(te.pos1, 0, 0, cl_sfx_disrexp, 1, ATTN_NORM, 0);
         break;
     case TE_TELEPORT_EFFECT:
     case TE_DBALL_GOAL:
         CL_TeleportParticles(te.pos1);
         break;
     case TE_WIDOWBEAMOUT:
         CL_ParseWidow();
         break;
     case TE_NUKEBLAST:
         CL_ParseNuke();
         break;
     case TE_WIDOWSPLASH:
         CL_WidowSplash();
         break;
     default:
         Com_Error(ERR_DROP, "%s: bad type", __func__);
     }
 }
Referenced by CL_ParseServerMessage().
CL_ParticleEffect()
void CL_ParticleEffect (vec3_t org, vec3_t dir, int color, int count)
Definition at line 877 of file effects.c.
 {
     vec3_t oy;
     VectorSet(oy, 0.0f, 1.0f, 0.0f);
     if (fabs(DotProduct(oy, dir)) > 0.95f)
         VectorSet(oy, 1.0f, 0.0f, 0.0f);
     vec3_t ox;
     CrossProduct(oy, dir, ox);
     count *= cl_particle_num_factor->value;
     const int spark_count = count / 10;
     const float dirt_horizontal_spread = 2.0f;
     const float dirt_vertical_spread = 1.0f;
     const float dirt_base_velocity = 40.0f;
     const float dirt_rand_velocity = 70.0f;
     const float spark_horizontal_spread = 1.0f;
     const float spark_vertical_spread = 1.0f;
     const float spark_base_velocity = 50.0f;
     const float spark_rand_velocity = 130.0f;
     for (int i = 0; i < count; i++) {
         cparticle_t* p = CL_AllocParticle();
         if (!p)
             return;
         p->time = cl.time;
         p->color = color + (rand() & 7);
         p->brightness = 0.5f;
         vec3_t origin;
         VectorCopy(org, origin);
         VectorMA(origin, dirt_horizontal_spread * crand(), ox, origin);
         VectorMA(origin, dirt_horizontal_spread * crand(), oy, origin);
         VectorMA(origin, dirt_vertical_spread * frand() + 1.0f, dir, origin);
         VectorCopy(origin, p->org);
         vec3_t velocity;
         VectorSubtract(origin, org, velocity);
         VectorNormalize(velocity);
         VectorScale(velocity, dirt_base_velocity + frand() * dirt_rand_velocity, p->vel);
         p->accel[0] = p->accel[1] = 0;
         p->accel[2] = -PARTICLE_GRAVITY;
         p->alpha = 1.0;
         p->alphavel = -1.0 / (0.5 + frand() * 0.3);
     }
     for (int i = 0; i < spark_count; i++) {
         cparticle_t* p = CL_AllocParticle();
         if (!p)
             return;
         p->time = cl.time;
         p->color = 0xe0 + (rand() & 7);
         p->brightness = cvar_pt_particle_emissive->value;
         vec3_t origin;
         VectorCopy(org, origin);
         VectorMA(origin, spark_horizontal_spread * crand(), ox, origin);
         VectorMA(origin, spark_horizontal_spread * crand(), oy, origin);
         VectorMA(origin, spark_vertical_spread * frand() + 1.0f, dir, origin);
         VectorCopy(origin, p->org);
         vec3_t velocity;
         VectorSubtract(origin, org, velocity);
         VectorNormalize(velocity);
         VectorScale(velocity, spark_base_velocity + powf(frand(), 2.0f) * spark_rand_velocity, p->vel);
         p->accel[0] = p->accel[1] = 0;
         p->accel[2] = -PARTICLE_GRAVITY;
         p->alpha = 1.0;
         p->alphavel = -2.0 / (0.5 + frand() * 0.3);
     }
 }
Referenced by CL_MuzzleFlash2(), and CL_ParseTEnt().
CL_ParticleEffect2()
void CL_ParticleEffect2 (vec3_t org, vec3_t dir, int color, int count)
Definition at line 1060 of file effects.c.
 {
     int         i, j;
     cparticle_t *p;
     float       d;
     count *= cl_particle_num_factor->value;
     for (i = 0; i < count; i++) {
         p = CL_AllocParticle();
         if (!p)
             return;
         p->time = cl.time;
         p->color = color;
         p->brightness = 1.0f;
         d = rand() & 7;
         for (j = 0; j < 3; j++) {
             p->org[j] = org[j] + ((rand() & 7) - 4) + d * dir[j];
             p->vel[j] = crand() * 20;
         }
         p->accel[0] = p->accel[1] = 0;
         p->accel[2] = -PARTICLE_GRAVITY;
         p->alpha = 1.0;
         p->alphavel = -1.0 / (0.5 + frand() * 0.3);
     }
 }
Referenced by CL_ParseTEnt().
CL_ParticleEffect3()
void CL_ParticleEffect3 (vec3_t org, vec3_t dir, int color, int count)
Definition at line 989 of file newfx.c.
 {
     int         i, j;
     cparticle_t *p;
     float       d;
     for (i = 0; i < count; i++) {
         p = CL_AllocParticle();
         if (!p)
             return;
         p->time = cl.time;
         p->color = color;
         d = rand() & 7;
         for (j = 0; j < 3; j++) {
             p->org[j] = org[j] + ((rand() & 7) - 4) + d * dir[j];
             p->vel[j] = crand() * 20;
         }
         p->accel[0] = p->accel[1] = 0;
         p->accel[2] = PARTICLE_GRAVITY;
         p->alpha = 1.0;
         p->alphavel = -1.0 / (0.5 + frand() * 0.3);
     }
 }
Referenced by CL_ParseTEnt().
CL_ParticleEffectWaterSplash()
void CL_ParticleEffectWaterSplash (vec3_t org, vec3_t dir, int color, int count)
Definition at line 959 of file effects.c.
 {
     vec3_t oy;
     VectorSet(oy, 0.0f, 1.0f, 0.0f);
     if (fabs(DotProduct(oy, dir)) > 0.95f)
         VectorSet(oy, 1.0f, 0.0f, 0.0f);
     vec3_t ox;
     CrossProduct(oy, dir, ox);
     count *= cl_particle_num_factor->value;
     const float water_horizontal_spread = 0.25f;
     const float water_vertical_spread = 1.0f;
     const float water_base_velocity = 80.0f;
     const float water_rand_velocity = 150.0f;
     for (int i = 0; i < count; i++) {
         cparticle_t* p = CL_AllocParticle();
         if (!p)
             return;
         p->time = cl.time;
         p->color = color + (rand() & 7);
         p->brightness = 1.0f;
         vec3_t origin;
         VectorCopy(org, origin);
         VectorMA(origin, water_horizontal_spread * crand(), ox, origin);
         VectorMA(origin, water_horizontal_spread * crand(), oy, origin);
         VectorMA(origin, water_vertical_spread * frand() + 1.0f, dir, origin);
         VectorCopy(origin, p->org);
         vec3_t velocity;
         VectorSubtract(origin, org, velocity);
         VectorNormalize(velocity);
         VectorScale(velocity, water_base_velocity + frand() * water_rand_velocity, p->vel);
         p->accel[0] = p->accel[1] = 0;
         p->accel[2] = -PARTICLE_GRAVITY;
         p->alpha = 1.0;
         p->alphavel = -1.0 / (0.5 + frand() * 0.3);
     }
 }
Referenced by CL_ParseTEnt().
CL_ParticleSmokeEffect()
void CL_ParticleSmokeEffect (vec3_t org, vec3_t dir, int color, int count, int magnitude)
Definition at line 721 of file newfx.c.
 {
     int         i, j;
     cparticle_t *p;
     float       d;
     vec3_t      r, u;
     MakeNormalVectors(dir, r, u);
     for (i = 0; i < count; i++) {
         p = CL_AllocParticle();
         if (!p)
             return;
         p->time = cl.time;
         p->color = color + (rand() & 7);
         for (j = 0; j < 3; j++) {
             p->org[j] = org[j] + magnitude * 0.1 * crand();
         }
         VectorScale(dir, magnitude, p->vel);
         d = crand() * magnitude / 3;
         VectorMA(p->vel, d, r, p->vel);
         d = crand() * magnitude / 3;
         VectorMA(p->vel, d, u, p->vel);
         p->accel[0] = p->accel[1] = p->accel[2] = 0;
         p->alpha = 1.0;
         p->alphavel = -1.0 / (0.5 + frand() * 0.3);
     }
 }
Referenced by CL_ParseTEnt().
CL_ParticleSteamEffect()
void CL_ParticleSteamEffect (vec3_t org, vec3_t dir, int color, int count, int magnitude)
Definition at line 341 of file newfx.c.
 {
     int         i, j;
     cparticle_t *p;
     float       d;
     vec3_t      r, u;
     MakeNormalVectors(dir, r, u);
     for (i = 0; i < count; i++) {
         p = CL_AllocParticle();
         if (!p)
             return;
         p->time = cl.time;
         p->color = color + (rand() & 7);
         for (j = 0; j < 3; j++) {
             p->org[j] = org[j] + magnitude * 0.1 * crand();
         }
         VectorScale(dir, magnitude, p->vel);
         d = crand() * magnitude / 3;
         VectorMA(p->vel, d, r, p->vel);
         d = crand() * magnitude / 3;
         VectorMA(p->vel, d, u, p->vel);
         p->accel[0] = p->accel[1] = 0;
         p->accel[2] = -PARTICLE_GRAVITY / 2;
         p->alpha = 1.0;
         p->alphavel = -1.0 / (0.5 + frand() * 0.3);
     }
 }
Referenced by CL_ParseSteam(), and CL_ParseTEnt().
CL_ParticleSteamEffect2()
void CL_ParticleSteamEffect2 (cl_sustain_t * self)
Definition at line 375 of file newfx.c.
 {
     int         i, j;
     cparticle_t *p;
     float       d;
     vec3_t      r, u;
     vec3_t      dir;
     VectorCopy(self->dir, dir);
     MakeNormalVectors(dir, r, u);
     for (i = 0; i < self->count; i++) {
         p = CL_AllocParticle();
         if (!p)
             return;
         p->time = cl.time;
         p->color = self->color + (rand() & 7);
         for (j = 0; j < 3; j++) {
             p->org[j] = self->org[j] + self->magnitude * 0.1 * crand();
         }
         VectorScale(dir, self->magnitude, p->vel);
         d = crand() * self->magnitude / 3;
         VectorMA(p->vel, d, r, p->vel);
         d = crand() * self->magnitude / 3;
         VectorMA(p->vel, d, u, p->vel);
         p->accel[0] = p->accel[1] = 0;
         p->accel[2] = -PARTICLE_GRAVITY / 2;
         p->alpha = 1.0;
         p->alphavel = -1.0 / (0.5 + frand() * 0.3);
     }
     self->nextthink += self->thinkinterval;
 }
Referenced by CL_ParseSteam().
CL_PredictAngles()
void CL_PredictAngles (void)
Definition at line 168 of file predict.c.
 {
     cl.predicted_angles[0] = cl.viewangles[0] + SHORT2ANGLE(cl.frame.ps.pmove.delta_angles[0]);
     cl.predicted_angles[1] = cl.viewangles[1] + SHORT2ANGLE(cl.frame.ps.pmove.delta_angles[1]);
     cl.predicted_angles[2] = cl.viewangles[2] + SHORT2ANGLE(cl.frame.ps.pmove.delta_angles[2]);
 }
Referenced by CL_PredictMovement(), and set_active_state().
CL_PredictMovement()
void CL_PredictMovement (void)
Definition at line 175 of file predict.c.
 {
     unsigned    ack, current, frame;
     pmove_t     pm;
     int         step, oldz;
     if (cls.state != ca_active) {
         return;
     }
     if (cls.demo.playback) {
         return;
     }
     if (sv_paused->integer) {
         return;
     }
     if (!cl_predict->integer || (cl.frame.ps.pmove.pm_flags & PMF_NO_PREDICTION)) {
         // just set angles
         CL_PredictAngles();
         return;
     }
     ack = cl.history[cls.netchan->incoming_acknowledged & CMD_MASK].cmdNumber;
     current = cl.cmdNumber;
     // if we are too far out of date, just freeze
     if (current - ack > CMD_BACKUP - 1) {
         SHOWMISS("%i: exceeded CMD_BACKUP\n", cl.frame.number);
         return;
     }
     if (!cl.cmd.msec && current == ack) {
         SHOWMISS("%i: not moved\n", cl.frame.number);
         return;
     }
     X86_PUSH_FPCW;
     X86_SINGLE_FPCW;
     // copy current state to pmove
     memset(&pm, 0, sizeof(pm));
     pm.trace = CL_Trace;
     pm.pointcontents = CL_PointContents;
     pm.s = cl.frame.ps.pmove;
 #if USE_SMOOTH_DELTA_ANGLES
     VectorCopy(cl.delta_angles, pm.s.delta_angles);
 #endif
     // run frames
     while (++ack <= current) {
         pm.cmd = cl.cmds[ack & CMD_MASK];
         Pmove(&pm, &cl.pmp);
         // save for debug checking
         VectorCopy(pm.s.origin, cl.predicted_origins[ack & CMD_MASK]);
     }
     // run pending cmd
     if (cl.cmd.msec) {
         pm.cmd = cl.cmd;
         pm.cmd.forwardmove = cl.localmove[0];
         pm.cmd.sidemove = cl.localmove[1];
         pm.cmd.upmove = cl.localmove[2];
         Pmove(&pm, &cl.pmp);
         frame = current;
         // save for debug checking
         VectorCopy(pm.s.origin, cl.predicted_origins[(current + 1) & CMD_MASK]);
     } else {
         frame = current - 1;
     }
     X86_POP_FPCW;
     if (pm.s.pm_type != PM_SPECTATOR && (pm.s.pm_flags & PMF_ON_GROUND)) {
         oldz = cl.predicted_origins[cl.predicted_step_frame & CMD_MASK][2];
         step = pm.s.origin[2] - oldz;
         if (step > 63 && step < 160) {
             cl.predicted_step = step * 0.125f;
             cl.predicted_step_time = cls.realtime;
             cl.predicted_step_frame = frame + 1;    // don't double step
         }
     }
     if (cl.predicted_step_frame < frame) {
         cl.predicted_step_frame = frame;
     }
     // copy results out for rendering
     VectorScale(pm.s.origin, 0.125f, cl.predicted_origin);
     VectorScale(pm.s.velocity, 0.125f, cl.predicted_velocity);
     VectorCopy(pm.viewangles, cl.predicted_angles);
 }
Referenced by CL_Frame().
CL_PrepRefresh()
void CL_PrepRefresh (void)
Definition at line 333 of file precache.c.
 {
     int         i;
     char        *name;
     if (!cls.ref_initialized)
         return;
     if (!cl.mapname[0])
         return;     // no map loaded
     // register models, pics, and skins
     R_BeginRegistration(cl.mapname);
     CL_LoadState(LOAD_MODELS);
     CL_RegisterTEntModels();
 #if CL_RTX_SHADERBALLS
     cvar_shaderballs = Cvar_Get("cl_shaderballs", "0", 0);
     if (cvar_shaderballs->integer && vid_rtx->integer)
     {
         cl_dev_shaderballs = R_RegisterModel("develop/objects/ShaderBallArray/ShaderBallArray16.MD3");
         if (cl_dev_shaderballs)
             Com_Printf("Loaded the ShaderBalls model\n");
         else
             Com_WPrintf("Failed to load the ShaderBalls model\n");
     }
     else
         cl_dev_shaderballs = -1;
 #endif
     for (i = 2; i < MAX_MODELS; i++) {
         name = cl.configstrings[CS_MODELS + i];
         if (!name[0]) {
             break;
         }
         if (name[0] == '#') {
             continue;
         }
         cl.model_draw[i] = R_RegisterModel(name);
     }
     CL_LoadState(LOAD_IMAGES);
     for (i = 1; i < MAX_IMAGES; i++) {
         name = cl.configstrings[CS_IMAGES + i];
         if (!name[0]) {
             break;
         }
         cl.image_precache[i] = R_RegisterPic2(name);
     }
     CL_LoadState(LOAD_CLIENTS);
     for (i = 0; i < MAX_CLIENTS; i++) {
         name = cl.configstrings[CS_PLAYERSKINS + i];
         if (!name[0]) {
             continue;
         }
         CL_LoadClientinfo(&cl.clientinfo[i], name);
     }
     CL_LoadClientinfo(&cl.baseclientinfo, "unnamed\\male/grunt");
     // set sky textures and speed
     CL_SetSky();
     // the renderer can now free unneeded stuff
     R_EndRegistration();
     // clear any lines of console text
     Con_ClearNotify_f();
     SCR_UpdateScreen();
     int cdtrack = atoi(cl.configstrings[CS_CDTRACK]);
     OGG_PlayTrack(cdtrack);
 }
Referenced by CL_Begin(), CL_Precache_f(), CL_RestartFilesystem(), and CL_RestartRefresh().
CL_QuadTrail()
void CL_QuadTrail (vec3_t start, vec3_t end)
Definition at line 1388 of file effects.c.
 {
     vec3_t      move;
     vec3_t      vec;
     float       len;
     int         j;
     cparticle_t *p;
     int         dec;
     VectorCopy(start, move);
     VectorSubtract(end, start, vec);
     len = VectorNormalize(vec);
     dec = 5;
     VectorScale(vec, 5, vec);
     while (len > 0) {
         len -= dec;
         p = CL_AllocParticle();
         if (!p)
             return;
         VectorClear(p->accel);
         p->time = cl.time;
         p->alpha = 1.0;
         p->alphavel = -1.0 / (0.8 + frand() * 0.2);
         p->color = 115;
         p->brightness = cvar_pt_particle_emissive->value;
         for (j = 0; j < 3; j++) {
             p->org[j] = move[j] + crand() * 16;
             p->vel[j] = crand() * 5;
             p->accel[j] = 0;
         }
         VectorAdd(move, vec, move);
     }
 }
CL_QueueDownload()
qerror_t CL_QueueDownload (const char * path, dltype_t type)
Definition at line 49 of file download.c.
 {
     dlqueue_t *q;
     size_t len;
     FOR_EACH_DLQ(q) {
         // avoid sending duplicate requests
         if (!FS_pathcmp(path, q->path)) {
             Com_DPrintf("%s: %s [DUP]\n", __func__, path);
             return Q_ERR_EXIST;
         }
     }
     len = strlen(path);
     if (len >= MAX_QPATH) {
         Com_Error(ERR_DROP, "%s: oversize quake path", __func__);
     }
     q = Z_Malloc(sizeof(*q) + len);
     memcpy(q->path, path, len + 1);
     q->type = type;
     q->state = DL_PENDING;
 #if USE_CURL
     // paks get bumped to the top and HTTP switches to single downloading.
     // this prevents someone on 28k dialup trying to do both the main .pak
     // and referenced configstrings data at once.
     if (type == DL_PAK)
         List_Insert(&cls.download.queue, &q->entry);
     else
 #endif
         List_Append(&cls.download.queue, &q->entry);
     cls.download.pending++;
     Com_DPrintf("%s: %s [%d]\n", __func__, path, cls.download.pending);
     return Q_ERR_SUCCESS;
 }
Referenced by check_and_queue_download(), check_file_len(), and HTTP_QueueDownload().
CL_Quit_f()
void CL_Quit_f (void)
CL_RegisterBspModels()
void CL_RegisterBspModels (void)
Definition at line 226 of file precache.c.
 {
     qerror_t ret;
     char *name;
     int i;
     ret = BSP_Load(cl.configstrings[CS_MODELS + 1], &cl.bsp);
     if (cl.bsp == NULL) {
         Com_Error(ERR_DROP, "Couldn't load %s: %s",
                   cl.configstrings[CS_MODELS + 1], Q_ErrorString(ret));
     }
 #if USE_MAPCHECKSUM
     if (cl.bsp->checksum != atoi(cl.configstrings[CS_MAPCHECKSUM])) {
         if (cls.demo.playback) {
             Com_WPrintf("Local map version differs from demo: %i != %s\n",
                         cl.bsp->checksum, cl.configstrings[CS_MAPCHECKSUM]);
         } else {
             Com_Error(ERR_DROP, "Local map version differs from server: %i != %s",
                       cl.bsp->checksum, cl.configstrings[CS_MAPCHECKSUM]);
         }
     }
 #endif
     for (i = 1; i < MAX_MODELS; i++) {
         name = cl.configstrings[CS_MODELS + i];
         if (!name[0]) {
             break;
         }
         if (name[0] == '*')
             cl.model_clip[i] = BSP_InlineModel(cl.bsp, name);
         else
             cl.model_clip[i] = NULL;
     }
 }
Referenced by CL_Precache_f(), and CL_RequestNextDownload().
CL_RegisterInput()
void CL_RegisterInput (void)
Definition at line 707 of file input.c.
 {
     Cmd_AddCommand("centerview", IN_CenterView);
     Cmd_AddCommand("+moveup", IN_UpDown);
     Cmd_AddCommand("-moveup", IN_UpUp);
     Cmd_AddCommand("+movedown", IN_DownDown);
     Cmd_AddCommand("-movedown", IN_DownUp);
     Cmd_AddCommand("+left", IN_LeftDown);
     Cmd_AddCommand("-left", IN_LeftUp);
     Cmd_AddCommand("+right", IN_RightDown);
     Cmd_AddCommand("-right", IN_RightUp);
     Cmd_AddCommand("+forward", IN_ForwardDown);
     Cmd_AddCommand("-forward", IN_ForwardUp);
     Cmd_AddCommand("+back", IN_BackDown);
     Cmd_AddCommand("-back", IN_BackUp);
     Cmd_AddCommand("+lookup", IN_LookupDown);
     Cmd_AddCommand("-lookup", IN_LookupUp);
     Cmd_AddCommand("+lookdown", IN_LookdownDown);
     Cmd_AddCommand("-lookdown", IN_LookdownUp);
     Cmd_AddCommand("+strafe", IN_StrafeDown);
     Cmd_AddCommand("-strafe", IN_StrafeUp);
     Cmd_AddCommand("+moveleft", IN_MoveleftDown);
     Cmd_AddCommand("-moveleft", IN_MoveleftUp);
     Cmd_AddCommand("+moveright", IN_MoverightDown);
     Cmd_AddCommand("-moveright", IN_MoverightUp);
     Cmd_AddCommand("+speed", IN_SpeedDown);
     Cmd_AddCommand("-speed", IN_SpeedUp);
     Cmd_AddCommand("+attack", IN_AttackDown);
     Cmd_AddCommand("-attack", IN_AttackUp);
     Cmd_AddCommand("+use", IN_UseDown);
     Cmd_AddCommand("-use", IN_UseUp);
     Cmd_AddCommand("impulse", IN_Impulse);
     Cmd_AddCommand("+klook", IN_KLookDown);
     Cmd_AddCommand("-klook", IN_KLookUp);
     Cmd_AddCommand("+mlook", IN_MLookDown);
     Cmd_AddCommand("-mlook", IN_MLookUp);
     Cmd_AddCommand("in_restart", IN_Restart_f);
     cl_nodelta = Cvar_Get("cl_nodelta", "0", 0);
     cl_maxpackets = Cvar_Get("cl_maxpackets", "30", 0);
     cl_fuzzhack = Cvar_Get("cl_fuzzhack", "0", 0);
     cl_packetdup = Cvar_Get("cl_packetdup", "1", 0);
 #ifdef _DEBUG
     cl_showpackets = Cvar_Get("cl_showpackets", "0", 0);
 #endif
     cl_instantpacket = Cvar_Get("cl_instantpacket", "1", 0);
     cl_batchcmds = Cvar_Get("cl_batchcmds", "1", 0);
     cl_upspeed = Cvar_Get("cl_upspeed", "200", 0);
     cl_forwardspeed = Cvar_Get("cl_forwardspeed", "200", 0);
     cl_sidespeed = Cvar_Get("cl_sidespeed", "200", 0);
     cl_yawspeed = Cvar_Get("cl_yawspeed", "140", 0);
     cl_pitchspeed = Cvar_Get("cl_pitchspeed", "150", CVAR_CHEAT);
     cl_anglespeedkey = Cvar_Get("cl_anglespeedkey", "1.5", CVAR_CHEAT);
     cl_run = Cvar_Get("cl_run", "1", CVAR_ARCHIVE);
     freelook = Cvar_Get("freelook", "1", CVAR_ARCHIVE);
     lookspring = Cvar_Get("lookspring", "0", CVAR_ARCHIVE);
     lookstrafe = Cvar_Get("lookstrafe", "0", CVAR_ARCHIVE);
     sensitivity = Cvar_Get("sensitivity", "3", CVAR_ARCHIVE);
     m_pitch = Cvar_Get("m_pitch", "0.022", CVAR_ARCHIVE);
     m_invert = Cvar_Get("m_invert", "0", CVAR_ARCHIVE);
     m_yaw = Cvar_Get("m_yaw", "0.022", 0);
     m_forward = Cvar_Get("m_forward", "1", 0);
     m_side = Cvar_Get("m_side", "1", 0);
     m_filter = Cvar_Get("m_filter", "0", 0);
     m_accel = Cvar_Get("m_accel", "0", 0);
     m_autosens = Cvar_Get("m_autosens", "0", 0);
     m_autosens->changed = m_autosens_changed;
     m_autosens_changed(m_autosens);
 }
Referenced by CL_InitLocal().
CL_RegisterSounds()
void CL_RegisterSounds (void)
Definition at line 203 of file precache.c.
 {
     int i;
     char    *s;
     S_BeginRegistration();
     CL_RegisterTEntSounds();
     for (i = 1; i < MAX_SOUNDS; i++) {
         s = cl.configstrings[CS_SOUNDS + i];
         if (!s[0])
             break;
         cl.sound_precache[i] = S_RegisterSound(s);
     }
     S_EndRegistration();
 }
Referenced by CL_Begin(), CL_Precache_f(), CL_RestartFilesystem(), and CL_RestartSound_f().
CL_RegisterTEntModels()
void CL_RegisterTEntModels (void)
Definition at line 100 of file tent.c.
 {
     cl_mod_explode = R_RegisterModel("models/objects/explode/tris.md2");
     cl_mod_smoke = R_RegisterModel("models/objects/smoke/tris.md2");
     cl_mod_flash = R_RegisterModel("models/objects/flash/tris.md2");
     cl_mod_parasite_segment = R_RegisterModel("models/monsters/parasite/segment/tris.md2");
     cl_mod_grapple_cable = R_RegisterModel("models/ctf/segment/tris.md2");
     cl_mod_explo4 = R_RegisterModel("models/objects/r_explode/tris.md2");
     cl_mod_explosions[0] = R_RegisterModel("sprites/rocket_0.sp2");
     cl_mod_explosions[1] = R_RegisterModel("sprites/rocket_1.sp2");
     cl_mod_explosions[2] = R_RegisterModel("sprites/rocket_5.sp2");
     cl_mod_explosions[3] = R_RegisterModel("sprites/rocket_6.sp2");
     cl_mod_bfg_explo = R_RegisterModel("sprites/s_bfg2.sp2");
     cl_mod_powerscreen = R_RegisterModel("models/items/armor/effect/tris.md2");
     cl_mod_laser = R_RegisterModel("models/objects/laser/tris.md2");
     cl_mod_dmspot = R_RegisterModel("models/objects/dmspot/tris.md2");
     cl_mod_lightning = R_RegisterModel("models/proj/lightning/tris.md2");
     cl_mod_heatbeam = R_RegisterModel("models/proj/beam/tris.md2");
     cl_mod_explo4_big = R_RegisterModel("models/objects/r_explode2/tris.md2");
     for (int i = 0; i < sizeof(cl_mod_explosions) / sizeof(*cl_mod_explosions); i++)
     {
         model_t* model = MOD_ForHandle(cl_mod_explosions[i]);
         model->sprite_vertical = qtrue;
     }
 }
Referenced by CL_PrepRefresh().
CL_RegisterTEntSounds()
void CL_RegisterTEntSounds (void)
Definition at line 64 of file tent.c.
 {
     int     i;
     char    name[MAX_QPATH];
     cl_sfx_ric1 = S_RegisterSound("world/ric1.wav");
     cl_sfx_ric2 = S_RegisterSound("world/ric2.wav");
     cl_sfx_ric3 = S_RegisterSound("world/ric3.wav");
     cl_sfx_lashit = S_RegisterSound("weapons/lashit.wav");
     cl_sfx_flare = S_RegisterSound("weapons/flare.wav");
     cl_sfx_spark5 = S_RegisterSound("world/spark5.wav");
     cl_sfx_spark6 = S_RegisterSound("world/spark6.wav");
     cl_sfx_spark7 = S_RegisterSound("world/spark7.wav");
     cl_sfx_railg = S_RegisterSound("weapons/railgf1a.wav");
     cl_sfx_rockexp = S_RegisterSound("weapons/rocklx1a.wav");
     cl_sfx_grenexp = S_RegisterSound("weapons/grenlx1a.wav");
     cl_sfx_watrexp = S_RegisterSound("weapons/xpld_wat.wav");
     S_RegisterSound("player/land1.wav");
     S_RegisterSound("player/fall2.wav");
     S_RegisterSound("player/fall1.wav");
     for (i = 0; i < 4; i++) {
         Q_snprintf(name, sizeof(name), "player/step%i.wav", i + 1);
         cl_sfx_footsteps[i] = S_RegisterSound(name);
     }
     cl_sfx_lightning = S_RegisterSound("weapons/tesla.wav");
     cl_sfx_disrexp = S_RegisterSound("weapons/disrupthit.wav");
 }
Referenced by CL_RegisterSounds().
CL_RegisterVWepModels()
void CL_RegisterVWepModels (void)
Definition at line 269 of file precache.c.
 {
     int         i;
     char        *name;
     cl.numWeaponModels = 1;
     strcpy(cl.weaponModels[0], "weapon.md2");
     // only default model when vwep is off
     if (!cl_vwep->integer) {
         return;
     }
     for (i = 2; i < MAX_MODELS; i++) {
         name = cl.configstrings[CS_MODELS + i];
         if (!name[0]) {
             break;
         }
         if (name[0] != '#') {
             continue;
         }
         // special player weapon model
         strcpy(cl.weaponModels[cl.numWeaponModels++], name + 1);
         if (cl.numWeaponModels == MAX_CLIENTWEAPONMODELS) {
             break;
         }
     }
 }
Referenced by CL_Precache_f(), CL_Skins_f(), and cl_vwep_changed().
CL_RequestNextDownload()
void CL_RequestNextDownload (void)
Definition at line 735 of file download.c.
 {
     char fn[MAX_QPATH], *name;
     size_t len;
     int i;
     if (cls.state != ca_connected && cls.state != ca_loading)
         return;
     if (allow_download->integer <= 0 || NET_IsLocalAddress(&cls.serverAddress)) {
         if (precache_check <= PRECACHE_MAP) {
             CL_RegisterBspModels();
         }
         CL_Begin();
         return;
     }
     switch (precache_check) {
     case PRECACHE_MODELS:
         // confirm map
         if (allow_download_maps->integer)
             check_file(cl.configstrings[CS_MODELS + 1], DL_MAP);
         // checking for models
         if (allow_download_models->integer) {
             for (i = 2; i < MAX_MODELS; i++) {
                 name = cl.configstrings[CS_MODELS + i];
                 if (!name[0]) {
                     break;
                 }
                 if (name[0] == '*' || name[0] == '#') {
                     continue;
                 }
                 check_file(name, DL_MODEL);
             }
         }
         precache_check = PRECACHE_OTHER;
         // fall through
     case PRECACHE_OTHER:
         if (allow_download_models->integer) {
             if (downloads_pending(DL_MODEL)) {
                 // pending downloads (models), let's wait here before we can check skins.
                 Com_DPrintf("%s: waiting for models...\n", __func__);
                 return;
             }
             for (i = 2; i < MAX_MODELS; i++) {
                 name = cl.configstrings[CS_MODELS + i];
                 if (!name[0]) {
                     break;
                 }
                 if (name[0] == '*' || name[0] == '#') {
                     continue;
                 }
                 check_skins(name);
             }
         }
         if (allow_download_sounds->integer) {
             for (i = 1; i < MAX_SOUNDS; i++) {
                 name = cl.configstrings[CS_SOUNDS + i];
                 if (!name[0]) {
                     break;
                 }
                 if (name[0] == '*') {
                     continue;
                 }
                 if (name[0] == '#') {
                     len = Q_strlcpy(fn, name + 1, sizeof(fn));
                 } else {
                     len = Q_concat(fn, sizeof(fn), "sound/", name, NULL);
                 }
                 check_file_len(fn, len, DL_OTHER);
             }
         }
         if (allow_download_pics->integer) {
             for (i = 1; i < MAX_IMAGES; i++) {
                 name = cl.configstrings[CS_IMAGES + i];
                 if (!name[0]) {
                     break;
                 }
                 if (name[0] == '/' || name[0] == '\\') {
                     len = Q_strlcpy(fn, name + 1, sizeof(fn));
                 } else {
                     len = Q_concat(fn, sizeof(fn), "pics/", name, ".pcx", NULL);
                 }
                 check_file_len(fn, len, DL_OTHER);
             }
         }
         if (allow_download_players->integer) {
             // find sexed sounds
             precache_sexed_total = 0;
             for (i = 1; i < MAX_SOUNDS; i++) {
                 if (cl.configstrings[CS_SOUNDS + i][0] == '*') {
                     precache_sexed_sounds[precache_sexed_total++] = i;
                 }
             }
             for (i = 0; i < MAX_CLIENTS; i++) {
                 name = cl.configstrings[CS_PLAYERSKINS + i];
                 if (!name[0]) {
                     continue;
                 }
                 check_player(name);
             }
         }
         if (allow_download_textures->integer) {
             static const char env_suf[6][3] = {
                 "rt", "bk", "lf", "ft", "up", "dn"
             };
             for (i = 0; i < 6; i++) {
                 len = Q_concat(fn, sizeof(fn), "env/", cl.configstrings[CS_SKY], env_suf[i], ".tga", NULL);
                 check_file_len(fn, len, DL_OTHER);
             }
         }
         precache_check = PRECACHE_MAP;
         // fall through
     case PRECACHE_MAP:
         if (downloads_pending(DL_MAP)) {
             // map might still be downloading?
             Com_DPrintf("%s: waiting for map...\n", __func__);
             return;
         }
         // load the map file before checking textures
         CL_RegisterBspModels();
         if (allow_download_textures->integer) {
             for (i = 0; i < cl.bsp->numtexinfo; i++) {
                 len = Q_concat(fn, sizeof(fn), "textures/", cl.bsp->texinfo[i].name, ".wal", NULL);
                 check_file_len(fn, len, DL_OTHER);
             }
         }
         precache_check = PRECACHE_FINAL;
         // fall through
     case PRECACHE_FINAL:
         if (downloads_pending(DL_OTHER)) {
             // pending downloads (possibly textures), let's wait here.
             Com_DPrintf("%s: waiting for others...\n", __func__);
             return;
         }
         // all done, tell server we are ready
         CL_Begin();
         break;
     default:
         Com_Error(ERR_DROP, "%s: bad precache_check\n", __func__);
     }
 }
Referenced by abort_downloads(), CL_Precache_f(), finish_download(), finish_udp_download(), and start_download().
CL_ResetPrecacheCheck()
void CL_ResetPrecacheCheck (void)
Definition at line 897 of file download.c.
 {
     precache_check = PRECACHE_MODELS;
 }
Referenced by CL_Precache_f().
CL_RestartFilesystem()
void CL_RestartFilesystem (qboolean total)
Definition at line 2418 of file main.c.
 {
     int cls_state;
     if (!cl_running->integer) {
         FS_Restart(total);
         return;
     }
     Com_DPrintf("%s(%d)\n", __func__, total);
     // temporary switch to loading state
     cls_state = cls.state;
     if (cls.state >= ca_precached) {
         cls.state = ca_loading;
     }
     Con_Popup(qfalse);
     UI_Shutdown();
     S_StopAllSounds();
     S_FreeAllSounds();
     // write current config before changing game directory
     CL_WriteConfig();
     if (cls.ref_initialized) {
         R_Shutdown(qfalse);
         FS_Restart(total);
         R_Init(qfalse);
         SCR_RegisterMedia();
         Con_RegisterMedia();
         UI_Init();
     } else {
         FS_Restart(total);
     }
     if (cls_state == ca_disconnected) {
         UI_OpenMenu(UIMENU_DEFAULT);
     } else if (cls_state >= ca_loading && cls_state <= ca_active) {
         CL_LoadState(LOAD_MAP);
         CL_PrepRefresh();
         CL_LoadState(LOAD_SOUNDS);
         CL_RegisterSounds();
         CL_LoadState(LOAD_NONE);
     } else if (cls_state == ca_cinematic) {
         cl.image_precache[0] = R_RegisterPic2(cl.mapname);
     }
     CL_LoadDownloadIgnores();
     // switch back to original state
     cls.state = cls_state;
     Con_Close(qfalse);
     CL_UpdateFrameTimes();
     cvar_modified &= ~CVAR_FILES;
 }
Referenced by finish_download(), fs_game_changed(), and FS_Restart_f().
CL_RestartRefresh()
void CL_RestartRefresh (qboolean total)
Definition at line 2483 of file main.c.
 {
     int cls_state;
     if (!cls.ref_initialized) {
         return;
     }
     // temporary switch to loading state
     cls_state = cls.state;
     if (cls.state >= ca_precached) {
         cls.state = ca_loading;
     }
     Con_Popup(qfalse);
     S_StopAllSounds();
     if (total) {
         IN_Shutdown();
         CL_ShutdownRefresh();
         CL_InitRefresh();
         IN_Init();
     } else {
         UI_Shutdown();
         R_Shutdown(qfalse);
         R_Init(qfalse);
         SCR_RegisterMedia();
         Con_RegisterMedia();
         UI_Init();
     }
     if (cls_state == ca_disconnected) {
         UI_OpenMenu(UIMENU_DEFAULT);
     } else if (cls_state >= ca_loading && cls_state <= ca_active) {
         CL_LoadState(LOAD_MAP);
         CL_PrepRefresh();
         CL_LoadState(LOAD_NONE);
     } else if (cls_state == ca_cinematic) {
         cl.image_precache[0] = R_RegisterPic2(cl.mapname);
     }
     // switch back to original state
     cls.state = cls_state;
     Con_Close(qfalse);
     CL_UpdateFrameTimes();
     cvar_modified &= ~CVAR_FILES;
 }
Referenced by CL_ReloadRefresh_f(), CL_RestartRefresh_f(), and CL_RunRefresh().
CL_RocketTrail()
void CL_RocketTrail (vec3_t start, vec3_t end, centity_t * old)
Definition at line 1579 of file effects.c.
 {
     vec3_t      move;
     vec3_t      vec;
     float       len;
     int         j;
     cparticle_t *p;
     float       dec;
     // smoke
     CL_DiminishingTrail(start, end, old, EF_ROCKET);
     // fire
     VectorCopy(start, move);
     VectorSubtract(end, start, vec);
     len = VectorNormalize(vec);
     dec = 1;
     VectorScale(vec, dec, vec);
     while (len > 0) {
         len -= dec;
         if ((rand() & 7) == 0) {
             p = CL_AllocParticle();
             if (!p)
                 return;
             VectorClear(p->accel);
             p->time = cl.time;
             p->alpha = 1.0;
             p->alphavel = -1.0 / (1 + frand() * 0.2);
             p->color = 0xdc + (rand() & 3);
             p->brightness = cvar_pt_particle_emissive->value;
             for (j = 0; j < 3; j++) {
                 p->org[j] = move[j] + crand() * 5;
                 p->vel[j] = crand() * 20;
             }
             p->accel[2] = -PARTICLE_GRAVITY;
         }
         VectorAdd(move, vec, move);
     }
 }
Referenced by CL_AddPacketEntities().
CL_RunParticles()
void CL_RunParticles (void)
CL_RunRefresh()
void CL_RunRefresh (void)
Definition at line 232 of file refresh.c.
 {
     if (!cls.ref_initialized) {
         return;
     }
     VID_PumpEvents();
     if (mode_changed) {
         if (mode_changed & MODE_FULLSCREEN) {
             VID_SetMode();
             if (vid_fullscreen->integer) {
                 Cvar_Set("_vid_fullscreen", vid_fullscreen->string);
             }
         } else {
             if (vid_fullscreen->integer) {
                 if (mode_changed & MODE_MODELIST) {
                     VID_SetMode();
                 }
             } else {
                 if (mode_changed & MODE_GEOMETRY) {
                     VID_SetMode();
                 }
             }
         }
         mode_changed = 0;
     }
     if (cvar_modified & CVAR_REFRESH) {
         CL_RestartRefresh(qtrue);
         cvar_modified &= ~CVAR_REFRESH;
     } else if (cvar_modified & CVAR_FILES) {
         CL_RestartRefresh(qfalse);
         cvar_modified &= ~CVAR_FILES;
     }
 }
Referenced by CL_ProcessEvents().
CL_SeekDemoMessage()
void CL_SeekDemoMessage (void)
Definition at line 1343 of file parse.c.
 {
     int         cmd, extrabits;
     int         index;
 #ifdef _DEBUG
     if (cl_shownet->integer == 1) {
         Com_LPrintf(PRINT_DEVELOPER, "%"PRIz" ", msg_read.cursize);
     } else if (cl_shownet->integer > 1) {
         Com_LPrintf(PRINT_DEVELOPER, "------------------\n");
     }
 #endif
 //
 // parse the message
 //
     while (1) {
         if (msg_read.readcount > msg_read.cursize) {
             Com_Error(ERR_DROP, "%s: read past end of server message", __func__);
         }
         if ((cmd = MSG_ReadByte()) == -1) {
             SHOWNET(1, "%3"PRIz":END OF MESSAGE\n", msg_read.readcount - 1);
             break;
         }
         extrabits = cmd >> SVCMD_BITS;
         cmd &= SVCMD_MASK;
 #ifdef _DEBUG
         if (cl_shownet->integer > 1) {
             MSG_ShowSVC(cmd);
         }
 #endif
         // other commands
         switch (cmd) {
         default:
             Com_Error(ERR_DROP, "%s: illegible server message: %d", __func__, cmd);
             break;
         case svc_nop:
             break;
         case svc_disconnect:
         case svc_reconnect:
             Com_Error(ERR_DISCONNECT, "Server disconnected");
             break;
         case svc_print:
             MSG_ReadByte();
             // fall thorugh
         case svc_centerprint:
         case svc_stufftext:
             MSG_ReadString(NULL, 0);
             break;
         case svc_configstring:
             index = MSG_ReadShort();
             CL_ParseConfigstring(index);
             break;
         case svc_sound:
             CL_ParseStartSoundPacket();
             break;
         case svc_temp_entity:
             CL_ParseTEntPacket();
             break;
         case svc_muzzleflash:
         case svc_muzzleflash2:
             CL_ParseMuzzleFlashPacket(0);
             break;
         case svc_frame:
             CL_ParseFrame(extrabits);
             continue;
         case svc_inventory:
             CL_ParseInventory();
             break;
         case svc_layout:
             CL_ParseLayout();
             break;
         }
     }
 }
Referenced by CL_Seek_f().
CL_SendCmd()
void CL_SendCmd (void)
Definition at line 1166 of file input.c.
 {
     if (cls.state < ca_connected) {
         return; // not talking to a server
     }
     // generate usercmds while playing a demo,
     // but do not send them
     if (!cls.netchan) {
         return;
     }
     if (cls.state != ca_active || sv_paused->integer) {
         // send a userinfo update if needed
         CL_SendUserinfo();
         // just keepalive or update reliable
         if (cls.netchan->ShouldUpdate(cls.netchan)) {
             CL_SendKeepAlive();
         }
         cl.sendPacketNow = qfalse;
         return;
     }
     // are there any new usercmds to send after all?
     if (cl.lastTransmitCmdNumber == cl.cmdNumber) {
         return; // nothing to send
     }
     // send a userinfo update if needed
     CL_SendUserinfo();
     if (cls.serverProtocol == PROTOCOL_VERSION_Q2PRO && cl_batchcmds->integer) {
         CL_SendBatchedCmd();
     } else {
         CL_SendDefaultCmd();
     }
     cl.sendPacketNow = qfalse;
 }
Referenced by CL_Frame().
CL_SendRcon()
void CL_SendRcon (const netadr_t * adr, const char * pass, const char * cmd)
Definition at line 637 of file main.c.
 {
     NET_Config(NET_CLIENT);
     CL_AddRequest(adr, REQ_RCON);
     Netchan_OutOfBand(NS_CLIENT, adr, "rcon \"%s\" %s", pass, cmd);
 }
Referenced by CL_Rcon_f(), and Con_Action().
CL_Server_g()
const char* CL_Server_g (const char * partial, int argnum, int state)
CL_ShutdownRefresh()
void CL_ShutdownRefresh (void)
Definition at line 375 of file refresh.c.
 {
     if (!cls.ref_initialized) {
         return;
     }
     // Shutdown the rest of graphics subsystems
     V_Shutdown();
     SCR_Shutdown();
     UI_Shutdown();
     vid_geometry->changed = NULL;
     vid_fullscreen->changed = NULL;
     vid_modelist->changed = NULL;
     R_Shutdown(qtrue);
     cls.ref_initialized = qfalse;
     // no longer active
     cls.active = ACT_MINIMIZED;
     Z_LeakTest(TAG_RENDERER);
 }
Referenced by CL_RestartRefresh(), and CL_Shutdown().
CL_SmokeAndFlash()
void CL_SmokeAndFlash (vec3_t origin)
Definition at line 207 of file tent.c.
 {
     explosion_t *ex;
     ex = CL_AllocExplosion();
     VectorCopy(origin, ex->ent.origin);
     ex->type = ex_misc;
     ex->frames = 4;
     ex->ent.flags = RF_TRANSLUCENT | RF_NOSHADOW;
     ex->start = cl.servertime - CL_FRAMETIME;
     ex->ent.model = cl_mod_smoke;
     ex = CL_AllocExplosion();
     VectorCopy(origin, ex->ent.origin);
     ex->type = ex_flash;
     ex->ent.flags = RF_FULLBRIGHT;
     ex->frames = 2;
     ex->start = cl.servertime - CL_FRAMETIME;
     ex->ent.model = cl_mod_flash;
 }
Referenced by CL_MuzzleFlash2(), and CL_ParseTEnt().
CL_SmokeTrail()
void CL_SmokeTrail (vec3_t start, vec3_t end, int colorStart, int colorRun, int spacing)
Definition at line 105 of file newfx.c.
 {
     vec3_t      move;
     vec3_t      vec;
     float       len;
     int         j;
     cparticle_t *p;
     VectorCopy(start, move);
     VectorSubtract(end, start, vec);
     len = VectorNormalize(vec);
     VectorScale(vec, spacing, vec);
     // FIXME: this is a really silly way to have a loop
     while (len > 0) {
         len -= spacing;
         p = CL_AllocParticle();
         if (!p)
             return;
         VectorClear(p->accel);
         p->time = cl.time;
         p->alpha = 1.0;
         p->alphavel = -1.0 / (1 + frand() * 0.5);
         p->color = colorStart + (rand() % colorRun);
         for (j = 0; j < 3; j++) {
             p->org[j] = move[j] + crand() * 3;
             p->accel[j] = 0;
         }
         p->vel[2] = 20 + crand() * 5;
         VectorAdd(move, vec, move);
     }
 }
CL_StartNextDownload()
void CL_StartNextDownload (void)
Definition at line 294 of file download.c.
 {
     dlqueue_t *q;
     if (!cls.download.pending || cls.download.current) {
         return;
     }
     FOR_EACH_DLQ(q) {
         if (q->state == DL_PENDING) {
             if (start_udp_download(q)) {
                 break;
             }
         }
     }
 }
Referenced by abort_downloads(), check_file_len(), and finish_udp_download().
CL_Stop_f()
void CL_Stop_f (void)
Definition at line 268 of file demo.c.
 {
     uint32_t msglen;
     char buffer[MAX_QPATH];
     if (!cls.demo.recording) {
         Com_Printf("Not recording a demo.\n");
         return;
     }
 // finish up
     msglen = (uint32_t)-1;
     FS_Write(&msglen, 4, cls.demo.recording);
     format_demo_size(buffer, sizeof(buffer));
 // close demofile
     FS_FCloseFile(cls.demo.recording);
     cls.demo.recording = 0;
     cls.demo.paused = qfalse;
     cls.demo.frames_written = 0;
     cls.demo.frames_dropped = 0;
     cls.demo.others_dropped = 0;
 // print some statistics
     Com_Printf("Stopped demo (%s).\n", buffer);
 // tell the server we finished recording
     CL_UpdateRecordingSetting();
 }
Referenced by CL_Changing_f(), CL_CleanupDemos(), and CL_WriteDemoMessage().
CL_TagTrail()
void CL_TagTrail (vec3_t start, vec3_t end, int color)
Definition at line 646 of file newfx.c.
 {
     vec3_t      move;
     vec3_t      vec;
     float       len;
     int         j;
     cparticle_t *p;
     int         dec;
     VectorCopy(start, move);
     VectorSubtract(end, start, vec);
     len = VectorNormalize(vec);
     dec = 5;
     VectorScale(vec, 5, vec);
     while (len >= 0) {
         len -= dec;
         p = CL_AllocParticle();
         if (!p)
             return;
         VectorClear(p->accel);
         p->time = cl.time;
         p->alpha = 1.0;
         p->alphavel = -1.0 / (0.8 + frand() * 0.2);
         p->color = color;
         for (j = 0; j < 3; j++) {
             p->org[j] = move[j] + crand() * 16;
             p->vel[j] = crand() * 5;
             p->accel[j] = 0;
         }
         VectorAdd(move, vec, move);
     }
 }
Referenced by CL_AddPacketEntities().
CL_TeleporterParticles()
void CL_TeleporterParticles (vec3_t org)
Definition at line 1098 of file effects.c.
 {
     int         i, j;
     cparticle_t *p;
     const int count = 8 * cl_particle_num_factor->value;
     for (i = 0; i < count; i++) {
         p = CL_AllocParticle();
         if (!p)
             return;
         p->time = cl.time;
         p->color = 0xdb;
         p->brightness = 1.0f;
         for (j = 0; j < 2; j++) {
             p->org[j] = org[j] - 16 + (rand() & 31);
             p->vel[j] = crand() * 14;
         }
         p->org[2] = org[2] - 8 + (rand() & 7);
         p->vel[2] = 80 + (rand() & 7);
         p->accel[0] = p->accel[1] = 0;
         p->accel[2] = -PARTICLE_GRAVITY;
         p->alpha = 1.0;
         p->alphavel = -0.5;
     }
 }
Referenced by entity_event().
CL_TeleportParticles()
void CL_TeleportParticles (vec3_t org)
Definition at line 1942 of file effects.c.
 {
     int         i, j, k;
     cparticle_t *p;
     float       vel;
     vec3_t      dir;
     for (i = -16; i <= 16; i += 4)
         for (j = -16; j <= 16; j += 4)
             for (k = -16; k <= 32; k += 4) {
                 p = CL_AllocParticle();
                 if (!p)
                     return;
                 p->time = cl.time;
                 p->color = 7 + (rand() & 7);
                 p->brightness = 1.0f;
                 p->alpha = 1.0;
                 p->alphavel = -1.0 / (0.3 + (rand() & 7) * 0.02);
                 p->org[0] = org[0] + i + (rand() & 3);
                 p->org[1] = org[1] + j + (rand() & 3);
                 p->org[2] = org[2] + k + (rand() & 3);
                 dir[0] = j * 8;
                 dir[1] = i * 8;
                 dir[2] = k * 8;
                 VectorNormalize(dir);
                 vel = 50 + (rand() & 63);
                 VectorScale(dir, vel, p->vel);
                 p->accel[0] = p->accel[1] = 0;
                 p->accel[2] = -PARTICLE_GRAVITY;
             }
 }
Referenced by CL_ParseTEnt(), and entity_event().
CL_Tracker_Explode()
void CL_Tracker_Explode (vec3_t origin)
Definition at line 611 of file newfx.c.
 {
     vec3_t          dir, backdir;
     int             i;
     cparticle_t     *p;
     for (i = 0; i < 300; i++) {
         p = CL_AllocParticle();
         if (!p)
             return;
         VectorClear(p->accel);
         p->time = cl.time;
         p->alpha = 1.0;
         p->alphavel = -1.0;
         p->color = 0;
         dir[0] = crand();
         dir[1] = crand();
         dir[2] = crand();
         VectorNormalize(dir);
         VectorScale(dir, -1, backdir);
         VectorMA(origin, 64, dir, p->org);
         VectorScale(backdir, 64, p->vel);
     }
 }
CL_Tracker_Shell()
void CL_Tracker_Shell (vec3_t origin)
Definition at line 466 of file newfx.c.
 {
     vec3_t          dir;
     int             i;
     cparticle_t     *p;
     for (i = 0; i < 300; i++) {
         p = CL_AllocParticle();
         if (!p)
             return;
         VectorClear(p->accel);
         p->time = cl.time;
         p->alpha = 1.0;
         p->alphavel = INSTANT_PARTICLE;
         p->color = 0;
         dir[0] = crand();
         dir[1] = crand();
         dir[2] = crand();
         VectorNormalize(dir);
         VectorMA(origin, 40, dir, p->org);
     }
 }
Referenced by CL_AddPacketEntities().
CL_TrackerTrail()
void CL_TrackerTrail (vec3_t start, vec3_t end, int particleColor)
Definition at line 418 of file newfx.c.
 {
     vec3_t      move;
     vec3_t      vec;
     vec3_t      forward, right, up, angle_dir;
     float       len;
     int         j;
     cparticle_t *p;
     int         dec;
     float       dist;
     VectorCopy(start, move);
     VectorSubtract(end, start, vec);
     len = VectorNormalize(vec);
     VectorCopy(vec, forward);
     vectoangles2(forward, angle_dir);
     AngleVectors(angle_dir, forward, right, up);
     dec = 3;
     VectorScale(vec, 3, vec);
     // FIXME: this is a really silly way to have a loop
     while (len > 0) {
         len -= dec;
         p = CL_AllocParticle();
         if (!p)
             return;
         VectorClear(p->accel);
         p->time = cl.time;
         p->alpha = 1.0;
         p->alphavel = -2.0;
         p->color = particleColor;
         dist = DotProduct(move, forward);
         VectorMA(move, 8 * cos(dist), up, p->org);
         for (j = 0; j < 3; j++) {
             p->vel[j] = 0;
             p->accel[j] = 0;
         }
         p->vel[2] = 5;
         VectorAdd(move, vec, move);
     }
 }
Referenced by CL_AddPacketEntities().
CL_TrapParticles()
void CL_TrapParticles (entity_t * ent)
Definition at line 897 of file newfx.c.
 {
     vec3_t      move;
     vec3_t      vec;
     vec3_t      start, end;
     float       len;
     int         j;
     cparticle_t *p;
     int         dec;
     ent->origin[2] -= 14;
     VectorCopy(ent->origin, start);
     VectorCopy(ent->origin, end);
     end[2] += 64;
     VectorCopy(start, move);
     VectorSubtract(end, start, vec);
     len = VectorNormalize(vec);
     dec = 5;
     VectorScale(vec, 5, vec);
     // FIXME: this is a really silly way to have a loop
     while (len > 0) {
         len -= dec;
         p = CL_AllocParticle();
         if (!p)
             return;
         VectorClear(p->accel);
         p->time = cl.time;
         p->alpha = 1.0;
         p->alphavel = -1.0 / (0.3 + frand() * 0.2);
         p->color = 0xe0;
         for (j = 0; j < 3; j++) {
             p->org[j] = move[j] + crand();
             p->vel[j] = crand() * 15;
             p->accel[j] = 0;
         }
         p->accel[2] = PARTICLE_GRAVITY;
         VectorAdd(move, vec, move);
     }
     {
         int         i, j, k;
         cparticle_t *p;
         float       vel;
         vec3_t      dir;
         vec3_t      org;
         ent->origin[2] += 14;
         VectorCopy(ent->origin, org);
         for (i = -2; i <= 2; i += 4)
             for (j = -2; j <= 2; j += 4)
                 for (k = -2; k <= 4; k += 4) {
                     p = CL_AllocParticle();
                     if (!p)
                         return;
                     p->time = cl.time;
                     p->color = 0xe0 + (rand() & 3);
                     p->alpha = 1.0;
                     p->alphavel = -1.0 / (0.3 + (rand() & 7) * 0.02);
                     p->org[0] = org[0] + i + ((rand() & 23) * crand());
                     p->org[1] = org[1] + j + ((rand() & 23) * crand());
                     p->org[2] = org[2] + k + ((rand() & 23) * crand());
                     dir[0] = j * 8;
                     dir[1] = i * 8;
                     dir[2] = k * 8;
                     VectorNormalize(dir);
                     vel = 50 + (rand() & 63);
                     VectorScale(dir, vel, p->vel);
                     p->accel[0] = p->accel[1] = 0;
                     p->accel[2] = -PARTICLE_GRAVITY;
                 }
     }
 }
Referenced by CL_AddPacketEntities().
CL_UpdateBlendSetting()
void CL_UpdateBlendSetting (void)
Definition at line 292 of file view.c.
 {
     if (cls.state < ca_connected) {
         return;
     }
     if (cls.serverProtocol < PROTOCOL_VERSION_R1Q2) {
         return;
     }
     MSG_WriteByte(clc_setting);
     MSG_WriteShort(CLS_NOBLEND);
     MSG_WriteShort(!cl_add_blend->integer);
     MSG_FlushTo(&cls.netchan->message);
 }
Referenced by cl_add_blend_changed(), and CL_Begin().
CL_UpdateCmd()
void CL_UpdateCmd (int msec)
Definition at line 655 of file input.c.
 {
     VectorClear(cl.localmove);
     if (sv_paused->integer) {
         return;
     }
     // add to milliseconds of time to apply the move
     cl.cmd.msec += msec;
     // adjust viewangles
     CL_AdjustAngles(msec);
     // get basic movement from keyboard
     CL_BaseMove(cl.localmove);
     // allow mice to add to the move
     CL_MouseMove();
     // add accumulated mouse forward/side movement
     cl.localmove[0] += cl.mousemove[0];
     cl.localmove[1] += cl.mousemove[1];
     // clamp to server defined max speed
     CL_ClampSpeed(cl.localmove);
     CL_ClampPitch();
     cl.cmd.angles[0] = ANGLE2SHORT(cl.viewangles[0]);
     cl.cmd.angles[1] = ANGLE2SHORT(cl.viewangles[1]);
     cl.cmd.angles[2] = ANGLE2SHORT(cl.viewangles[2]);
 }
Referenced by CL_Frame().
CL_UpdateConfigstring()
void CL_UpdateConfigstring (int index)
Definition at line 417 of file precache.c.
 {
     const char *s = cl.configstrings[index];
     if (index == CS_MAXCLIENTS) {
         cl.maxclients = atoi(s);
         return;
     }
     if (index == CS_AIRACCEL) {
         if (cl.pmp.qwmode)
             cl.pmp.airaccelerate = qtrue;
         else
             cl.pmp.airaccelerate = atoi(s) ? qtrue : qfalse;
         return;
     }
     if (index == CS_MODELS + 1) {
         size_t len = strlen(s);
         if (len <= 9) {
             Com_Error(ERR_DROP, "%s: bad world model: %s", __func__, s);
         }
         memcpy(cl.mapname, s + 5, len - 9);   // skip "maps/"
         cl.mapname[len - 9] = 0; // cut off ".bsp"
         return;
     }
 #if USE_LIGHTSTYLES
     if (index >= CS_LIGHTS && index < CS_LIGHTS + MAX_LIGHTSTYLES) {
         CL_SetLightStyle(index - CS_LIGHTS, s);
         return;
     }
 #endif
     if (cls.state < ca_precached) {
         return;
     }
     if (index >= CS_MODELS + 2 && index < CS_MODELS + MAX_MODELS) {
         int i = index - CS_MODELS;
         cl.model_draw[i] = R_RegisterModel(s);
         if (*s == '*')
             cl.model_clip[i] = BSP_InlineModel(cl.bsp, s);
         else
             cl.model_clip[i] = NULL;
         return;
     }
     if (index >= CS_SOUNDS && index < CS_SOUNDS + MAX_SOUNDS) {
         cl.sound_precache[index - CS_SOUNDS] = S_RegisterSound(s);
         return;
     }
     if (index >= CS_IMAGES && index < CS_IMAGES + MAX_IMAGES) {
         cl.image_precache[index - CS_IMAGES] = R_RegisterPic2(s);
         return;
     }
     if (index >= CS_PLAYERSKINS && index < CS_PLAYERSKINS + MAX_CLIENTS) {
         CL_LoadClientinfo(&cl.clientinfo[index - CS_PLAYERSKINS], s);
         return;
     }
 }
Referenced by CL_ParseConfigstring(), and CL_Seek_f().
CL_UpdateFrameTimes()
void CL_UpdateFrameTimes (void)
Definition at line 3136 of file main.c.
 {
     if (!cls.state) {
         return; // not yet fully initialized
     }
     // check if video driver supports syncing to vertical retrace
     if (cl_async->integer > 1 && !(r_config.flags & QVF_VIDEOSYNC)) {
         Cvar_Reset(cl_async);
     }
     if (com_timedemo->integer) {
         // timedemo just runs at full speed
         ref_msec = phys_msec = main_msec = 0;
         sync_mode = SYNC_FULL;
     } else if (cls.active == ACT_MINIMIZED) {
         // run at 10 fps if minimized
         ref_msec = phys_msec = 0;
         main_msec = fps_to_msec(10);
         sync_mode = SYNC_SLEEP_10;
     } else if (cls.active == ACT_RESTORED || cls.state != ca_active) {
         // run at 60 fps if not active
         ref_msec = phys_msec = 0;
         if (cl_async->integer > 1) {
             main_msec = 0;
             sync_mode = SYNC_SLEEP_VIDEO;
         } else {
             main_msec = fps_to_msec(60);
             sync_mode = SYNC_SLEEP_60;
         }
     } else if (cl_async->integer > 0) {
         // run physics and refresh separately
         phys_msec = fps_to_msec(Cvar_ClampInteger(cl_maxfps, 10, 120));
         if (cl_async->integer > 1) {
             ref_msec = 0;
             sync_mode = ASYNC_VIDEO;
         } else if (r_maxfps->integer) {
             ref_msec = fps_to_msec(Cvar_ClampInteger(r_maxfps, 10, 1000));
             sync_mode = ASYNC_MAXFPS;
         } else {
             ref_msec = 1;
             sync_mode = ASYNC_FULL;
         }
         main_msec = 0;
     } else {
         // everything ticks in sync with refresh
         phys_msec = ref_msec = 0;
         if (cl_maxfps->integer) {
             main_msec = fps_to_msec(Cvar_ClampInteger(cl_maxfps, 10, 1000));
             sync_mode = SYNC_MAXFPS;
         } else {
             main_msec = 1;
             sync_mode = SYNC_FULL;
         }
     }
     Com_DDDPrintf("%s: mode=%s main_msec=%d ref_msec=%d, phys_msec=%d\n",
                   __func__, sync_names[sync_mode], main_msec, ref_msec, phys_msec);
     ref_extra = phys_extra = main_extra = 0;
 }
Referenced by CL_Activate(), CL_Changing_f(), CL_ClearState(), CL_Disconnect(), CL_InitLocal(), CL_RestartFilesystem(), CL_RestartRefresh(), cl_sync_changed(), SCR_ModeChanged(), and set_active_state().
CL_UpdateRecordingSetting()
void CL_UpdateRecordingSetting (void)
Definition at line 265 of file main.c.
 {
     int rec;
     if (!cls.netchan) {
         return;
     }
     if (cls.serverProtocol < PROTOCOL_VERSION_R1Q2) {
         return;
     }
     if (cls.demo.recording) {
         rec = 1;
     } else {
         rec = 0;
     }
 #if USE_CLIENT_GTV
     if (cls.gtv.state == ca_active) {
         rec |= 1;
     }
 #endif
     MSG_WriteByte(clc_setting);
     MSG_WriteShort(CLS_RECORDING);
     MSG_WriteShort(rec);
     MSG_FlushTo(&cls.netchan->message);
 }
Referenced by CL_Begin(), CL_Record_f(), CL_Stop_f(), parse_stream_start(), and parse_stream_stop().
CL_Widowbeamout()
void CL_Widowbeamout (cl_sustain_t * self)
Definition at line 520 of file newfx.c.
 {
     static const byte   colortable[4] = {2 * 8, 13 * 8, 21 * 8, 18 * 8};
     vec3_t          dir;
     int             i;
     cparticle_t     *p;
     float           ratio;
     ratio = 1.0 - (((float)self->endtime - (float)cl.time) / 2100.0);
     for (i = 0; i < 300; i++) {
         p = CL_AllocParticle();
         if (!p)
             return;
         VectorClear(p->accel);
         p->time = cl.time;
         p->alpha = 1.0;
         p->alphavel = INSTANT_PARTICLE;
         p->color = colortable[rand() & 3];
         dir[0] = crand();
         dir[1] = crand();
         dir[2] = crand();
         VectorNormalize(dir);
         VectorMA(self->org, (45.0 * ratio), dir, p->org);
     }
 }
Referenced by CL_ParseWidow().
CL_WidowSplash()
void CL_WidowSplash (void)
Definition at line 582 of file newfx.c.
 {
     static const byte   colortable[4] = {2 * 8, 13 * 8, 21 * 8, 18 * 8};
     int         i;
     cparticle_t *p;
     vec3_t      dir;
     for (i = 0; i < 256; i++) {
         p = CL_AllocParticle();
         if (!p)
             return;
         p->time = cl.time;
         p->color = colortable[rand() & 3];
         dir[0] = crand();
         dir[1] = crand();
         dir[2] = crand();
         VectorNormalize(dir);
         VectorMA(te.pos1, 45.0, dir, p->org);
         VectorMA(vec3_origin, 40.0, dir, p->vel);
         p->accel[0] = p->accel[1] = 0;
         p->alpha = 1.0;
         p->alphavel = -0.8 / (0.5 + frand() * 0.3);
     }
 }
Referenced by CL_ParseTEnt().
CL_WriteConfig()
void CL_WriteConfig (void)
Definition at line 2391 of file main.c.
 {
     qhandle_t f;
     qerror_t ret;
     ret = FS_FOpenFile(COM_CONFIG_CFG, &f, FS_MODE_WRITE | FS_FLAG_TEXT);
     if (!f) {
         Com_EPrintf("Couldn't open %s for writing: %s\n",
                     COM_CONFIG_CFG, Q_ErrorString(ret));
         return;
     }
     FS_FPrintf(f, "// generated by " APPLICATION ", do not modify\n");
     Key_WriteBindings(f);
     Cvar_WriteVariables(f, CVAR_ARCHIVE, qfalse);
     FS_FCloseFile(f);
 }
Referenced by CL_RestartFilesystem(), CL_Shutdown(), and UI_PopMenu().
CL_WriteDemoMessage()
qboolean CL_WriteDemoMessage (sizebuf_t * buf)
Definition at line 41 of file demo.c.
 {
     uint32_t msglen;
     ssize_t ret;
     if (buf->overflowed) {
         SZ_Clear(buf);
         Com_WPrintf("Demo message overflowed (should never happen).\n");
         return qtrue;
     }
     if (!buf->cursize)
         return qtrue;
     msglen = LittleLong(buf->cursize);
     ret = FS_Write(&msglen, 4, cls.demo.recording);
     if (ret != 4)
         goto fail;
     ret = FS_Write(buf->data, buf->cursize, cls.demo.recording);
     if (ret != buf->cursize)
         goto fail;
     Com_DDPrintf("%s: wrote %"PRIz" bytes\n", __func__, buf->cursize);
     SZ_Clear(buf);
     return qtrue;
 fail:
     SZ_Clear(buf);
     Com_EPrintf("Couldn't write demo: %s\n", Q_ErrorString(ret));
     CL_Stop_f();
     return qfalse;
 }
Referenced by CL_PacketEvent(), CL_Record_f(), parse_next_message(), and resume_record().
COM_BlockSequenceCRCByte()
byte COM_BlockSequenceCRCByte (byte * base, size_t length, int sequence)
Definition at line 148 of file crc.c.
 {
     int     n;
     const byte  *p;
     int     x;
     byte chkb[60 + 4];
     unsigned short crc;
     if (sequence < 0)
         Com_Error(ERR_DROP, "%s: sequence < 0", __func__);
     p = chktbl + (sequence % (sizeof(chktbl) - 4));
     if (length > 60)
         length = 60;
     memcpy(chkb, base, length);
     chkb[length] = p[0];
     chkb[length + 1] = p[1];
     chkb[length + 2] = p[2];
     chkb[length + 3] = p[3];
     length += 4;
     crc = CRC_Block(chkb, length);
     for (x = 0, n = 0; n < length; n++)
         x += chkb[n];
     crc = (crc ^ x) & 0xff;
     return crc;
 }
Referenced by CL_SendDefaultCmd().
Con_CheckResize()
void Con_CheckResize (void)
Definition at line 367 of file console.c.
 {
     int     width;
     con.scale = R_ClampScale(con_scale);
     con.vidWidth = r_config.width * con.scale;
     con.vidHeight = r_config.height * con.scale;
     width = (con.vidWidth / CHAR_WIDTH) - 2;
     con.linewidth = width > CON_LINEWIDTH ? CON_LINEWIDTH : width;
     con.prompt.inputLine.visibleChars = con.linewidth;
     con.prompt.widthInChars = con.linewidth - 1; // account for color byte
     con.chatPrompt.inputLine.visibleChars = con.linewidth;
 }
Referenced by Con_Init(), con_scale_changed(), and SCR_ModeChanged().
Con_ClearNotify_f()
void Con_ClearNotify_f (void)
Definition at line 276 of file console.c.
 {
     int     i;
     for (i = 0; i < CON_TIMES; i++)
         con.times[i] = 0;
 }
Referenced by CL_PrepRefresh(), Con_Close(), SCR_CenterPrint(), SCR_EndLoadingPlaque(), and toggle_console().
Con_ClearTyping()
void Con_ClearTyping (void)
Definition at line 109 of file console.c.
 {
     // clear any typing
     IF_Clear(&con.prompt.inputLine);
     Prompt_ClearState(&con.prompt);
 }
Referenced by Con_Close(), and toggle_console().
Con_Close()
void Con_Close (qboolean force)
Definition at line 124 of file console.c.
 {
     if (con.mode > CON_POPUP && !force) {
         return;
     }
     // if not connected, console or menu should be up
     if (cls.state < ca_active && !(cls.key_dest & KEY_MENU)) {
         return;
     }
     Con_ClearTyping();
     Con_ClearNotify_f();
     Key_SetDest(cls.key_dest & ~KEY_CONSOLE);
     con.destHeight = con.currentHeight = 0;
     con.mode = CON_POPUP;
     con.chat = CHAT_NONE;
 }
Referenced by CL_RestartFilesystem(), CL_RestartRefresh(), Key_Event(), SCR_PlayCinematic(), set_active_state(), start_message_mode(), and UI_PushMenu().
Con_DrawConsole()
void Con_DrawConsole (void)
Definition at line 1032 of file console.c.
 {
     R_SetScale(con.scale);
     Con_DrawSolidConsole();
     Con_DrawNotify();
     R_SetScale(1.0f);
 }
Referenced by SCR_UpdateScreen().
Con_Init()
void Con_Init (void)
Definition at line 436 of file console.c.
 {
     memset(&con, 0, sizeof(con));
 //
 // register our commands
 //
     Cmd_Register(c_console);
     con_notifytime = Cvar_Get("con_notifytime", "3", 0);
     con_notifylines = Cvar_Get("con_notifylines", "4", 0);
     con_clock = Cvar_Get("con_clock", "0", 0);
     con_height = Cvar_Get("con_height", "0.5", 0);
     con_speed = Cvar_Get("scr_conspeed", "3", 0);
     con_alpha = Cvar_Get("con_alpha", "1", 0);
     con_scale = Cvar_Get("con_scale", "1", 0);
     con_scale->changed = con_scale_changed;
     con_font = Cvar_Get("con_font", "conchars", 0);
     con_font->changed = con_param_changed;
     con_background = Cvar_Get("con_background", "conback", 0);
     con_background->changed = con_param_changed;
     con_scroll = Cvar_Get("con_scroll", "0", 0);
     con_history = Cvar_Get("con_history", "0", 0);
     IF_Init(&con.prompt.inputLine, 0, MAX_FIELD_TEXT - 1);
     IF_Init(&con.chatPrompt.inputLine, 0, MAX_FIELD_TEXT - 1);
     con.prompt.printf = Con_Printf;
     // use default width since no video is initialized yet
     r_config.width = 640;
     r_config.height = 480;
     con.linewidth = -1;
     con.scale = 1;
     con.color = COLOR_NONE;
     con.text[0][0] = COLOR_NONE;
     con.x = 1;
     Con_CheckResize();
     con.initialized = qtrue;
 }
Referenced by Qcommon_Init().
Con_Popup()
void Con_Popup (qboolean force)
Definition at line 152 of file console.c.
 {
     if (force) {
         con.mode = CON_POPUP;
     }
     Key_SetDest(cls.key_dest | KEY_CONSOLE);
     Con_RunConsole();
 }
Referenced by CL_CheckForResend(), CL_Connect_f(), CL_PlayDemo_f(), CL_RestartFilesystem(), and CL_RestartRefresh().
Con_PostInit()
void Con_PostInit (void)
Definition at line 479 of file console.c.
 {
     if (con_history->integer > 0) {
         Prompt_LoadHistory(&con.prompt, COM_HISTORYFILE_NAME);
     }
 }
Referenced by CL_Init().
Con_Print()
void Con_Print (const char * txt)
Definition at line 557 of file console.c.
 {
     char *p;
     int l;
     if (!con.initialized)
         return;
     while (*txt) {
         if (con.newline) {
             if (con.newline == '\n') {
                 Con_Linefeed();
             } else {
                 Con_CarriageRet();
             }
             con.newline = 0;
         }
         // count word length
         for (p = (char *)txt; *p > 32; p++)
             ;
         l = p - txt;
         // word wrap
         if (l < con.linewidth && con.x + l > con.linewidth) {
             Con_Linefeed();
         }
         switch (*txt) {
         case '\r':
         case '\n':
             con.newline = *txt;
             break;
         default:    // display character and advance
             if (con.x == con.linewidth) {
                 Con_Linefeed();
             }
             p = con.text[con.current & CON_TOTALLINES_MASK];
             p[con.x++] = *txt;
             break;
         }
         txt++;
     }
 }
Referenced by Com_LPrintf(), and Con_Printf().
Con_RegisterMedia()
void Con_RegisterMedia (void)
Definition at line 628 of file console.c.
 {
     qerror_t err;
     con.charsetImage = R_RegisterImage(con_font->string, IT_FONT, IF_PERMANENT | IF_SRGB, &err);
     if (!con.charsetImage) {
         if (strcmp(con_font->string, "conchars")) {
             Com_WPrintf("Couldn't load %s: %s\n", con_font->string, Q_ErrorString(err));
             Cvar_Reset(con_font);
             con.charsetImage = R_RegisterImage("conchars", IT_FONT, IF_PERMANENT | IF_SRGB, &err);
         }
         if (!con.charsetImage) {
             Com_Error(ERR_FATAL, "Couldn't load pics/conchars.pcx: %s", Q_ErrorString(err));
         }
     }
     con.backImage = R_RegisterImage(con_background->string, IT_PIC, IF_PERMANENT | IF_SRGB, &err);
     if (!con.backImage) {
         if (strcmp(con_background->string, "conback")) {
             Com_WPrintf("Couldn't load %s: %s\n", con_background->string, Q_ErrorString(err));
             Cvar_Reset(con_background);
             con.backImage = R_RegisterImage("conback", IT_PIC, IF_PERMANENT | IF_SRGB, &err);
         }
         if (!con.backImage) {
             Com_EPrintf("Couldn't load pics/conback.pcx: %s\n", Q_ErrorString(err));
         }
     }
 }
Referenced by CL_InitRefresh(), CL_RestartFilesystem(), CL_RestartRefresh(), and con_param_changed().
Con_RunConsole()
void Con_RunConsole (void)
Definition at line 982 of file console.c.
 {
     if (cls.disable_screen) {
         con.destHeight = con.currentHeight = 0;
         return;
     }
     if (!(cls.key_dest & KEY_MENU)) {
         if (cls.state == ca_disconnected) {
             // draw fullscreen console
             con.destHeight = con.currentHeight = 1;
             return;
         }
         if (cls.state > ca_disconnected && cls.state < ca_active) {
             // draw half-screen console
             con.destHeight = con.currentHeight = 0.5f;
             return;
         }
     }
 // decide on the height of the console
     if (cls.key_dest & KEY_CONSOLE) {
         con.destHeight = Cvar_ClampValue(con_height, 0.1f, 1);
     } else {
         con.destHeight = 0;             // none visible
     }
     if (con_speed->value <= 0) {
         con.currentHeight = con.destHeight;
         return;
     }
     if (con.currentHeight > con.destHeight) {
         con.currentHeight -= con_speed->value * cls.frametime;
         if (con.currentHeight < con.destHeight) {
             con.currentHeight = con.destHeight;
         }
     } else if (con.currentHeight < con.destHeight) {
         con.currentHeight += con_speed->value * cls.frametime;
         if (con.currentHeight > con.destHeight) {
             con.currentHeight = con.destHeight;
         }
     }
 }
Referenced by CL_Frame(), CL_Init(), and Con_Popup().
Con_Shutdown()
void Con_Shutdown (void)
Definition at line 491 of file console.c.
 {
     if (con_history->integer > 0) {
         Prompt_SaveHistory(&con.prompt, COM_HISTORYFILE_NAME, con_history->integer);
     }
     Prompt_Clear(&con.prompt);
 }
Referenced by CL_Shutdown().
Con_SkipNotify()
void Con_SkipNotify (qboolean skip)
Definition at line 99 of file console.c.
 {
     con.skipNotify = skip;
 }
Referenced by CL_ParsePrint().
Con_ToggleConsole_f()
void Con_ToggleConsole_f (void)
Definition at line 194 of file console.c.
 {
     toggle_console(CON_DEFAULT, CHAT_NONE);
 }
Referenced by Key_Event().
FX_Init()
void FX_Init (void)
Definition at line 838 of file effects.c.
 {
     cvar_pt_particle_emissive = Cvar_Get("pt_particle_emissive", "10.0", 0);
     cl_particle_num_factor = Cvar_Get("cl_particle_num_factor", "1", 0);
 }
Referenced by CL_InitRefresh().
IN_Activate()
void IN_Activate (void)
Definition at line 117 of file input.c.
 {
     if (input.api.Grab) {
         input.api.Grab(IN_GetCurrentGrab());
     }
 }
Referenced by check_paused(), CL_Activate(), CL_CheckForPause(), CL_DeltaFrame(), in_changed_soft(), IN_Init(), Key_Event(), Key_SetDest(), and SCR_ModeChanged().
IN_Frame()
void IN_Frame (void)
Definition at line 140 of file input.c.
 {
     if (input.modified) {
         IN_Restart_f();
         return;
     }
     if (input.api.GetEvents) {
         input.api.GetEvents();
     }
 #if USE_LIRC
     Lirc_GetEvents();
 #endif
 }
Referenced by CL_ProcessEvents().
IN_Init()
void IN_Init (void)
Definition at line 210 of file input.c.
 {
     qboolean ret = qfalse;
 #if USE_LIRC
     Lirc_Init();
 #endif
     in_enable = Cvar_Get("in_enable", "1", 0);
     in_enable->changed = in_changed_hard;
     if (!in_enable->integer) {
         Com_Printf("Mouse input disabled.\n");
         return;
     }
 #if USE_DINPUT
     in_direct = Cvar_Get("in_direct", "1", 0);
     if (in_direct->integer) {
         DI_FillAPI(&input.api);
         ret = input.api.Init();
         if (!ret) {
             Cvar_Set("in_direct", "0");
         }
     }
 #endif
     if (!ret) {
         VID_FillInputAPI(&input.api);
         ret = input.api.Init();
         if (!ret) {
             Cvar_Set("in_enable", "0");
             return;
         }
     }
 #if USE_DINPUT
     in_direct->changed = in_changed_hard;
 #endif
     in_grab = Cvar_Get("in_grab", "1", 0);
     in_grab->changed = in_changed_soft;
     IN_Activate();
 }
Referenced by CL_Init(), CL_RestartRefresh(), and IN_Restart_f().
IN_Shutdown()
void IN_Shutdown (void)
Definition at line 173 of file input.c.
 {
 #if USE_DINPUT
     if (in_direct) {
         in_direct->changed = NULL;
     }
 #endif
     if (in_grab) {
         in_grab->changed = NULL;
     }
     if (input.api.Shutdown) {
         input.api.Shutdown();
     }
 #if USE_LIRC
     Lirc_Shutdown();
 #endif
     memset(&input, 0, sizeof(input));
 }
Referenced by CL_RestartRefresh(), CL_Shutdown(), and IN_Restart_f().
Key_Console()
void Key_Console (int key)
Definition at line 1137 of file console.c.
 {
     if (key == 'l' && Key_IsDown(K_CTRL)) {
         Con_Clear_f();
         return;
     }
     if (key == 'd' && Key_IsDown(K_CTRL)) {
         con.mode = CON_DEFAULT;
         return;
     }
     if (key == K_ENTER || key == K_KP_ENTER) {
         Con_Action();
         goto scroll;
     }
     if ((key == 'v' && Key_IsDown(K_CTRL)) ||
         (key == K_INS && Key_IsDown(K_SHIFT)) || key == K_MOUSE3) {
         Con_Paste();
         goto scroll;
     }
     if (key == K_TAB) {
         Prompt_CompleteCommand(&con.prompt, qtrue);
         goto scroll;
     }
     if (key == 'r' && Key_IsDown(K_CTRL)) {
         Prompt_CompleteHistory(&con.prompt, qfalse);
         goto scroll;
     }
     if (key == 's' && Key_IsDown(K_CTRL)) {
         Prompt_CompleteHistory(&con.prompt, qtrue);
         goto scroll;
     }
     if (key == K_UPARROW || (key == 'p' && Key_IsDown(K_CTRL))) {
         Prompt_HistoryUp(&con.prompt);
         goto scroll;
     }
     if (key == K_DOWNARROW || (key == 'n' && Key_IsDown(K_CTRL))) {
         Prompt_HistoryDown(&con.prompt);
         goto scroll;
     }
     if (key == K_PGUP || key == K_MWHEELUP) {
         if (Key_IsDown(K_CTRL)) {
             con.display -= 6;
         } else {
             con.display -= 2;
         }
         Con_CheckTop();
         return;
     }
     if (key == K_PGDN || key == K_MWHEELDOWN) {
         if (Key_IsDown(K_CTRL)) {
             con.display += 6;
         } else {
             con.display += 2;
         }
         if (con.display > con.current) {
             con.display = con.current;
         }
         return;
     }
     if (key == K_HOME && Key_IsDown(K_CTRL)) {
         con.display = 1;
         Con_CheckTop();
         return;
     }
     if (key == K_END && Key_IsDown(K_CTRL)) {
         con.display = con.current;
         return;
     }
     if (IF_KeyEvent(&con.prompt.inputLine, key)) {
         Prompt_ClearState(&con.prompt);
         Con_InteractiveMode();
     }
 scroll:
     if (con_scroll->integer & 1) {
         con.display = con.current;
     }
 }
Referenced by Key_Event().
Key_Message()
void Key_Message (int key)
Definition at line 1241 of file console.c.
 {
     if (key == 'l' && Key_IsDown(K_CTRL)) {
         IF_Clear(&con.chatPrompt.inputLine);
         return;
     }
     if (key == K_ENTER || key == K_KP_ENTER) {
         char *cmd = Prompt_Action(&con.chatPrompt);
         if (cmd) {
             Con_Say(cmd);
         }
         Key_SetDest(cls.key_dest & ~KEY_MESSAGE);
         return;
     }
     if (key == K_ESCAPE) {
         Key_SetDest(cls.key_dest & ~KEY_MESSAGE);
         IF_Clear(&con.chatPrompt.inputLine);
         return;
     }
     if (key == 'r' && Key_IsDown(K_CTRL)) {
         Prompt_CompleteHistory(&con.chatPrompt, qfalse);
         return;
     }
     if (key == 's' && Key_IsDown(K_CTRL)) {
         Prompt_CompleteHistory(&con.chatPrompt, qtrue);
         return;
     }
     if (key == K_UPARROW || (key == 'p' && Key_IsDown(K_CTRL))) {
         Prompt_HistoryUp(&con.chatPrompt);
         return;
     }
     if (key == K_DOWNARROW || (key == 'n' && Key_IsDown(K_CTRL))) {
         Prompt_HistoryDown(&con.chatPrompt);
         return;
     }
     if (IF_KeyEvent(&con.chatPrompt.inputLine, key)) {
         Prompt_ClearState(&con.chatPrompt);
     }
 }
Referenced by Key_Event().
LOC_AddLocationsToScene()
void LOC_AddLocationsToScene (void)
Definition at line 177 of file locs.c.
 {
     location_t *loc, *nearest;
     vec3_t dir;
     float dist;
     entity_t ent;
     if (!loc_draw->integer) {
         return;
     }
     memset(&ent, 0, sizeof(ent));
     ent.model = R_RegisterModel("models/items/c_head/tris.md2");
     ent.skin = R_RegisterSkin("models/items/c_head/skin.pcx");
     nearest = LOC_FindClosest(cl.playerEntityOrigin);
     if (!nearest) {
         return;
     }
     LIST_FOR_EACH(location_t, loc, &cl_locations, entry) {
         VectorSubtract(cl.playerEntityOrigin, loc->origin, dir);
         dist = VectorLength(dir);
         if (dist > loc_dist->integer) {
             continue;
         }
         VectorCopy(loc->origin, ent.origin);
         if (loc == nearest) {
             ent.origin[2] += 10.0f * sin(cl.time * 0.01f);
             V_AddLight(loc->origin, 200, 1, 1, 1);
         }
         V_AddEntity(&ent);
     }
 }
Referenced by CL_AddEntities().
LOC_FreeLocations()
void LOC_FreeLocations (void)
Definition at line 122 of file locs.c.
 {
     location_t *loc, *next;
     LIST_FOR_EACH_SAFE(location_t, loc, next, &cl_locations, entry) {
         Z_Free(loc);
     }
     List_Init(&cl_locations);
 }
Referenced by CL_ClearState().
LOC_Init()
void LOC_Init (void)
Definition at line 376 of file locs.c.
 {
     loc_trace = Cvar_Get("loc_trace", "0", 0);
     loc_draw = Cvar_Get("loc_draw", "0", 0);
     loc_dist = Cvar_Get("loc_dist", "500", 0);
     Cmd_AddMacro("loc_here", LOC_Here_m);
     Cmd_AddMacro("loc_there", LOC_There_m);
     Cmd_AddCommand("loc_add", LOC_Add_f);
     Cmd_AddCommand("loc_delete", LOC_Delete_f);
     Cmd_AddCommand("loc_update", LOC_Update_f);
     Cmd_AddCommand("loc_write", LOC_Write_f);
 }
Referenced by CL_InitLocal().
LOC_LoadLocations()
void LOC_LoadLocations (void)
Definition at line 59 of file locs.c.
 {
     char path[MAX_OSPATH];
     char *buffer, *s, *p;
     int line, count;
     location_t *loc;
     int argc;
     qerror_t ret;
     // load from main directory
     Q_concat(path, sizeof(path), "locs/", cl.mapname, ".loc", NULL);
     ret = FS_LoadFile(path, (void **)&buffer);
     if (!buffer) {
         if (ret != Q_ERR_NOENT) {
             Com_EPrintf("Couldn't load %s: %s\n", path, Q_ErrorString(ret));
         }
         return;
     }
     s = buffer;
     line = count = 0;
     while (*s) {
         p = strchr(s, '\n');
         if (p) {
             *p = 0;
         }
         Cmd_TokenizeString(s, qfalse);
         line++;
         argc = Cmd_Argc();
         if (argc) {
             if (argc < 4) {
                 Com_WPrintf("Line %d is incomplete in %s\n", line, path);
             } else {
                 loc = LOC_Alloc(Cmd_RawArgsFrom(3));
                 loc->origin[0] = atof(Cmd_Argv(0)) * 0.125f;
                 loc->origin[1] = atof(Cmd_Argv(1)) * 0.125f;
                 loc->origin[2] = atof(Cmd_Argv(2)) * 0.125f;
                 List_Append(&cl_locations, &loc->entry);
                 count++;
             }
         }
         if (!p) {
             break;
         }
         s = p + 1;
     }
     Com_DPrintf("Loaded %d location%s from %s\n",
                 count, count == 1 ? "" : "s", path);
     FS_FreeFile(buffer);
 }
Referenced by CL_Begin().
LOC_UpdateCvars()
void LOC_UpdateCvars (void)
SCR_AddToChatHUD()
void SCR_AddToChatHUD (const char * text)
Definition at line 903 of file screen.c.
 {
     chatline_t *line;
     char *p;
     line = &scr_chatlines[scr_chathead++ & CHAT_LINE_MASK];
     Q_strlcpy(line->text, text, sizeof(line->text));
     line->time = cls.realtime;
     p = strrchr(line->text, '\n');
     if (p)
         *p = 0;
 }
Referenced by CL_ParsePrint().
SCR_BeginLoadingPlaque()
void SCR_BeginLoadingPlaque (void)
Definition at line 1424 of file screen.c.
 {
     if (!cls.state) {
         return;
     }
     if (cls.disable_screen) {
         return;
     }
 #ifdef _DEBUG
     if (developer->integer) {
         return;
     }
 #endif
     // if at console or menu, don't bring up the plaque
     if (cls.key_dest & (KEY_CONSOLE | KEY_MENU)) {
         return;
     }
     scr.draw_loading = qtrue;
     SCR_UpdateScreen();
     cls.disable_screen = Sys_Milliseconds();
 }
Referenced by CL_Changing_f(), SCR_RunCinematic(), SV_InitGame(), and SV_SpawnServer().
SCR_CenterPrint()
void SCR_CenterPrint (const char * str)
Definition at line 462 of file screen.c.
 {
     const char  *s;
     scr_centertime_start = cls.realtime;
     if (!strcmp(scr_centerstring, str)) {
         return;
     }
     Q_strlcpy(scr_centerstring, str, sizeof(scr_centerstring));
     // count the number of lines for centering
     scr_center_lines = 1;
     s = str;
     while (*s) {
         if (*s == '\n')
             scr_center_lines++;
         s++;
     }
     // echo it to the console
     Com_Printf("%s\n", scr_centerstring);
     Con_ClearNotify_f();
 }
Referenced by CL_ParseCenterPrint().
SCR_ClearChatHUD_f()
void SCR_ClearChatHUD_f (void)
Definition at line 897 of file screen.c.
 {
     memset(scr_chatlines, 0, sizeof(scr_chatlines));
     scr_chathead = 0;
 }
Referenced by CL_Disconnect().
SCR_DebugGraph()
void SCR_DebugGraph (float value, int color)
Referenced by PF_DebugGraph(), and SCR_UpdateScreen().
SCR_DrawStringEx()
int SCR_DrawStringEx (int x, int y, int flags, size_t maxlen, const char * s, qhandle_t font)
Definition at line 139 of file screen.c.
 {
     size_t len = strlen(s);
     if (len > maxlen) {
         len = maxlen;
     }
     if ((flags & UI_CENTER) == UI_CENTER) {
         x -= len * CHAR_WIDTH / 2;
     } else if (flags & UI_RIGHT) {
         x -= len * CHAR_WIDTH;
     }
     return R_DrawString(x, y, flags, maxlen, s, font);
 }
Referenced by Con_DrawSolidConsole(), draw_shadowed_string(), and SCR_DrawStringMulti().
SCR_DrawStringMulti()
void SCR_DrawStringMulti (int x, int y, int flags, size_t maxlen, const char * s, qhandle_t font)
Definition at line 163 of file screen.c.
 {
     char    *p;
     size_t  len;
     while (*s) {
         p = strchr(s, '\n');
         if (!p) {
             SCR_DrawStringEx(x, y, flags, maxlen, s, font);
             break;
         }
         len = p - s;
         if (len > maxlen) {
             len = maxlen;
         }
         SCR_DrawStringEx(x, y, flags, len, s, font);
         y += CHAR_HEIGHT;
         s = p + 1;
     }
 }
Referenced by SCR_DrawCenterString().
SCR_EndLoadingPlaque()
void SCR_EndLoadingPlaque (void)
Definition at line 1456 of file screen.c.
 {
     if (!cls.state) {
         return;
     }
     cls.disable_screen = 0;
     Con_ClearNotify_f();
 }
Referenced by CL_Disconnect(), Qcommon_Init(), SCR_PlayCinematic(), set_active_state(), and toggle_console().
SCR_FadeAlpha()
float SCR_FadeAlpha (unsigned startTime, unsigned visTime, unsigned fadeTime)
Definition at line 193 of file screen.c.
 {
     float alpha;
     unsigned timeLeft, delta = cls.realtime - startTime;
     if (delta >= visTime) {
         return 0;
     }
     if (fadeTime > visTime) {
         fadeTime = visTime;
     }
     alpha = 1;
     timeLeft = visTime - delta;
     if (timeLeft < fadeTime) {
         alpha = (float)timeLeft / fadeTime;
     }
     return alpha;
 }
Referenced by Con_DrawNotify(), SCR_DrawCenterString(), and SCR_DrawChatHUD().
SCR_FinishCinematic()
void SCR_FinishCinematic (void)
Definition at line 105 of file cin.c.
 {
     SCR_StopCinematic();
     // tell the server to advance to the next map / cinematic
     CL_ClientCommand(va("nextserver %i\n", cl.servercount));
 }
Referenced by Key_Event(), SCR_PlayCinematic(), and SCR_RunCinematic().
SCR_GetFont()
qhandle_t SCR_GetFont (void)
Definition at line 2196 of file screen.c.
 {
     return scr.font_pic;
 }
Referenced by draw_shadowed_string().
SCR_Init()
void SCR_Init (void)
Definition at line 1348 of file screen.c.
 {
     scr_viewsize = Cvar_Get("viewsize", "100", CVAR_ARCHIVE);
     scr_showpause = Cvar_Get("scr_showpause", "1", 0);
     scr_centertime = Cvar_Get("scr_centertime", "2.5", 0);
 #ifdef _DEBUG
     scr_netgraph = Cvar_Get("netgraph", "0", 0);
     scr_timegraph = Cvar_Get("timegraph", "0", 0);
     scr_debuggraph = Cvar_Get("debuggraph", "0", 0);
     scr_graphheight = Cvar_Get("graphheight", "32", 0);
     scr_graphscale = Cvar_Get("graphscale", "1", 0);
     scr_graphshift = Cvar_Get("graphshift", "0", 0);
 #endif
     scr_demobar = Cvar_Get("scr_demobar", "1", 0);
     scr_font = Cvar_Get("scr_font", "conchars", 0);
     scr_font->changed = scr_font_changed;
     scr_scale = Cvar_Get("scr_scale", "2", 0);
     scr_scale->changed = scr_scale_changed;
     scr_crosshair = Cvar_Get("crosshair", "0", CVAR_ARCHIVE);
     scr_crosshair->changed = scr_crosshair_changed;
     scr_chathud = Cvar_Get("scr_chathud", "0", 0);
     scr_chathud_lines = Cvar_Get("scr_chathud_lines", "4", 0);
     scr_chathud_time = Cvar_Get("scr_chathud_time", "0", 0);
     scr_chathud_x = Cvar_Get("scr_chathud_x", "8", 0);
     scr_chathud_y = Cvar_Get("scr_chathud_y", "-64", 0);
     ch_health = Cvar_Get("ch_health", "0", 0);
     ch_health->changed = scr_crosshair_changed;
     ch_red = Cvar_Get("ch_red", "1", 0);
     ch_red->changed = scr_crosshair_changed;
     ch_green = Cvar_Get("ch_green", "1", 0);
     ch_green->changed = scr_crosshair_changed;
     ch_blue = Cvar_Get("ch_blue", "1", 0);
     ch_blue->changed = scr_crosshair_changed;
     ch_alpha = Cvar_Get("ch_alpha", "1", 0);
     ch_alpha->changed = scr_crosshair_changed;
     ch_scale = Cvar_Get("ch_scale", "1", 0);
     ch_scale->changed = scr_crosshair_changed;
     ch_x = Cvar_Get("ch_x", "0", 0);
     ch_y = Cvar_Get("ch_y", "0", 0);
     scr_draw2d = Cvar_Get("scr_draw2d", "2", 0);
     scr_showturtle = Cvar_Get("scr_showturtle", "1", 0);
     scr_showitemname = Cvar_Get("scr_showitemname", "1", CVAR_ARCHIVE);
     scr_lag_x = Cvar_Get("scr_lag_x", "-1", 0);
     scr_lag_y = Cvar_Get("scr_lag_y", "-1", 0);
     scr_lag_draw = Cvar_Get("scr_lag_draw", "0", 0);
     scr_lag_min = Cvar_Get("scr_lag_min", "0", 0);
     scr_lag_max = Cvar_Get("scr_lag_max", "200", 0);
     scr_alpha = Cvar_Get("scr_alpha", "1", 0);
     scr_fps = Cvar_Get("scr_fps", "0", CVAR_ARCHIVE);
 #ifdef _DEBUG
     scr_showstats = Cvar_Get("scr_showstats", "0", 0);
     scr_showpmove = Cvar_Get("scr_showpmove", "0", 0);
 #endif
     Cmd_Register(scr_cmds);
     scr_scale_changed(scr_scale);
     scr.initialized = qtrue;
 }
Referenced by CL_InitRefresh().
SCR_LagClear()
void SCR_LagClear (void)
Definition at line 532 of file screen.c.
 {
     lag.head = 0;
 }
Referenced by set_active_state().
SCR_LagSample()
void SCR_LagSample (void)
Definition at line 537 of file screen.c.
 {
     int i = cls.netchan->incoming_acknowledged & CMD_MASK;
     client_history_t *h = &cl.history[i];
     unsigned ping;
     h->rcvd = cls.realtime;
     if (!h->cmdNumber || h->rcvd < h->sent) {
         return;
     }
     ping = h->rcvd - h->sent;
     for (i = 0; i < cls.netchan->dropped; i++) {
         lag.samples[lag.head % LAG_WIDTH] = ping | LAG_CRIT_BIT;
         lag.head++;
     }
     if (cl.frameflags & FF_SUPPRESSED) {
         ping |= LAG_WARN_BIT;
     }
     lag.samples[lag.head % LAG_WIDTH] = ping;
     lag.head++;
 }
Referenced by CL_PacketEvent().
SCR_ModeChanged()
void SCR_ModeChanged (void)
Definition at line 1278 of file screen.c.
 {
     IN_Activate();
     Con_CheckResize();
     UI_ModeChanged();
     // video sync flag may have changed
     CL_UpdateFrameTimes();
     cls.disable_screen = 0;
     if (scr.initialized)
         scr.hud_scale = R_ClampScale(scr_scale);
     scr.hud_alpha = 1.f;
 }
Referenced by Win_ModeChanged().
SCR_PlayCinematic()
void SCR_PlayCinematic (const char * name)
Definition at line 477 of file cin.c.
 {
     int     width, height;
     int     old_khz;
     // make sure CD isn't playing music
     OGG_Stop();
     cin.s_khz_original = 0;
     cin.frame_index = 0;
     cin.start_time = 0;
     if (!COM_CompareExtension(name, ".pcx"))
     {
         cl.image_precache[0] = R_RegisterPic2(name);
         if (!cl.image_precache[0]) {
             SCR_FinishCinematic();
             return;
         }
     }
     else if (!COM_CompareExtension(name, ".cin"))
     {
         if (!Cvar_VariableValue("cl_cinematics"))
         {
             SCR_FinishCinematic();
             return;
         }
         Q_snprintf(cin.file_name, sizeof(cin.file_name), "video/%s", name);
         FS_FOpenFile(cin.file_name, &cin.file, FS_MODE_READ);
         if (!cin.file)
         {
             Com_WPrintf("Cinematic \"%s\" not found. Skipping.\n", name);
             SCR_FinishCinematic();
             return;
         }
         FS_Read(&width, 4, cin.file);
         FS_Read(&height, 4, cin.file);
         cin.width = LittleLong(width);
         cin.height = LittleLong(height);
         FS_Read(&cin.s_rate, 4, cin.file);
         cin.s_rate = LittleLong(cin.s_rate);
         FS_Read(&cin.s_width, 4, cin.file);
         cin.s_width = LittleLong(cin.s_width);
         FS_Read(&cin.s_channels, 4, cin.file);
         cin.s_channels = LittleLong(cin.s_channels);
         Huff1TableInit();
         cin.palette_active = qfalse;
         // switch to 22 khz sound if necessary
         old_khz = Cvar_VariableValue("s_khz");
         if (old_khz != cin.s_rate / 1000 && s_started == SS_DMA)
         {
             cin.s_khz_original = old_khz;
             Cvar_Set("s_khz", va("%d", cin.s_rate / 1000));
         }
         cin.frame_index = 0;
         cl.image_precache[0] = SCR_ReadNextFrame();
         cin.start_time = cls.realtime;
     }
     else
     {
         SCR_FinishCinematic();
         return;
     }
     cls.state = ca_cinematic;
     SCR_EndLoadingPlaque();     // get rid of loading plaque
     Con_Close(qfalse);          // get rid of connection screen
 }
Referenced by CL_ParseServerData().
SCR_RegisterMedia()
void SCR_RegisterMedia (void)
Definition at line 1297 of file screen.c.
 {
     int     i, j;
     for (i = 0; i < 2; i++)
         for (j = 0; j < STAT_PICS; j++)
             scr.sb_pics[i][j] = R_RegisterPic(sb_nums[i][j]);
     scr.inven_pic = R_RegisterPic("inventory");
     scr.field_pic = R_RegisterPic("field_3");
     scr.backtile_pic = R_RegisterImage("backtile", IT_PIC, IF_PERMANENT | IF_REPEAT, NULL);
     scr.pause_pic = R_RegisterPic("pause");
     R_GetPicSize(&scr.pause_width, &scr.pause_height, scr.pause_pic);
     scr.loading_pic = R_RegisterPic("loading");
     R_GetPicSize(&scr.loading_width, &scr.loading_height, scr.loading_pic);
     scr.net_pic = R_RegisterPic("net");
     scr.font_pic = R_RegisterFont(scr_font->string);
     scr_crosshair_changed(scr_crosshair);
 }
Referenced by CL_InitRefresh(), CL_RestartFilesystem(), and CL_RestartRefresh().
SCR_RunCinematic()
void SCR_RunCinematic ()
Definition at line 429 of file cin.c.
 {
     int     frame;
     if (cin.start_time <= 0)
         return;
     if (cin.frame_index == -1)
         return; // static image
     if (cls.key_dest != KEY_GAME)
     {
         // pause if menu or console is up
         cin.start_time = cls.realtime - cin.frame_index * 1000 / 14;
         S_UnqueueRawSamples();
         return;
     }
     frame = (cls.realtime - cin.start_time)*14.0 / 1000;
     if (frame <= cin.frame_index)
         return;
     if (frame > cin.frame_index + 1)
     {
         // Com_Printf("Dropped frame: %i > %i\n", frame, cin.frame_index + 1);
         cin.start_time = cls.realtime - cin.frame_index * 1000 / 14;
     }
     R_UnregisterImage(cl.image_precache[0]);
     cl.image_precache[0] = SCR_ReadNextFrame();
     if (!cl.image_precache[0])
     {
         SCR_FinishCinematic();
         cin.start_time = 1; // hack to get the black screen behind loading
         SCR_BeginLoadingPlaque();
         cin.start_time = 0;
         return;
     }
 }
Referenced by CL_Frame().
SCR_SetCrosshairColor()
void SCR_SetCrosshairColor (void)
Definition at line 1242 of file screen.c.
 {
     int health;
     if (!ch_health->integer) {
         return;
     }
     health = cl.frame.ps.stats[STAT_HEALTH];
     if (health <= 0) {
         VectorSet(scr.crosshair_color.u8, 0, 0, 0);
         return;
     }
     // red
     scr.crosshair_color.u8[0] = 255;
     // green
     if (health >= 66) {
         scr.crosshair_color.u8[1] = 255;
     } else if (health < 33) {
         scr.crosshair_color.u8[1] = 0;
     } else {
         scr.crosshair_color.u8[1] = (255 * (health - 33)) / 33;
     }
     // blue
     if (health >= 99) {
         scr.crosshair_color.u8[2] = 255;
     } else if (health < 66) {
         scr.crosshair_color.u8[2] = 0;
     } else {
         scr.crosshair_color.u8[2] = (255 * (health - 66)) / 33;
     }
 }
Referenced by CL_DeltaFrame(), and scr_crosshair_changed().
SCR_SetHudAlpha()
void SCR_SetHudAlpha (float alpha)
Definition at line 2201 of file screen.c.
 {
     scr.hud_alpha = alpha;
 }
Referenced by evaluate_reference_mode(), and R_BeginFrame_RTX().
SCR_Shutdown()
void SCR_Shutdown (void)
Definition at line 1413 of file screen.c.
 {
     Cmd_Deregister(scr_cmds);
     scr.initialized = qfalse;
 }
Referenced by CL_ShutdownRefresh().
SCR_SizeDown()
void SCR_SizeDown (void)
SCR_SizeUp()
void SCR_SizeUp (void)
SCR_TouchPics()
void SCR_TouchPics (void)
SCR_UpdateScreen()
void SCR_UpdateScreen (void)
Definition at line 2142 of file screen.c.
 {
     static int recursive;
     if (!scr.initialized) {
         return;             // not initialized yet
     }
     // if the screen is disabled (loading plaque is up), do nothing at all
     if (cls.disable_screen) {
         unsigned delta = Sys_Milliseconds() - cls.disable_screen;
         if (delta < 120 * 1000) {
             return;
         }
         cls.disable_screen = 0;
         Com_Printf("Loading plaque timed out.\n");
     }
     if (recursive > 1) {
         Com_Error(ERR_FATAL, "%s: recursively called", __func__);
     }
     recursive++;
     R_BeginFrame();
     // do 3D refresh drawing
     SCR_DrawActive();
     // draw main menu
     UI_Draw(cls.realtime);
     // draw console
     Con_DrawConsole();
     // draw loading plaque
     SCR_DrawLoading();
 #ifdef _DEBUG
     // draw debug graphs
     if (scr_timegraph->integer)
         SCR_DebugGraph(cls.frametime * 300, 0);
     if (scr_debuggraph->integer || scr_timegraph->integer || scr_netgraph->integer)
         SCR_DrawDebugGraph();
 #endif
     R_EndFrame();
     recursive--;
 }
Referenced by BuildList(), CL_Changing_f(), CL_ConnectionlessPacket(), CL_Frame(), CL_LoadState(), CL_PlayDemo_f(), CL_PrepRefresh(), CL_Reconnect_f(), CL_Skins_f(), Con_Action(), PingServers(), and SCR_BeginLoadingPlaque().
V_AddEntity()
void V_AddEntity (entity_t * ent)
Definition at line 91 of file view.c.
 {
     if (r_numentities >= MAX_ENTITIES)
         return;
     r_entities[r_numentities++] = *ent;
 }
Referenced by CL_AddBeams(), CL_AddExplosions(), CL_AddLasers(), CL_AddPacketEntities(), CL_AddPlayerBeams(), CL_AddViewWeapon(), and LOC_AddLocationsToScene().
V_AddParticle()
void V_AddParticle (particle_t * p)
Definition at line 106 of file view.c.
 {
     if (r_numparticles >= MAX_PARTICLES)
         return;
     r_particles[r_numparticles++] = *p;
 }
V_Init()
void V_Init (void)
Definition at line 533 of file view.c.
 {
     Cmd_Register(v_cmds);
 #ifdef _DEBUG
     cl_testblend = Cvar_Get("cl_testblend", "0", 0);
     cl_testparticles = Cvar_Get("cl_testparticles", "0", 0);
     cl_testentities = Cvar_Get("cl_testentities", "0", 0);
 #if USE_DLIGHTS
     cl_testlights = Cvar_Get("cl_testlights", "0", CVAR_CHEAT);
 #endif
     cl_stats = Cvar_Get("cl_stats", "0", 0);
 #endif
 #if USE_DLIGHTS
     cl_add_lights = Cvar_Get("cl_lights", "1", 0);
     cl_show_lights = Cvar_Get("cl_show_lights", "0", 0);
 #endif
     cl_add_particles = Cvar_Get("cl_particles", "1", 0);
     cl_add_entities = Cvar_Get("cl_entities", "1", 0);
     cl_add_blend = Cvar_Get("cl_blend", "1", 0);
     cl_add_blend->changed = cl_add_blend_changed;
     cl_adjustfov = Cvar_Get("cl_adjustfov", "1", 0);
 }
Referenced by CL_InitRefresh().
V_RenderView()
void V_RenderView (void)
Definition at line 402 of file view.c.
 {
     // an invalid frame will just use the exact previous refdef
     // we can't use the old frame if the video mode has changed, though...
     if (cl.frame.valid) {
         V_ClearScene();
         // build a refresh entity list and calc cl.sim*
         // this also calls CL_CalcViewValues which loads
         // v_forward, etc.
         CL_AddEntities();
 #ifdef _DEBUG
         if (cl_testparticles->integer)
             V_TestParticles();
         if (cl_testentities->integer)
             V_TestEntities();
 #if USE_DLIGHTS
         if (cl_testlights->integer)
             V_TestLights();
 #endif
         if (cl_testblend->integer) {
             cl.refdef.blend[0] = 1;
             cl.refdef.blend[1] = 0.5;
             cl.refdef.blend[2] = 0.25;
             cl.refdef.blend[3] = 0.5;
         }
 #endif
         // never let it sit exactly on a node line, because a water plane can
         // dissapear when viewed with the eye exactly on it.
         // the server protocol only specifies to 1/8 pixel, so add 1/16 in each axis
         cl.refdef.vieworg[0] += 1.0 / 16;
         cl.refdef.vieworg[1] += 1.0 / 16;
         cl.refdef.vieworg[2] += 1.0 / 16;
         cl.refdef.x = scr_vrect.x;
         cl.refdef.y = scr_vrect.y;
         cl.refdef.width = scr_vrect.width;
         cl.refdef.height = scr_vrect.height;
         // adjust for non-4/3 screens
         if (cl_adjustfov->integer) {
             cl.refdef.fov_y = cl.fov_y;
             cl.refdef.fov_x = V_CalcFov(cl.refdef.fov_y, cl.refdef.height, cl.refdef.width);
         } else {
             cl.refdef.fov_x = cl.fov_x;
             cl.refdef.fov_y = V_CalcFov(cl.refdef.fov_x, cl.refdef.width, cl.refdef.height);
         }
         cl.refdef.time = cl.time * 0.001;
         if (cl.frame.areabytes) {
             cl.refdef.areabits = cl.frame.areabits;
         } else {
             cl.refdef.areabits = NULL;
         }
         if (!cl_add_entities->integer)
             r_numentities = 0;
         if (!cl_add_particles->integer)
             r_numparticles = 0;
 #if USE_DLIGHTS
         if (!cl_add_lights->integer)
             r_numdlights = 0;
 #endif
         if (!cl_add_blend->integer)
             Vector4Clear(cl.refdef.blend);
         cl.refdef.num_entities = r_numentities;
         cl.refdef.entities = r_entities;
         cl.refdef.num_particles = r_numparticles;
         cl.refdef.particles = r_particles;
 #if USE_DLIGHTS
         cl.refdef.num_dlights = r_numdlights;
         cl.refdef.dlights = r_dlights;
 #endif
 #if USE_LIGHTSTYLES
         cl.refdef.lightstyles = r_lightstyles;
 #endif
         cl.refdef.rdflags = cl.frame.ps.rdflags;
         // sort entities for better cache locality
         qsort(cl.refdef.entities, cl.refdef.num_entities, sizeof(cl.refdef.entities[0]), entitycmpfnc);
     }
     R_RenderFrame(&cl.refdef);
 #ifdef _DEBUG
     if (cl_stats->integer)
 #if USE_DLIGHTS
         Com_Printf("ent:%i  lt:%i  part:%i\n", r_numentities, r_numdlights, r_numparticles);
 #else
         Com_Printf("ent:%i  part:%i\n", r_numentities, r_numparticles);
 #endif
 #endif
     V_SetLightLevel();
 }
Referenced by SCR_DrawActive().
V_Shutdown()
void V_Shutdown (void)
Definition at line 560 of file view.c.
 {
     Cmd_Deregister(v_cmds);
 }
Referenced by CL_ShutdownRefresh().
Variable Documentation
cl
client_state_t cl
Definition at line 99 of file main.c.
Referenced by AC_CheckTimeouts(), AC_ClientAnnounce(), AC_ClientBegin(), AC_ClientConnect(), AC_ClientDisconnect(), AC_ClientQuery(), AC_ClientToken(), AC_Drop(), AC_Info_f(), AC_Invalidate_f(), AC_List_f(), AC_ParseClient(), AC_ParseClientAck(), AC_ParseDisconnect(), AC_ParseFileViolation(), AC_ParseQueryReply(), AC_ParseViolation(), AC_Update_f(), active_sun_preset(), AL_AddLoopSounds(), AL_Update(), build_gamestate(), check_player(), CheckDMRules(), CL_AddBeams(), CL_AddExplosions(), CL_AddLasers(), CL_AddPacketEntities(), CL_AddParticles(), CL_AddPlayerBeams(), CL_AddViewWeapon(), CL_AdjustAngles(), CL_AllocExplosion(), CL_AllocLaser(), CL_Ammo_m(), CL_Armor_m(), CL_Begin(), CL_BFGExplosionParticles(), CL_BfgParticles(), CL_BigTeleportParticles(), CL_BlasterParticles(), CL_BlasterParticles2(), CL_BlasterTrail(), CL_BlasterTrail2(), CL_BloodParticleEffect(), CL_BubbleTrail(), CL_BubbleTrail2(), CL_CalcViewValues(), CL_Changing_f(), CL_CheatsOK(), CL_CheckPredictionError(), CL_CheckTimeout(), CL_ClampPitch(), CL_ClampSpeed(), CL_ClearState(), CL_ClipMoveToEntities(), CL_Cluster_m(), CL_ClusterThere_m(), CL_ColorExplosionParticles(), CL_ConnectionlessPacket(), CL_DebugTrail(), CL_DeltaFrame(), CL_DemoFrame(), CL_DiminishingTrail(), CL_DumpClients_f(), CL_DumpLayout_f(), CL_DumpStatusbar_f(), CL_EmitDemoFrame(), CL_EmitDemoSnapshot(), CL_ExplosionParticles(), CL_FinalizeCmd(), CL_FinishViewValues(), CL_FirstDemoFrame(), CL_FlagTrail(), CL_FlyEffect(), CL_FlyParticles(), CL_ForceWall(), CL_Frame(), CL_GenericParticleEffect(), CL_GetEntitySoundOrigin(), CL_GetResolutionScale(), CL_GTV_EmitFrame(), CL_GTV_WriteMessage(), CL_HdrColor_m(), CL_Health_m(), CL_Heatbeam(), CL_IonripperTrail(), CL_ItemRespawnParticles(), CL_KeyState(), CL_LoadClientinfo(), CL_LogoutEffect(), CL_Mapname_m(), CL_Material_m(), CL_Material_Override_m(), CL_MeasureStats(), CL_MonsterPlasma_Shell(), CL_MouseMove(), CL_MuzzleFlash(), CL_MuzzleFlash2(), CL_Name_g(), cl_noskins_changed(), CL_Nukeblast(), CL_NumLightPolys_m(), CL_OldRailTrail(), CL_ParseBaseline(), CL_ParseBeam(), CL_ParseCenterPrint(), CL_ParseConfigstring(), CL_ParseDeltaEntity(), CL_ParseFrame(), CL_ParseInventory(), CL_ParseLayout(), CL_ParseNuke(), CL_ParsePacketEntities(), CL_ParsePlayerBeam(), CL_ParsePrint(), CL_ParseServerData(), CL_ParseStartSoundPacket(), CL_ParseSteam(), CL_ParseTEnt(), CL_ParseWidow(), CL_ParticleEffect(), CL_ParticleEffect2(), CL_ParticleEffect3(), CL_ParticleEffectWaterSplash(), CL_ParticleSmokeEffect(), CL_ParticleSteamEffect(), CL_ParticleSteamEffect2(), CL_PlainExplosion(), CL_PointContents(), CL_PredictAngles(), CL_PredictMovement(), CL_PrepRefresh(), CL_ProcessEvents(), CL_ProcessSustain(), CL_QuadTrail(), CL_RailLights(), CL_RailSpiral(), CL_Record_f(), CL_RegisterBspModels(), CL_RegisterSounds(), CL_RegisterVWepModels(), CL_RequestNextDownload(), CL_ResolutionScale_m(), CL_RestartFilesystem(), CL_RestartRefresh(), CL_RocketTrail(), CL_Seek_f(), CL_SendBatchedCmd(), CL_SendCmd(), CL_SendDefaultCmd(), CL_SendKeepAlive(), CL_SetClientTime(), CL_SetSky(), CL_SetupFirstPersonView(), CL_SetupThirdPersionView(), CL_Skins_f(), CL_SmokeAndFlash(), CL_SmokeTrail(), CL_Suspend_f(), CL_TagTrail(), CL_TeleporterParticles(), CL_TeleportParticles(), CL_Timer_m(), CL_Trace(), CL_Tracker_Explode(), CL_Tracker_Shell(), CL_TrackerTrail(), CL_TrapParticles(), CL_UpdateCmd(), CL_UpdateConfigstring(), CL_Ups_m(), CL_ViewDir_m(), CL_ViewPos_m(), CL_WeaponModel_m(), CL_Widowbeamout(), CL_WidowSplash(), Cmd_Inven_f(), Cmd_Say_f(), Cmd_WeapLast_f(), Cmd_WeapNext_f(), Cmd_WeapPrev_f(), Con_DrawSolidConsole(), DeathmatchScoreboardMessage(), DMA_DriftBeginofs(), dump_lag(), dump_protocols(), dump_settings(), emit_gamestate(), emit_packet_entities(), entity_event(), entity_new(), entity_optimized(), entity_update(), entity_update_new(), entity_update_old(), find_client_slot(), G_CheckChaseStats(), G_SetSpectatorStats(), IN_AttackDown(), IN_CenterView(), IN_GetCurrentGrab(), IN_UseDown(), Key_Event(), LOC_Add_f(), LOC_AddLocationsToScene(), LOC_Delete_f(), LOC_FindClosest(), LOC_Here_m(), LOC_LoadLocations(), LOC_There_m(), LOC_Update_f(), LOC_Write_f(), MVD_BroadcastPrintf(), MVD_GameClientDisconnect(), MVD_GameClientDrop(), MVD_GameClientNameChanged(), MVD_LayoutClients(), MVD_ParseMulticast(), MVD_ParseSound(), MVD_RemoveClient(), MVD_Say_f(), MVD_SetServerState(), MVD_SwitchChannel(), MVD_UnicastPrint(), MVD_UnicastSend(), permit_connection(), ping_avg(), ping_min(), prepare_entities(), print_channel(), Qcommon_Frame(), ready_to_send(), ready_to_send_hacked(), resume_record(), S_BuildSoundList(), S_ParseStartSound(), S_RegisterSexedSound(), S_RegisterSexedSounds(), S_Update(), SCR_DrawActive(), SCR_DrawInventory(), SCR_DrawLayout(), SCR_DrawSelectedItemName(), SCR_DrawStats(), SCR_DrawTurtle(), SCR_ExecuteLayoutString(), SCR_FinishCinematic(), SCR_LagSample(), SCR_PlayCinematic(), SCR_RunCinematic(), SCR_ScoreDump_f(), SCR_ScoreShot_f(), SCR_SetCrosshairColor(), SCR_StopCinematic(), SCR_TimeRefresh_f(), SelectNextItem(), SelectPrevItem(), set_active_state(), shell_effect_hack(), SV_CalcPings(), SV_CountClients(), SV_GiveMsec(), SV_Lag_f(), SV_Player_g(), SV_SetPlayer(), SV_StatusString(), SV_UserinfoChanged(), TH_DrawLayoutString(), V_RenderView(), V_SetLightLevel(), V_Viewpos_f(), ValidateSelectedItem(), and vkpt_freecam_mousemove().
cl_async
cvar_t* cl_async
Definition at line 32 of file main.c.
Referenced by CL_InitLocal(), and CL_UpdateFrameTimes().
cl_beginmapcmd
cvar_t* cl_beginmapcmd
Definition at line 61 of file main.c.
Referenced by CL_InitLocal(), and set_active_state().
cl_changemapcmd
cvar_t* cl_changemapcmd
Definition at line 60 of file main.c.
Referenced by CL_Changing_f(), and CL_InitLocal().
cl_chat_filter
cvar_t* cl_chat_filter
Definition at line 55 of file main.c.
Referenced by CL_InitLocal(), and CL_ParsePrint().
cl_chat_notify
cvar_t* cl_chat_notify
Definition at line 53 of file main.c.
Referenced by CL_InitLocal(), and CL_ParsePrint().
cl_chat_sound
cvar_t* cl_chat_sound
Definition at line 54 of file main.c.
Referenced by CL_InitLocal(), and CL_ParsePrint().
cl_cmdbuf
cmdbuf_t cl_cmdbuf
Definition at line 104 of file main.c.
Referenced by CL_FinalizeCmd(), CL_Init(), CL_ParseServerData(), CL_ParseStuffText(), CL_PlayDemo_f(), and CL_ProcessEvents().
cl_cmdbuf_text
char cl_cmdbuf_text[MAX_STRING_CHARS]
Definition at line 105 of file main.c.
Referenced by CL_Init().
cl_disable_explosions
cvar_t* cl_disable_explosions
Definition at line 52 of file main.c.
Referenced by CL_InitLocal(), and CL_ParseTEnt().
cl_disable_particles
cvar_t* cl_disable_particles
Definition at line 51 of file main.c.
Referenced by CL_AddPacketEntities(), CL_InitLocal(), and CL_ParseTEnt().
cl_disconnectcmd
cvar_t* cl_disconnectcmd
Definition at line 59 of file main.c.
Referenced by CL_Disconnect(), and CL_InitLocal().
cl_entities
centity_t cl_entities[MAX_EDICTS]
Definition at line 101 of file main.c.
Referenced by build_gamestate(), CL_AddPacketEntities(), CL_ClearState(), CL_DeltaFrame(), CL_FinishViewValues(), CL_GetEntitySoundOrigin(), CL_GTV_EmitFrame(), CL_MuzzleFlash(), CL_MuzzleFlash2(), entity_event(), entity_update(), player_update(), and shell_effect_hack().
cl_explosion_frametime
cvar_t* cl_explosion_frametime
Definition at line 57 of file main.c.
Referenced by CL_InitLocal(), and CL_PlainExplosion().
cl_explosion_sprites
cvar_t* cl_explosion_sprites
Definition at line 56 of file main.c.
Referenced by CL_InitLocal(), CL_ParseTEnt(), and CL_PlainExplosion().
cl_explosions
explosion_t cl_explosions[MAX_EXPLOSIONS]
Definition at line 136 of file tent.c.
Referenced by CL_AddExplosions(), CL_AllocExplosion(), and CL_ClearExplosions().
cl_footsteps
cvar_t* cl_footsteps
Definition at line 26 of file main.c.
Referenced by CL_InitLocal(), CL_UpdateFootstepsSetting(), and entity_event().
cl_gibs
cvar_t* cl_gibs
Definition at line 63 of file main.c.
Referenced by CL_AddPacketEntities(), CL_InitLocal(), and CL_UpdateGibSetting().
cl_gun
cvar_t* cl_gun
Definition at line 29 of file main.c.
cl_gunalpha
cvar_t* cl_gunalpha
Definition at line 30 of file main.c.
Referenced by CL_AddViewWeapon(), and CL_InitLocal().
cl_kickangles
cvar_t* cl_kickangles
Definition at line 36 of file main.c.
Referenced by CL_InitLocal(), and CL_SetupFirstPersonView().
cl_noglow
cvar_t* cl_noglow
Definition at line 38 of file main.c.
Referenced by CL_AddPacketEntities(), and CL_InitLocal().
cl_nolerp
cvar_t* cl_nolerp
Definition at line 39 of file main.c.
Referenced by CL_InitLocal(), entity_new(), entity_update_old(), and player_update().
cl_noskins
cvar_t* cl_noskins
Definition at line 25 of file main.c.
Referenced by CL_InitLocal(), and CL_ParsePlayerSkin().
cl_player_model
cvar_t* cl_player_model
Definition at line 47 of file main.c.
Referenced by CL_AddViewWeapon(), CL_FinishViewValues(), CL_InitLocal(), CL_UpdateGunSetting(), prepare_entities(), prepare_ubo(), vkpt_freecam_reset(), vkpt_freecam_update(), and vkpt_pt_create_toplevel().
cl_predict
cvar_t* cl_predict
Definition at line 28 of file main.c.
Referenced by CL_CalcViewValues(), CL_CheckPredictionError(), CL_InitLocal(), CL_PredictMovement(), CL_UpdatePredictSetting(), and CL_Ups_m().
cl_rollhack
cvar_t* cl_rollhack
Definition at line 37 of file main.c.
Referenced by CL_AddPacketEntities(), and CL_InitLocal().
cl_thirdperson_angle
cvar_t* cl_thirdperson_angle
Definition at line 48 of file main.c.
Referenced by CL_InitLocal(), and CL_SetupThirdPersionView().
cl_thirdperson_range
cvar_t* cl_thirdperson_range
Definition at line 49 of file main.c.
Referenced by CL_InitLocal(), and CL_SetupThirdPersionView().
cl_vwep
cvar_t* cl_vwep
Definition at line 72 of file main.c.
Referenced by CL_InitLocal(), and CL_RegisterVWepModels().
cls
client_static_t cls
Definition at line 98 of file main.c.
Referenced by abort_downloads(), AL_AddLoopSounds(), build_gamestate(), CL_Activate(), CL_AddRequest(), CL_Begin(), CL_CalcViewValues(), CL_Changing_f(), CL_CheatsOK(), CL_CheckForIP(), CL_CheckForPause(), CL_CheckForResend(), CL_CheckPredictionError(), CL_CheckTimeout(), CL_CleanupDemos(), CL_CleanupDownloads(), CL_ClearState(), CL_ClientCommand(), CL_Connect_f(), CL_ConnectionlessPacket(), CL_DeltaFrame(), CL_DemoFrame(), CL_DemoPos_m(), CL_Disconnect(), CL_Disconnect_f(), CL_Download_f(), CL_DumpClients_f(), CL_EmitDemoFrame(), CL_EmitDemoSnapshot(), CL_FinalizeCmd(), CL_FindRequest(), CL_FinishDownload(), CL_FirstDemoFrame(), CL_FollowIP_f(), CL_ForwardToServer(), CL_ForwardToServer_f(), CL_Frame(), CL_GTV_EmitFrame(), CL_GTV_Resume(), CL_GTV_Run(), CL_GTV_Shutdown(), CL_GTV_Start_f(), CL_GTV_Status_f(), CL_GTV_Stop_f(), CL_GTV_Suspend(), CL_GTV_Transmit(), CL_GTV_WriteMessage(), CL_HandleDownload(), CL_IgnoreDownload(), CL_Init(), CL_InitDemos(), CL_InitDownloads(), CL_InitLocal(), CL_InitRefresh(), CL_Lag_m(), CL_LoadDownloadIgnores(), CL_MeasureStats(), CL_MouseMove(), CL_Name_g(), cl_noskins_changed(), CL_PacketEvent(), CL_ParseCenterPrint(), CL_ParseConfigstring(), CL_ParseDownload(), CL_ParseFrame(), CL_ParsePrint(), CL_ParsePrintMessage(), CL_ParseReconnect(), CL_ParseServerData(), CL_ParseServerMessage(), CL_ParseZPacket(), CL_PassiveConnect_f(), CL_Ping_m(), CL_PlayDemo_f(), CL_Precache_f(), CL_PredictMovement(), CL_PrepRefresh(), CL_QueueDownload(), CL_Rcon_f(), CL_RecentIP_g(), CL_Reconnect_f(), CL_Record_f(), CL_RegisterBspModels(), CL_RequestNextDownload(), CL_RestartFilesystem(), CL_RestartRefresh(), CL_RunRefresh(), CL_Seek_f(), CL_SendBatchedCmd(), CL_SendCmd(), CL_SendDefaultCmd(), CL_SendKeepAlive(), CL_SendUserinfo(), CL_Server_m(), CL_ServerStatus_f(), CL_Shutdown(), CL_ShutdownRefresh(), CL_Skins_f(), CL_StartNextDownload(), CL_Stop_f(), CL_Suspend_f(), CL_UpdateBlendSetting(), CL_UpdateConfigstring(), CL_UpdateFootstepsSetting(), CL_UpdateFrameTimes(), CL_UpdateGibSetting(), CL_UpdateGunSetting(), CL_UpdatePredictSetting(), CL_UpdateRecordingSetting(), CL_UpdateUserinfo(), CL_Ups_m(), cl_vwep_changed(), CL_WriteDemoMessage(), Con_Action(), Con_CarriageRet(), Con_Close(), Con_DrawNotify(), Con_DrawSolidConsole(), con_param_changed(), Con_Popup(), Con_RemoteMode_f(), Con_RunConsole(), con_scale_changed(), downloads_pending(), drop_client(), dump_program(), emit_gamestate(), entity_optimized(), exec_server_string(), find_snapshot(), finish_download(), finish_udp_download(), format_demo_size(), format_demo_status(), HTTP_QueueDownload(), HTTP_SetServer(), IN_AttackDown(), IN_GetCurrentGrab(), IN_UseDown(), inflate_udp_download(), Key_Event(), Key_GetDest(), Key_Message(), Key_SetDest(), lerp_client_fov(), LOC_Add_f(), LOC_Delete_f(), LOC_Here_m(), LOC_There_m(), LOC_Update_f(), LOC_Write_f(), parse_hello(), parse_message(), parse_next_message(), parse_ping(), parse_stream_start(), parse_stream_stop(), progress_func(), R_RenderFrame_RTX(), ready_to_send(), resume_record(), S_Activate(), S_Update(), SCR_AddToChatHUD(), SCR_BeginLoadingPlaque(), SCR_CenterPrint(), SCR_Draw2D(), SCR_DrawActive(), SCR_DrawDemo(), SCR_DrawInventory(), SCR_DrawLayout(), SCR_DrawNet(), SCR_EndLoadingPlaque(), SCR_FadeAlpha(), SCR_LagSample(), SCR_ModeChanged(), SCR_PlayCinematic(), SCR_RunCinematic(), SCR_ScoreDump_f(), SCR_ScoreShot_f(), SCR_Sky_f(), SCR_TimeRefresh_f(), SCR_UpdateScreen(), set_active_state(), start_message_mode(), start_next_download(), start_udp_download(), toggle_console(), UI_PopMenu(), update_status(), write_stream(), and write_udp_download().
gun_frame
int gun_frame
Definition at line 27 of file view.c.
Referenced by CL_AddViewWeapon(), V_Gun_Next_f(), and V_Gun_Prev_f().
gun_model
qhandle_t gun_model
Definition at line 28 of file view.c.
Referenced by CL_AddViewWeapon(), and V_Gun_Model_f().
info_fov
cvar_t* info_fov
Definition at line 84 of file main.c.
Referenced by CL_InitLocal(), and lerp_client_fov().
info_gender
cvar_t* info_gender
Definition at line 87 of file main.c.
Referenced by CL_FixUpGender(), and CL_InitLocal().
info_hand
cvar_t* info_hand
Definition at line 86 of file main.c.
Referenced by CL_AddPlayerBeams(), CL_AddViewWeapon(), CL_InitLocal(), and CL_UpdateGunSetting().
info_msg
cvar_t* info_msg
Definition at line 85 of file main.c.
Referenced by CL_InitLocal().
info_name
cvar_t* info_name
Definition at line 81 of file main.c.
Referenced by CL_InitLocal().
info_password
cvar_t* info_password
Definition at line 79 of file main.c.
Referenced by CL_InitLocal().
info_rate
cvar_t* info_rate
Definition at line 83 of file main.c.
Referenced by CalcPingRate(), and CL_InitLocal().
info_skin
cvar_t* info_skin
Definition at line 82 of file main.c.
Referenced by CL_FixUpGender(), CL_InitLocal(), and CL_UpdateUserinfo().
info_spectator
cvar_t* info_spectator
Definition at line 80 of file main.c.
Referenced by CL_InitLocal().
info_uf
cvar_t* info_uf
Definition at line 88 of file main.c.
Referenced by CL_InitLocal(), and lerp_client_fov().
mz
mz_params_t mz
Definition at line 656 of file parse.c.
Referenced by CL_MuzzleFlash(), CL_MuzzleFlash2(), and CL_ParseMuzzleFlashPacket().
scr_vrect
vrect_t scr_vrect
Definition at line 105 of file screen.c.
Referenced by SCR_CalcVrect(), and V_RenderView().
snd
snd_params_t snd
Definition at line 657 of file parse.c.
Referenced by CL_ParseStartSoundPacket(), and S_ParseStartSound().
te
tent_params_t te
Definition at line 655 of file parse.c.
Referenced by CL_OldRailTrail(), CL_ParseBeam(), CL_ParseLaser(), CL_ParseNuke(), CL_ParsePlayerBeam(), CL_ParseSteam(), CL_ParseTEnt(), CL_ParseTEntPacket(), CL_ParseWidow(), CL_PlainExplosion(), CL_RailCore(), CL_RailLights(), CL_RailSpiral(), CL_WidowSplash(), and dirtoangles().