Quake II RTX doxygen: C:/entry/dev/Q2RTX/src/refresh/vkpt/precomputed_sky.h File Reference
precomputed_sky.h File Reference
Classes
struct AtmosphereParameters
Enumerations
enum SkyPreset { SKY_NONE, SKY_EARTH, SKY_STROGGOS }
Functions
VkResult SkyInitializeDataGPU ()
void SkyReleaseDataGPU ()
void UpdateTerrainShadowMapView (vec3_t forward)
VkResult SkyLoadScatterParameters (SkyPreset preset)
VkDescriptorSetLayout * SkyGetDescriptorLayout ()
VkDescriptorSet SkyGetDescriptorSet ()
void RecordCommandBufferShadowmap (VkCommandBuffer cmd_buf)
void InitializeShadowmapResources ()
void ReleaseShadowmapResources ()
Variables
static const uint32_t ShadowmapSize = 2048
static const uint32_t ShadowmapHeightmapSize = 4096
static const uint32_t ShadowmapGridSize = 1024
static const float ShadowmapWorldSize = 30.0f
static const float ShadowmapWorldElevation = 3.0f
Enumeration Type Documentation
SkyPreset
enum SkyPreset
Enumerator
SKY_NONE
SKY_EARTH
SKY_STROGGOS
Definition at line 28 of file precomputed_sky.h.
 {
     SKY_NONE,
     SKY_EARTH,
     SKY_STROGGOS
 } SkyPreset;
Function Documentation
InitializeShadowmapResources()
void InitializeShadowmapResources ()
Definition at line 975 of file precomputed_sky.c.
 {
     CreateShadowMap(&ShadowmapData);
     ShadowmapGrid = FillVertexAndIndexBuffers("env/terrain_heightmap.dds", ShadowmapGridSize, ShadowmapWorldSize);
 }
Referenced by vkpt_physical_sky_initialize().
RecordCommandBufferShadowmap()
void RecordCommandBufferShadowmap (VkCommandBuffer cmd_buf)
Definition at line 991 of file precomputed_sky.c.
 {
     IMAGE_BARRIER(cmd_buf,
         .image = ShadowmapData.TargetTexture,
         .subresourceRange = { .aspectMask = VK_IMAGE_ASPECT_DEPTH_BIT, .levelCount = 1, .layerCount = 1 },
         .srcAccessMask = VK_ACCESS_SHADER_READ_BIT,
         .dstAccessMask = VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT | VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT,
         .oldLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
         .newLayout = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL,
     );
     VkClearValue clearValues;
     clearValues.depthStencil.depth = 1.0f;
     clearValues.depthStencil.stencil = 0;
     VkRenderPassBeginInfo renderPassBeginInfo =
     {
         .sType = VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO,
         .renderPass = render_pass_smap,
         .framebuffer = ShadowmapData.FrameBuffer,
         .renderArea.extent.width = ShadowmapData.Width,
         .renderArea.extent.height = ShadowmapData.Height,
         .clearValueCount = 1,
         .pClearValues = &clearValues,
     };
     vkCmdBeginRenderPass(cmd_buf, &renderPassBeginInfo, VK_SUBPASS_CONTENTS_INLINE);
     vkCmdBindPipeline(cmd_buf, VK_PIPELINE_BIND_POINT_GRAPHICS, pipeline_smap);
     VkViewport viewport =
     {
         .width = ShadowmapData.Width,
         .height = ShadowmapData.Height,
         .minDepth = 0,
         .maxDepth = 1.0f,
     };
     vkCmdSetViewport(cmd_buf, 0, 1, &viewport);
     VkRect2D rect2D =
     {
         .extent.width = ShadowmapData.Width,
         .extent.height = ShadowmapData.Height,
         .offset.x = 0,
         .offset.y = 0,
     };
     vkCmdSetScissor(cmd_buf, 0, 1, &rect2D);
     float depthBiasConstant = 0.f;
     float depthBiasSlope = 0.f;
     vkCmdPushConstants(cmd_buf, pipeline_layout_smap, VK_SHADER_STAGE_VERTEX_BIT, 0, sizeof(float) * 16, terrain_shadowmap_viewproj);
     VkDeviceSize offsets[1] = { 0 };
     vkCmdBindVertexBuffers(cmd_buf, 0, 1, &ShadowmapGrid.Vertexes.buffer, offsets);
     vkCmdBindIndexBuffer(cmd_buf, ShadowmapGrid.Indexes.buffer, 0, VK_INDEX_TYPE_UINT32);
     vkCmdDrawIndexed(cmd_buf, ShadowmapGrid.IndexCount, 1, 0, 0, 0);
     vkCmdEndRenderPass(cmd_buf);
     IMAGE_BARRIER(cmd_buf,
         .image = ShadowmapData.TargetTexture,
         .subresourceRange = { .aspectMask = VK_IMAGE_ASPECT_DEPTH_BIT,.levelCount = 1,.layerCount = 1 },
         .srcAccessMask = VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT | VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT,
         .dstAccessMask = VK_ACCESS_SHADER_READ_BIT,
         .oldLayout = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL,
         .newLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
     );
 }
Referenced by vkpt_physical_sky_record_cmd_buffer().
ReleaseShadowmapResources()
void ReleaseShadowmapResources ()
Definition at line 981 of file precomputed_sky.c.
 {
     buffer_destroy(&ShadowmapGrid.Indexes);
     buffer_destroy(&ShadowmapGrid.Vertexes);
     memset(&ShadowmapGrid, 0, sizeof(ShadowmapGrid));
     ReleaseShadowmap(&ShadowmapData);
 }
Referenced by vkpt_physical_sky_destroy().
SkyGetDescriptorLayout()
VkDescriptorSetLayout* SkyGetDescriptorLayout ()
Definition at line 356 of file precomputed_sky.c.
 {
     return &uniform_precomputed_descriptor_layout;
 }
Referenced by vkpt_physical_sky_initialize().
SkyGetDescriptorSet()
VkDescriptorSet SkyGetDescriptorSet ()
Definition at line 361 of file precomputed_sky.c.
 {
     return desc_set_precomputed_ubo;
 }
Referenced by vkpt_physical_sky_record_cmd_buffer().
SkyInitializeDataGPU()
VkResult SkyInitializeDataGPU ()
Definition at line 597 of file precomputed_sky.c.
 {
     LoadImageFromDDS("env/clouds.dds", BINDING_OFFSET_SKY_CLOUDS, &SkyClouds, "SkyClouds");
     LoadImageFromDDS("env/terrain_albedo.dds", BINDING_OFFSET_TERRAIN_ALBEDO, &TerrainAlbedo, "SkyGBufferAlbedo");
     LoadImageFromDDS("env/terrain_normal.dds", BINDING_OFFSET_TERRAIN_NORMALS, &TerrainNormals, "SkyGBufferNormals");
     LoadImageFromDDS("env/terrain_depth.dds", BINDING_OFFSET_TERRAIN_DEPTH, &TerrainDepth, "SkyGBufferDepth");
     vkpt_uniform_precomputed_buffer_create();
     return VK_SUCCESS;
 }
Referenced by vkpt_physical_sky_initialize().
SkyLoadScatterParameters()
VkResult SkyLoadScatterParameters (SkyPreset preset)
Definition at line 565 of file precomputed_sky.c.
 {
     const char* Planet;
     if (preset == SKY_EARTH)
     {
         Planet = "earth";
         Constants = &Params_Earth;
     }
     else if (preset == SKY_STROGGOS)
     {
         Planet = "stroggos";
         Constants = &Params_Stroggos;
     }
     ReleaseInfo(&SkyTransmittance);
     ReleaseInfo(&SkyInscatter);
     ReleaseInfo(&SkyIrradiance);
     char FileBuf[MAX_QPATH];
     Q_snprintf(FileBuf, sizeof(FileBuf), "env/transmittance_%s.dds", Planet);
     LoadImageFromDDS(FileBuf, BINDING_OFFSET_SKY_TRANSMITTANCE, &SkyTransmittance, "SkyTransmittance");
     Q_snprintf(FileBuf, sizeof(FileBuf), "env/inscatter_%s.dds", Planet);
     LoadImageFromDDS(FileBuf, BINDING_OFFSET_SKY_SCATTERING, &SkyInscatter, "SkyInscatter");
     Q_snprintf(FileBuf, sizeof(FileBuf), "env/irradiance_%s.dds", Planet);
     LoadImageFromDDS(FileBuf, BINDING_OFFSET_SKY_IRRADIANCE, &SkyIrradiance, "SkyIrradiance");
     vkpt_uniform_precomputed_buffer_update();
     return VK_SUCCESS;
 }
Referenced by vkpt_evaluate_sun_light().
SkyReleaseDataGPU()
void SkyReleaseDataGPU ()
Definition at line 610 of file precomputed_sky.c.
 {
     ReleaseInfo(&SkyTransmittance);
     ReleaseInfo(&SkyInscatter);
     ReleaseInfo(&SkyIrradiance);
     ReleaseInfo(&SkyClouds);
     ReleaseInfo(&TerrainAlbedo);
     ReleaseInfo(&TerrainNormals);
     ReleaseInfo(&TerrainDepth);
     vkpt_uniform_precomputed_buffer_destroy();
 }
Referenced by vkpt_physical_sky_destroy().
UpdateTerrainShadowMapView()
void UpdateTerrainShadowMapView (vec3_t forward)
Definition at line 550 of file precomputed_sky.c.
 {
     float Proj[16];
     float View[16];
     float BoundingOffset = ShadowmapWorldSize * 0.75f;
     create_centered_orthographic_matrix(Proj, -BoundingOffset, BoundingOffset, -BoundingOffset, BoundingOffset, -ShadowmapWorldSize * 0.75f, ShadowmapWorldSize * 0.75f);
     vec3_t up = { 0, 0, 1.0f };
     vec3_t origin = { 0.f };
     create_look_at_matrix(View, origin, forward, up);
     mult_matrix_matrix(terrain_shadowmap_viewproj, Proj, View);
 }
Referenced by vkpt_physical_sky_update_ubo().
Variable Documentation
ShadowmapGridSize
const uint32_t ShadowmapGridSize = 1024 static
Definition at line 24 of file precomputed_sky.h.
Referenced by InitializeShadowmapResources().
ShadowmapHeightmapSize
const uint32_t ShadowmapHeightmapSize = 4096 static
Definition at line 23 of file precomputed_sky.h.
ShadowmapSize
const uint32_t ShadowmapSize = 2048 static
Definition at line 22 of file precomputed_sky.h.
Referenced by CreateShadowMap().
ShadowmapWorldElevation
const float ShadowmapWorldElevation = 3.0f static
Definition at line 26 of file precomputed_sky.h.
ShadowmapWorldSize
const float ShadowmapWorldSize = 30.0f static
Definition at line 25 of file precomputed_sky.h.
Referenced by InitializeShadowmapResources(), and UpdateTerrainShadowMapView().