Quake II RTX doxygen: C:/entry/dev/Q2RTX/src/client/locs.c File Reference
locs.c File Reference
#include "client.h"
Classes
struct location_t
Functions
static LIST_DECL (cl_locations)
static location_t * LOC_Alloc (const char *name)
void LOC_LoadLocations (void)
void LOC_FreeLocations (void)
static location_t * LOC_FindClosest (vec3_t pos)
void LOC_AddLocationsToScene (void)
static size_t LOC_Here_m (char *buffer, size_t size)
static size_t LOC_There_m (char *buffer, size_t size)
static void LOC_Add_f (void)
static void LOC_Delete_f (void)
static void LOC_Update_f (void)
static void LOC_Write_f (void)
void LOC_Init (void)
Variables
static cvar_t * loc_draw
static cvar_t * loc_trace
static cvar_t * loc_dist
Function Documentation
LIST_DECL()
static LIST_DECL (cl_locations) static
LOC_Add_f()
static void LOC_Add_f (void) static
Definition at line 268 of file locs.c.
 {
     location_t *loc;
     if (Cmd_Argc() < 2) {
         Com_Printf("Usage: %s <name>\n", Cmd_Argv(0));
         return;
     }
     if (cls.state != ca_active) {
         Com_Printf("Must be in a level.\n");
         return;
     }
     loc = LOC_Alloc(Cmd_Args());
     VectorCopy(cl.playerEntityOrigin, loc->origin);
     List_Append(&cl_locations, &loc->entry);
 }
Referenced by LOC_Init().
LOC_AddLocationsToScene()
void LOC_AddLocationsToScene (void)
Definition at line 177 of file locs.c.
 {
     location_t *loc, *nearest;
     vec3_t dir;
     float dist;
     entity_t ent;
     if (!loc_draw->integer) {
         return;
     }
     memset(&ent, 0, sizeof(ent));
     ent.model = R_RegisterModel("models/items/c_head/tris.md2");
     ent.skin = R_RegisterSkin("models/items/c_head/skin.pcx");
     nearest = LOC_FindClosest(cl.playerEntityOrigin);
     if (!nearest) {
         return;
     }
     LIST_FOR_EACH(location_t, loc, &cl_locations, entry) {
         VectorSubtract(cl.playerEntityOrigin, loc->origin, dir);
         dist = VectorLength(dir);
         if (dist > loc_dist->integer) {
             continue;
         }
         VectorCopy(loc->origin, ent.origin);
         if (loc == nearest) {
             ent.origin[2] += 10.0f * sin(cl.time * 0.01f);
             V_AddLight(loc->origin, 200, 1, 1, 1);
         }
         V_AddEntity(&ent);
     }
 }
Referenced by CL_AddEntities().
LOC_Alloc()
static location_t* LOC_Alloc (const char * name) static
Definition at line 42 of file locs.c.
 {
     location_t *loc;
     size_t len;
     len = strlen(name);
     loc = Z_Malloc(sizeof(*loc) + len);
     memcpy(loc->name, name, len + 1);
     return loc;
 }
Referenced by LOC_Add_f(), LOC_LoadLocations(), and LOC_Update_f().
LOC_Delete_f()
static void LOC_Delete_f (void) static
Definition at line 287 of file locs.c.
 {
     location_t *loc;
     if (cls.state != ca_active) {
         Com_Printf("Must be in a level.\n");
         return;
     }
     loc = LOC_FindClosest(cl.playerEntityOrigin);
     if (!loc) {
         Com_Printf("No closest location.\n");
         return;
     }
     List_Remove(&loc->entry);
     Z_Free(loc);
 }
Referenced by LOC_Init().
LOC_FindClosest()
static location_t* LOC_FindClosest (vec3_t pos) static
Definition at line 138 of file locs.c.
 {
     location_t *loc, *nearest;
     vec3_t dir;
     float dist, minDist;
     trace_t trace;
     minDist = 99999;
     nearest = NULL;
     LIST_FOR_EACH(location_t, loc, &cl_locations, entry) {
         VectorSubtract(pos, loc->origin, dir);
         dist = VectorLength(dir);
         if (dist > loc_dist->value) {
             continue;
         }
         if (loc_trace->integer) {
             CM_BoxTrace(&trace, pos, loc->origin, vec3_origin, vec3_origin,
                         cl.bsp->nodes, MASK_SOLID);
             if (trace.fraction != 1.0f) {
                 continue;
             }
         }
         if (dist < minDist) {
             minDist = dist;
             nearest = loc;
         }
     }
     return nearest;
 }
Referenced by LOC_AddLocationsToScene(), LOC_Delete_f(), LOC_Here_m(), LOC_There_m(), and LOC_Update_f().
LOC_FreeLocations()
void LOC_FreeLocations (void)
Definition at line 122 of file locs.c.
 {
     location_t *loc, *next;
     LIST_FOR_EACH_SAFE(location_t, loc, next, &cl_locations, entry) {
         Z_Free(loc);
     }
     List_Init(&cl_locations);
 }
Referenced by CL_ClearState().
LOC_Here_m()
static size_t LOC_Here_m (char * buffer, size_t size) static
Definition at line 221 of file locs.c.
 {
     location_t *loc;
     size_t ret;
     ret = Q_strlcpy(buffer, "unknown", size);
     if (cls.state != ca_active) {
         return ret;
     }
     loc = LOC_FindClosest(cl.playerEntityOrigin);
     if (loc) {
         ret = Q_strlcpy(buffer, loc->name, size);
     }
     return ret;
 }
Referenced by LOC_Init().
LOC_Init()
void LOC_Init (void)
Definition at line 376 of file locs.c.
 {
     loc_trace = Cvar_Get("loc_trace", "0", 0);
     loc_draw = Cvar_Get("loc_draw", "0", 0);
     loc_dist = Cvar_Get("loc_dist", "500", 0);
     Cmd_AddMacro("loc_here", LOC_Here_m);
     Cmd_AddMacro("loc_there", LOC_There_m);
     Cmd_AddCommand("loc_add", LOC_Add_f);
     Cmd_AddCommand("loc_delete", LOC_Delete_f);
     Cmd_AddCommand("loc_update", LOC_Update_f);
     Cmd_AddCommand("loc_write", LOC_Write_f);
 }
Referenced by CL_InitLocal().
LOC_LoadLocations()
void LOC_LoadLocations (void)
Definition at line 59 of file locs.c.
 {
     char path[MAX_OSPATH];
     char *buffer, *s, *p;
     int line, count;
     location_t *loc;
     int argc;
     qerror_t ret;
     // load from main directory
     Q_concat(path, sizeof(path), "locs/", cl.mapname, ".loc", NULL);
     ret = FS_LoadFile(path, (void **)&buffer);
     if (!buffer) {
         if (ret != Q_ERR_NOENT) {
             Com_EPrintf("Couldn't load %s: %s\n", path, Q_ErrorString(ret));
         }
         return;
     }
     s = buffer;
     line = count = 0;
     while (*s) {
         p = strchr(s, '\n');
         if (p) {
             *p = 0;
         }
         Cmd_TokenizeString(s, qfalse);
         line++;
         argc = Cmd_Argc();
         if (argc) {
             if (argc < 4) {
                 Com_WPrintf("Line %d is incomplete in %s\n", line, path);
             } else {
                 loc = LOC_Alloc(Cmd_RawArgsFrom(3));
                 loc->origin[0] = atof(Cmd_Argv(0)) * 0.125f;
                 loc->origin[1] = atof(Cmd_Argv(1)) * 0.125f;
                 loc->origin[2] = atof(Cmd_Argv(2)) * 0.125f;
                 List_Append(&cl_locations, &loc->entry);
                 count++;
             }
         }
         if (!p) {
             break;
         }
         s = p + 1;
     }
     Com_DPrintf("Loaded %d location%s from %s\n",
                 count, count == 1 ? "" : "s", path);
     FS_FreeFile(buffer);
 }
Referenced by CL_Begin().
LOC_There_m()
static size_t LOC_There_m (char * buffer, size_t size) static
Definition at line 244 of file locs.c.
 {
     location_t *loc;
     vec3_t pos;
     trace_t trace;
     int ret;
     ret = Q_strlcpy(buffer, "unknown", size);
     if (cls.state != ca_active) {
         return ret;
     }
     VectorMA(cl.playerEntityOrigin, 8192, cl.v_forward, pos);
     CM_BoxTrace(&trace, cl.playerEntityOrigin, pos, vec3_origin, vec3_origin,
                 cl.bsp->nodes, MASK_SOLID);
     loc = LOC_FindClosest(trace.endpos);
     if (loc) {
         ret = Q_strlcpy(buffer, loc->name, size);
     }
     return ret;
 }
Referenced by LOC_Init().
LOC_Update_f()
static void LOC_Update_f (void) static
Definition at line 306 of file locs.c.
 {
     location_t *oldloc, *newloc;
     if (Cmd_Argc() < 2) {
         Com_Printf("Usage: %s <name>\n", Cmd_Argv(0));
         return;
     }
     if (cls.state != ca_active) {
         Com_Printf("Must be in a level.\n");
         return;
     }
     oldloc = LOC_FindClosest(cl.playerEntityOrigin);
     if (!oldloc) {
         Com_Printf("No closest location.\n");
         return;
     }
     newloc = LOC_Alloc(Cmd_Args());
     VectorCopy(oldloc->origin, newloc->origin);
     List_Link(oldloc->entry.prev, oldloc->entry.next, &newloc->entry);
     Z_Free(oldloc);
 }
Referenced by LOC_Init().
LOC_Write_f()
static void LOC_Write_f (void) static
Definition at line 332 of file locs.c.
 {
     char buffer[MAX_OSPATH];
     location_t *loc;
     qhandle_t f;
     int count;
     if (cls.state != ca_active) {
         Com_Printf("Must be in a level.\n");
         return;
     }
     if (LIST_EMPTY(&cl_locations)) {
         Com_Printf("No locations to write.\n");
         return;
     }
     f = FS_EasyOpenFile(buffer, sizeof(buffer), FS_MODE_WRITE | FS_FLAG_TEXT,
                         "locs/", cl.mapname, ".loc");
     if (!f) {
         return;
     }
     count = 0;
     LIST_FOR_EACH(location_t, loc, &cl_locations, entry) {
         FS_FPrintf(f, "%d %d %d %s\n",
                    (int)(loc->origin[0] * 8),
                    (int)(loc->origin[1] * 8),
                    (int)(loc->origin[2] * 8),
                    loc->name);
         count++;
     }
     Com_Printf("Wrote %d location%s to %s\n",
                count, count == 1 ? "" : "s", buffer);
     FS_FCloseFile(f);
 }
Referenced by LOC_Init().
Variable Documentation
loc_dist
cvar_t* loc_dist static
Definition at line 35 of file locs.c.
Referenced by LOC_AddLocationsToScene(), LOC_FindClosest(), and LOC_Init().
loc_draw
cvar_t* loc_draw static
Definition at line 33 of file locs.c.
Referenced by LOC_AddLocationsToScene(), and LOC_Init().
loc_trace
cvar_t* loc_trace static
Definition at line 34 of file locs.c.
Referenced by LOC_FindClosest(), and LOC_Init().